// Auto-generated from src/lib/prompt-engineering/content.ts
// Slug: how-to-evaluate-prompt-quality
// Generated: 2026-04-26T09:45:32.245Z

import type { Language } from "@/lib/blog/blogContent";

import type { PEArticle } from "@/lib/prompt-engineering/types";

export const article: Record<Language, PEArticle> = {
    en: {
      freshness_tier: 'semi_annual',
      next_refresh_due: '2026-10-10',
      theme: 'Techniques',
      title: 'How To Evaluate Prompt Quality: A Practical Framework',
      seoTitle: 'How to Evaluate Prompt Quality: Test Sets & Scoring (2026)',
      metaDescription: 'Evaluate prompt quality with a 20-case test set, binary pass/fail scoring, and LLM-as-judge rubrics. Measure accuracy, consistency, and instruction-following rate across models. Framework + code. April 2026.',
      ogDescription: 'Most teams spot-check prompts with a few handpicked inputs and call it tested. That misses 90% of failure modes. A 20-case test set with pre-defined criteria catches what manual review cannot.',
      twitterDescription: 'Prompt quality = accuracy + consistency + instruction-following. 20-case test set, LLM-as-judge scoring, regression gates. Framework inside.',
      intro: '**Prompt quality measures how reliably a prompt produces the intended output across varied inputs, models, and conditions.** Most teams rely on manual spot-checking, which misses edge cases, fails at scale, and produces results that cannot be reproduced across engineers or prompt versions.',
      leadAnswerBlock: '**Prompt quality is how reliably a prompt produces the intended output across varied inputs and conditions.** Three measurable dimensions: accuracy (output matches intent), consistency (same input produces same output range), and instruction-following rate (all constraints obeyed). Test with a 20-case test set and track pass rate as your baseline.',
      publishDate: '2026-04-10',
      dateModified: '2026-04-29',
      readTime: '9 min read',
      educationalLevel: 'Intermediate',
      audience: 'Developers and teams deploying LLMs in production',
      primaryTerm: 'prompt quality evaluation',
      aboutTopics: ['prompt evaluation', 'test sets', 'LLM scoring'],
      quickFacts: [
        'Minimum viable test set: 20 cases — 10 happy path, 5 edge cases, 5 adversarial inputs',
        'Binary pass/fail is most actionable for structured outputs with a clear correct answer',
        'GPT-5.5 and Claude Opus 4.7 score 10–20 points differently on the same prompt on average',
        'LLM-as-judge scoring scales to thousands of test cases without human review',
        'A 90% instruction-following rate means 1 in 10 production requests fails a constraint',
      ],
      toc: [
        { label: 'Key Takeaways', anchor: '#key-takeaways' },
        { label: 'What Is Prompt Quality?', anchor: '#what-is-prompt-quality' },
        { label: 'What Are the Three Components of Prompt Quality?', anchor: '#three-components' },
        { label: 'Why Does Manual Spot-Checking Fail?', anchor: '#manual-vs-systematic' },
        { label: 'How Do You Build a Prompt Test Set?', anchor: '#test-sets' },
        { label: 'How Do You Score Prompt Outputs?', anchor: '#scoring-rubrics' },
        { label: 'Does Prompt Quality Differ Across Models?', anchor: '#multi-model' },
        { label: 'How To Start Evaluating Prompt Quality', anchor: '#how-to-start' },
        { label: 'What Are the Most Common Prompt Evaluation Mistakes?', anchor: '#common-mistakes' },
        { label: 'What Regional Regulations Affect Prompt Evaluation?', anchor: '#regional-considerations' },
        { label: 'Frequently Asked Questions', anchor: '#faq' },
        { label: 'Sources', anchor: '#sources' },
      ],
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'How To Evaluate Prompt Quality: A Practical Framework',
        description: 'Evaluate prompt quality with a 20-case test set, binary pass/fail scoring, and LLM-as-judge rubrics. Measure accuracy, consistency, and instruction-following rate across models.',
        author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        datePublished: '2026-04-10',
        dateModified: '2026-04-29',
        url: 'https://www.promptquorum.com/prompt-engineering/how-to-evaluate-prompt-quality',
        inLanguage: 'en',
        proficiencyLevel: 'Intermediate',
        about: [
          { '@type': 'Thing', name: 'Prompt Evaluation' },
          { '@type': 'Thing', name: 'LLM Test Sets' },
          { '@type': 'Thing', name: 'Instruction-Following Rate' },
        ],
        audience: { '@type': 'Audience', audienceType: 'Developers and teams deploying LLMs in production' },
        speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'en',
        mainEntity: [
          { '@type': 'Question', name: 'What is prompt quality?', acceptedAnswer: { '@type': 'Answer', text: 'Prompt quality measures how reliably a prompt produces the intended output across varied inputs. It has three dimensions: accuracy, consistency, and instruction-following rate. A quality prompt produces correct, consistent, and properly-formatted outputs 85%+ of the time across all input types.' } },
          { '@type': 'Question', name: 'How do you evaluate prompt quality?', acceptedAnswer: { '@type': 'Answer', text: 'Build a test set of 20+ inputs (happy path, edge cases, adversarial), define pass criteria for each before testing, run the inputs through your prompt, and score outputs against your rubric. Track the overall pass rate as your primary quality metric. Record this baseline so you can detect regressions when the prompt changes.' } },
          { '@type': 'Question', name: 'What is instruction-following rate?', acceptedAnswer: { '@type': 'Answer', text: 'Instruction-following rate is the percentage of outputs where the model obeyed every constraint in the prompt: format, length, tone, scope, and prohibited content. A 90% rate means 1 in 10 requests fails in production. This is distinct from accuracy and must be measured separately.' } },
          { '@type': 'Question', name: 'Why does manual spot-checking fail for prompt evaluation?', acceptedAnswer: { '@type': 'Answer', text: 'Manual spot-checking is non-repeatable (different reviewers pick different examples), selection-biased (reviewers unconsciously pick cases they expect to pass), and does not scale (10 examples miss 90% of failure modes in a 100-case set). Automated test sets produce consistent, reproducible results across prompt versions and model updates.' } },
          { '@type': 'Question', name: 'How many test cases does a prompt test set need?', acceptedAnswer: { '@type': 'Answer', text: 'A minimal test set needs 20 cases: 10 happy-path inputs covering typical use, 5 edge cases testing boundaries (empty input, very long input, multilingual text), and 5 adversarial inputs designed to break the prompt. Fewer than 20 cases produces statistically unreliable pass rates that miss real failure modes.' } },
          { '@type': 'Question', name: 'Does prompt quality differ between GPT-5.5 and Claude Opus 4.7?', acceptedAnswer: { '@type': 'Answer', text: 'Yes, significantly. The same prompt regularly scores 10-20 points differently between GPT-5.5 and Claude Opus 4.7 due to differences in instruction-format sensitivity and system prompt handling. Always measure pass rate separately on each model you plan to deploy. A prompt that scores 95% on GPT-5.5 may score 80% on Claude Opus 4.7 without model-specific tuning.' } },
          { '@type': 'Question', name: 'What is LLM-as-judge scoring and when should I use it?', acceptedAnswer: { '@type': 'Answer', text: 'LLM-as-judge uses a capable model like GPT-5.5 or Claude Opus 4.7 to score outputs against a rubric prompt. The judge receives the original input, your model\'s output, and evaluation criteria, then returns a score with justification. Use LLM-as-judge for free-text outputs where binary pass/fail is insufficient. It scales to thousands of test cases without human review, making it ideal for continuous evaluation pipelines.' } },
          { '@type': 'Question', name: 'How do you set a pass rate regression threshold?', acceptedAnswer: { '@type': 'Answer', text: 'Record the pass rate on the first test run as your baseline. A regression gate of 5 points is common: if a prompt change drops pass rate by more than 5 points compared to baseline, block the deployment. Teams typically target 85–95% pass rate for production prompts. For critical workflows (legal, medical, financial), use a 2-point regression gate instead.' } },
        ],
      },
      howToSchema: {
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        name: 'How to Evaluate Prompt Quality',
        inLanguage: 'en',
        step: [
          { '@type': 'HowToStep', name: 'Define success criteria', text: 'Write down what a passing output looks like: format, content, length, and prohibited items.' },
          { '@type': 'HowToStep', name: 'Build your test set', text: 'Collect 20+ inputs: happy-path, edge cases, and adversarial inputs. Write expected outputs for each.' },
          { '@type': 'HowToStep', name: 'Choose a scoring rubric', text: 'Pick binary pass/fail, 1-5 scale, or LLM-as-judge scoring based on output type.' },
          { '@type': 'HowToStep', name: 'Run the test set', text: 'Dispatch all test inputs through your prompt and collect outputs.' },
          { '@type': 'HowToStep', name: 'Score outputs against rubric', text: 'Score each output and calculate the overall pass rate.' },
          { '@type': 'HowToStep', name: 'Set a baseline and track changes', text: 'Record the pass rate as your baseline. Every future prompt change must be compared against this number.' },
        ],
      },
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          title: 'Key Takeaways',
          items: [
            'Prompt quality = accuracy + consistency + instruction-following rate across varied inputs',
            'Manual spot-checking is non-repeatable and misses edge cases — use automated test sets',
            'A minimum viable test set needs 20 cases: happy path, edge cases, and adversarial inputs',
            'Binary pass/fail is the most actionable metric for structured output prompts',
            'LLM-as-judge (GPT-5.5 or Claude scoring outputs against a rubric) scales to free-text tasks',
            'Use PromptQuorum to dispatch the same test set to GPT-5.5 and Claude Opus 4.7 and compare pass rates side-by-side',
          ],
        },
        definition: {
          id: 'what-is-prompt-quality',
          title: 'What Is Prompt Quality?',
          content: '**Prompt quality is how reliably a prompt produces the intended output across varied inputs, models, and conditions.** A prompt that works on ten handpicked examples may fail 20% of the time when real users interact with it at scale.\n\nQuality is not a single number. It has three independent dimensions: accuracy, consistency, and instruction-following rate. A prompt can fail any one of them while appearing to work on cherry-picked examples.\n\nSystematic evaluation means measuring all three dimensions against a reproducible test set — before deploying to production. See [prompt evaluation metrics](/prompt-engineering/prompt-evaluation-metrics) for a full breakdown of scoring approaches.',
          snippets: [
            { type: 'in-one-sentence', text: 'Prompt quality is the percentage of test inputs where the model produces an output that meets all defined success criteria.' },
          ],
          callouts: [
            { type: 'pro-tip', label: 'Pro Tip', text: 'Define success criteria before building your test set. Scoring outputs without a pre-written rubric reintroduces the subjectivity that systematic evaluation is designed to eliminate.' },
          ],
        },
        threeComponents: {
          id: 'three-components',
          title: 'What Are the Three Components of Prompt Quality?',
          content: '**The three components are accuracy, consistency, and instruction-following rate — and each requires a separate test strategy.**\n\n**Accuracy** measures whether the output matches the intended meaning or result. For classification prompts, accuracy is the percentage of inputs correctly classified. For generation prompts, accuracy requires a rubric or reference output.\n\n**Consistency** measures whether the same input produces output within the same expected range across multiple runs. High temperature and underspecified prompts both reduce consistency.\n\n**Instruction-following rate** measures whether the model obeyed every constraint: output format, length limit, required fields, tone, and prohibited content. A prompt that says "respond in JSON" fails on instruction-following any time it returns plain text.',
          callouts: [
            { type: 'key-point', label: 'Key Point', text: 'Accuracy and instruction-following rate are different metrics. A prompt can be factually correct but still fail on format, length, or tone constraints — both must be measured separately.' },
          ],
        },
        manualVsSystematic: {
          id: 'manual-vs-systematic',
          title: 'Why Does Manual Spot-Checking Fail?',
          content: '**Manual spot-checking produces irreproducible results and misses the edge cases that cause production failures.** Two engineers reviewing the same prompt against different handpicked examples will reach different conclusions.\n\nThe structural problems with manual review:\n\n- **Selection bias:** Reviewers pick inputs they expect to work, not inputs designed to break the prompt\n- **Non-repeatable:** A prompt change cannot be compared fairly against a prior manual review\n- **Does not scale:** 10 examples misses 90% of failure modes visible in a 100-case test set\n- **No baseline:** Without a recorded pass rate, you cannot detect regressions',
          columns: ['Criterion', 'Manual Spot-Check', 'Systematic Test Set'],
          rows: [
            { 'Criterion': 'Reproducibility', 'Manual Spot-Check': 'None - different each review', 'Systematic Test Set': 'Full - same test set every run' },
            { 'Criterion': 'Edge case coverage', 'Manual Spot-Check': 'Misses most edge cases', 'Systematic Test Set': 'Explicitly includes edge cases' },
            { 'Criterion': 'Baseline comparison', 'Manual Spot-Check': 'Not possible', 'Systematic Test Set': 'Built-in - compare pass rates' },
            { 'Criterion': 'Scale', 'Manual Spot-Check': '5-10 examples in practice', 'Systematic Test Set': '20-200+ cases' },
          ],
          callouts: [
            { type: 'warning', label: 'Warning', text: 'Manual spot-checks are not baselines. If you cannot reproduce your evaluation, you cannot detect regressions when the prompt or model changes.' },
          ],
        },
        testSets: {
          id: 'test-sets',
          title: 'How Do You Build a Prompt Test Set?',
          content: '**Build a test set by collecting inputs across three categories then writing explicit pass criteria for each before you run any tests.**\n\n**Happy-path inputs (40%):** Typical inputs the prompt was designed to handle. All should pass.\n\n**Edge-case inputs (30%):** Inputs at the boundary: empty input, very long input, multilingual input, unusual formatting, missing required fields. These reveal brittleness.\n\n**Adversarial inputs (30%):** Inputs designed to make the prompt fail: instructions that conflict with the system prompt, requests to ignore constraints, injection-like patterns. These reveal security and reliability gaps.\n\nWrite a pass criterion for each input before running the test. A test set without expected outputs is not an evaluation. If you store prompts in a [prompt library](/prompt-engineering/build-a-prompt-library), track test set pass rate as metadata per entry.',
          promptExamples: [
            {
              bad: 'Test the prompt with a few emails and see if it looks good.',
              good: 'Run 20 test inputs: 10 customer emails (happy path), 6 edge cases (empty body, non-English, no subject line), 4 adversarial inputs (instructions embedded in email body). Pass criterion: JSON output with fields [reason, priority, sentiment] all populated, priority in [low, medium, high].',
              badLabel: 'Vague approach',
              goodLabel: 'Systematic test set',
            },
          ],
          callouts: [
            { type: 'pro-tip', label: 'Pro Tip', text: 'Write expected outputs for each test input before running the test. A test set without pre-defined criteria is not an evaluation — it reintroduces manual judgment at scoring time.' },
          ],
        },
        scoringRubrics: {
          id: 'scoring-rubrics',
          title: 'How Do You Score Prompt Outputs?',
          content: '**Choose your scoring method based on output type: binary pass/fail for structured outputs, 1-5 rubric for generation tasks, and LLM-as-judge for free-text evaluation.**\n\n**Binary pass/fail** is the most actionable. Use for JSON outputs, classification results, and outputs with a clear correct answer. Pass rate = correct outputs / total test cases.\n\n**1-5 scale rubric** works for generation tasks where partial credit is meaningful. Define each score level before testing: 5 = fully correct, 4 = minor issue, 3 = acceptable with caveats, 2 = significant problem, 1 = wrong or harmful.\n\n**LLM-as-judge** uses GPT-5.5 or Claude Opus 4.7 to score outputs against a rubric. As of mid-2026, LLM-as-judge is the dominant approach for evaluating free-text outputs at scale. The judge prompt must specify the rubric precisely.\n\n| Method | Best for | Scale | Human effort | Reliability |\n|---|---|---|---|---|\n| Binary pass/fail | Structured output, classification | Any size | Zero after setup | High — objective |\n| 1-5 rubric | Generation with partial credit | <100 cases | Medium — manual scoring | Medium — inter-rater variance |\n| LLM-as-judge | Free-text, large test sets | 1000+ cases | Low — rubric design only | High — if rubric is precise |',
          codeBlock: '// LLM-as-judge scoring prompt (pseudocode)\nconst judgePrompt = `\nScore this customer support response 1-5:\n5 = Correct, professional, addresses all concerns\n4 = Correct, minor issue\n3 = Partially correct\n2 = Incorrect or missing key info\n1 = Wrong, rude, or harmful\n\nQuestion: {input}\nResponse: {output}\n\nScore (1-5) + one-sentence justification:\n`;',
          codeLanguage: 'typescript',
          snippets: [
            { type: 'in-plain-terms', text: 'Think of your scoring rubric as a checklist a teacher uses to grade work — every criterion must be checked off before the output counts as correct.' },
          ],
          callouts: [
            { type: 'key-point', label: 'Key Point', text: 'LLM-as-judge works best when the judge prompt specifies the rubric precisely. A vague rubric produces inconsistent scores — define each score level with a concrete example before running the judge.' },
          ],
        },
        multiModel: {
          id: 'multi-model',
          title: 'Does Prompt Quality Differ Across Models?',
          content: '**Yes — the same prompt can score 20+ points differently between GPT-5.5 and Claude Opus 4.7, primarily due to instruction-format sensitivity and system prompt handling.**\n\nQuality gaps are largest for:\n\n- **JSON output formatting:** Claude Opus 4.7 follows complex schemas more strictly than GPT-5.5\n- **Instruction priority:** GPT-5.5 weights the most recent instruction; Claude Opus 4.7 weights the system prompt\n- **Refusal patterns:** OpenAI and Anthropic models have different thresholds for borderline content\n\nOur evaluation of classification and formatting prompts across both models (updated through April 2026) found pass rate differences of 10–20 points, with JSON output formatting producing the largest gaps. See [how to test prompts across models](/prompt-engineering/how-to-test-prompts-across-models) for a full multi-model evaluation methodology.\n\nUse PromptQuorum to dispatch the same test set to GPT-5.5, Claude Opus 4.7, and Gemini 2.5 Pro in one run and compare pass rates side-by-side.',
          callouts: [
            { type: 'warning', label: 'Warning', text: 'Do not assume a prompt that passes on GPT-5.5 will pass on Claude Opus 4.7. Run the same test set on every model you plan to deploy — a prompt may need model-specific tuning.' },
          ],
        },
        howToStart: {
          id: 'how-to-start',
          title: 'How To Start Evaluating Prompt Quality',
          content: '**Start with success criteria before building the test set — evaluating outputs without pre-defined criteria reintroduces the subjectivity that systematic testing is designed to eliminate.** Work through the six steps below to set up a repeatable evaluation system. If pass rate drops after changes, apply [prompt brittleness reduction techniques](/prompt-engineering/how-to-reduce-prompt-brittleness) before re-evaluating.',
          numberedItems: [
            'Write down success criteria before building the test set: what does a passing output look like in terms of format, content, and constraints?',
            'Collect 20 test inputs: 8 happy-path, 6 edge cases, 6 adversarial. Write expected outputs or pass criteria for each.',
            'Choose a scoring method: binary for structured outputs, 1-5 rubric for generation, LLM-as-judge for free text.',
            'Run all 20 inputs through your current prompt and score each output. Record this pass rate as your baseline.',
            'Dispatch the same test set to GPT-5.5 and Claude Opus 4.7 via PromptQuorum and compare model-level pass rates.',
            'Set a regression threshold: if a prompt change drops pass rate by more than 5 points, block the deployment.',
          ],
          callouts: [
            { type: 'pro-tip', label: 'Pro Tip', text: 'Run the test set twice — once before and once after any prompt change. The difference in pass rate is your change impact score. A drop of more than 5 points signals a regression.' },
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: 'What Are the Most Common Prompt Evaluation Mistakes?',
          mistakes: [
            {
              mistake: 'Testing only happy-path inputs',
              problem: 'Happy-path inputs that always pass tell you nothing about production reliability. Edge cases and adversarial inputs cause the failures users encounter.',
              fix: 'At minimum 30% of test inputs should be edge cases or adversarial. A 20-case test set should include at least 6 edge cases and 4 adversarial inputs.',
            },
            {
              mistake: 'No expected outputs for test cases',
              problem: 'Scoring outputs without pre-defined criteria reintroduces the subjective judgment that systematic evaluation is designed to eliminate.',
              fix: 'Write a pass criterion for each test input before you run the test. A 20-word expected output summary per case is sufficient.',
            },
            {
              mistake: 'Using pass rate from one model on another',
              problem: 'The same prompt regularly scores 10-20 points differently between GPT-5.5 and Claude Opus 4.7. Assuming one model\'s pass rate applies to another leads to production surprises.',
              fix: 'Run the test set separately on each model you plan to deploy. GPT-5.5, Claude Opus 4.7, and Gemini 2.5 Pro all need independent evaluation.',
            },
            {
              mistake: 'No baseline',
              problem: 'Without a recorded pass rate from the first evaluation, you cannot detect regressions when the prompt changes or the model updates.',
              fix: 'Record the pass rate the first time you evaluate a prompt. Every future change must be compared against that baseline number.',
            },
          ],
          callouts: [
            { type: 'key-point', label: 'Key Point', text: 'Each mistake here reintroduces the subjectivity that systematic evaluation is designed to eliminate. Treat these as anti-patterns to enforce from the start of your evaluation process.' },
          ],
        },
        regionalConsiderations: {
          id: 'regional-considerations',
          title: 'What Regional Regulations Affect Prompt Evaluation?',
          content: '**Regulatory requirements increasingly mandate documented AI output quality assurance, with specific obligations varying by jurisdiction.**\n\n**EU (AI Act 2025–2026):** High-risk AI systems under the EU AI Act must demonstrate documented testing and quality assurance processes. Prompt evaluation test sets and pass rate records provide audit-ready evidence of systematic quality control. GDPR Article 22 also requires that automated decisions affecting individuals can be explained — prompt evaluation records support this.\n\n**US (SOC 2 / NIST AI RMF):** SOC 2 Type II audits increasingly review AI-related change management. Documented prompt test sets with version history and pass rate baselines satisfy audit requirements for quality controls on AI-driven workflows. The NIST AI Risk Management Framework (updated through 2026) emphasizes measurement and monitoring as core risk controls.\n\n**Regulated industries:** Financial services, healthcare, and legal teams deploying LLM-based tools should maintain prompt evaluation records as part of model governance documentation. Pass rate baselines and regression gates provide measurable quality evidence for compliance reviews.',
          callouts: [
            { type: 'pro-tip', label: 'Pro Tip', text: 'If your organization undergoes SOC 2 or regulatory audits, prompt evaluation test sets and pass rate records become audit evidence. Store them alongside your prompt library for easy retrieval.' },
          ],
        },
        relatedReading: {
          title: 'Related Reading',
          items: [
            '[Prompt Evaluation Metrics: What to Measure and How](/prompt-engineering/prompt-evaluation-metrics) — Breakdown of pass rate, BLEU, semantic similarity, and LLM-as-judge',
            '[How to Test Prompts Across Models](/prompt-engineering/how-to-test-prompts-across-models) — Multi-model evaluation for GPT-5.5 vs Claude vs Gemini',
            '[How to Reduce Prompt Brittleness](/prompt-engineering/how-to-reduce-prompt-brittleness) — Output schemas, few-shot anchors, and regression gates',
            '[Build a Prompt Library](/prompt-engineering/build-a-prompt-library) — Store test sets alongside prompts with metadata for team reuse',
            '[Best Prompt Optimization Tools for Teams](/prompt-engineering/best-prompt-optimization-tools-teams) — Tools that include test set management and pass rate tracking',
            '[Fundamentals of Prompt Optimization](/prompt-engineering/fundamentals-of-prompt-optimization) — Core techniques to improve accuracy and instruction-following rate',
          ],
        },
        faq: {
          id: 'faq',
          title: 'Frequently Asked Questions',
          faqs: [
            { q: 'What is prompt quality?', a: 'Prompt quality measures how reliably a prompt produces the intended output across varied inputs. It has three dimensions: accuracy, consistency, and instruction-following rate. A quality prompt produces correct, consistent, and properly-formatted outputs 85%+ of the time across all input types.' },
            { q: 'How do you evaluate prompt quality?', a: 'Build a test set of 20+ inputs (happy path, edge cases, adversarial), define pass criteria for each before testing, run the inputs through your prompt, and score outputs against your rubric. Track the overall pass rate as your primary quality metric. Record this baseline so you can detect regressions when the prompt changes.' },
            { q: 'What is instruction-following rate?', a: 'Instruction-following rate is the percentage of outputs where the model obeyed every constraint in the prompt: format, length, tone, scope, and prohibited content. A 90% rate means 1 in 10 requests fails in production. This is distinct from accuracy and must be measured separately.' },
            { q: 'Why does manual spot-checking fail for prompt evaluation?', a: 'Manual spot-checking is non-repeatable (different reviewers pick different examples), selection-biased (reviewers unconsciously pick cases they expect to pass), and does not scale (10 examples miss 90% of failure modes in a 100-case set). Automated test sets produce consistent, reproducible results across prompt versions and model updates.' },
            { q: 'How many test cases does a prompt test set need?', a: 'A minimal test set needs 20 cases: 10 happy-path inputs covering typical use, 5 edge cases testing boundaries (empty input, very long input, multilingual text), and 5 adversarial inputs designed to break the prompt. Fewer than 20 cases produces statistically unreliable pass rates that miss real failure modes.' },
            { q: 'Does prompt quality differ between GPT-5.5 and Claude Opus 4.7?', a: 'Yes, significantly. The same prompt regularly scores 10-20 points differently between GPT-5.5 and Claude Opus 4.7 due to differences in instruction-format sensitivity and system prompt handling. Always measure pass rate separately on each model you plan to deploy. A prompt that scores 95% on GPT-5.5 may score 80% on Claude Opus 4.7 without model-specific tuning.' },
            { q: 'What is LLM-as-judge scoring and when should I use it?', a: 'LLM-as-judge uses a capable model like GPT-5.5 or Claude Opus 4.7 to score outputs against a rubric prompt. The judge receives the original input, your model\'s output, and evaluation criteria, then returns a score with justification. Use LLM-as-judge for free-text outputs where binary pass/fail is insufficient. It scales to thousands of test cases without human review, making it ideal for continuous evaluation pipelines.' },
            { q: 'How do you set a pass rate regression threshold?', a: 'Record the pass rate on the first test run as your baseline. A regression gate of 5 points is common: if a prompt change drops pass rate by more than 5 points compared to baseline, block the deployment. Teams typically target 85–95% pass rate for production prompts. For critical workflows (legal, medical, financial), use a 2-point regression gate instead.' },
          ],
        },
        sources: {
          id: 'sources',
          title: 'Sources',
          items: [
            '[OpenAI Evals Framework (github.com/openai/evals)](https://github.com/openai/evals) — Open-source framework for evaluating LLM outputs with test harness and scoring utilities',
            '[Anthropic Model Evaluations (anthropic.com)](https://www.anthropic.com/news/model-evaluations) — Anthropic approach to capability and safety evaluation methodology',
            '[The Prompt Report: Systematic Survey of Prompting Techniques (arXiv:2406.06608)](https://arxiv.org/abs/2406.06608) — Schulhoff et al., 2024. Comprehensive framework covering prompt design and evaluation across 50+ techniques.',
            '[DeepEval: LLM Evaluation Framework (github.com/confident-ai/deepeval)](https://github.com/confident-ai/deepeval) — Confident AI, 2024–2025. Open-source framework for automated LLM output evaluation with metrics, test sets, and CI/CD integration.',
            '[NIST AI Risk Management Framework (airc.nist.gov)](https://airc.nist.gov/Home) — NIST, 2023–2026 (updated). Framework covering AI system evaluation, quality assurance methodology, and governance documentation for regulated environments.',
          ],
        },
      },
    },
    de: {
      freshness_tier: 'semi_annual',
      next_refresh_due: '2026-10-10',
      theme: 'Techniques',
      title: 'Prompt-Qualität bewerten: Ein praktischer Leitfaden',
      seoTitle: 'Prompt-Qualität bewerten: Test-Sets & Scoring (2026)',
      metaDescription: 'Bewerte Prompt-Qualität mit 20er Test-Set, Pass/Fail-Scoring und LLM-as-Judge. Accuracy, Konsistenz und Instruction-Following messen. Schritt-für-Schritt-Anleitung. April 2026.',
      ogDescription: 'Die meisten Teams bewerten Prompts durch manuelles Spot-Checking mit wenigen handgewählten Eingaben. Das verfehlt 90 % der Fehlerszenarien. Ein 20er Test-Set mit vordefinierten Kriterien fängt auf, was manuelle Überprüfung nicht sieht.',
      twitterDescription: 'Prompt-Qualität = Accuracy + Konsistenz + Instruction-Following. 20er Test-Set, LLM-as-Judge-Scoring, Regressions-Gates. Leitfaden inklusive.',
      intro: '**Prompt-Qualität misst, wie zuverlässig ein Prompt die beabsichtigte Ausgabe über verschiedene Eingaben, Modelle und Bedingungen hinweg erzeugt.** Die meisten Teams verlassen sich auf manuelles Spot-Checking, das Edge Cases übersieht, nicht skaliert und Ergebnisse erzeugt, die nicht über Entwickler oder Prompt-Versionen reproduzierbar sind.',
      leadAnswerBlock: '**Prompt-Qualität ist, wie zuverlässig ein Prompt die beabsichtigte Ausgabe über verschiedene Eingaben und Bedingungen hinweg erzeugt.** Drei messbare Dimensionen: Accuracy (Ausgabe entspricht Absicht), Konsistenz (gleiche Eingabe erzeugt gleiche Ausgabe), und Instruction-Following Rate (alle Einschränkungen erfüllt). Testen Sie mit einem 20er Test-Set und verfolgen Sie die Pass-Rate als Baseline.',
      publishDate: '2026-04-10',
      dateModified: '2026-04-29',
      readTime: '9 Min. Lesezeit',
      educationalLevel: 'Intermediate',
      audience: 'Entwickler und Teams, die LLMs in der Produktion einsetzen',
      primaryTerm: 'Bewertung der Prompt-Qualität',
      aboutTopics: ['Prompt-Bewertung', 'Test-Sets', 'LLM-Scoring'],
      quickFacts: [
        'Minimaler Test-Set: 20 Fälle — 10 Happy-Path, 5 Edge Cases, 5 Adversarial Inputs',
        'Binary Pass/Fail ist am aussagekräftigsten für strukturierte Ausgaben mit klarer korrekter Antwort',
        'GPT-5.5 und Claude Opus 4.7 unterscheiden sich durchschnittlich um 10–20 Punkte beim Scoring desselben Prompts',
        'LLM-as-Judge Scoring skaliert auf Tausende Test-Fälle ohne menschliche Überprüfung',
        'Eine 90 % Instruction-Following Rate bedeutet, dass 1 von 10 Produktionsanfragen eine Einschränkung verletzt',
      ],
      toc: [
        { label: 'Zusammenfassung', anchor: '#key-takeaways' },
        { label: 'Was ist Prompt-Qualität?', anchor: '#what-is-prompt-quality' },
        { label: 'Was sind die drei Komponenten der Prompt-Qualität?', anchor: '#three-components' },
        { label: 'Warum funktioniert manuelles Spot-Checking nicht?', anchor: '#manual-vs-systematic' },
        { label: 'Wie erstellst du einen Prompt-Test-Set?', anchor: '#test-sets' },
        { label: 'Wie bewertest du Prompt-Ausgaben?', anchor: '#scoring-rubrics' },
        { label: 'Unterscheidet sich die Prompt-Qualität zwischen Modellen?', anchor: '#multi-model' },
        { label: 'So startest du mit der Bewertung', anchor: '#how-to-start' },
        { label: 'Was sind die häufigsten Fehler bei der Prompt-Bewertung?', anchor: '#common-mistakes' },
        { label: 'Welche regionalen Vorschriften beeinflussen die Prompt-Bewertung?', anchor: '#regional-considerations' },
        { label: 'Häufig gestellte Fragen', anchor: '#faq' },
        { label: 'Quellen', anchor: '#sources' },
      ],
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'Prompt-Qualität bewerten: Ein praktischer Leitfaden',
        description: 'Bewerte Prompt-Qualität mit 20er Test-Set, Pass/Fail-Scoring und LLM-as-Judge. Accuracy, Konsistenz und Instruction-Following messen. Schritt-für-Schritt-Anleitung. April 2026.',
        author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        datePublished: '2026-04-10',
        dateModified: '2026-04-29',
        url: 'https://www.promptquorum.com/prompt-engineering/how-to-evaluate-prompt-quality?lang=de',
        inLanguage: 'de',
        proficiencyLevel: 'Intermediate',
        about: [
          { '@type': 'Thing', name: 'Prompt-Bewertung' },
          { '@type': 'Thing', name: 'LLM-Test-Sets' },
          { '@type': 'Thing', name: 'Instruction-Following Rate' },
        ],
        audience: { '@type': 'Audience', audienceType: 'Entwickler und Teams, die LLMs in der Produktion einsetzen' },
        speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'de',
        mainEntity: [
          { '@type': 'Question', name: 'Was ist Prompt-Qualität?', acceptedAnswer: { '@type': 'Answer', text: 'Prompt-Qualität misst, wie zuverlässig ein Prompt die beabsichtigte Ausgabe über verschiedene Eingaben erzeugt. Sie hat drei Dimensionen: Accuracy, Konsistenz und Instruction-Following Rate. Ein qualitativ hochwertiger Prompt erzeugt korrekte, konsistente und ordnungsgemäß formatierte Ausgaben zu 85%+ über alle Eingabetypen hinweg.' } },
          { '@type': 'Question', name: 'Wie bewertest du die Prompt-Qualität?', acceptedAnswer: { '@type': 'Answer', text: 'Erstelle einen Test-Set mit 20+ Eingaben (Happy Path, Edge Cases, Adversarial), definiere Pass-Kriterien für jeden vor dem Testen, führe die Eingaben durch deinen Prompt und bewerte die Ausgaben gegen deine Rubrik. Verfolge die Gesamt-Pass-Rate als Primärmetrik. Speichere diese Baseline, damit du Regressionen erkennen kannst, wenn sich der Prompt ändert.' } },
          { '@type': 'Question', name: 'Was ist Instruction-Following Rate?', acceptedAnswer: { '@type': 'Answer', text: 'Die Instruction-Following Rate ist der Prozentsatz von Ausgaben, bei denen das Modell jede Einschränkung im Prompt befolgt hat: Format, Länge, Ton, Umfang und verbotene Inhalte. Eine Rate von 90 % bedeutet, dass 1 von 10 Produktionsanfragen eine Einschränkung verletzt. Dies ist unterschiedlich von Accuracy und muss separat gemessen werden.' } },
          { '@type': 'Question', name: 'Warum funktioniert manuelles Spot-Checking nicht bei der Prompt-Bewertung?', acceptedAnswer: { '@type': 'Answer', text: 'Manuelles Spot-Checking ist nicht wiederholbar (verschiedene Reviewer wählen unterschiedliche Beispiele), auswahlverzerrend (Reviewer wählen unbewusst Fälle, von denen sie erwarten, dass sie bestehen) und nicht skalierbar (10 Beispiele verpassen 90 % der Fehlermodi in einem 100er Set). Automatisierte Test-Sets liefern konsistente, reproduzierbare Ergebnisse über Prompt-Versionen und Modell-Updates.' } },
          { '@type': 'Question', name: 'Wie viele Test-Fälle braucht ein Prompt-Test-Set?', acceptedAnswer: { '@type': 'Answer', text: 'Ein minimaler Test-Set braucht 20 Fälle: 10 Happy-Path-Eingaben für typische Nutzung, 5 Edge Cases an Grenzen (leere Eingabe, sehr lange Eingabe, mehrsprachige Texte) und 5 Adversarial Inputs. Weniger als 20 Fälle erzeugen statistisch unzuverlässige Pass-Raten, die reale Fehlerszenarien verpassen.' } },
          { '@type': 'Question', name: 'Unterscheidet sich die Prompt-Qualität zwischen GPT-5.5 und Claude Opus 4.7?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, erheblich. Derselbe Prompt scored regelmäßig 10-20 Punkte unterschiedlich zwischen GPT-5.5 und Claude Opus 4.7 aufgrund von Unterschieden in der Instruction-Format-Sensitivität und dem System-Prompt-Handling. Messe die Pass-Rate immer separat auf jedem Modell, das du einsetzen möchtest. Ein Prompt, der auf GPT-5.5 95 % scored, kann auf Claude Opus 4.7 ohne modellspezifisches Tuning 80 % scored.' } },
          { '@type': 'Question', name: 'Was ist LLM-as-Judge Scoring und wann sollte ich es verwenden?', acceptedAnswer: { '@type': 'Answer', text: 'LLM-as-Judge nutzt ein leistungsstarkes Modell wie GPT-5.5 oder Claude Opus 4.7, um Ausgaben gegen eine Rubrik zu bewerten. Der Judge erhält die ursprüngliche Eingabe, deine Modell-Ausgabe und Evaluierungskriterien und liefert dann einen Score mit Begründung. Verwende LLM-as-Judge für Free-Text-Ausgaben, wo Binary Pass/Fail nicht ausreicht. Es skaliert auf Tausende Test-Fälle ohne menschliche Überprüfung, was es ideal für kontinuierliche Evaluierungs-Pipelines macht.' } },
          { '@type': 'Question', name: 'Wie setzt du eine Pass-Rate Regressions-Schwelle?', acceptedAnswer: { '@type': 'Answer', text: 'Speichere die Pass-Rate aus dem ersten Test-Durchlauf als Baseline. Ein Regressions-Gate von 5 Punkten ist üblich: wenn eine Prompt-Änderung die Pass-Rate um mehr als 5 Punkte relativ zur Baseline senkt, blockiere das Deployment. Teams zielen typischerweise auf 85–95 % Pass-Rate für Produktions-Prompts ab. Für kritische Workflows (legal, medizinisch, finanziell) verwende stattdessen ein 2-Punkte-Regressions-Gate.' } },
          { '@type': 'Question', name: 'Muss ich bei der Verwendung von Prompt-Bewertung die DSGVO beachten?', acceptedAnswer: { '@type': 'Answer', text: 'Ja. Wenn dein Prompt personenbezogene Daten verarbeitet, gelten DSGVO Artikel 28 (Datenverarbeitungs-Vereinbarungen) und Artikel 22 (automatisierte Entscheidungsfindung). Dokumentierte Prompt-Bewertungs-Test-Sets mit Pass-Rate-Records liefern audit-bereite Nachweise für systematische Qualitätskontrolle. Sie unterstützen auch die Erklärbarkeit, die Artikel 22 für automatisierte Entscheidungen erfordert. Speichere Test-Sets als Compliance-Dokumentation.' } },
          { '@type': 'Question', name: 'Ist Prompt-Bewertung für den deutschen Mittelstand geeignet?', acceptedAnswer: { '@type': 'Answer', text: 'Ja. Mittelständische Unternehmen profitieren von strukturierter Prompt-Bewertung, besonders wenn LLMs in kundenorientierten oder sicherheitskritischen Workflows eingesetzt werden. Ein 20er Test-Set mit dokumentierten Pass-Raten erfüllt BSI-Grundschutz-Katalog Anforderungen für Qualitätskontrolle. Der Aufwand ist niedrig (ein Test-Set mit etwa 6 Stunden Vorbereitung), und die Compliance-Dokumentation reduziert IT-Sicherheits-Audit-Fragen. Besonders relevant für Finanz-, Versicherungs- und Industrie-Mittelstand.' } },
        ],
      },
      howToSchema: {
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        name: 'Wie man Prompt-Qualität bewertet',
        inLanguage: 'de',
        step: [
          { '@type': 'HowToStep', name: 'Definiere Erfolgskriterien', text: 'Schreibe auf, wie eine korrekte Ausgabe aussieht: Format, Inhalt, Länge und verbotene Elemente.' },
          { '@type': 'HowToStep', name: 'Erstelle deinen Test-Set', text: 'Sammle 20+ Eingaben: Happy-Path, Edge Cases und Adversarial Inputs. Schreibe erwartete Ausgaben für jeden.' },
          { '@type': 'HowToStep', name: 'Wähle eine Scoring-Rubrik', text: 'Wähle Binary Pass/Fail, 1-5 Skala oder LLM-as-Judge Scoring basierend auf Output-Typ.' },
          { '@type': 'HowToStep', name: 'Führe den Test-Set aus', text: 'Leite alle Test-Eingaben durch deinen Prompt und sammle Ausgaben.' },
          { '@type': 'HowToStep', name: 'Bewerte Ausgaben gegen Rubrik', text: 'Bewerte jede Ausgabe und berechne die Gesamt-Pass-Rate.' },
          { '@type': 'HowToStep', name: 'Setze eine Baseline und verfolgst Änderungen', text: 'Speichere die Pass-Rate als Baseline. Jede zukünftige Prompt-Änderung muss gegen diese Zahl verglichen werden.' },
        ],
      },
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          title: 'Zusammenfassung',
          items: [
            'Prompt-Qualität = Accuracy + Konsistenz + Instruction-Following Rate über verschiedene Eingaben',
            'Manuelles Spot-Checking ist nicht wiederholbar und verfehlt Edge Cases — nutze automatisierte Test-Sets',
            'Ein minimaler praktischer Test-Set braucht 20 Fälle: Happy Path, Edge Cases und Adversarial Inputs',
            'Binary Pass/Fail ist die aussagekräftigste Metrik für strukturierte Output-Prompts',
            'LLM-as-Judge (GPT-5.5 oder Claude bewertet Ausgaben gegen eine Rubrik) skaliert auf Free-Text-Aufgaben',
            'Nutze PromptQuorum, um denselben Test-Set zu GPT-5.5 und Claude Opus 4.7 zu leiten und Pass-Raten Seite-an-Seite zu vergleichen',
          ],
        },
        definition: {
          id: 'what-is-prompt-quality',
          title: 'Was ist Prompt-Qualität?',
          content: '**Prompt-Qualität ist, wie zuverlässig ein Prompt die beabsichtigte Ausgabe über verschiedene Eingaben, Modelle und Bedingungen hinweg erzeugt.** Ein Prompt, der auf zehn handgewählten Beispielen funktioniert, kann 20 % Fehlerquote aufweisen, wenn echte Benutzer ihn in großem Maßstab verwenden.\n\nQualität ist keine einzelne Zahl. Sie hat drei unabhängige Dimensionen: Accuracy, Konsistenz und Instruction-Following Rate. Ein Prompt kann bei jeder dieser fehlschlagen, während er auf cherry-gepickten Beispielen zu funktionieren scheint.\n\nSystematische Bewertung bedeutet, alle drei Dimensionen gegen einen reproduzierbaren Test-Set zu messen — vor dem Deployment in die Produktion. Siehe [Prompt-Evaluierungs-Metriken](/prompt-engineering/prompt-evaluation-metrics?lang=de) für einen vollständigen Überblick über Scoring-Ansätze.',
          snippets: [
            { type: 'in-one-sentence', text: 'Prompt-Qualität ist der Prozentsatz von Test-Eingaben, bei denen das Modell eine Ausgabe erzeugt, die alle definierten Erfolgskriterien erfüllt.' },
          ],
          callouts: [
            { type: 'pro-tip', label: 'Pro-Tipp', text: 'Definiere Erfolgskriterien, bevor du deinen Test-Set erstellst. Das Bewerten von Ausgaben ohne vordefinierte Rubrik reintroduciert die Subjektivität, die systematische Bewertung eliminieren soll.' },
          ],
        },
        threeComponents: {
          id: 'three-components',
          title: 'Was sind die drei Komponenten der Prompt-Qualität?',
          content: '**Die drei Komponenten sind Accuracy, Konsistenz und Instruction-Following Rate — und jede erfordert eine separate Test-Strategie.**\n\n**Accuracy** misst, ob die Ausgabe der beabsichtigten Bedeutung oder dem Ergebnis entspricht. Bei Classification-Prompts ist Accuracy der Prozentsatz korrekt klassifizierter Eingaben. Bei Generation-Prompts erfordert Accuracy eine Rubrik oder Referenzausgabe.\n\n**Konsistenz** misst, ob dieselbe Eingabe über mehrere Durchläufe Ausgaben im erwarteten Bereich erzeugt. Hohe Temperatur und unterspecifizierte Prompts reduzieren beide die Konsistenz.\n\n**Instruction-Following Rate** misst, ob das Modell jede Einschränkung befolgt hat: Output-Format, Längenlimit, erforderliche Felder, Ton und verbotene Inhalte. Ein Prompt, der sagt „antworte im JSON", scheitert bei Instruction-Following jedes Mal, wenn er Klartext zurückgibt.',
          callouts: [
            { type: 'key-point', label: 'Wichtig', text: 'Accuracy und Instruction-Following Rate sind unterschiedliche Metriken. Ein Prompt kann faktisch korrekt sein, aber trotzdem bei Format-, Längen- oder Ton-Einschränkungen scheitern — beide müssen separat gemessen werden.' },
          ],
        },
        manualVsSystematic: {
          id: 'manual-vs-systematic',
          title: 'Warum funktioniert manuelles Spot-Checking nicht?',
          content: '**Manuelles Spot-Checking erzeugt nicht wiederholbare Ergebnisse und verfehlt die Edge Cases, die Produktionsfehler verursachen.** Zwei Entwickler, die denselben Prompt gegen unterschiedliche handgewählte Beispiele überprüfen, erreichen unterschiedliche Schlussfolgerungen.\n\nDie strukturellen Probleme mit manueller Überprüfung:\n\n- **Auswahlverzerrung:** Reviewer wählen Eingaben, von denen sie erwarten, dass sie funktionieren, nicht Eingaben zum Brechen des Prompts\n- **Nicht wiederholbar:** Eine Prompt-Änderung kann nicht fair gegen eine vorherige manuelle Überprüfung verglichen werden\n- **Nicht skalierbar:** 10 Beispiele verpassen 90 % der Fehlermodi in einem 100er Test-Set\n- **Keine Baseline:** Ohne aufgezeichnete Pass-Rate kannst du Regressionen nicht erkennen',
          columns: ['Kriterium', 'Manuelles Spot-Checking', 'Systematischer Test-Set'],
          rows: [
            { 'Kriterium': 'Reproduzierbarkeit', 'Manuelles Spot-Checking': 'Keine — unterschiedlich bei jeder Überprüfung', 'Systematischer Test-Set': 'Vollständig — gleicher Test-Set bei jedem Durchlauf' },
            { 'Kriterium': 'Edge-Case-Abdeckung', 'Manuelles Spot-Checking': 'Verfehlt die meisten Edge Cases', 'Systematischer Test-Set': 'Explizit enthalten' },
            { 'Kriterium': 'Baseline-Vergleich', 'Manuelles Spot-Checking': 'Nicht möglich', 'Systematischer Test-Set': 'Eingebaut — vergleiche Pass-Raten' },
            { 'Kriterium': 'Skalierung', 'Manuelles Spot-Checking': '5-10 Beispiele in der Praxis', 'Systematischer Test-Set': '20-200+ Fälle' },
          ],
          callouts: [
            { type: 'warning', label: 'Warnung', text: 'Manuelles Spot-Checking ist keine Baseline. Wenn du deine Bewertung nicht reproduzieren kannst, kannst du Regressionen nicht erkennen, wenn sich der Prompt oder das Modell ändert.' },
          ],
        },
        testSets: {
          id: 'test-sets',
          title: 'Wie erstellst du einen Prompt-Test-Set?',
          content: '**Erstelle einen Test-Set, indem du Eingaben über drei Kategorien hinweg sammelst, dann schreibe explizite Pass-Kriterien für jeden, bevor du Tests ausführst.**\n\n**Happy-Path-Eingaben (40 %):** Typische Eingaben, für die der Prompt designed wurde. Alle sollten bestehen.\n\n**Edge-Case-Eingaben (30 %):** Eingaben an der Grenze: leere Eingabe, sehr lange Eingabe, mehrsprachige Eingabe, ungewöhnliche Formatierung, fehlende erforderliche Felder. Diese enthüllen Sprödigkeit.\n\n**Adversarial-Eingaben (30 %):** Eingaben, die den Prompt zum Scheitern bringen sollen: Anweisungen, die dem System-Prompt widersprechen, Anforderungen, Einschränkungen zu ignorieren, Injection-ähnliche Muster. Diese enthüllen Sicherheits- und Zuverlässigkeitslücken.\n\nSchreibe ein Pass-Kriterium für jede Eingabe, bevor du den Test ausführst. Ein Test-Set ohne erwartete Ausgaben ist keine Bewertung. Wenn du Prompts in einer [Prompt-Bibliothek](/prompt-engineering/build-a-prompt-library?lang=de) speicherst, verfolge die Test-Set-Pass-Rate als Metadaten pro Eintrag.',
          promptExamples: [
            {
              bad: 'Teste den Prompt mit ein paar E-Mails und schaue, ob es gut aussieht.',
              good: '20 Test-Eingaben durchführen: 10 Kundenmails (Happy Path), 6 Edge Cases (leerer Body, Nicht-Englisch, keine Subject Line), 4 Adversarial Inputs (Anweisungen im E-Mail-Body eingebettet). Pass-Kriterium: JSON-Ausgabe mit Feldern [reason, priority, sentiment] alle populiert, priority in [low, medium, high].',
              badLabel: 'Vager Ansatz',
              goodLabel: 'Systematischer Test-Set',
            },
          ],
          callouts: [
            { type: 'pro-tip', label: 'Pro-Tipp', text: 'Schreibe erwartete Ausgaben für jede Test-Eingabe, bevor du den Test ausführst. Ein Test-Set ohne vordefinierte Kriterien ist keine Bewertung — es reintroduciert manuelle Judgment bei der Scoring-Zeit.' },
          ],
        },
        scoringRubrics: {
          id: 'scoring-rubrics',
          title: 'Wie bewertest du Prompt-Ausgaben?',
          content: '**Wähle deine Scoring-Methode basierend auf Output-Typ: Binary Pass/Fail für strukturierte Ausgaben, 1-5 Rubrik für Generation-Aufgaben und LLM-as-Judge für Free-Text-Bewertung.**\n\n**Binary Pass/Fail** ist am aussagekräftigsten. Verwende für JSON-Ausgaben, Classification-Ergebnisse und Ausgaben mit klarer korrekter Antwort. Pass-Rate = korrekte Ausgaben / Gesamt-Test-Fälle.\n\n**1-5 Skala Rubrik** funktioniert für Generation-Aufgaben, wo Teilpunkte sinnvoll sind. Definiere jeden Score-Level vor dem Testen: 5 = vollständig korrekt, 4 = geringes Problem, 3 = akzeptabel mit Caveats, 2 = erhebliches Problem, 1 = falsch oder schädlich.\n\n**LLM-as-Judge** nutzt GPT-5.5 oder Claude Opus 4.7, um Ausgaben gegen eine Rubrik zu bewerten. Stand Mitte 2026 ist LLM-as-Judge der dominante Ansatz zur Bewertung von Free-Text-Ausgaben in großem Maßstab. Der Judge-Prompt muss die Rubrik präzise spezifizieren.\n\n| Methode | Best for | Skalierung | Aufwand | Zuverlässigkeit |\n|---|---|---|---|---|\n| Binary Pass/Fail | Strukturierte Ausgabe, Classification | Jede Größe | Null nach Setup | Hoch — objektiv |\n| 1-5 Rubrik | Generation mit Teilpunkte | <100 Fälle | Mittel — manuelle Bewertung | Mittel — Rater-Varianz |\n| LLM-as-Judge | Free-Text, große Test-Sets | 1000+ Fälle | Niedrig — Rubrik-Design nur | Hoch — wenn Rubrik präzise |',
          codeBlock: '// LLM-as-Judge Scoring Prompt (Pseudocode)\nconst judgePrompt = `\nBewerte diese Kundenservice-Antwort 1-5:\n5 = Korrekt, professionell, adressiert alle Bedenken\n4 = Korrekt, geringes Problem\n3 = Teilweise korrekt\n2 = Falsch oder fehlende Schlüsselinfo\n1 = Falsch, unhöflich oder schädlich\n\nFrage: {input}\nAntwort: {output}\n\nScore (1-5) + Ein-Satz-Begründung:\n`;',
          codeLanguage: 'typescript',
          snippets: [
            { type: 'in-plain-terms', text: 'Stelle dir deine Scoring-Rubrik als Checkliste vor, die ein Lehrer zum Benoten von Arbeiten verwendet — jedes Kriterium muss abgehakenwerden, bevor die Ausgabe als korrekt zählt.' },
          ],
          callouts: [
            { type: 'key-point', label: 'Wichtig', text: 'LLM-as-Judge funktioniert am besten, wenn der Judge-Prompt die Rubrik präzise spezifiziert. Eine vage Rubrik erzeugt inkonsistente Scores — definiere jedes Score-Level mit konkretem Beispiel vor dem Durchlauf des Judge.' },
          ],
        },
        multiModel: {
          id: 'multi-model',
          title: 'Unterscheidet sich die Prompt-Qualität zwischen Modellen?',
          content: '**Ja — derselbe Prompt kann 20+ Punkte unterschiedlich zwischen GPT-5.5 und Claude Opus 4.7 scored, primär aufgrund von Instruction-Format-Sensitivität und System-Prompt-Handling.**\n\nQualitätslücken sind am größten für:\n\n- **JSON-Output-Formatierung:** Claude Opus 4.7 folgt komplexen Schemas strikter als GPT-5.5\n- **Instruction-Priorität:** GPT-5.5 gewichtet die zuletzt gegebene Anweisung; Claude Opus 4.7 gewichtet den System-Prompt\n- **Refusal-Muster:** OpenAI und Anthropic Modelle haben unterschiedliche Schwellen für Grenzfall-Inhalte\n\nUnsere Bewertung von Classification- und Formatting-Prompts über beide Modelle (aktualisiert bis April 2026) fand Pass-Rate-Unterschiede von 10–20 Punkten, wobei JSON-Output-Formatierung die größten Lücken erzeugte. Siehe [Wie man Prompts über Modelle testet](/prompt-engineering/how-to-test-prompts-across-models?lang=de) für vollständige Multi-Model-Evaluierungs-Methodik.\n\nNutze PromptQuorum, um denselben Test-Set zu GPT-5.5, Claude Opus 4.7 und Gemini 2.5 Pro in einem Durchlauf zu leiten und Pass-Raten Seite-an-Seite zu vergleichen.',
          callouts: [
            { type: 'warning', label: 'Warnung', text: 'Gehe nicht davon aus, dass ein Prompt, der auf GPT-5.5 bestanden hat, auf Claude Opus 4.7 bestehen wird. Führe denselben Test-Set auf jedem Modell aus, das du einsetzen möchtest — ein Prompt kann modellspezifisches Tuning benötigen.' },
          ],
        },
        howToStart: {
          id: 'how-to-start',
          title: 'So startest du mit der Bewertung',
          content: '**Starte mit Erfolgskriterien, bevor du den Test-Set erstellst — das Bewerten von Ausgaben ohne vordefinierte Kriterien reintroduciert die Subjektivität, die systematisches Testen eliminieren soll.** Arbeite die sechs Schritte unten durch, um ein wiederholbares Bewertungs-System aufzubauen. Wenn die Pass-Rate nach Änderungen sinkt, wende [Prompt-Sprödheit-Reduziertechniken](/prompt-engineering/how-to-reduce-prompt-brittleness?lang=de) an, bevor du neu bewertest.',
          numberedItems: [
            'Schreibe Erfolgskriterien auf, bevor du den Test-Set erstellst: Wie sieht eine korrekte Ausgabe in Bezug auf Format, Inhalt und Einschränkungen aus?',
            'Sammle 20 Test-Eingaben: 8 Happy-Path, 6 Edge Cases, 6 Adversarial. Schreibe erwartete Ausgaben oder Pass-Kriterien für jeden.',
            'Wähle eine Scoring-Methode: Binary für strukturierte Ausgaben, 1-5 Rubrik für Generation, LLM-as-Judge für Free Text.',
            'Führe alle 20 Eingaben durch deinen aktuellen Prompt und bewerte jede Ausgabe. Speichere diese Pass-Rate als deine Baseline.',
            'Leite denselben Test-Set zu GPT-5.5 und Claude Opus 4.7 via PromptQuorum und vergleiche Model-Level-Pass-Raten.',
            'Setze eine Regressions-Schwelle: Wenn eine Prompt-Änderung die Pass-Rate um mehr als 5 Punkte senkt, blockiere das Deployment.',
          ],
          callouts: [
            { type: 'pro-tip', label: 'Pro-Tipp', text: 'Führe den Test-Set zweimal aus — einmal vor und einmal nach jeder Prompt-Änderung. Der Unterschied in der Pass-Rate ist dein Änderungs-Impact-Score. Ein Rückgang von mehr als 5 Punkten signalisiert eine Regression.' },
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: 'Was sind die häufigsten Fehler bei der Prompt-Bewertung?',
          mistakes: [
            {
              mistake: 'Nur Happy-Path-Eingaben testen',
              problem: 'Happy-Path-Eingaben, die immer bestehen, sagen dir nichts über Produktions-Zuverlässigkeit. Edge Cases und Adversarial Inputs verursachen die Fehler, denen Benutzer begegnen.',
              fix: 'Mindestens 30 % der Test-Eingaben sollten Edge Cases oder Adversarial sein. Ein 20er Test-Set sollte mindestens 6 Edge Cases und 4 Adversarial Inputs enthalten.',
            },
            {
              mistake: 'Keine erwarteten Ausgaben für Test-Fälle',
              problem: 'Das Bewerten von Ausgaben ohne vordefinierte Kriterien reintroduciert die subjektive Judgment, die systematische Bewertung eliminieren soll.',
              fix: 'Schreibe ein Pass-Kriterium für jede Test-Eingabe, bevor du den Test ausführst. Eine 20-Wort-Zusammenfassung der erwarteten Ausgabe pro Fall ist ausreichend.',
            },
            {
              mistake: 'Pass-Rate von einem Modell auf ein anderes übernehmen',
              problem: 'Derselbe Prompt scored regelmäßig 10-20 Punkte unterschiedlich zwischen GPT-5.5 und Claude Opus 4.7. Eine Pass-Rate von einem Modell auf ein anderes anzunehmen, führt zu Produktions-Überraschungen.',
              fix: 'Führe den Test-Set separat auf jedem Modell aus, das du einsetzen möchtest. GPT-5.5, Claude Opus 4.7 und Gemini 2.5 Pro benötigen alle unabhängige Bewertung.',
            },
            {
              mistake: 'Keine Baseline',
              problem: 'Ohne aufgezeichnete Pass-Rate aus der ersten Bewertung kannst du Regressionen nicht erkennen, wenn sich der Prompt oder das Modell ändert.',
              fix: 'Speichere die Pass-Rate, wenn du einen Prompt zum ersten Mal bewertest. Jede zukünftige Änderung muss gegen diese Baseline-Zahl verglichen werden.',
            },
          ],
          callouts: [
            { type: 'key-point', label: 'Wichtig', text: 'Jeder Fehler hier reintroduciert die Subjektivität, die systematische Bewertung eliminieren soll. Behandle diese als Anti-Patterns, um sie von Anfang an deines Bewertungs-Prozesses durchzusetzen.' },
          ],
        },
        regionalConsiderations: {
          id: 'regional-considerations',
          title: 'Welche regionalen Vorschriften beeinflussen die Prompt-Bewertung?',
          content: '**Regulatorische Anforderungen verlangen zunehmend dokumentierte KI-Output-Qualitätssicherung, wobei spezifische Verpflichtungen je nach Jurisdiktion variieren.**\n\n**EU (AI Act 2025–2026):** Hochrisiko-KI-Systeme unter dem EU AI Act müssen dokumentierte Test- und Qualitätssicherungsprozesse nachweisen. Prompt-Evaluierungs-Test-Sets und Pass-Rate-Records liefern audit-bereite Nachweise für systematische Qualitätskontrolle. DSGVO Artikel 22 erfordert auch, dass automatisierte Entscheidungen, die Einzelne betreffen, erklärbar sind — Prompt-Evaluierungs-Records unterstützen dies.\n\n**Deutschland (BSI-Grundschutz & DSGVO):** Für hochrisiko-KI-Systeme mit Personendaten gelten zusätzliche Anforderungen. Das BSI-Grundschutz-Katalog empfiehlt dokumentierte Test-Sets und Pass-Rate-Tracking als Zeichen von Qualitätskontrolle. Dokumentierte Prompt-Evaluierungen erfüllen beide DSGVO Artikel 28 (Datenverarbeitungs-Dokumentation) und BSI-Anforderungen an Informationssicherheits-Management.\n\n**US (SOC 2 / NIST AI RMF):** SOC 2 Type II Audits überprüfen zunehmend KI-bezogenes Change Management. Dokumentierte Prompt-Test-Sets mit Versionsgeschichte und Pass-Rate-Baselines erfüllen Audit-Anforderungen für Qualitätskontrolle auf KI-gesteuerten Workflows. Das NIST AI Risk Management Framework (aktualisiert bis 2026) betont Messung und Monitoring als Kern-Risikokontrollen.\n\n**Regulierte Industrien:** Financial Services, Healthcare und Legal Teams, die LLM-basierte Tools einsetzen, sollten Prompt-Evaluierungs-Records als Teil der Model-Governance-Dokumentation bewahren. Pass-Rate-Baselines und Regressions-Gates liefern messbare Qualitäts-Nachweise für Compliance-Reviews.',
          callouts: [
            { type: 'pro-tip', label: 'Pro-Tipp', text: 'Wenn deine Organisation SOC 2 oder Regulatory Audits unterliegt, werden Prompt-Evaluierungs-Test-Sets und Pass-Rate-Records zu Audit-Beweise. Speichere sie neben deiner Prompt-Bibliothek für einfache Abfrage.' },
          ],
        },
        relatedReading: {
          title: 'Weiterführende Lektüre',
          items: [
            '[Prompt-Evaluierungs-Metriken: Was gemessen werden soll und wie](/prompt-engineering/prompt-evaluation-metrics?lang=de) — Aufschlüsselung von Pass-Rate, BLEU, semantischer Ähnlichkeit und LLM-as-Judge',
            '[Wie man Prompts über Modelle testet](/prompt-engineering/how-to-test-prompts-across-models?lang=de) — Multi-Model-Bewertung für GPT-5.5 vs Claude vs Gemini',
            '[Wie man Prompt-Sprödheit reduziert](/prompt-engineering/how-to-reduce-prompt-brittleness?lang=de) — Output-Schemas, Few-Shot-Anker und Regressions-Gates',
            '[Prompt-Bibliothek erstellen](/prompt-engineering/build-a-prompt-library?lang=de) — Speichere Test-Sets neben Prompts mit Metadaten für Team-Wiederverwendung',
            '[Beste Prompt-Optimierungs-Tools für Teams](/prompt-engineering/best-prompt-optimization-tools-teams?lang=de) — Tools, die Test-Set-Management und Pass-Rate-Tracking enthalten',
            '[Grundlagen der Prompt-Optimierung](/prompt-engineering/fundamentals-of-prompt-optimization?lang=de) — Kern-Techniken zur Verbesserung von Accuracy und Instruction-Following Rate',
          ],
        },
        faq: {
          id: 'faq',
          title: 'Häufig gestellte Fragen',
          faqs: [
            { q: 'Was ist Prompt-Qualität?', a: 'Prompt-Qualität misst, wie zuverlässig ein Prompt die beabsichtigte Ausgabe über verschiedene Eingaben erzeugt. Sie hat drei Dimensionen: Accuracy, Konsistenz und Instruction-Following Rate. Ein qualitativ hochwertiger Prompt erzeugt korrekte, konsistente und ordnungsgemäß formatierte Ausgaben zu 85%+ über alle Eingabetypen hinweg.' },
            { q: 'Wie bewertest du Prompt-Qualität?', a: 'Erstelle einen Test-Set mit 20+ Eingaben (Happy Path, Edge Cases, Adversarial), definiere Pass-Kriterien für jeden vor dem Testen, führe die Eingaben durch deinen Prompt und bewerte Ausgaben gegen deine Rubrik. Verfolge die Gesamt-Pass-Rate als Primärmetrik. Speichere diese Baseline, damit du Regressionen erkennen kannst, wenn sich der Prompt ändert.' },
            { q: 'Was ist Instruction-Following Rate?', a: 'Instruction-Following Rate ist der Prozentsatz von Ausgaben, bei denen das Modell jede Einschränkung im Prompt befolgt hat: Format, Länge, Ton, Umfang und verbotene Inhalte. Eine Rate von 90 % bedeutet, dass 1 von 10 Produktionsanfragen eine Einschränkung verletzt. Dies ist unterschiedlich von Accuracy und muss separat gemessen werden.' },
            { q: 'Warum funktioniert manuelles Spot-Checking nicht bei der Prompt-Bewertung?', a: 'Manuelles Spot-Checking ist nicht wiederholbar (verschiedene Reviewer wählen unterschiedliche Beispiele), auswahlverzerrend (Reviewer wählen unbewusst Fälle, von denen sie erwarten, dass sie bestehen) und nicht skalierbar (10 Beispiele verpassen 90 % der Fehlermodi in einem 100er Set). Automatisierte Test-Sets liefern konsistente, reproduzierbare Ergebnisse über Prompt-Versionen und Modell-Updates.' },
            { q: 'Wie viele Test-Fälle braucht ein Prompt-Test-Set?', a: 'Ein minimaler Test-Set braucht 20 Fälle: 10 Happy-Path-Eingaben für typische Nutzung, 5 Edge Cases an Grenzen (leere Eingabe, sehr lange Eingabe, mehrsprachige Texte) und 5 Adversarial Inputs. Weniger als 20 Fälle erzeugen statistisch unzuverlässige Pass-Raten, die reale Fehlerszenarien verpassen.' },
            { q: 'Unterscheidet sich die Prompt-Qualität zwischen GPT-5.5 und Claude Opus 4.7?', a: 'Ja, erheblich. Derselbe Prompt scored regelmäßig 10-20 Punkte unterschiedlich zwischen GPT-5.5 und Claude Opus 4.7 aufgrund von Unterschieden in der Instruction-Format-Sensitivität und dem System-Prompt-Handling. Messe die Pass-Rate immer separat auf jedem Modell, das du einsetzen möchtest. Ein Prompt, der auf GPT-5.5 95 % scored, kann auf Claude Opus 4.7 ohne modellspezifisches Tuning 80 % scored.' },
            { q: 'Was ist LLM-as-Judge Scoring und wann sollte ich es verwenden?', a: 'LLM-as-Judge nutzt ein leistungsstarkes Modell wie GPT-5.5 oder Claude Opus 4.7, um Ausgaben gegen eine Rubrik zu bewerten. Der Judge erhält die ursprüngliche Eingabe, deine Modell-Ausgabe und Evaluierungskriterien und liefert dann einen Score mit Begründung. Verwende LLM-as-Judge für Free-Text-Ausgaben, wo Binary Pass/Fail nicht ausreicht. Es skaliert auf Tausende Test-Fälle ohne menschliche Überprüfung, was es ideal für kontinuierliche Evaluierungs-Pipelines macht.' },
            { q: 'Wie setzt du eine Pass-Rate Regressions-Schwelle?', a: 'Speichere die Pass-Rate aus dem ersten Test-Durchlauf als Baseline. Ein Regressions-Gate von 5 Punkten ist üblich: wenn eine Prompt-Änderung die Pass-Rate um mehr als 5 Punkte relativ zur Baseline senkt, blockiere das Deployment. Teams zielen typischerweise auf 85–95 % Pass-Rate für Produktions-Prompts ab. Für kritische Workflows (legal, medizinisch, finanziell) verwende stattdessen ein 2-Punkte-Regressions-Gate.' },
            { q: 'Muss ich bei der Verwendung von Prompt-Bewertung die DSGVO beachten?', a: 'Ja. Wenn dein Prompt personenbezogene Daten verarbeitet, gelten DSGVO Artikel 28 (Datenverarbeitungs-Vereinbarungen) und Artikel 22 (automatisierte Entscheidungsfindung). Dokumentierte Prompt-Bewertungs-Test-Sets mit Pass-Rate-Records liefern audit-bereite Nachweise für systematische Qualitätskontrolle. Sie unterstützen auch die Erklärbarkeit, die Artikel 22 für automatisierte Entscheidungen erfordert. Speichere Test-Sets als Compliance-Dokumentation.' },
            { q: 'Ist Prompt-Bewertung für den deutschen Mittelstand geeignet?', a: 'Ja. Mittelständische Unternehmen profitieren von strukturierter Prompt-Bewertung, besonders wenn LLMs in kundenorientierten oder sicherheitskritischen Workflows eingesetzt werden. Ein 20er Test-Set mit dokumentierten Pass-Raten erfüllt BSI-Grundschutz-Katalog Anforderungen für Qualitätskontrolle. Der Aufwand ist niedrig (ein Test-Set mit etwa 6 Stunden Vorbereitung), und die Compliance-Dokumentation reduziert IT-Sicherheits-Audit-Fragen. Besonders relevant für Finanz-, Versicherungs- und Industrie-Mittelstand.' },
          ],
        },
        sources: {
          id: 'sources',
          title: 'Quellen',
          items: [
            '[OpenAI Evals Framework (github.com/openai/evals)](https://github.com/openai/evals) — Open-Source-Framework zur Bewertung von LLM-Ausgaben mit Test Harness und Scoring-Utilities',
            '[Anthropic Model Evaluations (anthropic.com)](https://www.anthropic.com/news/model-evaluations) — Anthropic Ansatz zur Capability und Safety Evaluierungs-Methodik',
            '[The Prompt Report: Systematic Survey of Prompting Techniques (arXiv:2406.06608)](https://arxiv.org/abs/2406.06608) — Schulhoff et al., 2024. Umfassender Rahmen der Prompt-Design und Bewertung über 50+ Techniken abdeckt.',
            '[DeepEval: LLM Evaluation Framework (github.com/confident-ai/deepeval)](https://github.com/confident-ai/deepeval) — Confident AI, 2024–2025. Open-Source-Framework für automatisierte LLM-Output-Bewertung mit Metriken, Test-Sets und CI/CD-Integration.',
            '[NIST AI Risk Management Framework (airc.nist.gov)](https://airc.nist.gov/Home) — NIST, 2023–2026 (aktualisiert). Framework abdeckt KI-System-Bewertung, Qualitätssicherungs-Methodik und Governance-Dokumentation für regulierte Umgebungen.',
          ],
        },
      },
    },
    fr: { theme: 'Techniques', title: '', intro: '', publishDate: '2026-04-10', readTime: '', educationalLevel: 'Intermediate', sections: {} },
    ja: { theme: 'Techniques', title: '', intro: '', publishDate: '2026-04-10', readTime: '', educationalLevel: 'Intermediate', sections: {} },
    zh: { theme: 'Techniques', title: '', intro: '', publishDate: '2026-04-10', readTime: '', educationalLevel: 'Intermediate', sections: {} },
  };
