import type { Language } from '@/lib/blog/blogContent';
import type { PEArticle } from '@/lib/prompt-engineering/types';

export const article: Record<Language, PEArticle> = {
  en: {
    freshness_tier: 'evergreen',
    theme: 'Evaluation & Reliability',
    title: 'How to Reduce Prompt Brittleness',
    intro: 'Prompt brittleness causes silent production failures. Learn 7 techniques — structured output, defensive instructions, regression testing — to make prompts reliable across input variations and model updates.',
    seoTitle: 'How to Reduce Prompt Brittleness: 7 Techniques',
    metaDescription: 'Prompt brittleness causes production failures that are invisible in testing. Learn 7 techniques — structured output, defensive instructions, regression suites — to make prompts reliable.',
    ogTitle: 'How to Reduce Prompt Brittleness: 7 Techniques',
    ogDescription: 'A prompt that passes every internal test can produce wrong outputs the moment a real user phrases the request differently — or the model updates without warning. Learn how to fix it.',
    twitterTitle: 'How to Reduce Prompt Brittleness',
    twitterDescription: 'Prompts break silently on input variations. 7 techniques: structured output, few-shot anchoring, defensive instructions, parameterization, regression testing, version pinning, output validation.',
    publishDate: '2026-04-29',
    dateModified: '2026-04-29',
    readTime: '8 min read',
    educationalLevel: 'Advanced',
    audience: 'Developers and prompt engineers managing prompts in production',
    primaryTerm: 'prompt brittleness',
    aboutTopics: ['Prompt Engineering', 'LLM Reliability', 'Prompt Testing'],
    leadAnswerBlock: '**Prompt brittleness is the tendency of a prompt to fail silently when input phrasing, model version, or context changes slightly. Reducing brittleness requires format enforcement, defensive instructions, and a regression test set built before deployment.**',
    toc: [
      { label: 'What Is Prompt Brittleness?', anchor: 'what-is-prompt-brittleness' },
      { label: 'What Causes Prompt Brittleness?', anchor: 'causes-of-prompt-brittleness' },
      { label: 'How Do You Reduce Prompt Brittleness?', anchor: 'techniques-to-reduce-prompt-brittleness' },
      { label: 'Brittle vs. Robust Prompt Examples', anchor: 'prompt-examples' },
      { label: 'How Do You Test Prompts for Brittleness?', anchor: 'how-to-test-for-brittleness' },
      { label: 'Common Mistakes That Create Brittle Prompts', anchor: 'common-mistakes' },
      { label: 'How to Start Reducing Brittleness Today', anchor: 'how-to-start' },
      { label: 'FAQs', anchor: 'faq' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'A brittle prompt produces correct output on familiar test inputs but fails silently when phrasing, data, or model version changes',
          'The top cause: implicit format assumptions — expecting a specific output shape without enforcing it',
          'Structured output (JSON mode) eliminates format-mismatch brittleness with a single API flag',
          'Few-shot examples reduce brittleness by anchoring expected output format and style',
          'A regression test set of 20+ cases — including edge cases — is the minimum for safe deployment',
          'Model version pinning prevents silent behavioral drift after provider updates',
          'Output validation layers catch failures that prompt redesign alone cannot prevent',
        ],
      },
      whatIsBrittleness: {
        id: 'what-is-prompt-brittleness',
        title: 'What Is Prompt Brittleness?',
        content: [
          '**Prompt brittleness is when a prompt produces expected results on test inputs but breaks silently when inputs change slightly.** A brittle prompt breaks on rephrased questions, edge case inputs, model version updates, or stacked system prompts. The output does not error — it is just wrong, making brittleness invisible until it reaches production.',
          'Failures are silent because the model returns a plausible-sounding answer instead of throwing an exception. Users see a result and trust it. Teams don\'t discover brittleness until end-users report incorrect outputs, which can happen weeks after deployment.',
        ],
        snippets: [
          { type: 'in-one-sentence', text: 'A brittle prompt is one whose output degrades silently when input phrasing, model version, or execution context changes outside its original test conditions.' },
          { type: 'in-plain-terms', text: 'Think of a brittle prompt like a lock that works perfectly with one key but jams with any key cut even slightly differently — and gives no error message when it jams.' },
        ],
        callouts: [
          { type: 'Key Point', label: 'Silent failures', text: 'Brittle prompts do not throw exceptions. The model returns an output — it is just wrong. This makes brittleness harder to detect than a code bug.' },
          { type: 'Did You Know?', label: 'Brittleness vs. hallucination', text: 'Hallucination is a model generating false facts. Brittleness is a prompt design flaw: the same model, given slightly different input, stops following the intended instruction pattern.' },
        ],
      },
      causesOfBrittleness: {
        id: 'causes-of-prompt-brittleness',
        title: 'What Causes Prompt Brittleness?',
        content: 'Most brittleness comes from five patterns in how prompts are written and tested.',
        items: [
          '**Implicit format expectations** — The prompt asks for a specific output format (JSON, bullet list, yes/no) without enforcing it. Any input variation that causes the model to add a preamble or rephrase breaks downstream parsing.',
          '**Happy-path-only testing** — Prompts are validated on 3–5 manually curated examples that always work. Edge cases — empty inputs, very long text, ambiguous phrasing — are never tested.',
          '**Model version sensitivity** — LLM providers update models silently. A prompt tuned on one checkpoint may behave differently after a provider update, with no error signal.',
          '**Context contamination** — When a prompt is combined with a system prompt, memory injection, or tool output, the combined context can override or dilute the original instruction.',
          '**Over-specific trigger phrasing** — Prompts that depend on exact wording ("respond only if the user asks about X") fail when the user\'s phrasing is semantically equivalent but lexically different.',
        ],
        callouts: [
          { type: 'Warning', label: 'Context contamination compounds', text: 'In multi-turn conversations or agentic pipelines, each additional injection point adds a new brittleness vector. Test the prompt in its actual runtime context, not in isolation.' },
        ],
      },
      techniquesToReduce: {
        id: 'techniques-to-reduce-prompt-brittleness',
        title: 'How Do You Reduce Prompt Brittleness?',
        content: 'Seven techniques address the five root causes above. Apply them in order — the earlier techniques cover the most common failure modes.',
        numberedItems: [
          '**Enforce structured output** — Use JSON mode or native structured output APIs instead of asking the model to "respond in JSON". Format enforcement moves the reliability burden from the prompt to the API layer.',
          '**Add explicit few-shot examples** — Include 2–3 input/output pairs that demonstrate correct behavior, including one edge case. Examples anchor the model\'s behavior more reliably than instruction-only prompts.',
          '**Write defensive instructions** — Specify what the model should do when the input is missing, ambiguous, or outside scope. Example: "If no date is found, return `null`. Do not guess." Without this, the model fills gaps with plausible-sounding defaults.',
          '**Parameterise inputs** — Replace hardcoded values and inline examples with named variables (`{{customer_name}}`, `{{document_text}}`). Parameterised prompts are easier to test systematically and prevent accidental over-fitting to example values.',
          '**Build a regression test set before deploying** — Assemble 20+ test cases covering the expected distribution plus 5+ edge cases. Run the test set before every model upgrade or prompt change.',
          '**Pin model versions in production** — Use versioned model identifiers (e.g., `gpt-4o-2024-08-06`) in production. Update only after running the full regression suite against the new version.',
          '**Add an output validation layer** — Validate model output programmatically before passing it downstream. Check type, schema, length, or required field presence. Return a controlled fallback — not the raw model output — on validation failure.',
        ],
        callouts: [
          { type: 'Pro Tip', label: 'Techniques 1 and 7 together', text: 'Structured output (technique 1) prevents most format errors. Output validation (technique 7) catches the residual cases where the model returns valid JSON but with wrong field values. Use both in production pipelines.' },
        ],
      },
      promptExamplesSection: {
        id: 'prompt-examples',
        title: 'Brittle vs. Robust Prompt Examples',
        content: 'These before/after examples show how each source of brittleness can be addressed.',
        promptExamples: [
          {
            bad: 'Classify this support ticket as urgent or routine: {{ticket}}',
            good: 'Classify the support ticket below. Return exactly one of these two JSON objects: {"priority": "urgent"} or {"priority": "routine"}. Do not add explanation. Ticket: {{ticket}}',
            badLabel: 'Brittle: free-text output',
            goodLabel: 'Robust: enforced JSON',
          },
          {
            bad: 'Extract the customer\'s email address from this message: {{message}}',
            good: 'Extract the customer\'s email address from the message below. Return a JSON object: {"email": "<address>"}. If no email address is present, return {"email": null}. Do not guess or infer. Message: {{message}}',
            badLabel: 'Brittle: no null case',
            goodLabel: 'Robust: explicit null handling',
          },
          {
            bad: 'Summarise this article in one sentence: {{article}}',
            good: 'Summarise the article in exactly one sentence. Examples:\nArticle: [short tech news] → Summary: Researchers released a new benchmark measuring LLM reasoning speed across five tasks.\nArticle: [short legal doc] → Summary: The regulation requires data processors to report breaches within 72 hours of discovery.\nArticle: {{article}} → Summary:',
            badLabel: 'Brittle: output length and style vary',
            goodLabel: 'Robust: few-shot anchors format',
          },
        ],
      },
      howToTestForBrittleness: {
        id: 'how-to-test-for-brittleness',
        title: 'How Do You Test Prompts for Brittleness?',
        content: 'Testing for brittleness means deliberately stressing the prompt beyond its happy path. Five testing patterns cover the most common failure modes.',
        items: [
          '**Paraphrase testing** — Restate 5–10 test inputs using different wording and measure whether outputs stay consistent. Brittle prompts show high variance across paraphrases.',
          '**Edge case testing** — Test empty inputs, maximum-length inputs, non-English text, special characters, and inputs that are in-scope but unusual. These expose implicit assumptions.',
          '**Temperature variation** — Run the same inputs at temperature 0.0, 0.5, and 1.0. Robust prompts show consistent structure across the range; brittle prompts break format at higher temperatures.',
          '**Model swap tests** — Run the same prompt and test cases on at least two models. Divergent outputs signal model-specific over-fitting. See [how to test prompts across models](/prompt-engineering/how-to-test-prompts-across-models) for a framework.',
          '**Regression runs before every update** — Run the full test set after each model version change, system prompt update, or prompt edit. Log pass rates per test category (format, content, edge case) to track regression patterns.',
        ],
        callouts: [
          { type: 'Best Practice', label: 'Minimum viable test set', text: 'A test set of 20 cases — 10 typical inputs, 5 paraphrase variants, 5 edge cases — is the minimum for detecting common brittleness patterns before deployment.' },
        ],
      },
      commonMistakes: {
        id: 'common-mistakes',
        title: 'Common Mistakes That Create Brittle Prompts',
        mistakes: [
          {
            mistake: 'Testing only the happy path',
            problem: 'Developers validate prompts against 3–5 examples that always work, then deploy. Edge cases — ambiguous inputs, missing fields, unusual formatting — are never tested and fail in production.',
            fix: 'Assemble a test set before deployment. Include at least 5 edge cases explicitly designed to break the prompt. Run this set before every change.',
          },
          {
            mistake: 'Parsing free-text output with string matching',
            problem: 'Code that checks `if "Yes" in response` breaks when the model responds "Yes, " or "Certainly, yes" — both semantically correct but lexically non-matching. This is the most common source of silent production failures.',
            fix: 'Enforce structured output at the API level. Parse the returned JSON object, not the raw response string.',
          },
          {
            mistake: 'No model version pinning',
            problem: 'Using an alias like `gpt-4o` instead of a versioned model ID means any provider update silently changes model behavior. Teams discover the regression only when users report wrong outputs.',
            fix: 'Use versioned model identifiers in production deployments. Document which version the prompt was tuned on. Upgrade only after running the regression suite against the new version.',
          },
          {
            mistake: 'Writing prompts without a null or fallback case',
            problem: 'A prompt that asks "extract the phone number" with no instruction for the missing-number case causes the model to hallucinate a plausible number when none exists in the input.',
            fix: 'Every extraction or classification prompt must include a `null` or `N/A` return path with an explicit instruction: "If not found, return null."',
          },
        ],
      },
      howToStart: {
        id: 'how-to-start',
        title: 'How to Start Reducing Brittleness Today',
        numberedItems: [
          'Identify your three highest-traffic or highest-risk prompts in production',
          'For each prompt, write 5 paraphrase variants of a typical input and run them — compare outputs for consistency',
          'Add 5 edge case inputs: empty input, maximum length, non-English text, input missing an expected field, input with unexpected characters',
          'If any prompt parses free-text output, switch to structured output or JSON mode in the next deployment',
          'Add a defensive instruction for each gap or null case you identified in step 2–3',
          'Commit your test cases to version control alongside the prompt — treat them as the prompt\'s specification',
          'Set up a CI step that runs the test suite before any prompt or model change is deployed',
          'Pin the model version identifier in your production config and document the version the prompt was tuned on',
        ],
      },
      faq: {
        id: 'faq',
        title: 'Frequently Asked Questions',
        faqs: [
          {
            q: 'What is a brittle prompt?',
            a: 'A brittle prompt is a prompt that produces correct output on its test inputs but fails silently when input phrasing, model version, or runtime context changes. Unlike a code bug, brittleness produces a plausible-looking output — it is just wrong — making it hard to detect without explicit testing.',
          },
          {
            q: 'How do I know if my prompt is brittle?',
            a: 'Rephrase 5 of your standard test inputs and measure whether outputs stay consistent in format, content, and correctness. If any paraphrase breaks the expected output structure or produces a hallucinated answer, the prompt is brittle in that dimension. Temperature variation (0.0 vs 1.0) and edge case inputs (empty, max-length, non-English) are the fastest additional checks.',
          },
          {
            q: 'How many test cases do I need to catch brittleness?',
            a: 'A minimum of 20 cases is enough to detect the most common brittleness patterns: 10 typical inputs covering the expected distribution, 5 paraphrase variants of 2–3 inputs, and 5 edge cases explicitly designed to stress the prompt. More cases improve coverage but the first 20 catch the majority of production failures.',
          },
          {
            q: 'Is JSON mode enough to prevent brittleness?',
            a: 'JSON mode eliminates format-mismatch brittleness — the prompt can no longer return free text when JSON is expected. However, it does not prevent content brittleness: the model can return valid JSON with incorrect field values, missing fields, or wrong data types. Output validation (checking schema, required fields, and value types) is required alongside JSON mode for full protection.',
          },
          {
            q: 'Does few-shot prompting reduce brittleness compared to zero-shot?',
            a: 'Yes. Few-shot examples anchor the model\'s output format and style more reliably than instruction-only prompts. A zero-shot prompt that says "respond in JSON" is more brittle than a few-shot prompt that shows JSON input/output pairs. For production prompts, include at least 2–3 examples — one of which demonstrates an edge case.',
          },
          {
            q: 'Should I use the same prompt across all models?',
            a: 'Not without testing. Models differ in instruction following, default output format, and refusal behavior. A prompt tuned on one model can produce structurally different output on another. Run your regression test set on any new model before switching production traffic. See [how to test prompts across models](/prompt-engineering/how-to-test-prompts-across-models) for a cross-model testing framework.',
          },
          {
            q: 'How often should I test prompts for regression?',
            a: 'Run the regression suite on every prompt change, every model version upgrade, and every system prompt update. For high-volume production prompts, run a subset of 5–10 representative cases on a weekly schedule to catch silent drift from model provider updates that occur between planned upgrades.',
          },
          {
            q: 'What is the difference between prompt brittleness and prompt injection?',
            a: 'Prompt brittleness is a reliability failure: the prompt breaks on legitimate input variations outside its test distribution. Prompt injection is a security failure: a malicious actor deliberately crafts input to override prompt instructions. Both are prompt design flaws, but brittleness is addressed by robustness techniques, while injection requires input sanitization and privilege separation. See [prompt injection and security](/prompt-engineering/prompt-injection-and-security) for injection-specific mitigations.',
          },
        ],
      },
      relatedReading: {
        id: 'related-reading',
        title: 'Related Reading',
        items: [
          { title: 'How to evaluate prompt quality', url: '/prompt-engineering/how-to-evaluate-prompt-quality?lang=en' },
          { title: 'How to test prompts across models', url: '/prompt-engineering/how-to-test-prompts-across-models?lang=en' },
          { title: 'Prompt evaluation metrics', url: '/prompt-engineering/prompt-evaluation-metrics?lang=en' },
          { title: 'Structured output and JSON mode', url: '/prompt-engineering/structured-output-and-json-mode?lang=en' },
          { title: 'Zero-shot vs. few-shot prompting', url: '/prompt-engineering/zero-shot-vs-few-shot?lang=en' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'How to Reduce Prompt Brittleness',
      description: 'Prompt brittleness causes production failures that are invisible in testing. Learn 7 techniques — structured output, defensive instructions, regression suites — to make prompts reliable.',
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      datePublished: '2026-04-29',
      dateModified: '2026-04-29',
      url: 'https://www.promptquorum.com/prompt-engineering/how-to-reduce-prompt-brittleness',
      inLanguage: 'en',
      about: [
        { '@type': 'Thing', name: 'Prompt Engineering' },
        { '@type': 'Thing', name: 'LLM Reliability' },
        { '@type': 'Thing', name: 'Prompt Testing' },
      ],
      mentions: [
        { '@type': 'SoftwareApplication', name: 'JSON mode' },
        { '@type': 'SoftwareApplication', name: 'PromptQuorum' },
      ],
      educationalLevel: 'Advanced',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
    },
    howToSchema: {
      '@context': 'https://schema.org',
      '@type': 'HowTo',
      name: 'How to Reduce Prompt Brittleness',
      step: [
        { '@type': 'HowToStep', position: '1', name: 'Enforce structured output', text: 'Use JSON mode or native structured output APIs instead of asking the model to "respond in JSON". Format enforcement moves the reliability burden from the prompt to the API layer.' },
        { '@type': 'HowToStep', position: '2', name: 'Add explicit few-shot examples', text: 'Include 2–3 input/output pairs that demonstrate correct behavior, including one edge case. Examples anchor the model\'s behavior more reliably than instruction-only prompts.' },
        { '@type': 'HowToStep', position: '3', name: 'Write defensive instructions', text: 'Specify what the model should do when the input is missing, ambiguous, or outside scope. Example: "If no date is found, return `null`. Do not guess." Without this, the model fills gaps with plausible-sounding defaults.' },
        { '@type': 'HowToStep', position: '4', name: 'Parameterise inputs', text: 'Replace hardcoded values and inline examples with named variables (`{{customer_name}}`, `{{document_text}}`). Parameterised prompts are easier to test systematically and prevent accidental over-fitting to example values.' },
        { '@type': 'HowToStep', position: '5', name: 'Build a regression test set before deploying', text: 'Assemble 20+ test cases covering the expected distribution plus 5+ edge cases. Run the test set before every model upgrade or prompt change.' },
        { '@type': 'HowToStep', position: '6', name: 'Pin model versions in production', text: 'Use versioned model identifiers (e.g., `gpt-4o-2024-08-06`) in production. Update only after running the full regression suite against the new version.' },
        { '@type': 'HowToStep', position: '7', name: 'Add an output validation layer', text: 'Validate model output programmatically before passing it downstream. Check type, schema, length, or required field presence. Return a controlled fallback — not the raw model output — on validation failure.' },
      ],
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'What is a brittle prompt?',
          acceptedAnswer: { '@type': 'Answer', text: 'A brittle prompt is a prompt that produces correct output on its test inputs but fails silently when input phrasing, model version, or runtime context changes. Unlike a code bug, brittleness produces a plausible-looking output — it is just wrong — making it hard to detect without explicit testing.' },
        },
        {
          '@type': 'Question',
          name: 'How do I know if my prompt is brittle?',
          acceptedAnswer: { '@type': 'Answer', text: 'Rephrase 5 of your standard test inputs and measure whether outputs stay consistent in format, content, and correctness. If any paraphrase breaks the expected output structure or produces a hallucinated answer, the prompt is brittle in that dimension. Temperature variation (0.0 vs 1.0) and edge case inputs (empty, max-length, non-English) are the fastest additional checks.' },
        },
        {
          '@type': 'Question',
          name: 'How many test cases do I need to catch brittleness?',
          acceptedAnswer: { '@type': 'Answer', text: 'A minimum of 20 cases is enough to detect the most common brittleness patterns: 10 typical inputs covering the expected distribution, 5 paraphrase variants of 2–3 inputs, and 5 edge cases explicitly designed to stress the prompt. More cases improve coverage but the first 20 catch the majority of production failures.' },
        },
        {
          '@type': 'Question',
          name: 'Is JSON mode enough to prevent brittleness?',
          acceptedAnswer: { '@type': 'Answer', text: 'JSON mode eliminates format-mismatch brittleness — the prompt can no longer return free text when JSON is expected. However, it does not prevent content brittleness: the model can return valid JSON with incorrect field values, missing fields, or wrong data types. Output validation (checking schema, required fields, and value types) is required alongside JSON mode for full protection.' },
        },
        {
          '@type': 'Question',
          name: 'Does few-shot prompting reduce brittleness compared to zero-shot?',
          acceptedAnswer: { '@type': 'Answer', text: 'Yes. Few-shot examples anchor the model\'s output format and style more reliably than instruction-only prompts. A zero-shot prompt that says "respond in JSON" is more brittle than a few-shot prompt that shows JSON input/output pairs. For production prompts, include at least 2–3 examples — one of which demonstrates an edge case.' },
        },
        {
          '@type': 'Question',
          name: 'Should I use the same prompt across all models?',
          acceptedAnswer: { '@type': 'Answer', text: 'Not without testing. Models differ in instruction following, default output format, and refusal behavior. A prompt tuned on one model can produce structurally different output on another. Run your regression test set on any new model before switching production traffic. See how to test prompts across models for a cross-model testing framework.' },
        },
        {
          '@type': 'Question',
          name: 'How often should I test prompts for regression?',
          acceptedAnswer: { '@type': 'Answer', text: 'Run the regression suite on every prompt change, every model version upgrade, and every system prompt update. For high-volume production prompts, run a subset of 5–10 representative cases on a weekly schedule to catch silent drift from model provider updates that occur between planned upgrades.' },
        },
        {
          '@type': 'Question',
          name: 'What is the difference between prompt brittleness and prompt injection?',
          acceptedAnswer: { '@type': 'Answer', text: 'Prompt brittleness is a reliability failure: the prompt breaks on legitimate input variations outside its test distribution. Prompt injection is a security failure: a malicious actor deliberately crafts input to override prompt instructions. Both are prompt design flaws, but brittleness is addressed by robustness techniques, while injection requires input sanitization and privilege separation. See prompt injection and security for injection-specific mitigations.' },
        },
      ],
    },
  },
  de: {
    freshness_tier: 'evergreen',
    theme: 'Evaluation & Reliability',
    title: 'How to Reduce Prompt Brittleness',
    intro: 'Prompt brittleness causes silent production failures. Learn 7 techniques — structured output, defensive instructions, regression testing — to make prompts reliable across input variations and model updates.',
    seoTitle: 'How to Reduce Prompt Brittleness: 7 Techniques',
    metaDescription: 'Prompt brittleness causes production failures that are invisible in testing. Learn 7 techniques — structured output, defensive instructions, regression suites — to make prompts reliable.',
    publishDate: '2026-04-29',
    dateModified: '2026-04-29',
    readTime: '8 min read',
    educationalLevel: 'Advanced',
    sections: {} as any,
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      inLanguage: 'de',
      url: 'https://www.promptquorum.com/prompt-engineering/how-to-reduce-prompt-brittleness?lang=de',
    },
  },
  fr: {
    freshness_tier: 'evergreen',
    theme: 'Evaluation & Reliability',
    title: 'How to Reduce Prompt Brittleness',
    intro: 'Prompt brittleness causes silent production failures. Learn 7 techniques — structured output, defensive instructions, regression testing — to make prompts reliable across input variations and model updates.',
    seoTitle: 'How to Reduce Prompt Brittleness: 7 Techniques',
    metaDescription: 'Prompt brittleness causes production failures that are invisible in testing. Learn 7 techniques — structured output, defensive instructions, regression suites — to make prompts reliable.',
    publishDate: '2026-04-29',
    dateModified: '2026-04-29',
    readTime: '8 min read',
    educationalLevel: 'Advanced',
    sections: {} as any,
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      inLanguage: 'fr',
      url: 'https://www.promptquorum.com/prompt-engineering/how-to-reduce-prompt-brittleness?lang=fr',
    },
  },
  ja: {
    freshness_tier: 'evergreen',
    theme: 'Evaluation & Reliability',
    title: 'How to Reduce Prompt Brittleness',
    intro: 'Prompt brittleness causes silent production failures. Learn 7 techniques — structured output, defensive instructions, regression testing — to make prompts reliable across input variations and model updates.',
    seoTitle: 'How to Reduce Prompt Brittleness: 7 Techniques',
    metaDescription: 'Prompt brittleness causes production failures that are invisible in testing. Learn 7 techniques — structured output, defensive instructions, regression suites — to make prompts reliable.',
    publishDate: '2026-04-29',
    dateModified: '2026-04-29',
    readTime: '8 min read',
    educationalLevel: 'Advanced',
    sections: {} as any,
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      inLanguage: 'ja',
      url: 'https://www.promptquorum.com/prompt-engineering/how-to-reduce-prompt-brittleness?lang=ja',
    },
  },
  zh: {
    freshness_tier: 'evergreen',
    theme: 'Evaluation & Reliability',
    title: 'How to Reduce Prompt Brittleness',
    intro: 'Prompt brittleness causes silent production failures. Learn 7 techniques — structured output, defensive instructions, regression testing — to make prompts reliable across input variations and model updates.',
    seoTitle: 'How to Reduce Prompt Brittleness: 7 Techniques',
    metaDescription: 'Prompt brittleness causes production failures that are invisible in testing. Learn 7 techniques — structured output, defensive instructions, regression suites — to make prompts reliable.',
    publishDate: '2026-04-29',
    dateModified: '2026-04-29',
    readTime: '8 min read',
    educationalLevel: 'Advanced',
    sections: {} as any,
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      inLanguage: 'zh',
      url: 'https://www.promptquorum.com/prompt-engineering/how-to-reduce-prompt-brittleness?lang=zh',
    },
  },
};
