import type { Language } from "@/lib/blog/blogContent";
import type { PEArticle } from "@/lib/prompt-engineering/types";

export const article: Record<Language, PEArticle> = {
  en: {
    freshness_tier: 'evergreen',
    theme: 'Workflows & Automation',
    title: 'From Prompts to Repeatable Workflows: Automation Templates for Production Teams',
    seoTitle: 'Prompts to Repeatable Workflows: Automation Templates',
    intro: 'A single prompt that runs when someone remembers to run it is not a system — it is a task. This guide shows how to convert prompts into repeatable workflows with defined triggering conditions, state management, and four production-ready templates covering document processing, research pipelines, code review, and customer triage.',
    metaDescription: 'Convert prompts into automated workflows with triggers, state management, and error handling. 4 templates: document processing, research, code review, triage.',
    ogDescription: '4 production workflow templates: document processing (n8n + GPT), research (LangChain), code review (GitHub Actions + Claude), triage (Make + PromptQuorum).',
    twitterDescription: 'A prompt you run manually is a task. A prompt with a trigger, routing, and error handling is a workflow. 4 production templates inside.',
    publishDate: '2026-05-02',
    readTime: '11 min read',
    educationalLevel: 'Advanced',
    primaryTerm: 'Repeatable Prompt Workflows',
    leadAnswerBlock: '**A repeatable workflow is a prompt-based process with defined triggering conditions, inputs, outputs, and error handling that runs consistently without manual intervention.** The difference between a prompt and a workflow is whether you need to be present for it to run.',
    quickFacts: [
      'Automate when frequency exceeds 5 runs per week with structured inputs',
      '3 trigger types: event-based (webhook), schedule-based (cron), threshold-based (metric)',
      'Make costs $0–$16/month for up to 10,000 operations; n8n is free and self-hostable',
      'JSON output schema required at every step boundary — never pass raw unstructured text',
      'Most production teams reach 70–80% automation with 20–30% human review on edge cases',
      '4 templates: document processing, research pipeline, code review, customer triage',
    ],
    toc: [
      { label: 'The Difference Between a Prompt and a Workflow', anchor: 'prompt_vs_workflow' },
      { label: 'Triggering Conditions and State Management', anchor: 'triggering' },
      { label: '4 Workflow Templates for Production Teams', anchor: 'four_templates' },
      { label: 'Tools for Building Prompt Workflows', anchor: 'tools' },
      { label: 'When to Automate vs. Stay Manual', anchor: 'when_to_automate' },
      { label: 'Common Mistakes', anchor: 'common_mistakes' },
      { label: 'FAQ', anchor: 'faq' },
      { label: 'Related Reading', anchor: 'related_reading' },
      { label: 'Sources', anchor: 'sources' },
    ],
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompts-to-repeatable-workflows',
      inLanguage: 'en',
      headline: 'From Prompts to Repeatable Workflows: Automation Templates for Production Teams',
      description: 'Convert prompts into automated workflows with triggers, state management, and error handling. 4 templates: document processing, research, code review, triage.',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['prompt workflows', 'automation templates', 'repeatable prompts', 'LangChain workflow', 'n8n prompts', 'Make automation', 'production AI workflow'],
      mentions: [
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
        { '@type': 'Thing', name: 'LangChain' },
        { '@type': 'Thing', name: 'n8n' },
        { '@type': 'Thing', name: 'Make' },
        { '@type': 'Thing', name: 'PromptQuorum' },
        { '@type': 'Thing', name: 'Braintrust' },
        { '@type': 'Thing', name: 'Promptfoo' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompts-to-repeatable-workflows', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'en',
      mainEntity: [
        { '@type': 'Question', name: 'What is a repeatable prompt workflow?', acceptedAnswer: { '@type': 'Answer', text: 'A repeatable prompt workflow is a prompt-based process that runs automatically when a defined triggering condition is met, routes output to the next step, and handles errors without manual intervention. Unlike a one-off prompt, a workflow does not require a human to decide when to run it or what to do with the result.' } },
        { '@type': 'Question', name: 'What tools are best for building prompt workflows?', acceptedAnswer: { '@type': 'Answer', text: 'n8n is best for self-hosted, open-source workflows at $0 cost. Make (formerly Integromat) is best for visual, no-code workflows at $0–$16/month. LangChain is best for Python or JavaScript code-based pipelines with full control. PromptQuorum adds multi-model dispatch and comparison across GPT-4o, Claude 4.6 Sonnet, and Gemini 2.5 Pro.' } },
        { '@type': 'Question', name: 'When should I automate a prompt versus run it manually?', acceptedAnswer: { '@type': 'Answer', text: 'Automate if you run the same prompt more than 5 times per week, inputs are structured and predictable, and output routes to a defined next step. Stay manual if inputs vary unpredictably, human judgment is required in every instance, or volume is below 5 runs per week.' } },
        { '@type': 'Question', name: 'How do I manage state between workflow steps?', acceptedAnswer: { '@type': 'Answer', text: 'Pass structured output (JSON, markdown with headers) from one step as the input to the next. Use a shared variable store (e.g., n8n workflow data, LangChain memory) to carry context across steps. Avoid passing raw model output as unstructured text — always define an output schema at each step boundary.' } },
        { '@type': 'Question', name: 'What is the minimum viable workflow structure?', acceptedAnswer: { '@type': 'Answer', text: 'A minimum viable workflow has 4 components: a trigger (scheduled, event-driven, or API call), a prompt execution step (calls the LLM API with the formatted prompt), an output validation step (checks format and quality requirements), and a routing step (sends output to the next system or flags for human review). Add state management and error handling as complexity grows.' } },
        { '@type': 'Question', name: 'How do I choose between Make, n8n, and LangChain for prompt workflows?', acceptedAnswer: { '@type': 'Answer', text: 'Use Make (formerly Integromat) for teams that need a visual no-code interface with 1,000+ app integrations — best for business automation without coding. Use n8n for teams that want no-code with self-hosted control and source access — better privacy, more flexibility. Use LangChain for developers building complex multi-step chains with memory, retrieval, and tool use in Python or JavaScript.' } },
        { '@type': 'Question', name: 'When should I automate a prompt workflow vs keep it manual?', acceptedAnswer: { '@type': 'Answer', text: 'Automate when: the prompt runs more than 10 times per day, the inputs follow a predictable format, the output feeds directly into another system, and the pass rate on a test set exceeds 90%. Keep manual when: the inputs are highly varied, the task requires judgment that cannot be scored automatically, or the output affects irreversible decisions (legal, financial, medical).' } },
      ],
    },
    sections: {
      tldr: {
        isTldr: true,
        title: 'TL;DR',
        content: 'A workflow is a prompt with a trigger, output routing, and error handling — not just a prompt run automatically. Automate when frequency exceeds 5 runs per week, inputs are structured, and output always routes to the same next step. Four production templates cover the most common use cases: document processing, research pipeline, code review, and customer triage.',
      },
      prompt_vs_workflow: {
        title: 'The Difference Between a Prompt and a Workflow',
        snippets: [
          { type: 'in-one-sentence', text: 'A workflow is a prompt that runs automatically when a trigger fires and routes its output to a defined next step without human intervention.' },
          { type: 'in-plain-terms', text: 'Think of a workflow as a prompt that has been given a job title: it knows when to start, what to do with the result, and what to do when something goes wrong.' },
        ],
        content: [
          '**A prompt requires a human to decide when to run it and what to do with the output; a workflow runs automatically when a condition is met and routes the output to the next step.** This is the operational distinction — not a difference in the prompt text itself.',
          'A prompt that extracts invoice data is still just a prompt if someone copies and pastes each invoice into ChatGPT manually. The same extraction logic becomes a workflow when a file upload triggers it, the output is parsed into a structured record, and that record is routed to an accounting system.',
          'Automate when you run the same prompt more than 5 times per week with the same trigger and the output always goes to the same next step. Below that frequency, or when inputs vary significantly, manual prompting is faster than building automation infrastructure.',
        ],
        callouts: [
          { type: 'insight', label: 'Operational definition', text: 'The difference between a prompt and a workflow is not the prompt text — it is whether the system decides when to run it and what happens next.' },
        ],
      },
      triggering: {
        title: 'Triggering Conditions and State Management',
        content: [
          '**Three trigger types cover almost all production prompt workflows: event-based, schedule-based, and threshold-based.** Choosing the wrong trigger type is one of the main reasons workflows run too often, not often enough, or on stale data.',
          'Event-based triggers fire on a specific event: a webhook fires when a file is uploaded, a form is submitted, or an API call arrives. Schedule-based triggers fire on a cron — "run every Monday at 09:00" or "run every 6 hours." Threshold-based triggers fire when a metric crosses a value — error rate exceeds 5%, ticket queue depth exceeds 100, sentiment score drops below 0.4.',
          'State management is how output from one step is passed to the next without losing context. Define a JSON output schema at each step boundary. Store intermediate results in a variable store (n8n workflow data, LangChain memory, or a database field). Never pass raw unstructured model output as the input to the next step — parse it first.',
        ],
        callouts: [
          { type: 'warning', label: 'State management failure', text: 'Passing raw unstructured model output between steps is the most common cause of silent workflow failures. Always define a JSON schema at every step boundary and validate before routing.' },
        ],
      },
      four_templates: {
        title: '4 Workflow Templates for Production Teams',
        content: [
          '**Four templates cover the most common production use cases: document processing, research pipeline, code review, and customer triage.** Each template defines the trigger, the prompt chain, the output routing, and the recommended tools.',
        ],
        numberedItems: [
          'Document Processing — trigger: new PDF upload → extract key data (dates, parties, amounts) → classify document type → route to assigned reviewer queue. Tools: n8n for orchestration + GPT-4o for extraction and classification. Output: structured JSON record written to a shared database.',
          'Research Pipeline — trigger: topic list submitted → search web sources → summarize each source → synthesize into a structured report. Tools: LangChain for multi-step orchestration + Perplexity API for web search. Output: markdown report with citations, stored in a shared folder.',
          'Code Review Loop — trigger: pull request opened → analyze diff → generate inline review comments categorized by severity → post comments to the PR. Tools: GitHub Actions for trigger + Claude 4.6 Sonnet for diff analysis. Output: PR comments posted via GitHub API.',
          'Customer Triage — trigger: new support ticket received → classify severity (P1/P2/P3) → route to the correct queue → generate a draft first-response. Tools: Make for orchestration + PromptQuorum for multi-model dispatch (dispatch to GPT-4o for classification, Claude 4.6 Sonnet for draft generation). Output: ticket updated with severity label and draft response.',
        ],
      },
      tools: {
        title: 'Tools for Building Prompt Workflows',
        content: [
          '**The right tool depends on whether your team prefers visual automation, code-first pipelines, or multi-model dispatch.** Use one primary tool and add PromptQuorum for model-layer decisions.',
          'Make (formerly Integromat) is a visual, no-code workflow builder. Cost: $0 for up to 1,000 operations/month, $16/month for 10,000 operations. Best for: non-technical teams, CRM and email integrations, straightforward trigger-action pipelines. Limitation: complex branching logic is harder to maintain visually at scale.',
          'n8n is open-source and self-hostable at $0 cost. It supports code nodes for custom logic alongside visual flow building. Best for: engineering teams that want full control and data privacy. LangChain (Python and JavaScript) is a code-first framework for building multi-step prompt pipelines with memory, agents, and tool use. Best for: developers building custom applications. PromptQuorum adds multi-model dispatch and side-by-side output comparison across GPT-4o, Claude 4.6 Sonnet, and Gemini 2.5 Pro — use it at any step where model selection affects output quality.',
        ],
        callouts: [
          { type: 'tip', label: 'Tool selection rule', text: 'Start with Make or n8n for orchestration and add PromptQuorum at any step where you need to compare model outputs or dispatch to the best model for that step type.' },
        ],
      },
      when_to_automate: {
        title: 'When to Automate vs. Stay Manual',
        content: [
          '**Automate a prompt workflow when: frequency exceeds 5 runs per week, inputs are structured and predictable, and output routes to a defined next step every time.** All three conditions must be true for automation to pay off.',
          'Stay manual when inputs vary unpredictably (e.g., ad hoc research questions with no fixed format), when human judgment is required in every case rather than just edge cases, or when the current volume is below 5 runs per week — the overhead of building and maintaining the automation exceeds the time saved.',
          'A third category is hybrid: automate the structured steps (data extraction, classification, routing) and keep the judgment step manual (final approval, escalation decision). Most production teams land here — 70–80% automated, 20–30% human review on edge cases.',
        ],
      },
      common_mistakes: {
        title: 'Common Mistakes When Building Prompt Workflows',
        mistakes: [
          { mistake: 'Building workflows before validating the prompt', problem: 'If the underlying prompt fails, the workflow amplifies the failure at scale', fix: 'Test and validate the core prompt against 10+ real examples before wiring it into a workflow' },
          { mistake: 'No error handling or fallback path', problem: 'When the model returns unexpected output, the workflow silently fails or produces corrupt downstream data', fix: 'Always add an output validation step and a fallback route (human review queue or retry with alternate model)' },
          { mistake: 'Single-model workflow with no failover', problem: 'If the primary model\'s API is down, the entire workflow stops', fix: 'Design workflows with a fallback model route. PromptQuorum multi-model dispatch makes this straightforward.' },
          { mistake: 'No monitoring on automated workflows', problem: 'Workflows run silently — you don\'t know output quality is degrading until downstream damage accumulates', fix: 'Log pass rate per run. Alert on quality drops >5% week-over-week.' },
        ],
      },
      key_takeaways: {
        title: 'Key Takeaways',
        items: [
          'A workflow is a prompt with a trigger, output routing, and error handling — not just a prompt run automatically',
          'Automate when frequency >5/week, inputs are structured, and output always routes to the same next step',
          'Three trigger types: event-based (webhook/upload), schedule-based (cron), threshold-based (metric crossing)',
          'Define a JSON output schema at every step boundary — never pass raw unstructured text between steps',
          '4 production templates: document processing (n8n + GPT-4o), research (LangChain + Perplexity), code review (GitHub Actions + Claude 4.6 Sonnet), customer triage (Make + PromptQuorum)',
          'Most teams reach 70–80% automation with 20–30% human review on edge cases',
        ],
      },
      faq: {
        title: 'Frequently Asked Questions',
        faqs: [
          { q: 'What is a repeatable prompt workflow?', a: 'A repeatable prompt workflow is a prompt-based process that runs automatically when a defined triggering condition is met, routes output to the next step, and handles errors without manual intervention. Unlike a one-off prompt, a workflow does not require a human to decide when to run it or what to do with the result.' },
          { q: 'What tools are best for building prompt workflows?', a: 'n8n is best for self-hosted, open-source workflows at $0 cost. Make (formerly Integromat) is best for visual, no-code workflows at $0–$16/month. LangChain is best for Python or JavaScript code-based pipelines with full control. PromptQuorum adds multi-model dispatch and comparison across GPT-4o, Claude 4.6 Sonnet, and Gemini 2.5 Pro.' },
          { q: 'What is the minimum viable workflow structure?', a: 'A minimum viable workflow has 4 components: a trigger (scheduled, event-driven, or API call), a prompt execution step (calls the LLM API with the formatted prompt), an output validation step (checks format and quality requirements), and a routing step (sends output to the next system or flags for human review). Add state management and error handling as complexity grows.' },
          { q: 'How do I choose between Make, n8n, and LangChain for prompt workflows?', a: 'Use Make (formerly Integromat) for teams that need a visual no-code interface with 1,000+ app integrations — best for business automation without coding. Use n8n for teams that want no-code with self-hosted control and source access — better privacy, more flexibility. Use LangChain for developers building complex multi-step chains with memory, retrieval, and tool use in Python or JavaScript.' },
          { q: 'When should I automate a prompt workflow vs keep it manual?', a: 'Automate when: the prompt runs more than 10 times per day, the inputs follow a predictable format, the output feeds directly into another system, and the pass rate on a test set exceeds 90%. Keep manual when: the inputs are highly varied, the task requires judgment that cannot be scored automatically, or the output affects irreversible decisions (legal, financial, medical).' },
        ],
      },
      related_reading: {
        title: 'Related Reading',
        items: [
          { title: 'Prompt Chaining: Multi-Step Prompting', url: '/prompt-engineering/prompt-chaining' },
          { title: 'Prompt Engineering for Developers Workflow', url: '/prompt-engineering/prompt-engineering-for-developers-workflow' },
          { title: 'Prompt Engineering for Content Teams', url: '/prompt-engineering/prompt-engineering-for-content-teams' },
          { title: 'Prompt Engineering for Support Operations', url: '/prompt-engineering/prompt-engineering-for-support-operations' },
          { title: 'Best Tools for Structured Output', url: '/prompt-engineering/best-tools-structured-output' },
        ],
      },
      sources: {
        title: 'Sources',
        items: [
          { title: 'n8n Documentation', url: 'https://docs.n8n.io' },
          { title: 'Make (Integromat) Documentation', url: 'https://www.make.com/en/help' },
          { title: 'LangChain Documentation', url: 'https://python.langchain.com/docs' },
        ],
      },
    },
  },

  de: {
    freshness_tier: 'evergreen',
    theme: 'Workflows & Automatisierung',
    title: 'Von Prompts zu automatisierten Workflows: 4 Vorlagen (2026)',
    seoTitle: 'Prompts zu wiederholbaren Workflows: Automatisierungsvorlagen',
    intro: 'Ein einzelner Prompt, der nur dann ausgeführt wird, wenn jemand daran denkt, ist kein System — es ist eine Aufgabe. Dieser Leitfaden zeigt, wie Sie Prompts in wiederholbare Workflows mit definierten Auslösebedingungen, State Management und vier produktionsreifen Vorlagen umwandeln.',
    metaDescription: 'Prompts in automatisierte Workflows umwandeln: Auslösebedingungen, State Management, Fehlerbehandlung. 4 Vorlagen: Dokumentenverarbeitung, Recherche, Code-Review, Triage.',
    ogDescription: '4 Produktions-Workflow-Vorlagen: Dokumentenverarbeitung (n8n + GPT), Recherche (LangChain), Code-Review (GitHub Actions + Claude), Triage (Make + PromptQuorum).',
    twitterDescription: 'Ein manuell ausgeführter Prompt ist eine Aufgabe. Ein Prompt mit Auslöser, Routing und Fehlerbehandlung ist ein Workflow. 4 Produktionsvorlagen.',
    publishDate: '2026-05-02',
    readTime: '11 Min. Lesezeit',
    educationalLevel: 'Advanced',
    primaryTerm: 'Wiederholbare Prompt-Workflows',
    leadAnswerBlock: '**Ein wiederholbarer Workflow ist ein promptbasierter Prozess mit definierten Auslösebedingungen, Inputs, Outputs und Fehlerbehandlung, der konsistent ohne manuelle Eingriffe ausgeführt wird.** Der Unterschied zwischen einem Prompt und einem Workflow ist, ob Sie anwesend sein müssen, damit er ausgeführt wird.',
    quickFacts: [
      'Automatisieren Sie, wenn die Häufigkeit 5 Ausführungen pro Woche übersteigt und die Eingaben strukturiert sind',
      '3 Auslösertypen: ereignisbasiert (Webhook), zeitplanbasiert (Cron), schwellenwertbasiert (Metrik)',
      'Make kostet 0–16 $/Monat für bis zu 10.000 Operationen; n8n ist kostenlos und selbst hostbar',
      'JSON-Ausgabeschema an jeder Schrittgrenze erforderlich — niemals unstrukturierten Text weitergeben',
      'Die meisten Produktionsteams erreichen 70–80 % Automatisierung mit 20–30 % menschlichem Review',
      '4 Vorlagen: Dokumentenverarbeitung, Recherche-Pipeline, Code-Review, Kundentriage',
    ],
    toc: [
      { label: 'Der Unterschied zwischen einem Prompt und einem Workflow', anchor: 'prompt_vs_workflow' },
      { label: 'Auslösebedingungen und State Management', anchor: 'triggering' },
      { label: '4 Workflow-Vorlagen für Produktionsteams', anchor: 'four_templates' },
      { label: 'Tools für die Erstellung von Prompt-Workflows', anchor: 'tools' },
      { label: 'Wann automatisieren, wann manuell bleiben', anchor: 'when_to_automate' },
      { label: 'Häufige Fehler', anchor: 'common_mistakes' },
      { label: 'FAQ', anchor: 'faq' },
      { label: 'Weiterführende Lektüre', anchor: 'related_reading' },
      { label: 'Quellen', anchor: 'sources' },
    ],
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompts-to-repeatable-workflows?lang=de',
      inLanguage: 'de',
      headline: 'Von Prompts zu automatisierten Workflows: 4 Vorlagen',
      description: 'Prompts in automatisierte Workflows umwandeln: Auslösebedingungen, State Management, Fehlerbehandlung. 4 Vorlagen: Dokumentenverarbeitung, Recherche, Code-Review, Triage.',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['Prompt-Workflows', 'Automatisierungsvorlagen', 'wiederholbare Prompts', 'LangChain Workflow', 'n8n Prompts', 'Produktions-KI-Workflow'],
      mentions: [
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
        { '@type': 'Thing', name: 'LangChain' },
        { '@type': 'Thing', name: 'n8n' },
        { '@type': 'Thing', name: 'Make' },
        { '@type': 'Thing', name: 'PromptQuorum' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompts-to-repeatable-workflows', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'de',
      mainEntity: [
        { '@type': 'Question', name: 'Was ist ein wiederholbarer Prompt-Workflow?', acceptedAnswer: { '@type': 'Answer', text: 'Ein wiederholbarer Prompt-Workflow ist ein promptbasierter Prozess, der automatisch ausgelöst wird, wenn eine definierte Bedingung erfüllt ist, die Ausgabe an den nächsten Schritt weiterleitet und Fehler ohne manuellen Eingriff behandelt.' } },
        { '@type': 'Question', name: 'Wann sollte ich einen Prompt automatisieren?', acceptedAnswer: { '@type': 'Answer', text: 'Automatisieren Sie, wenn Sie denselben Prompt mehr als 5-mal pro Woche mit demselben Auslöser ausführen und die Ausgabe immer zum selben nächsten Schritt weitergeleitet wird.' } },
        { '@type': 'Question', name: 'Welche Tools eignen sich für Prompt-Workflows?', acceptedAnswer: { '@type': 'Answer', text: 'n8n ist am besten für selbst gehostete Open-Source-Workflows geeignet (kostenlos). Make eignet sich für visuelle No-Code-Workflows (0–16 $/Monat). LangChain ist ideal für codebasierte Pipelines in Python oder JavaScript. PromptQuorum ergänzt um Multi-Modell-Dispatch zwischen GPT-4o, Claude 4.6 Sonnet und Gemini 2.5 Pro.' } },
        { '@type': 'Question', name: 'Was ist die minimale Workflow-Struktur?', acceptedAnswer: { '@type': 'Answer', text: 'Ein minimaler Workflow hat 4 Komponenten: einen Auslöser, einen Prompt-Ausführungsschritt, einen Ausgabevalidierungsschritt und einen Routing-Schritt. State Management und Fehlerbehandlung ergänzen Sie je nach Komplexität.' } },
        { '@type': 'Question', name: 'Wie wähle ich zwischen Make, n8n und LangChain?', acceptedAnswer: { '@type': 'Answer', text: 'Verwenden Sie Make für Teams, die eine visuelle No-Code-Oberfläche mit 1.000+ App-Integrationen benötigen. Verwenden Sie n8n für Teams, die No-Code mit selbst gehostetem Zugriff wünschen. Verwenden Sie LangChain für Entwickler, die komplexe mehrstufige Ketten mit Memory, Retrieval und Tool-Nutzung in Python oder JavaScript aufbauen.' } },
        { '@type': 'Question', name: 'Wann automatisieren vs. manuell halten?', acceptedAnswer: { '@type': 'Answer', text: 'Automatisieren Sie, wenn der Prompt mehr als 10-mal täglich ausgeführt wird, die Eingaben einem vorhersehbaren Format folgen, die Ausgabe direkt in ein anderes System fließt und die Bestehensrate auf einem Testset 90 % übersteigt. Halten Sie manuell, wenn die Eingaben sehr variabel sind oder die Ausgabe unwiderrufliche Entscheidungen betrifft.' } },
        { '@type': 'Question', name: 'Wie verwalte ich den State zwischen Workflow-Schritten?', acceptedAnswer: { '@type': 'Answer', text: 'Übergeben Sie strukturierte Ausgaben (JSON, Markdown) von einem Schritt als Eingabe zum nächsten. Verwenden Sie einen Variablenspeicher für den Kontext zwischen den Schritten. Definieren Sie an jeder Schrittgrenze ein Ausgabeschema.' } },
      ],
    },
    sections: {
      tldr: {
        isTldr: true,
        title: 'Kurzfassung',
        content: 'Ein Workflow ist ein Prompt mit einem Auslöser, Output-Routing und Fehlerbehandlung — nicht nur ein automatisch ausgeführter Prompt. Automatisieren Sie bei mehr als 5 Ausführungen pro Woche mit strukturierten Eingaben. Vier Produktionsvorlagen decken die häufigsten Anwendungsfälle ab.',
      },
      prompt_vs_workflow: {
        title: 'Der Unterschied zwischen einem Prompt und einem Workflow',
        snippets: [
          { type: 'in-one-sentence', text: 'Ein Workflow ist ein Prompt, der automatisch ausgeführt wird, wenn ein Auslöser feuert, und seine Ausgabe an einen definierten nächsten Schritt weiterleitet.' },
          { type: 'in-plain-terms', text: 'Stellen Sie sich einen Workflow als einen Prompt mit einer Berufsbezeichnung vor: Er weiß, wann er starten soll, was mit dem Ergebnis zu tun ist und was bei Fehlern zu tun ist.' },
        ],
        content: [
          '**Ein Prompt erfordert, dass ein Mensch entscheidet, wann er ausgeführt werden soll und was mit der Ausgabe geschehen soll; ein Workflow wird automatisch ausgeführt, wenn eine Bedingung erfüllt ist, und leitet die Ausgabe an den nächsten Schritt weiter.** Das ist der operative Unterschied — nicht ein Unterschied im Prompt-Text selbst.',
          'Ein Prompt, der Rechnungsdaten extrahiert, ist immer noch nur ein Prompt, wenn jemand jede Rechnung manuell in ChatGPT kopiert. Dieselbe Extraktionslogik wird zum Workflow, wenn ein Datei-Upload sie auslöst, die Ausgabe in einen strukturierten Datensatz geparst wird und dieser Datensatz an ein Buchhaltungssystem weitergeleitet wird.',
          'Automatisieren Sie, wenn Sie denselben Prompt mehr als 5-mal pro Woche mit demselben Auslöser ausführen und die Ausgabe immer zum selben nächsten Schritt geht. Unterhalb dieser Häufigkeit oder bei stark variierenden Eingaben ist manuelles Prompting schneller als das Aufbauen einer Automatisierungsinfrastruktur.',
        ],
        callouts: [
          { type: 'insight', label: 'Operative Definition', text: 'Der Unterschied zwischen einem Prompt und einem Workflow liegt nicht im Prompt-Text — sondern darin, ob das System entscheidet, wann er ausgeführt wird und was danach passiert.' },
        ],
      },
      triggering: {
        title: 'Auslösebedingungen und State Management',
        content: [
          '**Drei Auslöser-Typen decken fast alle Produktions-Prompt-Workflows ab: ereignisbasiert, zeitplanbasiert und schwellenwertbasiert.** Die Wahl des falschen Auslöser-Typs ist einer der häufigsten Gründe, warum Workflows zu oft, zu selten oder mit veralteten Daten ausgeführt werden.',
          'Ereignisbasierte Auslöser werden bei einem bestimmten Ereignis aktiviert: Ein Webhook wird ausgelöst, wenn eine Datei hochgeladen, ein Formular abgeschickt oder ein API-Aufruf eingeht. Zeitplanbasierte Auslöser werden nach einem Cron-Zeitplan aktiviert. Schwellenwertbasierte Auslöser werden aktiviert, wenn eine Kennzahl einen Wert überschreitet — z. B. Fehlerrate über 5 %, Ticket-Warteschlangentiefe über 100 oder Sentiment-Score unter 0,4.',
          'State Management bezeichnet, wie Ausgaben von einem Schritt ohne Kontextverlust an den nächsten übergeben werden. Definieren Sie an jeder Schrittgrenze ein JSON-Ausgabeschema. Speichern Sie Zwischenergebnisse in einem Variablenspeicher. Übergeben Sie niemals unstrukturierte Modellausgaben als Eingabe zum nächsten Schritt — parsen Sie sie zuerst.',
        ],
        callouts: [
          { type: 'warning', label: 'State-Management-Fehler', text: 'Das Weitergeben von rohen, unstrukturierten Modellausgaben zwischen Schritten ist die häufigste Ursache für stille Workflow-Fehler. Definieren Sie immer ein JSON-Schema an jeder Schrittgrenze.' },
        ],
      },
      four_templates: {
        title: '4 Workflow-Vorlagen für Produktionsteams',
        content: [
          '**Vier Vorlagen decken die häufigsten Produktionsanwendungsfälle ab: Dokumentenverarbeitung, Recherche-Pipeline, Code-Review und Kundentriage.**',
        ],
        numberedItems: [
          'Dokumentenverarbeitung — Auslöser: neues PDF hochgeladen → Kerndaten extrahieren (Daten, Parteien, Beträge) → Dokumenttyp klassifizieren → an Reviewer-Warteschlange weiterleiten. Tools: n8n + GPT-4o. Ausgabe: strukturierter JSON-Datensatz in einer gemeinsamen Datenbank.',
          'Recherche-Pipeline — Auslöser: Themenliste eingereicht → Webquellen suchen → jede Quelle zusammenfassen → strukturierten Bericht erstellen. Tools: LangChain + Perplexity API. Ausgabe: Markdown-Bericht mit Quellenangaben.',
          'Code-Review-Schleife — Auslöser: Pull Request geöffnet → Diff analysieren → Review-Kommentare nach Schweregrad erstellen → Kommentare im PR veröffentlichen. Tools: GitHub Actions + Claude 4.6 Sonnet. Ausgabe: PR-Kommentare über GitHub API.',
          'Kundentriage — Auslöser: neues Support-Ticket eingegangen → Schweregrad klassifizieren (P1/P2/P3) → an richtigen Kanal weiterleiten → Erstentwurf einer Antwort generieren. Tools: Make + PromptQuorum. Ausgabe: Ticket mit Schweregradlabel und Antwortentwurf aktualisiert.',
        ],
      },
      tools: {
        title: 'Tools für die Erstellung von Prompt-Workflows',
        content: [
          '**Das richtige Tool hängt davon ab, ob Ihr Team visuelle Automatisierung, codebasierte Pipelines oder Multi-Modell-Dispatch bevorzugt.**',
          'Make ist ein visueller No-Code-Workflow-Builder. Kosten: 0 $ für bis zu 1.000 Operationen/Monat, 16 $/Monat für 10.000 Operationen. Am besten für: nicht-technische Teams, CRM- und E-Mail-Integrationen. n8n ist Open-Source und selbst hostbar für 0 $. LangChain (Python und JavaScript) ist ein codebasiertes Framework für mehrstufige Prompt-Pipelines.',
          'PromptQuorum ergänzt jedes dieser Tools um Multi-Modell-Dispatch und den direkten Vergleich von Ausgaben zwischen GPT-4o, Claude 4.6 Sonnet und Gemini 2.5 Pro. Verwenden Sie es an Schritten, bei denen die Modellwahl die Ausgabequalität beeinflusst.',
        ],
        callouts: [
          { type: 'tip', label: 'Tool-Auswahlregel', text: 'Beginnen Sie mit Make oder n8n für die Orchestrierung und fügen Sie PromptQuorum an Schritten hinzu, an denen Sie Modellausgaben vergleichen oder das beste Modell dispatchen möchten.' },
        ],
      },
      when_to_automate: {
        title: 'Wann automatisieren, wann manuell bleiben?',
        content: [
          '**Automatisieren Sie einen Prompt-Workflow, wenn: die Häufigkeit 5 Ausführungen pro Woche überschreitet, Eingaben strukturiert und vorhersehbar sind und die Ausgabe jedes Mal an einen definierten nächsten Schritt weitergeleitet wird.** Alle drei Bedingungen müssen erfüllt sein.',
          'Bleiben Sie bei manuellen Prompts, wenn Eingaben unvorhersehbar variieren, wenn menschliches Urteilsvermögen in jedem Fall (nicht nur in Ausnahmefällen) erforderlich ist oder wenn das aktuelle Volumen unter 5 Ausführungen pro Woche liegt.',
          'Eine dritte Kategorie ist hybrid: Die strukturierten Schritte (Datenextraktion, Klassifizierung, Weiterleitung) automatisieren und den Beurteilungsschritt (endgültige Genehmigung, Eskalationsentscheidung) manuell behalten. Die meisten Produktionsteams landen hier — 70–80 % automatisiert, 20–30 % manuelle Überprüfung bei Randfällen.',
        ],
      },
      common_mistakes: {
        title: 'Häufige Fehler beim Aufbau von Prompt-Workflows',
        mistakes: [
          { mistake: 'Workflow vor der Validierung des Prompts aufbauen', problem: 'Wenn der zugrunde liegende Prompt fehlschlägt, verstärkt der Workflow den Fehler im großen Maßstab', fix: 'Testen und validieren Sie den Kern-Prompt an 10+ realen Beispielen, bevor Sie ihn in einen Workflow integrieren' },
          { mistake: 'Keine Fehlerbehandlung oder kein Fallback-Pfad', problem: 'Wenn das Modell unerwartete Ausgaben liefert, schlägt der Workflow still fehl oder erzeugt korrumpierte nachgelagerte Daten', fix: 'Fügen Sie immer einen Ausgabevalidierungsschritt und eine Fallback-Route hinzu (menschliche Review-Warteschlange oder Wiederholungsversuch mit alternativem Modell)' },
          { mistake: 'Single-Modell-Workflow ohne Failover', problem: 'Wenn die API des primären Modells ausfällt, stoppt der gesamte Workflow', fix: 'Gestalten Sie Workflows mit einer Fallback-Modellroute. PromptQuorum Multi-Modell-Dispatch macht dies unkompliziert.' },
          { mistake: 'Kein Monitoring für automatisierte Workflows', problem: 'Workflows laufen still — Sie erkennen nicht, dass die Ausgabequalität sinkt, bis nachgelagerte Schäden entstanden sind', fix: 'Protokollieren Sie die Bestehensrate pro Lauf. Alarmieren Sie bei Qualitätsrückgängen >5 % Woche-zu-Woche.' },
        ],
      },
      key_takeaways: {
        title: 'Wichtigste Erkenntnisse',
        items: [
          'Ein Workflow ist ein Prompt mit einem Auslöser, Output-Routing und Fehlerbehandlung — nicht nur ein automatisch ausgeführter Prompt',
          'Automatisieren Sie bei Häufigkeit >5/Woche, strukturierten Eingaben und konstantem Output-Routing',
          'Drei Auslöser-Typen: ereignisbasiert (Webhook/Upload), zeitplanbasiert (Cron), schwellenwertbasiert (Metrik)',
          'JSON-Ausgabeschema an jeder Schrittgrenze definieren — niemals unstrukturierte Rohdaten weitergeben',
          '4 Produktionsvorlagen: Dokumentenverarbeitung (n8n + GPT-4o), Recherche (LangChain + Perplexity), Code-Review (GitHub Actions + Claude 4.6 Sonnet), Kundentriage (Make + PromptQuorum)',
        ],
      },
      faq: {
        title: 'Häufig gestellte Fragen',
        faqs: [
          { q: 'Was ist ein wiederholbarer Prompt-Workflow?', a: 'Ein wiederholbarer Prompt-Workflow ist ein promptbasierter Prozess, der automatisch ausgelöst wird, wenn eine definierte Bedingung erfüllt ist, die Ausgabe an den nächsten Schritt weiterleitet und Fehler ohne manuellen Eingriff behandelt.' },
          { q: 'Was ist die minimale Workflow-Struktur?', a: 'Ein minimaler Workflow hat 4 Komponenten: einen Auslöser, einen Prompt-Ausführungsschritt, einen Ausgabevalidierungsschritt und einen Routing-Schritt. State Management und Fehlerbehandlung ergänzen Sie je nach Komplexität.' },
          { q: 'Wie wähle ich zwischen Make, n8n und LangChain?', a: 'Verwenden Sie Make für Teams, die eine visuelle No-Code-Oberfläche mit 1.000+ App-Integrationen benötigen. Verwenden Sie n8n für Teams, die No-Code mit selbst gehostetem Zugriff wünschen. Verwenden Sie LangChain für Entwickler, die komplexe mehrstufige Ketten in Python oder JavaScript aufbauen.' },
          { q: 'Wann automatisieren vs. manuell halten?', a: 'Automatisieren Sie, wenn der Prompt mehr als 10-mal täglich ausgeführt wird, die Eingaben einem vorhersehbaren Format folgen und die Bestehensrate auf einem Testset 90 % übersteigt. Halten Sie manuell, wenn die Eingaben sehr variabel sind oder die Ausgabe unwiderrufliche Entscheidungen betrifft.' },
        ],
      },
      related_reading: {
        title: 'Weiterführende Lektüre',
        items: [
          { title: 'Prompt Chaining: Multi-Step Prompting', url: '/prompt-engineering/prompt-chaining' },
          { title: 'Prompt Engineering for Developers Workflow', url: '/prompt-engineering/prompt-engineering-for-developers-workflow' },
          { title: 'Prompt Engineering for Content Teams', url: '/prompt-engineering/prompt-engineering-for-content-teams' },
          { title: 'Prompt Engineering for Support Operations', url: '/prompt-engineering/prompt-engineering-for-support-operations' },
          { title: 'Best Tools for Structured Output', url: '/prompt-engineering/best-tools-structured-output' },
        ],
      },
      sources: {
        title: 'Quellen',
        items: [
          { title: 'n8n Documentation', url: 'https://docs.n8n.io' },
          { title: 'Make (Integromat) Documentation', url: 'https://www.make.com/en/help' },
          { title: 'LangChain Documentation', url: 'https://python.langchain.com/docs' },
        ],
      },
    },
  },

  fr: {
    freshness_tier: 'evergreen',
    theme: 'Workflows & Automatisation',
    title: 'Des prompts aux workflows répétables : modèles d\'automatisation pour les équipes en production',
    seoTitle: 'Prompts vers workflows répétables : modèles d\'automatisation',
    intro: 'Un prompt unique exécuté uniquement quand quelqu\'un s\'en souvient n\'est pas un système — c\'est une tâche. Ce guide explique comment convertir des prompts en workflows répétables avec des conditions de déclenchement définies, une gestion d\'état, et quatre modèles prêts pour la production.',
    metaDescription: 'Convertir des prompts en workflows automatisés avec déclencheurs, gestion d\'état et gestion des erreurs. 4 modèles : traitement de documents, recherche, revue de code, triage.',
    ogDescription: '4 modèles de workflows de production : traitement de documents (n8n + GPT), recherche (LangChain), revue de code (GitHub Actions + Claude), triage (Make + PromptQuorum).',
    twitterDescription: 'Un prompt exécuté manuellement est une tâche. Un prompt avec déclencheur, routage et gestion des erreurs est un workflow. 4 modèles de production.',
    publishDate: '2026-05-02',
    readTime: '11 min de lecture',
    educationalLevel: 'Advanced',
    primaryTerm: 'Workflows de prompts répétables',
    leadAnswerBlock: '**Un workflow répétable est un processus basé sur des prompts avec des conditions de déclenchement définies, des entrées, des sorties et une gestion des erreurs qui s\'exécute de manière cohérente sans intervention manuelle.** La différence entre un prompt et un workflow est de savoir si vous devez être présent pour qu\'il s\'exécute.',
    quickFacts: [
      'Automatisez quand la fréquence dépasse 5 exécutions par semaine avec des entrées structurées',
      '3 types de déclencheurs : événementiel (webhook), planifié (cron), par seuil (métrique)',
      'Make coûte 0–16 $/mois pour 10 000 opérations ; n8n est gratuit et auto-hébergeable',
      'Schéma de sortie JSON requis à chaque frontière d\'étape — ne jamais passer de texte brut',
      'La plupart des équipes atteignent 70–80 % d\'automatisation avec 20–30 % de révision humaine',
      '4 modèles : traitement de documents, pipeline de recherche, revue de code, triage client',
    ],
    toc: [
      { label: 'La différence entre un prompt et un workflow', anchor: 'prompt_vs_workflow' },
      { label: 'Conditions de déclenchement et gestion de l\'état', anchor: 'triggering' },
      { label: '4 modèles de workflows pour les équipes en production', anchor: 'four_templates' },
      { label: 'Outils pour créer des workflows de prompts', anchor: 'tools' },
      { label: 'Quand automatiser vs rester manuel', anchor: 'when_to_automate' },
      { label: 'Erreurs courantes', anchor: 'common_mistakes' },
      { label: 'FAQ', anchor: 'faq' },
      { label: 'Lectures connexes', anchor: 'related_reading' },
      { label: 'Sources', anchor: 'sources' },
    ],
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompts-to-repeatable-workflows?lang=fr',
      inLanguage: 'fr',
      headline: 'Des prompts aux workflows répétables : modèles d\'automatisation pour les équipes en production',
      description: 'Convertir des prompts en workflows automatisés avec déclencheurs, gestion d\'état et gestion des erreurs. 4 modèles : traitement de documents, recherche, revue de code, triage.',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['workflows de prompts', 'automatisation', 'prompts répétables', 'LangChain workflow', 'n8n prompts', 'Make automatisation'],
      mentions: [
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
        { '@type': 'Thing', name: 'LangChain' },
        { '@type': 'Thing', name: 'n8n' },
        { '@type': 'Thing', name: 'Make' },
        { '@type': 'Thing', name: 'PromptQuorum' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompts-to-repeatable-workflows', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'fr',
      mainEntity: [
        { '@type': 'Question', name: 'Qu\'est-ce qu\'un workflow de prompts répétable ?', acceptedAnswer: { '@type': 'Answer', text: 'Un workflow de prompts répétable est un processus basé sur des prompts qui s\'exécute automatiquement lorsqu\'une condition de déclenchement définie est remplie, achemine la sortie vers l\'étape suivante et gère les erreurs sans intervention manuelle.' } },
        { '@type': 'Question', name: 'Quelle est la structure minimale d\'un workflow ?', acceptedAnswer: { '@type': 'Answer', text: 'Un workflow minimal comprend 4 composants : un déclencheur, une étape d\'exécution du prompt, une étape de validation de la sortie, et une étape de routage. Ajoutez la gestion d\'état et la gestion des erreurs selon la complexité.' } },
        { '@type': 'Question', name: 'Comment choisir entre Make, n8n et LangChain ?', acceptedAnswer: { '@type': 'Answer', text: 'Utilisez Make pour les équipes qui ont besoin d\'une interface visuelle sans code avec 1 000+ intégrations d\'applications. Utilisez n8n pour les équipes qui veulent un contrôle auto-hébergé. Utilisez LangChain pour les développeurs qui construisent des chaînes complexes en Python ou JavaScript.' } },
        { '@type': 'Question', name: 'Quand automatiser vs garder manuel ?', acceptedAnswer: { '@type': 'Answer', text: 'Automatisez quand le prompt s\'exécute plus de 10 fois par jour, les entrées suivent un format prévisible et la sortie alimente directement un autre système. Gardez manuel quand les entrées sont très variées ou que la sortie affecte des décisions irréversibles.' } },
      ],
    },
    sections: {
      tldr: {
        isTldr: true,
        title: 'En bref',
        content: 'Un workflow est un prompt avec un déclencheur, un routage de sortie et une gestion des erreurs — pas seulement un prompt exécuté automatiquement. Automatisez quand la fréquence dépasse 5 exécutions par semaine avec des entrées structurées. Quatre modèles de production couvrent les cas d\'usage les plus courants.',
      },
      prompt_vs_workflow: {
        title: 'La différence entre un prompt et un workflow',
        snippets: [
          { type: 'in-one-sentence', text: 'Un workflow est un prompt qui s\'exécute automatiquement quand un déclencheur se déclenche et achemine sa sortie vers une étape suivante définie sans intervention humaine.' },
          { type: 'in-plain-terms', text: 'Imaginez un workflow comme un prompt qui a reçu un titre de poste : il sait quand démarrer, quoi faire avec le résultat, et quoi faire en cas de problème.' },
        ],
        content: [
          '**Un prompt nécessite qu\'un humain décide quand l\'exécuter et quoi faire avec la sortie ; un workflow s\'exécute automatiquement lorsqu\'une condition est remplie et achemine la sortie vers l\'étape suivante.** C\'est la distinction opérationnelle — pas une différence dans le texte du prompt lui-même.',
          'Un prompt qui extrait des données de facture est toujours un simple prompt si quelqu\'un copie-colle manuellement chaque facture dans ChatGPT. La même logique d\'extraction devient un workflow lorsqu\'un envoi de fichier le déclenche, que la sortie est analysée dans un enregistrement structuré et que cet enregistrement est acheminé vers un système comptable.',
          'Automatisez lorsque vous exécutez le même prompt plus de 5 fois par semaine avec le même déclencheur et que la sortie va toujours à la même étape suivante. En dessous de cette fréquence, ou lorsque les entrées varient significativement, le prompting manuel est plus rapide.',
        ],
        callouts: [
          { type: 'insight', label: 'Définition opérationnelle', text: 'La différence entre un prompt et un workflow n\'est pas le texte du prompt — c\'est si le système décide quand l\'exécuter et ce qui se passe ensuite.' },
        ],
      },
      triggering: {
        title: 'Conditions de déclenchement et gestion de l\'état',
        content: [
          '**Trois types de déclencheurs couvrent presque tous les workflows de prompts en production : événementiel, planifié, et par seuil.** Choisir le mauvais type de déclencheur est l\'une des principales raisons pour lesquelles les workflows s\'exécutent trop souvent, pas assez, ou sur des données périmées.',
          'Les déclencheurs événementiels se déclenchent sur un événement spécifique : un webhook se déclenche lors d\'un téléchargement de fichier, d\'une soumission de formulaire ou d\'un appel API. Les déclencheurs planifiés se déclenchent sur un cron. Les déclencheurs par seuil se déclenchent lorsqu\'une métrique dépasse une valeur — taux d\'erreur supérieur à 5 %, score de sentiment inférieur à 0,4.',
          'La gestion d\'état désigne la manière dont la sortie d\'une étape est transmise à la suivante sans perdre le contexte. Définissez un schéma de sortie JSON à chaque frontière d\'étape. Ne transmettez jamais une sortie de modèle brute non structurée comme entrée à l\'étape suivante.',
        ],
        callouts: [
          { type: 'warning', label: 'Échec de gestion d\'état', text: 'Transmettre des sorties de modèle brutes non structurées entre les étapes est la cause la plus courante d\'échecs silencieux de workflow. Définissez toujours un schéma JSON à chaque frontière d\'étape.' },
        ],
      },
      four_templates: {
        title: '4 modèles de workflows pour les équipes en production',
        content: [
          '**Quatre modèles couvrent les cas d\'usage les plus courants : traitement de documents, pipeline de recherche, revue de code et triage client.**',
        ],
        numberedItems: [
          'Traitement de documents — déclencheur : nouveau PDF téléchargé → extraire les données clés → classifier le type de document → acheminer vers la file de révision. Outils : n8n + GPT-4o. Sortie : enregistrement JSON structuré écrit dans une base de données partagée.',
          'Pipeline de recherche — déclencheur : liste de sujets soumise → rechercher des sources web → résumer chaque source → générer un rapport structuré. Outils : LangChain + API Perplexity. Sortie : rapport Markdown avec citations.',
          'Boucle de revue de code — déclencheur : pull request ouverte → analyser le diff → générer des commentaires catégorisés par sévérité → publier les commentaires sur la PR. Outils : GitHub Actions + Claude 4.6 Sonnet. Sortie : commentaires PR publiés via l\'API GitHub.',
          'Triage client — déclencheur : nouveau ticket de support reçu → classifier la sévérité (P1/P2/P3) → acheminer vers la bonne file → générer un brouillon de première réponse. Outils : Make + PromptQuorum. Sortie : ticket mis à jour avec label de sévérité et brouillon de réponse.',
        ],
      },
      tools: {
        title: 'Outils pour créer des workflows de prompts',
        content: [
          '**Le bon outil dépend de si votre équipe préfère l\'automatisation visuelle, les pipelines basés sur le code, ou le dispatch multi-modèle.**',
          'Make est un générateur de workflows visuel sans code. Coût : 0 $ pour 1 000 opérations/mois, 16 $/mois pour 10 000 opérations. n8n est open-source et auto-hébergeable à 0 $. LangChain (Python et JavaScript) est un framework basé sur le code pour des pipelines de prompts multi-étapes.',
          'PromptQuorum ajoute le dispatch multi-modèle et la comparaison côte à côte des sorties entre GPT-4o, Claude 4.6 Sonnet et Gemini 2.5 Pro. Utilisez-le à toute étape où le choix du modèle affecte la qualité de la sortie.',
        ],
        callouts: [
          { type: 'tip', label: 'Règle de sélection d\'outil', text: 'Commencez avec Make ou n8n pour l\'orchestration et ajoutez PromptQuorum aux étapes où vous avez besoin de comparer les sorties des modèles ou de dispatcher vers le meilleur modèle.' },
        ],
      },
      when_to_automate: {
        title: 'Quand automatiser vs rester manuel',
        content: [
          '**Automatisez un workflow de prompts lorsque : la fréquence dépasse 5 exécutions par semaine, les entrées sont structurées et prévisibles, et la sortie est acheminée vers une étape suivante définie à chaque fois.** Les trois conditions doivent être vraies pour que l\'automatisation soit rentable.',
          'Restez manuel lorsque les entrées varient de façon imprévisible, lorsqu\'un jugement humain est requis dans chaque cas, ou lorsque le volume actuel est inférieur à 5 exécutions par semaine.',
          'Une troisième catégorie est hybride : automatiser les étapes structurées et garder l\'étape de jugement manuelle. La plupart des équipes en production arrivent ici — 70–80 % automatisé, 20–30 % de révision humaine pour les cas limites.',
        ],
      },
      common_mistakes: {
        title: 'Erreurs courantes lors de la construction de workflows de prompts',
        mistakes: [
          { mistake: 'Construire des workflows avant de valider le prompt', problem: 'Si le prompt sous-jacent échoue, le workflow amplifie l\'échec à grande échelle', fix: 'Testez et validez le prompt principal sur 10+ exemples réels avant de l\'intégrer dans un workflow' },
          { mistake: 'Pas de gestion des erreurs ou de chemin de secours', problem: 'Quand le modèle retourne une sortie inattendue, le workflow échoue silencieusement ou produit des données corrompues en aval', fix: 'Ajoutez toujours une étape de validation de sortie et une route de secours (file de révision humaine ou nouvelle tentative avec un modèle alternatif)' },
          { mistake: 'Workflow mono-modèle sans basculement', problem: 'Si l\'API du modèle principal est indisponible, tout le workflow s\'arrête', fix: 'Concevez des workflows avec une route de modèle de secours. Le dispatch multi-modèle de PromptQuorum rend cela simple.' },
          { mistake: 'Aucune surveillance sur les workflows automatisés', problem: 'Les workflows s\'exécutent silencieusement — vous ne savez pas que la qualité des sorties se dégrade jusqu\'à ce que des dommages en aval s\'accumulent', fix: 'Enregistrez le taux de réussite par exécution. Alertez sur les baisses de qualité >5 % semaine après semaine.' },
        ],
      },
      key_takeaways: {
        title: 'Points clés',
        items: [
          'Un workflow est un prompt avec un déclencheur, un acheminement de sortie et une gestion des erreurs — pas seulement un prompt exécuté automatiquement',
          'Automatisez quand la fréquence >5/semaine, les entrées sont structurées et la sortie est toujours acheminée vers la même étape suivante',
          'Trois types de déclencheurs : événementiel (webhook/envoi), planifié (cron), par seuil (métrique)',
          'Définir un schéma de sortie JSON à chaque frontière d\'étape — ne jamais transmettre du texte brut non structuré',
          '4 modèles de production : traitement de documents (n8n + GPT-4o), recherche (LangChain + Perplexity), revue de code (GitHub Actions + Claude 4.6 Sonnet), triage client (Make + PromptQuorum)',
        ],
      },
      faq: {
        title: 'Questions fréquentes',
        faqs: [
          { q: 'Qu\'est-ce qu\'un workflow de prompts répétable ?', a: 'Un workflow de prompts répétable est un processus basé sur des prompts qui s\'exécute automatiquement lorsqu\'une condition de déclenchement définie est remplie, achemine la sortie et gère les erreurs sans intervention manuelle.' },
          { q: 'Quelle est la structure minimale d\'un workflow ?', a: 'Un workflow minimal comprend 4 composants : un déclencheur, une étape d\'exécution du prompt, une étape de validation de la sortie, et une étape de routage.' },
          { q: 'Comment choisir entre Make, n8n et LangChain ?', a: 'Utilisez Make pour les équipes qui ont besoin d\'une interface visuelle sans code. Utilisez n8n pour le contrôle auto-hébergé. Utilisez LangChain pour les développeurs construisant des chaînes complexes en Python ou JavaScript.' },
          { q: 'Quand automatiser vs garder manuel ?', a: 'Automatisez quand le prompt s\'exécute plus de 10 fois par jour avec des entrées prévisibles et une sortie qui alimente un autre système. Gardez manuel quand les entrées sont très variées ou que la sortie affecte des décisions irréversibles.' },
        ],
      },
      related_reading: {
        title: 'Lectures connexes',
        items: [
          { title: 'Prompt Chaining: Multi-Step Prompting', url: '/prompt-engineering/prompt-chaining' },
          { title: 'Prompt Engineering for Developers Workflow', url: '/prompt-engineering/prompt-engineering-for-developers-workflow' },
          { title: 'Prompt Engineering for Content Teams', url: '/prompt-engineering/prompt-engineering-for-content-teams' },
          { title: 'Prompt Engineering for Support Operations', url: '/prompt-engineering/prompt-engineering-for-support-operations' },
          { title: 'Best Tools for Structured Output', url: '/prompt-engineering/best-tools-structured-output' },
        ],
      },
      sources: {
        title: 'Sources',
        items: [
          { title: 'n8n Documentation', url: 'https://docs.n8n.io' },
          { title: 'Make (Integromat) Documentation', url: 'https://www.make.com/en/help' },
          { title: 'LangChain Documentation', url: 'https://python.langchain.com/docs' },
        ],
      },
    },
  },

  ja: {
    freshness_tier: 'evergreen',
    theme: 'ワークフローと自動化',
    title: 'プロンプトから繰り返し可能なワークフローへ：本番チーム向け自動化テンプレート',
    seoTitle: 'プロンプトから繰り返し可能なワークフローへ：自動化テンプレート',
    intro: '誰かが覚えているときだけ実行される単独のプロンプトはシステムではありません——それはタスクです。このガイドでは、明確なトリガー条件、状態管理、そして4つの本番対応テンプレートを使用して、プロンプトを繰り返し可能なワークフローに変換する方法を解説します。',
    metaDescription: 'トリガー、状態管理、エラー処理を使ってプロンプトを自動化ワークフローに変換。4つのテンプレート：文書処理、リサーチ、コードレビュー、トリアージ。',
    ogDescription: '4つの本番ワークフローテンプレート：文書処理（n8n + GPT）、リサーチ（LangChain）、コードレビュー（GitHub Actions + Claude）、トリアージ（Make + PromptQuorum）。',
    twitterDescription: '手動で実行するプロンプトはタスクです。トリガー、ルーティング、エラー処理を持つプロンプトはワークフローです。4つの本番テンプレートを紹介。',
    publishDate: '2026-05-02',
    readTime: '11分で読める',
    educationalLevel: 'Advanced',
    primaryTerm: '繰り返し可能なプロンプトワークフロー',
    leadAnswerBlock: '**繰り返し可能なワークフローとは、明確なトリガー条件、入力、出力、エラー処理を持つプロンプトベースのプロセスであり、手動介入なしに一貫して実行されます。** プロンプトとワークフローの違いは、それを実行するためにあなたが場にいる必要があるかどうかです。',
    quickFacts: [
      '週5回以上の頻度で構造化された入力がある場合に自動化する',
      '3つのトリガータイプ：イベントベース（Webhook）、スケジュールベース（cron）、しきい値ベース（メトリクス）',
      'Makeは10,000オペレーションで月0〜16ドル；n8nは無料で自己ホスト可能',
      'すべてのステップ境界でJSON出力スキーマが必要——非構造化テキストを渡さない',
      'ほとんどの本番チームは70〜80%の自動化と20〜30%の人間によるレビューに落ち着く',
      '4つのテンプレート：文書処理、リサーチパイプライン、コードレビュー、顧客トリアージ',
    ],
    toc: [
      { label: 'プロンプトとワークフローの違い', anchor: 'prompt_vs_workflow' },
      { label: 'トリガー条件と状態管理', anchor: 'triggering' },
      { label: '本番チーム向け4つのワークフローテンプレート', anchor: 'four_templates' },
      { label: 'プロンプトワークフロー構築のためのツール', anchor: 'tools' },
      { label: '自動化すべき状況と手動で行うべき状況', anchor: 'when_to_automate' },
      { label: 'よくある間違い', anchor: 'common_mistakes' },
      { label: 'よくある質問', anchor: 'faq' },
      { label: '関連記事', anchor: 'related_reading' },
      { label: '参考資料', anchor: 'sources' },
    ],
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompts-to-repeatable-workflows?lang=ja',
      inLanguage: 'ja',
      headline: 'プロンプトから繰り返し可能なワークフローへ：本番チーム向け自動化テンプレート',
      description: 'トリガー、状態管理、エラー処理を使ってプロンプトを自動化ワークフローに変換。4つのテンプレート：文書処理、リサーチ、コードレビュー、トリアージ。',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['プロンプトワークフロー', '自動化テンプレート', '繰り返し可能なプロンプト', 'LangChainワークフロー', 'n8nプロンプト'],
      mentions: [
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
        { '@type': 'Thing', name: 'LangChain' },
        { '@type': 'Thing', name: 'n8n' },
        { '@type': 'Thing', name: 'Make' },
        { '@type': 'Thing', name: 'PromptQuorum' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompts-to-repeatable-workflows', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'ja',
      mainEntity: [
        { '@type': 'Question', name: '繰り返し可能なプロンプトワークフローとは何ですか？', acceptedAnswer: { '@type': 'Answer', text: '繰り返し可能なプロンプトワークフローとは、定義されたトリガー条件が満たされると自動的に実行され、出力を次のステップにルーティングし、手動介入なしにエラーを処理するプロンプトベースのプロセスです。' } },
        { '@type': 'Question', name: '最小限のワークフロー構造とは何ですか？', acceptedAnswer: { '@type': 'Answer', text: '最小限のワークフローには4つのコンポーネントがあります：トリガー、プロンプト実行ステップ、出力検証ステップ、ルーティングステップ。複雑さに応じて状態管理とエラー処理を追加します。' } },
        { '@type': 'Question', name: 'Make、n8n、LangChainの選択方法は？', acceptedAnswer: { '@type': 'Answer', text: '1,000以上のアプリ統合を持つビジュアルなノーコードインターフェースが必要なチームにはMakeを使用します。自己ホストコントロールを求めるチームにはn8nを使用します。PythonまたはJavaScriptで複雑なマルチステップチェーンを構築する開発者にはLangChainを使用します。' } },
        { '@type': 'Question', name: 'いつ自動化してどのような場合に手動で行うべきですか？', acceptedAnswer: { '@type': 'Answer', text: 'プロンプトが1日10回以上実行され、入力が予測可能なフォーマットに従い、出力が別のシステムに直接フィードされ、テストセットの合格率が90%を超える場合に自動化します。入力が非常に多様な場合や出力が取り消せない決定に影響する場合は手動のままにします。' } },
      ],
    },
    sections: {
      tldr: {
        isTldr: true,
        title: '要点',
        content: 'ワークフローはトリガー、出力ルーティング、エラー処理を持つプロンプトです——単に自動実行されるプロンプトではありません。週5回以上の頻度で構造化された入力がある場合に自動化します。4つの本番テンプレートが最も一般的なユースケースをカバーします。',
      },
      prompt_vs_workflow: {
        title: 'プロンプトとワークフローの違い',
        snippets: [
          { type: 'in-one-sentence', text: 'ワークフローはトリガーが発火したときに自動実行され、人間の介入なしに定義された次のステップに出力をルーティングするプロンプトです。' },
          { type: 'in-plain-terms', text: 'ワークフローを肩書きを与えられたプロンプトと考えてください：いつ開始するか、結果をどうするか、そして何か問題が起きたときに何をするかを知っています。' },
        ],
        content: [
          '**プロンプトは人間がいつ実行するか、出力をどう扱うかを決める必要がある。ワークフローは条件が満たされると自動的に実行され、出力を次のステップにルーティングする。** これが操作上の区別であり、プロンプトテキスト自体の違いではありません。',
          '請求書データを抽出するプロンプトは、誰かが手動でChatGPTに各請求書をコピー＆ペーストしている限り、依然として単なるプロンプトです。同じ抽出ロジックは、ファイルアップロードがトリガーとなり、出力が構造化レコードに解析され、そのレコードが会計システムにルーティングされるときにワークフローになります。',
          '同じトリガーで週に5回以上同じプロンプトを実行し、出力が常に同じ次のステップに向かう場合は自動化します。その頻度未満の場合、または入力が大幅に変動する場合は、手動プロンプティングの方が速いです。',
        ],
        callouts: [
          { type: 'insight', label: '操作上の定義', text: 'プロンプトとワークフローの違いはプロンプトテキストにあるのではありません——システムがいつ実行するかを決め、その後何が起きるかという点にあります。' },
        ],
      },
      triggering: {
        title: 'トリガー条件と状態管理',
        content: [
          '**3つのトリガータイプがほぼすべての本番プロンプトワークフローをカバーします：イベントベース、スケジュールベース、しきい値ベース。** 間違ったトリガータイプを選択することが、ワークフローが多すぎる頻度で、少なすぎる頻度で、または古いデータで実行される主な理由の一つです。',
          'イベントベーストリガーは特定のイベントで発火します：ファイルがアップロードされると、フォームが送信されると、またはAPIコールが届くとWebhookが発火します。スケジュールベーストリガーはcronで発火します。しきい値ベーストリガーはメトリクスが値を超えたときに発火します——エラー率が5%を超える、センチメントスコアが0.4を下回る。',
          '状態管理とは、コンテキストを失わずに一つのステップの出力を次のステップに渡す方法です。各ステップの境界でJSON出力スキーマを定義します。変数ストアに中間結果を保存します。非構造化モデル出力を次のステップの入力として渡さないでください——まず解析してください。',
        ],
        callouts: [
          { type: 'warning', label: '状態管理の失敗', text: 'ステップ間で生の非構造化モデル出力を渡すことが、ワークフローのサイレント失敗の最も一般的な原因です。すべてのステップ境界でJSONスキーマを定義し、ルーティング前に検証してください。' },
        ],
      },
      four_templates: {
        title: '本番チーム向け4つのワークフローテンプレート',
        content: [
          '**4つのテンプレートが最も一般的な本番ユースケースをカバーします：文書処理、リサーチパイプライン、コードレビュー、顧客トリアージ。**',
        ],
        numberedItems: [
          '文書処理 — トリガー：新しいPDFアップロード → 主要データを抽出（日付、当事者、金額）→ 文書タイプを分類 → レビュアーキューにルーティング。ツール：n8n + GPT-4o。出力：共有データベースに書き込まれた構造化JSONレコード。',
          'リサーチパイプライン — トリガー：トピックリスト送信 → ウェブソースを検索 → 各ソースを要約 → 構造化レポートを生成。ツール：LangChain + Perplexity API。出力：引用付きMarkdownレポート。',
          'コードレビューループ — トリガー：プルリクエストが開かれる → diff分析 → 重大度別にレビューコメントを生成 → PRにコメントを投稿。ツール：GitHub Actions + Claude 4.6 Sonnet。出力：GitHub APIを介して投稿されたPRコメント。',
          '顧客トリアージ — トリガー：新しいサポートチケット受信 → 重大度を分類（P1/P2/P3）→ 適切なキューにルーティング → 最初の応答の下書きを生成。ツール：Make + PromptQuorum。出力：重大度ラベルと応答下書きで更新されたチケット。',
        ],
      },
      tools: {
        title: 'プロンプトワークフロー構築のためのツール',
        content: [
          '**適切なツールは、チームがビジュアル自動化、コードファーストパイプライン、またはマルチモデルディスパッチを好むかどうかによって異なります。**',
          'Makeはビジュアルなノーコードワークフロービルダーです。コスト：月1,000オペレーションまで0ドル、10,000オペレーションで月16ドル。n8nはオープンソースで自己ホスト可能（0ドル）。LangChain（PythonとJavaScript）はメモリ、エージェント、ツール使用を備えたマルチステッププロンプトパイプライン向けのコードファーストフレームワークです。',
          'PromptQuorumはGPT-4o、Claude 4.6 Sonnet、Gemini 2.5 Proへのマルチモデルディスパッチと出力の並列比較を追加します。モデルの選択が出力品質に影響するステップで使用してください。',
        ],
        callouts: [
          { type: 'tip', label: 'ツール選択ルール', text: 'オーケストレーションにはMakeまたはn8nから始め、モデル出力を比較したり最適なモデルにディスパッチしたいステップでPromptQuorumを追加してください。' },
        ],
      },
      when_to_automate: {
        title: '自動化すべき状況と手動で行うべき状況',
        content: [
          '**プロンプトワークフローを自動化する条件：頻度が週5回を超える、入力が構造化されて予測可能、出力が毎回定義された次のステップにルーティングされる。** 自動化が効果を発揮するには3つの条件すべてが真でなければなりません。',
          '入力が予測不可能に変化する場合、例外ではなくすべてのケースで人間の判断が必要な場合、または現在のボリュームが週5回未満の場合は手動のままにしてください。',
          '3つ目のカテゴリはハイブリッドです：構造化されたステップ（データ抽出、分類、ルーティング）を自動化し、判断ステップ（最終承認、エスカレーション決定）は手動に保ちます。ほとんどの本番チームはここに落ち着きます——70〜80%自動化、20〜30%はエッジケースで人間のレビュー。',
        ],
      },
      common_mistakes: {
        title: 'プロンプトワークフロー構築時のよくある間違い',
        mistakes: [
          { mistake: 'プロンプトを検証する前にワークフローを構築する', problem: '基礎となるプロンプトが失敗すると、ワークフローはその失敗を大規模に増幅する', fix: 'ワークフローに組み込む前に、10以上の実際の例に対してコアプロンプトをテストして検証する' },
          { mistake: 'エラー処理またはフォールバックパスがない', problem: 'モデルが予期しない出力を返すと、ワークフローはサイレントに失敗するか、下流のデータが破損する', fix: '常に出力検証ステップとフォールバックルート（人間のレビューキューまたは代替モデルでの再試行）を追加する' },
          { mistake: 'フェイルオーバーなしのシングルモデルワークフロー', problem: 'プライマリモデルのAPIがダウンすると、ワークフロー全体が停止する', fix: 'フォールバックモデルルートを持つワークフローを設計する。PromptQuorumのマルチモデルディスパッチがこれを簡単にする。' },
          { mistake: '自動化ワークフローの監視なし', problem: 'ワークフローはサイレントに実行される——下流のダメージが蓄積するまで出力品質が低下していることに気づかない', fix: '実行ごとに合格率をログに記録する。週対週で>5%の品質低下についてアラートを設定する。' },
        ],
      },
      key_takeaways: {
        title: '重要なポイント',
        items: [
          'ワークフローはトリガー、出力ルーティング、エラー処理を持つプロンプト——単に自動実行されるプロンプトではない',
          '週5回以上の頻度、構造化された入力、一定の出力ルーティングがある場合は自動化する',
          '3つのトリガータイプ：イベントベース（Webhook/アップロード）、スケジュールベース（cron）、しきい値ベース（メトリクス）',
          '各ステップの境界でJSON出力スキーマを定義——非構造化テキストを渡さない',
          '4つの本番テンプレート：文書処理（n8n + GPT-4o）、リサーチ（LangChain + Perplexity）、コードレビュー（GitHub Actions + Claude 4.6 Sonnet）、顧客トリアージ（Make + PromptQuorum）',
        ],
      },
      faq: {
        title: 'よくある質問',
        faqs: [
          { q: '繰り返し可能なプロンプトワークフローとは何ですか？', a: '繰り返し可能なプロンプトワークフローとは、定義されたトリガー条件が満たされると自動的に実行され、出力を次のステップにルーティングし、手動介入なしにエラーを処理するプロンプトベースのプロセスです。' },
          { q: '最小限のワークフロー構造とは何ですか？', a: '最小限のワークフローには4つのコンポーネントがあります：トリガー、プロンプト実行ステップ、出力検証ステップ、ルーティングステップ。複雑さに応じて状態管理とエラー処理を追加します。' },
          { q: 'Make、n8n、LangChainの選択方法は？', a: '1,000以上のアプリ統合を持つビジュアルなノーコードインターフェースが必要なチームにはMakeを使用します。自己ホストコントロールを求めるチームにはn8nを使用します。PythonまたはJavaScriptで複雑なマルチステップチェーンを構築する開発者にはLangChainを使用します。' },
          { q: 'いつ自動化してどのような場合に手動で行うべきですか？', a: 'プロンプトが1日10回以上実行され、入力が予測可能で、出力が別のシステムに直接フィードされる場合に自動化します。入力が非常に多様な場合や出力が取り消せない決定に影響する場合は手動のままにします。' },
        ],
      },
      related_reading: {
        title: '関連記事',
        items: [
          { title: 'Prompt Chaining: Multi-Step Prompting', url: '/prompt-engineering/prompt-chaining' },
          { title: 'Prompt Engineering for Developers Workflow', url: '/prompt-engineering/prompt-engineering-for-developers-workflow' },
          { title: 'Prompt Engineering for Content Teams', url: '/prompt-engineering/prompt-engineering-for-content-teams' },
          { title: 'Prompt Engineering for Support Operations', url: '/prompt-engineering/prompt-engineering-for-support-operations' },
          { title: 'Best Tools for Structured Output', url: '/prompt-engineering/best-tools-structured-output' },
        ],
      },
      sources: {
        title: '参考資料',
        items: [
          { title: 'n8n Documentation', url: 'https://docs.n8n.io' },
          { title: 'Make (Integromat) Documentation', url: 'https://www.make.com/en/help' },
          { title: 'LangChain Documentation', url: 'https://python.langchain.com/docs' },
        ],
      },
    },
  },

  zh: {
    freshness_tier: 'evergreen',
    theme: '工作流与自动化',
    title: '从Prompt到可重复工作流：生产团队的自动化模板',
    seoTitle: 'Prompt到可重复工作流：自动化模板',
    intro: '只有在有人记得运行时才执行的单个Prompt不是一个系统——它只是一个任务。本指南展示如何将Prompt转化为具有明确触发条件、状态管理和四个生产就绪模板的可重复工作流。',
    metaDescription: '使用触发器、状态管理和错误处理将Prompt转化为自动化工作流。4个模板：文档处理、研究、代码审查、分诊。',
    ogDescription: '4个生产工作流模板：文档处理（n8n + GPT）、研究（LangChain）、代码审查（GitHub Actions + Claude）、分诊（Make + PromptQuorum）。',
    twitterDescription: '手动运行的Prompt是任务。带有触发器、路由和错误处理的Prompt是工作流。4个生产模板。',
    publishDate: '2026-05-02',
    readTime: '11分钟阅读',
    educationalLevel: 'Advanced',
    primaryTerm: '可重复Prompt工作流',
    leadAnswerBlock: '**可重复工作流是一个基于Prompt的流程，具有明确的触发条件、输入、输出和错误处理，无需人工干预即可持续运行。** Prompt与工作流的区别在于：运行时是否需要你在场。',
    quickFacts: [
      '当频率超过每周5次且输入结构化时进行自动化',
      '3种触发类型：基于事件（Webhook）、基于计划（cron）、基于阈值（指标）',
      'Make每月10,000次操作费用0–16美元；n8n免费且可自托管',
      '每个步骤边界都需要JSON输出架构——永远不要传递非结构化文本',
      '大多数生产团队实现70–80%自动化，20–30%人工审查',
      '4个模板：文档处理、研究管道、代码审查、客户分诊',
    ],
    toc: [
      { label: 'Prompt和工作流之间的区别', anchor: 'prompt_vs_workflow' },
      { label: '触发条件和状态管理', anchor: 'triggering' },
      { label: '生产团队的4个工作流模板', anchor: 'four_templates' },
      { label: '构建Prompt工作流的工具', anchor: 'tools' },
      { label: '何时自动化与手动操作', anchor: 'when_to_automate' },
      { label: '常见错误', anchor: 'common_mistakes' },
      { label: '常见问题', anchor: 'faq' },
      { label: '相关阅读', anchor: 'related_reading' },
      { label: '参考来源', anchor: 'sources' },
    ],
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompts-to-repeatable-workflows?lang=zh',
      inLanguage: 'zh',
      headline: '从Prompt到可重复工作流：生产团队的自动化模板',
      description: '使用触发器、状态管理和错误处理将Prompt转化为自动化工作流。4个模板：文档处理、研究、代码审查、分诊。',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['Prompt工作流', '自动化模板', '可重复Prompt', 'LangChain工作流', 'n8n Prompt', '生产AI工作流'],
      mentions: [
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
        { '@type': 'Thing', name: 'LangChain' },
        { '@type': 'Thing', name: 'n8n' },
        { '@type': 'Thing', name: 'Make' },
        { '@type': 'Thing', name: 'PromptQuorum' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompts-to-repeatable-workflows', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'zh',
      mainEntity: [
        { '@type': 'Question', name: '什么是可重复的Prompt工作流？', acceptedAnswer: { '@type': 'Answer', text: '可重复的Prompt工作流是一个基于Prompt的流程，当定义的触发条件满足时自动运行，将输出路由到下一步，并在无需人工干预的情况下处理错误。' } },
        { '@type': 'Question', name: '最小可行工作流结构是什么？', acceptedAnswer: { '@type': 'Answer', text: '最小可行工作流有4个组件：触发器、Prompt执行步骤、输出验证步骤和路由步骤。随着复杂性增长添加状态管理和错误处理。' } },
        { '@type': 'Question', name: '如何在Make、n8n和LangChain之间选择？', acceptedAnswer: { '@type': 'Answer', text: '对需要1,000+应用集成的可视化无代码界面的团队使用Make。对想要自托管控制的团队使用n8n。对在Python或JavaScript中构建复杂多步骤链的开发者使用LangChain。' } },
        { '@type': 'Question', name: '何时应该自动化Prompt工作流vs保持手动？', acceptedAnswer: { '@type': 'Answer', text: '当Prompt每天运行超过10次、输入遵循可预测格式、输出直接进入另一个系统且测试集通过率超过90%时自动化。当输入高度变化或输出影响不可撤销的决定时保持手动。' } },
      ],
    },
    sections: {
      tldr: {
        isTldr: true,
        title: '摘要',
        content: '工作流是带有触发器、输出路由和错误处理的Prompt——而不仅仅是自动运行的Prompt。当频率超过每周5次且输入结构化时进行自动化。四个生产模板涵盖最常见的用例。',
      },
      prompt_vs_workflow: {
        title: 'Prompt和工作流之间的区别',
        snippets: [
          { type: 'in-one-sentence', text: '工作流是当触发器触发时自动运行并将其输出路由到定义的下一步而无需人工干预的Prompt。' },
          { type: 'in-plain-terms', text: '把工作流想象成一个被赋予了职位的Prompt：它知道何时开始、如何处理结果，以及出错时该做什么。' },
        ],
        content: [
          '**Prompt需要人来决定何时运行以及如何处理输出；工作流在条件满足时自动运行并将输出路由到下一步。** 这是操作上的区别——而不是Prompt文本本身的区别。',
          '提取发票数据的Prompt，如果有人手动将每张发票复制粘贴到ChatGPT中，它仍然只是一个Prompt。当文件上传触发它、输出被解析为结构化记录并路由到会计系统时，同样的提取逻辑就变成了工作流。',
          '当你每周以相同触发条件运行相同Prompt超过5次，且输出始终进入相同的下一步时，进行自动化。低于该频率，或当输入显著变化时，手动提示比构建自动化基础设施更快。',
        ],
        callouts: [
          { type: 'insight', label: '操作定义', text: 'Prompt和工作流的区别不在于Prompt文本——而在于系统是否决定何时运行它以及接下来会发生什么。' },
        ],
      },
      triggering: {
        title: '触发条件和状态管理',
        content: [
          '**三种触发类型涵盖几乎所有生产Prompt工作流：基于事件、基于计划和基于阈值。** 选择错误的触发类型是工作流运行过于频繁、不够频繁或在陈旧数据上运行的主要原因之一。',
          '基于事件的触发器在特定事件上触发：当文件上传、表单提交或API调用到达时，Webhook触发。基于计划的触发器按cron触发——"每周一09:00运行"。基于阈值的触发器在指标超过某个值时触发——错误率超过5%，情感分数低于0.4。',
          '状态管理是指如何在不丢失上下文的情况下将一个步骤的输出传递到下一步。在每个步骤边界定义JSON输出架构。将中间结果存储在变量存储中。永远不要将原始非结构化模型输出作为下一步的输入传递——先解析它。',
        ],
        callouts: [
          { type: 'warning', label: '状态管理失败', text: '在步骤之间传递原始非结构化模型输出是工作流静默失败的最常见原因。始终在每个步骤边界定义JSON架构并在路由前进行验证。' },
        ],
      },
      four_templates: {
        title: '生产团队的4个工作流模板',
        content: [
          '**4个模板涵盖最常见的生产用例：文档处理、研究管道、代码审查和客户分诊。**',
        ],
        numberedItems: [
          '文档处理——触发：新PDF上传 → 提取关键数据（日期、当事方、金额）→ 分类文档类型 → 路由到审阅者队列。工具：n8n + GPT-4o。输出：写入共享数据库的结构化JSON记录。',
          '研究管道——触发：提交主题列表 → 搜索网络来源 → 汇总每个来源 → 生成结构化报告。工具：LangChain + Perplexity API。输出：带引用的Markdown报告。',
          '代码审查循环——触发：拉取请求打开 → 分析差异 → 按严重程度生成内联审查评论 → 将评论发布到PR。工具：GitHub Actions + Claude 4.6 Sonnet。输出：通过GitHub API发布的PR评论。',
          '客户分诊——触发：收到新支持工单 → 分类严重程度（P1/P2/P3）→ 路由到正确队列 → 生成初始回复草稿。工具：Make + PromptQuorum。输出：更新了严重程度标签和回复草稿的工单。',
        ],
      },
      tools: {
        title: '构建Prompt工作流的工具',
        content: [
          '**正确的工具取决于你的团队偏好可视化自动化、代码优先管道还是多模型调度。**',
          'Make是一个可视化无代码工作流构建器。成本：每月1,000次操作以内免费，每月10,000次操作16美元。n8n是开源且可自托管的（0美元）。LangChain（Python和JavaScript）是一个用于构建多步骤Prompt管道的代码优先框架。',
          'PromptQuorum为GPT-4o、Claude 4.6 Sonnet和Gemini 2.5 Pro添加多模型调度和并排输出比较。在模型选择影响输出质量的任何步骤中使用它。',
        ],
        callouts: [
          { type: 'tip', label: '工具选择规则', text: '从Make或n8n开始进行编排，并在需要比较模型输出或调度到最佳模型的步骤添加PromptQuorum。' },
        ],
      },
      when_to_automate: {
        title: '何时自动化与手动操作',
        content: [
          '**自动化Prompt工作流的条件：频率超过每周5次、输入结构化且可预测、输出每次都路由到定义好的下一步。** 自动化要回报成本，三个条件都必须成立。',
          '当输入变化不可预测、每种情况（而非仅边缘情况）都需要人工判断，或当前量低于每周5次时，保持手动。',
          '第三类是混合型：自动化结构化步骤（数据提取、分类、路由），保持判断步骤手动（最终批准、升级决定）。大多数生产团队在这里落地——70–80%自动化，20–30%在边缘情况进行人工审查。',
        ],
      },
      common_mistakes: {
        title: '构建Prompt工作流时的常见错误',
        mistakes: [
          { mistake: '在验证Prompt之前构建工作流', problem: '如果底层Prompt失败，工作流会在大规模上放大失败', fix: '在将其接入工作流之前，针对10+个真实示例测试和验证核心Prompt' },
          { mistake: '没有错误处理或回退路径', problem: '当模型返回意外输出时，工作流静默失败或产生损坏的下游数据', fix: '始终添加输出验证步骤和回退路由（人工审查队列或使用备用模型重试）' },
          { mistake: '没有故障转移的单模型工作流', problem: '如果主模型的API宕机，整个工作流停止', fix: '设计具有回退模型路由的工作流。PromptQuorum的多模型调度使这变得简单。' },
          { mistake: '自动化工作流没有监控', problem: '工作流静默运行——你不知道输出质量正在下降，直到下游损害积累', fix: '记录每次运行的通过率。对每周超过5%的质量下降发出警报。' },
        ],
      },
      key_takeaways: {
        title: '关键要点',
        items: [
          '工作流是带有触发器、输出路由和错误处理的Prompt——而不仅仅是自动运行的Prompt',
          '当频率>每周5次、输入结构化、输出始终路由到相同下一步时自动化',
          '三种触发类型：基于事件（Webhook/上传）、基于计划（cron）、基于阈值（指标）',
          '在每个步骤边界定义JSON输出架构——永远不要传递非结构化文本',
          '4个生产模板：文档处理（n8n + GPT-4o）、研究（LangChain + Perplexity）、代码审查（GitHub Actions + Claude 4.6 Sonnet）、客户分诊（Make + PromptQuorum）',
        ],
      },
      faq: {
        title: '常见问题',
        faqs: [
          { q: '什么是可重复的Prompt工作流？', a: '可重复的Prompt工作流是一个基于Prompt的流程，当定义的触发条件满足时自动运行，将输出路由到下一步，并在无需人工干预的情况下处理错误。' },
          { q: '最小可行工作流结构是什么？', a: '最小可行工作流有4个组件：触发器、Prompt执行步骤、输出验证步骤和路由步骤。随着复杂性增长添加状态管理和错误处理。' },
          { q: '如何在Make、n8n和LangChain之间选择？', a: '对需要可视化无代码界面的团队使用Make。对想要自托管控制的团队使用n8n。对在Python或JavaScript中构建复杂多步骤链的开发者使用LangChain。' },
          { q: '何时应该自动化Prompt工作流vs保持手动？', a: '当Prompt每天运行超过10次且输入可预测时自动化。当输入高度变化或输出影响不可撤销的决定（法律、财务、医疗）时保持手动。' },
        ],
      },
      related_reading: {
        title: '相关阅读',
        items: [
          { title: 'Prompt Chaining: Multi-Step Prompting', url: '/prompt-engineering/prompt-chaining' },
          { title: 'Prompt Engineering for Developers Workflow', url: '/prompt-engineering/prompt-engineering-for-developers-workflow' },
          { title: 'Prompt Engineering for Content Teams', url: '/prompt-engineering/prompt-engineering-for-content-teams' },
          { title: 'Prompt Engineering for Support Operations', url: '/prompt-engineering/prompt-engineering-for-support-operations' },
          { title: 'Best Tools for Structured Output', url: '/prompt-engineering/best-tools-structured-output' },
        ],
      },
      sources: {
        title: '参考来源',
        items: [
          { title: 'n8n Documentation', url: 'https://docs.n8n.io' },
          { title: 'Make (Integromat) Documentation', url: 'https://www.make.com/en/help' },
          { title: 'LangChain Documentation', url: 'https://python.langchain.com/docs' },
        ],
      },
    },
  },
}
