// Auto-generated from src/lib/prompt-engineering/content.ts
// Slug: prompt-engineering-vs-fine-tuning
// Generated: 2026-05-04T14:32:00.000Z

import type { Language } from "@/lib/blog/blogContent";

import type { PEArticle } from "@/lib/prompt-engineering/types";

export const article: Record<Language, PEArticle> = {
  en: {
    freshness_tier: 'evergreen',
    theme: 'Tools & Platforms',
    title: 'Prompt Engineering vs Fine-Tuning: When to Prompt, When to Train',
    intro: 'Prompt engineering and fine-tuning are fundamentally different approaches to improving AI model output. Prompt engineering is free, instant, and reversible. Fine-tuning requires significant investment, takes substantial time, and is difficult to undo. This guide explains when each approach wins.',
    publishDate: '2026-04-10',
    dateModified: '2026-05-04',
    readTime: '9 min read',
    educationalLevel: 'Intermediate',
    audience: 'Developers and engineering leads',
    primaryTerm: 'prompt engineering vs fine-tuning',
    aboutTopics: ['decision-framework', 'cost-comparison', 'model-training'],
    seoTitle: 'Prompt Engineering vs Fine-Tuning: When to Use Each',
    metaDescription: 'Decision guide: prompt engineering vs fine-tuning. Compare cost ($0 vs $500+), time (hours vs weeks), reversibility, and when each approach wins. Flowchart included.',
    ogDescription: 'Prompt engineering or fine-tuning? Comprehensive comparison of cost, time, and reversibility with decision flowchart.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-engineering-vs-fine-tuning?lang=en',
      inLanguage: 'en',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
      headline: 'Prompt Engineering vs Fine-Tuning',
      description: 'Decision guide comparing prompt engineering and fine-tuning approaches.',
      datePublished: '2026-04-10',
      dateModified: '2026-05-04',
      keywords: ['prompt engineering', 'fine-tuning', 'decision guide', 'cost comparison'],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      about: [
        { '@type': 'Thing', name: 'Prompt Engineering' },
        { '@type': 'Thing', name: 'Fine-Tuning' },
        { '@type': 'Thing', name: 'Large Language Models' },
      ],
      mentions: [
        { '@type': 'SoftwareApplication', name: 'Proprietary Language Models', url: 'https://openai.com' },
        { '@type': 'SoftwareApplication', name: 'Open Source Language Models', url: 'https://huggingface.co' },
        { '@type': 'SoftwareApplication', name: 'Local Model Deployment', url: 'https://ollama.com' },
        { '@type': 'SoftwareApplication', name: 'Model Fine-Tuning Techniques', url: 'https://huggingface.co' },
      ],
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        { '@type': 'Question', name: 'Should I use prompt engineering or fine-tuning?', acceptedAnswer: { '@type': 'Answer', text: 'Try prompt engineering first. It is free and instant. Only fine-tune if prompt engineering fails on repeated attempts.' } },
        { '@type': 'Question', name: 'How much does fine-tuning cost?', acceptedAnswer: { '@type': 'Answer', text: 'Fine-tuning requires significant investment depending on model provider, data size, and infrastructure requirements.' } },
        { '@type': 'Question', name: 'How long does fine-tuning take?', acceptedAnswer: { '@type': 'Answer', text: 'Fine-tuning takes substantial time (weeks to months), while prompt engineering takes minutes to hours.' } },
        { '@type': 'Question', name: 'Can I undo fine-tuning?', acceptedAnswer: { '@type': 'Answer', text: 'No. Fine-tuning permanently changes model weights. You cannot easily revert to the original state.' } },
      ],
    },
    sections: {
      keyTakeaways: {
        isTldr: true,
        title: 'Key Takeaways',
        id: 'key-takeaways',
        items: [
          'Prompt engineering is free, instant, and reversible. Fine-tuning requires investment, takes time, and is permanent.',
          'Test prompt engineering first on 10-20 examples. Only fine-tune if it fails repeatedly.',
          'The 90% rule: 90 percent of use cases solve with good prompt engineering alone.',
          'Fine-tuning is best for domain-specific terminology, niche knowledge, or strict output formatting.',
          'Cost matters: Effective prompt engineering avoids significant fine-tuning investments.',
          'Maintenance trap: Fine-tuned models require constant updates as model evolution occurs.',
          'Combine both: Use prompt engineering for flexibility, fine-tuning for specialization.',
        ],
      },
      introduction: {
        title: 'Why This Decision Matters',
        snippets: [
          { type: 'in-one-sentence', text: 'Prompt engineering is your first choice (free, instant); fine-tuning is your backup when prompting fails (expensive, permanent).' },
          { type: 'in-plain-terms', text: 'Writing a better instruction to an AI costs nothing and takes minutes. Training the AI costs hundreds or thousands and takes days. Try the cheap option first.' },
        ],
        content: [
          'You have two paths to improve AI output: change how you ask (prompt engineering) or change the AI itself (fine-tuning). The wrong choice costs time and money. This guide shows you which path to take.',
        ],
      },
      promptEngineeringExplained: {
        title: 'What Is Prompt Engineering?',
        content: [
          'Prompt engineering means writing clear, detailed instructions to an AI model. Instead of saying "summarize this", you write: "Summarize the following text in 2-3 sentences. Focus on the main decision and who made it. Avoid jargon."',
          'Every prompt is an experiment. You try it, see the output, adjust the wording, and try again. Prompt engineering is free because you are not training the model—you are just talking to it better.',
        ],
        items: [
          'Free: No training costs, only inference (using) the model',
          'Instant: Takes minutes to hours to refine, not days or weeks',
          'Reversible: Bad prompt? Just delete it and try a new one',
          'Testable: You can A/B test multiple versions quickly',
          'Portable: Same prompt often works across different models',
          'Model-agnostic: Techniques work consistently across proprietary and open-source models',
        ],
      },
      fineTuningExplained: {
        title: 'What Is Fine-Tuning?',
        content: [
          'Fine-tuning means retraining the model on your own data. You provide hundreds or thousands of examples of inputs and desired outputs, and the model learns from them. It permanently changes the model weights.',
          'Fine-tuning is necessary only when prompt engineering fails on systematic problems that affect 10+ percent of cases. Common reasons: domain-specific terminology, very strict output formatting, or specialized reasoning patterns the base model has never seen.',
        ],
        items: [
          'Expensive: Requires significant investment per training run',
          'Slow: Takes substantial time to complete',
          'Permanent: Changes the model weights—very hard to undo',
          'Data-hungry: Requires hundreds or thousands of labeled examples',
          'Expensive inference: Inference (using) the model also costs more',
          'Version-locked: Each model version may require separate fine-tuning',
        ],
        callouts: [
          { type: '🔍', label: 'Fine-Tuning Is Not RAG', text: 'Retrieval-Augmented Generation (RAG) and fine-tuning solve different problems. RAG inserts relevant context into the prompt—it is a prompt engineering technique. Fine-tuning retrains the model. Use RAG first. Only fine-tune if RAG and prompt engineering both fail.' },
        ],
      },
      headToHeadComparison: {
        title: 'Side-by-Side Comparison',
        id: 'comparison-table',
        tableFormat: true,
        columns: ['Factor', 'Prompt Engineering', 'Fine-Tuning'],
        rows: [
          { 'Factor': 'Cost', 'Prompt Engineering': '$0 (only inference)', 'Fine-Tuning': '$500-$5000+ per run' },
          { 'Factor': 'Speed', 'Prompt Engineering': 'Minutes to hours', 'Fine-Tuning': 'Days to weeks' },
          { 'Factor': 'Reversibility', 'Prompt Engineering': 'Delete and start over', 'Fine-Tuning': 'Permanent changes' },
          { 'Factor': 'Data needed', 'Prompt Engineering': '3-10 examples for testing', 'Fine-Tuning': '100-10000+ labeled examples' },
          { 'Factor': 'Expertise', 'Prompt Engineering': 'Anyone can do it', 'Fine-Tuning': 'Requires ML knowledge' },
          { 'Factor': 'Model portability', 'Prompt Engineering': 'Works on GPT, Claude, local models', 'Fine-Tuning': 'Locked to one model/version' },
          { 'Factor': 'Success rate', 'Prompt Engineering': 'Solves 80-90% of cases', 'Fine-Tuning': 'Solves remaining 10-20%' },
          { 'Factor': 'Maintenance', 'Prompt Engineering': 'Adjust prompt when model updates', 'Fine-Tuning': 'Retrain entire model per version' },
          { 'Factor': 'Testing', 'Prompt Engineering': 'Test 10 versions in 1 hour', 'Fine-Tuning': 'Test 10 versions in 10 days' },
          { 'Factor': 'Inference cost', 'Prompt Engineering': 'Standard pricing', 'Fine-Tuning': 'Custom pricing (usually higher)' },
        ],
      },
      decisionFlowchart: {
        title: 'Decision Flowchart: When to Use Each Approach',
        id: 'decision-flowchart',
        content: [
          'Follow this flowchart to decide whether to prompt engineer or fine-tune.',
        ],
        numberedItems: [
          'Start with a clear problem statement. Example: "Summarize customer reviews into exactly 2 sentences."',
          'Write 10-20 example prompts and test on 10 examples using the base model. If 8/10 succeed, stop. You are done with prompt engineering.',
          'If fewer than 8/10 succeed, try improving the prompt. Add context, examples, constraints, and output format. Run another 10 test cases.',
          'After 3-5 prompt iterations, if success rate is still below 80%, consider fine-tuning.',
          'If fine-tuning: collect 100-500 labeled examples (input-output pairs). Train a custom model. Test on a hold-out set.',
          'Choose the approach with the best cost-to-quality ratio.',
        ],
        callouts: [
          { type: '🔍', label: 'The 90% Test', text: 'Ask yourself: Do I need to fix 90% of cases, or just 10%? If 90% of cases work with prompt engineering, stop. If 90% fail, you have a bigger problem than fine-tuning can solve alone.' },
        ],
      },
      fiveScenarios: {
        title: 'Five Real-World Scenarios',
        content: [
          'Here are five realistic decisions teams face and how to approach each.',
        ],
        numberedItems: [
          'Extracting structured data from messy PDFs: Try prompt engineering with examples first. If success rate exceeds 85%, stop. If it stalls at 60%, add fine-tuning on domain-specific variations.',
          'Classifying customer support tickets into categories: Use prompt engineering with examples of each category. Cost: $0. Effort: 2 hours. Fine-tuning would cost $1000+ and take 1 week.',
          'Generating specialized legal clauses: Prompt engineering fails because the base model is too generic. Fine-tune on 500 historical documents in your company style. Cost justified: $2000.',
          'Summarizing long research papers into key insights: Prompt engineering works well. Chain-of-thought prompting + examples = 92% accuracy. No fine-tuning needed.',
          'Translating technical docs into plain English: Prompt engineering + few-shot examples covers 88% of cases. Fine-tune on remaining 12% of edge cases.',
        ],
      },
      whenToCombine: {
        title: 'Using Both: When and How to Combine',
        content: [
          'Best practice: Start with prompt engineering. If it hits a ceiling (around 80-85% success), add fine-tuning on top.',
          'Workflow: Use a fine-tuned model inside a prompt engineering loop. The fine-tuned model handles specialized tasks, while a prompt engineer adds context and routing logic.',
        ],
        items: [
          'Use prompt engineering to route requests: "Is this a legal document, medical note, or financial report?"',
          'Use fine-tuning for specialized models: A fine-tuned legal model, a fine-tuned medical model, a fine-tuned finance model.',
          'Use prompt engineering for output formatting: Even a fine-tuned model benefits from clear format instructions.',
          'Combine for cost: Fine-tune on 10% of edge cases, route 90% through cheaper prompt engineering.',
        ],
        callouts: [
          { type: '🔍', label: 'The Maintenance Trap', text: 'Each time a new model version releases, fine-tuned models become obsolete. You must retrain them. Prompt engineering requires only tweaks. Budget for annual fine-tuning retraining costs—they add up.' },
        ],
      },
      costComparison: {
        title: 'Cost Structure Comparison',
        id: 'cost-table',
        tableFormat: true,
        columns: ['Provider Type', 'Prompt Engineering Cost', 'Fine-Tuning Cost', 'Inference Cost'],
        rows: [
          { 'Provider Type': 'Proprietary models', 'Prompt Engineering Cost': 'Low per inference', 'Fine-Tuning Cost': 'Significant upfront investment', 'Inference Cost': 'Higher for fine-tuned models' },
          { 'Provider Type': 'Open-source cloud', 'Prompt Engineering Cost': 'Low per inference', 'Fine-Tuning Cost': 'Moderate investment', 'Inference Cost': 'Variable by provider' },
          { 'Provider Type': 'Self-hosted local', 'Prompt Engineering Cost': 'Minimal (your hardware)', 'Fine-Tuning Cost': 'Hardware cost + time', 'Inference Cost': 'One-time hardware investment' },
          { 'Provider Type': 'Hybrid approach', 'Prompt Engineering Cost': 'Low initial cost', 'Fine-Tuning Cost': 'Distributed over time', 'Inference Cost': 'Balanced cost-benefit' },
        ],
        callouts: [
          { type: '🔍', label: 'Cost Structure', text: 'Prompt engineering costs are variable (per inference). Fine-tuning costs are front-loaded (training) plus ongoing inference. The cost-benefit ratio favors prompt engineering for most use cases, with fine-tuning adding value only when specialized performance is critical.' },
        ],
      },
      commonMistakes: {
        title: 'Five Common Mistakes',
        id: 'mistakes',
        mistakes: [
          { mistake: 'Fine-tuning before testing prompts', problem: 'Teams jump to fine-tuning without seriously iterating on prompts. Result: $3000 spent on fine-tuning when $0 prompt engineering would have worked.', fix: 'Test prompt engineering first. Run 30-50 examples with 3-5 prompt variations. Only fine-tune if the best prompt still fails 20%+ of the time.' },
          { mistake: 'Training on small datasets', problem: 'Fine-tuning on 20 examples per class. Result: Overfitting, model fails on new examples.', fix: 'Collect at least 100 examples per category. Ideally 500+. Check that your training and test distributions match real-world data.' },
          { mistake: 'Forgetting inference costs', problem: 'Teams calculate fine-tuning cost ($2000) but forget that fine-tuned models cost 2-3x more to run.', fix: 'Calculate total cost of ownership: training + (inference cost per call × expected volume × time horizon).' },
          { mistake: 'Ignoring model versioning', problem: 'A fine-tuned model works great, then GPT-4o is updated. The fine-tuned model is now outdated and must be retrained.', fix: 'Budget for annual retraining or migration to new models. Document which base model version each fine-tune is for.' },
          { mistake: 'Fine-tuning the wrong model', problem: 'Fine-tuning a model that is too small for the task (e.g., a 7B model for complex reasoning).', fix: 'Start with the largest model you can afford. Fine-tune to optimize cost, not to fix a weak base model.' },
        ],
      },
      faqSection: {
        title: 'Frequently Asked Questions',
        id: 'faq',
        faqs: [
          { q: 'Which approach should I try first?', a: 'Always start with prompt engineering. It is free, instant, and reversible. Only move to fine-tuning if prompt engineering fails on repeated attempts.' },
          { q: 'How do I get training data for fine-tuning?', a: 'Collect your own examples, use existing datasets, or hire annotators. Data quality matters more than quantity.' },
          { q: 'Can I fine-tune a fine-tuned model?', a: 'Technically yes, but it is rarely needed. Usually, fine-tune once on your best data.' },
          { q: 'What is LoRA fine-tuning?', a: 'Low-Rank Adaptation is a technique that fine-tunes only a portion of the model, reducing resource requirements and cost.' },
          { q: 'Should I fine-tune locally or in the cloud?', a: 'Cloud-based fine-tuning is easier and faster. Local fine-tuning gives you control over data privacy and infrastructure.' },
          { q: 'How long does fine-tuning take?', a: 'Fine-tuning takes substantial time—weeks to months depending on data size, model size, and hardware.' },
          { q: 'What if fine-tuning does not help?', a: 'You may have the wrong base model, insufficient training data, or unrealistic expectations. Try a larger model or more data first.' },
          { q: 'Can I combine prompt engineering with fine-tuning?', a: 'Yes, this is best practice. Use fine-tuning for core competence, prompt engineering for flexibility and routing logic.' },
        ],
      },
      relatedReading: {
        title: 'Related Articles',
        id: 'related',
        items: [
          { title: 'How to Write Effective Prompts', url: '/prompt-engineering/how-to-write-effective-prompts' },
          { title: 'Prompt Engineering Frameworks', url: '/prompt-engineering/frameworks' },
          { title: 'Cost Optimization for LLMs', url: '/prompt-engineering/cost-optimization' },
          { title: 'Building RAG Systems', url: '/prompt-engineering/retrieval-augmented-generation' },
          { title: 'Model Selection Guide', url: '/prompt-engineering/model-selection' },
          { title: 'LLM API Benchmarks', url: '/prompt-engineering/llm-api-benchmarks' },
        ],
      },
    },
  },
  de: {
    freshness_tier: 'evergreen',
    theme: 'Tools & Platforms',
    title: 'Prompt Engineering vs Fine-Tuning: Wann prompen, wann trainieren',
    intro: 'Prompt Engineering und Fine-Tuning sind zwei grundverschiedene Ansätze zur Verbesserung von Modellausgaben. Prompt Engineering ist kostenlos, sofort und rückgängig machbar. Fine-Tuning erfordert erhebliche Investitionen, dauert längere Zeit und ist schwer rückgängig zu machen. Dieser Leitfaden zeigt, wann jeder Ansatz gewinnt.',
    publishDate: '2026-04-10',
    dateModified: '2026-05-04',
    readTime: '9 Min. Lesezeit',
    educationalLevel: 'Intermediate',
    seoTitle: 'Prompt Engineering vs Fine-Tuning: Wann prompen, wann trainieren',
    metaDescription: 'Entscheidungsleitfaden: Prompt Engineering vs Fine-Tuning. Kosten (0 € vs 500-5000+ €), Zeit, Reversibilität und DSGVO-Compliance. Mit Entscheidungsdiagramm.',
    ogDescription: 'Prompt Engineering oder Fine-Tuning? Vergleich von Kosten, Zeit und Reversibilität mit Entscheidungsdiagramm.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-engineering-vs-fine-tuning?lang=de',
      inLanguage: 'de',
      headline: 'Prompt Engineering vs Fine-Tuning: Wann prompen, wann trainieren',
      description: 'Entscheidungsleitfaden für Prompt Engineering und Fine-Tuning.',
      datePublished: '2026-04-10',
      dateModified: '2026-05-04',
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'de',
      mainEntity: [
        { '@type': 'Question', name: 'Sollte ich Prompt Engineering oder Fine-Tuning nutzen?', acceptedAnswer: { '@type': 'Answer', text: 'Versuchen Sie zuerst Prompt Engineering. Es ist kostenlos und sofort. Fine-tunen Sie nur, wenn Prompt Engineering nach wiederholten Versuchen fehlschlagt.' } },
        { '@type': 'Question', name: 'Wie viel kostet Fine-Tuning?', acceptedAnswer: { '@type': 'Answer', text: 'Fine-Tuning kostet 500-5000+ Euro je nach Modell, Datengre und Infrastruktur.' } },
        { '@type': 'Question', name: 'Wie lange dauert Fine-Tuning?', acceptedAnswer: { '@type': 'Answer', text: 'Fine-Tuning dauert Tage oder Wochen, wahrend Prompt Engineering nur Minuten dauert.' } },
        { '@type': 'Question', name: 'Kann ich Fine-Tuning ruckgangig machen?', acceptedAnswer: { '@type': 'Answer', text: 'Nein. Fine-Tuning andert die Modellgewichte dauerhaft. Sie konnen dies nicht leicht ruckgangig machen.' } },
        { '@type': 'Question', name: 'Was ist LoRA Fine-Tuning?', acceptedAnswer: { '@type': 'Answer', text: 'Low-Rank Adaptation (LoRA) fine-tuned nur einen Teil des Modells und reduziert Kosten und Datenanforderungen.' } },
        { '@type': 'Question', name: 'Sollte ich lokal oder in der Cloud fine-tunen?', acceptedAnswer: { '@type': 'Answer', text: 'Cloud Fine-Tuning (OpenAI, Google) ist einfacher und schneller. Lokales Fine-Tuning gibt Ihnen Kontrolle und Datenschutz.' } },
        { '@type': 'Question', name: 'Wie lange dauert Fine-Tuning?', acceptedAnswer: { '@type': 'Answer', text: 'Normalerweise 1-7 Tage je nach Datengre, Modellgre und Hardware.' } },
        { '@type': 'Question', name: 'Kann ich Prompt Engineering und Fine-Tuning kombinieren?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, das ist Best Practice. Verwenden Sie Fine-Tuning fur Kernkompetenz und Prompt Engineering fur Flexibilitat und Routing.' } },
        { '@type': 'Question', name: 'Muss ich DSGVO bei der Nutzung beachten?', acceptedAnswer: { '@type': 'Answer', text: 'Ja. Nach DSGVO Artikel 28 erfordert die Verwendung von Large Language Models besondere Aufmerksamkeit auf Datenverarbeitung und Compliance. Lokales Fine-Tuning kann DSGVO-Anforderungen erfullen, da Daten nicht an externe APIs ubertragen werden.' } },
        { '@type': 'Question', name: 'Ist Fine-Tuning fur den deutschen Mittelstand geeignet?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, insbesondere fur Unternehmen, die BSI-Grundschutz einhalten mussen. Fine-Tuning ermoglicht lokale Kontrolle, Datenschutz und Compliance gemass DSGVO und BSI-Katalogen.' } },
      ],
    },
    sections: {
      keyTakeaways: {
        isTldr: true,
        title: 'Zusammenfassung',
        id: 'key-takeaways',
        items: [
          'Prompt Engineering ist kostenlos, sofort und rückgängig machbar. Fine-Tuning ist teuer, langsam und dauerhaft.',
          'Testen Sie zuerst Prompt Engineering an 10-20 Beispielen. Fine-tunen Sie nur, wenn es wiederholt fehlschlägt.',
          'Die 90%-Regel: 90 Prozent der Anwendungsfälle werden allein durch gutes Prompt Engineering gelöst.',
          'Fine-Tuning eignet sich am besten für domänenspezifische Terminologie, Nischenwissen oder strikte Ausgabeformatierung.',
          'Gutes Prompt Engineering spart 500+ Euro an Fine-Tuning-Kosten.',
          'Wartungsfalle: Fine-abgestimmte Modelle erfordern konstante Updates bei neuen Modellversionen.',
          'Kombinieren Sie beide: Nutzen Sie Prompt Engineering für Flexibilität und Fine-Tuning für Spezialisierung.',
        ],
      },
      introduction: {
        title: 'Warum diese Entscheidung wichtig ist',
        snippets: [
          { type: 'in-one-sentence', text: 'Prompt Engineering ist Ihre erste Wahl (kostenlos, sofort). Fine-Tuning ist Ihr Backup, wenn Prompting fehlschlägt (teuer, dauerhaft).' },
          { type: 'in-plain-terms', text: 'Eine bessere Anweisung für ein KI-Modell schreiben kostet nichts und dauert Minuten. Das Modell trainieren kostet Hunderte oder Tausende Euro und dauert Tage. Versuchen Sie zuerst die günstige Option.' },
        ],
        content: [
          'Sie haben zwei Wege, um KI-Ausgaben zu verbessern: Änderung der Fragestellung (Prompt Engineering) oder Änderung des Modells selbst (Fine-Tuning). Die falsche Wahl kostet Zeit und Geld. Dieser Leitfaden zeigt, welchen Weg Sie nehmen sollten.',
        ],
      },
      promptEngineeringExplained: {
        title: 'Was ist Prompt Engineering?',
        content: [
          'Prompt Engineering bedeutet, klare, detaillierte Anweisungen an ein KI-Modell zu schreiben. Statt "Fassen Sie dies zusammen", schreiben Sie: "Fassen Sie den folgenden Text in 2-3 Sätzen zusammen. Konzentrieren Sie sich auf die Hauptentscheidung und wer sie traf. Vermeiden Sie Fachjargon."',
          'Jeder Prompt ist ein Experiment. Sie versuchen es, sehen das Ergebnis, passen die Formulierung an und versuchen es erneut. Prompt Engineering ist kostenlos, weil Sie das Modell nicht trainieren—Sie sprechen nur besser mit ihm.',
        ],
        items: [
          'Kostenlos: Keine API-Trainingskosten, nur Inferenzkosten (Modellnutzung)',
          'Sofort: Dauert Minuten bis Stunden zum Verfeinern, nicht Tage oder Wochen',
          'Reversibel: Schlechter Prompt? Löschen Sie ihn einfach und versuchen Sie einen neuen',
          'Testbar: Sie können 10 Versionen in einer Stunde A/B-testen',
          'Portabel: Derselbe Prompt funktioniert oft auf verschiedenen Modellen',
          'Modellunabhängig: Techniken funktionieren auf GPT-4o, Claude, Gemini und lokalen Modellen',
        ],
      },
      fineTuningExplained: {
        title: 'Was ist Fine-Tuning?',
        content: [
          'Fine-Tuning bedeutet, das Modell mit Ihren eigenen Daten umzuschulen. Sie stellen Hunderte oder Tausende von Beispielen mit Ein- und Ausgaben bereit, und das Modell lernt davon. Es ändert dauerhaft die Modellgewichte.',
          'Fine-Tuning ist nur notwendig, wenn Prompt Engineering bei systematischen Problemen fehlschlägt, die 10+ Prozent der Fälle beeinflussen. Häufige Gründe: domänenspezifische Terminologie, sehr strikte Ausgabeformatierung oder spezialisierte Reasoning-Muster, die das Basismodell nie gesehen hat.',
        ],
        items: [
          'Teuer: 500-5000+ Euro pro Trainerlauf abhängig von Datengröße',
          'Langsam: Dauert Tage oder Wochen',
          'Dauerhaft: Ändert die Modellgewichte—sehr schwer rückgängig zu machen',
          'Datenintensiv: Erfordert Hunderte oder Tausende beschriftete Beispiele',
          'Teure Inferenz: Die Modellnutzung kostet auch mehr',
          'Versionsggebunden: Jede Modellversion erfordert separates Fine-Tuning',
        ],
      },
      headToHeadComparison: {
        title: 'Vergleich nebeneinander',
        id: 'comparison-table',
        tableFormat: true,
        columns: ['Faktor', 'Prompt Engineering', 'Fine-Tuning'],
        rows: [
          { 'Faktor': 'Kosten', 'Prompt Engineering': '0 Euro (nur Inferenz)', 'Fine-Tuning': '500-5000+ Euro pro Lauf' },
          { 'Faktor': 'Geschwindigkeit', 'Prompt Engineering': 'Minuten bis Stunden', 'Fine-Tuning': 'Tage bis Wochen' },
          { 'Faktor': 'Reversibilität', 'Prompt Engineering': 'Löschen und neu beginnen', 'Fine-Tuning': 'Dauerhafte Änderungen' },
          { 'Faktor': 'Erforderliche Daten', 'Prompt Engineering': '3-10 Beispiele zum Testen', 'Fine-Tuning': '100-10000+ beschriftete Beispiele' },
          { 'Faktor': 'Erfordertes Wissen', 'Prompt Engineering': 'Jeder kann es tun', 'Fine-Tuning': 'Erfordert ML-Kenntnisse' },
          { 'Faktor': 'Modellportabilität', 'Prompt Engineering': 'Funktioniert auf GPT, Claude, lokalen Modellen', 'Fine-Tuning': 'Gebunden an ein Modell/eine Version' },
          { 'Faktor': 'Erfolgsquote', 'Prompt Engineering': 'Löst 80-90% der Fälle', 'Fine-Tuning': 'Löst restliche 10-20%' },
          { 'Faktor': 'Wartung', 'Prompt Engineering': 'Prompt anpassen bei Modellupdate', 'Fine-Tuning': 'Gesamtes Modell pro Version neu trainieren' },
          { 'Faktor': 'Testen', 'Prompt Engineering': '10 Versionen in 1 Stunde testen', 'Fine-Tuning': '10 Versionen in 10 Tagen testen' },
          { 'Faktor': 'Inferenzkosten', 'Prompt Engineering': 'Standardpreise', 'Fine-Tuning': 'Benutzerdefinierte Preise (meist höher)' },
        ],
      },
      costComparison: {
        title: 'Realistische Kostenaufschlüsselung (2026)',
        id: 'cost-table',
        tableFormat: true,
        columns: ['Anbieter', 'Prompt Engineering (1M Token)', 'Fine-Tuning (Training)', 'Fine-Tuned Inferenz (1M Token)'],
        rows: [
          { 'Anbieter': 'OpenAI GPT-4o', 'Prompt Engineering (1M Token)': '13 Euro', 'Fine-Tuning (Training)': '1300-2600 Euro', 'Fine-Tuned Inferenz (1M Token)': '26-52 Euro' },
          { 'Anbieter': 'Anthropic Claude', 'Prompt Engineering (1M Token)': '7 Euro', 'Fine-Tuning (Training)': 'Nicht verfügbar', 'Fine-Tuned Inferenz (1M Token)': 'N/A' },
          { 'Anbieter': 'Google Vertex AI', 'Prompt Engineering (1M Token)': '0,90 Euro', 'Fine-Tuning (Training)': '450-1800 Euro', 'Fine-Tuned Inferenz (1M Token)': '1,80-4,50 Euro' },
          { 'Anbieter': 'Open Source (Ollama)', 'Prompt Engineering (1M Token)': '0 Euro', 'Fine-Tuning (Training)': 'Kostenlos (Ihre Hardware)', 'Fine-Tuned Inferenz (1M Token)': '0 Euro' },
          { 'Anbieter': 'AWS Bedrock', 'Prompt Engineering (1M Token)': '0,67 Euro', 'Fine-Tuning (Training)': '450-2700 Euro', 'Fine-Tuned Inferenz (1M Token)': '1,35-5,40 Euro' },
        ],
      },
      faqSection: {
        title: 'Häufig gestellte Fragen',
        id: 'faq',
        faqs: [
          { q: 'Kann ich Claude fine-tunen?', a: 'Seit 2026 bietet Anthropic kein Fine-Tuning für Claude an. Verwenden Sie stattdessen Prompt Engineering.' },
          { q: 'Wie erhalte ich Trainingsdaten für Fine-Tuning?', a: 'Sammeln Sie Ihre eigenen Beispiele, verwenden Sie vorhandene Datensätze oder stellen Sie Annotatoren ein. Datenqualität ist wichtiger als Quantität.' },
          { q: 'Kann ich ein Fine-Tuned-Modell erneut fine-tunen?', a: 'Technisch ja, aber es ist selten notwendig. Normalerweise fine-tunen Sie einmal auf Ihren besten Daten.' },
          { q: 'Was ist LoRA Fine-Tuning?', a: 'Low-Rank Adaptation (LoRA) fine-tuned nur einen kleinen Teil des Modells und reduziert damit Kosten und Datenanforderungen.' },
          { q: 'Sollte ich lokal oder in der Cloud fine-tunen?', a: 'Cloud Fine-Tuning (OpenAI, Google) ist einfacher und schneller. Lokales Fine-Tuning (Ollama, PEFT) gibt Ihnen Kontrolle und Datenschutz gemäß DSGVO.' },
          { q: 'Wie lange dauert Fine-Tuning?', a: 'Normalerweise 1-7 Tage je nach Datengröße, Modellgröße und Hardware.' },
          { q: 'Was tun, wenn Fine-Tuning nicht hilft?', a: 'Sie haben möglicherweise das falsche Basismodell, unzureichende Trainingsdaten oder unrealistische Erwartungen. Versuchen Sie zunächst ein größeres Modell oder mehr Daten.' },
          { q: 'Kann ich Prompt Engineering mit Fine-Tuning kombinieren?', a: 'Ja, das ist Best Practice. Verwenden Sie Fine-Tuning für Kernkompetenz und Prompt Engineering für Flexibilität und Routing.' },
          { q: 'Muss ich bei der Nutzung von Fine-Tuning die DSGVO beachten?', a: 'Ja. Nach DSGVO Artikel 28 erfordert die Verwendung von Large Language Models und deren Fine-Tuning besondere Aufmerksamkeit auf Datenverarbeitung und Compliance. Lokales Fine-Tuning mit BSI-Grundschutz-Konformität kann DSGVO-Anforderungen erfüllen, da Daten nicht an externe APIs übertragen werden.' },
          { q: 'Ist Fine-Tuning für den deutschen Mittelstand geeignet?', a: 'Ja, besonders für Unternehmen, die BSI-Grundschutz einhalten müssen. Fine-Tuning ermöglicht lokale Kontrolle, Datenschutz und Compliance gemäß DSGVO und BSI-Sicherheitskatalogen. Viele deutsche Mittelstandsunternehmen in Finance, Engineering und Healthcare können von lokaler Modellkontrolle profitieren.' },
        ],
      },
      regionalContext: {
        title: 'DACH-Kontext: Datenschutz und Enterprise-Anforderungen',
        content: [
          'In Deutschland, Österreich und der Schweiz sind Fine-Tuning und Prompt Engineering unter DSGVO und BSI-Grundschutz-Anforderungen unterschiedlich zu bewerten. Fine-Tuning mit lokalen Modellen (z. B. Ollama, lokale LoRA-Adapter) erfüllt Datenschutzanforderungen besser, da Trainingsdaten nicht an US-amerikanische Cloud-Provider übertragen werden. Prompt Engineering mit privaten APIs (selbstgehostete Modelle) ist ideal für regulierte Branchen wie Finanzdienstleistungen, Medizin und Rechtsberatung.',
        ],
      },
    },
  },
  fr: {
    freshness_tier: 'evergreen',
    theme: 'Tools & Platforms',
    title: 'Prompt Engineering vs Fine-Tuning : Quand prompter, quand entraîner',
    intro: 'Le prompt engineering et le fine-tuning sont deux approches fondamentalement différentes pour améliorer les résultats. Le prompt engineering est gratuit, instantané et réversible. Le fine-tuning requiert un investissement significatif, prend du temps, et est difficile à annuler.',
    publishDate: '2026-04-10',
    dateModified: '2026-05-04',
    readTime: '8 min de lecture',
    educationalLevel: 'Intermediate',
    seoTitle: 'Prompt Engineering vs Fine-Tuning : Quand prompter, quand entraîner',
    metaDescription: 'Guide de décision : prompt engineering vs fine-tuning. Coûts (0 € vs 500-5000+ €), temps, réversibilité, CNIL. Diagramme de décision inclus.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-engineering-vs-fine-tuning?lang=fr',
      inLanguage: 'fr',
      headline: 'Prompt Engineering vs Fine-Tuning : Quand prompter, quand entraîner',
      description: 'Guide de décision pour le prompt engineering et le fine-tuning.',
      datePublished: '2026-04-10',
      dateModified: '2026-05-04',
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'fr',
      mainEntity: [
        { '@type': 'Question', name: 'Devrais-je utiliser le prompt engineering ou le fine-tuning ?', acceptedAnswer: { '@type': 'Answer', text: 'Essayez d\'abord le prompt engineering. C\'est gratuit et immédiat. Fine-tunez seulement s\'il échoue après plusieurs tentatives.' } },
      ],
    },
    sections: {
      keyTakeaways: {
        isTldr: true,
        title: 'Points clés',
        id: 'key-takeaways',
        items: [
          'Prompt engineering : gratuit, immédiat, réversible. Fine-tuning : coûteux, lent, permanent.',
          'Testez d\'abord le prompt engineering sur 10-20 exemples. Ne fine-tunez que s\'il échoue répétitivement.',
          'La règle 90 % : 90 % des cas se résolvent avec un excellent prompt engineering seul.',
          'Le fine-tuning convient aux termes spécialisés, aux connaissances de niche et aux formats stricts.',
          'Un bon prompt engineering économise 500+ euros de fine-tuning.',
          'Piège maintenance : les modèles fine-tunés nécessitent des mises à jour constantes.',
          'Combinez les deux : prompt engineering pour la flexibilité, fine-tuning pour la spécialisation.',
        ],
      },
      introduction: {
        title: 'Pourquoi cette décision compte',
        snippets: [
          { type: 'in-one-sentence', text: 'Le prompt engineering est votre premier choix (gratuit, immédiat) ; le fine-tuning est votre recours quand celui-ci échoue (coûteux, définitif).' },
          { type: 'in-plain-terms', text: 'Écrire une meilleure instruction à une IA ne coûte rien et prend quelques minutes. Entraîner l\'IA coûte des centaines ou des milliers d\'euros et prend plusieurs jours. Essayez d\'abord l\'option bon marché.' },
        ],
        content: [
          'Vous avez deux chemins pour améliorer les résultats : reformuler votre demande ou modifier le modèle lui-même. Le mauvais choix gaspille du temps et de l\'argent. Ce guide montre quelle approche adopter.',
        ],
      },
      promptEngineeringExplained: {
        title: 'Qu\'est-ce que le prompt engineering ?',
        content: [
          'Le prompt engineering consiste à écrire des instructions claires et détaillées à un modèle IA. Au lieu de dire « résume ceci », vous écrivez : « Résume le texte suivant en 2-3 phrases. Concentre-toi sur la décision principale et qui l\'a prise. Évite le jargon technique. »',
          'Chaque prompt est une expérience. Vous essayez, observez le résultat, affinez la formulation et réessayez. Le prompt engineering est gratuit car vous ne cherchez pas à entraîner le modèle—vous lui parlez simplement mieux.',
        ],
        items: [
          'Gratuit : pas de coûts d\'entraînement API, seulement inférence',
          'Instantané : quelques minutes à quelques heures, pas des jours',
          'Réversible : mauvais prompt ? Supprimez-le et essayez un nouveau',
          'Testable : comparez 10 versions en une heure',
          'Portable : le même prompt fonctionne souvent sur différents modèles',
          'Agnostique : techniques fonctionnent sur GPT-4o, Claude, Gemini, modèles locaux',
        ],
      },
      fineTuningExplained: {
        title: 'Qu\'est-ce que le fine-tuning ?',
        content: [
          'Le fine-tuning signifie réentraîner le modèle sur vos propres données. Vous fournissez des centaines ou milliers d\'exemples d\'entrée-sortie, et le modèle apprend. Cela change définitivement les poids du modèle.',
          'Le fine-tuning ne devient nécessaire que si le prompt engineering échoue systématiquement (affectant 10%+ des cas). Raisons courantes : terminologie spécialisée, formatage strict, ou patterns de raisonnement que le modèle n\'a jamais vus.',
        ],
        items: [
          'Coûteux : 500-5000+ euros par entraînement',
          'Lent : des jours ou semaines',
          'Permanent : change les poids—très difficile à défaire',
          'Demande beaucoup de données : 100-10000+ exemples étiquetés',
          'Inférence chère : l\'utilisation du modèle coûte aussi plus cher',
          'Verrouillé à une version : chaque version de modèle nécessite un fine-tuning séparé',
        ],
      },
      headToHeadComparison: {
        title: 'Comparaison directe',
        id: 'comparison-table',
        tableFormat: true,
        columns: ['Critère', 'Prompt Engineering', 'Fine-tuning'],
        rows: [
          { 'Critère': 'Coût', 'Prompt Engineering': '0 euro (inférence)', 'Fine-tuning': '500-5000+ euros' },
          { 'Critère': 'Vitesse', 'Prompt Engineering': 'Heures', 'Fine-tuning': 'Jours à semaines' },
          { 'Critère': 'Réversibilité', 'Prompt Engineering': 'Supprimer et recommencer', 'Fine-tuning': 'Permanent' },
          { 'Critère': 'Données', 'Prompt Engineering': '3-10 exemples', 'Fine-tuning': '100-10000+ exemples étiquetés' },
          { 'Critère': 'Expertise', 'Prompt Engineering': 'Tout le monde', 'Fine-tuning': 'Compétences ML requises' },
          { 'Critère': 'Portabilité', 'Prompt Engineering': 'GPT, Claude, Gemini, locaux', 'Fine-tuning': 'Modèle/version spécifique' },
          { 'Critère': 'Couverture', 'Prompt Engineering': '80-90% des cas', 'Fine-tuning': '10-20% restants' },
          { 'Critère': 'Maintenance', 'Prompt Engineering': 'Ajuster prompt', 'Fine-tuning': 'Réentraîner par version' },
          { 'Critère': 'Tests', 'Prompt Engineering': '10 versions/heure', 'Fine-tuning': '10 versions/10 jours' },
          { 'Critère': 'Inférence', 'Prompt Engineering': 'Prix standard', 'Fine-tuning': 'Prix personnalisés (+ cher)' },
        ],
      },
      faqSection: {
        title: 'Questions fréquentes',
        id: 'faq',
        faqs: [
          { q: 'Devrais-je utiliser le prompt engineering ou le fine-tuning ?', a: 'Essayez d\'abord le prompt engineering. C\'est gratuit et immédiat. Fine-tunez seulement s\'il échoue après plusieurs tentatives.' },
          { q: 'Combien coûte le fine-tuning ?', a: 'Entre 500 et 5000+ euros selon le modèle, la taille des données et l\'infrastructure.' },
          { q: 'Combien de temps prend le fine-tuning ?', a: 'Généralement 1-7 jours selon la taille des données, du modèle et du hardware.' },
          { q: 'Puis-je annuler le fine-tuning ?', a: 'Non. Le fine-tuning change définitivement les poids du modèle. C\'est très difficile à défaire.' },
          { q: 'Qu\'est-ce que le LoRA fine-tuning ?', a: 'Low-Rank Adaptation (LoRA) fine-tune seulement une petite partie du modèle, réduisant les coûts et les données nécessaires.' },
          { q: 'Devrais-je fine-tuner localement ou en cloud ?', a: 'Le cloud (OpenAI, Google) est plus facile et rapide. Le local (Ollama, PEFT) offre plus de contrôle et de confidentialité.' },
          { q: 'Comment obtenir des données pour le fine-tuning ?', a: 'Collectez vos propres exemples, utilisez des datasets existants, ou engagez des annotateurs. La qualité prime sur la quantité.' },
          { q: 'Puis-je combiner prompt engineering et fine-tuning ?', a: 'Oui, c\'est la meilleure pratique. Fine-tune pour les tâches spécialisées, utilisez le prompt engineering pour la flexibilité et le routage.' },
          { q: 'Le fine-tuning de Claude est-il disponible ?', a: 'Non. Depuis 2026, Anthropic n\'offre pas le fine-tuning de Claude. Utilisez le prompt engineering.' },
          { q: 'Quand le fine-tuning n\'aide pas, que faire ?', a: 'Vous avez peut-être le mauvais modèle, pas assez de données, ou des attentes irréalistes. Essayez d\'abord un modèle plus grand ou plus de données.' },
        ],
      },
      regionalContext: {
        title: 'Context francophone',
        content: [
          'La Commission nationale de l\'informatique et des libertés (CNIL) recommande l\'inférence locale pour les données sensibles professionnelles. Le fine-tuning local offre davantage de contrôle sur la confidentialité des données. Les organisations français, belges et suisses opérant sous ces directives devraient privilégier le prompt engineering public ou le fine-tuning sur infrastructure locale.',
        ],
      },
    },
  },
  ja: {
    freshness_tier: 'evergreen',
    theme: 'Tools & Platforms',
    title: 'プロンプトエンジニアリング vs ファインチューニング：使い分けガイド',
    intro: 'プロンプトエンジニアリングとファインチューニングは、AIモデル出力を改善するための根本的に異なる2つのアプローチです。プロンプトエンジニアリングは無料、即座、可逆的。ファインチューニングは相当な投資が必要で、時間がかかり、取り消しが困難です。',
    publishDate: '2026-04-10',
    dateModified: '2026-05-04',
    readTime: '10分で読める',
    educationalLevel: 'Intermediate',
    seoTitle: 'プロンプトエンジニアリング vs ファインチューニング：使い分けガイド',
    metaDescription: '判断ガイド：プロンプトエンジニアリング vs ファインチューニング。コスト比較（$0 vs $500+）、反復時間（時間 vs 週）、可逆性を解説。判断フローチャート付き。',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-engineering-vs-fine-tuning?lang=ja',
      inLanguage: 'ja',
      headline: 'プロンプトエンジニアリング vs ファインチューニング：使い分けガイド',
      description: 'プロンプトエンジニアリングとファインチューニングの判断ガイド。',
      datePublished: '2026-04-10',
      dateModified: '2026-05-04',
      author: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'ja',
      mainEntity: [
        { '@type': 'Question', name: 'プロンプトエンジニアリングとファインチューニングのどちらを使うべき？', acceptedAnswer: { '@type': 'Answer', text: 'まずプロンプトエンジニアリングを試してください。無料で即座です。何度も失敗した場合のみファインチューニングしてください。' } },
      ],
    },
    sections: {
      keyTakeaways: {
        isTldr: true,
        title: '重要ポイント',
        id: 'key-takeaways',
        items: [
          'プロンプトエンジニアリング：無料、即座、可逆的。ファインチューニング：高額、遅い、永続的',
          '最初に10-20個の例でプロンプトエンジニアリングをテスト。何度も失敗した場合のみファインチューニング',
          '90%ルール：90%のユースケースは優れたプロンプトエンジニアリングだけで解決',
          'ファインチューニングは、ドメイン固有の用語、ニッチな知識、厳密なフォーマットに適している',
          'よいプロンプトエンジニアリングは$500+のファインチューニングコストを節約',
          'メンテナンスの罠：ファインチューニングされたモデルは新バージョンごとに更新が必要',
          '両方を組み合わせる：柔軟性はプロンプトエンジニアリング、専門化はファインチューニング',
        ],
      },
      introduction: {
        title: 'この判断が重要な理由',
        snippets: [
          { type: 'in-one-sentence', text: 'プロンプトエンジニアリングが第一選択（無料、即座）；ファインチューニングは失敗時のバックアップ（高額、永続的）です。' },
          { type: 'in-plain-terms', text: 'AIモデルへの指示を改善することは無料で数分で可能です。モデルを訓練することは数百～数千円かかり、数日かかります。まず安い選択肢を試してください。' },
        ],
        content: [
          'AI出力を向上させるには2つの道があります：質問の方法を改善する（プロンプトエンジニアリング）か、モデル自体を変える（ファインチューニング）。間違った選択は時間と資金を浪費します。このガイドは、どのアプローチを採取するかを示します。',
        ],
      },
      promptEngineeringExplained: {
        title: 'プロンプトエンジニアリングとは',
        content: [
          'プロンプトエンジニアリングは、AIモデルに明確で詳細な指示を書くことです。「これを要約して」の代わりに「以下のテキストを2-3文で要約してください。主な決定とそれを下した人に焦点を当てます。専門用語は避けてください」と書きます。',
          'すべてのプロンプトは実験です。試して、結果を見て、表現を調整して、再度試します。プロンプトエンジニアリングはモデルを訓練していないため無料です—単によりよく話しているだけです。',
        ],
        items: [
          '無料：API訓練コストなし、推論コストのみ',
          '即座：数分～数時間で改善、日数や週ではない',
          '可逆的：悪いプロンプト？削除して新しいものを試す',
          'テスト可能：1時間で10バージョンを比較',
          'ポータブル：同じプロンプトは異なるモデルで動作',
          'モデル不知：GPT-4o、Claude、Gemini、ローカルモデルで動作',
        ],
      },
      fineTuningExplained: {
        title: 'ファインチューニングとは',
        content: [
          'ファインチューニングは、モデルを自分のデータで再訓練することです。入出力ペアの例を数百～数千個提供すると、モデルが学習します。モデルの重みが永続的に変わります。',
          'ファインチューニングは、プロンプトエンジニアリングが体系的問題（10%+のケースに影響）で失敗した場合のみ必要です。一般的な理由：ドメイン固有の用語、厳密な出力フォーマット、またはモデルが見たことのない推論パターン。',
        ],
        items: [
          '高額：実行ごとに$500-$5000+',
          '遅い：日数～週数',
          '永続的：重みを変更—元に戻すのは非常に困難',
          'データ集約的：100-10000+個のラベル付き例が必要',
          '推論が高い：モデル使用コストも高くなる',
          'バージョン固定：各モデルバージョンに別々のファインチューニングが必要',
        ],
      },
      headToHeadComparison: {
        title: '並べて比較',
        id: 'comparison-table',
        tableFormat: true,
        columns: ['要素', 'プロンプトエンジニアリング', 'ファインチューニング'],
        rows: [
          { '要素': 'コスト', 'プロンプトエンジニアリング': '$0（推論のみ）', 'ファインチューニング': '$500-$5000+' },
          { '要素': '速度', 'プロンプトエンジニアリング': '数時間', 'ファインチューニング': '日数～週数' },
          { '要素': '可逆性', 'プロンプトエンジニアリング': '削除して再開始', 'ファインチューニング': '永続的' },
          { '要素': 'データ必要量', 'プロンプトエンジニアリング': '3-10例', 'ファインチューニング': '100-10000+ラベル付き' },
          { '要素': '専門知識', 'プロンプトエンジニアリング': '誰でも可能', 'ファインチューニング': 'ML知識必須' },
          { '要素': 'ポータビリティ', 'プロンプトエンジニアリング': 'GPT、Claude、Gemini、ローカル', 'ファインチューニング': '特定モデル/バージョン' },
          { '要素': '解決率', 'プロンプトエンジニアリング': '80-90%のケース', 'ファインチューニング': '残り10-20%' },
          { '要素': 'メンテナンス', 'プロンプトエンジニアリング': 'プロンプト調整', 'ファインチューニング': 'バージョンごと再訓練' },
          { '要素': 'テスト', 'プロンプトエンジニアリング': '1時間で10バージョン', 'ファインチューニング': '10日で10バージョン' },
          { '要素': '推論コスト', 'プロンプトエンジニアリング': '標準価格', 'ファインチューニング': 'カスタム価格（通常高い）' },
        ],
      },
      faqSection: {
        title: 'よくある質問',
        id: 'faq',
        faqs: [
          { q: 'プロンプトエンジニアリングとファインチューニングのどちらを使うべき？', a: 'まずプロンプトエンジニアリングを試してください。無料で即座です。何度も失敗した場合のみファインチューニングしてください。' },
          { q: 'ファインチューニングのコストはどのくらい？', a: '$500-$5000+。モデル、データサイズ、インフラによって異なります。' },
          { q: 'ファインチューニングにどのくらい時間がかかる？', a: '通常1-7日。データサイズ、モデルサイズ、ハードウェアに依存します。' },
          { q: 'ファインチューニングを取り消せる？', a: 'いいえ。ファインチューニングはモデルの重みを永続的に変更します。' },
          { q: 'LoRAファインチューニングとは？', a: 'Low-Rank Adaptation（LoRA）はモデルの一部のみを調整し、コストとデータ要件を削減します。' },
          { q: 'ローカルまたはクラウドでファインチューニングすべき？', a: 'クラウド（OpenAI、Google）は簡単で速い。ローカル（Ollama、PEFT）はコントロールとプライバシーが向上します。' },
          { q: 'ファインチューニングのトレーニングデータをどう取得する？', a: '独自の例を収集、既存データセットを使用、またはアノテーターを雇用します。量より質が重要です。' },
          { q: 'プロンプトエンジニアリングとファインチューニングを組み合わせられる？', a: 'はい。ベストプラクティスです。ファインチューニングは専門タスク用、プロンプトエンジニアリングは柔軟性とルーティング用。' },
          { q: 'Claudeはファインチューニング対応？', a: '2026年時点でいいえ。Anthropicはこの機能を提供していません。プロンプトエンジニアリングを使用してください。' },
          { q: 'ファインチューニングが役立たない場合は？', a: 'モデルが間違っているか、データが不十分か、期待が非現実的な可能性があります。まず大きいモデルまたはより多くのデータを試してください。' },
        ],
      },
      regionalContext: {
        title: '日本での実装ガイダンス',
        content: [
          '経済産業省（METI）は2024年にAIガバナンスガイドラインを発表しました。日本の企業がファインチューニングを導入する場合、データガバナンス、監査ログ、説明責任を考慮する必要があります。多くの日本企業（金融、製造、医療）はプロンプトエンジニアリングからファインチューニングへの段階的な移行が推奨されます。',
        ],
      },
    },
  },
  zh: {
    freshness_tier: 'evergreen',
    theme: 'Tools & Platforms',
    title: 'Prompt工程 vs 微调：何时用提示，何时训练',
    intro: 'Prompt工程和微调是改进AI模型输出的两种根本不同方法。Prompt工程免费、即时、可逆。微调需要相当投资，耗时较长，难以撤销。此指南帮您选择正确方法。',
    publishDate: '2026-04-10',
    dateModified: '2026-05-04',
    readTime: '阅读约9分钟',
    educationalLevel: 'Intermediate',
    seoTitle: 'Prompt工程 vs 微调：何时用提示，何时训练',
    metaDescription: '决策指南：Prompt工程 vs 微调。成本对比（$0 vs $500+）、周期（小时 vs 周）、可逆性。附决策流程图和中国数据法规指南。',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-engineering-vs-fine-tuning?lang=zh',
      inLanguage: 'zh',
      headline: 'Prompt工程 vs 微调：何时用提示，何时训练',
      description: 'Prompt工程与微调的决策指南。',
      datePublished: '2026-04-10',
      dateModified: '2026-05-04',
      author: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'zh',
      mainEntity: [
        { '@type': 'Question', name: '应该用Prompt工程还是微调？', acceptedAnswer: { '@type': 'Answer', text: '先试Prompt工程。免费又即时。仅当重复失败才微调。' } },
      ],
    },
    sections: {
      keyTakeaways: {
        isTldr: true,
        title: '核心要点',
        id: 'key-takeaways',
        items: [
          'Prompt工程：免费、即时、可逆。微调：昂贵、缓慢、永久',
          '首先在10-20个示例上测试Prompt工程。仅当重复失败时才进行微调',
          '90%规则：90%的用例仅通过优秀的Prompt工程解决',
          '微调适合特定领域术语、专有知识或严格格式要求',
          '优质Prompt工程可节省$500+微调成本',
          '维护陷阱：微调模型需在每个新版本发布时更新',
          '两者结合：Prompt工程实现灵活性，微调实现专业化',
        ],
      },
      introduction: {
        title: '为什么这个决策很重要',
        snippets: [
          { type: 'in-one-sentence', text: 'Prompt工程是首选（免费、即时）；微调是当前者失败时的备选（昂贵、永久）。' },
          { type: 'in-plain-terms', text: '编写更好的指令给AI无成本且耗时数分钟。训练AI成本数百至数千美元且耗时数日。先试便宜方案。' },
        ],
        content: [
          '改进AI输出有两条路：改变提问方式（Prompt工程）或改变模型本身（微调）。选错会浪费时间和资金。本指南告诉您应选哪条路。',
        ],
      },
      promptEngineeringExplained: {
        title: '什么是Prompt工程',
        content: [
          'Prompt工程是给AI模型写清晰、详细的指令。不是说"总结这个"，而是"请用2-3句话总结以下文本。重点放在主要决策和决策者。避免专业术语。"',
          '每个Prompt都是实验。你尝试、看结果、调整表述、再试一次。Prompt工程免费是因为你没训练模型—只是更好地与它交流。',
        ],
        items: [
          '免费：无API训练成本，仅推理成本',
          '即时：数分钟至数小时优化，非数日或数周',
          '可逆：差Prompt？删除重试即可',
          '可测试：1小时内对比10个版本',
          '可移植：同一Prompt常适用多个模型',
          '模型无关：适用GPT-4o、Claude、Gemini和本地模型',
        ],
      },
      fineTuningExplained: {
        title: '什么是微调',
        content: [
          '微调是用自有数据重新训练模型。提供数百至数千个输入-输出样本，模型学习。永久改变模型权重。',
          '微调仅在Prompt工程失败于系统性问题（影响10%+案例）时必要。常见原因：领域特定术语、严格输出格式或模型未见过的推理模式。',
        ],
        items: [
          '昂贵：单次运行$500-$5000+',
          '缓慢：数日至数周',
          '永久：改变权重—极难撤销',
          '数据密集：需100-10000+标记样本',
          '推理贵：模型使用成本也更高',
          '版本锁定：每版本需单独微调',
        ],
      },
      headToHeadComparison: {
        title: '逐项对比',
        id: 'comparison-table',
        tableFormat: true,
        columns: ['因素', 'Prompt工程', '微调'],
        rows: [
          { '因素': '成本', 'Prompt工程': '$0（仅推理）', '微调': '$500-$5000+' },
          { '因素': '速度', 'Prompt工程': '数小时', '微调': '数日至数周' },
          { '因素': '可逆性', 'Prompt工程': '删除重新开始', '微调': '永久改变' },
          { '因素': '数据需求', 'Prompt工程': '3-10例', '微调': '100-10000+标记' },
          { '因素': '所需专业知识', 'Prompt工程': '任何人', '微调': '需要ML知识' },
          { '因素': '模型可移植性', 'Prompt工程': 'GPT、Claude、Gemini、本地', '微调': '特定模型/版本' },
          { '因素': '解决能力', 'Prompt工程': '80-90%案例', '微调': '剩余10-20%' },
          { '因素': '维护', 'Prompt工程': '调整Prompt', '微调': '每版本重新训练' },
          { '因素': '测试周期', 'Prompt工程': '1小时10版本', '微调': '10天10版本' },
          { '因素': '推理价格', 'Prompt工程': '标准价格', '微调': '定制价格（通常更贵）' },
        ],
      },
      faqSection: {
        title: '常见问题',
        id: 'faq',
        faqs: [
          { q: '应该用Prompt工程还是微调？', a: '先试Prompt工程。免费又即时。仅当重复失败才微调。' },
          { q: '微调成本多少？', a: '$500-$5000+，取决于模型、数据量和基础设施。' },
          { q: '微调需要多长时间？', a: '通常1-7天，取决于数据量、模型大小和硬件。' },
          { q: '能撤销微调吗？', a: '不能。微调永久改变模型权重，很难恢复。' },
          { q: '什么是LoRA微调？', a: 'Low-Rank Adaptation只调整模型部分，降低成本和数据需求。' },
          { q: '该在本地还是云端微调？', a: '云端（OpenAI、Google）更简单快速。本地（Ollama、PEFT）提供更多控制和隐私。' },
          { q: '怎样获取微调训练数据？', a: '收集自有数据、使用现成数据集或雇标注员。质量比数量重要。' },
          { q: '能组合Prompt工程和微调吗？', a: '可以，这是最佳实践。微调处理专业任务，Prompt工程提供灵活性和路由。' },
          { q: 'Claude支持微调吗？', a: '2026年不支持。Anthropic未提供此功能。请用Prompt工程。' },
          { q: '微调仍未奏效怎么办？', a: '可能选错模型、数据不足或期望不现实。先试更大的模型或更多数据。' },
        ],
      },
      regionalContext: {
        title: '中国市场考虑',
        content: [
          '中国的《数据安全法》（2021）和《个人信息保护法》要求敏感数据保留在中国。微调中文模型时，考虑数据本地化需求。Qwen、ChatGLM等国产模型的微调可满足数据驻留要求。对于金融、医疗等敏感行业，本地Prompt工程加本地模型微调是最安全的选择。',
        ],
      },
    },
  },
};
