// Auto-generated from src/lib/prompt-engineering/content.ts
// Slug: prompt-engineering-vs-rag
// Generated: 2026-04-26T09:45:32.245Z

import type { Language } from "@/lib/blog/blogContent";

import type { PEArticle } from "@/lib/prompt-engineering/types";

export const article: Record<Language, PEArticle> = { en: { theme: 'Tools & Platforms', title: 'Prompt Engineering vs RAG', seoTitle: 'Guide', metaDescription: 'When to use.', intro: '**Guide.**', publishDate: '2026-04-10', dateModified: '2026-04-10', readTime: '8 min', educationalLevel: 'Intermediate', primaryTerm: 'RAG', aboutTopics: ['RAG'], schema: { '@context': 'https://schema.org', '@type': 'TechArticle', headline: 'RAG', datePublished: '2026-04-10', author: { '@type': 'Organization', name: 'PromptQuorum' }, publisher: { '@type': 'Organization', name: 'PromptQuorum' }, url: 'https://www.promptquorum.com/prompt-engineering/prompt-engineering-vs-rag-decision', inLanguage: 'en' }, faqSchema: { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'RAG?', acceptedAnswer: { '@type': 'Answer', text: 'Knowledge-intensive tasks.' } }] }, sections: { keyTakeaways: { isTldr: true, items: ['PE: general', 'RAG: specialized'] }, faq: { title: 'FAQ', faqs: [{ q: 'When RAG?', a: 'External knowledge.' }] }, sources: { title: 'Sources', items: ['[RAG](https://promptquorum.com)'] } } }, de: { theme: 'Tools & Platforms', title: 'RAG', seoTitle: 'RAG', metaDescription: 'RAG', intro: '[Translation coming soon](/prompt-engineering/best-prompt-engineering-tools-2026?lang=en).', publishDate: '2026-04-10', readTime: '8 min', educationalLevel: 'Intermediate', sections: {} }, fr: { theme: 'Tools & Platforms', title: 'RAG', seoTitle: 'RAG', metaDescription: 'RAG', intro: '[Translation coming soon](/prompt-engineering/best-prompt-engineering-tools-2026?lang=en).', publishDate: '2026-04-10', readTime: '8 min', educationalLevel: 'Intermediate', sections: {} }, ja: { theme: 'Tools & Platforms', title: 'RAG', seoTitle: 'RAG', metaDescription: 'RAG', intro: '[Translation coming soon](/prompt-engineering/best-prompt-engineering-tools-2026?lang=en).', publishDate: '2026-04-10', readTime: '8 min', educationalLevel: 'Intermediate', sections: {} }, zh: { freshness_tier: 'semi_annual', theme: 'Tools & Platforms', title: 'RAG', seoTitle: 'RAG', metaDescription: 'RAG', intro: '[Translation coming soon](/prompt-engineering/best-prompt-engineering-tools-2026?lang=en).', publishDate: '2026-04-10', readTime: '8 min', educationalLevel: 'Intermediate', sections: {} } };
