import type { Language } from "@/lib/blog/blogContent";
import type { PEArticle } from "@/lib/prompt-engineering/types";

export const article: Record<Language, PEArticle> = {
  en: {
    freshness_tier: 'evergreen',
    theme: 'Team Governance',
    title: 'Prompt Documentation Templates: 6 Reusable Formats for Teams',
    seoTitle: 'Prompt Documentation Templates: 6 Formats for Teams',
    intro: 'Undocumented prompts break silently, get duplicated, and can\'t be audited. Six reusable documentation templates cover every prompt lifecycle stage — from single-use one-liners to versioned production prompts with review history.',
    metaDescription: '6 prompt documentation templates for teams: one-liner card, version block, test suite header, decision log, change rationale, and API config block. Storage options: Git, PromptHub, Notion.',
    ogDescription: '6 reusable prompt documentation formats — one-liner card, version block, test suite header, decision log, change rationale, API config block. What each captures and where to store them.',
    twitterDescription: '6 prompt documentation templates for teams. From one-liner cards to full version blocks — what to capture at each stage.',
    publishDate: '2026-05-02',
    readTime: '10 min read',
    educationalLevel: 'Intermediate',
    primaryTerm: 'Prompt Documentation',
    leadAnswerBlock: '**Prompt documentation is the structured record of what a prompt does, why it was written that way, and what tests it must pass.** Without it, prompts are unreviewable, unrollbackable, and irreproducible when the author leaves the team.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-documentation-templates',
      inLanguage: 'en',
      headline: 'Prompt Documentation Templates: 6 Reusable Formats for Teams',
      description: '6 prompt documentation templates for teams: one-liner card, version block, test suite header, decision log, change rationale, and API config block.',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['prompt documentation', 'prompt templates', 'prompt management', 'prompt engineering team', 'prompt version control'],
      mentions: [
        { '@type': 'Thing', name: 'PromptHub' },
        { '@type': 'Thing', name: 'Git' },
        { '@type': 'Thing', name: 'Notion' },
        { '@type': 'Thing', name: 'Braintrust' },
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompt-documentation-templates', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'en',
      mainEntity: [
        { '@type': 'Question', name: 'Why do prompts need documentation?', acceptedAnswer: { '@type': 'Answer', text: 'Prompts without documentation can\'t be reviewed, audited, or reproduced. When the author changes the prompt and leaves no record, the team can\'t diagnose regressions, can\'t roll back to a known-good version, and can\'t onboard new members who need to understand the prompt\'s purpose. Documentation is the minimum requirement for any prompt used in production.' } },
        { '@type': 'Question', name: 'What is the minimum documentation a prompt needs?', acceptedAnswer: { '@type': 'Answer', text: 'The minimum is a one-liner card: prompt purpose (one sentence), target model, date created, and author. This takes 2 minutes to write and prevents the most common documentation failure — prompts whose purpose is unknown 6 months later.' } },
        { '@type': 'Question', name: 'Where should prompt documentation be stored?', acceptedAnswer: { '@type': 'Answer', text: 'Store prompt documentation in the same location as the prompt itself. Git works for prompts stored as code files — the commit message serves as the change log. PromptHub provides structured storage with version history, reviewer signatures, and test results built in. Notion works for teams that manage prompts as documents, but lacks version control and test integration.' } },
        { '@type': 'Question', name: 'How detailed does a prompt\'s change rationale need to be?', acceptedAnswer: { '@type': 'Answer', text: 'A change rationale needs three lines: what changed (one sentence), why (the problem the change solves), and what test confirmed it worked. Teams that skip the "why" invariably revert to the previous pattern after the author who made the change leaves the team.' } },
      ],
    },
    sections: {
      why_documentation: {
        title: 'Why Do Undocumented Prompts Break Teams?',
        content: [
          '**Undocumented prompts break teams in three ways: silent regression (no record of what changed), duplication (teams re-write existing prompts because they can\'t find them), and knowledge loss (prompts become unmaintainable when the author leaves).** Each failure is preventable with 5–10 minutes of documentation per prompt.',
          'The most expensive failure is silent regression. A team modifies a production prompt to fix one issue, inadvertently breaks another, and has no baseline to compare against. Without version history and a test suite header, diagnosing the regression requires manual comparison and guesswork.',
          'Use documentation for every prompt used more than once, stored in shared infrastructure, or deployed to production. Skip it for one-time exploratory prompts used in a single session.',
        ],
      },
      six_templates: {
        title: '6 Prompt Documentation Templates',
        content: [
          '**Six templates cover the full prompt lifecycle from first draft to production retirement.** Each template is designed to take under 10 minutes to complete and provide the minimum information required for each lifecycle stage.',
        ],
        numberedItems: [
          { title: 'One-Liner Card', whyItMatters: 'Purpose: capture the minimum viable record for any reused prompt. Fields: prompt name, purpose (1 sentence), target model, date created, author. Use when: a prompt is saved for the first time. Storage: any shared tool (Notion, Git, PromptHub).' },
          { title: 'Version Block', whyItMatters: 'Purpose: track prompt history for prompts that change over time. Fields: version number, date modified, author, what changed (1 sentence), reason for change (1 sentence), test result summary. Use when: a prompt is modified. Storage: Git commit message or PromptHub version entry.' },
          { title: 'Test Suite Header', whyItMatters: 'Purpose: define the acceptance criteria before writing tests. Fields: test goal (what the prompt must do), pass criteria (what output characteristics define success), golden examples (2–3 input/output pairs), known failure modes. Use when: a prompt enters the test suite. Storage: alongside the test file in Git or Braintrust project.' },
          { title: 'Decision Log', whyItMatters: 'Purpose: record design decisions that aren\'t obvious from the prompt text. Fields: decision made, alternatives considered, reason this option was chosen, date. Use when: a non-obvious design choice is made (e.g., why a specific temperature was set, why a particular constraint was added). Storage: doc linked from version block.' },
          { title: 'Change Rationale', whyItMatters: 'Purpose: explain why a prompt was changed in terms that allow the change to be reversed or replicated. Fields: problem statement (what was wrong), change made, expected improvement, measured result. Use when: a prompt is modified in response to a failure or regression. Storage: Git commit body or PromptHub change note.' },
          { title: 'API Config Block', whyItMatters: 'Purpose: record the model parameters used in production. Fields: model (e.g., GPT-4o, Claude 4.6 Sonnet), temperature, max tokens, top_p, stop sequences, system prompt version, user prompt version. Use when: a prompt is deployed to production. Storage: deployment config file, referenced in version block.' },
        ],
      },
      storage_options: {
        title: 'Where to Store Prompt Documentation',
        content: [
          '**Store prompt documentation in the same system as the prompt.** If the prompt lives in code, store docs in Git. If it lives in a GUI tool, store docs in that tool\'s notes or linked doc.',
        ],
        items: [
          'Git: best for engineering teams with prompts stored as files. Commit messages serve as version blocks. Free. Requires discipline. No built-in reviewer workflow.',
          'PromptHub: purpose-built prompt management with version history, reviewer signatures, and test result storage. $0–$49/month. Best for teams with 3+ people writing prompts.',
          'Notion: works for teams managing prompts as documents rather than code. Easy to set up. Lacks version control and test integration — treat as a documentation layer, not a source of truth.',
          'Braintrust: stores test suite headers and evaluation results alongside prompt versions. Best for teams running regular automated evaluations.',
        ],
      },
      key_takeaways: {
        title: 'Key Takeaways',
        isTldr: true,
        items: [
          'Every production prompt needs at minimum a One-Liner Card (purpose, model, date, author)',
          'Every modified prompt needs a Version Block (what changed, why, test result)',
          'Every tested prompt needs a Test Suite Header (pass criteria, golden examples, failure modes)',
          'Store documentation in the same system as the prompt — separate docs get abandoned',
          'The change rationale ("why") is the most important field: teams that skip it revert to old patterns when the author leaves',
          'PromptHub provides the most complete built-in documentation structure; Git works for engineering teams with good commit discipline',
        ],
      },
    },
  },

  de: {
    freshness_tier: 'evergreen',
    theme: 'Team-Steuerung',
    title: 'Prompt-Dokumentationsvorlagen: 6 wiederverwendbare Formate für Teams',
    seoTitle: 'Prompt-Dokumentationsvorlagen: 6 Formate für Teams',
    intro: 'Undokumentierte Prompts scheitern lautlos, werden dupliziert und können nicht auditiert werden. Sechs wiederverwendbare Dokumentationsvorlagen decken jeden Lebenszyklus-Abschnitt ab — von einfachen Einzeilern bis zu versionierten Produktions-Prompts mit Prüfverlauf.',
    metaDescription: '6 Prompt-Dokumentationsvorlagen für Teams: Einzeiler-Karte, Versionsblock, Testsuite-Header, Entscheidungsprotokoll, Änderungsbegründung und API-Konfigurationsblock.',
    ogDescription: '6 wiederverwendbare Prompt-Dokumentationsformate — Einzeiler-Karte, Versionsblock, Testsuite-Header, Entscheidungsprotokoll, Änderungsbegründung, API-Konfigurationsblock.',
    twitterDescription: '6 Prompt-Dokumentationsvorlagen für Teams. Von Einzeiler-Karten bis zu vollständigen Versionsblöcken.',
    publishDate: '2026-05-02',
    readTime: '10 Min. Lesezeit',
    educationalLevel: 'Intermediate',
    primaryTerm: 'Prompt-Dokumentation',
    leadAnswerBlock: '**Prompt-Dokumentation ist die strukturierte Aufzeichnung dessen, was ein Prompt tut, warum er so geschrieben wurde und welche Tests er bestehen muss.** Ohne sie sind Prompts nicht überprüfbar, nicht zurückrollbar und nicht reproduzierbar.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-documentation-templates?lang=de',
      inLanguage: 'de',
      headline: 'Prompt-Dokumentationsvorlagen: 6 wiederverwendbare Formate für Teams',
      description: '6 Prompt-Dokumentationsvorlagen für Teams: Einzeiler-Karte, Versionsblock, Testsuite-Header, Entscheidungsprotokoll, Änderungsbegründung, API-Konfigurationsblock.',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['Prompt-Dokumentation', 'Prompt-Vorlagen', 'Prompt-Management', 'Prompt-Engineering-Team'],
      mentions: [
        { '@type': 'Thing', name: 'PromptHub' },
        { '@type': 'Thing', name: 'Git' },
        { '@type': 'Thing', name: 'Notion' },
        { '@type': 'Thing', name: 'Braintrust' },
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompt-documentation-templates', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'de',
      mainEntity: [
        { '@type': 'Question', name: 'Warum brauchen Prompts eine Dokumentation?', acceptedAnswer: { '@type': 'Answer', text: 'Prompts ohne Dokumentation können nicht geprüft, auditiert oder reproduziert werden. Wenn der Autor den Prompt ändert und keine Aufzeichnung hinterlässt, kann das Team keine Regressionen diagnostizieren, nicht auf eine funktionierende Version zurückrollen und keine neuen Mitglieder einarbeiten.' } },
        { '@type': 'Question', name: 'Wo sollte Prompt-Dokumentation gespeichert werden?', acceptedAnswer: { '@type': 'Answer', text: 'Speichern Sie die Prompt-Dokumentation am selben Ort wie den Prompt selbst. Git eignet sich für Prompts als Code-Dateien. PromptHub bietet strukturierte Speicherung mit Versionsverlauf und Reviewer-Signaturen. Notion eignet sich für Teams, die Prompts als Dokumente verwalten.' } },
      ],
    },
    sections: {
      why_documentation: {
        title: 'Warum scheitern undokumentierte Prompts?',
        content: [
          '**Undokumentierte Prompts scheitern auf drei Arten: stille Regression (kein Nachweis, was sich geändert hat), Duplizierung und Wissensverlust.** Jeder Fehler ist mit 5–10 Minuten Dokumentation pro Prompt vermeidbar.',
          'Die teuerste Fehlerart ist stille Regression. Ein Team ändert einen Produktions-Prompt, um ein Problem zu beheben, beschädigt dabei unbeabsichtigt ein anderes und hat keine Ausgangsbasis für den Vergleich.',
          'Dokumentieren Sie jeden Prompt, der mehr als einmal verwendet, in gemeinsamer Infrastruktur gespeichert oder in der Produktion eingesetzt wird.',
        ],
      },
      six_templates: {
        title: '6 Prompt-Dokumentationsvorlagen',
        content: [
          '**Sechs Vorlagen decken den gesamten Prompt-Lebenszyklus ab.** Jede Vorlage ist so konzipiert, dass sie in unter 10 Minuten ausgefüllt werden kann.',
        ],
        numberedItems: [
          { title: 'Einzeiler-Karte', whyItMatters: 'Zweck: minimaler Nachweis für jeden wiederverwendeten Prompt. Felder: Prompt-Name, Zweck (1 Satz), Zielmodell, Erstellungsdatum, Autor.' },
          { title: 'Versionsblock', whyItMatters: 'Zweck: Prompt-Verlauf verfolgen. Felder: Versionsnummer, Änderungsdatum, Autor, Was geändert wurde (1 Satz), Grund für die Änderung (1 Satz), Testergebnis-Zusammenfassung.' },
          { title: 'Testsuite-Header', whyItMatters: 'Zweck: Abnahmekriterien vor dem Schreiben von Tests definieren. Felder: Testziel, Erfolgskriterien, Golden-Examples (2–3 Ein-/Ausgabe-Paare), bekannte Fehlermuster.' },
          { title: 'Entscheidungsprotokoll', whyItMatters: 'Zweck: Designentscheidungen aufzeichnen, die nicht offensichtlich sind. Felder: getroffene Entscheidung, betrachtete Alternativen, Begründung, Datum.' },
          { title: 'Änderungsbegründung', whyItMatters: 'Zweck: erklären, warum ein Prompt geändert wurde. Felder: Problembeschreibung, vorgenommene Änderung, erwartete Verbesserung, gemessenes Ergebnis.' },
          { title: 'API-Konfigurationsblock', whyItMatters: 'Zweck: Modellparameter in der Produktion aufzeichnen. Felder: Modell, Temperatur, Max-Tokens, Top-P, Stop-Sequenzen, System-Prompt-Version, User-Prompt-Version.' },
        ],
      },
      key_takeaways: {
        title: 'Wichtigste Erkenntnisse',
        isTldr: true,
        items: [
          'Jeder Produktions-Prompt benötigt mindestens eine Einzeiler-Karte (Zweck, Modell, Datum, Autor)',
          'Jeder geänderte Prompt benötigt einen Versionsblock (Was geändert wurde, warum, Testergebnis)',
          'Jeder getestete Prompt benötigt einen Testsuite-Header (Erfolgskriterien, Golden-Examples, Fehlermuster)',
          'Dokumentation am selben Ort wie der Prompt speichern — separate Dokumente werden aufgegeben',
          'Die Änderungsbegründung ("Warum") ist das wichtigste Feld',
        ],
      },
    },
  },

  fr: {
    freshness_tier: 'evergreen',
    theme: 'Gouvernance d\'équipe',
    title: 'Modèles de documentation des prompts : 6 formats réutilisables pour les équipes',
    seoTitle: 'Modèles de documentation des prompts : 6 formats pour équipes',
    intro: 'Les prompts non documentés échouent silencieusement, sont dupliqués et ne peuvent pas être audités. Six modèles de documentation réutilisables couvrent chaque étape du cycle de vie d\'un prompt.',
    metaDescription: '6 modèles de documentation des prompts pour équipes : fiche one-liner, bloc de version, en-tête de suite de tests, journal de décision, justification de changement et bloc de configuration API.',
    ogDescription: '6 formats de documentation des prompts réutilisables — fiche one-liner, bloc de version, en-tête de suite de tests, journal de décision, justification de changement, bloc de config API.',
    twitterDescription: '6 modèles de documentation des prompts pour équipes. Des fiches one-liner aux blocs de version complets.',
    publishDate: '2026-05-02',
    readTime: '10 min de lecture',
    educationalLevel: 'Intermediate',
    primaryTerm: 'Documentation des prompts',
    leadAnswerBlock: '**La documentation des prompts est le record structuré de ce que fait un prompt, pourquoi il a été écrit ainsi et quels tests il doit passer.** Sans elle, les prompts ne peuvent être ni révisés, ni annulés, ni reproduits.',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-documentation-templates?lang=fr',
      inLanguage: 'fr',
      headline: 'Modèles de documentation des prompts : 6 formats réutilisables pour les équipes',
      description: '6 modèles de documentation des prompts pour équipes : fiche one-liner, bloc de version, en-tête de suite de tests, journal de décision, justification de changement, bloc de config API.',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['documentation des prompts', 'modèles de prompts', 'gestion des prompts', 'équipe prompt engineering'],
      mentions: [
        { '@type': 'Thing', name: 'PromptHub' },
        { '@type': 'Thing', name: 'Git' },
        { '@type': 'Thing', name: 'Notion' },
        { '@type': 'Thing', name: 'Braintrust' },
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompt-documentation-templates', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'fr',
      mainEntity: [
        { '@type': 'Question', name: 'Pourquoi les prompts ont-ils besoin de documentation ?', acceptedAnswer: { '@type': 'Answer', text: 'Les prompts sans documentation ne peuvent être ni révisés, ni audités, ni reproduits. Quand l\'auteur modifie le prompt sans laisser de trace, l\'équipe ne peut pas diagnostiquer les régressions ni revenir à une version fonctionnelle.' } },
        { '@type': 'Question', name: 'Quelle est la documentation minimale nécessaire pour un prompt ?', acceptedAnswer: { '@type': 'Answer', text: 'Le minimum est une fiche one-liner : objectif du prompt (une phrase), modèle cible, date de création et auteur. Cela prend 2 minutes et prévient l\'échec de documentation le plus courant.' } },
      ],
    },
    sections: {
      why_documentation: {
        title: 'Pourquoi les prompts non documentés font-ils échouer les équipes ?',
        content: [
          '**Les prompts non documentés font échouer les équipes de trois façons : régression silencieuse, duplication et perte de connaissances.** Chaque échec est évitable avec 5 à 10 minutes de documentation par prompt.',
          'L\'échec le plus coûteux est la régression silencieuse. Une équipe modifie un prompt de production, casse inadvertamment autre chose, et n\'a pas de référence pour comparer.',
          'Documentez chaque prompt utilisé plus d\'une fois, stocké dans une infrastructure partagée ou déployé en production.',
        ],
      },
      six_templates: {
        title: '6 modèles de documentation des prompts',
        content: [
          '**Six modèles couvrent l\'intégralité du cycle de vie des prompts.** Chaque modèle est conçu pour être complété en moins de 10 minutes.',
        ],
        numberedItems: [
          { title: 'Fiche one-liner', whyItMatters: 'Objectif : enregistrement minimum pour tout prompt réutilisé. Champs : nom du prompt, objectif (1 phrase), modèle cible, date de création, auteur.' },
          { title: 'Bloc de version', whyItMatters: 'Objectif : suivre l\'historique du prompt. Champs : numéro de version, date de modification, auteur, ce qui a changé (1 phrase), raison du changement (1 phrase), résumé des résultats de test.' },
          { title: 'En-tête de suite de tests', whyItMatters: 'Objectif : définir les critères d\'acceptation avant d\'écrire les tests. Champs : objectif du test, critères de réussite, exemples golden (2–3 paires entrée/sortie), modes d\'échec connus.' },
          { title: 'Journal de décision', whyItMatters: 'Objectif : enregistrer les décisions de conception non évidentes. Champs : décision prise, alternatives considérées, raison du choix, date.' },
          { title: 'Justification de changement', whyItMatters: 'Objectif : expliquer pourquoi un prompt a été modifié. Champs : énoncé du problème, changement effectué, amélioration attendue, résultat mesuré.' },
          { title: 'Bloc de configuration API', whyItMatters: 'Objectif : enregistrer les paramètres du modèle en production. Champs : modèle, température, max tokens, top_p, séquences d\'arrêt, version du system prompt, version du user prompt.' },
        ],
      },
      key_takeaways: {
        title: 'Points clés',
        isTldr: true,
        items: [
          'Tout prompt de production nécessite au minimum une fiche one-liner (objectif, modèle, date, auteur)',
          'Tout prompt modifié nécessite un bloc de version (ce qui a changé, pourquoi, résultat de test)',
          'Tout prompt testé nécessite un en-tête de suite de tests',
          'Stocker la documentation au même endroit que le prompt',
          'La justification du changement (« pourquoi ») est le champ le plus important',
        ],
      },
    },
  },

  ja: {
    freshness_tier: 'evergreen',
    theme: 'チームガバナンス',
    title: 'Prompt文書化テンプレート：チーム向け6つの再利用可能フォーマット',
    seoTitle: 'Prompt文書化テンプレート：チーム向け6種類のフォーマット',
    intro: '文書化されていないPromptは静かに失敗し、重複され、監査できません。6つの再利用可能な文書化テンプレートがPromptのライフサイクル全段階をカバーします。',
    metaDescription: 'チーム向け6つのPrompt文書化テンプレート：ワンライナーカード、バージョンブロック、テストスイートヘッダー、決定ログ、変更理由、APIコンフィグブロック。',
    ogDescription: '6つの再利用可能なPrompt文書化フォーマット — ワンライナーカード、バージョンブロック、テストスイートヘッダー、決定ログ、変更理由、APIコンフィグブロック。',
    twitterDescription: 'チーム向け6つのPrompt文書化テンプレート。ワンライナーカードから完全なバージョンブロックまで。',
    publishDate: '2026-05-02',
    readTime: '10分で読める',
    educationalLevel: 'Intermediate',
    primaryTerm: 'Prompt文書化',
    leadAnswerBlock: '**Prompt文書化とは、Promptが何をするか、なぜそのように書かれたか、どのテストに合格しなければならないかの構造化された記録です。** なければPromptはレビューも、ロールバックも、再現もできません。',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-documentation-templates?lang=ja',
      inLanguage: 'ja',
      headline: 'Prompt文書化テンプレート：チーム向け6つの再利用可能フォーマット',
      description: 'チーム向け6つのPrompt文書化テンプレート：ワンライナーカード、バージョンブロック、テストスイートヘッダー、決定ログ、変更理由、APIコンフィグブロック。',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['Prompt文書化', 'Promptテンプレート', 'Prompt管理', 'チームプロンプトエンジニアリング'],
      mentions: [
        { '@type': 'Thing', name: 'PromptHub' },
        { '@type': 'Thing', name: 'Git' },
        { '@type': 'Thing', name: 'Notion' },
        { '@type': 'Thing', name: 'Braintrust' },
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompt-documentation-templates', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'ja',
      mainEntity: [
        { '@type': 'Question', name: 'なぜPromptには文書化が必要ですか？', acceptedAnswer: { '@type': 'Answer', text: '文書化されていないPromptはレビュー、監査、再現ができません。作成者がPromptを変更して記録を残さないと、チームは回帰を診断できず、既知の良い状態にロールバックできず、Promptの目的を理解する必要がある新メンバーをオンボードできません。' } },
        { '@type': 'Question', name: 'Promptに必要な最低限の文書化は何ですか？', acceptedAnswer: { '@type': 'Answer', text: '最低限はワンライナーカードです：Promptの目的（1文）、対象モデル、作成日、作成者。2分で書け、最も一般的な文書化の失敗（6ヶ月後に目的不明なPrompt）を防ぎます。' } },
      ],
    },
    sections: {
      why_documentation: {
        title: '文書化されていないPromptがなぜチームを失敗させるのか？',
        content: [
          '**文書化されていないPromptは3つの方法でチームを失敗させます：静かな回帰（何が変わったかの記録なし）、重複、知識の損失。** 各失敗はPromptあたり5〜10分の文書化で防げます。',
          '最もコストのかかる失敗は静かな回帰です。チームが本番Promptを修正して一つの問題を解決し、意図せず別の問題を引き起こし、比較する基準点がありません。',
          '複数回使用する、共有インフラに保存する、または本番にデプロイするすべてのPromptを文書化します。',
        ],
      },
      six_templates: {
        title: '6つのPrompt文書化テンプレート',
        content: [
          '**6つのテンプレートがPromptのライフサイクル全体をカバーします。** 各テンプレートは10分以内に記入できるように設計されています。',
        ],
        numberedItems: [
          { title: 'ワンライナーカード', whyItMatters: '目的：再利用されるPromptの最小限の記録。フィールド：Prompt名、目的（1文）、対象モデル、作成日、作成者。' },
          { title: 'バージョンブロック', whyItMatters: '目的：変更されるPromptの履歴を追跡。フィールド：バージョン番号、変更日、作成者、変更内容（1文）、変更理由（1文）、テスト結果サマリー。' },
          { title: 'テストスイートヘッダー', whyItMatters: '目的：テスト作成前に受入基準を定義。フィールド：テスト目標、合格基準、ゴールデンサンプル（2〜3の入出力ペア）、既知の失敗モード。' },
          { title: '決定ログ', whyItMatters: '目的：Promptテキストから明らかでない設計決定を記録。フィールド：決定事項、検討した代替案、この選択の理由、日付。' },
          { title: '変更理由', whyItMatters: '目的：Promptが変更された理由を説明。フィールド：問題の説明、変更内容、期待される改善点、測定された結果。' },
          { title: 'APIコンフィグブロック', whyItMatters: '目的：本番で使用するモデルパラメータを記録。フィールド：モデル、temperature、max_tokens、top_p、stop_sequences、システムPromptバージョン、ユーザーPromptバージョン。' },
        ],
      },
      key_takeaways: {
        title: '重要なポイント',
        isTldr: true,
        items: [
          'すべての本番Promptは最低限ワンライナーカード（目的、モデル、日付、作成者）が必要',
          'すべての変更されたPromptはバージョンブロックが必要',
          'すべてのテストされたPromptはテストスイートヘッダーが必要',
          'Promptと同じ場所に文書化を保存する — 別ドキュメントは放置される',
          '変更理由（「なぜ」）が最も重要なフィールド',
        ],
      },
    },
  },

  zh: {
    freshness_tier: 'evergreen',
    theme: '团队治理',
    title: 'Prompt文档化模板：团队可复用的6种格式',
    seoTitle: 'Prompt文档化模板：团队适用的6种格式',
    intro: '未经文档化的Prompt会悄无声息地失败、被重复创建，且无法审计。6个可复用的文档化模板覆盖了Prompt的完整生命周期——从一次性单行提示词到带有审查记录的版本化生产Prompt。',
    metaDescription: '团队使用的6种Prompt文档化模板：单行卡片、版本块、测试套件头、决策日志、变更理由和API配置块。存储方案：Git、PromptHub、Notion。',
    ogDescription: '6种可复用的Prompt文档格式——单行卡片、版本块、测试套件头、决策日志、变更理由、API配置块。每种格式的内容和存储位置解析。',
    twitterDescription: '团队Prompt文档化的6个模板。从单行卡片到完整版本块——每个阶段需要记录什么。',
    publishDate: '2026-05-02',
    readTime: '10分钟阅读',
    educationalLevel: 'Intermediate',
    primaryTerm: 'Prompt文档化',
    leadAnswerBlock: '**Prompt文档化是关于Prompt功能、编写方式和必须通过的测试的结构化记录。** 没有它，Prompt无法被审查、回滚或在作者离开后重现。',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      url: 'https://www.promptquorum.com/prompt-engineering/prompt-documentation-templates?lang=zh',
      inLanguage: 'zh',
      headline: 'Prompt文档化模板：团队可复用的6种格式',
      description: '团队使用的6种Prompt文档化模板：单行卡片、版本块、测试套件头、决策日志、变更理由和API配置块。',
      datePublished: '2026-05-02',
      dateModified: '2026-05-02',
      keywords: ['Prompt文档化', 'Prompt模板', 'Prompt管理', '团队提示词工程'],
      mentions: [
        { '@type': 'Thing', name: 'PromptHub' },
        { '@type': 'Thing', name: 'Git' },
        { '@type': 'Thing', name: 'Notion' },
        { '@type': 'Thing', name: 'Braintrust' },
        { '@type': 'Thing', name: 'GPT-4o' },
        { '@type': 'Thing', name: 'Claude 4.6 Sonnet' },
      ],
      author: { '@type': 'Person', name: 'Hans Kuepper', url: 'https://www.promptquorum.com/about' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com', logo: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/logo.svg' } },
      image: { '@type': 'ImageObject', url: 'https://www.promptquorum.com/api/og/prompt-documentation-templates', width: 1200, height: 630 },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'zh',
      mainEntity: [
        { '@type': 'Question', name: '为什么Prompt需要文档化？', acceptedAnswer: { '@type': 'Answer', text: '没有文档的Prompt无法被审查、审计或重现。当作者修改Prompt却没有留下记录时，团队无法诊断回归问题，无法回滚到已知可用的版本，也无法让需要了解Prompt用途的新成员顺利入职。' } },
        { '@type': 'Question', name: 'Prompt需要的最少文档是什么？', acceptedAnswer: { '@type': 'Answer', text: '最低要求是单行卡片：Prompt用途（一句话）、目标模型、创建日期和作者。填写只需2分钟，可以防止最常见的文档化失败——6个月后没人知道用途的Prompt。' } },
        { '@type': 'Question', name: 'Prompt文档应该存储在哪里？', acceptedAnswer: { '@type': 'Answer', text: '将Prompt文档存储在与Prompt本身相同的位置。Git适用于作为代码文件存储的Prompt。PromptHub提供内置版本历史和审查者签名的结构化存储。Notion适合将Prompt作为文档管理的团队，但缺乏版本控制和测试集成。' } },
      ],
    },
    sections: {
      why_documentation: {
        title: '未文档化的Prompt为何会让团队陷入困境？',
        content: [
          '**未文档化的Prompt以三种方式让团队失败：静默回归（无变更记录）、重复创建和知识流失。** 每种失败都可以通过每个Prompt5至10分钟的文档化来预防。',
          '最昂贵的失败是静默回归。团队修改生产Prompt以修复一个问题，无意中破坏了另一个，却没有基准进行对比。',
          '为每个使用超过一次、存储在共享基础设施中或部署到生产环境的Prompt建立文档。',
        ],
      },
      six_templates: {
        title: '6种Prompt文档化模板',
        content: [
          '**6个模板覆盖了Prompt的完整生命周期。** 每个模板设计为10分钟以内可完成填写。',
        ],
        numberedItems: [
          { title: '单行卡片', whyItMatters: '目的：为任何复用Prompt提供最基础的记录。字段：Prompt名称、用途（1句话）、目标模型、创建日期、作者。' },
          { title: '版本块', whyItMatters: '目的：跟踪随时间变化的Prompt历史。字段：版本号、修改日期、作者、变更内容（1句话）、变更原因（1句话）、测试结果摘要。' },
          { title: '测试套件头', whyItMatters: '目的：在编写测试前定义验收标准。字段：测试目标、通过标准、黄金样例（2至3个输入/输出对）、已知失败模式。' },
          { title: '决策日志', whyItMatters: '目的：记录从Prompt文本中不明显的设计决策。字段：已做出的决策、考虑过的替代方案、选择此方案的原因、日期。' },
          { title: '变更理由', whyItMatters: '目的：说明Prompt被修改的原因。字段：问题陈述、所做变更、预期改进、实测结果。' },
          { title: 'API配置块', whyItMatters: '目的：记录生产环境中使用的模型参数。字段：模型、temperature、max_tokens、top_p、stop_sequences、system prompt版本、user prompt版本。' },
        ],
      },
      key_takeaways: {
        title: '关键要点',
        isTldr: true,
        items: [
          '每个生产Prompt至少需要一张单行卡片（用途、模型、日期、作者）',
          '每个被修改的Prompt需要一个版本块',
          '每个被测试的Prompt需要一个测试套件头',
          '将文档存储在与Prompt相同的位置——单独的文档会被遗弃',
          '变更理由（"为什么"）是最重要的字段',
        ],
      },
    },
  },
}
