import type { Language } from '@/lib/blog/blogContent'
import type { PromptBiteArticle } from '../types'

export const article: Partial<Record<Language, PromptBiteArticle>> = {
  en: {
    theme: 'Model Comparisons',
    title: 'Best Qwen Model for Coding?',
    seoTitle: 'Qwen3-Coder 2026: 7B vs 14B vs 32B by VRAM Tier',
    metaDescription: 'Qwen3-Coder 32B leads at 24 GB VRAM with 91.5% HumanEval. At 8 GB, 7B hits 79.7%. 14B is the sweet spot at 12 GB. Size guide for every tier.',
    publishDate: '2026-05-26',
    freshness_tier: 'semi_annual',
    next_refresh_due: '2026-11-26',
    educationalLevel: 'Intermediate',
    audience: 'Developers choosing between Qwen3-Coder sizes for local coding',
    parentArticle: '/power-local-llm/best-local-coding-models-2026',
    siblingBites: ['qwen-coder-vs-deepseek-coder', 'can-you-run-qwen3-on-ollama'],
    is_living_page: false,
    quickAnswerTop: {
      en: {
        question: 'Best Qwen model for coding?',
        answer: 'Qwen3-Coder 32B is the best Qwen coding model if you have 24 GB VRAM (91.5% HumanEval). At 8 GB VRAM, the 7B version scores 79.7% and runs at 8–15 tok/s. The 14B is the sweet spot for most developers at 12 GB VRAM.',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M: 5.5 GB VRAM, 79.7% HumanEval, 8–15 tok/s — for RTX 3060 or 16 GB RAM',
          'Qwen3-Coder 14B Q4_K_M: 9.5 GB VRAM, 88.0% HumanEval, 4–8 tok/s — sweet spot for RTX 3080/4070',
          'Qwen3-Coder 32B Q4_K_M: 20.5 GB VRAM, 91.5% HumanEval, 2–4 tok/s — for RTX 4090 or M3 Max',
          'CPU-only (no GPU): 7B on 16 GB RAM, ~8 tok/s; acceptable for autocomplete',
        ],
        updatedDate: '2026-05',
      },
      de: {
        question: 'Bestes Qwen-Modell für Coding?',
        answer: 'Qwen3-Coder 32B ist das beste Qwen-Coding-Modell mit 24 GB VRAM (91,5 % HumanEval). Bei 8 GB VRAM erreicht die 7B-Version 79,7 % und läuft mit 8–15 tok/s. Die 14B ist der Sweet Spot für die meisten Entwickler bei 12 GB VRAM.',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M: 5,5 GB VRAM, 79,7 % HumanEval — für RTX 3060 oder 16 GB RAM',
          'Qwen3-Coder 14B Q4_K_M: 9,5 GB VRAM, 88,0 % HumanEval — Sweet Spot für RTX 3080/4070',
          'Qwen3-Coder 32B Q4_K_M: 20,5 GB VRAM, 91,5 % HumanEval — für RTX 4090 oder M3 Max',
        ],
        updatedDate: '2026-05',
      },
      fr: {
        question: 'Meilleur modèle Qwen pour le codage ?',
        answer: 'Qwen3-Coder 32B est le meilleur avec 24 Go VRAM (91,5 % HumanEval). À 8 Go VRAM, le 7B atteint 79,7%. Le 14B est le meilleur choix pour la plupart des développeurs à 12 Go VRAM.',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M : 5,5 Go VRAM, 79,7 % HumanEval',
          'Qwen3-Coder 14B Q4_K_M : 9,5 Go VRAM, 88,0 % HumanEval — meilleur rapport qualité/VRAM',
          'Qwen3-Coder 32B Q4_K_M : 20,5 Go VRAM, 91,5 % HumanEval',
        ],
        updatedDate: '2026-05',
      },
      ja: {
        question: 'コーディング向け最適Qwenモデルは？',
        answer: 'Qwen3-Coder 32Bは24 GB VRAMで最高性能（HumanEval 91.5%）。8 GB VRAMなら7B版が79.7%・8–15 tok/s。14Bは12 GB VRAMで多くの開発者に最適なスイートスポット。',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M：5.5 GB VRAM、HumanEval 79.7%',
          'Qwen3-Coder 14B Q4_K_M：9.5 GB VRAM、HumanEval 88.0%——スイートスポット',
          'Qwen3-Coder 32B Q4_K_M：20.5 GB VRAM、HumanEval 91.5%',
        ],
        updatedDate: '2026-05',
      },
      zh: {
        question: '编程最佳Qwen模型是哪个？',
        answer: 'Qwen3-Coder 32B在24 GB显存下表现最佳（HumanEval 91.5%）。8 GB显存选7B（79.7%，8–15 tok/s）；14B是12 GB显存开发者的最优选择。',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M：5.5 GB显存，HumanEval 79.7%，8–15 tok/s',
          'Qwen3-Coder 14B Q4_K_M：9.5 GB显存，HumanEval 88.0%——最优性价比',
          'Qwen3-Coder 32B Q4_K_M：20.5 GB显存，HumanEval 91.5%——顶级性能',
          'CPU-only：16 GB内存运行7B，约8 tok/s',
        ],
        updatedDate: '2026-05',
      },
    },
    sections: {
      tldr: {
        isTldr: true,
        items: [
          'Qwen3-Coder 32B Q4_K_M: 91.5% HumanEval — best Qwen coding model, needs 24 GB VRAM (RTX 4090 or M3 Max 48 GB)',
          'Qwen3-Coder 14B Q4_K_M: 88.0% HumanEval at 9.5 GB VRAM — sweet spot for RTX 3080 / RTX 4070 / M2 Pro',
          'Qwen3-Coder 7B Q4_K_M: 79.7% HumanEval at 5.5 GB VRAM — works on any RTX 3060 or 16 GB RAM CPU',
          'All sizes support: Python, TypeScript, Go, Rust, Java, C++, SQL, Bash, and 40+ other languages',
          'Install any size: `ollama pull qwen2.5-coder:7b` / `14b` / `32b`',
        ],
      },
      comparisonTable: {
        id: 'comparison',
        title: 'Qwen3-Coder Size Comparison',
        content: ['Choose the largest model your hardware can load at Q4_K_M without offloading layers to CPU.'],
        comparisonTable: {
          columns: ['Model', 'VRAM (Q4_K_M)', 'HumanEval (%)', 'Speed (GPU)', 'Best For'],
          rows: [
            { 'Model': 'Qwen3-Coder 7B',  'VRAM (Q4_K_M)': '5.5 GB',  'HumanEval (%)': '79.7', 'Speed (GPU)': '8–15 tok/s', 'Best For': 'RTX 3060 / 16 GB RAM laptop' },
            { 'Model': 'Qwen3-Coder 14B', 'VRAM (Q4_K_M)': '9.5 GB',  'HumanEval (%)': '88.0', 'Speed (GPU)': '4–8 tok/s',  'Best For': 'RTX 3080 / RTX 4070 / M2 Pro' },
            { 'Model': 'Qwen3-Coder 32B', 'VRAM (Q4_K_M)': '20.5 GB', 'HumanEval (%)': '91.5', 'Speed (GPU)': '2–4 tok/s',  'Best For': 'RTX 4090 / M3 Max 48 GB' },
          ],
        },
      },
      verdict: {
        id: 'verdict',
        title: 'Verdict: Which Size to Run',
        content: [
          '**8 GB VRAM or less (RTX 3060, GTX 1080 Ti, M2 16 GB):** Run Qwen3-Coder 7B Q4_K_M. It fits in 5.5 GB VRAM with room for the KV cache. For autocomplete and function generation in an IDE plugin, 79.7% HumanEval is sufficient.',
          '**12–16 GB VRAM (RTX 3080, RTX 4070, M2 Pro 32 GB):** Run Qwen3-Coder 14B Q4_K_M. The jump from 7B to 14B is the biggest quality-per-VRAM leap in the Qwen Coder family.',
          '**24 GB VRAM (RTX 4090, M3 Max 48 GB):** Run Qwen3-Coder 32B Q4_K_M. It outperforms GPT-5.5 mini on code generation benchmarks and handles multi-file context better.',
          '**CPU-only (no discrete GPU):** 7B Q4_K_M on 16 GB RAM, ~8 tok/s. Acceptable for occasional generation; too slow for real-time autocomplete.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Frequently Asked Questions',
        faqs: [
          { q: 'Is Qwen3-Coder better than DeepSeek-Coder for Python?', a: 'Qwen3-Coder 32B scores 91.5% HumanEval vs DeepSeek-Coder-V2-Lite at ~80%. For Python specifically, Qwen3-Coder 32B leads at the same VRAM tier.' },
          { q: 'Does Qwen3-Coder support Chinese code comments?', a: 'Yes. It handles mixed Chinese/English code comments natively — a significant advantage for Chinese developers.' },
          { q: 'Can I use Qwen3-Coder with Continue.dev or Cline?', a: 'Yes. Both support Ollama backends. Set the model to `qwen2.5-coder:32b` (or your chosen size) in the Continue.dev config or Cline settings.' },
          { q: 'What quantization level should I use?', a: 'Q4_K_M is the best balance: near full-precision quality, ~35% VRAM reduction. Use Q8_0 only if you have abundant VRAM and want maximum accuracy.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'Best Qwen Model for Coding? 7B vs 14B vs 32B Guide 2026',
      description: 'Qwen3-Coder size comparison: 7B at 5.5 GB VRAM (79.7% HumanEval), 14B at 9.5 GB (88.0%), 32B at 20.5 GB (91.5%). Pick the right size for your hardware.',
      url: 'https://www.promptquorum.com/prompt-bites/best-qwen-model-for-coding?lang=en',
      inLanguage: 'en',
      author: { '@type': 'Person', name: 'Hans Kuepper' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      datePublished: '2026-05-26',
      dateModified: '2026-05-26',
      about: [{ '@type': 'Thing', name: 'Qwen3-Coder Local LLM' }],
      mentions: [{ '@type': 'SoftwareApplication', name: 'Qwen3-Coder' }, { '@type': 'SoftwareApplication', name: 'Ollama' }],
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'en',
      mainEntity: [
        { '@type': 'Question', name: 'Best Qwen model for coding at 8 GB VRAM?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 7B Q4_K_M — fits in 5.5 GB VRAM, 79.7% HumanEval, 8–15 tok/s.' } },
        { '@type': 'Question', name: 'Best Qwen coding model at 12–16 GB VRAM?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 14B Q4_K_M — 9.5 GB VRAM, 88.0% HumanEval, the best quality-per-VRAM in the Coder family.' } },
        { '@type': 'Question', name: 'Is Qwen3-Coder better than DeepSeek-Coder?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 32B (91.5% HumanEval) outperforms DeepSeek-Coder-V2-Lite at the same VRAM tier.' } },
      ],
    },
  },

  de: {
    theme: 'Model Comparisons',
    title: 'Bestes Qwen-Modell für Coding?',
    seoTitle: 'Qwen3-Coder 2026: 7B vs 14B vs 32B nach VRAM-Tier',
    metaDescription: 'Qwen3-Coder 32B führt mit 24 GB VRAM (91,5 % HumanEval). Bei 8 GB: 7B mit 79,7 %. 14B ist der Sweet Spot bei 12 GB. Größenleitfaden für jede Tier.',
    publishDate: '2026-05-26',
    freshness_tier: 'semi_annual',
    next_refresh_due: '2026-11-26',
    educationalLevel: 'Intermediate',
    audience: 'Entwickler, die zwischen Qwen3-Coder-Größen für lokales Coding wählen',
    parentArticle: '/power-local-llm/best-local-coding-models-2026',
    siblingBites: ['qwen-coder-vs-deepseek-coder', 'can-you-run-qwen3-on-ollama'],
    is_living_page: false,
    quickAnswerTop: {
      en: { question: 'Best Qwen model for coding?', answer: 'Qwen3-Coder 32B at 24 GB VRAM (91.5% HumanEval). 7B at 8 GB, 14B sweet spot at 12 GB.', bullets: ['7B: 5.5 GB VRAM', '14B: 9.5 GB VRAM sweet spot', '32B: 20.5 GB VRAM best'], updatedDate: '2026-05' },
      de: {
        question: 'Bestes Qwen-Modell für Coding?',
        answer: 'Qwen3-Coder 32B ist das beste Qwen-Coding-Modell mit 24 GB VRAM (91,5 % HumanEval). Bei 8 GB VRAM: 7B mit 79,7 %. 14B ist der Sweet Spot für die meisten Entwickler bei 12 GB VRAM.',
        bullets: ['Qwen3-Coder 7B Q4_K_M: 5,5 GB VRAM, 79,7 % HumanEval', 'Qwen3-Coder 14B Q4_K_M: 9,5 GB VRAM, 88,0 % HumanEval', 'Qwen3-Coder 32B Q4_K_M: 20,5 GB VRAM, 91,5 % HumanEval'],
        updatedDate: '2026-05',
      },
      fr: { question: 'Meilleur modèle Qwen pour coder ?', answer: 'Qwen3-Coder 32B à 24 Go VRAM (91,5%). 7B à 8 Go, 14B sweet spot à 12 Go.', bullets: ['7B: 5,5 Go VRAM', '14B: 9,5 Go sweet spot', '32B: 20,5 Go meilleur'], updatedDate: '2026-05' },
      ja: { question: 'コーディング向け最適Qwenモデルは？', answer: '24 GB VRAMなら32B (91.5%)、8 GB VRAMなら7B、12 GB VRAMのスイートスポットは14B。', bullets: ['7B：5.5 GB VRAM', '14B：9.5 GB VRAMスイートスポット', '32B：20.5 GB VRAM'], updatedDate: '2026-05' },
      zh: { question: '编程最佳Qwen模型？', answer: '24 GB显存选32B（91.5%），8 GB选7B，12 GB最优选14B。', bullets: ['7B：5.5 GB显存', '14B：9.5 GB最优性价比', '32B：20.5 GB最佳性能'], updatedDate: '2026-05' },
    },
    sections: {
      tldr: {
        isTldr: true,
        items: [
          'Qwen3-Coder 32B Q4_K_M: 91,5 % HumanEval — bestes Qwen-Coding-Modell, benötigt 24 GB VRAM',
          'Qwen3-Coder 14B Q4_K_M: 88,0 % HumanEval bei 9,5 GB VRAM — Sweet Spot für RTX 3080/4070',
          'Qwen3-Coder 7B Q4_K_M: 79,7 % HumanEval bei 5,5 GB VRAM — für RTX 3060 oder 16 GB RAM',
          'Installation: `ollama pull qwen2.5-coder:7b` / `14b` / `32b`',
        ],
      },
      comparisonTable: {
        id: 'comparison',
        title: 'Qwen3-Coder Größenvergleich',
        content: ['Das größte Modell wählen, das bei Q4_K_M vollständig in den VRAM passt.'],
        comparisonTable: {
          columns: ['Modell', 'VRAM (Q4_K_M)', 'HumanEval (%)', 'Geschwindigkeit (GPU)', 'Geeignet für'],
          rows: [
            { 'Modell': 'Qwen3-Coder 7B',  'VRAM (Q4_K_M)': '5,5 GB',  'HumanEval (%)': '79,7', 'Geschwindigkeit (GPU)': '8–15 tok/s', 'Geeignet für': 'RTX 3060 / 16 GB RAM-Laptop' },
            { 'Modell': 'Qwen3-Coder 14B', 'VRAM (Q4_K_M)': '9,5 GB',  'HumanEval (%)': '88,0', 'Geschwindigkeit (GPU)': '4–8 tok/s',  'Geeignet für': 'RTX 3080 / RTX 4070 / M2 Pro' },
            { 'Modell': 'Qwen3-Coder 32B', 'VRAM (Q4_K_M)': '20,5 GB', 'HumanEval (%)': '91,5', 'Geschwindigkeit (GPU)': '2–4 tok/s',  'Geeignet für': 'RTX 4090 / M3 Max 48 GB' },
          ],
        },
      },
      verdict: {
        id: 'verdict',
        title: 'Urteil: Welche Größe verwenden',
        content: [
          '**8 GB VRAM oder weniger (RTX 3060, M2 16 GB):** Qwen3-Coder 7B Q4_K_M. Passt in 5,5 GB VRAM mit Platz für den KV-Cache.',
          '**12–16 GB VRAM (RTX 3080, RTX 4070, M2 Pro 32 GB):** Qwen3-Coder 14B Q4_K_M. Der Sprung von 7B auf 14B ist der größte Qualitätsgewinn pro VRAM.',
          '**24 GB VRAM (RTX 4090, M3 Max 48 GB):** Qwen3-Coder 32B Q4_K_M — überbietet GPT-4o mini bei Code-Generierungs-Benchmarks.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Häufig gestellte Fragen',
        faqs: [
          { q: 'Ist Qwen3-Coder besser als DeepSeek-Coder für Python?', a: 'Qwen3-Coder 32B erzielt 91,5 % HumanEval vs. ~80 % für DeepSeek-Coder-V2-Lite bei gleichem VRAM.' },
          { q: 'Unterstützt Qwen3-Coder chinesische Code-Kommentare?', a: 'Ja. Es verarbeitet gemischte chinesische/englische Code-Kommentare nativ.' },
          { q: 'Kann ich Qwen3-Coder mit Continue.dev oder Cline verwenden?', a: 'Ja. Ollama als Backend konfigurieren, Modell auf `qwen2.5-coder:32b` setzen.' },
          { q: 'Welches Quantisierungsniveau sollte ich verwenden?', a: 'Q4_K_M: bestes Gleichgewicht zwischen Qualität und VRAM-Reduzierung (~35 %).' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'Bestes Qwen-Modell für Coding? 7B vs 14B vs 32B 2026',
      description: 'Qwen3-Coder Größenvergleich: 7B bei 5,5 GB VRAM (79,7 % HumanEval), 14B bei 9,5 GB (88,0 %), 32B bei 20,5 GB (91,5 %).',
      url: 'https://www.promptquorum.com/de/prompt-bites/best-qwen-model-for-coding',
      inLanguage: 'de',
      author: { '@type': 'Person', name: 'Hans Kuepper' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      datePublished: '2026-05-26',
      dateModified: '2026-05-26',
      about: [{ '@type': 'Thing', name: 'Qwen3-Coder' }],
      mentions: [{ '@type': 'SoftwareApplication', name: 'Qwen3-Coder' }, { '@type': 'SoftwareApplication', name: 'Ollama' }],
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'de',
      mainEntity: [
        { '@type': 'Question', name: 'Bestes Qwen-Coding-Modell bei 8 GB VRAM?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 7B Q4_K_M — 5,5 GB VRAM, 79,7 % HumanEval.' } },
      ],
    },
  },

  fr: {
    theme: 'Model Comparisons',
    title: 'Meilleur modèle Qwen pour le codage ?',
    seoTitle: 'Qwen3-Coder 2026 : 7B vs 14B vs 32B par niveau VRAM',
    metaDescription: 'Qwen3-Coder 32B en tête à 24 Go VRAM (91,5 % HumanEval). À 8 Go : 7B atteint 79,7 %. Le 14B est le sweet spot à 12 Go. Guide par niveau de VRAM.',
    publishDate: '2026-05-26',
    freshness_tier: 'semi_annual',
    next_refresh_due: '2026-11-26',
    educationalLevel: 'Intermediate',
    audience: 'Développeurs choisissant la taille de Qwen3-Coder pour le codage local',
    parentArticle: '/power-local-llm/best-local-coding-models-2026',
    siblingBites: ['qwen-coder-vs-deepseek-coder', 'can-you-run-qwen3-on-ollama'],
    is_living_page: false,
    quickAnswerTop: {
      en: { question: 'Best Qwen model for coding?', answer: '32B at 24 GB VRAM, 14B at 12 GB (sweet spot), 7B at 8 GB.', bullets: ['7B: 5.5 GB VRAM', '14B: sweet spot', '32B: best quality'], updatedDate: '2026-05' },
      de: { question: 'Bestes Qwen-Modell für Coding?', answer: '32B bei 24 GB VRAM, 14B Sweet Spot bei 12 GB, 7B bei 8 GB.', bullets: ['7B: 5,5 GB VRAM', '14B: Sweet Spot', '32B: beste Qualität'], updatedDate: '2026-05' },
      fr: {
        question: 'Meilleur modèle Qwen pour le codage ?',
        answer: 'Qwen3-Coder 32B est le meilleur avec 24 Go VRAM (91,5 % HumanEval). À 8 Go VRAM, le 7B atteint 79,7 %. Le 14B est le sweet spot à 12 Go.',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M : 5,5 Go VRAM, 79,7 % HumanEval',
          'Qwen3-Coder 14B Q4_K_M : 9,5 Go VRAM, 88,0 % — meilleur rapport qualité/VRAM',
          'Qwen3-Coder 32B Q4_K_M : 20,5 Go VRAM, 91,5 % — meilleure qualité',
        ],
        updatedDate: '2026-05',
      },
      ja: { question: 'コーディング向け最適Qwenモデルは？', answer: '24 GB VRAMなら32B、12 GBスイートスポットは14B、8 GBは7B。', bullets: ['7B：5.5 GB VRAM', '14B：スイートスポット', '32B：最高品質'], updatedDate: '2026-05' },
      zh: { question: '编程最佳Qwen模型？', answer: '24 GB显存选32B，12 GB选14B（最优性价比），8 GB选7B。', bullets: ['7B：5.5 GB显存', '14B：最优性价比', '32B：最佳质量'], updatedDate: '2026-05' },
    },
    sections: {
      tldr: {
        isTldr: true,
        items: [
          'Qwen3-Coder 32B Q4_K_M : 91,5 % HumanEval — meilleur modèle Qwen pour le code, nécessite 24 Go VRAM',
          'Qwen3-Coder 14B Q4_K_M : 88,0 % HumanEval à 9,5 Go VRAM — sweet spot pour RTX 3080/4070',
          'Qwen3-Coder 7B Q4_K_M : 79,7 % HumanEval à 5,5 Go VRAM — pour RTX 3060 ou 16 Go RAM',
          'Installation : `ollama pull qwen2.5-coder:7b` / `14b` / `32b`',
        ],
      },
      comparisonTable: {
        id: 'comparison',
        title: 'Comparaison des tailles Qwen3-Coder',
        content: ['Choisir le plus grand modèle qui tient entièrement en VRAM au niveau Q4_K_M.'],
        comparisonTable: {
          columns: ['Modèle', 'VRAM (Q4_K_M)', 'HumanEval (%)', 'Vitesse (GPU)', 'Idéal pour'],
          rows: [
            { 'Modèle': 'Qwen3-Coder 7B',  'VRAM (Q4_K_M)': '5,5 Go',  'HumanEval (%)': '79,7', 'Vitesse (GPU)': '8–15 tok/s', 'Idéal pour': 'RTX 3060 / 16 Go RAM' },
            { 'Modèle': 'Qwen3-Coder 14B', 'VRAM (Q4_K_M)': '9,5 Go',  'HumanEval (%)': '88,0', 'Vitesse (GPU)': '4–8 tok/s',  'Idéal pour': 'RTX 3080 / RTX 4070 / M2 Pro' },
            { 'Modèle': 'Qwen3-Coder 32B', 'VRAM (Q4_K_M)': '20,5 Go', 'HumanEval (%)': '91,5', 'Vitesse (GPU)': '2–4 tok/s',  'Idéal pour': 'RTX 4090 / M3 Max 48 Go' },
          ],
        },
      },
      verdict: {
        id: 'verdict',
        title: 'Verdict : quelle taille choisir',
        content: [
          '**8 Go VRAM ou moins :** Qwen3-Coder 7B Q4_K_M. Tient en 5,5 Go VRAM avec espace pour le KV cache.',
          '**12–16 Go VRAM :** Qwen3-Coder 14B Q4_K_M. Le bond de 7B à 14B est le meilleur gain qualité/VRAM.',
          '**24 Go VRAM :** Qwen3-Coder 32B Q4_K_M — dépasse GPT-4o mini sur les benchmarks de génération de code.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Questions fréquentes',
        faqs: [
          { q: 'Qwen3-Coder est-il meilleur que DeepSeek-Coder ?', a: 'Qwen3-Coder 32B atteint 91,5 % HumanEval vs ~80 % pour DeepSeek-Coder-V2-Lite au même VRAM.' },
          { q: 'Qwen3-Coder supporte-t-il les commentaires en chinois ?', a: 'Oui, il gère nativement les commentaires chinois/anglais mixtes.' },
          { q: 'Compatible avec Continue.dev ou Cline ?', a: 'Oui. Configurer Ollama comme backend, modèle `qwen2.5-coder:32b`.' },
          { q: 'Quelle quantisation utiliser ?', a: 'Q4_K_M : meilleur équilibre qualité/réduction VRAM (~35 %).' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'Meilleur modèle Qwen pour le codage ? 7B vs 14B vs 32B 2026',
      description: 'Comparaison des tailles Qwen3-Coder : 7B à 5,5 Go VRAM (79,7%), 14B à 9,5 Go (88%), 32B à 20,5 Go (91,5%).',
      url: 'https://www.promptquorum.com/fr/prompt-bites/best-qwen-model-for-coding',
      inLanguage: 'fr',
      author: { '@type': 'Person', name: 'Hans Kuepper' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      datePublished: '2026-05-26',
      dateModified: '2026-05-26',
      about: [{ '@type': 'Thing', name: 'Qwen3-Coder' }],
      mentions: [{ '@type': 'SoftwareApplication', name: 'Qwen3-Coder' }, { '@type': 'SoftwareApplication', name: 'Ollama' }],
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'fr',
      mainEntity: [
        { '@type': 'Question', name: 'Meilleur modèle Qwen pour coder à 8 Go VRAM ?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 7B Q4_K_M — 5,5 Go VRAM, 79,7 % HumanEval.' } },
      ],
    },
  },

  ja: {
    theme: 'Model Comparisons',
    title: 'コーディング向け最適Qwenモデルは？',
    seoTitle: 'コーディング向け最適Qwen3-Coderモデル 2026 | 7B vs 14B vs 32B',
    metaDescription: 'Qwen3-Coder 32Bが24 GB VRAMで最高（HumanEval 91.5%）。8 GBなら7B（79.7%）。12 GBのスイートスポットは14B。VRAMティア別サイズガイド。',
    publishDate: '2026-05-26',
    freshness_tier: 'semi_annual',
    next_refresh_due: '2026-11-26',
    educationalLevel: 'Intermediate',
    audience: 'ローカルコーディング向けQwen3-Coderサイズを選ぶ開発者',
    parentArticle: '/power-local-llm/best-local-coding-models-2026',
    siblingBites: ['qwen-coder-vs-deepseek-coder', 'can-you-run-qwen3-on-ollama'],
    is_living_page: false,
    quickAnswerTop: {
      en: { question: 'Best Qwen model for coding?', answer: '32B at 24 GB VRAM, 14B sweet spot at 12 GB, 7B at 8 GB.', bullets: ['7B: 5.5 GB VRAM', '14B: sweet spot', '32B: best'], updatedDate: '2026-05' },
      de: { question: 'Bestes Qwen-Modell für Coding?', answer: '32B bei 24 GB, 14B Sweet Spot bei 12 GB, 7B bei 8 GB.', bullets: ['7B: 5,5 GB', '14B: Sweet Spot', '32B: beste Qualität'], updatedDate: '2026-05' },
      fr: { question: 'Meilleur Qwen pour coder ?', answer: '32B à 24 Go, 14B sweet spot à 12 Go, 7B à 8 Go.', bullets: ['7B: 5,5 Go', '14B: sweet spot', '32B: meilleur'], updatedDate: '2026-05' },
      ja: {
        question: 'コーディング向け最適Qwenモデルは？',
        answer: 'Qwen3-Coder 32Bが24 GB VRAMで最高性能（HumanEval 91.5%）。8 GB VRAMなら7B（79.7%、8–15 tok/s）。14Bは12 GB VRAMの開発者に最適なスイートスポット。',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M：5.5 GB VRAM、HumanEval 79.7%——RTX 3060向け',
          'Qwen3-Coder 14B Q4_K_M：9.5 GB VRAM、HumanEval 88.0%——スイートスポット',
          'Qwen3-Coder 32B Q4_K_M：20.5 GB VRAM、HumanEval 91.5%——最高性能',
        ],
        updatedDate: '2026-05',
      },
      zh: { question: '编程最佳Qwen模型？', answer: '24 GB显存选32B，12 GB选14B，8 GB选7B。', bullets: ['7B：5.5 GB显存', '14B：最优性价比', '32B：最佳质量'], updatedDate: '2026-05' },
    },
    sections: {
      tldr: {
        isTldr: true,
        items: [
          'Qwen3-Coder 32B Q4_K_M：HumanEval 91.5%——最高のQwenコーディングモデル、24 GB VRAM必要',
          'Qwen3-Coder 14B Q4_K_M：9.5 GB VRAMでHumanEval 88.0%——RTX 3080/4070のスイートスポット',
          'Qwen3-Coder 7B Q4_K_M：5.5 GB VRAMでHumanEval 79.7%——RTX 3060や16 GB RAMに対応',
          'インストール：`ollama pull qwen2.5-coder:7b` / `14b` / `32b`',
        ],
      },
      comparisonTable: {
        id: 'comparison',
        title: 'Qwen3-Coderサイズ比較',
        content: ['Q4_K_MでVRAMに完全に収まる最大モデルを選択してください。'],
        comparisonTable: {
          columns: ['モデル', 'VRAM (Q4_K_M)', 'HumanEval (%)', 'GPU速度', '推奨環境'],
          rows: [
            { 'モデル': 'Qwen3-Coder 7B',  'VRAM (Q4_K_M)': '5.5 GB',  'HumanEval (%)': '79.7', 'GPU速度': '8–15 tok/s', '推奨環境': 'RTX 3060 / 16 GB RAM' },
            { 'モデル': 'Qwen3-Coder 14B', 'VRAM (Q4_K_M)': '9.5 GB',  'HumanEval (%)': '88.0', 'GPU速度': '4–8 tok/s',  '推奨環境': 'RTX 3080 / RTX 4070 / M2 Pro' },
            { 'モデル': 'Qwen3-Coder 32B', 'VRAM (Q4_K_M)': '20.5 GB', 'HumanEval (%)': '91.5', 'GPU速度': '2–4 tok/s',  '推奨環境': 'RTX 4090 / M3 Max 48 GB' },
          ],
        },
      },
      verdict: {
        id: 'verdict',
        title: '結論：どのサイズを選ぶか',
        content: [
          '**8 GB VRAM以下（RTX 3060、M2 16 GB）：** Qwen3-Coder 7B Q4_K_M。KVキャッシュ用のスペースを残してVRAMに収まります。',
          '**12–16 GB VRAM（RTX 3080、RTX 4070、M2 Pro）：** Qwen3-Coder 14B Q4_K_M。7Bから14Bへの品質向上が最もコスパ高い。',
          '**24 GB VRAM（RTX 4090、M3 Max 48 GB）：** Qwen3-Coder 32B Q4_K_M——コード生成ベンチマークでGPT-4o miniを上回ります。',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'よくある質問',
        faqs: [
          { q: 'Qwen3-CoderはDeepSeek-CoderよりPython性能が良いですか？', a: 'Qwen3-Coder 32BはHumanEval 91.5%で、同VRAMのDeepSeek-Coder-V2-Lite（~80%）を上回ります。' },
          { q: 'Qwen3-Coderは中国語コメントに対応していますか？', a: 'はい。中英混在コメントをネイティブで処理できます。' },
          { q: 'Continue.devやClineで使えますか？', a: 'はい。OllamaバックエンドとしてモデルをQwen3-Coderに設定するだけです。' },
          { q: '推奨量子化レベルは？', a: 'Q4_K_M——品質とVRAM削減（~35%）の最良バランス。' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'コーディング向け最適Qwenモデル？7B vs 14B vs 32B 2026',
      description: 'Qwen3-Coderサイズ比較：7B（5.5 GB VRAM、HumanEval 79.7%）、14B（9.5 GB、88.0%）、32B（20.5 GB、91.5%）。',
      url: 'https://www.promptquorum.com/ja/prompt-bites/best-qwen-model-for-coding',
      inLanguage: 'ja',
      author: { '@type': 'Person', name: 'Hans Kuepper' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      datePublished: '2026-05-26',
      dateModified: '2026-05-26',
      about: [{ '@type': 'Thing', name: 'Qwen3-Coder' }],
      mentions: [{ '@type': 'SoftwareApplication', name: 'Qwen3-Coder' }, { '@type': 'SoftwareApplication', name: 'Ollama' }],
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'ja',
      mainEntity: [
        { '@type': 'Question', name: '8 GB VRAMでのコーディング向け最適Qwenモデルは？', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 7B Q4_K_M——5.5 GB VRAM、HumanEval 79.7%。' } },
      ],
    },
  },

  zh: {
    theme: 'Model Comparisons',
    title: '编程最佳Qwen模型是哪个？',
    seoTitle: 'Qwen3-Coder 2026编程对比：7B vs 14B vs 32B各显存层级完整指南',
    metaDescription: 'Qwen3-Coder 32B在24 GB显存下以91.5% HumanEval得分领先；14B是12 GB显存速度与精度最均衡的选择；7B在8 GB显存下得79.7%，适合低显存设备。三款均支持Ollama本地运行，按显存预算精准匹配，无需订阅费用。',
    publishDate: '2026-05-26',
    freshness_tier: 'semi_annual',
    next_refresh_due: '2026-11-26',
    educationalLevel: 'Intermediate',
    audience: '为本地编程选择Qwen3-Coder型号的开发者',
    parentArticle: '/power-local-llm/best-local-coding-models-2026',
    siblingBites: ['qwen-coder-vs-deepseek-coder', 'can-you-run-qwen3-on-ollama'],
    is_living_page: false,
    quickAnswerTop: {
      en: { question: 'Best Qwen model for coding?', answer: '32B at 24 GB VRAM, 14B sweet spot at 12 GB, 7B at 8 GB.', bullets: ['7B: 5.5 GB VRAM', '14B: sweet spot', '32B: best'], updatedDate: '2026-05' },
      de: { question: 'Bestes Qwen-Modell für Coding?', answer: '32B bei 24 GB, 14B Sweet Spot bei 12 GB.', bullets: ['7B: 5,5 GB', '14B: Sweet Spot'], updatedDate: '2026-05' },
      fr: { question: 'Meilleur Qwen pour coder ?', answer: '32B à 24 Go, 14B sweet spot à 12 Go.', bullets: ['7B: 5,5 Go', '14B: sweet spot'], updatedDate: '2026-05' },
      ja: { question: 'コーディング向け最適Qwenモデルは？', answer: '24 GB VRAMなら32B、12 GBスイートスポットは14B。', bullets: ['7B：5.5 GB', '14B：スイートスポット'], updatedDate: '2026-05' },
      zh: {
        question: '编程最佳Qwen模型是哪个？',
        answer: 'Qwen3-Coder 32B在24 GB显存下表现最佳（HumanEval 91.5%）。8 GB显存选7B（79.7%，8–15 tok/s）；12 GB显存最优选择是14B（88.0%）。',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M：5.5 GB显存，HumanEval 79.7%，8–15 tok/s——RTX 3060或16 GB内存适用',
          'Qwen3-Coder 14B Q4_K_M：9.5 GB显存，HumanEval 88.0%——性价比最优',
          'Qwen3-Coder 32B Q4_K_M：20.5 GB显存，HumanEval 91.5%——最高性能',
          '纯CPU（无独立显卡）：16 GB内存运行7B，约8 tok/s',
        ],
        updatedDate: '2026-05',
      },
    },
    sections: {
      tldr: {
        isTldr: true,
        items: [
          'Qwen3-Coder 32B Q4_K_M：HumanEval 91.5%——最佳Qwen编程模型，需24 GB显存',
          'Qwen3-Coder 14B Q4_K_M：9.5 GB显存下HumanEval 88.0%——RTX 3080/4070的最优选择',
          'Qwen3-Coder 7B Q4_K_M：5.5 GB显存下HumanEval 79.7%——RTX 3060或16 GB内存可用',
          '安装命令：`ollama pull qwen2.5-coder:7b` / `14b` / `32b`',
        ],
      },
      comparisonTable: {
        id: 'comparison',
        title: 'Qwen3-Coder各规格对比',
        content: ['选择能以Q4_K_M完整装入显存的最大规格模型。'],
        comparisonTable: {
          columns: ['模型', '显存 (Q4_K_M)', 'HumanEval (%)', 'GPU速度', '适用场景'],
          rows: [
            { '模型': 'Qwen3-Coder 7B',  '显存 (Q4_K_M)': '5.5 GB',  'HumanEval (%)': '79.7', 'GPU速度': '8–15 tok/s', '适用场景': 'RTX 3060 / 16 GB内存' },
            { '模型': 'Qwen3-Coder 14B', '显存 (Q4_K_M)': '9.5 GB',  'HumanEval (%)': '88.0', 'GPU速度': '4–8 tok/s',  '适用场景': 'RTX 3080 / RTX 4070 / M2 Pro' },
            { '模型': 'Qwen3-Coder 32B', '显存 (Q4_K_M)': '20.5 GB', 'HumanEval (%)': '91.5', 'GPU速度': '2–4 tok/s',  '适用场景': 'RTX 4090 / M3 Max 48 GB' },
          ],
        },
      },
      verdict: {
        id: 'verdict',
        title: '结论：选哪个规格',
        content: [
          '**8 GB显存或更少（RTX 3060、M2 16 GB）：** Qwen3-Coder 7B Q4_K_M。5.5 GB显存装载后还有KV缓存空间。',
          '**12–16 GB显存（RTX 3080、RTX 4070、M2 Pro）：** Qwen3-Coder 14B Q4_K_M。从7B到14B是Coder系列中性价比最高的提升。',
          '**24 GB显存（RTX 4090、M3 Max 48 GB）：** Qwen3-Coder 32B Q4_K_M——代码生成基准测试超越GPT-4o mini，多文件上下文处理更强。',
          '**纯CPU（无独立GPU）：** 16 GB内存运行7B Q4_K_M，约8 tok/s——偶尔生成可接受，实时自动补全偏慢。',
        ],
      },
      faqSection: {
        id: 'faq',
        title: '常见问题',
        faqs: [
          { q: 'Qwen3-Coder比DeepSeek-Coder更适合Python吗？', a: 'Qwen3-Coder 32B HumanEval 91.5%，同显存的DeepSeek-Coder-V2-Lite约80%。Python专项Qwen3-Coder 32B领先。' },
          { q: 'Qwen3-Coder支持中文代码注释吗？', a: '支持。原生处理中英混合代码注释——对中文开发者是显著优势。' },
          { q: '可以与Continue.dev或Cline配合使用吗？', a: '可以。两者均支持Ollama后端，在设置中将模型设为`qwen2.5-coder:32b`即可。' },
          { q: '应该使用哪种量化级别？', a: 'Q4_K_M：质量与显存节省（~35%）的最佳平衡。' },
        ],
      },
      relatedReading: {
        id: 'related-reading',
        title: '相关阅读',
        items: [
          '[Qwen本地部署指南2026](/zh/local-llms/qwen-local-deployment-guide-2026) — 初学者友好的Qwen3 7B Ollama一键部署教程。',
          '[微信本地LLM集成2026](/zh/power-local-llm/wechat-local-llm-integration-2026) — Qwen3-Coder驱动微信机器人：实现个人AI编程助手。',
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: '编程最佳Qwen模型？7B vs 14B vs 32B 2026',
      description: 'Qwen3-Coder规格对比：7B（5.5 GB显存，HumanEval 79.7%）、14B（9.5 GB，88.0%）、32B（20.5 GB，91.5%）。',
      url: 'https://www.promptquorum.com/zh/prompt-bites/best-qwen-model-for-coding',
      inLanguage: 'zh',
      author: { '@type': 'Person', name: 'Hans Kuepper' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      datePublished: '2026-05-26',
      dateModified: '2026-05-26',
      about: [{ '@type': 'Thing', name: 'Qwen3-Coder本地部署' }],
      mentions: [{ '@type': 'SoftwareApplication', name: 'Qwen3-Coder' }, { '@type': 'SoftwareApplication', name: 'Ollama' }],
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'zh',
      mainEntity: [
        { '@type': 'Question', name: '8 GB显存下编程最佳Qwen模型？', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 7B Q4_K_M——5.5 GB显存，HumanEval 79.7%。' } },
        { '@type': 'Question', name: 'Qwen3-Coder支持中文注释吗？', acceptedAnswer: { '@type': 'Answer', text: '支持，原生处理中英混合代码注释。' } },
      ],
    },
  },

  es: {
    theme: 'Model Comparisons',
    title: '¿Cuál es el mejor modelo Qwen para programar?',
    seoTitle: 'Qwen3-Coder 2026: 7B vs 14B vs 32B por nivel de VRAM',
    metaDescription: 'Qwen3-Coder 32B lidera con 24 GB de VRAM (HumanEval 91,5%). Con 8 GB el 7B logra 79,7%. El 14B es el punto óptimo a 12 GB. Guía de tamaños por hardware.',
    publishDate: '2026-05-26',
    freshness_tier: 'semi_annual',
    next_refresh_due: '2026-11-26',
    educationalLevel: 'Intermediate',
    audience: 'Desarrolladores eligiendo entre los tamaños de Qwen3-Coder para programación local',
    parentArticle: '/power-local-llm/best-local-coding-models-2026',
    siblingBites: ['qwen-coder-vs-deepseek-coder', 'can-you-run-qwen3-on-ollama'],
    is_living_page: false,
    quickAnswerTop: {
      en: { question: 'Best Qwen model for coding?', answer: '32B at 24 GB VRAM, 14B sweet spot at 12 GB, 7B at 8 GB.', bullets: ['7B: 5.5 GB VRAM', '14B: sweet spot', '32B: best quality'], updatedDate: '2026-05' },
      de: { question: 'Bestes Qwen-Modell für Coding?', answer: '32B bei 24 GB, 14B Sweet Spot bei 12 GB.', bullets: ['7B: 5,5 GB', '14B: Sweet Spot'], updatedDate: '2026-05' },
      fr: { question: 'Meilleur Qwen pour coder ?', answer: '32B à 24 Go, 14B sweet spot à 12 Go.', bullets: ['7B: 5,5 Go', '14B: sweet spot'], updatedDate: '2026-05' },
      ja: { question: 'コーディング向け最適Qwenモデルは？', answer: '24 GB VRAMなら32B、12 GBスイートスポットは14B。', bullets: ['7B：5.5 GB', '14B：スイートスポット'], updatedDate: '2026-05' },
      zh: { question: '编程最佳Qwen模型？', answer: '24 GB显存选32B，12 GB选14B。', bullets: ['7B：5.5 GB显存', '14B：最优性价比'], updatedDate: '2026-05' },
      es: {
        question: '¿Cuál es el mejor modelo Qwen para programar?',
        answer: 'Qwen3-Coder 32B es el mejor con 24 GB VRAM (HumanEval 91.5%). A 8 GB VRAM el 7B alcanza 79.7%. El 14B es el punto óptimo a 12 GB VRAM.',
        bullets: [
          'Qwen3-Coder 7B Q4_K_M: 5.5 GB VRAM, HumanEval 79.7%',
          'Qwen3-Coder 14B Q4_K_M: 9.5 GB VRAM, HumanEval 88.0% — punto óptimo',
          'Qwen3-Coder 32B Q4_K_M: 20.5 GB VRAM, HumanEval 91.5% — máxima calidad',
        ],
        updatedDate: '2026-05',
      },
    },
    sections: {
      tldr: {
        isTldr: true,
        items: [
          'Qwen3-Coder 32B Q4_K_M: HumanEval 91.5% — mejor modelo Qwen para código, necesita 24 GB VRAM',
          'Qwen3-Coder 14B Q4_K_M: HumanEval 88.0% a 9.5 GB VRAM — punto óptimo para RTX 3080/4070',
          'Qwen3-Coder 7B Q4_K_M: HumanEval 79.7% a 5.5 GB VRAM — funciona con RTX 3060 o 16 GB RAM',
          'Instalación: `ollama pull qwen2.5-coder:7b` / `14b` / `32b`',
        ],
      },
      comparisonTable: {
        id: 'comparison',
        title: 'Comparativa de tamaños de Qwen3-Coder',
        content: ['Elige el modelo más grande que quepa completamente en VRAM a Q4_K_M sin descargar capas a CPU.'],
        comparisonTable: {
          columns: ['Modelo', 'VRAM (Q4_K_M)', 'HumanEval (%)', 'Velocidad (GPU)', 'Mejor para'],
          rows: [
            { 'Modelo': 'Qwen3-Coder 7B',  'VRAM (Q4_K_M)': '5.5 GB',  'HumanEval (%)': '79.7', 'Velocidad (GPU)': '8–15 tok/s', 'Mejor para': 'RTX 3060 / 16 GB RAM' },
            { 'Modelo': 'Qwen3-Coder 14B', 'VRAM (Q4_K_M)': '9.5 GB',  'HumanEval (%)': '88.0', 'Velocidad (GPU)': '4–8 tok/s',  'Mejor para': 'RTX 3080 / RTX 4070 / M2 Pro' },
            { 'Modelo': 'Qwen3-Coder 32B', 'VRAM (Q4_K_M)': '20.5 GB', 'HumanEval (%)': '91.5', 'Velocidad (GPU)': '2–4 tok/s',  'Mejor para': 'RTX 4090 / M3 Max 48 GB' },
          ],
        },
      },
      verdict: {
        id: 'verdict',
        title: 'Veredicto: qué tamaño ejecutar',
        content: [
          '**8 GB VRAM o menos (RTX 3060, M2 16 GB):** Qwen3-Coder 7B Q4_K_M. Cabe en 5.5 GB VRAM con margen para la caché KV. Para autocompletado y generación de funciones en un plugin de IDE, 79.7% HumanEval es suficiente.',
          '**12–16 GB VRAM (RTX 3080, RTX 4070, M2 Pro):** Qwen3-Coder 14B Q4_K_M. El salto de 7B a 14B es el mayor en calidad por VRAM de la familia Qwen Coder.',
          '**24 GB VRAM (RTX 4090, M3 Max 48 GB):** Qwen3-Coder 32B Q4_K_M. Supera a GPT-4o mini en benchmarks de generación de código y maneja mejor el contexto multi-archivo.',
          '**Solo CPU (sin GPU dedicada):** 7B Q4_K_M con 16 GB RAM, ~8 tok/s. Aceptable para generación ocasional; demasiado lento para autocompletado en tiempo real.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Preguntas frecuentes',
        faqs: [
          { q: '¿Es Qwen3-Coder mejor que DeepSeek-Coder para Python?', a: 'Qwen3-Coder 32B obtiene 91.5% HumanEval frente a ~80% de DeepSeek-Coder-V2-Lite. Para Python específicamente, Qwen3-Coder 32B lidera al mismo nivel de VRAM.' },
          { q: '¿Qwen3-Coder admite comentarios en chino?', a: 'Sí. Maneja comentarios de código mixtos chino/inglés de forma nativa — una ventaja significativa para desarrolladores chinos.' },
          { q: '¿Puedo usar Qwen3-Coder con Continue.dev o Cline?', a: 'Sí. Ambos admiten backends de Ollama. Establece el modelo como `qwen2.5-coder:32b` en la configuración de Continue.dev o Cline.' },
          { q: '¿Qué nivel de cuantización debo usar?', a: 'Q4_K_M es el mejor equilibrio: calidad casi igual a la precisión completa con ~35% de reducción de VRAM. Usa Q8_0 solo si tienes VRAM de sobra y quieres máxima precisión.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: '¿Cuál es el mejor modelo Qwen para programar? 7B vs 14B vs 32B',
      description: 'Comparativa de tamaños Qwen3-Coder: 7B a 5.5 GB VRAM (79.7% HumanEval), 14B a 9.5 GB (88.0%), 32B a 20.5 GB (91.5%). Elige el tamaño correcto para tu hardware.',
      url: 'https://www.promptquorum.com/es/prompt-bites/best-qwen-model-for-coding',
      inLanguage: 'es',
      author: { '@type': 'Person', name: 'Hans Kuepper' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      datePublished: '2026-05-26',
      dateModified: '2026-05-26',
      about: [{ '@type': 'Thing', name: 'Qwen3-Coder LLM Local' }],
      mentions: [{ '@type': 'SoftwareApplication', name: 'Qwen3-Coder' }, { '@type': 'SoftwareApplication', name: 'Ollama' }],
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'es',
      mainEntity: [
        { '@type': 'Question', name: '¿Cuál es el mejor modelo Qwen para programar con 8 GB VRAM?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 7B Q4_K_M — cabe en 5.5 GB VRAM, HumanEval 79.7%, 8–15 tok/s.' } },
        { '@type': 'Question', name: '¿Cuál es el mejor modelo Qwen para programar con 12–16 GB VRAM?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen3-Coder 14B Q4_K_M — 9.5 GB VRAM, HumanEval 88.0%, la mejor relación calidad/VRAM de la familia.' } },
      ],
    },
  },
}
