export interface LLMTheme {
  id: string
  title: string
  description: string
  articleKeys: string[]
}

export const llmThemes: LLMTheme[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    description: 'Zero-to-running in under 10 minutes. OS-specific installation guides, first-model walkthroughs, and a privacy-first setup checklist for beginners. Ollama installs with a single command on macOS, Windows, and Linux. For 8 GB RAM, start with Llama 3.2 3B (Q4, ~2 GB) using `ollama pull llama3.2:3b`.',
    articleKeys: [
      'what-are-local-llms',
      'local-llms-vs-cloud-apis',
      'how-to-install-ollama',
      'how-to-install-lm-studio',
      'run-first-local-llm',
      'best-beginner-local-llm-models',
      'local-llm-one-click-installers',
      'troubleshooting-local-llm-setup',
      'local-llm-on-laptop',
      'local-llm-security-privacy-checklist',
      'local-llm-limitations',
      'qwen-local-deployment-guide-2026',
      'run-qwen-locally-guide-2026',
    ],
  },
  {
    id: 'best-models',
    title: 'Models by Use Case',
    description: 'Model reviews, benchmark comparisons, use-case winners, and quantization guides for Llama 4, Qwen3.5, DeepSeek, Gemma 4, and 70B+ models. Qwen2.5-Coder leads coding benchmarks; Mistral 7B is fastest for RAM-constrained setups. Every review includes exact VRAM requirements and benchmark scores versus GPT-4o.',
    articleKeys: [
      'best-local-llms-2026',
      'qwen-vs-llama-vs-mistral',
      'best-local-llms-for-coding',
      'best-local-llms-for-creative-writing',
      'small-local-llm-models',
      '70b-models-consumer-hardware',
      'llm-quantization-explained',
      'long-context-local-llms',
      'top-open-source-models-ollama',
      'local-llm-model-updates-2026',
      'best-local-llms-code-review',
      'best-local-llms-business-writing',
      'best-7b-models-consumer-hardware',
      'fastest-local-llms-low-end-pcs',
      'quantization-levels-comparison',
      'best-cpu-only-llm',
      'multilingual-local-llms',
      'glm-5-2-open-weights-frontier-2026',
      'best-arabic-local-llms-2026',
      'best-saudi-arabic-local-llms-allam-2026',
      'best-local-llms-portuguese-language-2026',
      'qwen-vs-claude-vs-deepseek-local-2026',
      'qwen-coder-vs-deepseek-mistral-local-2026',
      'best-local-reasoning-model-deepseek-r1-2026',
    ],
  },
  {
    id: 'tools-interfaces',
    title: 'Tools & Interfaces',
    description: 'Software showdowns, GUI comparisons, API setups, and front-end guides — Ollama, LM Studio, OpenWebUI, vLLM, llama.cpp, and more. Ollama exposes an OpenAI-compatible REST API at `localhost:11434` — drop-in replacement for cloud SDKs with no code changes. LM Studio adds a GUI and model browser for non-technical users.',
    articleKeys: [
      'ollama-vs-lm-studio',
      'best-local-llm-frontends',
      'text-generation-webui-vs-vllm-vs-llamacpp',
      'local-llm-openai-compatible-api',
      'lm-studio-advanced-features',
      'ollama-command-guide',
      'best-local-rag-tools',
      'desktop-vs-webui-local-llm',
      'local-llms-with-vscode-cursor',
      'headless-local-llms',
      'best-local-llm-stack-use-case',
      'lm-studio-vs-jan-ai',
      'open-webui-vs-sillytavern',
      'llamacpp-vs-ollama-vs-vllm',
      'local-llm-developer-stack',
      'cherry-studio-ai-desktop-client',
      'open-webui-review',
      'lobechat-review',
      'big-agi-review',
      'nextchat-review',
      'page-assist-review',
      'chatbox-review',
      'text-generation-webui-review',
      'sillytavern-review',
      'lobechat-bigagi-nextchat-pageassist-chatbox-compared',
      'best-ai-coding-assistant-local-llm',
      'xinference-llama-qwen-chatglm-mistral',
    ],
  },
  {
    id: 'hardware-performance',
    title: 'Hardware & Performance',
    description: 'Real hardware recommendations, VRAM math, GPU benchmarks, quantization trade-offs, and optimization tricks for RTX 5090, 4090, Mac Silicon, and budget builds. RTX 4060 (8 GB VRAM, ~$300) runs 7B models at 30+ tokens/sec. Apple Silicon M2 handles 7B–13B natively via Metal with no discrete GPU required.',
    articleKeys: [
      'local-llm-hardware-guide-2026',
      'vram-calculator-local-llm',
      'gpu-vs-cpu-vs-apple-silicon',
      'double-local-llm-speed',
      'best-gpus-for-local-llms',
      'run-70b-models-24gb-vram',
      'local-llm-power-consumption',
      'multi-gpu-local-llms',
      'laptop-vs-desktop-local-llm',
      'mobile-local-llms',
      'mram-in-memory-computing-local-ai-2026',
      'galaxy-vs-iphone-on-device-ai-2026',
      'galaxy-s26-local-ai-on-device-2026',
      'hbm-memory-on-device-ai-samsung-sk-hynix-2026',
    ],
  },
  {
    id: 'advanced-techniques',
    title: 'Advanced Techniques & Applications',
    description: 'Beyond basic chat — local RAG pipelines, LoRA fine-tuning, LangGraph agents, coding workflows, multimodal models, and custom model creation. Local RAG with Ollama + ChromaDB answers questions over private documents without cloud transfer. LoRA fine-tuning requires 500+ labeled examples and 24 GB+ VRAM; cloud GPU rental is a cost-effective alternative.',
    articleKeys: [
      'local-rag-2026',
      'fine-tuning-local-llms-lora',
      'local-ai-agents-langgraph-ollama',
      'prompt-engineering-for-local-models',
      'private-local-ai-for-business',
      'local-llms-for-coding-workflows',
      'multimodal-local-llms',
      'local-vs-cloud-agents',
      'create-custom-local-models',
      'future-of-local-llms',
      'run-qwen-vl-locally-2026',
    ],
  },
  {
    id: 'enterprise',
    title: 'Enterprise',
    description: 'On-prem deployment, air-gapped setups, GDPR/HIPAA compliance, multi-user scaling, and private RAG for organizations requiring full data sovereignty. Air-gapped setups bind Ollama to `localhost` with no external network access. GDPR compliance requires network isolation, full-disk encryption, and access logging — all covered in these guides.',
    articleKeys: [
      'why-enterprises-use-local-llms',
      'on-prem-air-gapped-local-llm',
      'enterprise-compliance-local-llms',
      'scaling-local-llms-enterprise',
      'corporate-rag-local-llms',
      'uae-pdpl-data-sovereignty-local-ai-2026',
      'saudi-pdpl-data-sovereignty-local-ai-2026',
      'local-llm-lgpd-compliance-brazil-2026',
      'eu-cloud-gpu-gdpr-2026',
      'gdpr-llm-risk-comparison-2026',
      'qwen-local-gdpr-setup-guide-2026',
      'qwen-gdpr-privacy-manifesto-2026',
      'deepseek-local-china-data-privacy-2026',
    ],
  },
  {
    id: 'gpu-buying-guides',
    title: 'GPU Buying Guides',
    description: 'GPU recommendations, budget picks, next-gen comparisons, and used-market value for running 7B to 70B models.',
    articleKeys: [
      'best-budget-gpus-local-llm',
      'rtx-5090-vs-rtx-4090-local-llm',
      'used-gpus-for-local-llms',
      'how-much-vram-local-llm',
      'best-amd-gpus-local-llm',
      'best-gpu-for-llm-inference-under-500-2026',
    ],
  },
  {
    id: 'hardware-setups',
    title: 'Hardware Setups',
    description: 'Complete system builds, mini PCs, laptops, and workstations at multiple price points for serious local inference.',
    articleKeys: [
      'local-llm-pc-build-1000',
      'local-llm-pc-build-2000',
      'local-llm-workstation-build',
      'best-mini-pcs-local-llm',
      'best-laptops-local-llm',
      'best-amd-mini-pc-local-llm-2026',
    ],
  },
  {
    id: 'privacy-business',
    title: 'Privacy & Business',
    description: 'Secure on-premises setups, multi-user deployments, NAS storage, and offline workflows for compliance-heavy organizations.',
    articleKeys: [
      'private-local-llm-sensitive-data',
      'local-llm-setup-for-teams',
      'best-nas-storage-local-llm',
      'vpn-for-local-llm-users',
      'secure-offline-local-llm-workflow',
    ],
  },
  {
    id: 'cost-comparisons',
    title: 'Cost & Comparisons',
    description: 'ROI analysis, price comparisons, total cost of ownership, and platform comparisons (Local vs CloudGPU vs Subscriptions).',
    articleKeys: [
      'local-llms-vs-chatgpt-plus',
      'local-llms-vs-claude-pro',
      'local-llm-vs-cloud-gpu-cost',
      'mac-vs-windows-vs-linux-local-llm',
      'gpu-vs-ai-subscription-roi',
      'alibaba-cloud-vs-tencent-cloud-gpu-ai-2026',
      'local-llm-cost-calculator-build-vs-rent-2026',
      'cloud-gpu-rental-comparison-2026',
    ],
  },
  {
    id: 'apple-silicon',
    title: 'Apple Silicon',
    description: 'Mac-specific guides for M-series Apple Silicon — unified memory sizing, MLX vs Ollama vs llama.cpp benchmarks, Whisper transcription on Metal, and Mac Mini/MacBook builds for local inference. Apple Silicon shares unified memory between CPU and GPU, so a 32 GB M-series Mac can run 30B-parameter models without a discrete GPU. MLX is Apple\'s own inference framework and is typically faster than llama.cpp on the same chip.',
    articleKeys: [
      'apple-silicon-m5-local-llm',
      'apple-silicon-local-llm-guide-2026',
      'm5-pro-max-llm-benchmarks-2026',
      'how-much-unified-memory-for-local-llm',
      'mlx-vs-ollama-vs-llama-cpp-mac',
      'ollama-on-mac-apple-silicon-setup-2026',
      'best-models-apple-silicon-2026',
      'mac-mini-m5-local-ai-server',
      'apple-silicon-whisper-metal-benchmark',
      'running-70b-models-apple-silicon-m5-max',
      'apple-silicon-vs-nvidia-gpu-local-llm',
      'apple-on-device-ai-vs-local-llms',
    ],
  },
  {
    id: 'enterprise-compliance',
    title: 'Enterprise & Compliance',
    description: 'Buying guides for enterprise GPU servers, SOC 2 and ISO 27001 compliance for self-hosted LLMs, commercial licensing terms, and head-to-head comparisons of API gateways, fine-tuning frameworks, agent frameworks, evaluation tools, observability platforms, and vector databases for production deployments. Renting cloud GPUs typically breaks even against buying on-premises hardware within 8-14 months for continuous workloads.',
    articleKeys: [
      'enterprise-gpu-server-buying-guide',
      'soc2-iso27001-self-hosted-llm-compliance',
      'data-residency-sovereign-ai-eu-gdpr-enterprise',
      'local-llm-commercial-license-guide-business',
      'renting-gpu-cloud-vs-buying-on-prem-enterprise-ai',
      'best-llm-api-gateway',
      'best-ai-code-review-tools',
      'local-ai-code-review-vs-coderabbit',
      'best-llm-fine-tuning-framework',
      'best-ai-agent-framework',
      'best-llm-evaluation-tools',
      'best-llm-observability-tools',
      'best-vector-database',
    ],
  },
]
