// Slug: balkonstrom-balcony-solar
// Phase 1 scaffold (2026-07-19) — structure/frontmatter only, no body content yet.
// Noindex + sitemap-excluded via PENDING_SLUGS in published.ts until content,
// translation, and internal-linking phases land (see TIER 6 in slugs.ts).
import type { Language } from "@/lib/blog/blogContent";
import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    freshness_tier: 'semi_annual',
    next_refresh_due: '2027-01-19',
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-en.webp',
    title: 'balkonstrom.com: Balcony Solar Company Profile',
    seoTitle: 'balkonstrom.com Balcony Solar Company Profile',
    metaDescription: 'Company profile for balkonstrom.com: history, ownership, and product range in the balcony solar market.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Readers researching balkonstrom.com as a company',
    intro: 'balkonstrom.com commissions custom "Made in Germany" DC cables from a named supplier rather than sourcing generic cabling for its kits. Registered as a GmbH in Uettingen, Bavaria, in August 2023 by two brothers from the Würzburg district, the company\'s own earlier claim of an informal 2021 start could not be independently verified — only the 2023 registration date is registry-confirmed. Germany is confirmed via a physical showroom in Uettingen; an Austria claim was not independently confirmed in this research.',
    // No cross-link requirement specified for this profile in Phase 1.
    sections: {
      snapshot: { title: 'balkonstrom.com: Company Snapshot', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: 'Uettingen, Bavaria, Germany; GmbH registered August 2023, founded by two brothers from the Würzburg district.' },
      timeline: { title: 'Timeline', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'GmbH registration date is the only firmly registry-confirmed date; an earlier informal-start claim (2021) is unverified.' },
      lineup: { title: 'Kit Lineup (Output)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: 'System output per bundle, as officially listed, paired with named battery hardware.' },
      markets: { title: 'Confirmed Market', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: 'Germany confirmed with a physical Uettingen showroom; Austria is claimed but not independently confirmed in this research.' },
      position: { title: 'Where balkonstrom.com Sits', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: 'Sources TÜV-certified panels and third-party storage; commissions custom "Made in Germany" DC cables from a named supplier.' },
      partners: { title: 'Confirmed Component Suppliers', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: 'Named directly on balkonstrom.com’s own product listings.' },
    },
  },
  de: {
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-de.webp',
    title: 'balkonstrom.com: Firmenprofil Balkonsolar-Anbieter',
    seoTitle: 'balkonstrom.com Firmenprofil Balkonsolar-Anbieter',
    metaDescription: 'Unternehmensprofil zu balkonstrom.com: Firmengeschichte, Eigentümerstruktur und Produktpalette im deutschen Markt für Balkonkraftwerke.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Leser, die sich über balkonstrom.com als Unternehmen informieren',
    intro: 'balkonstrom.com lässt individuelle DC-Kabel „Made in Germany" von einem namentlich genannten Lieferanten fertigen, statt generische Verkabelung für seine Sets zu beziehen. Die im August 2023 in Uettingen, Bayern, eingetragene GmbH wurde von zwei Brüdern aus dem Landkreis Würzburg gegründet; eine frühere eigene Angabe eines informellen Starts 2021 konnte nicht unabhängig verifiziert werden — nur das Eintragungsdatum 2023 ist registerlich bestätigt. Deutschland ist durch einen physischen Showroom in Uettingen bestätigt; eine Österreich-Angabe wurde in dieser Recherche nicht unabhängig bestätigt.',
    sections: {
      snapshot: { title: 'balkonstrom.com: Unternehmensüberblick', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: 'Uettingen, Bayern, Deutschland; GmbH eingetragen im August 2023, gegründet von zwei Brüdern aus dem Landkreis Würzburg.' },
      timeline: { title: 'Zeitleiste', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'Das GmbH-Eintragungsdatum ist das einzige registerlich bestätigte Datum; eine frühere informelle Gründungsangabe (2021) ist nicht verifiziert.' },
      lineup: { title: 'Produktreihe (Leistung)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: 'Systemleistung je Paket, wie offiziell angegeben, kombiniert mit namentlich genannter Batteriehardware.' },
      markets: { title: 'Bestätigter Markt', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: 'Deutschland bestätigt durch einen physischen Showroom in Uettingen; Österreich wird beansprucht, ist in dieser Recherche jedoch nicht unabhängig bestätigt.' },
      position: { title: 'Positionierung von balkonstrom.com', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: 'Bezieht TÜV-zertifizierte Module und Speicher von Drittanbietern; lässt individuelle DC-Kabel „Made in Germany" von einem namentlich genannten Lieferanten fertigen.' },
      partners: { title: 'Bestätigte Komponentenlieferanten', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: 'Direkt auf den eigenen Produktseiten von balkonstrom.com genannt.' },
    },
  },
  fr: {
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-fr.webp',
    title: 'balkonstrom.com : profil d\'entreprise solaire de balcon',
    seoTitle: 'balkonstrom.com : profil de l\'entreprise solaire balcon',
    metaDescription: 'Profil de l\'entreprise balkonstrom.com : historique, actionnariat et gamme de produits sur le marché du solaire de balcon.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Lecteurs qui recherchent des informations sur balkonstrom.com en tant qu\'entreprise',
    intro: 'balkonstrom.com fait fabriquer des câbles CC personnalisés « Made in Germany » par un fournisseur nommé plutôt que d\'utiliser du câblage générique pour ses kits. Immatriculée comme GmbH à Uettingen, en Bavière, en août 2023 par deux frères originaires du district de Würzburg, l\'entreprise revendique un début informel en 2021 qui n\'a pas pu être vérifié de manière indépendante — seule la date d\'immatriculation de 2023 est confirmée par le registre. L\'Allemagne est confirmée par un showroom physique à Uettingen ; une présence revendiquée en Autriche n\'a pas été confirmée de manière indépendante dans cette recherche.',
    sections: {
      snapshot: { title: 'balkonstrom.com : aperçu de l\'entreprise', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: 'Uettingen, Bavière, Allemagne ; GmbH immatriculée en août 2023, fondée par deux frères du district de Würzburg.' },
      timeline: { title: 'Chronologie', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'La date d\'immatriculation de la GmbH est la seule date confirmée par le registre ; une allégation antérieure de démarrage informel (2021) n\'est pas vérifiée.' },
      lineup: { title: 'Gamme de kits (puissance)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: 'Puissance du système par kit, telle qu\'indiquée officiellement, associée à du matériel de batterie nommé.' },
      markets: { title: 'Marché confirmé', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: 'Allemagne confirmée avec un showroom physique à Uettingen ; l\'Autriche est revendiquée mais non confirmée de manière indépendante dans cette recherche.' },
      position: { title: 'Positionnement de balkonstrom.com', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: 'S\'approvisionne en panneaux certifiés TÜV et en stockage tiers ; fait fabriquer des câbles DC sur mesure « Made in Germany » par un fournisseur nommé.' },
      partners: { title: 'Fournisseurs de composants confirmés', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: 'Nommés directement sur les fiches produits de balkonstrom.com.' },
    },
  },
  ja: {
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-ja.webp',
    title: 'balkonstrom.com:バルコニー太陽光発電会社プロファイル',
    seoTitle: 'balkonstrom.com バルコニー太陽光発電 企業プロファイル',
    metaDescription: 'balkonstrom.comの企業プロファイルです。バルコニー太陽光発電市場における沿革、所有構造、製品ラインナップの詳細を紹介する会社概要ページです。',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'balkonstrom.comを企業として調査している読者向け',
    intro: 'balkonstrom.comは、キットに汎用ケーブルを使うのではなく、指定サプライヤーに「Made in Germany」のカスタムDCケーブルを発注しています。同社は2023年8月にドイツ・バイエルン州ウェッティンゲンでGmbH(有限会社)として登記され、ヴュルツブルク郡出身の兄弟2人が設立しましたが、以前主張していた2021年の非公式な創業時期は独立した検証ができておらず、登記簿で確認できる確実な日付は2023年の登記日のみです。ドイツでの展開はウェッティンゲンの実店舗ショールームにより確認されている一方、オーストリアでの展開という主張は本調査では独立した確認が取れませんでした。',
    sections: {
      snapshot: { title: 'balkonstrom.com:企業スナップショット', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: 'ドイツ・バイエルン州ウェッティンゲンに所在。GmbH(有限会社)は2023年8月に登記され、ヴュルツブルク郡出身の兄弟2人によって設立されました。' },
      timeline: { title: '沿革', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'GmbHの登記日のみが登記簿で確認された確実な日付です。それ以前の非公式な創業時期(2021年)という主張は未確認です。' },
      lineup: { title: 'キット製品ライン(出力)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: '公式に記載されているバンドルごとのシステム出力で、指定されたバッテリー機器と組み合わされています。' },
      markets: { title: '確認済み市場', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: 'ウェッティンゲンの実店舗ショールームによりドイツでの展開が確認されています。オーストリアについては主張されていますが、本調査では独立した確認は取れていません。' },
      position: { title: 'balkonstrom.comの市場での位置付け', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: 'TÜV認証パネルとサードパーティ製蓄電システムを調達し、指定サプライヤーに「Made in Germany」のカスタムDCケーブルを発注しています。' },
      partners: { title: '確認済みの部品サプライヤー', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: 'balkonstrom.com自身の製品ページに直接記載されています。' },
    },
  },
  zh: {
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-zh.webp',
    title: 'balkonstrom.com:阳台太阳能公司概况',
    seoTitle: 'balkonstrom.com 阳台太阳能公司概况',
    metaDescription: 'balkonstrom.com公司概况:详细介绍该品牌在阳台太阳能市场中的发展历史、所有权结构、创立背景及产品线情况。',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: '正在调研balkonstrom.com这家公司的读者',
    intro: 'balkonstrom.com并未为其套件采购通用线缆,而是委托指定供应商定制生产"德国制造"的直流电缆。该公司于2023年8月在德国巴伐利亚州厄廷根注册为GmbH,由来自维尔茨堡地区的两兄弟创立;此前公司自称2021年非正式起步的说法未能独立核实——唯有2023年的注册日期经登记机构确认。德国市场已通过厄廷根的实体展厅得到确认;而奥地利市场的说法在本次调研中未能独立证实。',
    sections: {
      snapshot: { title: 'balkonstrom.com:公司概览', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: '位于德国巴伐利亚州厄廷根(Uettingen);GmbH于2023年8月注册,由维尔茨堡地区的两兄弟创立。' },
      timeline: { title: '发展历程', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'GmbH注册日期是唯一经登记机构确认的日期;更早的非正式创立说法(2021年)未经证实。' },
      lineup: { title: '套件产品线(输出功率)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: '官方列出的各套件系统输出功率,并配有指定的电池硬件。' },
      markets: { title: '已确认市场', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: '德国市场已通过厄廷根实体展厅确认;奥地利市场为公司自称,本次调研未能独立证实。' },
      position: { title: 'balkonstrom.com的市场定位', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: '采购经TÜV认证的太阳能板及第三方储能设备;委托指定供应商定制生产"德国制造"直流电缆。' },
      partners: { title: '已确认的部件供应商', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: '直接列于balkonstrom.com自身的产品页面上。' },
    },
  },
  es: {
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-es.webp',
    title: 'balkonstrom.com: perfil de la empresa de energía solar de balcón',
    seoTitle: 'balkonstrom.com: perfil de empresa solar de balcón',
    metaDescription: 'Perfil de la empresa balkonstrom.com: historia, propiedad y gama de productos en el mercado de energía solar de balcón.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Lectores que investigan balkonstrom.com como empresa',
    intro: 'balkonstrom.com encarga cables de CC personalizados "Made in Germany" a un proveedor especificado, en lugar de usar cableado genérico en sus kits. Registrada como GmbH en Uettingen, Baviera, en agosto de 2023 por dos hermanos del distrito de Würzburg, la afirmación previa de la propia empresa sobre un inicio informal en 2021 no pudo verificarse de forma independiente — solo la fecha de registro de 2023 está confirmada por el registro mercantil. Alemania está confirmada mediante una sala de exposición física en Uettingen; una afirmación sobre Austria no se confirmó de forma independiente en esta investigación.',
    sections: {
      snapshot: { title: 'balkonstrom.com: panorama de la empresa', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: 'Uettingen, Baviera, Alemania; GmbH registrada en agosto de 2023, fundada por dos hermanos del distrito de Würzburg.' },
      timeline: { title: 'Cronología', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'La fecha de registro de la GmbH es la única fecha confirmada por el registro mercantil; una afirmación anterior de inicio informal (2021) no está verificada.' },
      lineup: { title: 'Gama de kits (potencia)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: 'Potencia del sistema por paquete, según lo indicado oficialmente, junto con el hardware de batería especificado.' },
      markets: { title: 'Mercado confirmado', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: 'Alemania confirmada con una sala de exposición física en Uettingen; Austria se menciona como mercado, pero no se confirmó de forma independiente en esta investigación.' },
      position: { title: 'Posicionamiento de balkonstrom.com', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: 'Se abastece de paneles certificados por TÜV y almacenamiento de terceros; encarga cables de CC personalizados "Made in Germany" a un proveedor especificado.' },
      partners: { title: 'Proveedores de componentes confirmados', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: 'Mencionados directamente en las propias fichas de producto de balkonstrom.com.' },
    },
  },
  pt: {
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-pt.webp',
    title: 'balkonstrom.com: perfil da empresa de energia solar de varanda',
    seoTitle: 'balkonstrom.com: perfil de empresa solar de varanda',
    metaDescription: 'Perfil da empresa balkonstrom.com: história, estrutura societária e linha de produtos no mercado de energia solar de varanda.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Leitores que pesquisam a balkonstrom.com como empresa',
    intro: 'A balkonstrom.com encomenda cabos DC personalizados "Made in Germany" de um fornecedor especificado, em vez de usar cabeamento genérico em seus kits. Registrada como GmbH em Uettingen, na Baviera, em agosto de 2023 por dois irmãos do distrito de Würzburg, a alegação anterior da própria empresa de um início informal em 2021 não pôde ser verificada de forma independente — apenas a data de registro de 2023 é confirmada oficialmente. A Alemanha é confirmada por um showroom físico em Uettingen; uma alegação sobre a Áustria não foi confirmada de forma independente nesta pesquisa.',
    sections: {
      snapshot: { title: 'balkonstrom.com: visão geral da empresa', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: 'Uettingen, Baviera, Alemanha; GmbH registrada em agosto de 2023, fundada por dois irmãos do distrito de Würzburg.' },
      timeline: { title: 'Linha do tempo', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'A data de registro da GmbH é a única data confirmada oficialmente; uma alegação anterior de início informal (2021) não foi verificada.' },
      lineup: { title: 'Linha de kits (potência)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: 'Potência do sistema por kit, conforme informado oficialmente, combinada com hardware de bateria especificado.' },
      markets: { title: 'Mercado confirmado', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: 'Alemanha confirmada com showroom físico em Uettingen; a Áustria é mencionada, mas não foi confirmada de forma independente nesta pesquisa.' },
      position: { title: 'Posicionamento da balkonstrom.com', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: 'Utiliza painéis certificados pela TÜV e armazenamento de terceiros; encomenda cabos DC personalizados "Made in Germany" de um fornecedor especificado.' },
      partners: { title: 'Fornecedores de componentes confirmados', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: 'Citados diretamente nas páginas de produto da própria balkonstrom.com.' },
    },
  },
  ar: {
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-ar.webp',
    title: 'balkonstrom.com: الملف التعريفي لشركة الطاقة الشمسية للشرفات',
    seoTitle: 'balkonstrom.com: ملف شركة الطاقة الشمسية للشرفات',
    metaDescription: 'الملف التعريفي الكامل لشركة balkonstrom.com: التاريخ والملكية وتشكيلة المنتجات ضمن سوق الطاقة الشمسية للشرفات في ألمانيا.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'القراء الذين يبحثون عن balkonstrom.com كشركة',
    intro: 'تطلب balkonstrom.com تصنيع كابلات تيار مستمر (DC) مخصصة بعلامة "Made in Germany" من مورد محدد بالاسم، بدلاً من استخدام كابلات عامة في أطقمها. سُجّلت الشركة كشركة (GmbH) في أوتينغن ببافاريا في أغسطس 2023 على يد شقيقين من منطقة فورتسبورغ، ولم يتم التحقق بشكل مستقل من ادعاء سابق للشركة نفسها ببداية غير رسمية عام 2021 — إذ إن تاريخ التسجيل عام 2023 هو وحده المؤكد رسميًا من السجل. تم تأكيد وجود الشركة في ألمانيا عبر صالة عرض فعلية في أوتينغن؛ أما الادعاء بالتواجد في النمسا فلم يتم تأكيده بشكل مستقل في هذا البحث.',
    sections: {
      snapshot: { title: 'balkonstrom.com: لمحة عن الشركة', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: 'أوتينغن، بافاريا، ألمانيا؛ تم تسجيل الشركة (GmbH) في أغسطس 2023، وأسسها شقيقان من منطقة فورتسبورغ (Würzburg).' },
      timeline: { title: 'الجدول الزمني', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'تاريخ تسجيل الشركة (GmbH) هو التاريخ الوحيد المؤكد رسميًا من السجل؛ أما الادعاء السابق ببداية غير رسمية في عام 2021 فغير موثق.' },
      lineup: { title: 'تشكيلة الأطقم (الطاقة الناتجة)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: 'الطاقة الناتجة للنظام لكل حزمة، كما هو مدرج رسميًا، مقترنة بأجهزة بطارية محددة بالاسم.' },
      markets: { title: 'السوق المؤكد', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: 'تم تأكيد ألمانيا من خلال صالة عرض فعلية في أوتينغن؛ أما النمسا فهي مزعومة ولم يتم تأكيدها بشكل مستقل في هذا البحث.' },
      position: { title: 'موقع balkonstrom.com في السوق', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: 'تحصل على ألواح معتمدة من TÜV وأنظمة تخزين من أطراف ثالثة؛ وتطلب تصنيع كابلات تيار مستمر (DC) مخصصة بعلامة "Made in Germany" من مورد محدد بالاسم.' },
      partners: { title: 'موردو المكونات المؤكدون', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: 'مذكورون مباشرة في صفحات المنتجات الخاصة بـ balkonstrom.com.' },
    },
  },
  ko: {
    theme: 'Balcony Solar Money Pages',
    heroImage: '/images/balkonstrom-balcony-solar-overview-hero-ko.webp',
    title: 'balkonstrom.com: 발코니 태양광 기업 프로필',
    seoTitle: 'balkonstrom.com 발코니 태양광 기업 프로필',
    metaDescription: 'balkonstrom.com 기업 프로필입니다. 발코니 태양광 시장에서의 연혁, 소유 구조, 제품 라인업을 자세히 소개합니다.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'balkonstrom.com을 기업으로 조사하는 독자',
    intro: 'balkonstrom.com은 키트에 일반 케이블을 사용하는 대신, 지정된 공급업체에 "Made in Germany" 맞춤형 DC 케이블 제작을 의뢰합니다. 이 회사는 2023년 8월 독일 바이에른주 우에팅엔(Uettingen)에서 뷔르츠부르크(Würzburg) 지역 출신 형제 두 명이 GmbH로 등록했으며, 이전에 회사가 주장했던 2021년 비공식 창업 시점은 독립적으로 검증되지 않았습니다 — 등기부상 확인된 확실한 날짜는 2023년 등록일뿐입니다. 독일 시장은 우에팅엔의 실제 쇼룸을 통해 확인되었으나, 오스트리아 관련 주장은 이번 조사에서 독립적으로 확인되지 않았습니다.',
    sections: {
      snapshot: { title: 'balkonstrom.com: 기업 스냅샷', image: '/images/balkonstrom-balcony-solar-snapshot-en.svg', imageCaption: '독일 바이에른주 우에팅엔(Uettingen) 소재; GmbH는 2023년 8월에 등록되었으며, 뷔르츠부르크(Würzburg) 지역 출신 형제 두 명이 설립했습니다.' },
      timeline: { title: '연혁', image: '/images/balkonstrom-balcony-solar-timeline-en.svg', imageCaption: 'GmbH 등록일만이 등기부상 확인된 확실한 날짜이며, 그 이전의 비공식 창업 시점(2021년)이라는 주장은 검증되지 않았습니다.' },
      lineup: { title: '키트 라인업(출력)', image: '/images/balkonstrom-balcony-solar-lineup-en.svg', imageCaption: '공식적으로 명시된 번들별 시스템 출력이며, 지정된 배터리 하드웨어와 함께 제공됩니다.' },
      markets: { title: '확인된 시장', image: '/images/balkonstrom-balcony-solar-markets-en.svg', imageCaption: '우에팅엔의 실제 쇼룸을 통해 독일 시장이 확인되었습니다. 오스트리아는 주장되었으나 이번 조사에서 독립적으로 확인되지 않았습니다.' },
      position: { title: 'balkonstrom.com의 시장 위치', image: '/images/balkonstrom-balcony-solar-position-en.svg', imageCaption: 'TÜV 인증 패널과 제3자 저장 장치를 조달하며, 지정된 공급업체에 "Made in Germany" 맞춤형 DC 케이블 제작을 의뢰합니다.' },
      partners: { title: '확인된 부품 공급업체', image: '/images/balkonstrom-balcony-solar-partners-en.svg', imageCaption: 'balkonstrom.com 자체 제품 페이지에 직접 명시되어 있습니다.' },
    },
  },
}
