// Slug: best-balcony-solar-kits-2026
// BSOL-02 — Tier 1 buyer's guide, semi_annual, ★ MONEY, primary affiliate page, spot-check candidate. US-first.
import type { Language } from "@/lib/blog/blogContent";
import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    freshness_tier: 'semi_annual',
    next_refresh_due: '2027-01-02',
    last_full_refresh: '2026-07-02',
    current_hardware_mentioned: ['APsystems EZ1-LV-NA', 'APsystems EZ1', 'EcoFlow STREAM Ultra', 'BigBlue POWAFREE H1'],
    theme: 'Balcony Solar Money Pages',
    title: 'Best Balcony Solar Kits (2026): Complete Plug-In Solar Systems Compared',
    seoTitle: 'Best Balcony Solar Kits 2026: Tested & Compared',
    intro: 'A complete balcony solar kit bundles the panel(s) and micro-inverter so you don\'t have to source components separately. State-by-state legality currently limits which kits actually ship where in the US — availability, not just price, is the first filter that matters.',
    metaDescription: 'The best balcony solar kits for 2026, compared on price, local-control support, and current US state availability — verified pricing and legal restrictions as of July 2026.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '10 min read',
    educationalLevel: 'Intermediate',
    audience: 'US buyers shopping for a complete balcony solar kit',
    primaryTerm: 'best balcony solar kits',
    targetKeywords: ['best balcony solar kits 2026', 'plug in solar kit', 'apsystems ez1 kit', 'ecoflow stream ultra', 'balcony solar kit with battery'],
    leadAnswerBlock: '**The APsystems EZ1-LV-NA 1080W kit ($869) is the best overall balcony solar kit for most US buyers — the vendor ships it nationally with no purchase restriction, but that\'s separate from whether connecting it is confirmed legal in your specific state, since most US states haven\'t addressed balcony solar either way yet (check the state-by-state guide before buying).** Its EZ1 micro-inverter is also the only one in the category with a native local API. Buyers wanting battery storage face a harder constraint: the strongest storage kit, EcoFlow\'s STREAM Ultra, is currently sold and installable only in Utah under that state\'s specific legislation.',
    quickAnswerTop: {
      en: {
        question: 'What is the best balcony solar kit to buy right now?',
        answer: 'For most US buyers, the APsystems EZ1-LV-NA 1080W kit ($869, ussolarsupplier.com) is the strongest overall pick — nationally shippable, and its EZ1 micro-inverter has the category\'s only native local API. If you want battery storage, EcoFlow\'s STREAM Ultra is the standout hardware but is currently restricted to Utah installation. No sub-$400 kit was verifiably found to include a fully certified micro-inverter — treat very cheap complete kits with caution.',
        bullets: [
          'Best overall: APsystems EZ1-LV-NA 1080W kit — $869, ships nationally with no purchase restriction (separate from whether your state confirms it legal to connect — check first)',
          'Best local-control: APsystems EZ1 micro-inverter — native local API and official-style Home Assistant integration',
          'Best budget: APsystems EZ1 standalone micro-inverter ($325, pair with your own panels) — no verifiably certified sub-$400 complete kit exists',
          'Best with storage: EcoFlow STREAM Ultra — 1.92 kWh (expandable to 11.52 kWh), $1,279, currently Utah-only',
          'No product from any brand has UL 3700 certification yet as of write-time',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'Key Takeaways', anchor: '#key-takeaways' },
      { label: 'How We Chose', anchor: '#how-we-chose' },
      { label: 'Best Overall', anchor: '#best-overall' },
      { label: 'Best No-Cloud / Local-Control Pick', anchor: '#best-local-control' },
      { label: 'Best Budget', anchor: '#best-budget' },
      { label: 'Best With Storage', anchor: '#best-with-storage' },
      { label: 'Comparison Table', anchor: '#comparison-table' },
      { label: 'What to Look For', anchor: '#what-to-look-for' },
      { label: 'China Hardware & Price Note', anchor: '#china-price-note' },
      { label: 'FAQ', anchor: '#faq' },
      { label: 'Related Reading', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'Best overall: APsystems EZ1-LV-NA 1080W kit, $869 — the vendor ships it nationally with no purchase restriction, but that\'s not the same as your state confirming it legal to connect; check the state-by-state guide first.',
          'Best local-control: the APsystems EZ1 micro-inverter is the only one in this category confirmed to ship with a native local API and an official-style Home Assistant integration — verify the local-mode toggle at purchase, since one firmware version (1.1.2_b) reportedly removed it on some units.',
          'Best budget: no sub-$400 complete kit was verifiably found to include a certified micro-inverter — the APsystems EZ1 standalone unit ($325, pair with your own panels) is the more defensible budget route.',
          'Best with storage: EcoFlow STREAM Ultra (1.92 kWh, expandable to 11.52 kWh, $1,279) is the strongest storage-inclusive hardware, but is currently sold and installable only in Utah.',
          'State legality is the first filter, not price — confirm your state allows balcony solar before shopping by price or spec (see the country/state legal guide).',
          'No product from Hoymiles, Deye, EcoFlow, or APsystems has achieved UL 3700 certification yet — the standard launched January 2026 but certification testing is still pending industry-wide.',
        ],
      },
      howWeChose: {
        id: 'how-we-chose',
        title: 'How We Chose',
        content: [
          '**We prioritized current US availability and verifiable pricing over spec-sheet comparisons alone, since a well-specced kit that can\'t legally ship to your state isn\'t actually a usable pick.** Local-control support was weighted heavily given this cluster\'s focus on no-cloud, self-hosted setups — see the [full local-control thesis](/balcony-solar/home-assistant-balcony-solar-no-cloud) for why that matters.',
        ],
      },
      bestOverall: {
        id: 'best-overall',
        title: 'Best Overall: APsystems EZ1-LV-NA 1080W Kit',
        content: [
          '**The APsystems EZ1-LV-NA kit pairs two 540W Talesun bifacial panels with the EZ1-LV micro-inverter for $869 (down from $1,199 MSRP), sold and shipped from a US warehouse.** Because it uses the standalone microinverter route rather than a battery-storage unit, it isn\'t subject to the state-by-state storage restrictions that limit EcoFlow\'s comparable kit — a meaningful practical advantage while state legislation is still catching up across the country.',
        ],
        affiliateLinks: [
          { url: 'https://ussolarsupplier.com/products/1080w-plug-in-solar-kit-with-apsystems-ez1-microinverter-plug-in-home-solar-kit', productName: 'APsystems EZ1-LV-NA 1080W Kit', productCategory: 'Complete balcony solar kit', priceRange: '$869', label: 'Check current price' },
        ],
      },
      bestLocalControl: {
        id: 'best-local-control',
        title: 'Best No-Cloud / Local-Control Pick',
        content: [
          '**The APsystems EZ1 micro-inverter — sold both in the kit above and standalone — is the category\'s only confirmed native local API, with an official-style open-source Home Assistant integration that needs no cloud account.** One caveat worth verifying before you buy: a reported firmware version (1.1.2_b) removed local-API functionality on some units, so confirm the local-mode toggle is present on the unit you receive rather than assuming it from the spec sheet alone.',
          'Hoymiles hardware can also reach a genuinely no-cloud setup, but only via third-party OpenDTU firmware on separate ESP32-based hardware (roughly €55) plus a community Python integration — a real DIY project, not an out-of-box feature. See the [dedicated micro-inverter comparison](/balcony-solar/best-balcony-solar-microinverters) for the full breakdown.',
        ],
      },
      bestBudget: {
        id: 'best-budget',
        title: 'Best Budget',
        content: [
          '**We could not verify any complete kit under $400 that includes a certified micro-inverter — multiple current buying guides explicitly warn that sub-$400 listings "may not include a certified microinverter."** The more defensible budget route is the APsystems EZ1 standalone micro-inverter at $325 (with free lower-48 shipping direct from APsystems), which you pair with your own compatible panels.',
          'EcoFlow also sells a standalone STREAM Microinverter at $369 on sale, but its own product page states it is sold "only... within the state of Utah" under that state\'s specific legislation — not a nationally viable budget pick despite the attractive price.',
        ],
        affiliateLinks: [
          { url: 'https://usa.apsystems.com/product/ez1-microinverter/', productName: 'APsystems EZ1 Micro-Inverter (standalone)', productCategory: 'Micro-inverter', priceRange: '$325', label: 'Check current price' },
        ],
      },
      bestWithStorage: {
        id: 'best-with-storage',
        title: 'Best With Storage',
        content: [
          '**EcoFlow\'s STREAM Ultra is the strongest storage-inclusive balcony solar hardware on the market — 1.92 kWh base capacity (expandable to 11.52 kWh), a built-in grid-tied micro-inverter, 1,200W AC output, and a 10-year warranty on LFP cells rated for 6,000 cycles at 70% capacity retention.** The significant limitation: EcoFlow\'s own product page confirms plug-and-play installation is currently sold and installable only in Utah, reflecting how few US states currently permit permit-free plug-in storage systems.',
          'If you\'re outside Utah, BigBlue\'s POWAFREE H1 (2,560 Wh battery, integrated R800 micro-inverter, roughly IP67-rated) is legal in a wider — though still limited — set of states (Utah, Maryland, Maine, Virginia, and one more as of mid-2026). Its cited $699.99 sale price could not be independently confirmed on a BigBlue-owned page, so treat that figure as unverified pending direct confirmation.',
        ],
        callouts: [
          { type: 'warning', text: 'State legality for storage-inclusive balcony solar kits is currently far more restrictive than for panel-plus-microinverter-only kits. Confirm your state\'s status before buying a storage kit specifically.' },
        ],
        affiliateLinks: [
          { url: 'https://us.ecoflow.com/products/stream-ultra', productName: 'EcoFlow STREAM Ultra', productCategory: 'Balcony solar kit with battery', priceRange: '$1,279', label: 'Check current price' },
        ],
      },
      comparisonTable: {
        id: 'comparison-table',
        title: 'Comparison Table',
        rows: [
          { kit: 'APsystems EZ1-LV-NA 1080W', price: '$869', storage: 'None', control: 'Native local API', availability: 'Ships nationally' },
          { kit: 'APsystems EZ1 (standalone)', price: '$325', storage: 'None', control: 'Native local API', availability: 'Ships nationally' },
          { kit: 'EcoFlow STREAM Ultra', price: '$1,279', storage: '1.92–11.52 kWh', control: 'Cloud app (no verified local API)', availability: 'Utah only' },
          { kit: 'BigBlue POWAFREE H1', price: '~$699.99 (unverified)', storage: '2,560 Wh', control: 'Unverified', availability: '~5 states (UT/MD/ME/VA + 1)' },
        ],
        columns: ['kit', 'price', 'storage', 'control', 'availability'],
        tableFormat: true,
      },
      whatToLookFor: {
        id: 'what-to-look-for',
        title: 'What to Look For',
        content: [
          '**Check state legality first, then certification, then wattage limit and monitoring approach — in that order, since a great kit that can\'t legally ship or connect where you live isn\'t a usable option.** See the [state-by-state legal guide](/balcony-solar/balcony-solar-legal-us-states) before you shop by price alone.',
        ],
        items: [
          'State legality and any state-specific wattage cap — confirm before comparing kits',
          'Certification status (UL 1741/IEEE 1547 today; UL 3700 not yet available from any brand)',
          'Local vs. cloud monitoring, if that matters to you',
          'Whether storage is included, and whether that specific storage hardware is legal in your state',
        ],
      },
      chinaPriceNote: {
        id: 'china-price-note',
        title: 'China Hardware & Price Note',
        content: [
          '**Nearly all balcony solar hardware — panels and micro-inverters alike — is China-manufactured, and a China PV export-tax rebate removal effective April 1, 2026 is pushing module and kit prices up an estimated 10–15% into the second half of 2026.** If you\'re price-sensitive, buying sooner rather than later may matter more for this category than for most consumer electronics, since the underlying component cost trend is upward, not downward, for the foreseeable near term.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Frequently Asked Questions',
        faqs: [
          { q: 'What is the best balcony solar kit overall?', a: 'The APsystems EZ1-LV-NA 1080W kit ($869) is the strongest overall pick for most US buyers — it ships nationally without the state-storage restrictions that limit battery-inclusive kits, and its micro-inverter has native local-control support.' },
          { q: 'Is there a balcony solar kit with battery storage that ships nationwide?', a: 'Not currently verified. EcoFlow\'s STREAM Ultra, the strongest storage-inclusive option, is sold and installable only in Utah per the manufacturer\'s own product page. BigBlue\'s POWAFREE H1 has somewhat wider (but still limited) state availability.' },
          { q: 'Do any balcony solar kits have UL 3700 certification?', a: 'No. As of write-time, no product from any brand has completed UL 3700 certification — the standard launched in January 2026 and certification testing is still pending industry-wide.' },
          { q: 'What is the cheapest reliable balcony solar option?', a: 'The APsystems EZ1 standalone micro-inverter at $325 (paired with your own compatible panels) is the most defensible budget route we could verify — no complete kit under $400 was confirmed to include a certified micro-inverter.' },
          { q: 'Which balcony solar kit works best with Home Assistant?', a: 'Kits built around the APsystems EZ1 micro-inverter, which has a native local API and an official-style open-source Home Assistant integration requiring no cloud account.' },
          { q: 'Why are balcony solar kit prices rising?', a: 'China removed a PV-component export VAT rebate effective April 1, 2026, raising exporter costs and pushing module and kit prices up an estimated 10–15% into the second half of 2026.' },
          { q: 'Can I add a battery to a panel-only kit later?', a: 'This depends on your micro-inverter and battery compatibility — check the specific product\'s expansion options before assuming a panel-only kit can be upgraded with storage later.' },
          { q: 'Are these kits legal in every US state?', a: 'No — legality and wattage limits vary significantly by state. Confirm current status for your state before purchasing; see the state-by-state legal guide linked above.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'Best Balcony Solar Kits (2026): Complete Plug-In Solar Systems Compared',
      description: 'The best balcony solar kits for 2026, compared on price, local-control support, and current US state availability — verified pricing and legal restrictions as of July 2026.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      author: {
        '@type': 'Person',
        name: 'Hans Kuepper',
        sameAs: 'https://www.linkedin.com/in/hanskuepper/',
      },
      url: 'https://www.promptquorum.com/balcony-solar/best-balcony-solar-kits-2026',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: 'US buyers shopping for a complete balcony solar kit' },
      about: ['Balcony solar', 'APsystems EZ1', 'EcoFlow STREAM Ultra', 'Plug-in solar kit', 'UL 3700'],
    },
    itemListSchema: {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      numberOfItems: 4,
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'APsystems EZ1-LV-NA 1080W Kit', description: 'Best overall — $869, ships nationally, native local API.' },
        { '@type': 'ListItem', position: 2, name: 'APsystems EZ1 (standalone)', description: 'Best local-control and budget pick — $325, native local API.' },
        { '@type': 'ListItem', position: 3, name: 'EcoFlow STREAM Ultra', description: 'Best with storage — $1,279, 1.92–11.52 kWh, Utah-only currently.' },
        { '@type': 'ListItem', position: 4, name: 'BigBlue POWAFREE H1', description: 'Alternative storage pick with wider (but still limited) state availability.' },
      ],
    },
  },
  es: {
    theme: 'Balcony Solar Money Pages',
    title: 'Los Mejores Kits Solares de Balcón (2026): Sistemas Solares Enchufables Completos Comparados',
    seoTitle: 'Mejores Kits Solares de Balcón 2026: Comparativa',
    intro: 'Un kit solar de balcón completo incluye el panel (o paneles) y el microinversor, así que no tienes que buscar los componentes por separado. En Estados Unidos, la legalidad varía según el estado y actualmente limita qué kits realmente se pueden enviar a cada lugar — la disponibilidad, no solo el precio, es el primer filtro que importa.',
    metaDescription: 'Los mejores kits solares de balcón para 2026 en EE. UU., comparados por precio, soporte de control local y disponibilidad actual por estado — precios y restricciones legales verificados a julio de 2026.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '10 min de lectura',
    educationalLevel: 'Intermediate',
    audience: 'Compradores en EE. UU. que buscan un kit solar de balcón completo',
    primaryTerm: 'best balcony solar kits',
    targetKeywords: ['mejores kits solares de balcón 2026', 'kit solar enchufable', 'kit apsystems ez1', 'ecoflow stream ultra', 'kit solar de balcón con batería'],
    leadAnswerBlock: '**El kit APsystems EZ1-LV-NA de 1080W ($869) es el mejor kit solar de balcón en general para la mayoría de los compradores en EE. UU. — el fabricante lo envía a nivel nacional sin restricción de compra, pero eso es distinto de si conectarlo está confirmado como legal en tu estado específico, ya que la mayoría de los estados de EE. UU. todavía no se han pronunciado al respecto (consulta la guía estado por estado antes de comprar).** Su microinversor EZ1 también es el único de la categoría con una API local nativa. Los compradores que quieren almacenamiento con batería enfrentan una limitación mayor: el kit de almacenamiento más potente, el STREAM Ultra de EcoFlow, actualmente solo se vende e instala en Utah bajo la legislación específica de ese estado.',
    quickAnswerTop: {
      es: {
        question: '¿Cuál es el mejor kit solar de balcón para comprar ahora mismo?',
        answer: 'Para la mayoría de los compradores en EE. UU., el kit APsystems EZ1-LV-NA de 1080W ($869, ussolarsupplier.com) es la mejor opción en general — se envía a nivel nacional, y su microinversor EZ1 tiene la única API local nativa de la categoría. Si quieres almacenamiento con batería, el STREAM Ultra de EcoFlow es el hardware más destacado, pero actualmente está restringido a instalación en Utah. No se encontró de forma verificable ningún kit completo por debajo de $400 que incluya un microinversor totalmente certificado — trata con precaución los kits completos muy económicos.',
        bullets: [
          'Mejor en general: kit APsystems EZ1-LV-NA de 1080W — $869, se envía a nivel nacional sin restricción de compra (distinto de si tu estado confirma que es legal conectarlo — verifica primero)',
          'Mejor control local: microinversor APsystems EZ1 — API local nativa e integración con Home Assistant de estilo oficial',
          'Mejor opción económica: microinversor independiente APsystems EZ1 ($325, se combina con tus propios paneles) — no existe ningún kit completo por debajo de $400 verificablemente certificado',
          'Mejor con almacenamiento: EcoFlow STREAM Ultra — 1.92 kWh (ampliable a 11.52 kWh), $1,279, actualmente solo en Utah',
          'Ningún producto de ninguna marca tiene certificación UL 3700 todavía, hasta el momento de escribir esto',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'Puntos clave', anchor: '#key-takeaways' },
      { label: 'Cómo Elegimos', anchor: '#how-we-chose' },
      { label: 'El Mejor en General', anchor: '#best-overall' },
      { label: 'Mejor Opción Sin Nube / Control Local', anchor: '#best-local-control' },
      { label: 'Mejor Opción Económica', anchor: '#best-budget' },
      { label: 'Mejor Opción Con Almacenamiento', anchor: '#best-with-storage' },
      { label: 'Tabla Comparativa', anchor: '#comparison-table' },
      { label: 'Qué Buscar', anchor: '#what-to-look-for' },
      { label: 'Nota Sobre Hardware y Precios de China', anchor: '#china-price-note' },
      { label: 'Preguntas Frecuentes', anchor: '#faq' },
      { label: 'Lecturas Relacionadas', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'Mejor en general: el kit APsystems EZ1-LV-NA de 1080W, $869 — el fabricante lo envía a nivel nacional sin restricción de compra, pero eso no es lo mismo que tu estado confirme que es legal conectarlo; consulta primero la guía estado por estado.',
          'Mejor control local: el microinversor APsystems EZ1 es el único de esta categoría confirmado que incluye una API local nativa y una integración con Home Assistant de estilo oficial — verifica el interruptor de modo local al comprar, ya que una versión de firmware (1.1.2_b) reportadamente lo eliminó en algunas unidades.',
          'Mejor opción económica: no se encontró de forma verificable ningún kit completo por debajo de $400 que incluya un microinversor certificado — el microinversor independiente APsystems EZ1 ($325, se combina con tus propios paneles) es la opción económica más defendible.',
          'Mejor con almacenamiento: el EcoFlow STREAM Ultra (1.92 kWh, ampliable a 11.52 kWh, $1,279) es el hardware con almacenamiento incluido más potente, pero actualmente solo se vende e instala en Utah.',
          'La legalidad estatal es el primer filtro, no el precio — confirma que tu estado permite la energía solar de balcón antes de comprar por precio o especificaciones (consulta la guía legal por país/estado).',
          'Ningún producto de Hoymiles, Deye, EcoFlow o APsystems ha logrado la certificación UL 3700 todavía — el estándar se lanzó en enero de 2026, pero las pruebas de certificación siguen pendientes en toda la industria.',
        ],
      },
      howWeChose: {
        id: 'how-we-chose',
        title: 'Cómo Elegimos',
        content: [
          '**Priorizamos la disponibilidad actual en EE. UU. y el precio verificable por encima de las comparaciones basadas solo en hojas de especificaciones, ya que un kit bien especificado que no se puede enviar legalmente a tu estado no es en realidad una opción utilizable.** El soporte de control local tuvo un peso importante dado el enfoque de este grupo de artículos en configuraciones autoalojadas y sin nube — consulta la [tesis completa sobre control local](/es/balcony-solar/home-assistant-balcony-solar-no-cloud) para entender por qué eso importa.',
        ],
      },
      bestOverall: {
        id: 'best-overall',
        title: 'El Mejor en General: Kit APsystems EZ1-LV-NA de 1080W',
        content: [
          '**El kit APsystems EZ1-LV-NA combina dos paneles bifaciales Talesun de 540W con el microinversor EZ1-LV por $869 (rebajado desde $1,199 de PVP), vendido y enviado desde un almacén en EE. UU.** Como usa la ruta del microinversor independiente en lugar de una unidad de almacenamiento con batería, no está sujeto a las restricciones estado por estado sobre almacenamiento que limitan al kit comparable de EcoFlow — una ventaja práctica importante mientras la legislación estatal todavía se pone al día en todo el país.',
        ],
        affiliateLinks: [
          { url: 'https://ussolarsupplier.com/products/1080w-plug-in-solar-kit-with-apsystems-ez1-microinverter-plug-in-home-solar-kit', productName: 'APsystems EZ1-LV-NA 1080W Kit', productCategory: 'Kit solar de balcón completo', priceRange: '$869', label: 'Ver precio actual' },
        ],
      },
      bestLocalControl: {
        id: 'best-local-control',
        title: 'Mejor Opción Sin Nube / Control Local',
        content: [
          '**El microinversor APsystems EZ1 — vendido tanto en el kit anterior como por separado — es la única API local nativa confirmada en esta categoría, con una integración de Home Assistant de código abierto y estilo oficial que no requiere cuenta en la nube.** Una advertencia que vale la pena verificar antes de comprar: una versión de firmware reportada (1.1.2_b) eliminó la funcionalidad de la API local en algunas unidades, así que confirma que el interruptor de modo local está presente en la unidad que recibes en lugar de asumirlo solo por la hoja de especificaciones.',
          'El hardware de Hoymiles también puede lograr una configuración genuinamente sin nube, pero solo mediante el firmware de terceros OpenDTU en hardware separado basado en ESP32 (aproximadamente €55) más una integración comunitaria en Python — un proyecto DIY real, no una función lista para usar. Consulta la [comparativa dedicada de microinversores](/es/balcony-solar/best-balcony-solar-microinverters) para el desglose completo.',
        ],
      },
      bestBudget: {
        id: 'best-budget',
        title: 'Mejor Opción Económica',
        content: [
          '**No pudimos verificar ningún kit completo por debajo de $400 que incluya un microinversor certificado — varias guías de compra actuales advierten explícitamente que los anuncios por debajo de $400 "pueden no incluir un microinversor certificado".** La ruta económica más defendible es el microinversor independiente APsystems EZ1 a $325 (con envío gratuito a los 48 estados continentales directamente desde APsystems), que se combina con tus propios paneles compatibles.',
          'EcoFlow también vende un microinversor STREAM independiente a $369 en oferta, pero la propia página del producto indica que se vende "solo... dentro del estado de Utah" bajo la legislación específica de ese estado — no es una opción económica viable a nivel nacional a pesar del precio atractivo.',
        ],
        affiliateLinks: [
          { url: 'https://usa.apsystems.com/product/ez1-microinverter/', productName: 'APsystems EZ1 Micro-Inverter (standalone)', productCategory: 'Microinversor', priceRange: '$325', label: 'Ver precio actual' },
        ],
      },
      bestWithStorage: {
        id: 'best-with-storage',
        title: 'Mejor Opción Con Almacenamiento',
        content: [
          '**El STREAM Ultra de EcoFlow es el hardware solar de balcón con almacenamiento incluido más potente del mercado — 1.92 kWh de capacidad base (ampliable a 11.52 kWh), un microinversor conectado a la red incorporado, salida de CA de 1,200W y una garantía de 10 años en celdas LFP con capacidad para 6,000 ciclos manteniendo el 70% de la capacidad.** La limitación importante: la propia página del producto de EcoFlow confirma que la instalación plug-and-play actualmente solo se vende e instala en Utah, lo que refleja cuán pocos estados de EE. UU. permiten actualmente sistemas de almacenamiento enchufables sin permiso.',
          'Si estás fuera de Utah, el POWAFREE H1 de BigBlue (batería de 2,560 Wh, microinversor R800 integrado, con clasificación aproximada IP67) es legal en un conjunto más amplio — aunque todavía limitado — de estados (Utah, Maryland, Maine, Virginia y uno más a mediados de 2026). Su precio de oferta citado de $699.99 no se pudo confirmar de forma independiente en una página propiedad de BigBlue, así que trata esa cifra como no verificada hasta que se confirme directamente.',
        ],
        callouts: [
          { type: 'warning', text: 'La legalidad estatal para los kits solares de balcón con almacenamiento incluido es actualmente mucho más restrictiva que para los kits que solo incluyen panel más microinversor. Confirma el estado de tu jurisdicción antes de comprar específicamente un kit con almacenamiento.' },
        ],
        affiliateLinks: [
          { url: 'https://us.ecoflow.com/products/stream-ultra', productName: 'EcoFlow STREAM Ultra', productCategory: 'Kit solar de balcón con batería', priceRange: '$1,279', label: 'Ver precio actual' },
        ],
      },
      comparisonTable: {
        id: 'comparison-table',
        title: 'Tabla Comparativa',
        rows: [
          { Kit: 'APsystems EZ1-LV-NA 1080W', Precio: '$869', Almacenamiento: 'Ninguno', Control: 'API local nativa', Disponibilidad: 'Envío a nivel nacional' },
          { Kit: 'APsystems EZ1 (independiente)', Precio: '$325', Almacenamiento: 'Ninguno', Control: 'API local nativa', Disponibilidad: 'Envío a nivel nacional' },
          { Kit: 'EcoFlow STREAM Ultra', Precio: '$1,279', Almacenamiento: '1.92–11.52 kWh', Control: 'App en la nube (sin API local verificada)', Disponibilidad: 'Solo Utah' },
          { Kit: 'BigBlue POWAFREE H1', Precio: '~$699.99 (no verificado)', Almacenamiento: '2,560 Wh', Control: 'No verificado', Disponibilidad: '~5 estados (UT/MD/ME/VA + 1)' },
        ],
        columns: ['Kit', 'Precio', 'Almacenamiento', 'Control', 'Disponibilidad'],
        tableFormat: true,
      },
      whatToLookFor: {
        id: 'what-to-look-for',
        title: 'Qué Buscar',
        content: [
          '**Primero verifica la legalidad estatal, luego la certificación, y después el límite de vataje y el enfoque de monitoreo — en ese orden, ya que un excelente kit que no se puede enviar o conectar legalmente donde vives no es una opción utilizable.** Consulta la [guía legal estado por estado](/es/balcony-solar/balcony-solar-legal-us-states) antes de comprar solo por precio.',
        ],
        items: [
          'Legalidad estatal y cualquier límite de vataje específico del estado — confirma antes de comparar kits',
          'Estado de certificación (hoy UL 1741/IEEE 1547; UL 3700 todavía no está disponible de ninguna marca)',
          'Monitoreo local frente a monitoreo en la nube, si eso te importa',
          'Si el almacenamiento está incluido, y si ese hardware de almacenamiento específico es legal en tu estado',
        ],
      },
      chinaPriceNote: {
        id: 'china-price-note',
        title: 'Nota Sobre Hardware y Precios de China',
        content: [
          '**Casi todo el hardware solar de balcón — tanto paneles como microinversores — se fabrica en China, y la eliminación de un reembolso de impuesto de exportación fotovoltaica de China vigente desde el 1 de abril de 2026 está elevando los precios de módulos y kits en un estimado 10–15% hacia la segunda mitad de 2026.** Si eres sensible al precio, comprar antes que después podría importar más en esta categoría que en la mayoría de la electrónica de consumo, ya que la tendencia de costos de los componentes subyacentes es al alza, no a la baja, en el futuro cercano previsible.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Preguntas Frecuentes',
        faqs: [
          { q: '¿Cuál es el mejor kit solar de balcón en general?', a: 'El kit APsystems EZ1-LV-NA de 1080W ($869) es la mejor opción en general para la mayoría de los compradores en EE. UU. — se envía a nivel nacional sin las restricciones estatales de almacenamiento que limitan a los kits con batería incluida, y su microinversor tiene soporte de control local nativo.' },
          { q: '¿Existe un kit solar de balcón con almacenamiento de batería que se envíe a todo el país?', a: 'Actualmente no está verificado. El STREAM Ultra de EcoFlow, la opción con almacenamiento más potente, solo se vende e instala en Utah según la propia página del producto del fabricante. El POWAFREE H1 de BigBlue tiene una disponibilidad estatal algo más amplia (pero todavía limitada).' },
          { q: '¿Algún kit solar de balcón tiene certificación UL 3700?', a: 'No. Hasta el momento de escribir esto, ningún producto de ninguna marca ha completado la certificación UL 3700 — el estándar se lanzó en enero de 2026 y las pruebas de certificación siguen pendientes en toda la industria.' },
          { q: '¿Cuál es la opción solar de balcón confiable más económica?', a: 'El microinversor independiente APsystems EZ1 a $325 (combinado con tus propios paneles compatibles) es la ruta económica más defendible que pudimos verificar — ningún kit completo por debajo de $400 se confirmó que incluyera un microinversor certificado.' },
          { q: '¿Qué kit solar de balcón funciona mejor con Home Assistant?', a: 'Los kits construidos alrededor del microinversor APsystems EZ1, que tiene una API local nativa y una integración de Home Assistant de código abierto y estilo oficial que no requiere cuenta en la nube.' },
          { q: '¿Por qué están subiendo los precios de los kits solares de balcón?', a: 'China eliminó un reembolso del IVA de exportación de componentes fotovoltaicos vigente desde el 1 de abril de 2026, lo que aumenta los costos de los exportadores y eleva los precios de módulos y kits en un estimado 10–15% hacia la segunda mitad de 2026.' },
          { q: '¿Puedo añadir una batería a un kit de solo paneles más adelante?', a: 'Esto depende de la compatibilidad de tu microinversor y batería — verifica las opciones de expansión del producto específico antes de asumir que un kit de solo paneles se puede actualizar con almacenamiento más adelante.' },
          { q: '¿Son legales estos kits en todos los estados de EE. UU.?', a: 'No — la legalidad y los límites de vataje varían significativamente según el estado. Confirma el estado actual para tu estado antes de comprar; consulta la guía legal estado por estado enlazada arriba.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'Los Mejores Kits Solares de Balcón (2026): Sistemas Solares Enchufables Completos Comparados',
      description: 'Los mejores kits solares de balcón para 2026 en EE. UU., comparados por precio, soporte de control local y disponibilidad actual por estado — precios y restricciones legales verificados a julio de 2026.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      author: {
        '@type': 'Person',
        name: 'Hans Kuepper',
        sameAs: 'https://www.linkedin.com/in/hanskuepper/',
      },
      url: 'https://www.promptquorum.com/es/balcony-solar/best-balcony-solar-kits-2026',
      inLanguage: 'es',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: 'Compradores en EE. UU. que buscan un kit solar de balcón completo' },
      about: [
        { '@type': 'Thing', name: 'Energía solar de balcón' },
        { '@type': 'Thing', name: 'APsystems EZ1' },
        { '@type': 'Thing', name: 'EcoFlow STREAM Ultra' },
        { '@type': 'Thing', name: 'Kit solar enchufable' },
        { '@type': 'Thing', name: 'UL 3700' },
      ],
    },
    itemListSchema: {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      numberOfItems: 4,
      inLanguage: 'es',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'APsystems EZ1-LV-NA 1080W Kit', description: 'El mejor en general — $869, envío a nivel nacional, API local nativa.' },
        { '@type': 'ListItem', position: 2, name: 'APsystems EZ1 (standalone)', description: 'Mejor control local y opción económica — $325, API local nativa.' },
        { '@type': 'ListItem', position: 3, name: 'EcoFlow STREAM Ultra', description: 'Mejor con almacenamiento — $1,279, 1.92–11.52 kWh, actualmente solo Utah.' },
        { '@type': 'ListItem', position: 4, name: 'BigBlue POWAFREE H1', description: 'Opción alternativa de almacenamiento con disponibilidad estatal más amplia (pero todavía limitada).' },
      ],
    },
  },
  pt: {
    theme: 'Balcony Solar Money Pages',
    title: 'Os Melhores Kits de Energia Solar para Varanda (2026): Sistemas Solares Plug-and-Play Completos Comparados',
    seoTitle: 'Melhores Kits de Energia Solar para Varanda 2026',
    intro: 'Um kit de energia solar para varanda completo já vem com o(s) painel(is) e o microinversor, então você não precisa buscar os componentes separadamente. A legalidade varia por estado nos EUA e atualmente limita quais kits realmente podem ser enviados para cada lugar — a disponibilidade, não só o preço, é o primeiro filtro que importa.',
    metaDescription: 'Os melhores kits de energia solar para varanda em 2026 nos EUA, comparados por preço, suporte a controle local e disponibilidade atual por estado — preços e restrições legais verificados em julho de 2026.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '10 min de leitura',
    educationalLevel: 'Intermediate',
    audience: 'Compradores nos EUA em busca de um kit de energia solar para varanda completo',
    primaryTerm: 'best balcony solar kits',
    targetKeywords: ['melhores kits de energia solar para varanda 2026', 'kit solar plug-and-play', 'kit apsystems ez1', 'ecoflow stream ultra', 'kit solar de varanda com bateria'],
    leadAnswerBlock: '**O kit APsystems EZ1-LV-NA de 1080W ($869) é o melhor kit de energia solar para varanda em geral para a maioria dos compradores nos EUA — o fabricante o envia nacionalmente sem restrição de compra, mas isso é diferente de conectá-lo ser confirmadamente legal no seu estado específico, já que a maioria dos estados americanos ainda não se posicionou sobre energia solar de varanda (confira o guia estado por estado antes de comprar).** Seu microinversor EZ1 também é o único da categoria com API local nativa. Compradores que querem armazenamento em bateria enfrentam uma restrição maior: o kit de armazenamento mais forte, o STREAM Ultra da EcoFlow, atualmente só é vendido e instalável em Utah, sob a legislação específica daquele estado.',
    quickAnswerTop: {
      pt: {
        question: 'Qual é o melhor kit de energia solar para varanda para comprar agora?',
        answer: 'Para a maioria dos compradores nos EUA, o kit APsystems EZ1-LV-NA de 1080W ($869, ussolarsupplier.com) é a escolha mais forte em geral — é enviado nacionalmente, e seu microinversor EZ1 tem a única API local nativa da categoria. Se você quer armazenamento com bateria, o STREAM Ultra da EcoFlow é o destaque em hardware, mas atualmente é restrito à instalação em Utah. Nenhum kit completo abaixo de $400 foi comprovadamente encontrado com microinversor totalmente certificado — tenha cautela com kits completos muito baratos.',
        bullets: [
          'Melhor opção geral: kit APsystems EZ1-LV-NA de 1080W — $869, enviado nacionalmente sem restrição de compra (diferente de seu estado confirmar que é legal conectá-lo — confira antes)',
          'Melhor controle local: microinversor APsystems EZ1 — API local nativa e integração com o Home Assistant em estilo oficial',
          'Melhor opção econômica: microinversor avulso APsystems EZ1 ($325, combinado com seus próprios painéis) — nenhum kit completo abaixo de $400 comprovadamente certificado existe',
          'Melhor com armazenamento: EcoFlow STREAM Ultra — 1.92 kWh (expansível a 11.52 kWh), $1,279, atualmente só em Utah',
          'Nenhum produto de nenhuma marca tem certificação UL 3700 ainda, até o momento desta publicação',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'Pontos principais', anchor: '#key-takeaways' },
      { label: 'Como Escolhemos', anchor: '#how-we-chose' },
      { label: 'Melhor Opção Geral', anchor: '#best-overall' },
      { label: 'Melhor Opção Sem Nuvem / Controle Local', anchor: '#best-local-control' },
      { label: 'Melhor Opção Econômica', anchor: '#best-budget' },
      { label: 'Melhor Opção Com Armazenamento', anchor: '#best-with-storage' },
      { label: 'Tabela Comparativa', anchor: '#comparison-table' },
      { label: 'O Que Observar', anchor: '#what-to-look-for' },
      { label: 'Nota Sobre Hardware e Preços da China', anchor: '#china-price-note' },
      { label: 'Perguntas Frequentes', anchor: '#faq' },
      { label: 'Leituras Relacionadas', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'Melhor opção geral: o kit APsystems EZ1-LV-NA de 1080W, $869 — o fabricante o envia nacionalmente sem restrição de compra, mas isso não é o mesmo que seu estado confirmar que é legal conectá-lo; confira primeiro o guia estado por estado.',
          'Melhor controle local: o microinversor APsystems EZ1 é o único desta categoria confirmado com API local nativa e integração com o Home Assistant em estilo oficial — verifique a opção de modo local na compra, já que uma versão de firmware (1.1.2_b) supostamente a removeu em algumas unidades.',
          'Melhor opção econômica: nenhum kit completo abaixo de $400 foi comprovadamente encontrado com microinversor certificado — o microinversor avulso APsystems EZ1 ($325, combinado com seus próprios painéis) é a rota econômica mais defensável.',
          'Melhor com armazenamento: o EcoFlow STREAM Ultra (1.92 kWh, expansível a 11.52 kWh, $1,279) é o hardware com armazenamento incluído mais forte, mas atualmente só é vendido e instalável em Utah.',
          'A legalidade estadual é o primeiro filtro, não o preço — confirme se seu estado permite energia solar de varanda antes de comprar por preço ou especificações (veja o guia legal por país/estado).',
          'Nenhum produto da Hoymiles, Deye, EcoFlow ou APsystems obteve certificação UL 3700 ainda — o padrão foi lançado em janeiro de 2026, mas os testes de certificação ainda estão pendentes em toda a indústria.',
        ],
      },
      howWeChose: {
        id: 'how-we-chose',
        title: 'Como Escolhemos',
        content: [
          '**Priorizamos a disponibilidade atual nos EUA e o preço verificável em vez de comparações baseadas apenas em fichas técnicas, já que um kit bem especificado que não pode ser enviado legalmente para o seu estado não é, na prática, uma opção utilizável.** O suporte a controle local recebeu peso alto, dado o foco deste grupo de artigos em configurações sem nuvem e autogerenciadas — veja a [tese completa sobre controle local](/pt/balcony-solar/home-assistant-balcony-solar-no-cloud) para entender por que isso importa.',
        ],
      },
      bestOverall: {
        id: 'best-overall',
        title: 'Melhor Opção Geral: Kit APsystems EZ1-LV-NA de 1080W',
        content: [
          '**O kit APsystems EZ1-LV-NA combina dois painéis bifaciais Talesun de 540W com o microinversor EZ1-LV por $869 (reduzido de $1.199 de preço sugerido), vendido e enviado a partir de um armazém nos EUA.** Como usa a rota do microinversor avulso em vez de uma unidade de armazenamento em bateria, não está sujeito às restrições estaduais de armazenamento que limitam o kit equivalente da EcoFlow — uma vantagem prática relevante enquanto a legislação estadual ainda está se atualizando pelo país.',
        ],
        affiliateLinks: [
          { url: 'https://ussolarsupplier.com/products/1080w-plug-in-solar-kit-with-apsystems-ez1-microinverter-plug-in-home-solar-kit', productName: 'APsystems EZ1-LV-NA 1080W Kit', productCategory: 'Kit solar de varanda completo', priceRange: '$869', label: 'Ver preço atual' },
        ],
      },
      bestLocalControl: {
        id: 'best-local-control',
        title: 'Melhor Opção Sem Nuvem / Controle Local',
        content: [
          '**O microinversor APsystems EZ1 — vendido tanto no kit acima quanto separadamente — é a única API local nativa confirmada da categoria, com uma integração de código aberto para Home Assistant em estilo oficial que não precisa de conta na nuvem.** Um alerta que vale a pena verificar antes de comprar: uma versão de firmware relatada (1.1.2_b) removeu a funcionalidade da API local em algumas unidades, então confirme se a opção de modo local está presente na unidade que você recebe, em vez de presumir isso só pela ficha técnica.',
          'O hardware da Hoymiles também pode chegar a uma configuração genuinamente sem nuvem, mas só via firmware de terceiros OpenDTU em hardware separado baseado em ESP32 (cerca de €55) mais uma integração comunitária em Python — um projeto DIY de verdade, não um recurso pronto de fábrica. Veja a [comparação dedicada de microinversores](/pt/balcony-solar/best-balcony-solar-microinverters) para o detalhamento completo.',
        ],
      },
      bestBudget: {
        id: 'best-budget',
        title: 'Melhor Opção Econômica',
        content: [
          '**Não conseguimos verificar nenhum kit completo abaixo de $400 que inclua um microinversor certificado — vários guias de compra atuais alertam explicitamente que anúncios abaixo de $400 "podem não incluir um microinversor certificado".** A rota econômica mais defensável é o microinversor avulso APsystems EZ1 por $325 (com frete grátis para os 48 estados contíguos direto da APsystems), que você combina com seus próprios painéis compatíveis.',
          'A EcoFlow também vende um microinversor STREAM avulso por $369 em promoção, mas a própria página do produto informa que ele é vendido "somente... dentro do estado de Utah", sob a legislação específica daquele estado — não é uma opção econômica viável nacionalmente, apesar do preço atrativo.',
        ],
        affiliateLinks: [
          { url: 'https://usa.apsystems.com/product/ez1-microinverter/', productName: 'APsystems EZ1 Micro-Inverter (standalone)', productCategory: 'Microinversor', priceRange: '$325', label: 'Ver preço atual' },
        ],
      },
      bestWithStorage: {
        id: 'best-with-storage',
        title: 'Melhor Opção Com Armazenamento',
        content: [
          '**O STREAM Ultra da EcoFlow é o hardware solar de varanda com armazenamento incluído mais forte do mercado — 1.92 kWh de capacidade base (expansível a 11.52 kWh), microinversor conectado à rede embutido, saída CA de 1.200W e garantia de 10 anos em células LFP com classificação de 6.000 ciclos mantendo 70% da capacidade.** A limitação relevante: a própria página do produto da EcoFlow confirma que a instalação plug-and-play atualmente só é vendida e instalável em Utah, refletindo quão poucos estados americanos hoje permitem sistemas de armazenamento plug-in sem necessidade de licença.',
          'Se você estiver fora de Utah, o POWAFREE H1 da BigBlue (bateria de 2.560 Wh, microinversor R800 integrado, com classificação aproximada IP67) é legal em um conjunto mais amplo — ainda que limitado — de estados (Utah, Maryland, Maine, Virgínia e mais um em meados de 2026). O preço promocional citado de $699.99 não pôde ser confirmado de forma independente em uma página da própria BigBlue, então trate esse valor como não verificado até confirmação direta.',
        ],
        callouts: [
          { type: 'warning', text: 'A legalidade estadual para kits solares de varanda com armazenamento incluído hoje é bem mais restritiva do que para kits apenas com painel e microinversor. Confirme a situação do seu estado antes de comprar especificamente um kit com armazenamento.' },
        ],
        affiliateLinks: [
          { url: 'https://us.ecoflow.com/products/stream-ultra', productName: 'EcoFlow STREAM Ultra', productCategory: 'Kit solar de varanda com bateria', priceRange: '$1,279', label: 'Ver preço atual' },
        ],
      },
      comparisonTable: {
        id: 'comparison-table',
        title: 'Tabela Comparativa',
        rows: [
          { Kit: 'APsystems EZ1-LV-NA 1080W', Preço: '$869', Armazenamento: 'Nenhum', Controle: 'API local nativa', Disponibilidade: 'Envio nacional' },
          { Kit: 'APsystems EZ1 (avulso)', Preço: '$325', Armazenamento: 'Nenhum', Controle: 'API local nativa', Disponibilidade: 'Envio nacional' },
          { Kit: 'EcoFlow STREAM Ultra', Preço: '$1,279', Armazenamento: '1.92–11.52 kWh', Controle: 'App na nuvem (sem API local verificada)', Disponibilidade: 'Somente Utah' },
          { Kit: 'BigBlue POWAFREE H1', Preço: '~$699.99 (não verificado)', Armazenamento: '2,560 Wh', Controle: 'Não verificado', Disponibilidade: '~5 estados (UT/MD/ME/VA + 1)' },
        ],
        columns: ['Kit', 'Preço', 'Armazenamento', 'Controle', 'Disponibilidade'],
        tableFormat: true,
      },
      whatToLookFor: {
        id: 'what-to-look-for',
        title: 'O Que Observar',
        content: [
          '**Verifique primeiro a legalidade estadual, depois a certificação e só então o limite de potência e a forma de monitoramento — nessa ordem, já que um ótimo kit que não pode ser legalmente enviado ou conectado onde você mora não é uma opção utilizável.** Veja o [guia legal estado por estado](/pt/balcony-solar/balcony-solar-legal-us-states) antes de comprar só pelo preço.',
        ],
        items: [
          'Legalidade estadual e qualquer limite de potência específico do estado — confirme antes de comparar kits',
          'Status de certificação (hoje UL 1741/IEEE 1547; UL 3700 ainda não disponível em nenhuma marca)',
          'Monitoramento local versus na nuvem, se isso importa para você',
          'Se o armazenamento está incluído, e se esse hardware de armazenamento específico é legal no seu estado',
        ],
      },
      chinaPriceNote: {
        id: 'china-price-note',
        title: 'Nota Sobre Hardware e Preços da China',
        content: [
          '**Praticamente todo o hardware solar de varanda — painéis e microinversores — é fabricado na China, e a remoção de um reembolso de imposto de exportação fotovoltaica chinês, em vigor desde 1º de abril de 2026, está elevando os preços de módulos e kits em uma estimativa de 10–15% ao longo do segundo semestre de 2026.** Se você é sensível a preço, comprar mais cedo do que mais tarde pode importar mais nessa categoria do que na maioria dos eletrônicos de consumo, já que a tendência de custo dos componentes subjacentes é de alta, não de queda, no curto prazo previsível.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Perguntas Frequentes',
        faqs: [
          { q: 'Qual é o melhor kit de energia solar para varanda em geral?', a: 'O kit APsystems EZ1-LV-NA de 1080W ($869) é a melhor opção geral para a maioria dos compradores nos EUA — é enviado nacionalmente sem as restrições estaduais de armazenamento que limitam kits com bateria incluída, e seu microinversor tem suporte nativo a controle local.' },
          { q: 'Existe um kit de energia solar para varanda com armazenamento em bateria que seja enviado para todo o país?', a: 'Atualmente não confirmado. O STREAM Ultra da EcoFlow, a opção com armazenamento mais forte, só é vendido e instalável em Utah, segundo a própria página do produto do fabricante. O POWAFREE H1 da BigBlue tem disponibilidade estadual um pouco maior (mas ainda limitada).' },
          { q: 'Algum kit de energia solar para varanda tem certificação UL 3700?', a: 'Não. Até o momento desta publicação, nenhum produto de nenhuma marca concluiu a certificação UL 3700 — o padrão foi lançado em janeiro de 2026 e os testes de certificação ainda estão pendentes em toda a indústria.' },
          { q: 'Qual é a opção solar de varanda confiável mais barata?', a: 'O microinversor avulso APsystems EZ1 por $325 (combinado com seus próprios painéis compatíveis) é a rota econômica mais defensável que conseguimos verificar — nenhum kit completo abaixo de $400 foi confirmado com microinversor certificado.' },
          { q: 'Qual kit de energia solar para varanda funciona melhor com o Home Assistant?', a: 'Kits construídos em torno do microinversor APsystems EZ1, que tem API local nativa e uma integração de código aberto para Home Assistant em estilo oficial que não exige conta na nuvem.' },
          { q: 'Por que os preços dos kits de energia solar para varanda estão subindo?', a: 'A China removeu um reembolso de imposto de exportação de componentes fotovoltaicos em vigor desde 1º de abril de 2026, elevando os custos dos exportadores e os preços de módulos e kits em uma estimativa de 10–15% ao longo do segundo semestre de 2026.' },
          { q: 'Posso adicionar uma bateria a um kit apenas com painel depois?', a: 'Isso depende da compatibilidade do seu microinversor e da bateria — verifique as opções de expansão do produto específico antes de presumir que um kit apenas com painel pode ser atualizado com armazenamento depois.' },
          { q: 'Esses kits são legais em todos os estados dos EUA?', a: 'Não — a legalidade e os limites de potência variam bastante por estado. Confirme a situação atual do seu estado antes de comprar; veja o guia legal estado por estado linkado acima.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'Os Melhores Kits de Energia Solar para Varanda (2026): Sistemas Solares Plug-and-Play Completos Comparados',
      description: 'Os melhores kits de energia solar para varanda em 2026 nos EUA, comparados por preço, suporte a controle local e disponibilidade atual por estado — preços e restrições legais verificados em julho de 2026.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      author: {
        '@type': 'Person',
        name: 'Hans Kuepper',
        sameAs: 'https://www.linkedin.com/in/hanskuepper/',
      },
      url: 'https://www.promptquorum.com/pt/balcony-solar/best-balcony-solar-kits-2026',
      inLanguage: 'pt-BR',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: 'Compradores nos EUA em busca de um kit de energia solar para varanda completo' },
      about: [
        { '@type': 'Thing', name: 'Energia solar de varanda' },
        { '@type': 'Thing', name: 'APsystems EZ1' },
        { '@type': 'Thing', name: 'EcoFlow STREAM Ultra' },
        { '@type': 'Thing', name: 'Kit solar plug-and-play' },
        { '@type': 'Thing', name: 'UL 3700' },
      ],
    },
    itemListSchema: {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      numberOfItems: 4,
      inLanguage: 'pt-BR',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'APsystems EZ1-LV-NA 1080W Kit', description: 'Melhor opção geral — $869, envio nacional, API local nativa.' },
        { '@type': 'ListItem', position: 2, name: 'APsystems EZ1 (standalone)', description: 'Melhor controle local e opção econômica — $325, API local nativa.' },
        { '@type': 'ListItem', position: 3, name: 'EcoFlow STREAM Ultra', description: 'Melhor com armazenamento — $1,279, 1.92–11.52 kWh, atualmente somente Utah.' },
        { '@type': 'ListItem', position: 4, name: 'BigBlue POWAFREE H1', description: 'Opção alternativa de armazenamento com disponibilidade estadual mais ampla (mas ainda limitada).' },
      ],
    },
  },
  ar: {
    theme: 'Balcony Solar Money Pages',
    title: 'أفضل أطقم الطاقة الشمسية للشرفة (2026): مقارنة كاملة لأنظمة الطاقة الشمسية الجاهزة للتوصيل',
    seoTitle: 'أفضل أطقم الطاقة الشمسية للشرفة 2026 في أمريكا',
    intro: 'يجمع طقم الطاقة الشمسية الكامل للشرفة بين اللوح (أو الألواح) والعاكس الصغير (microinverter) بحيث لا تحتاج إلى شراء المكونات بشكل منفصل. تختلف القوانين حاليًا من ولاية إلى أخرى في الولايات المتحدة، وهذا يحدّ من الأطقم التي يمكن شحنها فعليًا إلى كل مكان — التوفر، وليس السعر فقط، هو أول معيار مهم.',
    metaDescription: 'أفضل أطقم الطاقة الشمسية للشرفة لعام 2026 في الولايات المتحدة، مقارنة من حيث السعر ودعم التحكم المحلي والتوفر الحالي حسب الولاية — الأسعار والقيود القانونية مُتحقق منها حتى يوليو 2026.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '10 دقائق للقراءة',
    educationalLevel: 'Intermediate',
    audience: 'مشترون في الولايات المتحدة يبحثون عن طقم طاقة شمسية كامل للشرفة',
    primaryTerm: 'best balcony solar kits',
    targetKeywords: ['أفضل أطقم الطاقة الشمسية للشرفة 2026', 'طقم طاقة شمسية جاهز للتوصيل', 'طقم APsystems EZ1', 'EcoFlow STREAM Ultra', 'طقم طاقة شمسية للشرفة مع بطارية'],
    leadAnswerBlock: '**طقم APsystems EZ1-LV-NA بقدرة 1080W (بسعر $869) هو أفضل طقم طاقة شمسية للشرفة بشكل عام لمعظم المشترين في الولايات المتحدة — يقوم البائع بشحنه على مستوى البلاد دون قيود على الشراء، لكن هذا يختلف عن كون توصيله مؤكَّدًا قانونيًا في ولايتك تحديدًا، إذ إن معظم الولايات الأمريكية لم تُصدر بعد موقفًا واضحًا بشأن الطاقة الشمسية للشرفة (راجع الدليل الخاص بكل ولاية قبل الشراء).** كما أن عاكسه الصغير EZ1 هو الوحيد في هذه الفئة الذي يتوفر بواجهة برمجة تطبيقات (API) محلية أصلية. أما المشترون الراغبون في تخزين الطاقة بالبطارية فيواجهون قيدًا أكبر: أقوى طقم تخزين، وهو STREAM Ultra من EcoFlow، يُباع ويُركَّب حاليًا فقط في ولاية يوتاه بموجب تشريعات تلك الولاية تحديدًا.',
    quickAnswerTop: {
      ar: {
        question: 'ما هو أفضل طقم طاقة شمسية للشرفة يمكن شراؤه الآن؟',
        answer: 'بالنسبة لمعظم المشترين في الولايات المتحدة، يُعد طقم APsystems EZ1-LV-NA بقدرة 1080W ($869 من ussolarsupplier.com) الخيار الأقوى بشكل عام — يُشحن على مستوى البلاد، وعاكسه الصغير EZ1 يتوفر بواجهة برمجة تطبيقات محلية أصلية وهي الوحيدة في هذه الفئة. إذا كنت ترغب في تخزين الطاقة بالبطارية، فإن STREAM Ultra من EcoFlow هو الجهاز الأبرز، لكنه حاليًا مقيَّد بالتركيب في ولاية يوتاه فقط. لم يتم العثور بشكل موثَّق على أي طقم كامل بسعر أقل من $400 يتضمن عاكسًا صغيرًا معتمدًا بالكامل — تعامل بحذر مع الأطقم الكاملة الرخيصة جدًا.',
        bullets: [
          'الأفضل بشكل عام: طقم APsystems EZ1-LV-NA بقدرة 1080W — $869، يُشحن على مستوى البلاد دون قيود على الشراء (يختلف عن تأكيد ولايتك أنه قانوني لتوصيله — تحقق أولًا)',
          'أفضل تحكم محلي: عاكس APsystems EZ1 الصغير — واجهة برمجة تطبيقات محلية أصلية وتكامل شبه رسمي مع Home Assistant',
          'الأفضل من حيث السعر: عاكس APsystems EZ1 المستقل ($325، يُستخدم مع ألواحك الخاصة) — لا يوجد طقم كامل بسعر أقل من $400 معتمد بشكل موثَّق',
          'الأفضل مع التخزين: EcoFlow STREAM Ultra — بسعة 1.92 kWh (قابلة للتوسيع إلى 11.52 kWh)، بسعر $1,279، وحاليًا في يوتاه فقط',
          'لا يوجد أي منتج من أي علامة تجارية يحمل شهادة UL 3700 حتى وقت كتابة هذا المقال',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'النقاط الرئيسية', anchor: '#key-takeaways' },
      { label: 'كيف اخترنا', anchor: '#how-we-chose' },
      { label: 'الأفضل بشكل عام', anchor: '#best-overall' },
      { label: 'أفضل خيار بلا سحابة / بتحكم محلي', anchor: '#best-local-control' },
      { label: 'الأفضل من حيث السعر', anchor: '#best-budget' },
      { label: 'الأفضل مع التخزين', anchor: '#best-with-storage' },
      { label: 'جدول المقارنة', anchor: '#comparison-table' },
      { label: 'ما الذي يجب البحث عنه', anchor: '#what-to-look-for' },
      { label: 'ملاحظة حول أجهزة وأسعار الصين', anchor: '#china-price-note' },
      { label: 'الأسئلة الشائعة', anchor: '#faq' },
      { label: 'قراءات ذات صلة', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'الأفضل بشكل عام: طقم APsystems EZ1-LV-NA بقدرة 1080W بسعر $869 — يقوم البائع بشحنه على مستوى البلاد دون قيود على الشراء، لكن هذا لا يعني أن ولايتك تؤكد أنه قانوني لتوصيله؛ راجع أولًا الدليل الخاص بكل ولاية.',
          'أفضل تحكم محلي: عاكس APsystems EZ1 الصغير هو الوحيد في هذه الفئة المؤكَّد أنه يأتي بواجهة برمجة تطبيقات محلية أصلية وتكامل شبه رسمي مع Home Assistant — تحقق من وجود خيار الوضع المحلي عند الشراء، إذ تشير التقارير إلى أن إصدار البرنامج الثابت (1.1.2_b) أزاله من بعض الوحدات.',
          'الأفضل من حيث السعر: لم نتمكن من التحقق من وجود أي طقم كامل بسعر أقل من $400 يتضمن عاكسًا صغيرًا معتمدًا — عاكس APsystems EZ1 المستقل بسعر $325 (يُستخدم مع ألواحك الخاصة) هو الخيار الاقتصادي الأكثر منطقية.',
          'الأفضل مع التخزين: EcoFlow STREAM Ultra (بسعة 1.92 kWh قابلة للتوسيع إلى 11.52 kWh، وبسعر $1,279) هو أقوى جهاز يتضمن التخزين، لكنه حاليًا يُباع ويُركَّب فقط في ولاية يوتاه.',
          'قانونية الولاية هي المعيار الأول، وليس السعر — تأكد من أن ولايتك تسمح بالطاقة الشمسية للشرفة قبل الشراء بناءً على السعر أو المواصفات (راجع الدليل القانوني حسب الدولة/الولاية).',
          'لم يحصل أي منتج من Hoymiles أو Deye أو EcoFlow أو APsystems على شهادة UL 3700 حتى الآن — أُطلق المعيار في يناير 2026، لكن اختبارات الاعتماد ما زالت معلّقة على مستوى الصناعة بأكملها.',
        ],
      },
      howWeChose: {
        id: 'how-we-chose',
        title: 'كيف اخترنا',
        content: [
          '**أعطينا الأولوية للتوفر الحالي في الولايات المتحدة والسعر القابل للتحقق منه، بدلًا من الاعتماد فقط على مقارنة الأوراق الفنية، لأن الطقم الجيد المواصفات الذي لا يمكن شحنه قانونيًا إلى ولايتك ليس خيارًا عمليًا فعليًا.** حصل دعم التحكم المحلي على وزن كبير نظرًا لتركيز هذه المجموعة من المقالات على الإعدادات المستضافة ذاتيًا وبلا سحابة — راجع [الأطروحة الكاملة حول التحكم المحلي](/ar/balcony-solar/home-assistant-balcony-solar-no-cloud) لمعرفة سبب أهمية ذلك.',
        ],
      },
      bestOverall: {
        id: 'best-overall',
        title: 'الأفضل بشكل عام: طقم APsystems EZ1-LV-NA بقدرة 1080W',
        content: [
          '**يجمع طقم APsystems EZ1-LV-NA بين لوحين ثنائيي الوجه من Talesun بقدرة 540W لكل منهما مع العاكس الصغير EZ1-LV بسعر $869 (بعد خصم من السعر المقترح $1,199)، ويُباع ويُشحن من مستودع في الولايات المتحدة.** ولأنه يعتمد مسار العاكس الصغير المستقل بدلًا من وحدة تخزين بالبطارية، فهو لا يخضع لقيود التخزين المختلفة من ولاية إلى أخرى التي تحدّ من الطقم المماثل من EcoFlow — وهي ميزة عملية مهمة في ظل استمرار التشريعات الولائية في اللحاق بالركب في جميع أنحاء البلاد.',
        ],
        affiliateLinks: [
          { url: 'https://ussolarsupplier.com/products/1080w-plug-in-solar-kit-with-apsystems-ez1-microinverter-plug-in-home-solar-kit', productName: 'APsystems EZ1-LV-NA 1080W Kit', productCategory: 'طقم طاقة شمسية كامل للشرفة', priceRange: '$869', label: 'تحقق من السعر الحالي' },
        ],
      },
      bestLocalControl: {
        id: 'best-local-control',
        title: 'أفضل خيار بلا سحابة / بتحكم محلي',
        content: [
          '**عاكس APsystems EZ1 الصغير — الذي يُباع ضمن الطقم أعلاه وبشكل مستقل أيضًا — هو الوحيد المؤكَّد في هذه الفئة الذي يتوفر بواجهة برمجة تطبيقات محلية أصلية، إلى جانب تكامل مفتوح المصدر شبه رسمي مع Home Assistant لا يتطلب حساب سحابة.** تحذير يستحق التحقق منه قبل الشراء: أشارت التقارير إلى أن إصدارًا للبرنامج الثابت (1.1.2_b) أزال وظيفة واجهة برمجة التطبيقات المحلية من بعض الوحدات، لذا تأكد من وجود خيار الوضع المحلي في الوحدة التي تستلمها بدلًا من افتراض ذلك من ورقة المواصفات فقط.',
          'يمكن لأجهزة Hoymiles أيضًا الوصول إلى إعداد بلا سحابة فعليًا، لكن فقط عبر البرنامج الثابت من طرف ثالث OpenDTU على أجهزة منفصلة تعتمد على ESP32 (بسعر يقارب €55) بالإضافة إلى تكامل مجتمعي بلغة Python — وهو مشروع DIY حقيقي وليس ميزة جاهزة. راجع [مقارنة العاكسات الصغيرة المخصصة](/ar/balcony-solar/best-balcony-solar-microinverters) للاطلاع على التفاصيل الكاملة.',
        ],
      },
      bestBudget: {
        id: 'best-budget',
        title: 'الأفضل من حيث السعر',
        content: [
          '**لم نتمكن من التحقق من وجود أي طقم كامل بسعر أقل من $400 يتضمن عاكسًا صغيرًا معتمدًا — تحذر عدة أدلة شراء حالية صراحةً من أن العروض التي تقل عن $400 "قد لا تتضمن عاكسًا صغيرًا معتمدًا".** الخيار الاقتصادي الأكثر منطقية هو عاكس APsystems EZ1 المستقل بسعر $325 (مع شحن مجاني إلى الولايات الـ48 المتجاورة مباشرة من APsystems)، والذي تستخدمه مع ألواحك المتوافقة الخاصة.',
          'تبيع EcoFlow أيضًا عاكسًا صغيرًا مستقلًا من طراز STREAM بسعر $369 ضمن عرض، لكن صفحة المنتج نفسها تذكر أنه يُباع "فقط... داخل ولاية يوتاه" بموجب تشريعات تلك الولاية تحديدًا — وهو ليس خيارًا اقتصاديًا قابلًا للتطبيق على مستوى البلاد رغم سعره الجذاب.',
        ],
        affiliateLinks: [
          { url: 'https://usa.apsystems.com/product/ez1-microinverter/', productName: 'APsystems EZ1 Micro-Inverter (standalone)', productCategory: 'عاكس صغير (Micro-inverter)', priceRange: '$325', label: 'تحقق من السعر الحالي' },
        ],
      },
      bestWithStorage: {
        id: 'best-with-storage',
        title: 'الأفضل مع التخزين',
        content: [
          '**يُعد STREAM Ultra من EcoFlow أقوى جهاز طاقة شمسية للشرفة يتضمن تخزينًا في السوق — بسعة أساسية 1.92 kWh (قابلة للتوسيع إلى 11.52 kWh)، وعاكس صغير مدمج متصل بالشبكة، وإخراج تيار متردد بقدرة 1,200W، وضمان 10 سنوات على خلايا LFP المصنَّفة لتحمل 6,000 دورة شحن مع الحفاظ على 70% من السعة.** القيد الأهم: تؤكد صفحة منتج EcoFlow نفسها أن التركيب الجاهز للتوصيل (plug-and-play) يُباع ويُركَّب حاليًا فقط في ولاية يوتاه، وهو ما يعكس قلة عدد الولايات الأمريكية التي تسمح حاليًا بأنظمة تخزين قابلة للتوصيل دون تصريح.',
          'إذا كنت خارج يوتاه، فإن POWAFREE H1 من BigBlue (بطارية بسعة 2,560 Wh، وعاكس صغير مدمج طراز R800، وتصنيف يقارب IP67) قانوني في مجموعة أوسع — وإن كانت لا تزال محدودة — من الولايات (يوتاه، ماريلاند، مين، فيرجينيا، وولاية إضافية اعتبارًا من منتصف 2026). لم يتم التحقق بشكل مستقل من سعر العرض المذكور البالغ $699.99 على صفحة تابعة لشركة BigBlue، لذا يجب التعامل مع هذا الرقم كرقم غير مؤكَّد إلى حين التأكيد المباشر.',
        ],
        callouts: [
          { type: 'warning', text: 'قانونية استخدام أطقم الطاقة الشمسية للشرفة التي تتضمن تخزينًا أكثر تقييدًا حاليًا بكثير من أطقم اللوح مع العاكس الصغير فقط. تأكد من وضع ولايتك قبل شراء طقم يتضمن تخزينًا تحديدًا.' },
        ],
        affiliateLinks: [
          { url: 'https://us.ecoflow.com/products/stream-ultra', productName: 'EcoFlow STREAM Ultra', productCategory: 'طقم طاقة شمسية للشرفة مع بطارية', priceRange: '$1,279', label: 'تحقق من السعر الحالي' },
        ],
      },
      comparisonTable: {
        id: 'comparison-table',
        title: 'جدول المقارنة',
        rows: [
          { 'الطقم': 'APsystems EZ1-LV-NA 1080W', 'السعر': '$869', 'التخزين': 'لا يوجد', 'التحكم': 'واجهة برمجة تطبيقات محلية أصلية', 'التوفر': 'شحن على مستوى البلاد' },
          { 'الطقم': 'APsystems EZ1 (مستقل)', 'السعر': '$325', 'التخزين': 'لا يوجد', 'التحكم': 'واجهة برمجة تطبيقات محلية أصلية', 'التوفر': 'شحن على مستوى البلاد' },
          { 'الطقم': 'EcoFlow STREAM Ultra', 'السعر': '$1,279', 'التخزين': '1.92–11.52 kWh', 'التحكم': 'تطبيق سحابي (بدون واجهة برمجة تطبيقات محلية مؤكدة)', 'التوفر': 'يوتاه فقط' },
          { 'الطقم': 'BigBlue POWAFREE H1', 'السعر': '~$699.99 (غير مؤكَّد)', 'التخزين': '2,560 Wh', 'التحكم': 'غير مؤكَّد', 'التوفر': '~5 ولايات (UT/MD/ME/VA + 1)' },
        ],
        columns: ['الطقم', 'السعر', 'التخزين', 'التحكم', 'التوفر'],
        tableFormat: true,
      },
      whatToLookFor: {
        id: 'what-to-look-for',
        title: 'ما الذي يجب البحث عنه',
        content: [
          '**تحقق أولًا من قانونية الولاية، ثم الاعتماد، ثم حد القدرة الكهربائية وطريقة المراقبة — بهذا الترتيب، لأن الطقم الممتاز الذي لا يمكن شحنه أو توصيله قانونيًا حيث تعيش ليس خيارًا عمليًا.** راجع [الدليل القانوني حسب الولاية](/ar/balcony-solar/balcony-solar-legal-us-states) قبل الشراء بناءً على السعر فقط.',
        ],
        items: [
          'قانونية الولاية وأي حد أقصى للقدرة الكهربائية خاص بالولاية — تأكد قبل مقارنة الأطقم',
          'حالة الاعتماد (اليوم UL 1741/IEEE 1547؛ UL 3700 غير متاح بعد من أي علامة تجارية)',
          'المراقبة المحلية مقابل المراقبة السحابية، إن كان ذلك مهمًا لك',
          'ما إذا كان التخزين مشمولًا، وما إذا كان جهاز التخزين هذا تحديدًا قانونيًا في ولايتك',
        ],
      },
      chinaPriceNote: {
        id: 'china-price-note',
        title: 'ملاحظة حول أجهزة وأسعار الصين',
        content: [
          '**يتم تصنيع جميع أجهزة الطاقة الشمسية للشرفة تقريبًا — الألواح والعاكسات الصغيرة على حد سواء — في الصين، وإلغاء استرداد ضريبة تصدير الخلايا الشمسية الصينية اعتبارًا من 1 أبريل 2026 يدفع أسعار الوحدات والأطقم للارتفاع بنسبة تقديرية تتراوح بين 10-15% خلال النصف الثاني من عام 2026.** إذا كنت حساسًا للسعر، فقد يكون الشراء عاجلًا أكثر أهمية في هذه الفئة مقارنة بمعظم الإلكترونيات الاستهلاكية، إذ إن اتجاه تكلفة المكونات الأساسية آخذ في الارتفاع وليس الانخفاض في المستقبل القريب المنظور.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'الأسئلة الشائعة',
        faqs: [
          { q: 'ما هو أفضل طقم طاقة شمسية للشرفة بشكل عام؟', a: 'طقم APsystems EZ1-LV-NA بقدرة 1080W (بسعر $869) هو الخيار الأقوى بشكل عام لمعظم المشترين في الولايات المتحدة — يُشحن على مستوى البلاد دون قيود التخزين الخاصة بالولايات التي تحدّ من الأطقم التي تتضمن بطارية، ويتمتع عاكسه الصغير بدعم تحكم محلي أصلي.' },
          { q: 'هل يوجد طقم طاقة شمسية للشرفة يتضمن تخزينًا بالبطارية ويُشحن على مستوى البلاد؟', a: 'غير مؤكَّد حاليًا. STREAM Ultra من EcoFlow، وهو أقوى خيار يتضمن تخزينًا، يُباع ويُركَّب فقط في ولاية يوتاه بحسب صفحة منتج الشركة المصنّعة نفسها. أما POWAFREE H1 من BigBlue فتوفره أوسع نسبيًا بين الولايات (لكنه لا يزال محدودًا).' },
          { q: 'هل يحمل أي طقم طاقة شمسية للشرفة شهادة UL 3700؟', a: 'لا. حتى وقت كتابة هذا المقال، لم يُكمل أي منتج من أي علامة تجارية اعتماد UL 3700 — أُطلق المعيار في يناير 2026، ولا تزال اختبارات الاعتماد معلّقة على مستوى الصناعة بأكملها.' },
          { q: 'ما هو أرخص خيار موثوق للطاقة الشمسية للشرفة؟', a: 'عاكس APsystems EZ1 الصغير المستقل بسعر $325 (مع ألواحك المتوافقة الخاصة) هو الخيار الاقتصادي الأكثر منطقية الذي تمكّنا من التحقق منه — لم يتم تأكيد أي طقم كامل بسعر أقل من $400 يتضمن عاكسًا صغيرًا معتمدًا.' },
          { q: 'أي طقم طاقة شمسية للشرفة يعمل بشكل أفضل مع Home Assistant؟', a: 'الأطقم المبنية حول عاكس APsystems EZ1 الصغير، الذي يتوفر بواجهة برمجة تطبيقات محلية أصلية وتكامل مفتوح المصدر شبه رسمي مع Home Assistant لا يتطلب حساب سحابة.' },
          { q: 'لماذا ترتفع أسعار أطقم الطاقة الشمسية للشرفة؟', a: 'ألغت الصين استرداد ضريبة القيمة المضافة على تصدير مكونات الخلايا الشمسية اعتبارًا من 1 أبريل 2026، ما يرفع تكاليف المصدّرين ويدفع أسعار الوحدات والأطقم للارتفاع بنسبة تقديرية تتراوح بين 10-15% خلال النصف الثاني من عام 2026.' },
          { q: 'هل يمكنني إضافة بطارية إلى طقم يحتوي على لوح فقط لاحقًا؟', a: 'يعتمد هذا على توافق العاكس الصغير الخاص بك مع البطارية — تحقق من خيارات التوسعة الخاصة بالمنتج قبل افتراض أن طقمًا يحتوي على لوح فقط يمكن ترقيته بإضافة تخزين لاحقًا.' },
          { q: 'هل هذه الأطقم قانونية في جميع الولايات الأمريكية؟', a: 'لا — تختلف القانونية وحدود القدرة الكهربائية بشكل كبير حسب الولاية. تأكد من الوضع الحالي لولايتك قبل الشراء؛ راجع الدليل القانوني حسب الولاية المرتبط أعلاه.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'أفضل أطقم الطاقة الشمسية للشرفة (2026): مقارنة كاملة لأنظمة الطاقة الشمسية الجاهزة للتوصيل',
      description: 'أفضل أطقم الطاقة الشمسية للشرفة لعام 2026 في الولايات المتحدة، مقارنة من حيث السعر ودعم التحكم المحلي والتوفر الحالي حسب الولاية — الأسعار والقيود القانونية مُتحقق منها حتى يوليو 2026.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      author: {
        '@type': 'Organization',
        name: 'PromptQuorum',
      },
      url: 'https://www.promptquorum.com/ar/balcony-solar/best-balcony-solar-kits-2026',
      inLanguage: 'ar',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: 'مشترون في الولايات المتحدة يبحثون عن طقم طاقة شمسية كامل للشرفة' },
      about: [
        { '@type': 'Thing', name: 'الطاقة الشمسية للشرفة' },
        { '@type': 'Thing', name: 'APsystems EZ1' },
        { '@type': 'Thing', name: 'EcoFlow STREAM Ultra' },
        { '@type': 'Thing', name: 'طقم طاقة شمسية جاهز للتوصيل' },
        { '@type': 'Thing', name: 'UL 3700' },
      ],
    },
    itemListSchema: {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      numberOfItems: 4,
      inLanguage: 'ar',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'APsystems EZ1-LV-NA 1080W Kit', description: 'الأفضل بشكل عام — $869، شحن على مستوى البلاد، واجهة برمجة تطبيقات محلية أصلية.' },
        { '@type': 'ListItem', position: 2, name: 'APsystems EZ1 (standalone)', description: 'أفضل تحكم محلي وخيار اقتصادي — $325، واجهة برمجة تطبيقات محلية أصلية.' },
        { '@type': 'ListItem', position: 3, name: 'EcoFlow STREAM Ultra', description: 'الأفضل مع التخزين — $1,279، 1.92–11.52 kWh، حاليًا يوتاه فقط.' },
        { '@type': 'ListItem', position: 4, name: 'BigBlue POWAFREE H1', description: 'خيار تخزين بديل بتوفر أوسع بين الولايات (لكنه لا يزال محدودًا).' },
      ],
    },
  },
};
