// Slug: ecoflow-balcony-solar
// Phase 1 scaffold (2026-07-19) — structure/frontmatter only, no body content yet.
// Noindex + sitemap-excluded via PENDING_SLUGS in published.ts until content,
// translation, and internal-linking phases land (see TIER 6 in slugs.ts).
import type { Language } from "@/lib/blog/blogContent";
import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    freshness_tier: 'semi_annual',
    next_refresh_due: '2027-01-19',
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow: Balcony Solar Company Profile',
    seoTitle: 'EcoFlow Balcony Solar Company Profile',
    metaDescription: 'Company profile for EcoFlow: history, ownership, product range, and role in the balcony solar market.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Readers researching EcoFlow as a company, distinct from buying-comparison intent',
    // TODO (internal-linking phase): reciprocal link to ecoflow-vs-anker-vs-zendure-balcony-solar (buyer-intent comparison); this page stays research-intent and must not duplicate that page's buying-decision framing.
    sections: {
      snapshot: { title: 'EcoFlow: Company Snapshot', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: 'Founded 2017 in Shenzhen by four co-founders; privately held, reportedly weighing a US IPO (December 2025 reports).' },
      timeline: { title: 'EcoFlow Timeline', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: 'Founding year and product-line names verified; exact launch dates for PowerStream/STREAM were not confirmed on a primary source.' },
      lineup: { title: 'STREAM Lineup (AC Output)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: 'Max AC output as officially listed; battery capacity scales separately by configuration.' },
      markets: { title: 'US Legalization, State by State', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: 'States with enacted plug-in-solar legislation (July 2026) where EcoFlow is a named, cited brand.' },
      position: { title: 'Where EcoFlow Sits', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'EcoFlow designs its own microinverter and battery hardware and sells direct — same dual role as Anker SOLIX.' },
      certification: { title: 'Certification Claims', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'VDE-AR-N 4105 and TÜV Rheinland are EcoFlow’s own stated claims — not independently re-verified against the certifying bodies in this research pass.' },
    },
  },
  de: {
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow: Unternehmensprofil Balkonkraftwerk',
    seoTitle: 'EcoFlow Balkonkraftwerk Unternehmensprofil',
    metaDescription: 'Unternehmensprofil zu EcoFlow: Geschichte, Eigentümerstruktur, Produktpalette und Rolle im Markt für Balkonkraftwerke.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Leser, die EcoFlow als Unternehmen recherchieren, unabhängig von einer Kaufabsicht',
    sections: {
      snapshot: { title: 'EcoFlow: Unternehmensüberblick', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: '2017 in Shenzhen von vier Mitgründern gegründet; in Privatbesitz, Berichten zufolge wird ein US-Börsengang geprüft (Berichte von Dezember 2025).' },
      timeline: { title: 'EcoFlow Zeitleiste', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: 'Gründungsjahr und Namen der Produktlinien bestätigt; genaue Markteinführungsdaten für PowerStream/STREAM konnten nicht anhand einer Primärquelle bestätigt werden.' },
      lineup: { title: 'STREAM-Modellreihe (AC-Ausgangsleistung)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: 'Maximale AC-Ausgangsleistung gemäß offizieller Angabe; die Akkukapazität skaliert je nach Konfiguration separat.' },
      markets: { title: 'Legalisierung in den USA, Bundesstaat für Bundesstaat', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: 'Bundesstaaten mit verabschiedeter Gesetzgebung zu Steckersolargeräten (Stand Juli 2026), in denen EcoFlow als namentlich genannte Marke zitiert wird.' },
      position: { title: 'Positionierung von EcoFlow', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'EcoFlow entwickelt eigene Mikrowechselrichter und Akku-Hardware und verkauft direkt – dieselbe Doppelrolle wie Anker SOLIX.' },
      certification: { title: 'Zertifizierungsangaben', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'VDE-AR-N 4105 und TÜV Rheinland sind eigene Angaben von EcoFlow – in dieser Recherche nicht unabhängig bei den Zertifizierungsstellen erneut überprüft.' },
    },
  },
  fr: {
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow : profil d\'entreprise solaire de balcon',
    seoTitle: 'EcoFlow : Profil Entreprise Solaire Balcon',
    metaDescription: 'Profil d\'entreprise d\'EcoFlow : historique, actionnariat, gamme de produits et rôle sur le marché du solaire de balcon.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Lecteurs qui recherchent des informations sur EcoFlow en tant qu\'entreprise, distinct d\'une intention d\'achat comparatif',
    sections: {
      snapshot: { title: 'EcoFlow : aperçu de l\'entreprise', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: 'Fondée en 2017 à Shenzhen par quatre cofondateurs ; société privée, envisagerait une introduction en bourse aux États-Unis (rapports de décembre 2025).' },
      timeline: { title: 'Chronologie d\'EcoFlow', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: 'Année de fondation et noms des gammes de produits vérifiés ; les dates de lancement exactes de PowerStream/STREAM n\'ont pas été confirmées par une source primaire.' },
      lineup: { title: 'Gamme STREAM (puissance de sortie CA)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: 'Puissance de sortie CA maximale selon les données officielles ; la capacité de la batterie varie séparément selon la configuration.' },
      markets: { title: 'Légalisation aux États-Unis, État par État', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: 'États ayant adopté une législation sur le solaire enfichable (juillet 2026) où EcoFlow est cité nommément comme marque.' },
      position: { title: 'Positionnement d\'EcoFlow', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'EcoFlow conçoit ses propres micro-onduleurs et batteries et vend en direct – le même double rôle qu\'Anker SOLIX.' },
      certification: { title: 'Déclarations de certification', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'VDE-AR-N 4105 et TÜV Rheinland sont des déclarations propres à EcoFlow – non revérifiées de manière indépendante auprès des organismes de certification dans le cadre de cette recherche.' },
    },
  },
  ja: {
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow:ベランダ太陽光発電の企業プロフィール',
    seoTitle: 'EcoFlow企業プロフィール ベランダ太陽光',
    metaDescription: 'EcoFlowの企業プロフィールです。沿革、資本構成、製品ラインナップ、ベランダ太陽光市場における位置づけを紹介します。',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: '購入比較目的とは異なり、企業としてのEcoFlowを調べている読者',
    sections: {
      snapshot: { title: 'EcoFlow:企業スナップショット', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: '2017年に深圳で4名の共同創業者により設立。非公開企業で、米国での新規株式公開(IPO)を検討していると報じられている(2025年12月の報道)。' },
      timeline: { title: 'EcoFlow年表', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: '設立年と製品ラインの名称は確認済みですが、PowerStream/STREAMの正確な発売日は一次情報源で確認できませんでした。' },
      lineup: { title: 'STREAMラインナップ(AC出力)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: '公式に記載された最大AC出力です。バッテリー容量は構成ごとに個別に変動します。' },
      markets: { title: '米国での合法化状況(州別)', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: 'プラグイン式太陽光発電に関する法律が制定された州(2026年7月時点)で、EcoFlowが名指しで引用されているものです。' },
      position: { title: 'EcoFlowの立ち位置', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'EcoFlowは独自のマイクロインバーターとバッテリーハードウェアを設計し、直接販売しています。Anker SOLIXと同様の二重の役割です。' },
      certification: { title: '認証に関する主張', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'VDE-AR-N 4105およびTÜV Rheinlandは、EcoFlow自身による主張であり、今回の調査では認証機関に対して独自に再検証は行っていません。' },
    },
  },
  zh: {
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow:阳台光伏企业档案',
    seoTitle: 'EcoFlow阳台光伏企业档案',
    metaDescription: 'EcoFlow企业档案:公司历史、股权结构、产品系列,以及在阳台光伏市场中的角色。',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: '研究EcoFlow作为企业本身的读者,而非比较购买意图的读者',
    sections: {
      snapshot: { title: 'EcoFlow:企业概况', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: '2017年由四位联合创始人在深圳创立;为私营企业,据报道正考虑在美国上市(2025年12月的报道)。' },
      timeline: { title: 'EcoFlow发展时间线', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: '成立年份及产品线名称已核实;PowerStream/STREAM的确切上市日期未能在一手资料中得到确认。' },
      lineup: { title: 'STREAM系列(AC输出功率)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: '最大AC输出功率为官方公布数据;电池容量根据配置不同而单独变化。' },
      markets: { title: '美国各州合法化情况', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: '已颁布插电式光伏立法的州份(截至2026年7月),其中EcoFlow被列为具名品牌。' },
      position: { title: 'EcoFlow的市场定位', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'EcoFlow自行设计微型逆变器和电池硬件并直接销售——与Anker SOLIX担任相同的双重角色。' },
      certification: { title: '认证声明', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'VDE-AR-N 4105和TÜV Rheinland为EcoFlow自身声明的认证——本次调研未针对认证机构进行独立复核。' },
    },
  },
  es: {
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow: perfil de empresa de solar de balcón',
    seoTitle: 'EcoFlow: Perfil Empresa Solar Balcón',
    metaDescription: 'Perfil de empresa de EcoFlow: historia, propiedad, gama de productos y su papel en el mercado de solar de balcón.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Lectores que investigan a EcoFlow como empresa, distinto de la intención de comparar para comprar',
    sections: {
      snapshot: { title: 'EcoFlow: panorama de la empresa', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: 'Fundada en 2017 en Shenzhen por cuatro cofundadores; de propiedad privada, según informes estaría considerando una salida a bolsa en EE. UU. (informes de diciembre de 2025).' },
      timeline: { title: 'Cronología de EcoFlow', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: 'El año de fundación y los nombres de las líneas de producto están verificados; las fechas exactas de lanzamiento de PowerStream/STREAM no se confirmaron en una fuente primaria.' },
      lineup: { title: 'Gama STREAM (salida de CA)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: 'Salida de CA máxima según lo indicado oficialmente; la capacidad de batería varía por separado según la configuración.' },
      markets: { title: 'Legalización en EE. UU., estado por estado', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: 'Estados con legislación aprobada sobre solar enchufable (julio de 2026) donde EcoFlow se cita como marca por nombre.' },
      position: { title: 'Posicionamiento de EcoFlow', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'EcoFlow diseña sus propios microinversores y baterías, y vende de forma directa; el mismo doble papel que Anker SOLIX.' },
      certification: { title: 'Afirmaciones de certificación', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'VDE-AR-N 4105 y TÜV Rheinland son afirmaciones propias de EcoFlow, no reverificadas de forma independiente ante los organismos certificadores en esta investigación.' },
    },
  },
  pt: {
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow: perfil da empresa de solar de varanda',
    seoTitle: 'EcoFlow: Perfil Empresa Solar Varanda',
    metaDescription: 'Perfil da empresa EcoFlow: história, propriedade, linha de produtos e papel no mercado de solar de varanda.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Leitores que pesquisam a EcoFlow como empresa, diferente da intenção de comparação para compra',
    sections: {
      snapshot: { title: 'EcoFlow: panorama da empresa', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: 'Fundada em 2017 em Shenzhen por quatro cofundadores; de capital fechado, segundo relatos estaria avaliando um IPO nos EUA (relatos de dezembro de 2025).' },
      timeline: { title: 'Linha do tempo da EcoFlow', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: 'Ano de fundação e nomes das linhas de produtos confirmados; as datas exatas de lançamento do PowerStream/STREAM não foram confirmadas em fonte primária.' },
      lineup: { title: 'Linha STREAM (saída CA)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: 'Saída CA máxima conforme informado oficialmente; a capacidade da bateria varia separadamente conforme a configuração.' },
      markets: { title: 'Legalização nos EUA, estado por estado', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: 'Estados com legislação aprovada sobre solar plug-in (julho de 2026) nos quais a EcoFlow é citada nominalmente como marca.' },
      position: { title: 'Posicionamento da EcoFlow', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'A EcoFlow projeta seus próprios microinversores e baterias e vende diretamente — o mesmo papel duplo da Anker SOLIX.' },
      certification: { title: 'Alegações de certificação', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'VDE-AR-N 4105 e TÜV Rheinland são alegações da própria EcoFlow — não reverificadas de forma independente junto aos órgãos certificadores nesta pesquisa.' },
    },
  },
  ar: {
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow: ملف الشركة للطاقة الشمسية للشرفات',
    seoTitle: 'EcoFlow: ملف شركة الطاقة الشمسية',
    metaDescription: 'ملف شركة EcoFlow: التاريخ والملكية وتشكيلة المنتجات ودورها في سوق الطاقة الشمسية للشرفات.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'القراء الذين يبحثون عن EcoFlow كشركة، بخلاف نية المقارنة الشرائية',
    sections: {
      snapshot: { title: 'EcoFlow: لمحة عن الشركة', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: 'تأسست عام 2017 في Shenzhen على يد أربعة مؤسسين مشاركين؛ وهي شركة مملوكة ملكية خاصة، وتفيد تقارير بأنها تدرس طرح أسهم أولي في الولايات المتحدة (تقارير ديسمبر 2025).' },
      timeline: { title: 'الجدول الزمني لـ EcoFlow', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: 'تم التحقق من سنة التأسيس وأسماء خطوط المنتجات؛ لم يتم تأكيد تواريخ الإطلاق الدقيقة لـ PowerStream/STREAM من مصدر أساسي.' },
      lineup: { title: 'تشكيلة STREAM (خرج التيار المتردد)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: 'أقصى خرج للتيار المتردد كما هو مُدرج رسمياً؛ سعة البطارية تتغير بشكل منفصل حسب التهيئة.' },
      markets: { title: 'التقنين في الولايات المتحدة، ولاية بولاية', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: 'الولايات التي سنّت تشريعات للطاقة الشمسية القابلة للتوصيل (يوليو 2026) والتي تُذكر فيها EcoFlow كعلامة تجارية بالاسم.' },
      position: { title: 'موقع EcoFlow في السوق', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'تصمم EcoFlow عاكساتها الدقيقة وبطارياتها الخاصة وتبيع مباشرة - نفس الدور المزدوج الذي تؤديه Anker SOLIX.' },
      certification: { title: 'ادعاءات الشهادات', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'معياري VDE-AR-N 4105 وTÜV Rheinland هما ادعاءان صادران عن EcoFlow نفسها - ولم تتم إعادة التحقق منهما بشكل مستقل لدى جهات إصدار الشهادات في إطار هذا البحث.' },
    },
  },
  ko: {
    theme: 'Balcony Solar Money Pages',
    title: 'EcoFlow: 발코니 태양광 기업 프로필',
    seoTitle: 'EcoFlow 발코니 태양광 기업 프로필',
    metaDescription: 'EcoFlow의 기업 프로필입니다. 연혁, 소유 구조, 제품 라인업, 그리고 발코니 태양광 시장에서의 역할을 소개합니다.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: '구매 비교 의도와는 별개로 EcoFlow를 기업으로서 조사하는 독자',
    sections: {
      snapshot: { title: 'EcoFlow: 기업 스냅숏', image: '/images/ecoflow-balcony-solar-snapshot-en.svg', imageCaption: '2017년 선전(Shenzhen)에서 4명의 공동 창업자가 설립했습니다. 비상장 기업이며, 미국 IPO를 검토 중이라는 보도가 있습니다(2025년 12월 보도).' },
      timeline: { title: 'EcoFlow 연혁', image: '/images/ecoflow-balcony-solar-timeline-en.svg', imageCaption: '설립 연도와 제품 라인 명칭은 확인되었으나, PowerStream/STREAM의 정확한 출시일은 1차 자료에서 확인되지 않았습니다.' },
      lineup: { title: 'STREAM 라인업(AC 출력)', image: '/images/ecoflow-balcony-solar-lineup-en.svg', imageCaption: '공식적으로 명시된 최대 AC 출력이며, 배터리 용량은 구성에 따라 별도로 달라집니다.' },
      markets: { title: '미국 주별 합법화 현황', image: '/images/ecoflow-balcony-solar-markets-en.svg', imageCaption: '플러그인 태양광 관련 법안이 제정된 주(2026년 7월 기준)로, EcoFlow가 브랜드명으로 명시적으로 언급된 곳입니다.' },
      position: { title: 'EcoFlow의 시장 위치', image: '/images/ecoflow-balcony-solar-position-en.svg', imageCaption: 'EcoFlow는 자체 마이크로인버터와 배터리 하드웨어를 설계하여 직접 판매합니다. Anker SOLIX와 동일한 이중 역할입니다.' },
      certification: { title: '인증 관련 주장', image: '/images/ecoflow-balcony-solar-certification-en.svg', imageCaption: 'VDE-AR-N 4105 및 TÜV Rheinland는 EcoFlow 자체의 주장이며, 이번 조사에서 인증 기관을 통해 독립적으로 재검증되지 않았습니다.' },
    },
  },
}
