// Slug: goodwe-balcony-solar
// Phase 1 scaffold (2026-07-19) — structure/frontmatter only, no body content yet.
// Noindex + sitemap-excluded via PENDING_SLUGS in published.ts until content,
// translation, and internal-linking phases land (see TIER 6 in slugs.ts).
import type { Language } from "@/lib/blog/blogContent";
import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    freshness_tier: 'semi_annual',
    next_refresh_due: '2027-01-19',
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe: Balcony Solar Company Profile',
    seoTitle: 'GoodWe Balcony Solar Company Profile',
    metaDescription: 'Company profile for GoodWe: history, ownership, and product range in the balcony solar market.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Readers researching GoodWe as a company',
    // No cross-link requirement specified for this profile in Phase 1.
    sections: {
      snapshot: { title: 'GoodWe: Company Snapshot', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: 'Founded 2010 in Suzhou, China; listed on the Shanghai STAR Market since September 2020. Balcony products sold under a separate consumer brand, PVBM.' },
      timeline: { title: 'Timeline', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: 'Founding and listing dates verified; Wood Mackenzie ranking is an independent, non-self-reported source.' },
      lineup: { title: 'ESA Athena Battery Capacity', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: 'Base and expanded capacity as officially listed on the PVBM product page.' },
      position: { title: 'Where GoodWe Sits', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'GoodWe is a large, independently-ranked inverter manufacturer whose PVBM sub-brand serves the balcony-consumer niche.' },
      ranking: { title: 'Independent Industry Ranking', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: 'One of the few companies in this set with an independent (Wood Mackenzie) ranking rather than a self-reported figure.' },
      certification: { title: 'Certification Note', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'PVBM marketing cites "VDE 4110" for an 800W product; VDE-AR-N 4105 is the standard typically associated with balcony-scale feed-in — flagged here rather than stated as settled.' },
    },
  },
  de: {
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe: Unternehmensprofil Balkonkraftwerke',
    seoTitle: 'GoodWe: Unternehmensprofil im Balkonkraftwerk-Markt',
    metaDescription: 'Unternehmensprofil zu GoodWe: Gründung, Börsennotierung, Eigentümerstruktur und Produktangebot der Marke PVBM im Balkonkraftwerk-Markt.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Leser, die GoodWe als Unternehmen recherchieren',
    sections: {
      snapshot: { title: 'GoodWe: Unternehmensüberblick', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: 'Gegründet 2010 in Suzhou, China; notiert am Shanghai STAR Market seit September 2020. Balkonprodukte werden unter der eigenständigen Verbrauchermarke PVBM verkauft.' },
      timeline: { title: 'Zeitachse', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: 'Gründungs- und Börsengangsdaten verifiziert; das Wood-Mackenzie-Ranking stammt aus einer unabhängigen, nicht selbst gemeldeten Quelle.' },
      lineup: { title: 'Akkukapazität ESA Athena', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: 'Basis- und erweiterte Kapazität wie offiziell auf der PVBM-Produktseite gelistet.' },
      position: { title: 'Wo GoodWe steht', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'GoodWe ist ein großer, unabhängig eingestufter Wechselrichterhersteller, dessen Submarke PVBM die Nische der Balkon-Verbraucher bedient.' },
      ranking: { title: 'Unabhängiges Branchenranking', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: 'Eines der wenigen Unternehmen in dieser Gruppe mit einem unabhängigen (Wood Mackenzie) Ranking statt einer selbst gemeldeten Zahl.' },
      certification: { title: 'Hinweis zur Zertifizierung', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'Das PVBM-Marketing nennt „VDE 4110“ für ein 800-W-Produkt; VDE-AR-N 4105 ist die Norm, die typischerweise mit der Einspeisung im Balkonkraftwerk-Maßstab verbunden wird — hier als offener Punkt markiert, nicht als geklärt dargestellt.' },
    },
  },
  fr: {
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe : profil d\'entreprise solaire balcon',
    seoTitle: 'GoodWe : profil d\'entreprise dans le solaire balcon',
    metaDescription: 'Profil d\'entreprise de GoodWe : fondation, cotation en bourse, actionnariat et gamme de produits de la marque PVBM sur le marché du solaire balcon.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Lecteurs qui recherchent des informations sur GoodWe',
    sections: {
      snapshot: { title: 'GoodWe : aperçu de l\'entreprise', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: 'Fondée en 2010 à Suzhou, en Chine ; cotée au Shanghai STAR Market depuis septembre 2020. Les produits pour balcon sont vendus sous une marque grand public distincte, PVBM.' },
      timeline: { title: 'Chronologie', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: 'Dates de fondation et d\'introduction en bourse vérifiées ; le classement Wood Mackenzie provient d\'une source indépendante, non auto-déclarée.' },
      lineup: { title: 'Capacité de batterie ESA Athena', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: 'Capacité de base et étendue telle qu\'indiquée officiellement sur la page produit PVBM.' },
      position: { title: 'Où se situe GoodWe', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'GoodWe est un grand fabricant d\'onduleurs classé de manière indépendante, dont la sous-marque PVBM sert le créneau des consommateurs de solaire balcon.' },
      ranking: { title: 'Classement sectoriel indépendant', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: 'L\'une des rares entreprises de cet ensemble avec un classement indépendant (Wood Mackenzie) plutôt qu\'un chiffre auto-déclaré.' },
      certification: { title: 'Remarque sur la certification', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'Le marketing de PVBM cite « VDE 4110 » pour un produit de 800 W ; VDE-AR-N 4105 est la norme habituellement associée à l\'injection à l\'échelle du solaire balcon — signalé ici comme un point ouvert, pas comme établi.' },
    },
  },
  ja: {
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe:ベランダ太陽光企業プロフィール',
    seoTitle: 'GoodWe企業プロフィール:ベランダ太陽光市場での立ち位置',
    metaDescription: 'GoodWeの企業プロフィールを解説。2010年の設立から上海STARマーケット上場、株主構成、消費者ブランドPVBMによるベランダ太陽光製品ラインナップまでを紹介します。',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'GoodWeという企業について調べている読者',
    sections: {
      snapshot: { title: 'GoodWe:企業スナップショット', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: '2010年に中国・蘇州で設立。2020年9月より上海STARマーケットに上場。ベランダ向け製品は別の消費者向けブランド「PVBM」で販売されている。' },
      timeline: { title: '沿革', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: '設立日と上場日は確認済み。Wood Mackenzieによるランキングは自己申告ではない独立した情報源によるもの。' },
      lineup: { title: 'ESA Athenaバッテリー容量', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: '基本容量と拡張容量はPVBMの製品ページに公式に記載されている数値。' },
      position: { title: 'GoodWeの立ち位置', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'GoodWeは独立機関による評価を受けた大手インバーターメーカーであり、サブブランドPVBMがベランダ消費者向けのニッチ市場を担う。' },
      ranking: { title: '独立系業界ランキング', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: '自己申告の数値ではなく、独立機関(Wood Mackenzie)によるランキングを持つ数少ない企業の一つ。' },
      certification: { title: '認証に関する注記', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'PVBMのマーケティングでは800W製品について「VDE 4110」を挙げているが、ベランダ規模の逆潮流に一般的に関連付けられる規格はVDE-AR-N 4105である。確定事項ではなく要確認事項としてここに記載する。' },
    },
  },
  zh: {
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe:阳台光伏公司简介',
    seoTitle: 'GoodWe阳台光伏公司简介:成立历史、股权结构与产品线',
    metaDescription: 'GoodWe公司简介:详解其成立于2010年的历史沿革、在上海科创板的上市情况、股权结构,以及旗下消费品牌PVBM在阳台光伏市场的完整产品线。',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: '正在了解GoodWe公司的读者',
    sections: {
      snapshot: { title: 'GoodWe:公司概况', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: '2010年成立于中国苏州,自2020年9月起在上海科创板(STAR Market)上市。阳台产品以独立消费品牌PVBM销售。' },
      timeline: { title: '发展历程', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: '成立日期和上市日期已核实;Wood Mackenzie的排名来自独立的非自我申报来源。' },
      lineup: { title: 'ESA Athena电池容量', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: '基础容量和扩展容量均为PVBM产品页面官方公布的数据。' },
      position: { title: 'GoodWe的市场地位', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'GoodWe是一家经独立评级的大型逆变器制造商,其子品牌PVBM专注于阳台消费者这一细分市场。' },
      ranking: { title: '独立行业排名', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: '在该组企业中,GoodWe是少数拥有独立(Wood Mackenzie)排名而非自我申报数据的公司之一。' },
      certification: { title: '认证说明', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'PVBM的宣传材料中为一款800W产品引用了"VDE 4110";而通常与阳台规模并网相关的标准是VDE-AR-N 4105——此处将其标记为存疑事项,而非既定事实。' },
    },
  },
  es: {
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe: perfil de empresa de solar de balcón',
    seoTitle: 'GoodWe: perfil completo de empresa solar de balcón',
    metaDescription: 'Perfil de empresa de GoodWe: fundación, cotización bursátil, propiedad y gama de productos de la marca PVBM en el mercado del solar de balcón.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Lectores que investigan a GoodWe como empresa',
    sections: {
      snapshot: { title: 'GoodWe: resumen de la empresa', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: 'Fundada en 2010 en Suzhou, China; cotiza en el Shanghai STAR Market desde septiembre de 2020. Los productos de balcón se venden bajo una marca de consumo independiente, PVBM.' },
      timeline: { title: 'Cronología', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: 'Fechas de fundación y de salida a bolsa verificadas; el ranking de Wood Mackenzie procede de una fuente independiente, no autodeclarada.' },
      lineup: { title: 'Capacidad de batería ESA Athena', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: 'Capacidad base y ampliada tal como figura oficialmente en la página de producto de PVBM.' },
      position: { title: 'Dónde se ubica GoodWe', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'GoodWe es un gran fabricante de inversores con clasificación independiente, cuya submarca PVBM atiende el nicho de consumidores de solar de balcón.' },
      ranking: { title: 'Ranking independiente del sector', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: 'Una de las pocas empresas de este grupo con una clasificación independiente (Wood Mackenzie) en lugar de una cifra autodeclarada.' },
      certification: { title: 'Nota sobre certificación', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'El marketing de PVBM cita "VDE 4110" para un producto de 800 W; VDE-AR-N 4105 es la norma habitualmente asociada a la inyección a escala de solar de balcón, señalada aquí como un punto abierto y no como algo resuelto.' },
    },
  },
  pt: {
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe: perfil da empresa de energia solar de varanda',
    seoTitle: 'GoodWe: perfil completo da empresa solar de varanda',
    metaDescription: 'Perfil da empresa GoodWe: fundação, listagem em bolsa, propriedade e linha de produtos da marca PVBM no mercado de energia solar de varanda.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'Leitores que pesquisam a GoodWe como empresa',
    sections: {
      snapshot: { title: 'GoodWe: panorama da empresa', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: 'Fundada em 2010 em Suzhou, na China; listada na Shanghai STAR Market desde setembro de 2020. Os produtos de varanda são vendidos sob uma marca de consumo separada, a PVBM.' },
      timeline: { title: 'Linha do tempo', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: 'Datas de fundação e listagem verificadas; o ranking da Wood Mackenzie vem de uma fonte independente, não autodeclarada.' },
      lineup: { title: 'Capacidade da bateria ESA Athena', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: 'Capacidade base e expandida conforme listado oficialmente na página de produto da PVBM.' },
      position: { title: 'Onde a GoodWe se posiciona', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'A GoodWe é uma grande fabricante de inversores com classificação independente, cuja submarca PVBM atende o nicho de consumidores de energia solar de varanda.' },
      ranking: { title: 'Ranking independente do setor', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: 'Uma das poucas empresas deste grupo com uma classificação independente (Wood Mackenzie) em vez de um número autodeclarado.' },
      certification: { title: 'Nota sobre certificação', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'O marketing da PVBM cita "VDE 4110" para um produto de 800 W; a VDE-AR-N 4105 é a norma normalmente associada à injeção na escala de energia solar de varanda — sinalizado aqui como um ponto em aberto, não como algo resolvido.' },
    },
  },
  ar: {
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe: الملف التعريفي لشركة الطاقة الشمسية للشرفات',
    seoTitle: 'GoodWe: الملف التعريفي لشركة الطاقة الشمسية للشرفات',
    metaDescription: 'ملف تعريفي لشركة GoodWe: التأسيس، الإدراج في البورصة، الملكية، وتشكيلة منتجات علامة PVBM بالكامل في سوق الطاقة الشمسية للشرفات.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'القراء الذين يبحثون عن شركة GoodWe',
    sections: {
      snapshot: { title: 'GoodWe: لمحة عن الشركة', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: 'تأسست عام 2010 في سوتشو، الصين؛ ومدرجة في سوق STAR بشنغهاي منذ سبتمبر 2020. تُباع منتجات الشرفات تحت علامة استهلاكية منفصلة تُسمى PVBM.' },
      timeline: { title: 'الجدول الزمني', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: 'تم التحقق من تاريخي التأسيس والإدراج؛ ويستند تصنيف Wood Mackenzie إلى مصدر مستقل غير معتمد على تصريح الشركة نفسها.' },
      lineup: { title: 'سعة بطارية ESA Athena', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: 'السعة الأساسية والموسّعة كما هي مدرجة رسميًا في صفحة منتج PVBM.' },
      position: { title: 'مكانة GoodWe في السوق', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'GoodWe مُصنّعة كبيرة لعواكس الطاقة ومصنّفة بشكل مستقل، وتخدم علامتها الفرعية PVBM فئة مستهلكي الطاقة الشمسية للشرفات.' },
      ranking: { title: 'تصنيف مستقل للصناعة', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: 'واحدة من الشركات القليلة في هذه المجموعة التي تملك تصنيفًا مستقلًا (Wood Mackenzie) بدلاً من رقم معتمد على تصريح ذاتي.' },
      certification: { title: 'ملاحظة حول الاعتماد', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'تشير تسويقات PVBM إلى "VDE 4110" لمنتج بقدرة 800 واط؛ في حين أن VDE-AR-N 4105 هو المعيار المرتبط عادةً بتغذية الشبكة على نطاق الشرفات — وقد أُشير إلى ذلك هنا كمسألة مفتوحة وليس كأمر محسوم.' },
    },
  },
  ko: {
    theme: 'Balcony Solar Money Pages',
    title: 'GoodWe: 발코니 태양광 기업 프로필',
    seoTitle: 'GoodWe 발코니 태양광 기업 프로필 및 시장 위치',
    metaDescription: 'GoodWe 기업 프로필을 소개합니다. 2010년 설립부터 상하이 STAR 마켓 상장, 소유 구조, 소비자 브랜드 PVBM의 발코니 태양광 제품 라인업까지 다룹니다.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-19',
    audience: 'GoodWe라는 기업을 조사하는 독자',
    sections: {
      snapshot: { title: 'GoodWe: 기업 개요', image: '/images/goodwe-balcony-solar-snapshot-en.svg', imageCaption: '2010년 중국 쑤저우(Suzhou)에서 설립되었으며, 2020년 9월부터 상하이 STAR 마켓에 상장되어 있습니다. 발코니용 제품은 별도의 소비자 브랜드인 PVBM으로 판매됩니다.' },
      timeline: { title: '연혁', image: '/images/goodwe-balcony-solar-timeline-en.svg', imageCaption: '설립일과 상장일은 확인되었으며, Wood Mackenzie 순위는 자체 보고가 아닌 독립적인 출처에서 나온 것입니다.' },
      lineup: { title: 'ESA Athena 배터리 용량', image: '/images/goodwe-balcony-solar-lineup-en.svg', imageCaption: '기본 용량과 확장 용량은 PVBM 제품 페이지에 공식적으로 기재된 수치입니다.' },
      position: { title: 'GoodWe의 시장 위치', image: '/images/goodwe-balcony-solar-position-en.svg', imageCaption: 'GoodWe는 독립적으로 순위가 매겨진 대형 인버터 제조사이며, 자사 서브 브랜드 PVBM이 발코니 소비자 틈새시장을 담당합니다.' },
      ranking: { title: '독립 업계 순위', image: '/images/goodwe-balcony-solar-ranking-en.svg', imageCaption: '이 그룹에서 자체 보고 수치가 아닌 독립적인(Wood Mackenzie) 순위를 보유한 몇 안 되는 기업 중 하나입니다.' },
      certification: { title: '인증 관련 참고 사항', image: '/images/goodwe-balcony-solar-certification-en.svg', imageCaption: 'PVBM 마케팅 자료는 800W 제품에 대해 "VDE 4110"을 언급하지만, 발코니 규모 계통 연계와 일반적으로 연관되는 규격은 VDE-AR-N 4105입니다. 이는 확정된 사실이 아니라 확인이 필요한 사항으로 표시합니다.' },
    },
  },
}
