// Slug: is-balcony-solar-legal-country-guide
// BSOL-11 — Tier 3 tracker master, semi_annual, ★ SPOT-CHECK (legal/moat). Links to BSOL-12..16.
import type { Language } from "@/lib/blog/blogContent";
import type { LLMArticle } from "@/lib/local-llms/types";
import { COUNTRY_DATA } from "@/lib/shared/balcony-solar-country-data";

const statusRows = COUNTRY_DATA.map((c) => ({
  country: c.country,
  status: c.legalStatus,
  powerLimit: c.powerLimitW ? `${c.powerLimitW}W` : (c.powerLimitNote || 'No fixed limit found'),
}));

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    freshness_tier: 'semi_annual',
    next_refresh_due: '2027-01-02',
    last_full_refresh: '2026-07-02',
    theme: 'Balcony Solar Legislation',
    title: 'Is Balcony Solar Legal? Country-by-Country Status Guide',
    seoTitle: 'Is Balcony Solar Legal? Global Status Guide (2026)',
    intro: 'Balcony solar\'s legal status ranges from a codified, well-defined simplified regime to genuine regulatory silence — and the difference matters more than any spec sheet before you buy anything. This guide tracks current status across every major market this site covers, with links to the full detail for each.',
    metaDescription: 'Is balcony solar legal in your country? Global status tracker covering the US, Germany, Spain, Portugal, Brazil, Mexico, and the Gulf/MENA region, verified July 2026.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '9 min read',
    educationalLevel: 'Intermediate',
    audience: 'Prospective balcony solar buyers needing to confirm legal status before purchasing',
    primaryTerm: 'is balcony solar legal',
    targetKeywords: ['is balcony solar legal', 'balcony solar legal status by country', 'plug in solar legality', 'where is balcony solar legal'],
    leadAnswerBlock: '**Balcony solar\'s legal status varies enormously by country: Portugal has a clearly codified simplified regime, Germany has a well-established one, the US varies entirely by state with no federal framework, and Brazil, Mexico, and the Gulf/MENA region currently have no dedicated small-system exemption at all.** There is no default assumption that\'s safe to make — confirm your specific country\'s (and in the US, state\'s) status before buying.',
    quickAnswerTop: {
      en: {
        question: 'Is balcony solar legal where I live?',
        answer: 'It depends entirely on your country, and in the US, your state. Portugal and Germany have the clearest, most established simplified regimes. The US has no federal framework — legality is determined state by state, with only a handful of states having passed dedicated legislation. Brazil, Mexico, and the Gulf/MENA region have no small-system exemption; standard interconnection rules apply regardless of size. Spain\'s status is genuinely ambiguous.',
        bullets: [
          'Portugal: explicitly legal, codified simplified regime for systems ≤700W with no grid export',
          'Germany: explicitly legal, established simplified regime (MaStR-only registration, 800W inverter cap)',
          'United States: varies by state, no federal framework — check the dedicated state-by-state guide',
          'Spain: ambiguous — conflicting vendor vs. legal sources on whether a simplified exemption exists',
          'Brazil, Mexico, Gulf/MENA: no small-system exemption — standard interconnection rules apply to any size',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'Key Takeaways', anchor: '#key-takeaways' },
      { label: 'Global Status Overview', anchor: '#global-status' },
      { label: 'What Does "Legal" Actually Mean?', anchor: '#what-legal-means' },
      { label: 'Country Pages', anchor: '#country-pages' },
      { label: 'How These Rules Are Changing', anchor: '#how-rules-are-changing' },
      { label: 'FAQ', anchor: '#faq' },
      { label: 'Related Reading', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'Legal status ranges from a codified simplified regime (Portugal, Germany) to genuine regulatory silence (parts of the Gulf/MENA region) — there is no safe default assumption.',
          'The US has no federal framework — legality is entirely state-determined, and most states haven\'t addressed balcony solar specifically at all yet.',
          'Brazil and Mexico both apply their standard full interconnection process regardless of system size — no small-system carve-out exists in either country.',
          'Spain\'s status is a genuine open question — sources conflict on whether small kits get a simplified exemption.',
          'This tracker and every linked country page pull from a single shared data source, so a status change in one place updates everywhere consistently.',
          'Rules change fastest in the US, where new states are actively passing balcony solar legislation — check the dedicated US page for current month-to-month status.',
        ],
      },
      globalStatus: {
        id: 'global-status',
        title: 'Global Status Overview',
        content: [
          '**This table summarizes current legal status and power limits across every market this site covers — click through to each country page for full detail, sourcing, and registration steps.**',
        ],
        rows: statusRows,
        columns: ['country', 'status', 'powerLimit'],
        tableFormat: true,
      },
      whatLegalMeans: {
        id: 'what-legal-means',
        title: 'What Does "Legal" Actually Mean?',
        content: [
          '**"Legal" for balcony solar usually means one of three distinct things, and conflating them is a common source of confusion: explicitly permitted under a dedicated simplified regime with a defined power limit, legal only in the sense that it falls under the same rules as any other grid-tied solar system with no lighter-touch path, or genuinely unaddressed by current regulation (neither permitted nor banned).** The country pages below specify which of these three applies to your market, since the practical difference — self-install with a simple form vs. a full formal interconnection process — is significant.',
          'One more thing worth knowing before you shop: most widely available balcony solar hardware reports production data to the manufacturer\'s cloud by default, regardless of which country\'s legal regime you\'re under — local-only monitoring is the exception you have to specifically look for, not the default you can assume. See [running balcony solar without the cloud](/balcony-solar/home-assistant-balcony-solar-no-cloud) if that matters to you.',
        ],
        snippetBlocks: [
          { type: 'one-sentence', text: '"Legal" balcony solar can mean anything from a codified simplified regime to genuine regulatory silence — check which applies to your specific country.' },
          { type: 'plain-terms', text: 'Some countries have made a special, easy path just for small plug-in systems. Others just apply the same rules as a full rooftop install, no matter how small your system is. A few haven\'t addressed it at all.' },
        ],
      },
      countryPages: {
        id: 'country-pages',
        title: 'Country Pages',
        content: [
          '**Each market below has a dedicated page with full legal detail, registration steps, and sourcing.**',
        ],
        links: [
          { url: '/balcony-solar/balcony-solar-legal-us-states', title: 'Is Balcony Solar Legal in the US? State-by-State Guide', description: 'Signed and pending state legislation, updated regularly' },
          { url: '/balcony-solar/balkonkraftwerk-germany-rules', title: 'Balkonkraftwerk: Germany Rules Explained', description: '800W cap, MaStR registration, and the new DIN VDE V 0126-95 standard' },
          { url: '/balcony-solar/balcony-solar-spain-latam', title: 'Balcony Solar in Spain & Latin America', description: 'Spain\'s ambiguous status explained' },
          { url: '/balcony-solar/balcony-solar-portugal-brazil', title: 'Balcony Solar in Portugal & Brazil', description: 'Portugal\'s codified regime vs. Brazil\'s regulatory gap' },
          { url: '/balcony-solar/balcony-solar-gulf-mena', title: 'Balcony Solar in the Gulf & MENA Region', description: 'Nascent regulation in the UAE and Saudi Arabia' },
        ],
      },
      howRulesAreChanging: {
        id: 'how-rules-are-changing',
        title: 'How These Rules Are Changing',
        content: [
          '**US state legislation is the fastest-moving part of this landscape — several states have signed dedicated balcony solar bills within the past year, and more are actively moving through state legislatures.** Outside the US, changes are less frequent but not absent: Germany\'s DIN VDE V 0126-95 product standard took effect as recently as December 2025, showing that even established markets continue to refine their rules.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Frequently Asked Questions',
        faqs: [
          { q: 'Which countries have the clearest balcony solar laws?', a: 'Portugal and Germany both have well-established, codified simplified regimes with clear power limits and registration processes — the clearest status of any markets covered here.' },
          { q: 'Is balcony solar legal everywhere in the US?', a: 'No — there is no federal framework. Legality is determined entirely at the state level, and only a handful of states have passed dedicated legislation so far. See the state-by-state guide for current status.' },
          { q: 'Do any countries explicitly ban balcony solar?', a: 'None of the markets covered in this guide have an explicit ban — status ranges from clearly permitted to ambiguous to unaddressed, but not outright prohibited.' },
          { q: 'Why is Spain\'s status listed as ambiguous rather than a clear yes or no?', a: 'Sources genuinely conflict — vendor and press sources claim a simplified exemption for small kits, while a detailed legal-focused source says full formalities still apply. This guide reports that conflict rather than picking a side without confirmation.' },
          { q: 'Do Brazil and Mexico allow balcony solar?', a: 'It\'s not banned, but neither country has a small-system exemption — the same full interconnection registration process applies regardless of system size, which is a meaningfully different situation from a dedicated simplified regime.' },
          { q: 'How often does this legal status information change?', a: 'This page and its linked country pages are on a 6-month refresh cycle, though the US state page refreshes faster (60 days) given how quickly US state legislation is moving.' },
          { q: 'What should I do if my country isn\'t listed here?', a: 'Check your national or regional energy regulator directly — this guide covers the markets this site currently tracks, not every country worldwide.' },
          { q: 'Is unregulated the same as legal?', a: 'Not necessarily — genuinely unaddressed regulation (as in parts of the Gulf/MENA region) means neither explicit permission nor prohibition exists, which carries different practical risk than a market with a clear simplified legal framework.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'Is Balcony Solar Legal? Country-by-Country Status Guide',
      description: 'Is balcony solar legal in your country? Global status tracker covering the US, Germany, Spain, Portugal, Brazil, Mexico, and the Gulf/MENA region, verified July 2026.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
      url: 'https://www.promptquorum.com/balcony-solar/is-balcony-solar-legal-country-guide',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: 'Prospective balcony solar buyers needing to confirm legal status before purchasing' },
      about: ['Balcony solar legality', 'Solar regulation', 'Steckersolargeräte', 'Plug-in solar law'],
    },
  },
  es: {
    theme: 'Balcony Solar Legislation',
    title: '¿Es legal la energía solar de balcón? Guía de estado país por país',
    seoTitle: '¿Es legal la energía solar de balcón? Guía global (2026)',
    intro: 'El estado legal de la energía solar de balcón va desde un régimen simplificado, codificado y bien definido hasta un auténtico vacío normativo — y esa diferencia importa más que cualquier ficha técnica antes de comprar nada. Esta guía hace seguimiento del estado actual en cada mercado principal que cubre este sitio, con enlaces al detalle completo de cada uno.',
    metaDescription: '¿Es legal la energía solar de balcón en tu país? Seguimiento global del estado legal en Estados Unidos, Alemania, España, Portugal, Brasil, México y la región del Golfo/MENA, verificado en julio de 2026.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '9 min de lectura',
    educationalLevel: 'Intermediate',
    audience: 'Compradores potenciales de energía solar de balcón que necesitan confirmar el estado legal antes de comprar',
    primaryTerm: 'es legal la energía solar de balcón',
    targetKeywords: ['es legal la energía solar de balcón', 'estado legal de la energía solar de balcón por país', 'legalidad del solar enchufable', 'dónde es legal la energía solar de balcón'],
    leadAnswerBlock: '**El estado legal de la energía solar de balcón varía enormemente según el país: Portugal tiene un régimen simplificado claramente codificado, Alemania tiene uno bien establecido, Estados Unidos varía completamente según el estado sin ningún marco federal, y Brasil, México y la región del Golfo/MENA actualmente no tienen ninguna exención específica para sistemas pequeños.** No existe una suposición por defecto que sea segura — confirma el estado legal de tu país concreto (y, en Estados Unidos, de tu estado) antes de comprar.',
    quickAnswerTop: {
      es: {
        question: '¿Es legal la energía solar de balcón donde vivo?',
        answer: 'Depende por completo de tu país, y en EE. UU., de tu estado. Portugal y Alemania tienen los regímenes simplificados más claros y establecidos. EE. UU. no tiene un marco federal — la legalidad se determina estado por estado, y solo un puñado de estados ha aprobado legislación dedicada. Brasil, México y la región del Golfo/MENA no tienen exención para sistemas pequeños; se aplican las reglas de interconexión estándar sin importar el tamaño. El estado de España es genuinamente ambiguo.',
        bullets: [
          'Portugal: explícitamente legal, régimen simplificado codificado para sistemas ≤700W sin exportación a la red',
          'Alemania: explícitamente legal, régimen simplificado establecido (registro único en el MaStR, límite de inversor de 800W)',
          'Estados Unidos: varía según el estado, sin marco federal — consulta la guía dedicada estado por estado',
          'España: ambiguo — fuentes de proveedores y legales en conflicto sobre si existe una exención simplificada',
          'Brasil, México, Golfo/MENA: sin exención para sistemas pequeños — se aplican reglas de interconexión estándar a cualquier tamaño',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'Puntos clave', anchor: '#key-takeaways' },
      { label: 'Panorama global del estado legal', anchor: '#global-status' },
      { label: '¿Qué significa realmente "legal"?', anchor: '#what-legal-means' },
      { label: 'Páginas por país', anchor: '#country-pages' },
      { label: 'Cómo están cambiando estas normas', anchor: '#how-rules-are-changing' },
      { label: 'Preguntas frecuentes', anchor: '#faq' },
      { label: 'Lecturas relacionadas', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'El estado legal va desde un régimen simplificado y codificado (Portugal, Alemania) hasta un auténtico vacío normativo (partes de la región del Golfo/MENA) — no existe una suposición por defecto que sea segura.',
          'Estados Unidos no tiene ningún marco federal — la legalidad depende por completo de cada estado, y la mayoría de los estados aún no han abordado específicamente la energía solar de balcón.',
          'Brasil y México aplican ambos su proceso completo de interconexión estándar sin importar el tamaño del sistema — ninguno de los dos países tiene una excepción para sistemas pequeños.',
          'El estado de España es una auténtica pregunta abierta — las fuentes se contradicen sobre si los kits pequeños obtienen una exención simplificada.',
          'Este seguimiento y cada página de país enlazada se nutren de una única fuente de datos compartida, así que un cambio de estado en un lugar se actualiza de forma consistente en todas partes.',
          'Las normas cambian más rápido en Estados Unidos, donde nuevos estados están aprobando activamente legislación sobre energía solar de balcón — consulta la página dedicada de Estados Unidos para el estado mes a mes actualizado.',
        ],
      },
      globalStatus: {
        id: 'global-status',
        title: 'Panorama global del estado legal',
        content: [
          '**Esta tabla resume el estado legal actual y los límites de potencia en cada mercado que cubre este sitio — haz clic en cada página de país para ver el detalle completo, las fuentes y los pasos de registro.**',
        ],
        rows: statusRows,
        columns: ['country', 'status', 'powerLimit'],
        tableFormat: true,
      },
      whatLegalMeans: {
        id: 'what-legal-means',
        title: '¿Qué significa realmente "legal"?',
        content: [
          '**"Legal" para la energía solar de balcón normalmente significa una de tres cosas distintas, y confundirlas es una fuente habitual de confusión: expresamente permitido bajo un régimen simplificado dedicado con un límite de potencia definido; legal solo en el sentido de que cae bajo las mismas normas que cualquier otro sistema solar conectado a red, sin ninguna vía más ligera; o genuinamente no abordado por la normativa vigente (ni permitido ni prohibido).** Las páginas de país siguientes especifican cuál de estas tres situaciones se aplica a tu mercado, ya que la diferencia práctica — autoinstalación con un formulario sencillo frente a un proceso formal de interconexión completo — es significativa.',
          'Otra cosa que conviene saber antes de comprar: la mayoría del hardware solar de balcón disponible reporta los datos de producción a la nube del fabricante por defecto, sin importar bajo qué régimen legal te encuentres — la monitorización exclusivamente local es la excepción que tienes que buscar específicamente, no algo que puedas dar por hecho. Consulta [cómo usar energía solar de balcón sin la nube](/es/balcony-solar/home-assistant-balcony-solar-no-cloud) si eso te importa.',
        ],
        snippetBlocks: [
          { type: 'one-sentence', text: '"Legal" en energía solar de balcón puede significar desde un régimen simplificado y codificado hasta un auténtico vacío normativo — comprueba cuál se aplica a tu país concreto.' },
          { type: 'plain-terms', text: 'Algunos países han creado una vía especial y sencilla solo para sistemas pequeños que se enchufan. Otros simplemente aplican las mismas normas que una instalación completa en tejado, sin importar lo pequeño que sea tu sistema. Unos pocos no lo han abordado en absoluto.' },
        ],
      },
      countryPages: {
        id: 'country-pages',
        title: 'Páginas por país',
        content: [
          '**Cada mercado siguiente tiene una página dedicada con el detalle legal completo, los pasos de registro y las fuentes.**',
        ],
        links: [
          { url: '/es/balcony-solar/balcony-solar-legal-us-states', title: '¿Es legal la energía solar de balcón en Estados Unidos? Guía estado por estado', description: 'Legislación estatal aprobada y pendiente, actualizada regularmente' },
          { url: '/es/balcony-solar/balkonkraftwerk-germany-rules', title: 'Balkonkraftwerk: las normas de Alemania explicadas', description: 'Límite de 800W, registro en el MaStR y el nuevo estándar DIN VDE V 0126-95' },
          { url: '/es/balcony-solar/balcony-solar-spain-latam', title: 'Energía solar de balcón en España y Latinoamérica', description: 'El estado ambiguo de España explicado' },
          { url: '/es/balcony-solar/balcony-solar-portugal-brazil', title: 'Energía solar de balcón en Portugal y Brasil', description: 'El régimen codificado de Portugal frente al vacío normativo de Brasil' },
          { url: '/es/balcony-solar/balcony-solar-gulf-mena', title: 'Energía solar de balcón en la región del Golfo y MENA', description: 'Regulación incipiente en los Emiratos Árabes Unidos y Arabia Saudita' },
        ],
      },
      howRulesAreChanging: {
        id: 'how-rules-are-changing',
        title: 'Cómo están cambiando estas normas',
        content: [
          '**La legislación estatal de Estados Unidos es la parte que más rápido evoluciona de este panorama — varios estados han aprobado leyes dedicadas a la energía solar de balcón en el último año, y más están avanzando activamente en las legislaturas estatales.** Fuera de Estados Unidos, los cambios son menos frecuentes pero no inexistentes: el estándar de producto alemán DIN VDE V 0126-95 entró en vigor tan recientemente como diciembre de 2025, lo que demuestra que incluso los mercados ya establecidos siguen refinando sus normas.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Preguntas frecuentes',
        faqs: [
          { q: '¿Qué países tienen las leyes de energía solar de balcón más claras?', a: 'Portugal y Alemania tienen ambos regímenes simplificados bien establecidos y codificados, con límites de potencia claros y procesos de registro definidos — el estado más claro de todos los mercados cubiertos aquí.' },
          { q: '¿Es legal la energía solar de balcón en todo Estados Unidos?', a: 'No — no existe ningún marco federal. La legalidad se determina por completo a nivel estatal, y hasta ahora solo un puñado de estados ha aprobado legislación dedicada. Consulta la guía estado por estado para el estado actual.' },
          { q: '¿Algún país prohíbe expresamente la energía solar de balcón?', a: 'Ninguno de los mercados cubiertos en esta guía tiene una prohibición expresa — el estado va desde claramente permitido hasta ambiguo o no abordado, pero no llega a la prohibición total.' },
          { q: '¿Por qué el estado de España figura como ambiguo en lugar de un sí o un no claro?', a: 'Las fuentes se contradicen de verdad — fuentes de proveedores y de prensa afirman que existe una exención simplificada para kits pequeños, mientras que una fuente centrada en el análisis legal detallado dice que todavía se aplican todas las formalidades. Esta guía reporta esa contradicción en lugar de decantarse por un lado sin confirmación.' },
          { q: '¿Brasil y México permiten la energía solar de balcón?', a: 'No está prohibida, pero ninguno de los dos países tiene una exención para sistemas pequeños — se aplica el mismo proceso completo de registro de interconexión sin importar el tamaño del sistema, una situación bastante distinta a la de un régimen simplificado dedicado.' },
          { q: '¿Con qué frecuencia cambia esta información sobre el estado legal?', a: 'Esta página y sus páginas de país enlazadas se actualizan cada 6 meses, aunque la página de estados de Estados Unidos se actualiza más rápido (cada 60 días) dado el ritmo con el que avanza la legislación estatal en ese país.' },
          { q: '¿Qué debo hacer si mi país no aparece aquí?', a: 'Consulta directamente al regulador energético nacional o regional de tu país — esta guía cubre los mercados que este sitio hace seguimiento actualmente, no todos los países del mundo.' },
          { q: '¿Es lo mismo no regulado que legal?', a: 'No necesariamente — una regulación genuinamente no abordada (como en partes de la región del Golfo/MENA) significa que no existe ni permiso expreso ni prohibición, lo cual conlleva un riesgo práctico distinto al de un mercado con un marco legal simplificado y claro.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: '¿Es legal la energía solar de balcón? Guía de estado país por país',
      description: '¿Es legal la energía solar de balcón en tu país? Seguimiento global del estado legal en Estados Unidos, Alemania, España, Portugal, Brasil, México y la región del Golfo/MENA, verificado en julio de 2026.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      inLanguage: 'es',
      author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
      url: 'https://www.promptquorum.com/es/balcony-solar/is-balcony-solar-legal-country-guide',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: 'Compradores potenciales de energía solar de balcón que necesitan confirmar el estado legal antes de comprar' },
      about: ['Legalidad de la energía solar de balcón', 'Regulación solar', 'Steckersolargeräte', 'Ley del solar enchufable'],
    },
  },
  pt: {
    theme: 'Balcony Solar Legislation',
    title: 'A energia solar de varanda é legal? Guia de status por país',
    seoTitle: 'Energia solar de varanda é legal? Guia global de status (2026)',
    intro: 'O status legal da energia solar de varanda varia de um regime simplificado, codificado e bem definido a um verdadeiro vazio regulatório — e essa diferença importa mais do que qualquer ficha técnica antes de você comprar qualquer coisa. Este guia acompanha o status atual em cada mercado importante coberto por este site, com links para o detalhamento completo de cada um.',
    metaDescription: 'A energia solar de varanda é legal no seu país? Painel global de status cobrindo Estados Unidos, Alemanha, Espanha, Portugal, Brasil, México e a região do Golfo/MENA, verificado em julho de 2026.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '9 min de leitura',
    educationalLevel: 'Intermediate',
    audience: 'Potenciais compradores de energia solar de varanda que precisam confirmar o status legal antes de comprar',
    primaryTerm: 'energia solar de varanda é legal',
    targetKeywords: ['energia solar de varanda é legal', 'status legal da energia solar de varanda por país', 'legalidade do solar plug-in', 'onde a energia solar de varanda é legal'],
    leadAnswerBlock: '**O status legal da energia solar de varanda varia enormemente por país: Portugal tem um regime simplificado claramente codificado, a Alemanha tem um regime bem estabelecido, os Estados Unidos variam totalmente por estado sem nenhum marco federal, e Brasil, México e a região do Golfo/MENA atualmente não têm nenhuma isenção dedicada para sistemas pequenos.** Não existe uma suposição padrão segura — confirme o status do seu país específico (e, nos Estados Unidos, do seu estado) antes de comprar.',
    quickAnswerTop: {
      pt: {
        question: 'A energia solar de varanda é legal onde eu moro?',
        answer: 'Depende inteiramente do seu país, e nos EUA, do seu estado. Portugal e Alemanha têm os regimes simplificados mais claros e estabelecidos. Os EUA não têm marco federal — a legalidade é determinada estado por estado, com apenas um punhado de estados tendo aprovado legislação dedicada. Brasil, México e a região do Golfo/MENA não têm isenção para sistemas pequenos; regras de interconexão padrão se aplicam independentemente do tamanho. O status da Espanha é genuinamente ambíguo.',
        bullets: [
          'Portugal: explicitamente legal, regime simplificado codificado para sistemas ≤700W sem exportação para a rede',
          'Alemanha: explicitamente legal, regime simplificado estabelecido (registro único no MaStR, limite de inversor de 800W)',
          'Estados Unidos: varia por estado, sem marco federal — confira o guia dedicado estado por estado',
          'Espanha: ambíguo — fontes de fornecedores e jurídicas em conflito sobre se existe uma isenção simplificada',
          'Brasil, México, Golfo/MENA: sem isenção para sistemas pequenos — regras de interconexão padrão se aplicam a qualquer tamanho',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'Pontos principais', anchor: '#key-takeaways' },
      { label: 'Panorama global de status', anchor: '#global-status' },
      { label: 'O que "legal" realmente significa?', anchor: '#what-legal-means' },
      { label: 'Páginas por país', anchor: '#country-pages' },
      { label: 'Como essas regras estão mudando', anchor: '#how-rules-are-changing' },
      { label: 'Perguntas frequentes', anchor: '#faq' },
      { label: 'Leituras relacionadas', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'O status legal varia de um regime simplificado e codificado (Portugal, Alemanha) a um verdadeiro vazio regulatório (partes da região do Golfo/MENA) — não existe uma suposição padrão segura.',
          'Os Estados Unidos não têm nenhum marco federal — a legalidade é determinada inteiramente por estado, e a maioria dos estados ainda nem abordou especificamente a energia solar de varanda.',
          'Brasil e México aplicam ambos o processo completo padrão de interconexão independentemente do tamanho do sistema — nenhum dos dois países tem uma exceção para sistemas pequenos.',
          'O status da Espanha é uma questão genuinamente em aberto — as fontes se contradizem sobre se kits pequenos recebem uma isenção simplificada.',
          'Este painel e cada página de país vinculada partem de uma única fonte de dados compartilhada, então uma mudança de status em um lugar se atualiza de forma consistente em todos os lugares.',
          'As regras mudam mais rápido nos Estados Unidos, onde novos estados estão aprovando ativamente legislação sobre energia solar de varanda — consulte a página dedicada dos EUA para o status atualizado mês a mês.',
        ],
      },
      globalStatus: {
        id: 'global-status',
        title: 'Panorama global de status',
        content: [
          '**Esta tabela resume o status legal atual e os limites de potência em cada mercado coberto por este site — clique em cada página de país para ver o detalhamento completo, as fontes e as etapas de registro.**',
        ],
        rows: statusRows,
        columns: ['country', 'status', 'powerLimit'],
        tableFormat: true,
      },
      whatLegalMeans: {
        id: 'what-legal-means',
        title: 'O que "legal" realmente significa?',
        content: [
          '**"Legal" para energia solar de varanda geralmente significa uma de três coisas distintas, e confundi-las é uma fonte comum de confusão: expressamente permitido sob um regime simplificado dedicado com um limite de potência definido; legal apenas no sentido de que se enquadra nas mesmas regras de qualquer outro sistema solar conectado à rede, sem nenhum caminho mais simplificado; ou genuinamente não abordado pela regulação vigente (nem permitido nem proibido).** As páginas de país abaixo especificam qual dessas três situações se aplica ao seu mercado, já que a diferença prática — autoinstalação com um formulário simples versus um processo formal completo de interconexão — é significativa.',
          'Mais uma coisa que vale a pena saber antes de comprar: a maioria dos hardwares de energia solar de varanda amplamente disponíveis reporta dados de produção para a nuvem do fabricante por padrão, independentemente do regime legal do seu país — o monitoramento exclusivamente local é a exceção que você precisa procurar especificamente, não o padrão que você pode presumir. Veja [como usar energia solar de varanda sem a nuvem](/pt/balcony-solar/home-assistant-balcony-solar-no-cloud) se isso for importante para você.',
        ],
        snippetBlocks: [
          { type: 'one-sentence', text: '"Legal" para energia solar de varanda pode significar qualquer coisa entre um regime simplificado codificado e um verdadeiro vazio regulatório — verifique qual se aplica ao seu país específico.' },
          { type: 'plain-terms', text: 'Alguns países criaram um caminho especial e mais simples só para sistemas pequenos que se conectam na tomada. Outros simplesmente aplicam as mesmas regras de uma instalação completa no telhado, não importa o quão pequeno seja o seu sistema. Alguns poucos ainda nem trataram do assunto.' },
        ],
      },
      countryPages: {
        id: 'country-pages',
        title: 'Páginas por país',
        content: [
          '**Cada mercado abaixo tem uma página dedicada com o detalhamento legal completo, as etapas de registro e as fontes.**',
        ],
        links: [
          { url: '/pt/balcony-solar/balcony-solar-legal-us-states', title: 'A energia solar de varanda é legal nos EUA? Guia estado por estado', description: 'Legislação estadual assinada e pendente, atualizada regularmente' },
          { url: '/pt/balcony-solar/balkonkraftwerk-germany-rules', title: 'Balkonkraftwerk: as regras da Alemanha explicadas', description: 'Limite de 800W, registro no MaStR e o novo padrão DIN VDE V 0126-95' },
          { url: '/pt/balcony-solar/balcony-solar-spain-latam', title: 'Energia solar de varanda na Espanha e na América Latina', description: 'O status ambíguo da Espanha explicado' },
          { url: '/pt/balcony-solar/balcony-solar-portugal-brazil', title: 'Energia solar de varanda em Portugal e no Brasil', description: 'O regime codificado de Portugal versus o vazio regulatório do Brasil' },
          { url: '/pt/balcony-solar/balcony-solar-gulf-mena', title: 'Energia solar de varanda na região do Golfo e MENA', description: 'Regulação nascente nos Emirados Árabes Unidos e na Arábia Saudita' },
        ],
      },
      howRulesAreChanging: {
        id: 'how-rules-are-changing',
        title: 'Como essas regras estão mudando',
        content: [
          '**A legislação estadual dos Estados Unidos é a parte que muda mais rápido nesse cenário — vários estados assinaram leis dedicadas à energia solar de varanda no último ano, e mais estados estão avançando ativamente nas legislaturas estaduais.** Fora dos Estados Unidos, as mudanças são menos frequentes, mas não inexistentes: o padrão de produto alemão DIN VDE V 0126-95 entrou em vigor recentemente, em dezembro de 2025, mostrando que até mercados já estabelecidos continuam refinando suas regras.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Perguntas frequentes',
        faqs: [
          { q: 'Quais países têm as leis de energia solar de varanda mais claras?', a: 'Portugal e Alemanha têm ambos regimes simplificados bem estabelecidos e codificados, com limites de potência claros e processos de registro definidos — o status mais claro entre todos os mercados cobertos aqui.' },
          { q: 'A energia solar de varanda é legal em todos os lugares dos EUA?', a: 'Não — não existe nenhum marco federal. A legalidade é determinada inteiramente em nível estadual, e até agora apenas um punhado de estados aprovou legislação dedicada. Veja o guia estado por estado para o status atual.' },
          { q: 'Algum país proíbe expressamente a energia solar de varanda?', a: 'Nenhum dos mercados cobertos neste guia tem uma proibição expressa — o status varia de claramente permitido a ambíguo ou não abordado, mas não chega à proibição total.' },
          { q: 'Por que o status da Espanha está listado como ambíguo em vez de um sim ou não claro?', a: 'As fontes realmente se contradizem — fontes de fornecedores e de imprensa afirmam que existe uma isenção simplificada para kits pequenos, enquanto uma fonte focada em análise jurídica detalhada diz que ainda se aplicam todas as formalidades. Este guia reporta essa contradição em vez de tomar partido sem confirmação.' },
          { q: 'Brasil e México permitem a energia solar de varanda?', a: 'Não é proibida, mas nenhum dos dois países tem uma isenção para sistemas pequenos — aplica-se o mesmo processo completo de registro de interconexão independentemente do tamanho do sistema, uma situação bem diferente de um regime simplificado dedicado.' },
          { q: 'Com que frequência essa informação de status legal muda?', a: 'Esta página e suas páginas de país vinculadas seguem um ciclo de atualização de 6 meses, embora a página de estados dos EUA seja atualizada mais rápido (60 dias), dado o ritmo com que a legislação estadual americana está avançando.' },
          { q: 'O que devo fazer se meu país não estiver listado aqui?', a: 'Consulte diretamente o regulador de energia nacional ou regional do seu país — este guia cobre os mercados que este site atualmente acompanha, não todos os países do mundo.' },
          { q: 'Não regulamentado é o mesmo que legal?', a: 'Não necessariamente — uma regulação genuinamente não abordada (como em partes da região do Golfo/MENA) significa que não existe nem permissão expressa nem proibição, o que traz um risco prático diferente de um mercado com um marco legal simplificado e claro.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'A energia solar de varanda é legal? Guia de status por país',
      description: 'A energia solar de varanda é legal no seu país? Painel global de status cobrindo Estados Unidos, Alemanha, Espanha, Portugal, Brasil, México e a região do Golfo/MENA, verificado em julho de 2026.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      inLanguage: 'pt-BR',
      author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
      url: 'https://www.promptquorum.com/pt/balcony-solar/is-balcony-solar-legal-country-guide',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: 'Potenciais compradores de energia solar de varanda que precisam confirmar o status legal antes de comprar' },
      about: ['Legalidade da energia solar de varanda', 'Regulação solar', 'Steckersolargeräte', 'Lei do solar plug-in'],
    },
  },
  ar: {
    theme: 'Balcony Solar Legislation',
    title: 'هل الطاقة الشمسية للشرفة قانونية؟ دليل الوضع القانوني حسب الدولة',
    seoTitle: 'هل الطاقة الشمسية للشرفة قانونية؟ دليل الوضع العالمي (2026)',
    intro: 'يتراوح الوضع القانوني للطاقة الشمسية للشرفة بين نظام مبسّط مقنَّن وواضح المعالم وبين فراغ تنظيمي حقيقي — وهذا الفرق أهم من أي مواصفات تقنية قبل أن تشتري أي شيء. يتتبّع هذا الدليل الوضع الحالي في كل سوق رئيسي يغطيه هذا الموقع، مع روابط للتفاصيل الكاملة لكل دولة.',
    metaDescription: 'هل الطاقة الشمسية للشرفة قانونية في بلدك؟ متتبّع عالمي للوضع القانوني يغطي الولايات المتحدة وألمانيا وإسبانيا والبرتغال والبرازيل والمكسيك ومنطقة الخليج وشمال أفريقيا (MENA)، تم التحقق منه في يوليو 2026.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: 'قراءة 9 دقائق',
    educationalLevel: 'Intermediate',
    audience: 'مشترون محتملون للطاقة الشمسية للشرفة يحتاجون إلى تأكيد الوضع القانوني قبل الشراء',
    primaryTerm: 'هل الطاقة الشمسية للشرفة قانونية',
    targetKeywords: ['هل الطاقة الشمسية للشرفة قانونية', 'الوضع القانوني للطاقة الشمسية للشرفة حسب الدولة', 'شرعية الطاقة الشمسية القابلة للتوصيل المباشر', 'أين تكون الطاقة الشمسية للشرفة قانونية'],
    leadAnswerBlock: '**يختلف الوضع القانوني للطاقة الشمسية للشرفة اختلافًا كبيرًا حسب الدولة: البرتغال لديها نظام مبسّط مقنَّن بوضوح، وألمانيا لديها نظام راسخ جيدًا، والولايات المتحدة تختلف كليًا حسب الولاية دون أي إطار فيدرالي، بينما لا تملك البرازيل والمكسيك ومنطقة الخليج وشمال أفريقيا حاليًا أي إعفاء مخصص للأنظمة الصغيرة.** لا يوجد افتراض افتراضي آمن — تحقّق من وضع بلدك تحديدًا (وفي الولايات المتحدة، من وضع ولايتك) قبل الشراء.',
    quickAnswerTop: {
      ar: {
        question: 'هل الطاقة الشمسية للشرفة قانونية في مكان إقامتي؟',
        answer: 'يعتمد الأمر كليًا على دولتك، وفي الولايات المتحدة، على ولايتك. تمتلك البرتغال وألمانيا أوضح الأنظمة المبسّطة وأكثرها رسوخًا. لا تملك الولايات المتحدة إطارًا فيدراليًا — تُحدَّد القانونية ولاية بولاية، مع عدد قليل فقط من الولايات التي أقرت تشريعات مخصصة. لا تملك البرازيل والمكسيك ومنطقة الخليج وشمال أفريقيا إعفاءً للأنظمة الصغيرة؛ تنطبق قواعد الربط الشبكي القياسية بغض النظر عن الحجم. وضع إسبانيا غامض فعليًا.',
        bullets: [
          'البرتغال: قانونية صراحةً، نظام مبسّط مقنَّن للأنظمة ≤700W بدون تصدير إلى الشبكة',
          'ألمانيا: قانونية صراحةً، نظام مبسّط راسخ (تسجيل واحد في MaStR، حد عاكس 800 واط)',
          'الولايات المتحدة: تختلف حسب الولاية، دون إطار فيدرالي — راجع الدليل المخصص لكل ولاية',
          'إسبانيا: غامضة — تضارب بين مصادر الموردين والمصادر القانونية حول وجود إعفاء مبسّط',
          'البرازيل والمكسيك والخليج/شمال أفريقيا: لا يوجد إعفاء للأنظمة الصغيرة — تنطبق قواعد الربط الشبكي القياسية على أي حجم',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'النقاط الرئيسية', anchor: '#key-takeaways' },
      { label: 'نظرة عامة على الوضع القانوني عالميًا', anchor: '#global-status' },
      { label: 'ماذا تعني "قانونية" فعليًا؟', anchor: '#what-legal-means' },
      { label: 'صفحات الدول', anchor: '#country-pages' },
      { label: 'كيف تتغير هذه القواعد', anchor: '#how-rules-are-changing' },
      { label: 'الأسئلة الشائعة', anchor: '#faq' },
      { label: 'قراءات ذات صلة', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'يتراوح الوضع القانوني بين نظام مبسّط ومقنَّن (البرتغال، ألمانيا) وبين فراغ تنظيمي حقيقي (أجزاء من منطقة الخليج وشمال أفريقيا) — لا يوجد افتراض افتراضي آمن.',
          'لا تملك الولايات المتحدة أي إطار فيدرالي — يُحدَّد الوضع القانوني بالكامل على مستوى الولاية، ومعظم الولايات لم تتناول الطاقة الشمسية للشرفة تحديدًا حتى الآن.',
          'تطبّق كل من البرازيل والمكسيك عملية الربط بالشبكة الكاملة المعتادة بغض النظر عن حجم النظام — لا يوجد استثناء للأنظمة الصغيرة في أي من البلدين.',
          'وضع إسبانيا سؤال مفتوح حقًا — تتضارب المصادر حول ما إذا كانت الأطقم الصغيرة تحصل على إعفاء مبسّط.',
          'يعتمد هذا المتتبّع وكل صفحة دولة مرتبطة به على مصدر بيانات واحد مشترك، لذا فإن أي تغيير في الوضع في مكان واحد يُحدَّث بشكل متسق في كل مكان.',
          'تتغير القواعد بأسرع وتيرة في الولايات المتحدة، حيث تُقرّ ولايات جديدة بنشاط تشريعات خاصة بالطاقة الشمسية للشرفة — راجع صفحة الولايات المتحدة المخصصة للاطلاع على الوضع المحدَّث شهريًا.',
        ],
      },
      globalStatus: {
        id: 'global-status',
        title: 'نظرة عامة على الوضع القانوني عالميًا',
        content: [
          '**يلخّص هذا الجدول الوضع القانوني الحالي وحدود القدرة في كل سوق يغطيه هذا الموقع — انقر على كل صفحة دولة للاطلاع على التفاصيل الكاملة والمصادر وخطوات التسجيل.**',
        ],
        rows: statusRows,
        columns: ['country', 'status', 'powerLimit'],
        tableFormat: true,
      },
      whatLegalMeans: {
        id: 'what-legal-means',
        title: 'ماذا تعني "قانونية" فعليًا؟',
        content: [
          '**"قانونية" بالنسبة للطاقة الشمسية للشرفة تعني عادة أحد ثلاثة أمور مختلفة، والخلط بينها مصدر شائع للالتباس: مسموح بها صراحةً بموجب نظام مبسّط مخصص بحد أقصى محدد للقدرة؛ أو قانونية فقط بمعنى أنها تخضع لنفس القواعد المطبَّقة على أي نظام شمسي آخر متصل بالشبكة دون أي مسار أخف؛ أو غير مُتناوَلة فعليًا في التنظيم الحالي (لا مسموح بها ولا محظورة).** تحدد صفحات الدول أدناه أي هذه الحالات الثلاث ينطبق على سوقك، لأن الفرق العملي — التركيب الذاتي بنموذج بسيط مقابل عملية ربط شبكي رسمية كاملة — فرق كبير.',
          'أمر آخر يستحق معرفته قبل الشراء: تُرسِل معظم أجهزة الطاقة الشمسية للشرفة المتاحة على نطاق واسع بيانات الإنتاج إلى سحابة الشركة المصنّعة بشكل افتراضي، بغض النظر عن النظام القانوني في بلدك — المراقبة المحلية فقط هي الاستثناء الذي يجب أن تبحث عنه تحديدًا، وليست الوضع الافتراضي الذي يمكنك افتراضه. راجع [تشغيل الطاقة الشمسية للشرفة دون الاعتماد على السحابة](/ar/balcony-solar/home-assistant-balcony-solar-no-cloud) إذا كان ذلك مهمًا بالنسبة لك.',
        ],
        snippetBlocks: [
          { type: 'one-sentence', text: 'يمكن أن تعني "قانونية" بالنسبة للطاقة الشمسية للشرفة أي شيء بين نظام مبسّط مقنَّن وفراغ تنظيمي حقيقي — تحقق مما ينطبق على بلدك تحديدًا.' },
          { type: 'plain-terms', text: 'بعض الدول أنشأت مسارًا خاصًا وسهلًا فقط للأنظمة الصغيرة التي تُوصَل بالمقبس. دول أخرى تطبّق ببساطة نفس قواعد التركيب الكامل على السطح، بغض النظر عن صغر حجم نظامك. قلة من الدول لم تتناول الموضوع إطلاقًا.' },
        ],
      },
      countryPages: {
        id: 'country-pages',
        title: 'صفحات الدول',
        content: [
          '**لكل سوق أدناه صفحة مخصصة تتضمن التفاصيل القانونية الكاملة وخطوات التسجيل والمصادر.**',
        ],
        links: [
          { url: '/ar/balcony-solar/balcony-solar-legal-us-states', title: 'هل الطاقة الشمسية للشرفة قانونية في الولايات المتحدة؟ دليل حسب الولاية', description: 'تشريعات الولايات الموقَّعة والمعلَّقة، تُحدَّث بانتظام' },
          { url: '/ar/balcony-solar/balkonkraftwerk-germany-rules', title: 'Balkonkraftwerk: شرح قواعد ألمانيا', description: 'حد 800 واط، والتسجيل في MaStR، والمعيار الجديد DIN VDE V 0126-95' },
          { url: '/ar/balcony-solar/balcony-solar-spain-latam', title: 'الطاقة الشمسية للشرفة في إسبانيا وأمريكا اللاتينية', description: 'شرح وضع إسبانيا الغامض' },
          { url: '/ar/balcony-solar/balcony-solar-portugal-brazil', title: 'الطاقة الشمسية للشرفة في البرتغال والبرازيل', description: 'النظام المقنَّن في البرتغال مقابل الفراغ التنظيمي في البرازيل' },
          { url: '/ar/balcony-solar/balcony-solar-gulf-mena', title: 'الطاقة الشمسية للشرفة في منطقة الخليج وشمال أفريقيا', description: 'تنظيم ناشئ في الإمارات العربية المتحدة والمملكة العربية السعودية' },
        ],
      },
      howRulesAreChanging: {
        id: 'how-rules-are-changing',
        title: 'كيف تتغير هذه القواعد',
        content: [
          '**تُعد تشريعات الولايات الأمريكية الجزء الأسرع تغيرًا في هذا المشهد — أقرّت عدة ولايات مشاريع قوانين مخصصة للطاقة الشمسية للشرفة خلال العام الماضي، والمزيد يتقدم بنشاط عبر الهيئات التشريعية للولايات.** خارج الولايات المتحدة، التغييرات أقل تواترًا لكنها ليست غائبة: دخل معيار المنتج الألماني DIN VDE V 0126-95 حيز التنفيذ مؤخرًا في ديسمبر 2025، ما يُظهر أن حتى الأسواق الراسخة تواصل تنقيح قواعدها.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'الأسئلة الشائعة',
        faqs: [
          { q: 'أي الدول لديها أوضح قوانين للطاقة الشمسية للشرفة؟', a: 'كل من البرتغال وألمانيا لديهما نظام مبسّط راسخ ومقنَّن بحدود قدرة واضحة وعمليات تسجيل محددة — أوضح وضع بين جميع الأسواق المشمولة هنا.' },
          { q: 'هل الطاقة الشمسية للشرفة قانونية في كل أنحاء الولايات المتحدة؟', a: 'لا — لا يوجد إطار فيدرالي. يُحدَّد الوضع القانوني بالكامل على مستوى الولاية، وحتى الآن أقرّ عدد قليل فقط من الولايات تشريعات مخصصة. راجع الدليل حسب الولاية للاطلاع على الوضع الحالي.' },
          { q: 'هل تحظر أي دولة الطاقة الشمسية للشرفة صراحةً؟', a: 'لا يوجد حظر صريح في أي من الأسواق المشمولة في هذا الدليل — يتراوح الوضع بين مسموح به بوضوح وغامض أو غير مُتناوَل، لكن دون وصول إلى حظر تام.' },
          { q: 'لماذا يُدرَج وضع إسبانيا كغامض بدلاً من نعم أو لا واضحة؟', a: 'تتضارب المصادر فعليًا — تزعم مصادر من الموردين والصحافة وجود إعفاء مبسّط للأطقم الصغيرة، بينما يقول مصدر متخصص في التحليل القانوني المفصّل إن جميع الإجراءات الرسمية لا تزال مطلوبة. يورد هذا الدليل هذا التضارب بدلًا من الانحياز لأحد الطرفين دون تأكيد.' },
          { q: 'هل تسمح البرازيل والمكسيك بالطاقة الشمسية للشرفة؟', a: 'ليست محظورة، لكن لا يملك أي من البلدين إعفاءً للأنظمة الصغيرة — تُطبَّق نفس عملية تسجيل الربط بالشبكة الكاملة بغض النظر عن حجم النظام، وهو وضع مختلف جوهريًا عن نظام مبسّط مخصص.' },
          { q: 'كم مرة تتغير معلومات الوضع القانوني هذه؟', a: 'تخضع هذه الصفحة وصفحات الدول المرتبطة بها لدورة تحديث كل 6 أشهر، رغم أن صفحة ولايات الولايات المتحدة تُحدَّث بوتيرة أسرع (كل 60 يومًا) نظرًا لسرعة تطور تشريعات الولايات الأمريكية.' },
          { q: 'ماذا أفعل إذا لم تكن دولتي مُدرَجة هنا؟', a: 'راجع الجهة التنظيمية للطاقة الوطنية أو الإقليمية في بلدك مباشرةً — يغطي هذا الدليل الأسواق التي يتتبعها هذا الموقع حاليًا، وليس كل دولة في العالم.' },
          { q: 'هل غير المنظَّم يعني نفس معنى القانوني؟', a: 'ليس بالضرورة — التنظيم غير المُتناوَل فعليًا (كما في أجزاء من منطقة الخليج وشمال أفريقيا) يعني عدم وجود إذن صريح أو حظر، وهو ما يحمل مخاطر عملية مختلفة عن سوق لديه إطار قانوني مبسّط وواضح.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'هل الطاقة الشمسية للشرفة قانونية؟ دليل الوضع القانوني حسب الدولة',
      description: 'هل الطاقة الشمسية للشرفة قانونية في بلدك؟ متتبّع عالمي للوضع القانوني يغطي الولايات المتحدة وألمانيا وإسبانيا والبرتغال والبرازيل والمكسيك ومنطقة الخليج وشمال أفريقيا (MENA)، تم التحقق منه في يوليو 2026.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      inLanguage: 'ar',
      author: { '@type': 'Organization', name: 'PromptQuorum' },
      url: 'https://www.promptquorum.com/ar/balcony-solar/is-balcony-solar-legal-country-guide',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: 'مشترون محتملون للطاقة الشمسية للشرفة يحتاجون إلى تأكيد الوضع القانوني قبل الشراء' },
      about: ['شرعية الطاقة الشمسية للشرفة', 'تنظيم الطاقة الشمسية', 'Steckersolargeräte', 'قانون الطاقة الشمسية القابلة للتوصيل المباشر'],
    },
  },
  ja: {
    theme: 'Balcony Solar Legislation',
    title: 'バルコニーソーラーは合法か? 国別法的ステータスガイド',
    seoTitle: 'バルコニーソーラーは合法か? グローバルステータスガイド (2026年)',
    intro: 'バルコニーソーラーの法的ステータスは、明確に成文化された簡易制度から、実質的に規制が存在しない状態まで幅広く異なります——そしてこの違いは、購入前にはどんなスペック表よりも重要です。本ガイドでは、当サイトが扱う主要な市場すべての現在のステータスを追跡し、各国の詳細情報へのリンクを掲載しています。',
    metaDescription: 'あなたの国でバルコニーソーラーは合法ですか? アメリカ、ドイツ、スペイン、ポルトガル、ブラジル、メキシコ、湾岸・中東北アフリカ(MENA)地域の法的ステータスをカバーするグローバルトラッカー。2026年7月に検証済み。',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '約9分',
    educationalLevel: 'Intermediate',
    audience: '購入前に法的ステータスを確認する必要があるバルコニーソーラー購入検討者',
    primaryTerm: 'バルコニーソーラー 合法',
    targetKeywords: ['バルコニーソーラー 合法', '国別バルコニーソーラー法的ステータス', 'プラグイン太陽光発電の合法性', 'バルコニーソーラーが合法な国'],
    leadAnswerBlock: '**バルコニーソーラーの法的ステータスは国によって大きく異なります。ポルトガルには明確に成文化された簡易制度があり、ドイツには確立された制度があります。アメリカには連邦レベルの枠組みが存在せず、州ごとに完全に異なります。ブラジル、メキシコ、湾岸・MENA地域には現時点で小規模システム向けの専用の適用除外が一切ありません。** 安全に前提とできるデフォルトのルールは存在しません——購入前に、あなたの国(アメリカの場合は州)固有のステータスを必ず確認してください。',
    quickAnswerTop: {
      ja: {
        question: 'バルコニーソーラーは私が住んでいる場所で合法ですか?',
        answer: '完全にあなたの国次第であり、アメリカの場合は州次第です。ポルトガルとドイツには、最も明確で確立された簡易制度があります。アメリカには連邦の枠組みがなく、合法性は州ごとに決定され、専用の法律を制定した州はごく一部にとどまります。ブラジル、メキシコ、湾岸・MENA地域には小規模システム向けの適用除外がなく、規模にかかわらず標準的な系統連系ルールが適用されます。スペインのステータスは実質的にあいまいです。',
        bullets: [
          'ポルトガル: 明確に合法。系統への逆潮流なし・700W以下のシステム向けに成文化された簡易制度あり',
          'ドイツ: 明確に合法。確立された簡易制度あり(MaStRへの登録のみ、インバーター上限800W)',
          'アメリカ: 州によって異なり、連邦の枠組みはなし——専用の州別ガイドを確認',
          'スペイン: あいまい——簡易的な適用除外が存在するかどうかについて、販売元情報と法律情報が食い違う',
          'ブラジル、メキシコ、湾岸・MENA: 小規模システム向けの適用除外なし——規模を問わず標準的な系統連系ルールが適用される',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: '重要ポイント', anchor: '#key-takeaways' },
      { label: '世界の法的ステータス概観', anchor: '#global-status' },
      { label: '「合法」とは実際には何を意味するのか?', anchor: '#what-legal-means' },
      { label: '国別ページ', anchor: '#country-pages' },
      { label: 'これらのルールはどう変化しているか', anchor: '#how-rules-are-changing' },
      { label: 'よくある質問', anchor: '#faq' },
      { label: '関連記事', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          '法的ステータスは、成文化された簡易制度(ポルトガル、ドイツ)から、実質的な規制の空白(湾岸・MENA地域の一部)まで幅広く、安全に前提とできるデフォルトは存在しない。',
          'アメリカには連邦レベルの枠組みがなく、合法性は完全に州単位で決定される。ほとんどの州はバルコニーソーラーについて具体的にはまだ何も定めていない。',
          'ブラジルとメキシコはいずれも、システムの規模にかかわらず標準的な完全系統連系プロセスを適用する。両国とも小規模システム向けの例外規定は存在しない。',
          'スペインのステータスは本当に未解決の問題である——小型キットに簡易的な適用除外が認められるかどうかについて、情報源が食い違っている。',
          '本トラッカーおよびリンク先の各国ページはすべて単一の共有データソースを参照しているため、1か所でステータスが変更されれば、すべてのページに一貫して反映される。',
          'ルールが最も速く変化しているのはアメリカで、新たな州が積極的にバルコニーソーラー関連の法律を制定している——最新の月次ステータスは専用のアメリカページで確認できる。',
        ],
      },
      globalStatus: {
        id: 'global-status',
        title: '世界の法的ステータス概観',
        content: [
          '**この表は、当サイトが扱うすべての市場における現在の法的ステータスと出力制限をまとめたものです——各国ページをクリックすると、詳細情報、情報源、登録手順を確認できます。**',
        ],
        rows: statusRows,
        columns: ['country', 'status', 'powerLimit'],
        tableFormat: true,
      },
      whatLegalMeans: {
        id: 'what-legal-means',
        title: '「合法」とは実際には何を意味するのか?',
        content: [
          '**バルコニーソーラーにおける「合法」は通常、次の3つの異なる状態のいずれかを意味し、これらを混同することがよくある混乱の原因になります。定義された出力制限を伴う専用の簡易制度のもとで明示的に許可されている状態、他の系統連系型太陽光発電システムと同じ規則が適用されるだけで簡易な手続きは存在しないという意味での「合法」、そして現行の規制で実質的に扱われていない(許可も禁止もされていない)状態です。** 実務上の違い——簡単な様式での自己設置か、正式な系統連系プロセス全体か——は大きいため、以下の国別ページでは、あなたの市場がこの3つのうちどれに該当するかを明記しています。',
          '購入前に知っておく価値があるもう一つの点: 広く入手可能なバルコニーソーラー機器のほとんどは、どの国の法制度下にあるかにかかわらず、デフォルトで発電データをメーカーのクラウドに送信します——ローカルのみの監視は、当然のものとして前提できるデフォルトではなく、特に探さなければならない例外です。これが気になる場合は、[クラウドを使わずにバルコニーソーラーを運用する方法](/ja/balcony-solar/home-assistant-balcony-solar-no-cloud)を参照してください。',
        ],
        snippetBlocks: [
          { type: 'one-sentence', text: '「合法」なバルコニーソーラーは、成文化された簡易制度から実質的な規制の空白まで意味しうる——自分の国にどちらが当てはまるか確認しよう。' },
          { type: 'plain-terms', text: '一部の国では、小型のプラグイン式システム専用に特別で簡単な手続きが用意されている。他の国では、システムがどれほど小さくても、屋根全体への設置と同じ規則がそのまま適用される。いくつかの国はこの問題自体をまだ扱っていない。' },
        ],
      },
      countryPages: {
        id: 'country-pages',
        title: '国別ページ',
        content: [
          '**以下の各市場には、詳細な法的情報、登録手順、情報源をまとめた専用ページがあります。**',
        ],
        links: [
          { url: '/ja/balcony-solar/balcony-solar-legal-us-states', title: 'アメリカでバルコニーソーラーは合法か? 州別ガイド', description: '成立済みおよび審議中の州法、随時更新' },
          { url: '/ja/balcony-solar/balkonkraftwerk-germany-rules', title: 'Balkonkraftwerk: ドイツのルール解説', description: '800Wの上限、MaStR登録、新しいDIN VDE V 0126-95規格' },
          { url: '/ja/balcony-solar/balcony-solar-spain-latam', title: 'スペイン・ラテンアメリカのバルコニーソーラー', description: 'スペインのあいまいなステータスを解説' },
          { url: '/ja/balcony-solar/balcony-solar-portugal-brazil', title: 'ポルトガル・ブラジルのバルコニーソーラー', description: 'ポルトガルの成文化された制度とブラジルの規制の空白の対比' },
          { url: '/ja/balcony-solar/balcony-solar-gulf-mena', title: '湾岸・MENA地域のバルコニーソーラー', description: 'UAEとサウジアラビアにおける新興の規制' },
        ],
      },
      howRulesAreChanging: {
        id: 'how-rules-are-changing',
        title: 'これらのルールはどう変化しているか',
        content: [
          '**アメリカの州法は、この分野で最も急速に変化している部分です——過去1年間で複数の州が専用のバルコニーソーラー法案に署名しており、さらに多くの州議会で審議が進んでいます。** アメリカ以外では変化の頻度は低いものの、皆無ではありません。ドイツのDIN VDE V 0126-95製品規格は2025年12月というごく最近発効しており、確立された市場でさえルールの改良を続けていることを示しています。',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'よくある質問',
        faqs: [
          { q: 'バルコニーソーラーの法律が最も明確な国はどこですか?', a: 'ポルトガルとドイツはいずれも、明確な出力制限と登録プロセスを備えた、確立され成文化された簡易制度を持っています——ここで扱う市場の中で最も明確なステータスです。' },
          { q: 'アメリカ全土でバルコニーソーラーは合法ですか?', a: 'いいえ——連邦レベルの枠組みは存在しません。合法性は完全に州レベルで決定され、これまでのところ専用の法律を制定した州はごく一部です。最新のステータスは州別ガイドを参照してください。' },
          { q: 'バルコニーソーラーを明示的に禁止している国はありますか?', a: '本ガイドで扱う市場の中に明示的な禁止を設けている国はありません——ステータスは明確に許可されている状態からあいまい、未対応まで幅がありますが、完全な禁止には至っていません。' },
          { q: 'なぜスペインのステータスは明確な「はい」または「いいえ」ではなく、あいまいと記載されているのですか?', a: '情報源が実際に食い違っているためです。販売元や報道系の情報源は小型キット向けの簡易的な適用除外があると主張する一方、詳細な法律分析に基づく情報源は、依然として正式な手続き全体が必要だとしています。本ガイドは確認が取れないまま一方に肩入れするのではなく、この食い違いをそのまま報告しています。' },
          { q: 'ブラジルとメキシコはバルコニーソーラーを認めていますか?', a: '禁止はされていませんが、両国とも小規模システム向けの適用除外はありません——システムの規模にかかわらず、通常の系統連系登録プロセス全体が適用されます。これは専用の簡易制度がある場合とは大きく異なる状況です。' },
          { q: 'この法的ステータス情報はどのくらいの頻度で更新されますか?', a: 'このページとリンク先の各国ページは6か月ごとの更新サイクルにありますが、アメリカの州別ページはアメリカの州法の動きが速いため、より早いペース(60日ごと)で更新されます。' },
          { q: '自分の国がここに掲載されていない場合はどうすればよいですか?', a: 'あなたの国・地域のエネルギー規制当局に直接確認してください——本ガイドは当サイトが現在追跡している市場を扱っており、世界のすべての国を網羅しているわけではありません。' },
          { q: '「未規制」は「合法」と同じ意味ですか?', a: '必ずしもそうではありません——実質的に未対応の規制(湾岸・MENA地域の一部など)は、明示的な許可も禁止も存在しないことを意味し、明確な簡易的法制度がある市場とは異なる実務上のリスクを伴います。' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'バルコニーソーラーは合法か? 国別法的ステータスガイド',
      description: 'あなたの国でバルコニーソーラーは合法ですか? アメリカ、ドイツ、スペイン、ポルトガル、ブラジル、メキシコ、湾岸・中東北アフリカ(MENA)地域の法的ステータスをカバーするグローバルトラッカー。2026年7月に検証済み。',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      inLanguage: 'ja',
      author: { '@type': 'Organization', name: 'PromptQuorum' },
      url: 'https://www.promptquorum.com/ja/balcony-solar/is-balcony-solar-legal-country-guide',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: '購入前に法的ステータスを確認する必要があるバルコニーソーラー購入検討者' },
      about: ['バルコニーソーラーの合法性', '太陽光発電規制', 'Steckersolargeräte', 'プラグイン式太陽光発電法'],
    },
  },
  zh: {
    theme: 'Balcony Solar Legislation',
    title: '阳台光伏合法吗?各国法律状态指南',
    seoTitle: '阳台光伏合法吗?全球状态指南(2026年)',
    intro: '阳台光伏的法律状态差异很大,从明确成文、定义清晰的简化制度,到真正的监管空白——在购买任何设备之前,这种差异比任何规格表都更重要。本指南追踪本站覆盖的每个主要市场的当前状态,并提供各国详细信息的链接。',
    metaDescription: '你所在的国家阳台光伏合法吗?全球状态追踪,涵盖美国、德国、西班牙、葡萄牙、巴西、墨西哥以及海湾/中东北非(MENA)地区,截至2026年7月核实。',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '约9分钟',
    educationalLevel: 'Intermediate',
    audience: '需要在购买前确认法律状态的阳台光伏潜在买家',
    primaryTerm: '阳台光伏合法吗',
    targetKeywords: ['阳台光伏合法吗', '各国阳台光伏法律状态', '插座式光伏合法性', '哪些国家阳台光伏合法'],
    leadAnswerBlock: '**阳台光伏的法律状态因国家而异,差异巨大:葡萄牙有明确成文的简化制度,德国有成熟稳定的制度,美国完全因州而异且没有联邦框架,而巴西、墨西哥和海湾/MENA地区目前完全没有针对小型系统的专门豁免。** 没有可以安全套用的默认假设——购买前请务必确认你所在国家(在美国则是所在州)的具体状态。',
    quickAnswerTop: {
      zh: {
        question: '我所在的地方阳台光伏合法吗?',
        answer: '这完全取决于你所在的国家,在美国则取决于所在州。葡萄牙和德国拥有最清晰、最成熟的简化制度。美国没有联邦框架——合法性由各州自行决定,目前只有少数几个州通过了专门立法。巴西、墨西哥和海湾/MENA地区没有小型系统豁免;无论系统大小,都适用标准并网规则。西班牙的状态确实存在争议。',
        bullets: [
          '葡萄牙:明确合法,针对功率≤700W且不并网上传的系统有成文的简化制度',
          '德国:明确合法,拥有成熟的简化制度(仅需在MaStR注册,逆变器上限800W)',
          '美国:因州而异,没有联邦框架——请查看专门的各州指南',
          '西班牙:状态不明——供应商与法律来源在是否存在简化豁免上说法相互矛盾',
          '巴西、墨西哥、海湾/MENA地区:没有小型系统豁免——无论规模大小都适用标准并网规则',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: '关键要点', anchor: '#key-takeaways' },
      { label: '全球状态概览', anchor: '#global-status' },
      { label: '"合法"到底意味着什么?', anchor: '#what-legal-means' },
      { label: '各国专页', anchor: '#country-pages' },
      { label: '这些规则如何变化', anchor: '#how-rules-are-changing' },
      { label: '常见问题', anchor: '#faq' },
      { label: '相关阅读', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          '法律状态从成文的简化制度(葡萄牙、德国)到真正的监管空白(海湾/MENA部分地区)不等——没有可以安全套用的默认假设。',
          '美国没有联邦框架——合法性完全由各州决定,大多数州目前都尚未专门针对阳台光伏立法。',
          '巴西和墨西哥都对所有规模的系统适用标准的完整并网流程——两国均不存在针对小型系统的例外条款。',
          '西班牙的状态确实是一个悬而未决的问题——各方信息来源在小型套件是否享有简化豁免上意见不一。',
          '本追踪页面及其链接的每个国家专页都取自同一个共享数据源,因此一处状态变更会在所有页面同步一致地更新。',
          '规则变化最快的是美国,新的州正在积极通过阳台光伏相关立法——请查看专门的美国专页获取按月更新的最新状态。',
        ],
      },
      globalStatus: {
        id: 'global-status',
        title: '全球状态概览',
        content: [
          '**下表汇总了本站覆盖的每个市场当前的法律状态和功率限制——点击进入各国专页可查看完整细节、信息来源和注册步骤。**',
        ],
        rows: statusRows,
        columns: ['country', 'status', 'powerLimit'],
        tableFormat: true,
      },
      whatLegalMeans: {
        id: 'what-legal-means',
        title: '"合法"到底意味着什么?',
        content: [
          '**对阳台光伏而言,"合法"通常指以下三种截然不同情形之一,而把它们混为一谈是常见的困惑来源:在设有明确功率上限的专门简化制度下被明确允许;仅在与其他任何并网光伏系统适用相同规则这一意义上"合法",不存在任何更简便的路径;或是现行法规确实尚未涉及(既不允许也不禁止)。** 由于实际差异——用简单表格自行安装,与走完整的正式并网流程——非常显著,下方各国专页会具体说明你所在市场属于这三种情形中的哪一种。',
          '在购买之前还有一点值得了解:大多数广泛销售的阳台光伏硬件,无论你所在国家的法律制度如何,默认都会将发电数据上传到制造商的云端——仅限本地的监控是需要专门寻找的例外,而不能默认存在。如果这对你很重要,请参阅[不依赖云端运行阳台光伏系统](/zh/balcony-solar/home-assistant-balcony-solar-no-cloud)。',
        ],
        snippetBlocks: [
          { type: 'one-sentence', text: '阳台光伏的"合法"可能意味着从成文简化制度到真正监管空白之间的任何情况——请核实你所在国家具体适用哪一种。' },
          { type: 'plain-terms', text: '一些国家专门为小型插座式系统开辟了特殊、简便的通道。另一些国家则不管系统多小,都套用与整套屋顶安装相同的规则。还有少数国家根本没有涉及这个问题。' },
        ],
      },
      countryPages: {
        id: 'country-pages',
        title: '各国专页',
        content: [
          '**下方每个市场都有专门页面,提供完整的法律细节、注册步骤和信息来源。**',
        ],
        links: [
          { url: '/zh/balcony-solar/balcony-solar-legal-us-states', title: '美国阳台光伏合法吗?各州指南', description: '已签署及待批的州立法,定期更新' },
          { url: '/zh/balcony-solar/balkonkraftwerk-germany-rules', title: 'Balkonkraftwerk:德国规则详解', description: '800W上限、MaStR注册,以及新的DIN VDE V 0126-95标准' },
          { url: '/zh/balcony-solar/balcony-solar-spain-latam', title: '西班牙与拉丁美洲的阳台光伏', description: '详解西班牙不明确的状态' },
          { url: '/zh/balcony-solar/balcony-solar-portugal-brazil', title: '葡萄牙与巴西的阳台光伏', description: '葡萄牙的成文制度对比巴西的监管空白' },
          { url: '/zh/balcony-solar/balcony-solar-gulf-mena', title: '海湾与MENA地区的阳台光伏', description: '阿联酋和沙特阿拉伯正在兴起的监管' },
        ],
      },
      howRulesAreChanging: {
        id: 'how-rules-are-changing',
        title: '这些规则如何变化',
        content: [
          '**美国各州立法是这一领域变化最快的部分——过去一年内已有多个州签署了专门的阳台光伏法案,还有更多州正在积极推进立法程序。** 美国以外地区变化频率较低,但并非没有:德国的DIN VDE V 0126-95产品标准最近才于2025年12月生效,说明即便是成熟市场也在持续完善规则。',
        ],
      },
      faqSection: {
        id: 'faq',
        title: '常见问题',
        faqs: [
          { q: '哪些国家的阳台光伏法律最清晰?', a: '葡萄牙和德国都拥有成熟、成文的简化制度,功率限制和注册流程都很明确——是本指南所覆盖市场中状态最清晰的两个。' },
          { q: '阳台光伏在美国全境都合法吗?', a: '不是——美国没有联邦框架。合法性完全由各州决定,目前只有少数几个州通过了专门立法。请查看各州指南了解最新状态。' },
          { q: '有国家明确禁止阳台光伏吗?', a: '本指南覆盖的市场中没有一个明确禁止阳台光伏——状态从明确允许到不明确再到尚未涉及不等,但都没有到完全禁止的程度。' },
          { q: '为什么西班牙的状态被列为"不明确"而不是明确的是或否?', a: '因为信息来源确实相互矛盾——供应商和媒体来源声称小型套件享有简化豁免,而专注于详细法律分析的来源则表示仍需履行全部正式手续。本指南如实报告这一分歧,而不是在未经证实的情况下偏向任何一方。' },
          { q: '巴西和墨西哥允许阳台光伏吗?', a: '并未被禁止,但两国都没有小型系统豁免——无论系统规模大小,都适用同样完整的并网注册流程,这与专门的简化制度是明显不同的情形。' },
          { q: '这些法律状态信息多久更新一次?', a: '本页面及其链接的各国专页遵循6个月的更新周期,不过考虑到美国各州立法进展迅速,美国州级专页的更新频率更快(60天一次)。' },
          { q: '如果我所在的国家没有列在这里该怎么办?', a: '请直接查询你所在国家或地区的能源监管机构——本指南覆盖的是本站目前追踪的市场,而不是全球每一个国家。' },
          { q: '"无监管"和"合法"是一回事吗?', a: '不一定——真正尚未涉及的监管(例如海湾/MENA部分地区)意味着既没有明确允许,也没有明确禁止,这与拥有清晰简化法律框架的市场相比,带来的实际风险是不同的。' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: '阳台光伏合法吗?各国法律状态指南',
      description: '你所在的国家阳台光伏合法吗?全球状态追踪,涵盖美国、德国、西班牙、葡萄牙、巴西、墨西哥以及海湾/中东北非(MENA)地区,截至2026年7月核实。',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      inLanguage: 'zh',
      author: { '@type': 'Organization', name: 'PromptQuorum' },
      url: 'https://www.promptquorum.com/zh/balcony-solar/is-balcony-solar-legal-country-guide',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: '需要在购买前确认法律状态的阳台光伏潜在买家' },
      about: ['阳台光伏合法性', '太阳能监管', 'Steckersolargeräte', '插座式光伏法律'],
    },
  },
  fr: {
    theme: 'Balcony Solar Legislation',
    title: "L'énergie solaire de balcon est-elle légale ? Guide du statut pays par pays",
    seoTitle: "L'énergie solaire de balcon est-elle légale ? Guide mondial (2026)",
    intro: "Le statut juridique de l'énergie solaire de balcon va d'un régime simplifié codifié et bien défini à un véritable vide réglementaire — et cette différence compte plus que n'importe quelle fiche technique avant tout achat. Ce guide suit le statut actuel sur chaque marché majeur couvert par ce site, avec des liens vers le détail complet pour chacun.",
    metaDescription: "L'énergie solaire de balcon est-elle légale dans votre pays ? Suivi mondial du statut couvrant les États-Unis, l'Allemagne, l'Espagne, le Portugal, le Brésil, le Mexique et la région du Golfe/MENA, vérifié en juillet 2026.",
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '9 min de lecture',
    educationalLevel: 'Intermediate',
    audience: "Acheteurs potentiels d'énergie solaire de balcon devant confirmer le statut légal avant d'acheter",
    primaryTerm: "l'énergie solaire de balcon est-elle légale",
    targetKeywords: ["l'énergie solaire de balcon est-elle légale", "statut légal de l'énergie solaire de balcon par pays", "légalité du solaire plug-and-play", "où l'énergie solaire de balcon est-elle légale"],
    leadAnswerBlock: "**Le statut légal de l'énergie solaire de balcon varie énormément selon les pays : le Portugal dispose d'un régime simplifié clairement codifié, l'Allemagne d'un régime bien établi, les États-Unis varient entièrement selon l'État sans aucun cadre fédéral, et le Brésil, le Mexique et la région du Golfe/MENA n'ont actuellement aucune exemption dédiée pour les petits systèmes.** Il n'existe aucune hypothèse par défaut fiable — vérifiez le statut spécifique de votre pays (et, aux États-Unis, de votre État) avant d'acheter.",
    quickAnswerTop: {
      fr: {
        question: "L'énergie solaire de balcon est-elle légale là où j'habite ?",
        answer: "Cela dépend entièrement de votre pays, et aux États-Unis, de votre État. Le Portugal et l'Allemagne disposent des régimes simplifiés les plus clairs et les plus établis. Les États-Unis n'ont aucun cadre fédéral — la légalité est déterminée État par État, seule une poignée d'États ayant adopté une législation dédiée. Le Brésil, le Mexique et la région du Golfe/MENA n'ont aucune exemption pour les petits systèmes ; les règles d'interconnexion standard s'appliquent quelle que soit la taille. Le statut de l'Espagne est réellement ambigu.",
        bullets: [
          "Portugal : explicitement légal, régime simplifié codifié pour les systèmes ≤700W sans injection sur le réseau",
          "Allemagne : explicitement légal, régime simplifié établi (enregistrement unique au MaStR, plafond onduleur de 800W)",
          "États-Unis : varie selon l'État, aucun cadre fédéral — consultez le guide dédié État par État",
          "Espagne : ambigu — sources commerciales et juridiques contradictoires sur l'existence d'une exemption simplifiée",
          "Brésil, Mexique, Golfe/MENA : aucune exemption pour les petits systèmes — les règles d'interconnexion standard s'appliquent quelle que soit la taille",
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: 'Points clés', anchor: '#key-takeaways' },
      { label: 'Panorama mondial du statut', anchor: '#global-status' },
      { label: 'Que signifie réellement « légal » ?', anchor: '#what-legal-means' },
      { label: 'Pages par pays', anchor: '#country-pages' },
      { label: 'Comment ces règles évoluent', anchor: '#how-rules-are-changing' },
      { label: 'FAQ', anchor: '#faq' },
      { label: 'Lectures complémentaires', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          "Le statut légal va d'un régime simplifié codifié (Portugal, Allemagne) à un véritable vide réglementaire (certaines parties de la région du Golfe/MENA) — il n'existe aucune hypothèse par défaut fiable.",
          "Les États-Unis n'ont aucun cadre fédéral — la légalité est entièrement déterminée par l'État, et la plupart des États n'ont pas encore spécifiquement abordé l'énergie solaire de balcon.",
          "Le Brésil et le Mexique appliquent tous deux leur processus d'interconnexion complet standard quelle que soit la taille du système — aucune dérogation pour petits systèmes n'existe dans l'un ou l'autre pays.",
          "Le statut de l'Espagne est une véritable question ouverte — les sources se contredisent sur l'existence d'une exemption simplifiée pour les petits kits.",
          "Ce suivi et chaque page pays associée s'appuient sur une source de données unique et partagée, de sorte qu'un changement de statut à un endroit se répercute de façon cohérente partout.",
          "Les règles évoluent le plus vite aux États-Unis, où de nouveaux États adoptent activement une législation sur l'énergie solaire de balcon — consultez la page dédiée aux États-Unis pour le statut mois par mois.",
        ],
      },
      globalStatus: {
        id: 'global-status',
        title: 'Panorama mondial du statut',
        content: [
          "**Ce tableau résume le statut légal actuel et les limites de puissance pour chaque marché couvert par ce site — cliquez sur chaque page pays pour le détail complet, les sources et les étapes d'enregistrement.**",
        ],
        rows: statusRows,
        columns: ['country', 'status', 'powerLimit'],
        tableFormat: true,
      },
      whatLegalMeans: {
        id: 'what-legal-means',
        title: 'Que signifie réellement « légal » ?',
        content: [
          "**« Légal » pour l'énergie solaire de balcon signifie généralement l'une de trois situations distinctes, et les confondre est une source fréquente de confusion : explicitement autorisé dans le cadre d'un régime simplifié dédié avec une limite de puissance définie ; légal uniquement au sens où le système relève des mêmes règles que n'importe quel autre système solaire raccordé au réseau, sans voie allégée ; ou véritablement non traité par la réglementation actuelle (ni autorisé ni interdit).** Les pages pays ci-dessous précisent laquelle de ces trois situations s'applique à votre marché, car la différence pratique — auto-installation avec un formulaire simple contre processus d'interconnexion formel complet — est significative.",
          "Autre point à connaître avant d'acheter : la plupart du matériel solaire de balcon largement disponible transmet par défaut les données de production vers le cloud du fabricant, quel que soit le régime légal de votre pays — la surveillance strictement locale est l'exception qu'il faut rechercher spécifiquement, pas la valeur par défaut à supposer acquise. Consultez [utiliser l'énergie solaire de balcon sans le cloud](/fr/balcony-solar/home-assistant-balcony-solar-no-cloud) si cela compte pour vous.",
        ],
        snippetBlocks: [
          { type: 'one-sentence', text: "« Légal » pour l'énergie solaire de balcon peut désigner aussi bien un régime simplifié codifié qu'un véritable vide réglementaire — vérifiez lequel s'applique à votre pays." },
          { type: 'plain-terms', text: "Certains pays ont créé une voie spéciale et simple réservée aux petits systèmes branchables. D'autres appliquent simplement les mêmes règles qu'une installation complète en toiture, quelle que soit la taille de votre système. Quelques-uns n'ont pas du tout abordé la question." },
        ],
      },
      countryPages: {
        id: 'country-pages',
        title: 'Pages par pays',
        content: [
          "**Chaque marché ci-dessous dispose d'une page dédiée avec le détail juridique complet, les étapes d'enregistrement et les sources.**",
        ],
        links: [
          { url: '/fr/balcony-solar/balcony-solar-legal-us-states', title: "L'énergie solaire de balcon est-elle légale aux États-Unis ? Guide État par État", description: "Législation d'État adoptée et en cours d'examen, mise à jour régulièrement" },
          { url: '/fr/balcony-solar/balkonkraftwerk-germany-rules', title: 'Balkonkraftwerk : les règles allemandes expliquées', description: 'Plafond de 800W, enregistrement au MaStR et nouvelle norme DIN VDE V 0126-95' },
          { url: '/fr/balcony-solar/balcony-solar-spain-latam', title: "L'énergie solaire de balcon en Espagne et en Amérique latine", description: "Le statut ambigu de l'Espagne expliqué" },
          { url: '/fr/balcony-solar/balcony-solar-portugal-brazil', title: "L'énergie solaire de balcon au Portugal et au Brésil", description: "Le régime codifié du Portugal face au vide réglementaire du Brésil" },
          { url: '/fr/balcony-solar/balcony-solar-gulf-mena', title: "L'énergie solaire de balcon dans le Golfe et la région MENA", description: "Réglementation naissante aux Émirats arabes unis et en Arabie saoudite" },
        ],
      },
      howRulesAreChanging: {
        id: 'how-rules-are-changing',
        title: 'Comment ces règles évoluent',
        content: [
          "**La législation des États américains est la partie qui évolue le plus vite dans ce paysage — plusieurs États ont signé des lois dédiées à l'énergie solaire de balcon au cours de la dernière année, et d'autres progressent activement dans leurs législatures respectives.** En dehors des États-Unis, les changements sont moins fréquents mais pas absents : la norme produit allemande DIN VDE V 0126-95 est entrée en vigueur aussi récemment qu'en décembre 2025, ce qui montre que même les marchés établis continuent d'affiner leurs règles.",
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'Questions fréquentes',
        faqs: [
          { q: "Quels pays ont les lois sur l'énergie solaire de balcon les plus claires ?", a: "Le Portugal et l'Allemagne disposent tous deux de régimes simplifiés bien établis et codifiés, avec des limites de puissance claires et des processus d'enregistrement définis — le statut le plus clair parmi tous les marchés couverts ici." },
          { q: "L'énergie solaire de balcon est-elle légale partout aux États-Unis ?", a: "Non — il n'existe aucun cadre fédéral. La légalité est déterminée entièrement au niveau de l'État, et seule une poignée d'États ont pour l'instant adopté une législation dédiée. Consultez le guide État par État pour le statut actuel." },
          { q: "Certains pays interdisent-ils explicitement l'énergie solaire de balcon ?", a: "Aucun des marchés couverts dans ce guide n'a d'interdiction explicite — le statut va de clairement autorisé à ambigu ou non traité, mais jamais à une interdiction pure et simple." },
          { q: "Pourquoi le statut de l'Espagne est-il listé comme ambigu plutôt qu'un oui ou un non clair ?", a: "Les sources se contredisent réellement — les sources commerciales et de presse affirment qu'une exemption simplifiée existe pour les petits kits, tandis qu'une source d'analyse juridique détaillée indique que toutes les formalités complètes s'appliquent encore. Ce guide rapporte cette contradiction plutôt que de trancher sans confirmation." },
          { q: "Le Brésil et le Mexique autorisent-ils l'énergie solaire de balcon ?", a: "Ce n'est pas interdit, mais aucun des deux pays n'a d'exemption pour les petits systèmes — le même processus complet d'enregistrement d'interconnexion s'applique quelle que soit la taille du système, une situation nettement différente d'un régime simplifié dédié." },
          { q: "À quelle fréquence cette information sur le statut légal change-t-elle ?", a: "Cette page et les pages pays associées suivent un cycle de mise à jour de 6 mois, bien que la page dédiée aux États américains soit actualisée plus rapidement (60 jours) étant donné la rapidité d'évolution de la législation des États américains." },
          { q: "Que dois-je faire si mon pays n'est pas répertorié ici ?", a: "Consultez directement le régulateur de l'énergie national ou régional de votre pays — ce guide couvre les marchés actuellement suivis par ce site, pas tous les pays du monde." },
          { q: "Non réglementé est-il synonyme de légal ?", a: "Pas nécessairement — une réglementation véritablement non traitée (comme dans certaines parties de la région du Golfe/MENA) signifie qu'il n'existe ni autorisation explicite ni interdiction, ce qui comporte un risque pratique différent d'un marché doté d'un cadre légal simplifié et clair." },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: "L'énergie solaire de balcon est-elle légale ? Guide du statut pays par pays",
      description: "L'énergie solaire de balcon est-elle légale dans votre pays ? Suivi mondial du statut couvrant les États-Unis, l'Allemagne, l'Espagne, le Portugal, le Brésil, le Mexique et la région du Golfe/MENA, vérifié en juillet 2026.",
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      inLanguage: 'fr',
      author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
      url: 'https://www.promptquorum.com/fr/balcony-solar/is-balcony-solar-legal-country-guide',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: "Acheteurs potentiels d'énergie solaire de balcon devant confirmer le statut légal avant d'acheter" },
      about: ["Légalité de l'énergie solaire de balcon", 'Réglementation solaire', 'Steckersolargeräte', 'Droit du solaire plug-and-play'],
    },
  },
  ko: {
    theme: 'Balcony Solar Legislation',
    title: '베란다 태양광 발전은 합법인가? 국가별 법적 지위 가이드',
    seoTitle: '베란다 태양광 발전은 합법인가? 글로벌 현황 가이드 (2026)',
    intro: '베란다 태양광 발전의 법적 지위는 명확하게 성문화된 간소화 제도부터 사실상의 규제 공백까지 다양하며, 이 차이는 무언가를 구매하기 전에 어떤 사양표보다 중요합니다. 이 가이드는 이 사이트가 다루는 모든 주요 시장의 현재 상태를 추적하며, 각 국가의 상세 정보로 연결되는 링크를 제공합니다.',
    metaDescription: '당신의 국가에서 베란다 태양광 발전은 합법인가요? 미국, 독일, 스페인, 포르투갈, 브라질, 멕시코, 걸프/MENA 지역을 다루는 글로벌 현황 추적, 2026년 7월 기준 검증됨.',
    publishDate: '2026-07-02',
    dateModified: '2026-07-02',
    readTime: '9분 읽기',
    educationalLevel: 'Intermediate',
    audience: '구매 전 법적 지위를 확인해야 하는 베란다 태양광 발전 잠재 구매자',
    primaryTerm: '베란다 태양광 발전 합법',
    targetKeywords: ['베란다 태양광 발전 합법', '국가별 베란다 태양광 발전 법적 지위', '플러그인 태양광의 합법성', '베란다 태양광 발전이 합법인 국가'],
    leadAnswerBlock: '**베란다 태양광 발전의 법적 지위는 국가마다 크게 다릅니다. 포르투갈은 명확하게 성문화된 간소화 제도를 갖추고 있고, 독일은 확고하게 자리 잡은 제도를 운영하며, 미국은 연방 차원의 프레임워크 없이 주마다 완전히 다르고, 브라질·멕시코·걸프/MENA 지역은 현재 소형 시스템 전용 면제 규정이 전혀 없습니다.** 안전하게 적용할 수 있는 기본 가정은 없습니다—구매 전 반드시 해당 국가(미국의 경우 해당 주)의 구체적인 지위를 확인하세요.',
    quickAnswerTop: {
      ko: {
        question: '제가 사는 곳에서 베란다 태양광 발전은 합법인가요?',
        answer: '전적으로 거주 국가에 따라 다르며, 미국의 경우 주에 따라 다릅니다. 포르투갈과 독일은 가장 명확하고 확립된 간소화 제도를 갖추고 있습니다. 미국은 연방 프레임워크가 없어 합법성이 주별로 결정되며, 전용 법률을 통과시킨 주는 소수에 불과합니다. 브라질, 멕시코, 걸프/MENA 지역은 소형 시스템 면제 규정이 없어 규모와 상관없이 표준 계통연계 규칙이 적용됩니다. 스페인의 지위는 실제로 모호합니다.',
        bullets: [
          '포르투갈: 명시적으로 합법, 계통 역송전이 없는 700W 이하 시스템에 대해 성문화된 간소화 제도 존재',
          '독일: 명시적으로 합법, 확립된 간소화 제도(MaStR 등록만 필요, 인버터 상한 800W)',
          '미국: 주마다 다르며 연방 프레임워크 없음—전용 주별 가이드를 확인',
          '스페인: 모호함—간소화된 면제 규정이 존재하는지에 대해 판매자 정보와 법률 정보가 상충',
          '브라질, 멕시코, 걸프/MENA: 소형 시스템 면제 규정 없음—규모와 무관하게 표준 계통연계 규칙 적용',
        ],
        updatedDate: '2026-07-02',
      },
    },
    toc: [
      { label: '핵심 요약', anchor: '#key-takeaways' },
      { label: '글로벌 현황 개요', anchor: '#global-status' },
      { label: '"합법"이 실제로 의미하는 것', anchor: '#what-legal-means' },
      { label: '국가별 페이지', anchor: '#country-pages' },
      { label: '규정은 어떻게 변화하고 있는가', anchor: '#how-rules-are-changing' },
      { label: '자주 묻는 질문', anchor: '#faq' },
      { label: '관련 읽을거리', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          '법적 지위는 성문화된 간소화 제도(포르투갈, 독일)부터 사실상의 규제 공백(걸프/MENA 일부 지역)까지 다양하며, 안전하게 적용할 수 있는 기본 가정은 없습니다.',
          '미국은 연방 프레임워크가 없습니다—합법성은 전적으로 주 단위로 결정되며, 대부분의 주는 아직 베란다 태양광 발전을 구체적으로 다루지 않았습니다.',
          '브라질과 멕시코는 모두 시스템 규모와 무관하게 표준 전체 계통연계 절차를 적용합니다—두 나라 모두 소형 시스템 예외 규정이 존재하지 않습니다.',
          '스페인의 지위는 실제로 미해결 문제입니다—소형 키트가 간소화된 면제를 받는지에 대해 출처마다 의견이 엇갈립니다.',
          '이 추적 페이지와 연결된 모든 국가 페이지는 동일한 공유 데이터 소스를 참조하므로, 한 곳에서의 지위 변경이 모든 곳에 일관되게 반영됩니다.',
          '규정은 미국에서 가장 빠르게 변화하고 있으며, 새로운 주들이 활발히 베란다 태양광 발전 관련 법안을 통과시키고 있습니다—월별 최신 현황은 전용 미국 페이지를 확인하세요.',
        ],
      },
      globalStatus: {
        id: 'global-status',
        title: '글로벌 현황 개요',
        content: [
          '**이 표는 이 사이트가 다루는 모든 시장의 현재 법적 지위와 출력 제한을 요약한 것입니다——각 국가 페이지를 클릭하면 전체 세부 정보, 출처, 등록 절차를 확인할 수 있습니다.**',
        ],
        rows: statusRows,
        columns: ['country', 'status', 'powerLimit'],
        tableFormat: true,
      },
      whatLegalMeans: {
        id: 'what-legal-means',
        title: '"합법"이 실제로 의미하는 것',
        content: [
          '**베란다 태양광 발전에서 "합법"은 보통 세 가지 서로 다른 의미 중 하나를 뜻하며, 이를 혼동하는 것이 흔한 혼란의 원인입니다. 정의된 출력 제한을 가진 전용 간소화 제도 아래 명시적으로 허용되는 경우, 더 간편한 경로 없이 다른 일반 계통연계 태양광 시스템과 동일한 규정이 적용된다는 의미에서만 "합법"인 경우, 그리고 현행 규정에서 사실상 다뤄지지 않은(허용도 금지도 되지 않은) 경우입니다.** 자체 설치가 가능한 간단한 양식과 정식 계통연계 절차 전체를 거쳐야 하는 것 사이의 실질적 차이가 크기 때문에, 아래 국가별 페이지에서는 이 세 가지 중 어느 것이 해당 시장에 적용되는지 명시합니다.',
          '구매 전에 알아둘 만한 또 다른 사항: 널리 판매되는 베란다 태양광 하드웨어 대부분은 어느 나라의 법적 제도 아래 있든 기본적으로 발전 데이터를 제조사 클라우드로 전송합니다—로컬 전용 모니터링은 기본값이 아니라 특별히 찾아야 하는 예외입니다. 이 점이 중요하다면 [클라우드 없이 베란다 태양광 발전 운영하기](/ko/balcony-solar/home-assistant-balcony-solar-no-cloud)를 참고하세요.',
        ],
        snippetBlocks: [
          { type: 'one-sentence', text: '베란다 태양광 발전에서 "합법"은 성문화된 간소화 제도부터 사실상의 규제 공백까지 무엇이든 의미할 수 있습니다—자신의 국가에 어느 쪽이 해당하는지 확인하세요.' },
          { type: 'plain-terms', text: '일부 국가는 소형 플러그인 시스템만을 위한 특별하고 간편한 경로를 마련했습니다. 다른 국가는 시스템이 아무리 작아도 전체 지붕 설치와 동일한 규정을 그대로 적용합니다. 몇몇 국가는 이 문제를 아예 다루지 않았습니다.' },
        ],
      },
      countryPages: {
        id: 'country-pages',
        title: '국가별 페이지',
        content: [
          '**아래 각 시장에는 전체 법적 세부 정보, 등록 절차, 출처를 담은 전용 페이지가 있습니다.**',
        ],
        links: [
          { url: '/ko/balcony-solar/balcony-solar-legal-us-states', title: '미국에서 베란다 태양광 발전은 합법인가? 주별 가이드', description: '서명된 주 법률 및 계류 중인 법률, 정기적으로 업데이트' },
          { url: '/ko/balcony-solar/balkonkraftwerk-germany-rules', title: 'Balkonkraftwerk: 독일 규정 설명', description: '800W 상한, MaStR 등록, 새로운 DIN VDE V 0126-95 표준' },
          { url: '/ko/balcony-solar/balcony-solar-spain-latam', title: '스페인과 라틴아메리카의 베란다 태양광 발전', description: '스페인의 모호한 지위 설명' },
          { url: '/ko/balcony-solar/balcony-solar-portugal-brazil', title: '포르투갈과 브라질의 베란다 태양광 발전', description: '포르투갈의 성문화된 제도와 브라질의 규제 공백 비교' },
          { url: '/ko/balcony-solar/balcony-solar-gulf-mena', title: '걸프 및 MENA 지역의 베란다 태양광 발전', description: 'UAE와 사우디아라비아의 신생 규제' },
        ],
      },
      howRulesAreChanging: {
        id: 'how-rules-are-changing',
        title: '규정은 어떻게 변화하고 있는가',
        content: [
          '**미국 주 법률은 이 분야에서 가장 빠르게 변화하는 부분입니다—지난 1년 동안 여러 주가 전용 베란다 태양광 발전 법안에 서명했으며, 더 많은 주가 주 의회에서 적극적으로 논의를 진행하고 있습니다.** 미국 외 지역에서는 변화 빈도가 낮지만 없지는 않습니다. 독일의 DIN VDE V 0126-95 제품 표준은 2025년 12월이라는 비교적 최근에 발효되었으며, 이는 이미 확립된 시장조차 계속해서 규정을 다듬고 있음을 보여줍니다.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: '자주 묻는 질문',
        faqs: [
          { q: '베란다 태양광 발전 법률이 가장 명확한 국가는 어디인가요?', a: '포르투갈과 독일 모두 명확한 출력 제한과 등록 절차를 갖춘 확고하고 성문화된 간소화 제도를 운영하고 있습니다—여기서 다루는 시장 중 가장 명확한 지위입니다.' },
          { q: '미국 전역에서 베란다 태양광 발전이 합법인가요?', a: '아닙니다—연방 프레임워크가 존재하지 않습니다. 합법성은 전적으로 주 단위에서 결정되며, 지금까지 전용 법률을 통과시킨 주는 소수에 불과합니다. 최신 현황은 주별 가이드를 참고하세요.' },
          { q: '베란다 태양광 발전을 명시적으로 금지하는 국가가 있나요?', a: '이 가이드에서 다루는 시장 중 명시적으로 금지하는 국가는 없습니다—지위는 명확한 허용부터 모호함, 미다룸까지 다양하지만 완전한 금지에는 이르지 않습니다.' },
          { q: '왜 스페인의 지위는 명확한 예/아니오가 아니라 모호함으로 표시되나요?', a: '출처들이 실제로 상충하기 때문입니다—판매자 및 언론 출처는 소형 키트에 간소화된 면제가 존재한다고 주장하는 반면, 상세한 법률 분석에 초점을 맞춘 출처는 여전히 모든 정식 절차가 적용된다고 말합니다. 이 가이드는 확인되지 않은 채로 어느 한쪽 편을 들기보다 이 상충을 있는 그대로 전달합니다.' },
          { q: '브라질과 멕시코는 베란다 태양광 발전을 허용하나요?', a: '금지되지는 않았지만, 두 나라 모두 소형 시스템 면제 규정이 없습니다—시스템 규모와 무관하게 동일한 전체 계통연계 등록 절차가 적용되며, 이는 전용 간소화 제도와는 상당히 다른 상황입니다.' },
          { q: '이 법적 지위 정보는 얼마나 자주 변경되나요?', a: '이 페이지와 연결된 국가별 페이지는 6개월 갱신 주기를 따르지만, 미국 주 법률이 빠르게 변화하고 있는 만큼 미국 주별 페이지는 더 빠른 주기(60일)로 갱신됩니다.' },
          { q: '제 국가가 여기에 목록되어 있지 않다면 어떻게 해야 하나요?', a: '해당 국가 또는 지역의 에너지 규제 기관에 직접 문의하세요—이 가이드는 이 사이트가 현재 추적하는 시장을 다루며, 전 세계 모든 국가를 다루지는 않습니다.' },
          { q: '규제되지 않음은 합법과 같은 의미인가요?', a: '반드시 그렇지는 않습니다—사실상 다뤄지지 않은 규제(걸프/MENA 일부 지역 등)는 명시적 허용도 금지도 존재하지 않음을 의미하며, 이는 명확하고 간소화된 법적 프레임워크를 갖춘 시장과는 다른 실질적 위험을 수반합니다.' },
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: '베란다 태양광 발전은 합법인가? 국가별 법적 지위 가이드',
      description: '당신의 국가에서 베란다 태양광 발전은 합법인가요? 미국, 독일, 스페인, 포르투갈, 브라질, 멕시코, 걸프/MENA 지역을 다루는 글로벌 현황 추적, 2026년 7월 기준 검증됨.',
      datePublished: '2026-07-02',
      dateModified: '2026-07-02',
      inLanguage: 'ko',
      author: { '@type': 'Organization', name: 'PromptQuorum' },
      url: 'https://www.promptquorum.com/ko/balcony-solar/is-balcony-solar-legal-country-guide',
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro'] },
      educationalLevel: 'Intermediate',
      proficiencyLevel: 'Intermediate',
      audience: { '@type': 'Audience', audienceType: '구매 전 법적 지위를 확인해야 하는 베란다 태양광 발전 잠재 구매자' },
      about: ['베란다 태양광 발전의 합법성', '태양광 규제', 'Steckersolargeräte', '플러그인 태양광 법률'],
    },
  },
};
