// Slug: yuma-balcony-solar
// TODO (internal-linking phase): reciprocal link to balcony-solar-industry-overview (Yuma named as a kit reseller alongside Anker/EcoFlow/Zendure/priwatt) and to the balcony-solar kit/battery comparison pages; this page stays research-intent (history/ownership/scale) and must not duplicate buying-decision framing.
import type { Language } from "@/lib/blog/blogContent";
import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    freshness_tier: 'semi_annual',
    next_refresh_due: '2027-01-19',
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma: Balcony Solar Company Profile',
    seoTitle: 'Yuma Balcony Solar Company Profile',
    metaDescription: 'Company profile for Yuma: history, ownership, and product range in the balcony solar market.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: 'Readers researching Yuma as a company',
    intro: 'This profile covers Yuma as a company: its founding, ownership structure, product lineup, confirmed markets, and supplier relationships. It draws on the same registry data and standards referenced throughout PromptQuorum\'s balcony solar coverage, including the industry overview linked below. Readers comparing balcony solar kits or batteries before buying should see the dedicated comparison pages instead — this page does not cover pricing or a buying recommendation.',
    leadAnswerBlock: '**Yuma is a self-funded balcony solar company headquartered in Cologne, Germany, founded in 2020 by three co-founders, with no external investor round found.** Yuma does not manufacture its own inverters or batteries — it assembles kits from third-party components, including hardware from Hoymiles, EcoFlow, and Anker SOLIX, and its own product contribution is the mounting hardware, which varies by installation surface. Confirmed markets are Germany and Austria, per Yuma\'s own shipping and support documentation.',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma: Key Facts',
        items: [
          'Yuma was founded in 2020 by three co-founders and is headquartered in Cologne, Germany.',
          'The company is self-funded — no external investor round has been found.',
          'Yuma assembles balcony solar kits from third-party inverters and batteries rather than manufacturing its own hardware.',
          'Confirmed component suppliers named on Yuma\'s own product pages include Hoymiles, EcoFlow, and Anker SOLIX.',
          'Yuma\'s own product contribution is mounting hardware, offered in different formats depending on the installation surface.',
          'Confirmed markets are Germany and Austria, per Yuma\'s own shipping and support documentation.',
        ],
      },
      snapshot: {
        title: 'Yuma: Company Snapshot',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: 'Cologne, Germany; founded 2020 by three co-founders; self-funded, no external investor round found.',
        content: 'Yuma is headquartered in Cologne, Germany, and was founded in 2020 by three co-founders. The company is self-funded, and no external investor round has been found in company records or press coverage — a structural difference from balcony solar brands like Anker SOLIX and EcoFlow, which are divisions of larger publicly traded electronics companies. Yuma operates as a kit reseller: it packages third-party inverters and batteries with its own mounting hardware rather than manufacturing the electronics itself.',
        snippetBlocks: [
          { type: 'one-sentence', text: 'Yuma is a self-funded balcony solar kit company founded in 2020 and headquartered in Cologne, Germany.' },
          { type: 'plain-terms', text: 'Yuma isn\'t a subsidiary of a larger electronics company — it\'s an independent, privately held German startup that builds mounting hardware and bundles it with other companies\' inverters and batteries.' },
        ],
      },
      timeline: {
        title: 'Timeline',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: 'Founding year and market presence confirmed via Yuma\'s own About page and a 2022 TechCrunch mention.',
        content: 'Yuma was founded in 2020 by three co-founders in Cologne, Germany. Yuma\'s own About page confirms the founding year, and a 2022 TechCrunch mention independently corroborates the company\'s market presence in that period. No further company-confirmed milestones — such as funding rounds, headcount, or expansion dates — have been found beyond these two sources.',
      },
      lineup: {
        title: 'Product Line (Mounting Formats)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'Yuma assembles kits from third-party inverters/batteries — its own product is the mounting hardware, varied by installation surface.',
        content: 'Yuma\'s product line centers on mounting hardware, offered in different formats to match different installation surfaces such as balcony railings, walls, and flat roofs. The inverter and battery components bundled into each kit are sourced from third-party suppliers rather than designed or manufactured by Yuma itself. This makes Yuma\'s core engineering contribution the physical mounting system rather than the electronics that make the system grid-safe.',
      },
      markets: {
        title: 'Confirmed Markets',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: 'Germany and Austria confirmed via Yuma\'s own shipping/support documentation.',
        content: 'Yuma confirms sales and support coverage in Germany and Austria, per its own shipping and support documentation. No other markets have been confirmed in company records reviewed for this profile, and Yuma has not stated a date for expansion beyond these two countries.',
      },
      position: {
        title: 'Where Yuma Sits',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'Yuma sources components from other companies in this research set (Hoymiles, EcoFlow, Anker SOLIX) rather than manufacturing its own hardware.',
        content: 'The balcony solar supply chain splits into three layers: panel manufacturers, microinverter/battery makers, and kit resellers that package the two into a consumer product. Yuma operates squarely in the kit-reseller layer: it sources inverters and batteries from other companies covered in this research set — Hoymiles, EcoFlow, and Anker SOLIX — and its own manufacturing focus is mounting hardware rather than power electronics. This single-layer structure is more typical of the balcony solar market than the dual-layer approach used by Anker SOLIX and EcoFlow, which both design and manufacture their own battery hardware.',
      },
      partners: {
        title: 'Confirmed Component Suppliers',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: 'Named directly on Yuma\'s own product page — components Yuma bundles into kits rather than manufactures itself.',
        content: 'Yuma names Hoymiles, EcoFlow, and Anker SOLIX directly on its own product pages as suppliers of the inverters and batteries bundled into its kits. These are components Yuma assembles into finished products rather than hardware it designs or manufactures itself. No other supplier relationships have been confirmed beyond those named on Yuma\'s own site.',
      },
      faqSection: {
        id: 'faq',
        title: 'Frequently Asked Questions',
        faqs: [
          { q: 'Who owns Yuma?', a: 'Yuma was founded in 2020 by three co-founders and is headquartered in Cologne, Germany. The company is self-funded, and no external investor round has been found.' },
          { q: 'Is Yuma a subsidiary of a larger company?', a: 'No. Unlike Anker SOLIX or EcoFlow, which are divisions of larger publicly traded electronics companies, Yuma has been found to be an independent, privately held company.' },
          { q: 'Does Yuma manufacture its own inverters or batteries?', a: 'No. Yuma assembles kits from third-party components. Confirmed suppliers named on Yuma\'s own product page include Hoymiles, EcoFlow, and Anker SOLIX. Yuma\'s own product contribution is the mounting hardware.' },
          { q: 'What does Yuma actually make itself?', a: 'Yuma\'s own manufacturing focus is mounting hardware, offered in different formats for different installation surfaces such as balcony railings, walls, and flat roofs. The power electronics inside its kits come from third-party suppliers.' },
          { q: 'Which markets does Yuma sell in?', a: 'Yuma confirms sales and support coverage in Germany and Austria, per its own shipping and support documentation. No other markets have been confirmed.' },
          { q: 'When was Yuma founded?', a: 'Yuma was founded in 2020 by three co-founders. The founding year is confirmed on Yuma\'s own About page and corroborated by a 2022 TechCrunch mention of the company.' },
          { q: 'How does Yuma compare structurally to Anker SOLIX or EcoFlow?', a: 'Anker SOLIX and EcoFlow both design and manufacture their own battery hardware in addition to selling finished kits — a dual-layer structure. Yuma operates in a single layer: it sources inverters and batteries from other companies, including Hoymiles, EcoFlow, and Anker SOLIX, and focuses its own engineering on mounting hardware.' },
          { q: 'Is Yuma sold in the US?', a: 'No US market presence has been confirmed for Yuma. Its confirmed markets, per company documentation, are Germany and Austria.' },
        ],
      },
    },
  },
  de: {
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma: Unternehmensprofil im Balkonsolar-Markt',
    seoTitle: 'Yuma Balkonkraftwerke: Unternehmensprofil und Historie',
    metaDescription: 'Unternehmensprofil zu Yuma: Gründungsgeschichte, Eigentümerstruktur, Standort und Produktangebot des Anbieters im Markt für Balkonkraftwerke.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: 'Leser, die sich über das Unternehmen Yuma informieren möchten',
    intro: 'Dieses Profil behandelt Yuma als Unternehmen: Gründung, Eigentümerstruktur, Produktpalette, bestätigte Märkte und Lieferantenbeziehungen. Die Angaben stammen aus denselben Register- und Normendaten, auf die sich die gesamte Balkonsolar-Berichterstattung von PromptQuorum stützt, einschließlich des unten verlinkten Branchenüberblicks. Leser, die vor dem Kauf Balkonkraftwerk-Sets oder -Batterien vergleichen möchten, sollten stattdessen die dedizierten Vergleichsseiten lesen — dieser Beitrag behandelt weder Preise noch eine Kaufempfehlung.',
    leadAnswerBlock: '**Yuma ist ein selbstfinanziertes Balkonsolar-Unternehmen mit Sitz in Köln, das 2020 von drei Mitgründern gegründet wurde; eine externe Investorenrunde wurde nicht gefunden.** Yuma fertigt keine eigenen Wechselrichter oder Batterien — das Unternehmen stellt Sets aus Drittanbieter-Komponenten zusammen, darunter Hardware von Hoymiles, EcoFlow und Anker SOLIX, und der eigene Produktbeitrag ist die Montagehardware, die je nach Installationsfläche variiert. Bestätigte Märkte sind Deutschland und Österreich, laut Yumas eigener Versand- und Support-Dokumentation.',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma: Die wichtigsten Fakten',
        items: [
          'Yuma wurde 2020 von drei Mitgründern gegründet und hat seinen Sitz in Köln, Deutschland.',
          'Das Unternehmen ist selbstfinanziert — eine externe Investorenrunde wurde nicht gefunden.',
          'Yuma stellt Balkonkraftwerk-Sets aus Wechselrichtern und Batterien von Drittanbietern zusammen, statt eigene Hardware herzustellen.',
          'Bestätigte Komponentenlieferanten, die auf Yumas eigenen Produktseiten genannt werden, umfassen Hoymiles, EcoFlow und Anker SOLIX.',
          'Yumas eigener Produktbeitrag ist die Montagehardware, die in unterschiedlichen Formaten je nach Installationsfläche angeboten wird.',
          'Bestätigte Märkte sind Deutschland und Österreich, laut Yumas eigener Versand- und Support-Dokumentation.',
        ],
      },
      snapshot: {
        title: 'Yuma: Unternehmensüberblick',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: 'Köln, Deutschland; 2020 von drei Mitgründern gegründet; selbstfinanziert, keine externe Investorenrunde bekannt.',
        content: 'Yuma hat seinen Sitz in Köln, Deutschland, und wurde 2020 von drei Mitgründern gegründet. Das Unternehmen ist selbstfinanziert; eine externe Investorenrunde wurde weder in Unternehmensunterlagen noch in der Presseberichterstattung gefunden — ein struktureller Unterschied zu Balkonsolar-Marken wie Anker SOLIX und EcoFlow, die Sparten größerer börsennotierter Elektronikkonzerne sind. Yuma agiert als Kit-Wiederverkäufer: Das Unternehmen kombiniert Wechselrichter und Batterien von Drittanbietern mit eigener Montagehardware, statt die Elektronik selbst zu fertigen.',
        snippetBlocks: [
          { type: 'one-sentence', text: 'Yuma ist ein 2020 gegründetes, selbstfinanziertes Balkonkraftwerk-Unternehmen mit Sitz in Köln, Deutschland.' },
          { type: 'plain-terms', text: 'Yuma ist keine Tochtergesellschaft eines größeren Elektronikkonzerns — es handelt sich um ein unabhängiges, privat gehaltenes deutsches Start-up, das Montagehardware entwickelt und diese mit Wechselrichtern und Batterien anderer Unternehmen kombiniert.' },
        ],
      },
      timeline: {
        title: 'Zeitlinie',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: 'Gründungsjahr und Marktpräsenz bestätigt durch Yumas eigene Über-uns-Seite und eine TechCrunch-Erwähnung aus 2022.',
        content: 'Yuma wurde 2020 von drei Mitgründern in Köln, Deutschland, gegründet. Yumas eigene Über-uns-Seite bestätigt das Gründungsjahr, und eine TechCrunch-Erwähnung aus 2022 bestätigt unabhängig die Marktpräsenz des Unternehmens in diesem Zeitraum. Über diese beiden Quellen hinaus wurden keine weiteren vom Unternehmen bestätigten Meilensteine gefunden — etwa Finanzierungsrunden, Mitarbeiterzahlen oder Expansionsdaten.',
      },
      lineup: {
        title: 'Produktlinie (Montageformate)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'Yuma stellt Kits aus Wechselrichtern/Batterien von Drittanbietern zusammen — das eigene Produkt ist die Montagehardware, die je nach Installationsfläche variiert.',
        content: 'Yumas Produktlinie konzentriert sich auf Montagehardware, die in unterschiedlichen Formaten angeboten wird, um verschiedene Installationsflächen wie Balkongeländer, Wände und Flachdächer abzudecken. Die Wechselrichter- und Batteriekomponenten, die in jedem Set enthalten sind, stammen von Drittanbietern und werden nicht von Yuma selbst entwickelt oder gefertigt. Damit liegt Yumas technischer Kernbeitrag im physischen Montagesystem und nicht in der Elektronik, die das System netzsicher macht.',
      },
      markets: {
        title: 'Bestätigte Märkte',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: 'Deutschland und Österreich bestätigt durch Yumas eigene Versand-/Support-Dokumentation.',
        content: 'Yuma bestätigt Verkauf und Support in Deutschland und Österreich, laut eigener Versand- und Support-Dokumentation. Weitere Märkte wurden in den für dieses Profil geprüften Unternehmensunterlagen nicht bestätigt, und Yuma hat kein Datum für eine Expansion über diese beiden Länder hinaus genannt.',
      },
      position: {
        title: 'Yumas Positionierung',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'Yuma bezieht Komponenten von anderen Unternehmen aus diesem Recherche-Set (Hoymiles, EcoFlow, Anker SOLIX), statt eigene Hardware herzustellen.',
        content: 'Die Lieferkette für Balkonkraftwerke gliedert sich in drei Ebenen: Panelhersteller, Mikrowechselrichter-/Batteriehersteller und Kit-Wiederverkäufer, die beides zu einem Verbraucherprodukt zusammenführen. Yuma ist eindeutig in der Kit-Wiederverkäufer-Ebene aktiv: Das Unternehmen bezieht Wechselrichter und Batterien von anderen in diesem Recherche-Set behandelten Unternehmen — Hoymiles, EcoFlow und Anker SOLIX — und konzentriert die eigene Fertigung auf Montagehardware statt auf Leistungselektronik. Diese Ein-Ebenen-Struktur ist für den Balkonsolar-Markt typischer als der zweistufige Ansatz von Anker SOLIX und EcoFlow, die beide eigene Batteriehardware entwickeln und fertigen.',
      },
      partners: {
        title: 'Bestätigte Komponentenlieferanten',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: 'Direkt auf Yumas eigener Produktseite genannt — Komponenten, die Yuma zu Kits bündelt, statt sie selbst herzustellen.',
        content: 'Yuma nennt Hoymiles, EcoFlow und Anker SOLIX direkt auf seinen eigenen Produktseiten als Lieferanten der Wechselrichter und Batterien, die in seine Sets eingebaut werden. Es handelt sich um Komponenten, die Yuma zu Fertigprodukten zusammenbaut, statt sie selbst zu entwickeln oder zu fertigen. Über die auf Yumas eigener Website genannten Lieferanten hinaus wurden keine weiteren Lieferantenbeziehungen bestätigt.',
      },
      faqSection: {
        id: 'faq',
        title: 'Häufig gestellte Fragen',
        faqs: [
          { q: 'Wem gehört Yuma?', a: 'Yuma wurde 2020 von drei Mitgründern gegründet und hat seinen Sitz in Köln, Deutschland. Das Unternehmen ist selbstfinanziert; eine externe Investorenrunde wurde nicht gefunden.' },
          { q: 'Ist Yuma eine Tochtergesellschaft eines größeren Unternehmens?', a: 'Nein. Anders als Anker SOLIX oder EcoFlow, die Sparten größerer börsennotierter Elektronikkonzerne sind, wurde Yuma als unabhängiges, privat gehaltenes Unternehmen identifiziert.' },
          { q: 'Stellt Yuma eigene Wechselrichter oder Batterien her?', a: 'Nein. Yuma stellt Sets aus Drittanbieter-Komponenten zusammen. Bestätigte Lieferanten, die auf Yumas eigener Produktseite genannt werden, umfassen Hoymiles, EcoFlow und Anker SOLIX. Yumas eigener Produktbeitrag ist die Montagehardware.' },
          { q: 'Was stellt Yuma tatsächlich selbst her?', a: 'Yumas eigener Fertigungsschwerpunkt liegt auf Montagehardware, die in unterschiedlichen Formaten für verschiedene Installationsflächen wie Balkongeländer, Wände und Flachdächer angeboten wird. Die Leistungselektronik in den Sets stammt von Drittanbietern.' },
          { q: 'In welchen Märkten verkauft Yuma?', a: 'Yuma bestätigt Verkauf und Support in Deutschland und Österreich, laut eigener Versand- und Support-Dokumentation. Weitere Märkte wurden nicht bestätigt.' },
          { q: 'Wann wurde Yuma gegründet?', a: 'Yuma wurde 2020 von drei Mitgründern gegründet. Das Gründungsjahr wird auf Yumas eigener Über-uns-Seite bestätigt und durch eine TechCrunch-Erwähnung aus 2022 untermauert.' },
          { q: 'Wie unterscheidet sich Yuma strukturell von Anker SOLIX oder EcoFlow?', a: 'Anker SOLIX und EcoFlow entwickeln und fertigen beide eigene Batteriehardware zusätzlich zum Verkauf fertiger Sets — eine zweistufige Struktur. Yuma ist nur in einer Ebene tätig: Das Unternehmen bezieht Wechselrichter und Batterien von anderen Unternehmen, darunter Hoymiles, EcoFlow und Anker SOLIX, und konzentriert die eigene Entwicklung auf Montagehardware.' },
          { q: 'Wird Yuma in den USA verkauft?', a: 'Für Yuma wurde keine Präsenz auf dem US-Markt bestätigt. Die bestätigten Märkte laut Unternehmensdokumentation sind Deutschland und Österreich.' },
        ],
      },
    },
  },
  fr: {
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma : profil de l\'entreprise Balcony Solar',
    seoTitle: 'Yuma : profil de l\'entreprise solaire balcon',
    metaDescription: 'Profil de l\'entreprise Yuma : historique, structure de propriété, implantation et gamme de produits sur le marché du solaire de balcon.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: 'Lecteurs qui recherchent des informations sur l\'entreprise Yuma',
    intro: 'Ce profil couvre Yuma en tant qu\'entreprise : sa fondation, sa structure de propriété, sa gamme de produits, les marchés confirmés et ses relations fournisseurs. Il s\'appuie sur les mêmes données de registre et normes citées dans l\'ensemble de la couverture du solaire de balcon de PromptQuorum, y compris l\'aperçu de l\'industrie lié ci-dessous. Les lecteurs qui comparent des kits ou des batteries solaires de balcon avant d\'acheter devraient plutôt consulter les pages de comparaison dédiées — cette page ne couvre ni les prix ni une recommandation d\'achat.',
    leadAnswerBlock: '**Yuma est une entreprise solaire de balcon autofinancée, dont le siège est à Cologne, en Allemagne, fondée en 2020 par trois cofondateurs, sans aucun tour de financement externe recensé.** Yuma ne fabrique ni ses propres onduleurs ni ses propres batteries — l\'entreprise assemble des kits à partir de composants tiers, dont du matériel de Hoymiles, EcoFlow et Anker SOLIX, et sa propre contribution produit est le matériel de fixation, qui varie selon la surface d\'installation. Les marchés confirmés sont l\'Allemagne et l\'Autriche, selon la documentation d\'expédition et de support de Yuma elle-même.',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma : les chiffres clés',
        items: [
          'Yuma a été fondée en 2020 par trois cofondateurs et son siège est à Cologne, en Allemagne.',
          'L\'entreprise est autofinancée — aucun tour de financement externe n\'a été recensé.',
          'Yuma assemble des kits solaires de balcon à partir d\'onduleurs et de batteries tiers plutôt que de fabriquer son propre matériel.',
          'Les fournisseurs de composants confirmés, cités sur les propres pages produit de Yuma, incluent Hoymiles, EcoFlow et Anker SOLIX.',
          'La propre contribution produit de Yuma est le matériel de fixation, proposé sous différents formats selon la surface d\'installation.',
          'Les marchés confirmés sont l\'Allemagne et l\'Autriche, selon la documentation d\'expédition et de support de Yuma elle-même.',
        ],
      },
      snapshot: {
        title: 'Yuma : aperçu de l\'entreprise',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: 'Cologne, Allemagne ; fondée en 2020 par trois cofondateurs ; autofinancée, aucun tour de financement externe recensé.',
        content: 'Yuma a son siège à Cologne, en Allemagne, et a été fondée en 2020 par trois cofondateurs. L\'entreprise est autofinancée, et aucun tour de financement externe n\'a été trouvé dans les registres d\'entreprise ni dans la couverture médiatique — une différence structurelle par rapport aux marques solaires de balcon comme Anker SOLIX et EcoFlow, qui sont des divisions de grandes entreprises électroniques cotées en bourse. Yuma opère comme revendeur de kits : elle assemble des onduleurs et des batteries tiers avec son propre matériel de fixation plutôt que de fabriquer elle-même l\'électronique.',
        snippetBlocks: [
          { type: 'one-sentence', text: 'Yuma est une entreprise de kits solaires de balcon autofinancée, fondée en 2020 et basée à Cologne, en Allemagne.' },
          { type: 'plain-terms', text: 'Yuma n\'est pas une filiale d\'un grand groupe électronique — c\'est une start-up allemande indépendante et détenue à titre privé, qui conçoit du matériel de fixation et l\'associe aux onduleurs et batteries d\'autres entreprises.' },
        ],
      },
      timeline: {
        title: 'Chronologie',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: 'Année de fondation et présence sur le marché confirmées par la page « À propos » de Yuma et une mention de TechCrunch en 2022.',
        content: 'Yuma a été fondée en 2020 par trois cofondateurs à Cologne, en Allemagne. La propre page « À propos » de Yuma confirme l\'année de fondation, et une mention de TechCrunch en 2022 corrobore de manière indépendante la présence de l\'entreprise sur le marché à cette période. Aucun autre jalon confirmé par l\'entreprise — tour de financement, effectifs ou dates d\'expansion — n\'a été trouvé au-delà de ces deux sources.',
      },
      lineup: {
        title: 'Gamme de produits (formats de fixation)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'Yuma assemble des kits à partir d\'onduleurs/batteries tiers — son propre produit est le matériel de fixation, qui varie selon la surface d\'installation.',
        content: 'La gamme de produits de Yuma est centrée sur le matériel de fixation, proposé sous différents formats pour s\'adapter à diverses surfaces d\'installation telles que les garde-corps de balcon, les murs et les toits plats. Les composants onduleur et batterie inclus dans chaque kit proviennent de fournisseurs tiers plutôt que d\'être conçus ou fabriqués par Yuma elle-même. Cela fait du système de fixation physique la contribution technique principale de Yuma, plutôt que l\'électronique qui rend le système sûr pour le réseau.',
      },
      markets: {
        title: 'Marchés confirmés',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: 'Allemagne et Autriche confirmées par la documentation d\'expédition/support de Yuma.',
        content: 'Yuma confirme des ventes et une couverture de support en Allemagne et en Autriche, selon sa propre documentation d\'expédition et de support. Aucun autre marché n\'a été confirmé dans les registres d\'entreprise examinés pour ce profil, et Yuma n\'a annoncé aucune date d\'expansion au-delà de ces deux pays.',
      },
      position: {
        title: 'Positionnement de Yuma',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'Yuma s\'approvisionne en composants auprès d\'autres entreprises de cet ensemble de recherche (Hoymiles, EcoFlow, Anker SOLIX) plutôt que de fabriquer son propre matériel.',
        content: 'La chaîne d\'approvisionnement du solaire de balcon se divise en trois niveaux : fabricants de panneaux, fabricants de micro-onduleurs/batteries et revendeurs de kits qui assemblent les deux en un produit destiné au consommateur. Yuma opère clairement au niveau du revendeur de kits : elle s\'approvisionne en onduleurs et batteries auprès d\'autres entreprises couvertes dans cet ensemble de recherche — Hoymiles, EcoFlow et Anker SOLIX — et concentre sa propre fabrication sur le matériel de fixation plutôt que sur l\'électronique de puissance. Cette structure à un seul niveau est plus typique du marché du solaire de balcon que l\'approche à double niveau utilisée par Anker SOLIX et EcoFlow, qui conçoivent et fabriquent toutes deux leur propre matériel de batterie.',
      },
      partners: {
        title: 'Fournisseurs de composants confirmés',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: 'Cités directement sur la page produit de Yuma — des composants que Yuma assemble en kits plutôt que de fabriquer lui-même.',
        content: 'Yuma cite Hoymiles, EcoFlow et Anker SOLIX directement sur ses propres pages produit comme fournisseurs des onduleurs et batteries intégrés à ses kits. Ce sont des composants que Yuma assemble en produits finis plutôt que du matériel qu\'elle conçoit ou fabrique elle-même. Aucune autre relation fournisseur n\'a été confirmée au-delà de celles citées sur le propre site de Yuma.',
      },
      faqSection: {
        id: 'faq',
        title: 'Questions fréquemment posées',
        faqs: [
          { q: 'Qui possède Yuma ?', a: 'Yuma a été fondée en 2020 par trois cofondateurs et son siège est à Cologne, en Allemagne. L\'entreprise est autofinancée, et aucun tour de financement externe n\'a été trouvé.' },
          { q: 'Yuma est-elle une filiale d\'une entreprise plus grande ?', a: 'Non. Contrairement à Anker SOLIX ou EcoFlow, qui sont des divisions de grandes entreprises électroniques cotées en bourse, Yuma a été identifiée comme une entreprise indépendante et détenue à titre privé.' },
          { q: 'Yuma fabrique-t-elle ses propres onduleurs ou batteries ?', a: 'Non. Yuma assemble des kits à partir de composants tiers. Les fournisseurs confirmés cités sur la propre page produit de Yuma incluent Hoymiles, EcoFlow et Anker SOLIX. La propre contribution produit de Yuma est le matériel de fixation.' },
          { q: 'Que fabrique réellement Yuma elle-même ?', a: 'Le principal effort de fabrication de Yuma porte sur le matériel de fixation, proposé sous différents formats pour diverses surfaces d\'installation comme les garde-corps de balcon, les murs et les toits plats. L\'électronique de puissance des kits provient de fournisseurs tiers.' },
          { q: 'Sur quels marchés Yuma vend-elle ?', a: 'Yuma confirme des ventes et une couverture de support en Allemagne et en Autriche, selon sa propre documentation d\'expédition et de support. Aucun autre marché n\'a été confirmé.' },
          { q: 'Quand Yuma a-t-elle été fondée ?', a: 'Yuma a été fondée en 2020 par trois cofondateurs. L\'année de fondation est confirmée sur la propre page « À propos » de Yuma et corroborée par une mention de TechCrunch en 2022.' },
          { q: 'Comment Yuma se compare-t-elle structurellement à Anker SOLIX ou EcoFlow ?', a: 'Anker SOLIX et EcoFlow conçoivent et fabriquent toutes deux leur propre matériel de batterie en plus de vendre des kits finis — une structure à double niveau. Yuma opère sur un seul niveau : elle s\'approvisionne en onduleurs et batteries auprès d\'autres entreprises, dont Hoymiles, EcoFlow et Anker SOLIX, et concentre sa propre conception sur le matériel de fixation.' },
          { q: 'Yuma est-elle vendue aux États-Unis ?', a: 'Aucune présence sur le marché américain n\'a été confirmée pour Yuma. Ses marchés confirmés, selon la documentation de l\'entreprise, sont l\'Allemagne et l\'Autriche.' },
        ],
      },
    },
  },
  ja: {
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma:ベランダ太陽光発電企業プロフィール',
    seoTitle: 'Yumaのベランダ太陽光企業プロフィール',
    metaDescription: 'Yumaの企業プロフィールです。設立の経緯や所有構造、ベランダ太陽光発電市場における製品ラインナップについて解説します。',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: 'Yumaという企業について調べている読者',
    intro: '本プロフィールでは、企業としてのYumaについて解説します。設立経緯、所有構造、製品ラインナップ、確認済み市場、サプライヤー関係を取り上げます。数値はPromptQuorumのベランダ太陽光発電関連記事全体で使用しているものと同じ登録データ・規格に基づいており、下記の業界概観記事とも整合しています。購入前にベランダ太陽光発電用キットやバッテリーを比較検討したい読者は、専用の比較ページをご覧ください。本記事では価格や購入推奨は扱いません。',
    leadAnswerBlock: '**Yumaは、2020年に3名の共同創業者によってドイツ・ケルンで設立された自己資金運営のベランダ太陽光発電企業で、外部投資家からの出資ラウンドは確認されていません。**Yumaは自社でインバーターやバッテリーを製造しておらず、Hoymiles、EcoFlow、Anker SOLIXなどサードパーティ製のハードウェアを組み合わせてキットを構成しています。自社製品としての貢献は取り付け用ハードウェアであり、設置面に応じて異なります。確認済みの市場はドイツとオーストリアで、Yuma自身の配送・サポート資料に基づいています。',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma:重要な事実',
        items: [
          'Yumaは2020年に3名の共同創業者によって設立され、ドイツ・ケルンに拠点を置いています。',
          '同社は自己資金で運営されており、外部投資家からの出資ラウンドは確認されていません。',
          'Yumaは自社でハードウェアを製造せず、サードパーティ製のインバーターとバッテリーを組み合わせてベランダ太陽光発電キットを構成しています。',
          'Yuma自身の製品ページで確認されているコンポーネントサプライヤーには、Hoymiles、EcoFlow、Anker SOLIXが含まれます。',
          'Yuma自社の製品貢献は取り付け用ハードウェアであり、設置面に応じて異なる形式で提供されています。',
          '確認済みの市場はドイツとオーストリアで、Yuma自身の配送・サポート資料に基づいています。',
        ],
      },
      snapshot: {
        title: 'Yuma:企業スナップショット',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: 'ドイツ・ケルンを拠点とし、2020年に3名の共同創業者が設立。自己資金による運営で、外部投資家からの出資ラウンドは確認されていません。',
        content: 'Yumaはドイツ・ケルンに拠点を置き、2020年に3名の共同創業者によって設立されました。同社は自己資金で運営されており、企業記録や報道の中に外部投資家からの出資ラウンドは見つかっていません。これは、大手上場電子機器企業の一部門であるAnker SOLIXやEcoFlowといったベランダ太陽光発電ブランドとの構造的な違いです。Yumaはキット販売業者として機能しており、自社で電子部品を製造するのではなく、サードパーティ製のインバーターとバッテリーを自社の取り付け用ハードウェアと組み合わせています。',
        snippetBlocks: [
          { type: 'one-sentence', text: 'Yumaは、2020年設立、ドイツ・ケルンを拠点とする自己資金運営のベランダ太陽光発電キット企業です。' },
          { type: 'plain-terms', text: 'Yumaは大手電子機器企業の子会社ではなく、取り付け用ハードウェアを開発し、他社製のインバーターやバッテリーと組み合わせて販売する独立系の非公開ドイツ企業です。' },
        ],
      },
      timeline: {
        title: '沿革',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: '設立年と市場でのプレゼンスは、Yuma自身のAboutページおよび2022年のTechCrunchの記事で確認されています。',
        content: 'Yumaは2020年に3名の共同創業者によってドイツ・ケルンで設立されました。Yuma自身のAboutページが設立年を確認しており、2022年のTechCrunchの記事もこの時期における同社の市場でのプレゼンスを独立して裏付けています。この2つの情報源を超えて、資金調達ラウンド、従業員数、拡大時期といった企業確認済みの節目は見つかっていません。',
      },
      lineup: {
        title: '製品ライン(設置形式)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'Yumaはサードパーティ製のインバーター/バッテリーを組み合わせてキットを構成しています。自社製品は設置面に応じて異なる取り付け用ハードウェアです。',
        content: 'Yumaの製品ラインは取り付け用ハードウェアを中心としており、ベランダの手すり、壁、平屋根といった異なる設置面に対応するため、さまざまな形式で提供されています。各キットに組み込まれるインバーターとバッテリーのコンポーネントは、Yuma自身が設計・製造するのではなく、サードパーティのサプライヤーから調達されています。そのため、Yumaの中核的な技術的貢献は、システムを系統安全にする電子部品ではなく、物理的な取り付けシステムにあります。',
      },
      markets: {
        title: '確認済みの展開市場',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: 'ドイツとオーストリアでの展開は、Yuma自身の配送・サポート資料で確認されています。',
        content: 'Yumaは、自社の配送・サポート資料に基づき、ドイツとオーストリアでの販売とサポート提供を確認しています。本プロフィールの作成にあたって確認した企業記録では、これ以外の市場は確認されておらず、Yumaはこの2カ国を超える展開の時期を発表していません。',
      },
      position: {
        title: 'Yumaの市場ポジション',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'Yumaは自社でハードウェアを製造せず、本調査対象の他企業(Hoymiles、EcoFlow、Anker SOLIX)からコンポーネントを調達しています。',
        content: 'ベランダ太陽光発電のサプライチェーンは、パネルメーカー、マイクロインバーター/バッテリーメーカー、そして両者を組み合わせて消費者向け製品にするキット販売業者の3層に分かれています。Yumaは明確にキット販売業者の層で事業を行っており、本調査対象の他企業であるHoymiles、EcoFlow、Anker SOLIXからインバーターとバッテリーを調達し、自社の製造は電力電子機器ではなく取り付け用ハードウェアに集中しています。この単層構造は、自社でバッテリーハードウェアを設計・製造するAnker SOLIXやEcoFlowの二層アプローチよりも、ベランダ太陽光発電市場においてより一般的です。',
      },
      partners: {
        title: '確認済みの部品サプライヤー',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: 'Yuma自身の製品ページで直接記載されている、Yumaがキットに組み込むコンポーネントです。自社製造ではありません。',
        content: 'Yumaは、自社の製品ページで、キットに組み込むインバーターとバッテリーのサプライヤーとしてHoymiles、EcoFlow、Anker SOLIXを直接記載しています。これらはYumaが完成品に組み立てるコンポーネントであり、自社で設計・製造するハードウェアではありません。Yuma自身のサイトで記載されているもの以外のサプライヤー関係は確認されていません。',
      },
      faqSection: {
        id: 'faq',
        title: 'よくある質問',
        faqs: [
          { q: 'Yumaはどこが所有していますか?', a: 'Yumaは2020年に3名の共同創業者によって設立され、ドイツ・ケルンに拠点を置いています。同社は自己資金で運営されており、外部投資家からの出資ラウンドは見つかっていません。' },
          { q: 'Yumaは大手企業の子会社ですか?', a: 'いいえ。大手上場電子機器企業の一部門であるAnker SOLIXやEcoFlowとは異なり、Yumaは独立した非公開企業であることが確認されています。' },
          { q: 'Yumaは自社でインバーターやバッテリーを製造していますか?', a: 'いいえ。Yumaはサードパーティ製のコンポーネントを組み合わせてキットを構成しています。Yuma自身の製品ページで確認されているサプライヤーには、Hoymiles、EcoFlow、Anker SOLIXが含まれます。Yuma自社の製品貢献は取り付け用ハードウェアです。' },
          { q: 'Yumaは実際に自社で何を製造していますか?', a: 'Yuma自身の製造の中心は取り付け用ハードウェアであり、ベランダの手すり、壁、平屋根といった異なる設置面向けに、さまざまな形式で提供されています。キット内の電力電子機器はサードパーティのサプライヤーから供給されています。' },
          { q: 'Yumaはどの市場で販売していますか?', a: 'Yumaは、自社の配送・サポート資料に基づき、ドイツとオーストリアでの販売とサポート提供を確認しています。それ以外の市場は確認されていません。' },
          { q: 'Yumaはいつ設立されましたか?', a: 'Yumaは2020年に3名の共同創業者によって設立されました。設立年はYuma自身のAboutページで確認されており、2022年のTechCrunchの記事によっても裏付けられています。' },
          { q: 'YumaはAnker SOLIXやEcoFlowと構造的にどう違いますか?', a: 'Anker SOLIXとEcoFlowはいずれも、完成キットの販売に加えて自社でバッテリーハードウェアを設計・製造する二層構造を持っています。一方Yumaは単一の層で事業を行っており、Hoymiles、EcoFlow、Anker SOLIXを含む他企業からインバーターとバッテリーを調達し、自社の開発は取り付け用ハードウェアに集中しています。' },
          { q: 'Yumaは米国で販売されていますか?', a: 'Yumaの米国市場での展開は確認されていません。企業資料によれば、確認済みの市場はドイツとオーストリアです。' },
        ],
      },
    },
  },
  zh: {
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma:阳台太阳能公司简介',
    seoTitle: 'Yuma阳台太阳能公司简介',
    metaDescription: 'Yuma公司简介:介绍其发展历程、所有权结构、总部所在地以及在阳台太阳能市场的产品线概况。',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: '正在研究Yuma这家公司的读者',
    intro: '本简介介绍作为公司的Yuma:其创立历程、所有权结构、产品线、已确认的市场以及供应商关系。内容参考了PromptQuorum阳台太阳能全部报道中使用的相同注册数据与标准,包括下方链接的行业概览。如果读者是在购买前比较阳台太阳能套件或电池,建议改为查阅专门的对比页面——本页不涉及价格或购买建议。',
    leadAnswerBlock: '**Yuma是一家自筹资金运营的阳台太阳能公司,总部位于德国科隆,由三位联合创始人于2020年创立,未发现任何外部投资方参与融资。**Yuma并不自行制造逆变器或电池——公司使用第三方组件组装套件,包括来自Hoymiles、EcoFlow和Anker SOLIX的硬件,其自有产品贡献是安装硬件,具体形式因安装表面而异。已确认的市场为德国和奥地利,依据Yuma官方的配送与支持文档。',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma:核心事实',
        items: [
          'Yuma由三位联合创始人于2020年创立,总部位于德国科隆。',
          '公司为自筹资金运营——未发现外部投资方参与融资的记录。',
          'Yuma使用第三方逆变器和电池组装阳台太阳能套件,而非自行制造硬件。',
          'Yuma官方产品页面确认的组件供应商包括Hoymiles、EcoFlow和Anker SOLIX。',
          'Yuma自有的产品贡献是安装硬件,根据安装表面不同提供不同形式。',
          '已确认的市场为德国和奥地利,依据Yuma官方的配送与支持文档。',
        ],
      },
      snapshot: {
        title: 'Yuma:公司概况',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: '总部位于德国科隆;由三位联合创始人于2020年创立;自筹资金运营,未发现外部投资方参与融资。',
        content: 'Yuma总部位于德国科隆,由三位联合创始人于2020年创立。公司为自筹资金运营,在公司记录及媒体报道中均未发现有外部投资方参与融资——这与Anker SOLIX、EcoFlow等隶属于更大规模上市电子公司的阳台太阳能品牌在结构上有所不同。Yuma的定位是套件经销商:公司将第三方逆变器和电池与自有安装硬件组合在一起,而非自行制造电子元件。',
        snippetBlocks: [
          { type: 'one-sentence', text: 'Yuma是一家自筹资金运营的阳台太阳能套件公司,成立于2020年,总部位于德国科隆。' },
          { type: 'plain-terms', text: 'Yuma并非某家大型电子公司的子公司——它是一家独立的、私人持有的德国初创企业,负责开发安装硬件,并将其与其他公司生产的逆变器和电池搭配销售。' },
        ],
      },
      timeline: {
        title: '发展历程',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: '成立年份和市场存在已通过Yuma官方"关于我们"页面及2022年TechCrunch的报道得到确认。',
        content: 'Yuma由三位联合创始人于2020年在德国科隆创立。Yuma官方的"关于我们"页面确认了成立年份,2022年TechCrunch的一篇报道也独立佐证了公司在那一时期的市场存在。除这两个信息来源外,未发现其他经公司确认的重要节点,例如融资轮次、员工规模或扩张日期。',
      },
      lineup: {
        title: '产品线(安装形式)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'Yuma使用第三方逆变器/电池组装套件——其自有产品是安装硬件,根据安装表面不同而有所差异。',
        content: 'Yuma的产品线以安装硬件为核心,提供不同形式以适配阳台栏杆、墙面和平屋顶等不同的安装表面。每套套件中包含的逆变器和电池组件均来自第三方供应商,而非由Yuma自行设计或制造。这意味着Yuma的核心技术贡献在于物理安装系统,而非使系统电网安全的电子元件。',
      },
      markets: {
        title: '已确认的市场',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: '德国和奥地利已通过Yuma官方的配送/支持文档得到确认。',
        content: 'Yuma依据其官方的配送与支持文档,确认在德国和奥地利提供销售与支持服务。在为本简介审查的公司记录中,未发现其他已确认的市场,Yuma也未公布在这两个国家之外扩张的时间表。',
      },
      position: {
        title: 'Yuma的市场定位',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'Yuma从本次调研涉及的其他公司(Hoymiles、EcoFlow、Anker SOLIX)采购组件,而非自行制造硬件。',
        content: '阳台太阳能供应链分为三个层级:面板制造商、微型逆变器/电池制造商,以及将两者组装成消费者产品的套件经销商。Yuma明确处于套件经销商这一层级:公司从本次调研涉及的其他公司——Hoymiles、EcoFlow和Anker SOLIX——采购逆变器和电池,并将自身制造重心放在安装硬件而非电力电子元件上。这种单层结构在阳台太阳能市场中更为常见,不同于Anker SOLIX和EcoFlow采用的双层模式,后两者均自行设计和制造电池硬件。',
      },
      partners: {
        title: '已确认的组件供应商',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: '直接标注于Yuma官方产品页面——这些组件由Yuma组装进套件,而非自行制造。',
        content: 'Yuma在其官方产品页面上直接标明Hoymiles、EcoFlow和Anker SOLIX为套件中所用逆变器和电池的供应商。这些组件由Yuma组装成成品,而非由公司自行设计或制造的硬件。除Yuma官网标明的供应商外,未发现其他已确认的供应商关系。',
      },
      faqSection: {
        id: 'faq',
        title: '常见问题',
        faqs: [
          { q: 'Yuma归谁所有?', a: 'Yuma由三位联合创始人于2020年创立,总部位于德国科隆。公司为自筹资金运营,未发现外部投资方参与融资的记录。' },
          { q: 'Yuma是某家大公司的子公司吗?', a: '不是。与隶属于大型上市电子公司的Anker SOLIX或EcoFlow不同,Yuma被确认为一家独立的、私人持有的公司。' },
          { q: 'Yuma是否自行制造逆变器或电池?', a: '不是。Yuma使用第三方组件组装套件。Yuma官方产品页面确认的供应商包括Hoymiles、EcoFlow和Anker SOLIX。Yuma自有的产品贡献是安装硬件。' },
          { q: 'Yuma实际自行制造什么?', a: 'Yuma自身的制造重点是安装硬件,针对阳台栏杆、墙面和平屋顶等不同安装表面提供不同形式。套件中的电力电子元件来自第三方供应商。' },
          { q: 'Yuma在哪些市场销售?', a: 'Yuma依据其官方的配送与支持文档,确认在德国和奥地利提供销售与支持服务。未发现其他已确认的市场。' },
          { q: 'Yuma何时成立?', a: 'Yuma由三位联合创始人于2020年创立。成立年份已在Yuma官方"关于我们"页面得到确认,并由2022年TechCrunch的一篇报道佐证。' },
          { q: 'Yuma在结构上与Anker SOLIX或EcoFlow有何不同?', a: 'Anker SOLIX和EcoFlow除销售成品套件外,均自行设计和制造电池硬件——属于双层结构。Yuma仅在单一层级运营:从包括Hoymiles、EcoFlow和Anker SOLIX在内的其他公司采购逆变器和电池,自身的开发重心集中在安装硬件上。' },
          { q: 'Yuma在美国有售吗?', a: '目前未确认Yuma在美国市场有业务存在。根据公司文档,已确认的市场为德国和奥地利。' },
        ],
      },
    },
  },
  es: {
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma: perfil de la empresa de solar de balcón',
    seoTitle: 'Yuma: perfil de la empresa de solar de balcón',
    metaDescription: 'Perfil de la empresa Yuma: historia, estructura de propiedad, sede y gama de productos en el mercado de la energía solar de balcón.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: 'Lectores que investigan a Yuma como empresa',
    intro: 'Este perfil cubre a Yuma como empresa: su fundación, estructura de propiedad, gama de productos, mercados confirmados y relaciones con proveedores. Se basa en los mismos datos de registro y normas citados en toda la cobertura de solar de balcón de PromptQuorum, incluido el resumen del sector enlazado más abajo. Los lectores que comparan kits o baterías solares de balcón antes de comprar deberían consultar en su lugar las páginas de comparación dedicadas — esta página no cubre precios ni una recomendación de compra.',
    leadAnswerBlock: '**Yuma es una empresa de solar de balcón autofinanciada, con sede en Colonia (Alemania), fundada en 2020 por tres cofundadores, sin ninguna ronda de inversión externa identificada.** Yuma no fabrica sus propios inversores ni baterías: ensambla kits con componentes de terceros, incluido hardware de Hoymiles, EcoFlow y Anker SOLIX, y su propia contribución de producto es el hardware de montaje, que varía según la superficie de instalación. Los mercados confirmados son Alemania y Austria, según la propia documentación de envío y soporte de Yuma.',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma: datos clave',
        items: [
          'Yuma fue fundada en 2020 por tres cofundadores y tiene su sede en Colonia, Alemania.',
          'La empresa es autofinanciada — no se ha encontrado ninguna ronda de inversión externa.',
          'Yuma ensambla kits solares de balcón con inversores y baterías de terceros en lugar de fabricar su propio hardware.',
          'Los proveedores de componentes confirmados, citados en las propias páginas de producto de Yuma, incluyen Hoymiles, EcoFlow y Anker SOLIX.',
          'La contribución propia de Yuma al producto es el hardware de montaje, ofrecido en distintos formatos según la superficie de instalación.',
          'Los mercados confirmados son Alemania y Austria, según la propia documentación de envío y soporte de Yuma.',
        ],
      },
      snapshot: {
        title: 'Yuma: resumen de la empresa',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: 'Colonia (Alemania); fundada en 2020 por tres cofundadores; autofinanciada, sin ninguna ronda de inversión externa identificada.',
        content: 'Yuma tiene su sede en Colonia, Alemania, y fue fundada en 2020 por tres cofundadores. La empresa es autofinanciada, y no se ha encontrado ninguna ronda de inversión externa en registros corporativos ni en cobertura de prensa — una diferencia estructural respecto a marcas de solar de balcón como Anker SOLIX y EcoFlow, que son divisiones de empresas electrónicas cotizadas en bolsa más grandes. Yuma opera como revendedor de kits: combina inversores y baterías de terceros con su propio hardware de montaje en lugar de fabricar la electrónica ella misma.',
        snippetBlocks: [
          { type: 'one-sentence', text: 'Yuma es una empresa autofinanciada de kits solares de balcón, fundada en 2020 y con sede en Colonia, Alemania.' },
          { type: 'plain-terms', text: 'Yuma no es una filial de una gran empresa electrónica; es una startup alemana independiente y de propiedad privada que desarrolla hardware de montaje y lo combina con inversores y baterías de otras compañías.' },
        ],
      },
      timeline: {
        title: 'Cronología',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: 'El año de fundación y la presencia en el mercado se confirman en la página "Acerca de" de Yuma y en una mención de TechCrunch de 2022.',
        content: 'Yuma fue fundada en 2020 por tres cofundadores en Colonia, Alemania. La propia página "Acerca de" de Yuma confirma el año de fundación, y una mención de TechCrunch de 2022 corrobora de forma independiente la presencia de la empresa en el mercado durante ese periodo. No se han encontrado más hitos confirmados por la empresa —como rondas de financiación, número de empleados o fechas de expansión— más allá de estas dos fuentes.',
      },
      lineup: {
        title: 'Línea de productos (formatos de montaje)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'Yuma ensambla kits con inversores/baterías de terceros; su propio producto es el hardware de montaje, que varía según la superficie de instalación.',
        content: 'La línea de productos de Yuma se centra en el hardware de montaje, ofrecido en distintos formatos para adaptarse a diferentes superficies de instalación, como barandillas de balcón, paredes y tejados planos. Los componentes de inversor y batería incluidos en cada kit provienen de proveedores externos en lugar de ser diseñados o fabricados por la propia Yuma. Esto convierte al sistema de montaje físico en la principal contribución técnica de Yuma, en lugar de la electrónica que hace que el sistema sea seguro para la red.',
      },
      markets: {
        title: 'Mercados confirmados',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: 'Alemania y Austria confirmados mediante la documentación de envío/soporte propia de Yuma.',
        content: 'Yuma confirma ventas y cobertura de soporte en Alemania y Austria, según su propia documentación de envío y soporte. No se ha confirmado ningún otro mercado en los registros corporativos revisados para este perfil, y Yuma no ha indicado una fecha de expansión más allá de estos dos países.',
      },
      position: {
        title: 'Posicionamiento de Yuma',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'Yuma obtiene componentes de otras empresas de este conjunto de investigación (Hoymiles, EcoFlow, Anker SOLIX) en lugar de fabricar su propio hardware.',
        content: 'La cadena de suministro del solar de balcón se divide en tres niveles: fabricantes de paneles, fabricantes de microinversores/baterías y revendedores de kits que combinan ambos en un producto de consumo. Yuma opera claramente en el nivel de revendedor de kits: obtiene inversores y baterías de otras empresas cubiertas en este conjunto de investigación —Hoymiles, EcoFlow y Anker SOLIX— y centra su propia fabricación en el hardware de montaje en lugar de en la electrónica de potencia. Esta estructura de un solo nivel es más típica del mercado del solar de balcón que el enfoque de doble nivel utilizado por Anker SOLIX y EcoFlow, que diseñan y fabrican su propio hardware de batería.',
      },
      partners: {
        title: 'Proveedores de componentes confirmados',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: 'Mencionados directamente en la propia página de producto de Yuma: componentes que Yuma integra en kits en lugar de fabricar.',
        content: 'Yuma menciona directamente en sus propias páginas de producto a Hoymiles, EcoFlow y Anker SOLIX como proveedores de los inversores y baterías integrados en sus kits. Se trata de componentes que Yuma ensambla en productos terminados, no de hardware que diseñe o fabrique ella misma. No se han confirmado más relaciones con proveedores más allá de las mencionadas en el propio sitio de Yuma.',
      },
      faqSection: {
        id: 'faq',
        title: 'Preguntas frecuentes',
        faqs: [
          { q: '¿Quién es propietario de Yuma?', a: 'Yuma fue fundada en 2020 por tres cofundadores y tiene su sede en Colonia, Alemania. La empresa es autofinanciada, y no se ha encontrado ninguna ronda de inversión externa.' },
          { q: '¿Es Yuma una filial de una empresa más grande?', a: 'No. A diferencia de Anker SOLIX o EcoFlow, que son divisiones de grandes empresas electrónicas cotizadas en bolsa, se ha identificado a Yuma como una empresa independiente y de propiedad privada.' },
          { q: '¿Fabrica Yuma sus propios inversores o baterías?', a: 'No. Yuma ensambla kits con componentes de terceros. Los proveedores confirmados mencionados en la propia página de producto de Yuma incluyen Hoymiles, EcoFlow y Anker SOLIX. La propia contribución de producto de Yuma es el hardware de montaje.' },
          { q: '¿Qué fabrica Yuma realmente por sí misma?', a: 'El principal enfoque de fabricación propia de Yuma es el hardware de montaje, ofrecido en distintos formatos para diferentes superficies de instalación, como barandillas de balcón, paredes y tejados planos. La electrónica de potencia de sus kits proviene de proveedores externos.' },
          { q: '¿En qué mercados vende Yuma?', a: 'Yuma confirma ventas y cobertura de soporte en Alemania y Austria, según su propia documentación de envío y soporte. No se ha confirmado ningún otro mercado.' },
          { q: '¿Cuándo se fundó Yuma?', a: 'Yuma fue fundada en 2020 por tres cofundadores. El año de fundación se confirma en la propia página "Acerca de" de Yuma y se corrobora con una mención de TechCrunch de 2022.' },
          { q: '¿Cómo se compara Yuma estructuralmente con Anker SOLIX o EcoFlow?', a: 'Anker SOLIX y EcoFlow diseñan y fabrican su propio hardware de batería además de vender kits terminados, una estructura de doble nivel. Yuma opera en un solo nivel: obtiene inversores y baterías de otras empresas, incluidas Hoymiles, EcoFlow y Anker SOLIX, y centra su propio desarrollo en el hardware de montaje.' },
          { q: '¿Se vende Yuma en Estados Unidos?', a: 'No se ha confirmado ninguna presencia de Yuma en el mercado estadounidense. Sus mercados confirmados, según la documentación de la empresa, son Alemania y Austria.' },
        ],
      },
    },
  },
  pt: {
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma: perfil da empresa de energia solar de varanda',
    seoTitle: 'Yuma: perfil da empresa de solar de varanda',
    metaDescription: 'Perfil da empresa Yuma: histórico, estrutura societária, sede e linha de produtos no mercado de energia solar de varanda.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: 'Leitores que estão pesquisando a empresa Yuma',
    intro: 'Este perfil aborda a Yuma como empresa: sua fundação, estrutura societária, linha de produtos, mercados confirmados e relações com fornecedores. Baseia-se nos mesmos dados de registro e normas citados em toda a cobertura de energia solar de varanda da PromptQuorum, incluindo a visão geral do setor com link mais abaixo. Leitores que estão comparando kits ou baterias solares de varanda antes de comprar devem consultar as páginas de comparação dedicadas — este texto não trata de preços nem traz recomendação de compra.',
    leadAnswerBlock: '**A Yuma é uma empresa de energia solar de varanda autofinanciada, sediada em Colônia, na Alemanha, fundada em 2020 por três cofundadores, sem nenhuma rodada de investimento externo identificada.** A Yuma não fabrica seus próprios inversores nem baterias — a empresa monta kits com componentes de terceiros, incluindo hardware da Hoymiles, EcoFlow e Anker SOLIX, e sua própria contribuição de produto é o hardware de montagem, que varia conforme a superfície de instalação. Os mercados confirmados são Alemanha e Áustria, segundo a própria documentação de envio e suporte da Yuma.',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma: principais fatos',
        items: [
          'A Yuma foi fundada em 2020 por três cofundadores e tem sede em Colônia, Alemanha.',
          'A empresa é autofinanciada — nenhuma rodada de investimento externo foi encontrada.',
          'A Yuma monta kits solares de varanda com inversores e baterias de terceiros, em vez de fabricar seu próprio hardware.',
          'Os fornecedores de componentes confirmados, citados nas próprias páginas de produto da Yuma, incluem Hoymiles, EcoFlow e Anker SOLIX.',
          'A própria contribuição de produto da Yuma é o hardware de montagem, oferecido em diferentes formatos conforme a superfície de instalação.',
          'Os mercados confirmados são Alemanha e Áustria, segundo a própria documentação de envio e suporte da Yuma.',
        ],
      },
      snapshot: {
        title: 'Yuma: visão geral da empresa',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: 'Colônia, Alemanha; fundada em 2020 por três cofundadores; autofinanciada, sem nenhuma rodada de investimento externo identificada.',
        content: 'A Yuma tem sede em Colônia, Alemanha, e foi fundada em 2020 por três cofundadores. A empresa é autofinanciada, e nenhuma rodada de investimento externo foi encontrada em registros corporativos ou na cobertura da imprensa — uma diferença estrutural em relação a marcas de energia solar de varanda como a Anker SOLIX e a EcoFlow, que são divisões de empresas eletrônicas maiores e listadas em bolsa. A Yuma atua como revendedora de kits: combina inversores e baterias de terceiros com seu próprio hardware de montagem, em vez de fabricar a eletrônica ela mesma.',
        snippetBlocks: [
          { type: 'one-sentence', text: 'A Yuma é uma empresa autofinanciada de kits solares de varanda, fundada em 2020 e sediada em Colônia, Alemanha.' },
          { type: 'plain-terms', text: 'A Yuma não é subsidiária de uma grande empresa eletrônica — é uma startup alemã independente e de capital fechado que desenvolve hardware de montagem e o combina com inversores e baterias de outras empresas.' },
        ],
      },
      timeline: {
        title: 'Linha do tempo',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: 'Ano de fundação e presença no mercado confirmados pela própria página "Sobre" da Yuma e por uma menção do TechCrunch em 2022.',
        content: 'A Yuma foi fundada em 2020 por três cofundadores em Colônia, Alemanha. A própria página "Sobre" da Yuma confirma o ano de fundação, e uma menção do TechCrunch em 2022 corrobora de forma independente a presença da empresa no mercado naquele período. Nenhum outro marco confirmado pela empresa — como rodadas de financiamento, número de funcionários ou datas de expansão — foi encontrado além dessas duas fontes.',
      },
      lineup: {
        title: 'Linha de produtos (formatos de montagem)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'A Yuma monta kits com inversores/baterias de terceiros — seu próprio produto é o hardware de montagem, que varia conforme a superfície de instalação.',
        content: 'A linha de produtos da Yuma se concentra no hardware de montagem, oferecido em diferentes formatos para se adaptar a superfícies de instalação distintas, como grades de varanda, paredes e telhados planos. Os componentes de inversor e bateria incluídos em cada kit vêm de fornecedores terceiros, em vez de serem projetados ou fabricados pela própria Yuma. Isso faz do sistema físico de montagem a principal contribuição técnica da Yuma, em vez da eletrônica que torna o sistema seguro para a rede.',
      },
      markets: {
        title: 'Mercados confirmados',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: 'Alemanha e Áustria confirmados pela própria documentação de envio/suporte da Yuma.',
        content: 'A Yuma confirma vendas e cobertura de suporte na Alemanha e na Áustria, segundo sua própria documentação de envio e suporte. Nenhum outro mercado foi confirmado nos registros corporativos revisados para este perfil, e a Yuma não informou uma data para expansão além desses dois países.',
      },
      position: {
        title: 'Posicionamento da Yuma',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'A Yuma adquire componentes de outras empresas deste conjunto de pesquisa (Hoymiles, EcoFlow, Anker SOLIX) em vez de fabricar seu próprio hardware.',
        content: 'A cadeia de suprimentos da energia solar de varanda se divide em três camadas: fabricantes de painéis, fabricantes de microinversores/baterias e revendedores de kits que combinam os dois em um produto de consumo. A Yuma atua claramente na camada de revendedora de kits: adquire inversores e baterias de outras empresas cobertas neste conjunto de pesquisa — Hoymiles, EcoFlow e Anker SOLIX — e concentra sua própria fabricação em hardware de montagem, e não em eletrônica de potência. Essa estrutura de camada única é mais típica do mercado de energia solar de varanda do que a abordagem de dupla camada usada pela Anker SOLIX e pela EcoFlow, que projetam e fabricam seu próprio hardware de bateria.',
      },
      partners: {
        title: 'Fornecedores de componentes confirmados',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: 'Citados diretamente na própria página de produto da Yuma — componentes que a Yuma monta em kits em vez de fabricar.',
        content: 'A Yuma cita diretamente em suas próprias páginas de produto a Hoymiles, a EcoFlow e a Anker SOLIX como fornecedoras dos inversores e baterias montados em seus kits. São componentes que a Yuma monta em produtos finalizados, e não hardware que ela mesma projeta ou fabrica. Nenhuma outra relação com fornecedores foi confirmada além das citadas no próprio site da Yuma.',
      },
      faqSection: {
        id: 'faq',
        title: 'Perguntas frequentes',
        faqs: [
          { q: 'Quem é dono da Yuma?', a: 'A Yuma foi fundada em 2020 por três cofundadores e tem sede em Colônia, Alemanha. A empresa é autofinanciada, e nenhuma rodada de investimento externo foi encontrada.' },
          { q: 'A Yuma é subsidiária de uma empresa maior?', a: 'Não. Diferentemente da Anker SOLIX ou da EcoFlow, que são divisões de grandes empresas eletrônicas listadas em bolsa, a Yuma foi identificada como uma empresa independente e de capital fechado.' },
          { q: 'A Yuma fabrica seus próprios inversores ou baterias?', a: 'Não. A Yuma monta kits com componentes de terceiros. Os fornecedores confirmados citados na própria página de produto da Yuma incluem Hoymiles, EcoFlow e Anker SOLIX. A própria contribuição de produto da Yuma é o hardware de montagem.' },
          { q: 'O que a Yuma realmente fabrica por conta própria?', a: 'O foco de fabricação própria da Yuma é o hardware de montagem, oferecido em diferentes formatos para diferentes superfícies de instalação, como grades de varanda, paredes e telhados planos. A eletrônica de potência de seus kits vem de fornecedores terceiros.' },
          { q: 'Em quais mercados a Yuma vende?', a: 'A Yuma confirma vendas e cobertura de suporte na Alemanha e na Áustria, segundo sua própria documentação de envio e suporte. Nenhum outro mercado foi confirmado.' },
          { q: 'Quando a Yuma foi fundada?', a: 'A Yuma foi fundada em 2020 por três cofundadores. O ano de fundação é confirmado na própria página "Sobre" da Yuma e corroborado por uma menção do TechCrunch em 2022.' },
          { q: 'Como a Yuma se compara estruturalmente à Anker SOLIX ou à EcoFlow?', a: 'A Anker SOLIX e a EcoFlow projetam e fabricam seu próprio hardware de bateria além de vender kits finalizados — uma estrutura de dupla camada. A Yuma atua em uma única camada: adquire inversores e baterias de outras empresas, incluindo Hoymiles, EcoFlow e Anker SOLIX, e concentra seu próprio desenvolvimento no hardware de montagem.' },
          { q: 'A Yuma é vendida nos Estados Unidos?', a: 'Nenhuma presença da Yuma no mercado americano foi confirmada. Seus mercados confirmados, segundo a documentação da empresa, são Alemanha e Áustria.' },
        ],
      },
    },
  },
  ar: {
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma: الملف التعريفي لشركة الطاقة الشمسية للشرفات',
    seoTitle: 'Yuma: ملف الشركة للطاقة الشمسية للشرفات',
    metaDescription: 'ملف تعريفي لشركة Yuma: التاريخ، وهيكل الملكية، ومجموعة المنتجات في سوق الطاقة الشمسية للشرفات.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: 'القراء الذين يبحثون عن شركة Yuma',
    intro: 'يتناول هذا الملف التعريفي شركة Yuma من الناحية المؤسسية: تأسيسها، وهيكل ملكيتها، ومجموعة منتجاتها، والأسواق المؤكدة، وعلاقاتها مع الموردين. يستند إلى نفس بيانات السجلات والمعايير المستخدمة في تغطية PromptQuorum بأكملها للطاقة الشمسية للشرفات، بما في ذلك نظرة السوق والصناعة العامة المرتبطة أدناه. القراء الذين يقارنون أطقم أو بطاريات الطاقة الشمسية للشرفات قبل الشراء يجب عليهم مراجعة صفحات المقارنة المخصصة بدلاً من ذلك — لا تتناول هذه الصفحة الأسعار أو توصية شراء.',
    leadAnswerBlock: '**Yuma هي شركة طاقة شمسية للشرفات ممولة ذاتيًا، ومقرها كولونيا، ألمانيا، تأسست عام 2020 على يد ثلاثة شركاء مؤسسين، ولم يُعثر على أي جولة استثمار خارجية.** لا تصنّع Yuma عاكساتها أو بطارياتها الخاصة — بل تجمّع أطقمًا من مكونات جهات خارجية، بما في ذلك عتاد من Hoymiles وEcoFlow وAnker SOLIX، ومساهمتها الخاصة في المنتج هي عتاد التركيب، الذي يختلف حسب سطح التركيب. الأسواق المؤكدة هي ألمانيا والنمسا، وفقًا لوثائق الشحن والدعم الخاصة بشركة Yuma.',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma: أهم الحقائق',
        items: [
          'تأسست Yuma عام 2020 على يد ثلاثة شركاء مؤسسين، ويقع مقرها في كولونيا، ألمانيا.',
          'الشركة ممولة ذاتيًا — لم يُعثر على أي جولة استثمار خارجية.',
          'تجمّع Yuma أطقم الطاقة الشمسية للشرفات من عاكسات وبطاريات جهات خارجية بدلاً من تصنيع عتادها الخاص.',
          'من موردي المكونات المؤكدين المذكورين على صفحات منتجات Yuma الخاصة: Hoymiles وEcoFlow وAnker SOLIX.',
          'مساهمة Yuma الخاصة في المنتج هي عتاد التركيب، المتوفر بأشكال مختلفة حسب سطح التركيب.',
          'الأسواق المؤكدة هي ألمانيا والنمسا، وفقًا لوثائق الشحن والدعم الخاصة بشركة Yuma.',
        ],
      },
      snapshot: {
        title: 'Yuma: لمحة عن الشركة',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: 'كولونيا، ألمانيا؛ تأسست عام 2020 على يد ثلاثة شركاء مؤسسين؛ ممولة ذاتيًا، ولم يُعثر على أي جولة استثمار خارجية.',
        content: 'يقع مقر Yuma في كولونيا، ألمانيا، وقد تأسست عام 2020 على يد ثلاثة شركاء مؤسسين. الشركة ممولة ذاتيًا، ولم يُعثر على أي جولة استثمار خارجية في سجلات الشركة أو في التغطية الصحفية — وهو اختلاف هيكلي عن علامات الطاقة الشمسية للشرفات مثل Anker SOLIX وEcoFlow، وهما وحدتان تابعتان لشركات إلكترونيات أكبر مدرجة في البورصة. تعمل Yuma كموزّع أطقم: فهي تجمع عاكسات وبطاريات من جهات خارجية مع عتاد التركيب الخاص بها بدلاً من تصنيع الإلكترونيات بنفسها.',
        snippetBlocks: [
          { type: 'one-sentence', text: 'Yuma هي شركة أطقم طاقة شمسية للشرفات ممولة ذاتيًا، تأسست عام 2020 ومقرها كولونيا، ألمانيا.' },
          { type: 'plain-terms', text: 'Yuma ليست تابعة لشركة إلكترونيات كبرى — بل هي شركة ناشئة ألمانية مستقلة ومملوكة ملكية خاصة، تطوّر عتاد التركيب وتجمعه مع عاكسات وبطاريات من شركات أخرى.' },
        ],
      },
      timeline: {
        title: 'الجدول الزمني',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: 'تم تأكيد سنة التأسيس والوجود في السوق عبر صفحة "About" الخاصة بشركة Yuma وإشارة من TechCrunch عام 2022.',
        content: 'تأسست Yuma عام 2020 على يد ثلاثة شركاء مؤسسين في كولونيا، ألمانيا. تؤكد صفحة "About" الخاصة بشركة Yuma سنة التأسيس، وتدعم إشارة من TechCrunch عام 2022 بشكل مستقل وجود الشركة في السوق خلال تلك الفترة. لم يُعثر على أي محطات أخرى مؤكدة من الشركة — مثل جولات التمويل أو عدد الموظفين أو تواريخ التوسع — بخلاف هذين المصدرين.',
      },
      lineup: {
        title: 'خط المنتجات (أشكال التركيب)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'تجمّع Yuma أطقمًا من عاكسات وبطاريات من جهات خارجية — ومنتجها الخاص هو عتاد التركيب، الذي يختلف حسب سطح التركيب.',
        content: 'يتمحور خط منتجات Yuma حول عتاد التركيب، المتوفر بأشكال مختلفة لملاءمة أسطح تركيب مختلفة مثل درابزين الشرفة والجدران والأسطح المسطحة. تأتي مكونات العاكس والبطارية المدمجة في كل طقم من موردين خارجيين بدلاً من أن تصممها أو تصنّعها Yuma بنفسها. وهذا يجعل مساهمة Yuma التقنية الأساسية في نظام التركيب المادي وليس الإلكترونيات التي تجعل النظام آمنًا للشبكة.',
      },
      markets: {
        title: 'الأسواق المؤكدة',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: 'تم تأكيد ألمانيا والنمسا عبر وثائق الشحن والدعم الخاصة بشركة Yuma.',
        content: 'تؤكد Yuma المبيعات وتغطية الدعم في ألمانيا والنمسا، وفقًا لوثائق الشحن والدعم الخاصة بها. لم تُؤكَّد أي أسواق أخرى في سجلات الشركة التي تمت مراجعتها لهذا الملف التعريفي، ولم تُعلن Yuma عن تاريخ للتوسع خارج هذين البلدين.',
      },
      position: {
        title: 'موقع Yuma في السوق',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'تحصل Yuma على المكونات من شركات أخرى ضمن مجموعة البحث هذه (Hoymiles وEcoFlow وAnker SOLIX) بدلاً من تصنيع عتادها الخاص.',
        content: 'تنقسم سلسلة إمداد الطاقة الشمسية للشرفات إلى ثلاث طبقات: مصنّعو الألواح، ومصنّعو المُحوّلات الدقيقة/البطاريات، وموزّعو الأطقم الذين يجمّعون الاثنين في منتج استهلاكي. تعمل Yuma بوضوح في طبقة موزّعي الأطقم: فهي تحصل على العاكسات والبطاريات من شركات أخرى مشمولة في مجموعة البحث هذه — Hoymiles وEcoFlow وAnker SOLIX — وتركّز تصنيعها الخاص على عتاد التركيب بدلاً من إلكترونيات الطاقة. هذا الهيكل أحادي الطبقة أكثر شيوعًا في سوق الطاقة الشمسية للشرفات من النهج ثنائي الطبقة الذي تتبعه Anker SOLIX وEcoFlow، اللتان تصممان وتصنّعان عتاد البطارية الخاص بهما.',
      },
      partners: {
        title: 'موردو المكونات المؤكدون',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: 'مذكورون مباشرة على صفحة منتج Yuma الخاصة — وهي مكونات تجمّعها Yuma ضمن أطقم بدلاً من تصنيعها بنفسها.',
        content: 'تذكر Yuma مباشرة على صفحات منتجاتها الخاصة كلًا من Hoymiles وEcoFlow وAnker SOLIX كموردين للعاكسات والبطاريات المدمجة في أطقمها. وهي مكونات تجمّعها Yuma في منتجات نهائية، وليست عتادًا تصممه أو تصنّعه بنفسها. لم تُؤكَّد أي علاقات موردين أخرى بخلاف تلك المذكورة على موقع Yuma نفسه.',
      },
      faqSection: {
        id: 'faq',
        title: 'الأسئلة الشائعة',
        faqs: [
          { q: 'من يملك Yuma؟', a: 'تأسست Yuma عام 2020 على يد ثلاثة شركاء مؤسسين، ويقع مقرها في كولونيا، ألمانيا. الشركة ممولة ذاتيًا، ولم يُعثر على أي جولة استثمار خارجية.' },
          { q: 'هل Yuma تابعة لشركة أكبر؟', a: 'لا. على عكس Anker SOLIX أو EcoFlow، وهما وحدتان تابعتان لشركات إلكترونيات أكبر مدرجة في البورصة، تم تحديد Yuma كشركة مستقلة ومملوكة ملكية خاصة.' },
          { q: 'هل تصنّع Yuma عاكساتها أو بطارياتها الخاصة؟', a: 'لا. تجمّع Yuma أطقمًا من مكونات جهات خارجية. من الموردين المؤكدين المذكورين على صفحة منتج Yuma الخاصة: Hoymiles وEcoFlow وAnker SOLIX. مساهمة Yuma الخاصة في المنتج هي عتاد التركيب.' },
          { q: 'ماذا تصنّع Yuma فعليًا بنفسها؟', a: 'ينصب تركيز التصنيع الخاص بشركة Yuma على عتاد التركيب، المتوفر بأشكال مختلفة لأسطح تركيب مختلفة مثل درابزين الشرفة والجدران والأسطح المسطحة. تأتي إلكترونيات الطاقة داخل أطقمها من موردين خارجيين.' },
          { q: 'في أي أسواق تبيع Yuma؟', a: 'تؤكد Yuma المبيعات وتغطية الدعم في ألمانيا والنمسا، وفقًا لوثائق الشحن والدعم الخاصة بها. لم تُؤكَّد أي أسواق أخرى.' },
          { q: 'متى تأسست Yuma؟', a: 'تأسست Yuma عام 2020 على يد ثلاثة شركاء مؤسسين. تم تأكيد سنة التأسيس على صفحة "About" الخاصة بشركة Yuma، وتدعمها إشارة من TechCrunch عام 2022.' },
          { q: 'كيف تقارن Yuma هيكليًا بشركة Anker SOLIX أو EcoFlow؟', a: 'تصمم كل من Anker SOLIX وEcoFlow وتصنّعان عتاد البطارية الخاص بهما بالإضافة إلى بيع أطقم جاهزة — وهو هيكل ثنائي الطبقة. تعمل Yuma في طبقة واحدة فقط: فهي تحصل على العاكسات والبطاريات من شركات أخرى، بما فيها Hoymiles وEcoFlow وAnker SOLIX، وتركّز تطويرها الخاص على عتاد التركيب.' },
          { q: 'هل تُباع Yuma في الولايات المتحدة؟', a: 'لم يُؤكَّد أي وجود لشركة Yuma في السوق الأمريكية. الأسواق المؤكدة، وفقًا لوثائق الشركة، هي ألمانيا والنمسا.' },
        ],
      },
    },
  },
  ko: {
    theme: 'Balcony Solar Money Pages',
    title: 'Yuma: 발코니 태양광 기업 프로필',
    seoTitle: 'Yuma 발코니 태양광 기업 프로필',
    metaDescription: 'Yuma의 기업 프로필입니다. 연혁, 소유 구조, 발코니 태양광 시장에서의 제품 라인업을 다룹니다.',
    publishDate: '2026-07-19',
    dateModified: '2026-07-20',
    audience: 'Yuma라는 기업을 조사 중인 독자',
    intro: '이 프로필은 기업으로서의 Yuma를 다룹니다. 설립 배경, 소유 구조, 제품 라인업, 확인된 시장, 공급업체 관계를 살펴봅니다. 내용은 PromptQuorum의 발코니 태양광 관련 전체 콘텐츠에서 사용하는 것과 동일한 등록 데이터 및 표준을 참고했으며, 아래에 링크된 산업 개요와도 일치합니다. 구매 전 발코니 태양광 키트나 배터리를 비교하려는 독자는 전용 비교 페이지를 참고하시기 바랍니다. 이 문서는 가격이나 구매 추천을 다루지 않습니다.',
    leadAnswerBlock: '**Yuma는 2020년 세 명의 공동 창업자가 독일 쾰른에서 설립한 자체 자금 운영 발코니 태양광 기업으로, 외부 투자 라운드는 확인되지 않았습니다.** Yuma는 자체적으로 인버터나 배터리를 제조하지 않으며, Hoymiles, EcoFlow, Anker SOLIX 등 타사 하드웨어를 조합해 키트를 구성합니다. 자체 제품 기여 부분은 설치 표면에 따라 달라지는 장착용 하드웨어입니다. 확인된 시장은 독일과 오스트리아로, Yuma 자체의 배송 및 지원 문서에 근거합니다.',
    sections: {
      tldr: {
        id: 'tldr',
        isTldr: true,
        title: 'Yuma: 핵심 사실',
        items: [
          'Yuma는 2020년 세 명의 공동 창업자가 설립했으며, 독일 쾰른에 본사를 두고 있습니다.',
          '회사는 자체 자금으로 운영되며, 외부 투자 라운드는 확인되지 않았습니다.',
          'Yuma는 자체 하드웨어를 제조하는 대신 타사의 인버터와 배터리를 조합해 발코니 태양광 키트를 구성합니다.',
          'Yuma 자체 제품 페이지에서 확인된 부품 공급업체로는 Hoymiles, EcoFlow, Anker SOLIX가 있습니다.',
          'Yuma 자체의 제품 기여 부분은 장착용 하드웨어이며, 설치 표면에 따라 다른 형식으로 제공됩니다.',
          '확인된 시장은 독일과 오스트리아로, Yuma 자체의 배송 및 지원 문서에 근거합니다.',
        ],
      },
      snapshot: {
        title: 'Yuma: 기업 스냅샷',
        image: '/images/yuma-balcony-solar-snapshot-en.svg',
        imageCaption: '독일 쾰른에 위치하며, 2020년 세 명의 공동 창업자가 설립했습니다. 자체 자금으로 운영되며 외부 투자 라운드는 확인되지 않았습니다.',
        content: 'Yuma는 독일 쾰른에 본사를 두고 있으며, 2020년 세 명의 공동 창업자가 설립했습니다. 회사는 자체 자금으로 운영되며, 기업 기록이나 언론 보도에서 외부 투자 라운드는 발견되지 않았습니다. 이는 대형 상장 전자기업의 사업부인 Anker SOLIX나 EcoFlow 같은 발코니 태양광 브랜드와의 구조적 차이입니다. Yuma는 키트 재판매업체로 운영되며, 자체적으로 전자 부품을 제조하는 대신 타사의 인버터와 배터리를 자사의 장착용 하드웨어와 결합합니다.',
        snippetBlocks: [
          { type: 'one-sentence', text: 'Yuma는 2020년 설립되어 독일 쾰른에 본사를 둔 자체 자금 운영 발코니 태양광 키트 기업입니다.' },
          { type: 'plain-terms', text: 'Yuma는 대형 전자기업의 자회사가 아니라, 장착용 하드웨어를 개발하고 이를 다른 기업의 인버터·배터리와 결합해 판매하는 독립적이고 비상장인 독일 스타트업입니다.' },
        ],
      },
      timeline: {
        title: '연혁',
        image: '/images/yuma-balcony-solar-timeline-en.svg',
        imageCaption: '설립 연도와 시장 내 입지는 Yuma의 자체 소개 페이지와 2022년 TechCrunch 언급을 통해 확인되었습니다.',
        content: 'Yuma는 2020년 세 명의 공동 창업자가 독일 쾰른에서 설립했습니다. Yuma 자체 소개 페이지에서 설립 연도가 확인되며, 2022년 TechCrunch 언급이 그 시기 회사의 시장 내 입지를 독립적으로 뒷받침합니다. 이 두 출처 외에 자금 조달 라운드, 직원 수, 확장 시기 등 회사가 확인한 추가적인 이정표는 발견되지 않았습니다.',
      },
      lineup: {
        title: '제품 라인업(설치 방식)',
        image: '/images/yuma-balcony-solar-lineup-en.svg',
        imageCaption: 'Yuma는 타사의 인버터/배터리로 키트를 구성하며, 자체 제품은 설치 표면에 따라 달라지는 장착용 하드웨어입니다.',
        content: 'Yuma의 제품 라인업은 장착용 하드웨어를 중심으로 하며, 발코니 난간, 벽면, 평평한 지붕 등 다양한 설치 표면에 맞춰 여러 형식으로 제공됩니다. 각 키트에 포함된 인버터 및 배터리 구성 요소는 Yuma가 직접 설계하거나 제조하는 것이 아니라 타사 공급업체에서 조달됩니다. 이로 인해 Yuma의 핵심 기술적 기여는 시스템을 계통 안전하게 만드는 전자 부품이 아니라 물리적 장착 시스템에 있습니다.',
      },
      markets: {
        title: '확인된 시장',
        image: '/images/yuma-balcony-solar-markets-en.svg',
        imageCaption: '독일과 오스트리아는 Yuma 자체의 배송/지원 문서를 통해 확인되었습니다.',
        content: 'Yuma는 자체 배송 및 지원 문서를 통해 독일과 오스트리아에서의 판매 및 지원 범위를 확인하고 있습니다. 이 프로필 작성을 위해 검토한 회사 기록에서는 그 외 다른 시장이 확인되지 않았으며, Yuma는 이 두 국가를 넘어선 확장 시기를 밝히지 않았습니다.',
      },
      position: {
        title: 'Yuma의 시장 위치',
        image: '/images/yuma-balcony-solar-position-en.svg',
        imageCaption: 'Yuma는 자체 하드웨어를 제조하는 대신, 이번 조사 대상에 포함된 다른 기업(Hoymiles, EcoFlow, Anker SOLIX)으로부터 부품을 공급받습니다.',
        content: '발코니 태양광 공급망은 패널 제조업체, 마이크로인버터/배터리 제조업체, 그리고 이 둘을 결합해 소비자 제품으로 만드는 키트 재판매업체의 세 계층으로 나뉩니다. Yuma는 명확히 키트 재판매업체 계층에서 사업을 운영하며, 이번 조사 대상에 포함된 다른 기업인 Hoymiles, EcoFlow, Anker SOLIX로부터 인버터와 배터리를 조달하고, 자체 제조는 전력 전자 부품이 아닌 장착용 하드웨어에 집중합니다. 이러한 단일 계층 구조는 자체적으로 배터리 하드웨어를 설계·제조하는 Anker SOLIX와 EcoFlow의 이중 계층 방식보다 발코니 태양광 시장에서 더 전형적입니다.',
      },
      partners: {
        title: '확인된 부품 공급업체',
        image: '/images/yuma-balcony-solar-partners-en.svg',
        imageCaption: 'Yuma 자체 제품 페이지에 직접 명시되어 있으며, Yuma가 자체 제조하지 않고 키트에 결합하는 부품입니다.',
        content: 'Yuma는 자사 제품 페이지에서 키트에 결합되는 인버터와 배터리의 공급업체로 Hoymiles, EcoFlow, Anker SOLIX를 직접 명시하고 있습니다. 이는 Yuma가 완제품으로 조립하는 부품이며, 자체적으로 설계하거나 제조하는 하드웨어가 아닙니다. Yuma 자체 웹사이트에 명시된 것 외에 다른 공급업체 관계는 확인되지 않았습니다.',
      },
      faqSection: {
        id: 'faq',
        title: '자주 묻는 질문',
        faqs: [
          { q: 'Yuma는 누가 소유하고 있나요?', a: 'Yuma는 2020년 세 명의 공동 창업자가 설립했으며, 독일 쾰른에 본사를 두고 있습니다. 회사는 자체 자금으로 운영되며, 외부 투자 라운드는 발견되지 않았습니다.' },
          { q: 'Yuma는 대기업의 자회사인가요?', a: '아니요. 대형 상장 전자기업의 사업부인 Anker SOLIX나 EcoFlow와 달리, Yuma는 독립적이고 비상장인 기업으로 확인되었습니다.' },
          { q: 'Yuma는 자체적으로 인버터나 배터리를 제조하나요?', a: '아니요. Yuma는 타사 부품으로 키트를 구성합니다. Yuma 자체 제품 페이지에서 확인된 공급업체로는 Hoymiles, EcoFlow, Anker SOLIX가 있습니다. Yuma 자체의 제품 기여 부분은 장착용 하드웨어입니다.' },
          { q: 'Yuma가 실제로 자체 제조하는 것은 무엇인가요?', a: 'Yuma 자체 제조의 중심은 장착용 하드웨어로, 발코니 난간, 벽면, 평평한 지붕 등 다양한 설치 표면에 맞춰 여러 형식으로 제공됩니다. 키트 내 전력 전자 부품은 타사 공급업체에서 조달됩니다.' },
          { q: 'Yuma는 어느 시장에서 판매하나요?', a: 'Yuma는 자체 배송 및 지원 문서를 통해 독일과 오스트리아에서의 판매 및 지원 범위를 확인하고 있습니다. 그 외 다른 시장은 확인되지 않았습니다.' },
          { q: 'Yuma는 언제 설립되었나요?', a: 'Yuma는 2020년 세 명의 공동 창업자가 설립했습니다. 설립 연도는 Yuma 자체 소개 페이지에서 확인되며, 2022년 TechCrunch 언급을 통해 뒷받침됩니다.' },
          { q: 'Yuma는 Anker SOLIX나 EcoFlow와 구조적으로 어떻게 다른가요?', a: 'Anker SOLIX와 EcoFlow는 완제품 키트 판매에 더해 자체적으로 배터리 하드웨어를 설계·제조하는 이중 계층 구조를 갖고 있습니다. Yuma는 단일 계층에서 운영되며, Hoymiles, EcoFlow, Anker SOLIX를 포함한 다른 기업으로부터 인버터와 배터리를 조달하고, 자체 개발은 장착용 하드웨어에 집중합니다.' },
          { q: 'Yuma는 미국에서 판매되나요?', a: 'Yuma의 미국 시장 내 입지는 확인되지 않았습니다. 회사 문서에 따르면 확인된 시장은 독일과 오스트리아입니다.' },
        ],
      },
    },
  },
}
