// Auto-generated from src/lib/local-llms/content.ts
// Slug: local-llm-developer-stack
// Generated: 2026-05-03T11:33:08.370Z

import type { Language } from "@/lib/blog/blogContent";

import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
    en: {
      freshness_tier: 'semi_annual',
      theme: 'Tools & Interfaces',
      title: 'Best Local LLM Stack for Developers (April 2026)',
      seoTitle: 'Local LLM Dev Stack: CLI → API → Production Setup Guide 2026',
      intro: '**Developers should use vLLM + FastAPI + VS Code Copilot extension for production-grade local LLM inference.** As of April 2026, this stack enables real-time code completions, batch processing, and OpenAI API compatibility without vendor lock-in. Alternative (simpler): Ollama + llama.cpp CLI for one-off scripts.',
      metaDescription: 'Build a local LLM dev environment in 3 tiers: (1) Ollama CLI in 5 min, (2) vLLM + FastAPI server in 30 min, (3) production multi-GPU with nginx and Prometheus. VS Code and Cursor IDE integration. April 2026.',
      twitterDescription: '3-tier local LLM dev stack: Ollama CLI (5 min) → vLLM API (30 min) → production multi-GPU (2 hrs). VS Code + Cursor. April 2026.',
      publishDate: '2026-04-05',
      leadAnswerBlock: '**Developers should use vLLM + FastAPI + VS Code Copilot extension for production-grade local LLM inference. As of April 2026, this stack enables real-time code completions, batch processing, and OpenAI API compatibility without vendor lock-in.**',
      audience: 'Engineers deploying local LLMs in production or enterprise environments',
      readTime: '10 min',
      educationalLevel: 'Advanced',
      primaryTerm: 'Developer Stack',
      toc: [
        { label: 'TLDR', anchor: '#tldr' },
        { label: 'The Three Tiers', anchor: '#tiers' },
        { label: 'Tier 1: CLI Quick Start (5 minutes)', anchor: '#tier1' },
        { label: 'Tier 2: API Server with FastAPI (30 minutes)', anchor: '#tier2' },
        { label: 'Tier 3: Production Multi-User (2 hours)', anchor: '#tier3' },
        { label: 'IDE Integration (VS Code, Cursor)', anchor: '#ide' },
        { label: 'Debugging & Monitoring', anchor: '#monitoring' },
        { label: 'Regional Context & Compliance', anchor: '#regional' },
        { label: 'Common Setup Mistakes', anchor: '#mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Related Reading', anchor: '#related' },
        { label: 'Sources', anchor: '#sources' },
      ],
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        'headline': 'Best Local LLM Stack for Developers (April 2026)',
        'description': 'Production-grade local LLM stack: vLLM, FastAPI API server, IDE integration with VS Code Copilot, real-time code completions, 30-50 tokens/second.',
        'url': 'https://www.promptquorum.com/local-llms/local-llm-developer-stack',
        'datePublished': '2026-04-05',
        'dateModified': '2026-04-19',
        'author': { '@type': 'Person', 'name': 'Hans Kuepper', 'sameAs': 'https://www.promptquorum.com/author/hans-kuepper' },
        'publisher': { '@type': 'Organization', 'name': 'PromptQuorum', 'url': 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Advanced',
        'about': [
          { '@type': 'SoftwareApplication', 'name': 'vLLM' },
          { '@type': 'SoftwareApplication', 'name': 'FastAPI' },
          { '@type': 'SoftwareApplication', 'name': 'Ollama' },
          { '@type': 'SoftwareApplication', 'name': 'Continue.dev' },
        ],
        'speakable': { '@type': 'SpeakableSpecification', 'cssSelector': ['.article-intro', '.key-takeaways'] },
      },
      howToSchema: {
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        'name': 'How to Set Up a Local LLM Developer Stack',
        'totalTime': 'PT120M',
        'step': [
          { '@type': 'HowToStep', 'name': 'Install Ollama (Tier 1)', 'text': 'Run `brew install ollama` on macOS or download the Windows installer. Then run `ollama run llama3.2` to start a local model.' },
          { '@type': 'HowToStep', 'name': 'Install vLLM (Tier 2)', 'text': 'Install Python 3.10+ and run `pip install vllm torch`. Start the server with `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`.' },
          { '@type': 'HowToStep', 'name': 'Configure IDE integration', 'text': 'Install the Continue extension in VS Code. Set the API endpoint to `http://localhost:8000/v1` and the model name to `meta-llama/Llama-3.3-8B-Instruct`.' },
          { '@type': 'HowToStep', 'name': 'Set up Tier 3 production stack', 'text': 'Deploy 2 vLLM instances, configure nginx load balancer, set up Prometheus metrics collection, and add rate limiting per user.' },
          { '@type': 'HowToStep', 'name': 'Monitor and debug', 'text': 'Check vLLM stdout logs for OOM and CUDA errors. Use Prometheus /metrics endpoint for request latency and token throughput tracking.' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [
          { '@type': 'Question', 'name': 'Which tier should I use?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Tier 1 if solo (casual use). Tier 2 if single dev + IDE integration. Tier 3 if team + 24/7 service.' } },
          { '@type': 'Question', 'name': 'Can I use vLLM instead of Ollama?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Yes, but more setup. vLLM is faster (batching) and more flexible (Python API).' } },
          { '@type': 'Question', 'name': 'How do I serve models across multiple GPUs?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'vLLM: `--tensor-parallel-size 2`. Splits model across 2 GPUs for 2× throughput.' } },
          { '@type': 'Question', 'name': 'What if vLLM OOMs?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Use smaller quantization (Q4 vs. Q8), lower batch size, or allocate less VRAM per model. Check `nvidia-smi`.' } },
          { '@type': 'Question', 'name': 'Is Tier 3 production-ready?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Yes, with monitoring. Add Prometheus, Grafana, alerting (Alertmanager). Standard infrastructure patterns.' } },
        ],
      },
      gammaEmbedUrl: '/presentations/local-llm-developer-stack-static.html',
      gammaDescription: 'The slide deck below covers the three-tier local LLM developer stack (Ollama → vLLM API → production multi-user), IDE integration with VS Code and Cursor, debugging and monitoring with Prometheus, and regional compliance context. Download the PDF as a Local LLM Developer Stack reference card.',
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**Tier 1 (simple):** `ollama run llama3.2` + OpenWebUI. No code required.',
            '**Tier 2 (standard):** vLLM + FastAPI wrapper. Python 3.10+, pip install 2 packages, 30 min setup.',
            '**Tier 3 (production):** vLLM + nginx load balancer + monitoring (Prometheus). Multi-GPU, multi-user, fault-tolerant.',
            '**IDE integration:** VS Code Copilot or Cursor with vLLM OpenAI API endpoint.',
            '**Batch processing:** Send 10 prompts at once, get 10 responses in parallel (not sequential).',
            '**Cost:** Zero (open source) vs. $20/mo (Claude Pro) or $200/mo (large team cloud).',
            '**Speed:** Tier 2 achieves 30-50 tok/s for coding. Tier 3 achieves 200+ tok/s across users.',
            '**Complexity:** Tier 1 (1/10), Tier 2 (4/10), Tier 3 (8/10).',
          ],
        },
        'tiers': {
          id: 'tiers',
          title: 'The Three Tiers',
          content: 'Choose based on use case:',
          items: [
            '**Tier 1:** Solo dev, casual chat, no API server. Ollama + chat UI.',
            '**Tier 2:** Single developer, IDE integration, custom scripts. vLLM + FastAPI.',
            '**Tier 3:** Team deployment, 5+ developers, always-on service. vLLM + nginx + monitoring.',
          ],
        },
        'tier1': {
          id: 'tier1',
          title: 'Tier 1: CLI Quick Start (5 minutes)',
          numberedItems: [
            '`brew install ollama` (macOS) or download Windows installer.',
            '`ollama run llama3.2` (downloads & runs 8B model).',
            'Open browser: `http://localhost:11434` (Ollama web UI).',
            'Start chatting. Done.',
          ],
          content: 'For coding: install VS Code extension "Continue" (`continue.dev`), point to Ollama API, get completions in real-time.',
        },
        'tier2': {
          id: 'tier2',
          title: 'Tier 2: API Server with FastAPI (30 minutes)',
          numberedItems: [
            'Install Python 3.10+: `python --version`.',
            'Install vLLM: `pip install vllm torch`.',
            'Start vLLM server: `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`.',
            'Test endpoint: `curl http://localhost:8000/v1/chat/completions -d \'{"model": "Llama-3.1-8B-Instruct", "messages": [{"role": "user", "content": "Write Python code for Fibonacci"}]}\' -H "Content-Type: application/json"`.',
            'Integrate into IDE: point Copilot extension to `http://localhost:8000`.',
            'Batch requests: send multiple prompts in parallel, vLLM processes all at once.',
          ],
          content: 'Why FastAPI: OpenAI-compatible endpoint. Drop-in replacement for real OpenAI API in your code.',
        },
        'tier3': {
          id: 'tier3',
          title: 'Tier 3: Production Multi-User (2 hours)',
          numberedItems: [
            'Deploy 2 vLLM instances on separate GPUs (GPU 0, GPU 1).',
            'Configure nginx to load-balance requests across both instances.',
            'Set up Prometheus for metrics collection (request latency, tokens/sec, errors).',
            'Add rate limiting per user (token bucket algorithm).',
            'Deploy on cloud VM or on-prem server with 10Gbps network.',
            'Monitor via Grafana dashboard (optional).',
          ],
          content: 'Scales to 50+ concurrent developers (5 tok/s each) on dual-GPU rig. Cost: electricity only (~$100/month if 24/7).',
        },
        'ide': {
          id: 'ide',
          title: 'IDE Integration (VS Code, Cursor)',
          content: [
            '**Setup for real-time code completions:**',
            'Alternative (native IDE support): Cursor Editor has built-in local LLM support (no extension needed).',
          ],
          numberedItems: [
            'Install "Continue" extension (`continue.dev`).',
            'Open extension settings, configure custom API: `http://localhost:8000/v1` (vLLM endpoint).',
            'Set model name to match vLLM server (`meta-llama/Llama-3.3-8B-Instruct`).',
            'Press Ctrl+Shift+Space (or cmd+shift+space) to trigger completion.',
            'Completions stream in real-time (10-20 tok/s).',
          ],
        },
        'monitoring': {
          id: 'monitoring',
          title: 'Debugging & Monitoring',
          items: [
            '**vLLM logs:** Check stdout for errors (model loading, OOM, CUDA errors).',
            '**Prometheus metrics:** vLLM exports `/metrics` endpoint (request count, latency histogram, tokens generated).',
            '**Token counting:** Use `tiktoken` library to count tokens before sending (avoid OOM surprises).',
            '**Latency profiling:** Add timestamp logging before/after vLLM call to identify bottlenecks.',
          ],
        },
        'regional': {
          id: 'regional',
          title: 'Regional Context & Compliance',
          items: [
            '**EU / GDPR (Europe):** Local inference satisfies GDPR Article 28 -- no data leaves your infrastructure. No DPA required. Recommended for healthcare, legal, and financial workloads. BSI-Grundschutz-Kataloge certified for German enterprise deployments.',
            '**Japan / METI:** METI AI Governance Guidelines 2024 recommend on-premise inference for sensitive enterprise data. vLLM + Tier 3 setup meets METI audit trail requirements.',
            '**China / PIPL:** China\'s Personal Information Protection Law (2021) mandates data residency. Tier 2/3 local stack keeps all inference in-country. Compatible with Alibaba Cloud and Tencent Cloud GPU instances.',
            '**United States:** No federal AI data residency mandate as of 2026. HIPAA-covered entities must ensure PHI never leaves controlled infrastructure -- Tier 2/3 satisfies this by default.',
          ],
        },
        'mistakes': {
          title: 'Common Setup Mistakes',
          items: [
            'Running vLLM on same GPU as another process (Discord, gaming). Causes GPU out-of-memory errors.',
            'Sending requests with no timeout. If vLLM hangs, client hangs forever. Always set `timeout=60` in requests.',
            'Assuming vLLM auto-scales across multiple GPUs. Requires explicit `--tensor-parallel-size` flag.',
            'Forgetting to set CUDA_VISIBLE_DEVICES if multi-GPU. vLLM uses all GPUs by default.',
            'Using Llama 2 models in 2026. Meta deprecated Llama 2 for commercial use in January 2026. Use Llama 3.3 8B Instruct (Apache 2.0 license, no restrictions).',
            '**Using Llama 3.1 when Llama 3.3 is available.** Llama 3.3 8B Instruct has better instruction-following and is the recommended default as of April 2026. Use `ollama run llama3.3:8b-instruct`.',
          ],
        },
        'faqSection': {
          id: 'faq',
          title: 'FAQ',
          faqs: [
            { q: 'Which tier should I use?', a: 'Tier 1 if solo (casual use). Tier 2 if single dev + IDE integration. Tier 3 if team + 24/7 service.' },
            { q: 'Can I use vLLM instead of Ollama?', a: 'Yes, but more setup. vLLM is faster (batching) and more flexible (Python API).' },
            { q: 'How do I serve models across multiple GPUs?', a: 'vLLM: `--tensor-parallel-size 2`. Splits model across 2 GPUs for 2× throughput.' },
            { q: 'Can I fine-tune on top of vLLM inference?', a: 'No. Fine-tune separately (HuggingFace Transformers), then load fine-tuned model in vLLM.' },
            { q: 'What if vLLM OOMs?', a: 'Use smaller quantization (Q4 vs. Q8), lower batch size, or allocate less VRAM per model. Check `nvidia-smi`.' },
            { q: 'Is Tier 3 production-ready?', a: 'Yes, with monitoring. Add Prometheus, Grafana, alerting (Alertmanager). Standard infrastructure patterns.' },
          ],
        },
        'relatedReading': {
          id: 'related',
          title: 'Related Reading',
          items: [
            '[Best AI Coding Assistant for Local LLM](/local-llms/best-ai-coding-assistant-local-llm) -- Choose your IDE: Cursor, Continue.dev, Cody, Tabnine with local LLM support.',
            '[OpenAI-Compatible API with Local LLMs](/local-llms/local-llm-openai-compatible-api)',
            '[Ollama installation and setup guide](/local-llms/how-to-install-ollama)',
            '[Local LLMs with VS Code & Cursor](/local-llms/local-llms-with-vscode-cursor)',
            '[Fine-Tuning Local LLMs with LoRA](/local-llms/fine-tuning-local-llms-lora)',
          ],
        },
        'sources': {
          id: 'sources',
          title: 'Sources',
          items: [
            '[vLLM OpenAI-Compatible Server Documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html) -- Official vLLM API server setup guide',
            '[Continue.dev Configuration Documentation](https://docs.continue.dev/reference/Model%20Providers/openai) -- IDE extension config for custom OpenAI endpoints',
            '[Meta Llama 3.3 Model Card](https://ai.meta.com/llama/) -- Meta. Updated instruct model, Apache 2.0. Recommended replacement for Llama 3.1 8B.',
            '[Qwen2.5-Coder Model Card](https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct) -- Alibaba. 82% HumanEval, Apache 2.0 license. Best coding model under 8 GB VRAM.',
          ],
        },
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        'name': 'Best Local LLM Stack for Developers (April 2026)',
        'itemListElement': [
          { '@type': 'ListItem', position: 1, name: 'Tier 1 (simple): `ollama run llama3.2` + OpenWebUI. No code required.' },
          { '@type': 'ListItem', position: 2, name: 'Tier 2 (standard): vLLM + FastAPI wrapper. Python 3.10+, pip install 2 packages, 30 min setup.' },
          { '@type': 'ListItem', position: 3, name: 'Tier 3 (production): vLLM + nginx load balancer + monitoring (Prometheus). Multi-GPU, multi-user, fault-tolerant.' },
          { '@type': 'ListItem', position: 4, name: 'IDE integration: VS Code Copilot or Cursor with vLLM OpenAI API endpoint.' },
          { '@type': 'ListItem', position: 5, name: 'Batch processing: Send 10 prompts at once, get 10 responses in parallel (not sequential).' },
          { '@type': 'ListItem', position: 6, name: 'Cost: Zero (open source) vs. $20/mo (Claude Pro) or $200/mo (large team cloud).' },
          { '@type': 'ListItem', position: 7, name: 'Speed: Tier 2 achieves 30-50 tok/s for coding. Tier 3 achieves 200+ tok/s across users.' },
          { '@type': 'ListItem', position: 8, name: 'Complexity: Tier 1 (1/10), Tier 2 (4/10), Tier 3 (8/10).' },
        ],
      },
    },
    es: {
      freshness_tier: 'semi_annual',
      theme: 'Tools & Interfaces',
      title: 'Mejor Stack Local de LLM para Desarrolladores (abril 2026)',
      seoTitle: 'Stack LLM local para devs 2026: de CLI a producción',
      intro: '**Los desarrolladores deberían usar vLLM + FastAPI + la extensión de VS Code Copilot para inferencia local de LLM de nivel producción.** A partir de abril de 2026, este stack permite completaciones de código en tiempo real, procesamiento por lotes y compatibilidad con la API de OpenAI sin dependencia de un proveedor. Alternativa (más simple): Ollama + llama.cpp CLI para scripts puntuales.',
      metaDescription: 'Entorno de desarrollo local con LLM en 3 niveles: Ollama CLI (5 min), vLLM + FastAPI (30 min) y producción multi-GPU. Integra con VS Code y Cursor.',
      twitterDescription: 'Stack local LLM en 3 niveles: Ollama CLI (5 min) → vLLM API (30 min) → producción multi-GPU (2 h). VS Code + Cursor. Abril 2026.',
      publishDate: '2026-04-05',
      leadAnswerBlock: '**Los desarrolladores deberían usar vLLM + FastAPI + la extensión de VS Code Copilot para inferencia local de LLM de nivel producción. A partir de abril de 2026, este stack permite completaciones de código en tiempo real, procesamiento por lotes y compatibilidad con la API de OpenAI sin dependencia de un proveedor.**',
      audience: 'Ingenieros que despliegan LLMs locales en entornos de producción o empresariales',
      readTime: '10 min de lectura',
      educationalLevel: 'Advanced',
      primaryTerm: 'Developer Stack',
      toc: [
        { label: 'Puntos clave', anchor: '#tldr' },
        { label: 'Los tres niveles', anchor: '#tiers' },
        { label: 'Nivel 1: Inicio rápido con CLI (5 minutos)', anchor: '#tier1' },
        { label: 'Nivel 2: Servidor API con FastAPI (30 minutos)', anchor: '#tier2' },
        { label: 'Nivel 3: Producción multiusuario (2 horas)', anchor: '#tier3' },
        { label: 'Integración con IDE (VS Code, Cursor)', anchor: '#ide' },
        { label: 'Depuración y monitoreo', anchor: '#monitoring' },
        { label: 'Contexto regional y cumplimiento normativo', anchor: '#regional' },
        { label: 'Errores comunes de configuración', anchor: '#mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Lecturas relacionadas', anchor: '#related' },
        { label: 'Fuentes', anchor: '#sources' },
      ],
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        'headline': 'Mejor Stack Local de LLM para Desarrolladores (abril 2026)',
        'description': 'Stack de nivel producción: vLLM, FastAPI, integración IDE con VS Code Copilot, completaciones de código en tiempo real, 30-50 tokens/segundo. Sin dependencia de proveedor.',
        'url': 'https://www.promptquorum.com/es/local-llms/local-llm-developer-stack?lang=es',
        'datePublished': '2026-04-05',
        'dateModified': '2026-04-19',
        'author': { '@type': 'Person', 'name': 'Hans Kuepper' },
        'publisher': { '@type': 'Organization', 'name': 'PromptQuorum', 'url': 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Advanced',
        'about': [
          { '@type': 'Thing', 'name': 'vLLM' },
          { '@type': 'Thing', 'name': 'FastAPI' },
          { '@type': 'Thing', 'name': 'Ollama' },
          { '@type': 'Thing', 'name': 'Continue.dev' },
        ],
        'mentions': [
          { '@type': 'SoftwareApplication', 'name': 'vLLM' },
          { '@type': 'SoftwareApplication', 'name': 'FastAPI' },
          { '@type': 'SoftwareApplication', 'name': 'Ollama' },
          { '@type': 'SoftwareApplication', 'name': 'Continue.dev' },
        ],
        'speakable': { '@type': 'SpeakableSpecification', 'cssSelector': ['.article-intro', '.key-takeaways'] },
      },
      howToSchema: {
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        'name': 'Cómo configurar un stack de desarrollador con LLM local',
        'totalTime': 'PT120M',
        'step': [
          { '@type': 'HowToStep', 'name': 'Instalar Ollama (Nivel 1)', 'text': 'Ejecutar `brew install ollama` en macOS o descargar el instalador para Windows. Luego ejecutar `ollama run llama3.2` para iniciar un modelo local.' },
          { '@type': 'HowToStep', 'name': 'Instalar vLLM (Nivel 2)', 'text': 'Instalar Python 3.10+ y ejecutar `pip install vllm torch`. Iniciar el servidor con `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`.' },
          { '@type': 'HowToStep', 'name': 'Configurar la integración con el IDE', 'text': 'Instalar la extensión Continue en VS Code. Configurar el endpoint de la API como `http://localhost:8000/v1` y el nombre del modelo como `meta-llama/Llama-3.3-8B-Instruct`.' },
          { '@type': 'HowToStep', 'name': 'Configurar el stack de producción de Nivel 3', 'text': 'Desplegar 2 instancias de vLLM, configurar el balanceador de carga nginx, establecer la recolección de métricas con Prometheus y añadir limitación de tasa por usuario.' },
          { '@type': 'HowToStep', 'name': 'Monitorear y depurar', 'text': 'Revisar los logs de stdout de vLLM en busca de errores OOM y CUDA. Usar el endpoint /metrics de Prometheus para rastrear la latencia de solicitudes y el rendimiento de tokens.' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [
          { '@type': 'Question', 'name': '¿Qué nivel debo usar?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Nivel 1 para uso individual (casual). Nivel 2 para un desarrollador con integración de IDE. Nivel 3 para equipos con servicio 24/7.' } },
          { '@type': 'Question', 'name': '¿Puedo usar vLLM en lugar de Ollama?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Sí, pero requiere más configuración. vLLM es más rápido (procesamiento por lotes) y más flexible (API de Python).' } },
          { '@type': 'Question', 'name': '¿Cómo sirvo modelos en múltiples GPUs?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'vLLM: `--tensor-parallel-size 2`. Divide el modelo en 2 GPUs para el doble de rendimiento.' } },
          { '@type': 'Question', 'name': '¿Qué hago si vLLM genera OOM?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Usa una cuantización más pequeña (Q4 en lugar de Q8), reduce el tamaño del lote o asigna menos VRAM por modelo. Consulta `nvidia-smi`.' } },
          { '@type': 'Question', 'name': '¿El Nivel 3 está listo para producción?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Sí, con monitoreo. Agrega Prometheus, Grafana y alertas (Alertmanager). Patrones de infraestructura estándar.' } },
        ],
      },
      gammaEmbedUrl: '/presentations/local-llm-developer-stack-static.html',
      gammaDescription: 'La presentación de diapositivas a continuación cubre el stack de desarrollador con LLM local en tres niveles (Ollama → vLLM API → producción multiusuario), la integración con IDE usando VS Code y Cursor, la depuración y monitoreo con Prometheus, y el contexto regional de cumplimiento normativo. Descarga el PDF como tarjeta de referencia del Stack de Desarrollador con LLM Local.',
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            '**Nivel 1 (simple):** `ollama run llama3.2` + OpenWebUI. No se requiere código.',
            '**Nivel 2 (estándar):** vLLM + wrapper de FastAPI. Python 3.10+, pip install de 2 paquetes, configuración en 30 min.',
            '**Nivel 3 (producción):** vLLM + balanceador de carga nginx + monitoreo (Prometheus). Multi-GPU, multiusuario, tolerante a fallos.',
            '**Integración IDE:** VS Code Copilot o Cursor con el endpoint de la API OpenAI de vLLM.',
            '**Procesamiento por lotes:** Envía 10 prompts a la vez, recibe 10 respuestas en paralelo (no de forma secuencial).',
            '**Costo:** Cero (código abierto) vs. $20/mes (Claude Pro) o $200/mes (equipo grande en la nube).',
            '**Velocidad:** El Nivel 2 alcanza 30-50 tok/s para programación. El Nivel 3 alcanza 200+ tok/s entre usuarios.',
            '**Complejidad:** Nivel 1 (1/10), Nivel 2 (4/10), Nivel 3 (8/10).',
          ],
        },
        'tiers': {
          id: 'tiers',
          title: 'Los tres niveles',
          content: 'Elige según el caso de uso:',
          items: [
            '**Nivel 1:** Desarrollador individual, uso casual, sin servidor API. Ollama + interfaz de chat.',
            '**Nivel 2:** Desarrollador individual, integración con IDE, scripts personalizados. vLLM + FastAPI.',
            '**Nivel 3:** Despliegue en equipo, 5+ desarrolladores, servicio siempre activo. vLLM + nginx + monitoreo.',
          ],
        },
        'tier1': {
          id: 'tier1',
          title: 'Nivel 1: Inicio rápido con CLI (5 minutos)',
          numberedItems: [
            '`brew install ollama` (macOS) o descargar el instalador para Windows.',
            '`ollama run llama3.2` (descarga y ejecuta el modelo 8B).',
            'Abrir el navegador: `http://localhost:11434` (interfaz web de Ollama).',
            'Comenzar a chatear. Listo.',
          ],
          content: 'Para programación: instala la extensión "Continue" de VS Code (`continue.dev`), apúntala a la API de Ollama y obtén completaciones en tiempo real.',
        },
        'tier2': {
          id: 'tier2',
          title: 'Nivel 2: Servidor API con FastAPI (30 minutos)',
          numberedItems: [
            'Instalar Python 3.10+: `python --version`.',
            'Instalar vLLM: `pip install vllm torch`.',
            'Iniciar el servidor vLLM: `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`.',
            'Probar el endpoint: `curl http://localhost:8000/v1/chat/completions -d \'{"model": "Llama-3.1-8B-Instruct", "messages": [{"role": "user", "content": "Write Python code for Fibonacci"}]}\' -H "Content-Type: application/json"`.',
            'Integrar en el IDE: apuntar la extensión Copilot a `http://localhost:8000`.',
            'Solicitudes por lotes: envía múltiples prompts en paralelo; vLLM los procesa todos a la vez.',
          ],
          content: 'Por qué FastAPI: endpoint compatible con OpenAI. Reemplazo directo de la API real de OpenAI en tu código.',
        },
        'tier3': {
          id: 'tier3',
          title: 'Nivel 3: Producción multiusuario (2 horas)',
          numberedItems: [
            'Desplegar 2 instancias de vLLM en GPUs separadas (GPU 0, GPU 1).',
            'Configurar nginx para balancear las solicitudes entre ambas instancias.',
            'Configurar Prometheus para la recolección de métricas (latencia de solicitudes, tokens/seg, errores).',
            'Añadir limitación de tasa por usuario (algoritmo de token bucket).',
            'Desplegar en una VM en la nube o servidor on-premises con red de 10 Gbps.',
            'Monitorear mediante el panel de Grafana (opcional).',
          ],
          content: 'Escala a 50+ desarrolladores simultáneos (5 tok/s cada uno) en un equipo de doble GPU. Costo: solo electricidad (~$100/mes si está activo 24/7).',
        },
        'ide': {
          id: 'ide',
          title: 'Integración con IDE (VS Code, Cursor)',
          content: [
            '**Configuración para completaciones de código en tiempo real:**',
            'Alternativa (soporte nativo del IDE): Cursor Editor tiene soporte integrado para LLMs locales (no se requiere extensión).',
          ],
          numberedItems: [
            'Instalar la extensión "Continue" (`continue.dev`).',
            'Abrir la configuración de la extensión y configurar la API personalizada: `http://localhost:8000/v1` (endpoint de vLLM).',
            'Establecer el nombre del modelo para que coincida con el servidor vLLM (`meta-llama/Llama-3.3-8B-Instruct`).',
            'Presionar Ctrl+Shift+Space (o cmd+shift+space) para activar la completación.',
            'Las completaciones se transmiten en tiempo real (10-20 tok/s).',
          ],
        },
        'monitoring': {
          id: 'monitoring',
          title: 'Depuración y monitoreo',
          items: [
            '**Logs de vLLM:** Revisa stdout en busca de errores (carga del modelo, OOM, errores CUDA).',
            '**Métricas de Prometheus:** vLLM exporta el endpoint `/metrics` (recuento de solicitudes, histograma de latencia, tokens generados).',
            '**Conteo de tokens:** Usa la biblioteca `tiktoken` para contar tokens antes de enviar (evita sorpresas por OOM).',
            '**Perfilado de latencia:** Agrega registro de marcas de tiempo antes/después de la llamada a vLLM para identificar cuellos de botella.',
          ],
        },
        'regional': {
          id: 'regional',
          title: 'Contexto regional y cumplimiento normativo',
          items: [
            '**UE / RGPD (Europa):** La inferencia local satisface el Artículo 28 del RGPD -- ningún dato sale de tu infraestructura. No se requiere un DPA. Recomendado para cargas de trabajo en salud, derecho y finanzas.',
            '**Japón / METI:** Las Directrices de Gobernanza de IA del METI 2024 recomiendan la inferencia on-premises para datos empresariales sensibles. La configuración de vLLM + Nivel 3 cumple los requisitos de auditoría del METI.',
            '**China / PIPL:** La Ley de Protección de Información Personal de China (2021) exige la residencia de datos. El stack local de Nivel 2/3 mantiene toda la inferencia dentro del país. Compatible con instancias GPU de Alibaba Cloud y Tencent Cloud.',
            '**Estados Unidos:** No existe un mandato federal de residencia de datos de IA a partir de 2026. Las entidades cubiertas por HIPAA deben garantizar que la PHI nunca salga de la infraestructura controlada -- el Nivel 2/3 lo cumple por defecto.',
          ],
        },
        'mistakes': {
          title: 'Errores comunes de configuración',
          items: [
            'Ejecutar vLLM en la misma GPU que otro proceso (Discord, juegos). Causa errores de GPU out-of-memory.',
            'Enviar solicitudes sin tiempo de espera. Si vLLM se cuelga, el cliente espera indefinidamente. Establece siempre `timeout=60` en las solicitudes.',
            'Asumir que vLLM escala automáticamente en múltiples GPUs. Requiere el flag explícito `--tensor-parallel-size`.',
            'Olvidar establecer CUDA_VISIBLE_DEVICES en configuraciones multi-GPU. vLLM usa todas las GPUs por defecto.',
            'Usar modelos Llama 2 en 2026. Meta desaprobó Llama 2 para uso comercial en enero de 2026. Usa Llama 3.3 8B Instruct (licencia Apache 2.0, sin restricciones).',
            '**Usar Llama 3.1 cuando Llama 3.3 está disponible.** Llama 3.3 8B Instruct tiene mejor seguimiento de instrucciones y es el predeterminado recomendado a partir de abril de 2026. Usa `ollama run llama3.3:8b-instruct`.',
          ],
        },
        'faqSection': {
          id: 'faq',
          title: 'FAQ',
          faqs: [
            { q: '¿Qué nivel debo usar?', a: 'Nivel 1 para uso individual (casual). Nivel 2 para un desarrollador con integración de IDE. Nivel 3 para equipos con servicio 24/7.' },
            { q: '¿Puedo usar vLLM en lugar de Ollama?', a: 'Sí, pero requiere más configuración. vLLM es más rápido (procesamiento por lotes) y más flexible (API de Python).' },
            { q: '¿Cómo sirvo modelos en múltiples GPUs?', a: 'vLLM: `--tensor-parallel-size 2`. Divide el modelo en 2 GPUs para el doble de rendimiento.' },
            { q: '¿Puedo hacer fine-tuning sobre la inferencia de vLLM?', a: 'No. Realiza el fine-tuning por separado (HuggingFace Transformers) y luego carga el modelo ajustado en vLLM.' },
            { q: '¿Qué hago si vLLM genera OOM?', a: 'Usa una cuantización más pequeña (Q4 en lugar de Q8), reduce el tamaño del lote o asigna menos VRAM por modelo. Consulta `nvidia-smi`.' },
            { q: '¿El Nivel 3 está listo para producción?', a: 'Sí, con monitoreo. Agrega Prometheus, Grafana y alertas (Alertmanager). Patrones de infraestructura estándar.' },
          ],
        },
        'relatedReading': {
          id: 'related',
          title: 'Lecturas relacionadas',
          items: [
            '[Mejor asistente de codificación con IA para LLM local](/es/local-llms/best-ai-coding-assistant-local-llm) -- Elige tu IDE: Cursor, Continue.dev, Cody, Tabnine con soporte para LLMs locales.',
            '[API compatible con OpenAI con LLMs locales](/es/local-llms/local-llm-openai-compatible-api)',
            '[Guía de instalación y configuración de Ollama](/es/local-llms/how-to-install-ollama)',
            '[LLMs locales con VS Code y Cursor](/es/local-llms/local-llms-with-vscode-cursor)',
            '[Fine-Tuning de LLMs locales con LoRA](/es/local-llms/fine-tuning-local-llms-lora)',
          ],
        },
        'sources': {
          id: 'sources',
          title: 'Fuentes',
          items: [
            '[vLLM OpenAI-Compatible Server Documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html) -- Guía oficial de configuración del servidor API de vLLM',
            '[Continue.dev Configuration Documentation](https://docs.continue.dev/reference/Model%20Providers/openai) -- Configuración de la extensión IDE para endpoints OpenAI personalizados',
            '[Meta Llama 3.3 Model Card](https://ai.meta.com/llama/) -- Meta. Modelo instruct actualizado, Apache 2.0. Reemplazo recomendado de Llama 3.1 8B.',
            '[Qwen2.5-Coder Model Card](https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct) -- Alibaba. 82% HumanEval, licencia Apache 2.0. Mejor modelo de programación con menos de 8 GB de VRAM.',
          ],
        },
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        'name': 'Mejor Stack Local de LLM para Desarrolladores (abril 2026)',
        'itemListElement': [
          { '@type': 'ListItem', position: 1, name: 'Nivel 1 (simple): `ollama run llama3.2` + OpenWebUI. No se requiere código.' },
          { '@type': 'ListItem', position: 2, name: 'Nivel 2 (estándar): vLLM + wrapper de FastAPI. Python 3.10+, pip install de 2 paquetes, configuración en 30 min.' },
          { '@type': 'ListItem', position: 3, name: 'Nivel 3 (producción): vLLM + balanceador de carga nginx + monitoreo (Prometheus). Multi-GPU, multiusuario, tolerante a fallos.' },
          { '@type': 'ListItem', position: 4, name: 'Integración IDE: VS Code Copilot o Cursor con el endpoint de la API OpenAI de vLLM.' },
          { '@type': 'ListItem', position: 5, name: 'Procesamiento por lotes: Envía 10 prompts a la vez, recibe 10 respuestas en paralelo (no de forma secuencial).' },
          { '@type': 'ListItem', position: 6, name: 'Costo: Cero (código abierto) vs. $20/mes (Claude Pro) o $200/mes (equipo grande en la nube).' },
          { '@type': 'ListItem', position: 7, name: 'Velocidad: El Nivel 2 alcanza 30-50 tok/s para programación. El Nivel 3 alcanza 200+ tok/s entre usuarios.' },
          { '@type': 'ListItem', position: 8, name: 'Complejidad: Nivel 1 (1/10), Nivel 2 (4/10), Nivel 3 (8/10).' },
        ],
      },
    },
    de: {
      theme: 'Tools & Oberflächen',
      title: 'Best Local LLM Stack für Entwickler (April 2026)',
      seoTitle: 'Lokaler LLM-Entwickler-Stack 2026: Tools & Setup',
      intro: '**Entwickler sollten vLLM + FastAPI + VS Code Copilot-Erweiterung für produktionsreifen lokalen LLM-Betrieb verwenden.** Ab April 2026 ermöglicht dieser Stack Echtzeit-Code-Vervollständigungen, Batch-Verarbeitung und OpenAI-API-Kompatibilität ohne Vendor Lock-in. Alternative (einfacher): Ollama + llama.cpp CLI für einzelne Skripte.',
      metaDescription: 'Lokaler LLM-Entwickler-Stack 2026: Ollama, Continue, Aider und VS Code für KI-Entwicklung ohne Cloud. Tools, IDE-Integration und Workflow.',
      twitterDescription: '3-Stufen lokaler LLM-Dev-Stack: Ollama CLI (5 Min) → vLLM API (30 Min) → Produktion Multi-GPU (2 Std). VS Code + Cursor. April 2026.',
      publishDate: '2026-04-05',
      readTime: '10 Min. Lesezeit',
      educationalLevel: 'Advanced',
      primaryTerm: 'Developer Stack',
      toc: [
        { label: 'Zusammenfassung', anchor: '#tldr' },
        { label: 'Die drei Stufen', anchor: '#tiers' },
        { label: 'Stufe 1: CLI-Schnellstart (5 Minuten)', anchor: '#tier1' },
        { label: 'Stufe 2: API-Server mit FastAPI (30 Minuten)', anchor: '#tier2' },
        { label: 'Stufe 3: Produktivbetrieb für mehrere Nutzer (2 Stunden)', anchor: '#tier3' },
        { label: 'IDE-Integration (VS Code, Cursor)', anchor: '#ide' },
        { label: 'Fehlersuche & Monitoring', anchor: '#monitoring' },
        { label: 'Regionale Rahmenbedingungen & Compliance', anchor: '#regional' },
        { label: 'Häufige Einrichtungsfehler', anchor: '#mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Weiterführende Lektüre', anchor: '#related' },
        { label: 'Quellen', anchor: '#sources' },
      ],
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        'headline': 'Best Local LLM Stack für Entwickler (April 2026)',
        'description': 'Produktionsreifer Stack: vLLM, FastAPI, IDE-Integration VS Code, Echtzeit-Code-Vervollständigung, 30-50 Token/Sekunde. DSGVO-konform, kein Vendor Lock-in.',
        'url': 'https://www.promptquorum.com/de/local-llms/local-llm-developer-stack',
        'datePublished': '2026-04-05',
        'dateModified': '2026-04-19',
        'author': { '@type': 'Person', 'name': 'Hans Kuepper', 'sameAs': 'https://www.promptquorum.com/author/hans-kuepper' },
        'publisher': { '@type': 'Organization', 'name': 'PromptQuorum', 'url': 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Advanced',
        'about': [
          { '@type': 'SoftwareApplication', 'name': 'vLLM' },
          { '@type': 'SoftwareApplication', 'name': 'FastAPI' },
          { '@type': 'SoftwareApplication', 'name': 'Ollama' },
          { '@type': 'SoftwareApplication', 'name': 'Continue.dev' },
        ],
        'speakable': { '@type': 'SpeakableSpecification', 'cssSelector': ['.article-intro', '.key-takeaways'] },
      },
      howToSchema: {
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        'name': 'Wie man einen lokalen LLM-Developer-Stack einrichtet',
        'totalTime': 'PT120M',
        'step': [
          { '@type': 'HowToStep', 'name': 'Ollama installieren (Stufe 1)', 'text': '`brew install ollama` auf macOS ausführen oder den Windows-Installer herunterladen. Dann `ollama run llama3.2` starten, um ein lokales Modell zu laden.' },
          { '@type': 'HowToStep', 'name': 'vLLM installieren (Stufe 2)', 'text': 'Python 3.10+ installieren und `pip install vllm torch` ausführen. Server starten mit `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`.' },
          { '@type': 'HowToStep', 'name': 'IDE-Integration konfigurieren', 'text': 'Continue-Erweiterung in VS Code installieren. API-Endpunkt auf `http://localhost:8000/v1` setzen, Modellname auf `meta-llama/Llama-3.3-8B-Instruct`.' },
          { '@type': 'HowToStep', 'name': 'Stufe-3-Produktionsstack einrichten', 'text': '2 vLLM-Instanzen bereitstellen, nginx Load Balancer konfigurieren, Prometheus-Metrikerfassung einrichten und Rate-Limiting pro Nutzer hinzufügen.' },
          { '@type': 'HowToStep', 'name': 'Überwachen und debuggen', 'text': 'vLLM-stdout-Logs auf OOM- und CUDA-Fehler prüfen. Prometheus-/metrics-Endpunkt für Anfragelatenzen und Token-Durchsatz verwenden.' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [
          { '@type': 'Question', 'name': 'Welche Stufe soll ich verwenden?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Stufe 1 für Einzelnutzer (gelegentlicher Gebrauch). Stufe 2 für einzelne Entwickler mit IDE-Integration. Stufe 3 für Teams mit 24/7-Betrieb.' } },
          { '@type': 'Question', 'name': 'Kann ich vLLM statt Ollama verwenden?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Ja, aber mit mehr Aufwand. vLLM ist schneller (Batching) und flexibler (Python-API).' } },
          { '@type': 'Question', 'name': 'Wie betreibe ich Modelle über mehrere GPUs?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'vLLM: `--tensor-parallel-size 2`. Teilt das Modell auf 2 GPUs auf und verdoppelt den Durchsatz.' } },
          { '@type': 'Question', 'name': 'Was tun, wenn vLLM OOM auslöst?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Kleinere Quantisierung verwenden (Q4 statt Q8), Batch-Größe reduzieren oder weniger VRAM pro Modell zuweisen. `nvidia-smi` prüfen.' } },
          { '@type': 'Question', 'name': 'Ist Stufe 3 produktionsreif?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Ja, mit Monitoring. Prometheus, Grafana und Alerting (Alertmanager) hinzufügen. Standardmäßige Infrastrukturmuster.' } },
          { '@type': 'Question', 'name': 'Muss ich bei der Verwendung des lokalen LLM-Stacks die DSGVO beachten?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Lokale Inferenz erfüllt DSGVO-Artikel 28 ohne zusätzlichen Aufwand: Alle Daten verbleiben in Ihrer eigenen Infrastruktur, kein Auftragsverarbeiter wird benötigt und keine Drittlandübermittlung findet statt. Das BSI-Grundschutz-Kompendium empfiehlt lokale Verarbeitung für besonders schützenswerte Daten.' } },
          { '@type': 'Question', 'name': 'Ist der lokale LLM-Stack für den deutschen Mittelstand geeignet?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Ja. KMU profitieren von vollständiger Datensouveränität gemäß BSI-Grundschutz und IT-Sicherheitsgesetz 2.0, keinen laufenden API-Kosten und einer OpenAI-kompatiblen API für ERP- und CRM-Integration. Stufe 2 ist für die meisten Mittelstandsanwendungen ausreichend und in unter 30 Minuten einsatzbereit.' } },
        ],
      },
      gammaEmbedUrl: '/presentations/local-llm-developer-stack-static.html',
      gammaDescription: 'Das Foliendeck unten behandelt den dreistufigen lokalen LLM-Developer-Stack (Ollama → vLLM API → Multi-User-Produktion), IDE-Integration mit VS Code und Cursor, Debugging und Monitoring mit Prometheus sowie regionale Compliance-Anforderungen. Laden Sie die PDF als Local LLM Developer Stack Referenzkarte herunter.',
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**Stufe 1 (einfach):** `ollama run llama3.2` + OpenWebUI. Kein Code erforderlich.',
            '**Stufe 2 (Standard):** vLLM + FastAPI-Wrapper. Python 3.10+, pip install 2 Pakete, 30 Minuten Einrichtung.',
            '**Stufe 3 (Produktion):** vLLM + nginx Load Balancer + Monitoring (Prometheus). Multi-GPU, mehrere Nutzer, fehlertolerant.',
            '**IDE-Integration:** VS Code Copilot oder Cursor mit vLLM OpenAI-API-Endpunkt.',
            '**Batch-Verarbeitung:** 10 Prompts gleichzeitig senden, 10 Antworten parallel erhalten (nicht sequenziell).',
            '**Kosten:** Null (Open Source) vs. 20 $/Monat (Claude Pro) oder 200 $/Monat (großes Team, Cloud).',
            '**Geschwindigkeit:** Stufe 2 erreicht 30-50 Tok/s beim Coding. Stufe 3 erreicht 200+ Tok/s über mehrere Nutzer.',
            '**Komplexität:** Stufe 1 (1/10), Stufe 2 (4/10), Stufe 3 (8/10).',
          ],
        },
        'tiers': {
          title: 'Die drei Stufen',
          content: 'Auswahl je nach Anwendungsfall:',
          items: [
            '**Stufe 1:** Einzelentwickler, gelegentliche Nutzung, kein API-Server. Ollama + Chat-UI.',
            '**Stufe 2:** Einzelentwickler, IDE-Integration, eigene Skripte. vLLM + FastAPI.',
            '**Stufe 3:** Team-Deployment, 5+ Entwickler, Dauerbetrieb. vLLM + nginx + Monitoring.',
          ],
        },
        'tier1': {
          title: 'Stufe 1: CLI-Schnellstart (5 Minuten)',
          numberedItems: [
            '`brew install ollama` (macOS) oder Windows-Installer herunterladen.',
            '`ollama run llama3.2` (lädt 8B-Modell herunter und startet es).',
            'Browser öffnen: `http://localhost:11434` (Ollama Web-UI).',
            'Chatten beginnen. Fertig.',
          ],
          content: 'Für Coding: VS Code-Erweiterung „Continue" (`continue.dev`) installieren, auf Ollama-API verweisen und Echtzeit-Vervollständigungen erhalten.',
        },
        'tier2': {
          title: 'Stufe 2: API-Server mit FastAPI (30 Minuten)',
          numberedItems: [
            'Python 3.10+ installieren: `python --version`.',
            'vLLM installieren: `pip install vllm torch`.',
            'vLLM-Server starten: `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`.',
            'Endpunkt testen: `curl http://localhost:8000/v1/chat/completions -d \'{"model": "Llama-3.1-8B-Instruct", "messages": [{"role": "user", "content": "Write Python code for Fibonacci"}]}\' -H "Content-Type: application/json"`.',
            'In IDE integrieren: Copilot-Erweiterung auf `http://localhost:8000` verweisen.',
            'Batch-Anfragen: mehrere Prompts parallel senden, vLLM verarbeitet alle gleichzeitig.',
          ],
          content: 'Warum FastAPI: OpenAI-kompatibler Endpunkt. Drop-in-Ersatz für die echte OpenAI-API im eigenen Code.',
        },
        'tier3': {
          title: 'Stufe 3: Produktivbetrieb für mehrere Nutzer (2 Stunden)',
          numberedItems: [
            '2 vLLM-Instanzen auf separaten GPUs bereitstellen (GPU 0, GPU 1).',
            'nginx konfigurieren, um Anfragen auf beide Instanzen zu verteilen.',
            'Prometheus für Metrikerfassung einrichten (Anfragelatenzen, Tokens/Sekunde, Fehler).',
            'Rate-Limiting pro Nutzer hinzufügen (Token-Bucket-Algorithmus).',
            'Auf Cloud-VM oder lokalem Server mit 10-Gbit/s-Netzwerk bereitstellen.',
            'Optional: Grafana-Dashboard für die Überwachung einrichten.',
          ],
          content: 'Skaliert auf 50+ gleichzeitige Entwickler (je 5 Tok/s) auf einem Dual-GPU-Rechner. Kosten: nur Stromverbrauch (ca. 100 €/Monat bei 24/7-Betrieb).',
        },
        'ide': {
          title: 'IDE-Integration (VS Code, Cursor)',
          content: [
            '**Einrichtung für Echtzeit-Code-Vervollständigungen:**',
            'Alternative (nativer IDE-Support): Der Cursor Editor bietet integrierte Unterstützung für lokale LLMs (keine Erweiterung erforderlich).',
          ],
          numberedItems: [
            '„Continue"-Erweiterung installieren (`continue.dev`).',
            'Erweiterungseinstellungen öffnen, benutzerdefinierte API konfigurieren: `http://localhost:8000/v1` (vLLM-Endpunkt).',
            'Modellnamen auf vLLM-Server abstimmen (`meta-llama/Llama-3.3-8B-Instruct`).',
            'Strg+Umschalt+Leertaste (oder cmd+shift+space) drücken, um Vervollständigung auszulösen.',
            'Vervollständigungen werden in Echtzeit gestreamt (10-20 Tok/s).',
          ],
        },
        'monitoring': {
          title: 'Fehlersuche & Monitoring',
          items: [
            '**vLLM-Logs:** stdout auf Fehler prüfen (Modell-Laden, OOM, CUDA-Fehler).',
            '**Prometheus-Metriken:** vLLM exportiert den `/metrics`-Endpunkt (Anfragezahl, Latenz-Histogramm, generierte Tokens).',
            '**Token-Zählung:** Bibliothek `tiktoken` verwenden, um Tokens vor dem Senden zu zählen (OOM-Überraschungen vermeiden).',
            '**Latenz-Profiling:** Zeitstempel-Logging vor/nach dem vLLM-Aufruf hinzufügen, um Engpässe zu identifizieren.',
          ],
        },
        'regional': {
          title: 'Regionale Rahmenbedingungen & Compliance',
          items: [
            '**EU / DSGVO (Europa):** Lokale Inferenz erfüllt DSGVO-Artikel 28 - keine Daten verlassen die eigene Infrastruktur. Kein Auftragsverarbeitungsvertrag erforderlich. Empfohlen für Gesundheitswesen, Rechts- und Finanzdienstleistungen. BSI-Grundschutz-Kataloge konform für deutsche Unternehmensdeployments. DACH-Unternehmen (Deutschland, Österreich, Schweiz) erreichen vollständige Datensouveränität ohne US-Cloud-Abhängigkeit.',
            '**Japan / METI:** Die METI AI Governance Guidelines 2024 empfehlen On-Premise-Inferenz für sensible Unternehmensdaten. Das vLLM + Stufe-3-Setup erfüllt die METI-Anforderungen an Audit-Trails.',
            '**China / PIPL:** Das Gesetz zum Schutz personenbezogener Daten Chinas (2021) schreibt Datenresidenz vor. Der lokale Stufe-2/3-Stack hält alle Inferenzen im Land. Kompatibel mit GPU-Instanzen von Alibaba Cloud und Tencent Cloud.',
            '**Vereinigte Staaten:** Kein bundesweites KI-Datensouveränitätsmandat (Stand 2026). HIPAA-pflichtige Einrichtungen müssen sicherstellen, dass PHI die kontrollierte Infrastruktur nicht verlässt - Stufe 2/3 erfüllt dies standardmäßig.',
          ],
        },
        'mistakes': {
          title: 'Häufige Einrichtungsfehler',
          items: [
            'vLLM auf derselben GPU betreiben wie einen anderen Prozess (Discord, Gaming). Verursacht GPU-Out-of-Memory-Fehler.',
            'Anfragen ohne Timeout senden. Wenn vLLM hängt, wartet der Client endlos. Immer `timeout=60` in Anfragen setzen.',
            'Davon ausgehen, dass vLLM automatisch über mehrere GPUs skaliert. Erfordert explizites Flag `--tensor-parallel-size`.',
            'CUDA_VISIBLE_DEVICES bei Multi-GPU vergessen. vLLM verwendet standardmäßig alle GPUs.',
            'Llama-2-Modelle im Jahr 2026 verwenden. Meta hat Llama 2 für kommerzielle Nutzung im Januar 2026 eingestellt. Verwenden Sie Llama 3.1 8B Instruct (Apache-2.0-Lizenz, keine Einschränkungen).',
          ],
        },
        'faqSection': {
          title: 'FAQ',
          faqs: [
            { q: 'Welche Stufe soll ich verwenden?', a: 'Stufe 1 für Einzelnutzer (gelegentlicher Gebrauch). Stufe 2 für einzelne Entwickler mit IDE-Integration. Stufe 3 für Teams mit 24/7-Betrieb.' },
            { q: 'Kann ich vLLM statt Ollama verwenden?', a: 'Ja, aber mit mehr Aufwand. vLLM ist schneller (Batching) und flexibler (Python-API).' },
            { q: 'Wie betreibe ich Modelle über mehrere GPUs?', a: 'vLLM: `--tensor-parallel-size 2`. Teilt das Modell auf 2 GPUs auf und verdoppelt den Durchsatz.' },
            { q: 'Kann ich auf vLLM-Inferenz fine-tunen?', a: 'Nein. Fine-Tuning separat durchführen (HuggingFace Transformers), dann das fine-getunete Modell in vLLM laden.' },
            { q: 'Was tun, wenn vLLM OOM auslöst?', a: 'Kleinere Quantisierung verwenden (Q4 statt Q8), Batch-Größe reduzieren oder weniger VRAM pro Modell zuweisen. `nvidia-smi` prüfen.' },
            { q: 'Ist Stufe 3 produktionsreif?', a: 'Ja, mit Monitoring. Prometheus, Grafana und Alerting (Alertmanager) hinzufügen. Standardmäßige Infrastrukturmuster.' },
            { q: 'Muss ich bei der Verwendung des lokalen LLM-Stacks die DSGVO beachten?', a: 'Lokale Inferenz erfüllt DSGVO-Artikel 28 ohne zusätzlichen Aufwand: Alle Daten verbleiben in Ihrer eigenen Infrastruktur, kein Auftragsverarbeiter wird benötigt und keine Drittlandübermittlung findet statt. Das BSI-Grundschutz-Kompendium empfiehlt lokale Verarbeitung für besonders schützenswerte Daten. Für Gesundheits-, Rechts- und Finanzdienstleistungen in Deutschland ist Stufe 2/3 die datenschutzrechtlich bevorzugte Lösung.' },
            { q: 'Ist der lokale LLM-Stack für den deutschen Mittelstand geeignet?', a: 'Ja. Mittelständische Unternehmen profitieren von vollständiger Datensouveränität gemäß BSI-Grundschutz und IT-Sicherheitsgesetz 2.0, keinen laufenden API-Kosten und einer OpenAI-kompatiblen API für ERP- und CRM-Integration. Stufe 2 (vLLM + FastAPI) ist für die meisten Mittelstandsanwendungen ausreichend und in unter 30 Minuten einsatzbereit.' },
          ],
        },
        'relatedReading': {
          title: 'Weiterführende Lektüre',
          items: [
            '[Beste KI-Coding-Assistenten für lokale LLM](/de/local-llms/best-ai-coding-assistant-local-llm) -- Wählen Sie Ihre IDE: Cursor, Continue.dev, Cody, Tabnine mit Unterstützung für lokale LLMs.',
            '[OpenAI-kompatible API mit lokalen LLMs](/de/local-llms/local-llm-openai-compatible-api)',
            '[Ollama-Installations- und Einrichtungsanleitung](/de/local-llms/how-to-install-ollama)',
            '[Lokale LLMs mit VS Code & Cursor](/de/local-llms/local-llms-with-vscode-cursor)',
            '[Fine-Tuning lokaler LLMs mit LoRA](/de/local-llms/fine-tuning-local-llms-lora)',
          ],
        },
        'sources': {
          title: 'Quellen',
          items: [
            '[vLLM OpenAI-Compatible Server Documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html) -- Offizielle vLLM-API-Server-Einrichtungsanleitung',
            '[Continue.dev Configuration Documentation](https://docs.continue.dev/reference/Model%20Providers/openai) -- IDE-Erweiterungskonfiguration für benutzerdefinierte OpenAI-Endpunkte',
            '[Meta Llama 3.1 Model Card](https://llama.meta.com/llama3/) -- Offizielle Llama-3.1-Lizenz und Spezifikationen',
          ],
        },
      },
    },
    fr: {
      theme: 'Outils & Interfaces',
      title: 'Meilleur Stack LLM Local pour Développeurs (avril 2026)',
      seoTitle: 'Stack LLM Local Dev : CLI → API → Production Guide 2026',
      intro: '**Les développeurs devraient utiliser vLLM + FastAPI + l\'extension VS Code Copilot pour une inférence LLM locale de qualité production.** En avril 2026, ce stack permet des complétions de code en temps réel, le traitement par lots et la compatibilité OpenAI API sans dépendance fournisseur. Alternative (plus simple) : Ollama + llama.cpp CLI pour des scripts ponctuels.',
      metaDescription: 'Environnement LLM local en 3 niveaux : (1) Ollama CLI en 5 min, (2) vLLM + FastAPI en 30 min, (3) production multi-GPU avec nginx et Prometheus. Intégration VS Code et Cursor. Avril 2026.',
      twitterDescription: 'Stack LLM local 3 niveaux : Ollama CLI (5 min) → vLLM API (30 min) → production multi-GPU (2h). VS Code + Cursor. Avril 2026.',
      publishDate: '2026-04-05',
      readTime: '10 min de lecture',
      educationalLevel: 'Advanced',
      primaryTerm: 'Developer Stack',
      toc: [
        { label: 'Points clés', anchor: '#tldr' },
        { label: 'Les trois niveaux', anchor: '#tiers' },
        { label: 'Niveau 1 : Démarrage rapide CLI (5 minutes)', anchor: '#tier1' },
        { label: 'Niveau 2 : Serveur API avec FastAPI (30 minutes)', anchor: '#tier2' },
        { label: 'Niveau 3 : Production multi-utilisateurs (2 heures)', anchor: '#tier3' },
        { label: 'Intégration IDE (VS Code, Cursor)', anchor: '#ide' },
        { label: 'Débogage & Monitoring', anchor: '#monitoring' },
        { label: 'Contexte régional & Conformité', anchor: '#regional' },
        { label: 'Erreurs courantes de configuration', anchor: '#mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Lectures complémentaires', anchor: '#related' },
        { label: 'Sources', anchor: '#sources' },
      ],
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        'headline': 'Meilleur Stack LLM Local pour Développeurs (avril 2026)',
        'description': 'Stack production : vLLM, FastAPI, intégration IDE VS Code, complétions temps réel, 30-50 tokens/s. RGPD conforme, sans dépendance fournisseur.',
        'url': 'https://www.promptquorum.com/fr/local-llms/local-llm-developer-stack',
        'datePublished': '2026-04-05',
        'dateModified': '2026-04-19',
        'author': { '@type': 'Person', 'name': 'Hans Kuepper', 'sameAs': 'https://www.promptquorum.com/author/hans-kuepper' },
        'publisher': { '@type': 'Organization', 'name': 'PromptQuorum', 'url': 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Advanced',
        'about': [
          { '@type': 'SoftwareApplication', 'name': 'vLLM' },
          { '@type': 'SoftwareApplication', 'name': 'FastAPI' },
          { '@type': 'SoftwareApplication', 'name': 'Ollama' },
          { '@type': 'SoftwareApplication', 'name': 'Continue.dev' },
        ],
        'speakable': { '@type': 'SpeakableSpecification', 'cssSelector': ['.article-intro', '.key-takeaways'] },
      },
      howToSchema: {
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        'name': 'Comment configurer un stack LLM local pour développeurs',
        'totalTime': 'PT120M',
        'step': [
          { '@type': 'HowToStep', 'name': 'Installer Ollama (Niveau 1)', 'text': 'Exécuter `brew install ollama` sur macOS ou télécharger l\'installateur Windows. Puis lancer `ollama run llama3.2` pour démarrer un modèle local.' },
          { '@type': 'HowToStep', 'name': 'Installer vLLM (Niveau 2)', 'text': 'Installer Python 3.10+ et exécuter `pip install vllm torch`. Démarrer le serveur avec `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`.' },
          { '@type': 'HowToStep', 'name': 'Configurer l\'intégration IDE', 'text': 'Installer l\'extension Continue dans VS Code. Définir l\'endpoint API sur `http://localhost:8000/v1` et le nom du modèle sur `meta-llama/Llama-3.3-8B-Instruct`.' },
          { '@type': 'HowToStep', 'name': 'Configurer le stack de production Niveau 3', 'text': 'Déployer 2 instances vLLM, configurer le load balancer nginx, configurer la collecte de métriques Prometheus et ajouter la limitation de débit par utilisateur.' },
          { '@type': 'HowToStep', 'name': 'Surveiller et déboguer', 'text': 'Vérifier les logs stdout de vLLM pour les erreurs OOM et CUDA. Utiliser l\'endpoint Prometheus /metrics pour la latence des requêtes et le débit en tokens.' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [
          { '@type': 'Question', 'name': 'Quel niveau dois-je utiliser ?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Niveau 1 pour usage solo (occasionnel). Niveau 2 pour un développeur seul avec intégration IDE. Niveau 3 pour une équipe avec service 24/7.' } },
          { '@type': 'Question', 'name': 'Puis-je utiliser vLLM à la place d\'Ollama ?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Oui, mais avec plus de configuration. vLLM est plus rapide (batching) et plus flexible (API Python).' } },
          { '@type': 'Question', 'name': 'Comment répartir les modèles sur plusieurs GPU ?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'vLLM : `--tensor-parallel-size 2`. Répartit le modèle sur 2 GPU pour doubler le débit.' } },
          { '@type': 'Question', 'name': 'Que faire si vLLM provoque un OOM ?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Utiliser une quantification plus petite (Q4 vs Q8), réduire la taille du batch ou allouer moins de VRAM par modèle. Vérifier `nvidia-smi`.' } },
          { '@type': 'Question', 'name': 'Le Niveau 3 est-il prêt pour la production ?', 'acceptedAnswer': { '@type': 'Answer', 'text': 'Oui, avec monitoring. Ajouter Prometheus, Grafana et les alertes (Alertmanager). Schémas d\'infrastructure standard.' } },
        ],
      },
      gammaEmbedUrl: '/presentations/local-llm-developer-stack-static.html',
      gammaDescription: 'Le diaporama ci-dessous couvre la pile locale LLM à trois niveaux (Ollama → vLLM API → multi-utilisateurs en production), l\'intégration IDE avec VS Code et Cursor, le débogage et le monitoring avec Prometheus, ainsi que le contexte régional de conformité. Téléchargez le PDF comme fiche de référence Local LLM Developer Stack.',
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**Niveau 1 (simple) :** `ollama run llama3.2` + OpenWebUI. Aucun code requis.',
            '**Niveau 2 (standard) :** vLLM + wrapper FastAPI. Python 3.10+, pip install 2 paquets, 30 min de configuration.',
            '**Niveau 3 (production) :** vLLM + load balancer nginx + monitoring (Prometheus). Multi-GPU, multi-utilisateurs, tolérant aux pannes.',
            '**Intégration IDE :** VS Code Copilot ou Cursor avec l\'endpoint OpenAI API de vLLM.',
            '**Traitement par lots :** Envoyer 10 prompts simultanément, recevoir 10 réponses en parallèle (non séquentiel).',
            '**Coût :** Zéro (open source) vs 20 $/mois (Claude Pro) ou 200 $/mois (grande équipe, cloud).',
            '**Vitesse :** Niveau 2 atteint 30-50 tok/s pour le coding. Niveau 3 atteint 200+ tok/s entre utilisateurs.',
            '**Complexité :** Niveau 1 (1/10), Niveau 2 (4/10), Niveau 3 (8/10).',
          ],
        },
        'tiers': {
          title: 'Les trois niveaux',
          content: 'Choisir selon le cas d\'usage :',
          items: [
            '**Niveau 1 :** Développeur solo, usage occasionnel, pas de serveur API. Ollama + interface de chat.',
            '**Niveau 2 :** Développeur seul, intégration IDE, scripts personnalisés. vLLM + FastAPI.',
            '**Niveau 3 :** Déploiement équipe, 5+ développeurs, service permanent. vLLM + nginx + monitoring.',
          ],
        },
        'tier1': {
          title: 'Niveau 1 : Démarrage rapide CLI (5 minutes)',
          numberedItems: [
            '`brew install ollama` (macOS) ou télécharger l\'installateur Windows.',
            '`ollama run llama3.2` (télécharge et lance le modèle 8B).',
            'Ouvrir le navigateur : `http://localhost:11434` (interface web Ollama).',
            'Commencer à chatter. Terminé.',
          ],
          content: 'Pour le coding : installer l\'extension VS Code « Continue » (`continue.dev`), pointer vers l\'API Ollama et obtenir des complétions en temps réel.',
        },
        'tier2': {
          title: 'Niveau 2 : Serveur API avec FastAPI (30 minutes)',
          numberedItems: [
            'Installer Python 3.10+ : `python --version`.',
            'Installer vLLM : `pip install vllm torch`.',
            'Démarrer le serveur vLLM : `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`.',
            'Tester l\'endpoint : `curl http://localhost:8000/v1/chat/completions -d \'{"model": "Llama-3.1-8B-Instruct", "messages": [{"role": "user", "content": "Write Python code for Fibonacci"}]}\' -H "Content-Type: application/json"`.',
            'Intégrer dans l\'IDE : pointer l\'extension Copilot vers `http://localhost:8000`.',
            'Requêtes par lots : envoyer plusieurs prompts en parallèle, vLLM les traite tous simultanément.',
          ],
          content: 'Pourquoi FastAPI : endpoint compatible OpenAI. Remplacement direct de l\'API OpenAI réelle dans votre code.',
        },
        'tier3': {
          title: 'Niveau 3 : Production multi-utilisateurs (2 heures)',
          numberedItems: [
            'Déployer 2 instances vLLM sur des GPU séparés (GPU 0, GPU 1).',
            'Configurer nginx pour répartir les requêtes entre les deux instances.',
            'Configurer Prometheus pour la collecte de métriques (latence des requêtes, tokens/sec, erreurs).',
            'Ajouter la limitation de débit par utilisateur (algorithme de token bucket).',
            'Déployer sur VM cloud ou serveur on-prem avec réseau 10 Gbps.',
            'Surveiller via tableau de bord Grafana (optionnel).',
          ],
          content: 'Passe à 50+ développeurs simultanés (5 tok/s chacun) sur un rig dual-GPU. Coût : électricité uniquement (~100 €/mois en 24/7).',
        },
        'ide': {
          title: 'Intégration IDE (VS Code, Cursor)',
          content: [
            '**Configuration pour les complétions de code en temps réel :**',
            'Alternative (support IDE natif) : Cursor Editor intègre nativement le support LLM local (aucune extension requise).',
          ],
          numberedItems: [
            'Installer l\'extension « Continue » (`continue.dev`).',
            'Ouvrir les paramètres de l\'extension, configurer l\'API personnalisée : `http://localhost:8000/v1` (endpoint vLLM).',
            'Définir le nom du modèle pour correspondre au serveur vLLM (`meta-llama/Llama-3.3-8B-Instruct`).',
            'Appuyer sur Ctrl+Maj+Espace (ou cmd+shift+space) pour déclencher la complétion.',
            'Les complétions s\'affichent en temps réel (10-20 tok/s).',
          ],
        },
        'monitoring': {
          title: 'Débogage & Monitoring',
          items: [
            '**Logs vLLM :** Vérifier stdout pour les erreurs (chargement du modèle, OOM, erreurs CUDA).',
            '**Métriques Prometheus :** vLLM exporte l\'endpoint `/metrics` (nombre de requêtes, histogramme de latence, tokens générés).',
            '**Comptage de tokens :** Utiliser la bibliothèque `tiktoken` pour compter les tokens avant l\'envoi (éviter les surprises OOM).',
            '**Profilage de latence :** Ajouter un logging d\'horodatage avant/après l\'appel vLLM pour identifier les goulots d\'étranglement.',
          ],
        },
        'regional': {
          title: 'Contexte régional & Conformité',
          items: [
            '**UE / RGPD (Europe) :** L\'inférence locale satisfait l\'article 28 du RGPD -- aucune donnée ne quitte votre infrastructure. Aucun DPA requis. La CNIL recommande l\'IA locale pour le traitement de données professionnelles sensibles (financières, médicales, juridiques). Recommandé pour la santé, le droit et la finance.',
            '**Japon / METI :** Les directives de gouvernance de l\'IA du METI 2024 recommandent l\'inférence on-premise pour les données d\'entreprise sensibles. Le setup vLLM + Niveau 3 répond aux exigences d\'audit du METI.',
            '**Chine / PIPL :** La loi chinoise sur la protection des informations personnelles (2021) impose la résidence des données. Le stack local Niveau 2/3 garde toutes les inférences dans le pays. Compatible avec les instances GPU Alibaba Cloud et Tencent Cloud.',
            '**États-Unis :** Aucun mandat fédéral de résidence des données IA en 2026. Les entités soumises à HIPAA doivent s\'assurer que les PHI ne quittent pas l\'infrastructure contrôlée -- Niveau 2/3 le garantit par défaut.',
          ],
        },
        'mistakes': {
          title: 'Erreurs courantes de configuration',
          items: [
            'Faire tourner vLLM sur le même GPU qu\'un autre processus (Discord, jeux). Provoque des erreurs GPU out-of-memory.',
            'Envoyer des requêtes sans timeout. Si vLLM se bloque, le client attend indéfiniment. Toujours définir `timeout=60` dans les requêtes.',
            'Supposer que vLLM s\'adapte automatiquement à plusieurs GPU. Nécessite le flag explicite `--tensor-parallel-size`.',
            'Oublier de définir CUDA_VISIBLE_DEVICES en multi-GPU. vLLM utilise tous les GPU par défaut.',
            'Utiliser des modèles Llama 2 en 2026. Meta a déprécié Llama 2 pour usage commercial en janvier 2026. Utiliser Llama 3.1 8B Instruct (licence Apache 2.0, aucune restriction).',
          ],
        },
        'faqSection': {
          title: 'FAQ',
          faqs: [
            { q: 'Quel niveau dois-je utiliser ?', a: 'Niveau 1 pour usage solo (occasionnel). Niveau 2 pour un développeur seul avec intégration IDE. Niveau 3 pour une équipe avec service 24/7.' },
            { q: 'Puis-je utiliser vLLM à la place d\'Ollama ?', a: 'Oui, mais avec plus de configuration. vLLM est plus rapide (batching) et plus flexible (API Python).' },
            { q: 'Comment répartir les modèles sur plusieurs GPU ?', a: 'vLLM : `--tensor-parallel-size 2`. Répartit le modèle sur 2 GPU pour doubler le débit.' },
            { q: 'Puis-je fine-tuner par-dessus l\'inférence vLLM ?', a: 'Non. Fine-tuner séparément (HuggingFace Transformers), puis charger le modèle fine-tuné dans vLLM.' },
            { q: 'Que faire si vLLM provoque un OOM ?', a: 'Utiliser une quantification plus petite (Q4 vs Q8), réduire la taille du batch ou allouer moins de VRAM par modèle. Vérifier `nvidia-smi`.' },
            { q: 'Le Niveau 3 est-il prêt pour la production ?', a: 'Oui, avec monitoring. Ajouter Prometheus, Grafana et les alertes (Alertmanager). Schémas d\'infrastructure standard.' },
          ],
        },
        'relatedReading': {
          title: 'Lectures complémentaires',
          items: [
            '[Meilleur assistant IA de code pour LLM local](/fr/local-llms/best-ai-coding-assistant-local-llm) -- Choisissez votre IDE : Cursor, Continue.dev, Cody, Tabnine avec support LLM local.',
            '[API compatible OpenAI avec LLMs locaux](/fr/local-llms/local-llm-openai-compatible-api)',
            '[Guide d\'installation et de configuration d\'Ollama](/fr/local-llms/how-to-install-ollama)',
            '[LLMs locaux avec VS Code & Cursor](/fr/local-llms/local-llms-with-vscode-cursor)',
            '[Fine-Tuning de LLMs locaux avec LoRA](/fr/local-llms/fine-tuning-local-llms-lora)',
          ],
        },
        'sources': {
          title: 'Sources',
          items: [
            '[vLLM OpenAI-Compatible Server Documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html) -- Guide officiel de configuration du serveur API vLLM',
            '[Continue.dev Configuration Documentation](https://docs.continue.dev/reference/Model%20Providers/openai) -- Configuration de l\'extension IDE pour les endpoints OpenAI personnalisés',
            '[Meta Llama 3.1 Model Card](https://llama.meta.com/llama3/) -- Licence officielle et spécifications de Llama 3.1',
          ],
        },
      },
    },
    ja: {
      theme: 'ツール＆インターフェース',
      title: '開発者向けベストローカルLLMスタック（2026年4月）',
      seoTitle: 'ローカルLLM開発スタック：CLI→API→本番環境ガイド2026',
      intro: '**開発者は、本番グレードのローカルLLM推論にvLLM + FastAPI + VS Code Copilot拡張機能を使用してください。** 2026年4月現在、このスタックはリアルタイムのコード補完、バッチ処理、ベンダーロックインなしのOpenAI API互換性を実現します。代替案（よりシンプル）：単発スクリプト向けにOllama + llama.cpp CLIを使用してください。',
      metaDescription: 'ローカルLLM開発環境を3段階で構築：(1) Ollama CLI 5分、(2) vLLM + FastAPI 30分、(3) 本番マルチGPU（nginx + Prometheus）。VS Code・Cursor IDE連携対応。2026年4月。',
      twitterDescription: '3段階LLM開発スタック：Ollama CLI（5分）→ vLLM API（30分）→ 本番マルチGPU（2時間）。VS Code + Cursor。2026年4月。',
      publishDate: '2026-04-05',
      readTime: '10分で読める',
      educationalLevel: 'Advanced',
      primaryTerm: 'Developer Stack',
      toc: [
        { label: '重要ポイント', anchor: '#tldr' },
        { label: '3つの階層', anchor: '#tiers' },
        { label: '階層1：CLIクイックスタート（5分）', anchor: '#tier1' },
        { label: '階層2：FastAPIによるAPIサーバー（30分）', anchor: '#tier2' },
        { label: '階層3：マルチユーザー本番環境（2時間）', anchor: '#tier3' },
        { label: 'IDE統合（VS Code、Cursor）', anchor: '#ide' },
        { label: 'デバッグ＆モニタリング', anchor: '#monitoring' },
        { label: '地域別コンテキスト＆コンプライアンス', anchor: '#regional' },
        { label: 'よくある設定ミス', anchor: '#mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: '関連記事', anchor: '#related' },
        { label: '参考文献', anchor: '#sources' },
      ],
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        'headline': '開発者向けベストローカルLLMスタック（2026年4月）',
        'description': '本番グレードスタック：vLLM・FastAPI・IDE統合実現。VS Code Copilot拡張でリアルタイムコード補完、30-50トークン/秒。ベンダーロックインなし。',
        'url': 'https://www.promptquorum.com/ja/local-llms/local-llm-developer-stack',
        'datePublished': '2026-04-05',
        'dateModified': '2026-04-19',
        'author': { '@type': 'Organization', 'name': 'PromptQuorum' },
        'publisher': { '@type': 'Organization', 'name': 'PromptQuorum', 'url': 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Advanced',
        'about': [
          { '@type': 'SoftwareApplication', 'name': 'vLLM' },
          { '@type': 'SoftwareApplication', 'name': 'FastAPI' },
          { '@type': 'SoftwareApplication', 'name': 'Ollama' },
          { '@type': 'SoftwareApplication', 'name': 'Continue.dev' },
        ],
        'speakable': { '@type': 'SpeakableSpecification', 'cssSelector': ['.article-intro', '.key-takeaways'] },
      },
      howToSchema: {
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        'name': 'ローカルLLM開発者スタックのセットアップ方法',
        'totalTime': 'PT120M',
        'step': [
          { '@type': 'HowToStep', 'name': 'Ollamaのインストール（階層1）', 'text': 'macOSで`brew install ollama`を実行するか、Windowsインストーラーをダウンロードします。次に`ollama run llama3.2`を実行してローカルモデルを起動します。' },
          { '@type': 'HowToStep', 'name': 'vLLMのインストール（階層2）', 'text': 'Python 3.10+をインストールし、`pip install vllm torch`を実行します。`python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`でサーバーを起動します。' },
          { '@type': 'HowToStep', 'name': 'IDE統合の設定', 'text': 'VS CodeにContinue拡張機能をインストールします。APIエンドポイントを`http://localhost:8000/v1`に、モデル名を`meta-llama/Llama-3.3-8B-Instruct`に設定します。' },
          { '@type': 'HowToStep', 'name': '階層3本番スタックの構築', 'text': '2つのvLLMインスタンスをデプロイし、nginxロードバランサーを設定し、Prometheusメトリクス収集を設定し、ユーザーごとのレート制限を追加します。' },
          { '@type': 'HowToStep', 'name': '監視とデバッグ', 'text': 'vLLMのstdoutログでOOMとCUDAエラーを確認します。Prometheusの/metricsエンドポイントでリクエストレイテンシとトークンスループットを追跡します。' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [
          { '@type': 'Question', 'name': 'どの階層を使うべきですか？', 'acceptedAnswer': { '@type': 'Answer', 'text': '個人利用（カジュアル）なら階層1。IDE統合が必要な単独開発者なら階層2。チームや24/7サービスなら階層3。' } },
          { '@type': 'Question', 'name': 'OllamaのかわりにvLLMを使えますか？', 'acceptedAnswer': { '@type': 'Answer', 'text': '可能ですが、セットアップが増えます。vLLMはバッチ処理で高速で、Python APIによる柔軟性も優れています。' } },
          { '@type': 'Question', 'name': '複数GPUでモデルを提供するには？', 'acceptedAnswer': { '@type': 'Answer', 'text': 'vLLM：`--tensor-parallel-size 2`。モデルを2つのGPUに分散し、スループットを2倍にします。' } },
          { '@type': 'Question', 'name': 'vLLMがOOMになった場合は？', 'acceptedAnswer': { '@type': 'Answer', 'text': '小さい量子化（Q8よりQ4）を使用し、バッチサイズを下げるか、モデルあたりのVRAM割り当てを減らします。`nvidia-smi`で確認してください。' } },
          { '@type': 'Question', 'name': '階層3は本番環境に対応していますか？', 'acceptedAnswer': { '@type': 'Answer', 'text': 'はい、モニタリングがあれば対応しています。Prometheus、Grafana、アラート（Alertmanager）を追加してください。標準的なインフラパターンです。' } },
        ],
      },
      gammaEmbedUrl: '/presentations/local-llm-developer-stack-static.html',
      gammaDescription: '以下のスライドデッキは、3層のローカルLLM開発者スタック（Ollama → vLLM API → 本番マルチユーザー）、VS CodeとCursorを使用したIDE統合、Prometheusによるデバッグとモニタリング、および地域別コンプライアンスコンテキストをカバーしています。PDFをLocal LLM Developer Stackリファレンスカードとしてダウンロードしてください。',
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**階層1（シンプル）：** `ollama run llama3.2` + OpenWebUI。コード不要。',
            '**階層2（標準）：** vLLM + FastAPIラッパー。Python 3.10+、pip install 2パッケージ、30分セットアップ。',
            '**階層3（本番）：** vLLM + nginxロードバランサー + モニタリング（Prometheus）。マルチGPU、マルチユーザー、フォールトトレラント。',
            '**IDE統合：** VS Code CopilotまたはCursorをvLLM OpenAI APIエンドポイントに接続。',
            '**バッチ処理：** 10プロンプトを一度に送信し、10レスポンスを並列受信（順次処理ではない）。',
            '**コスト：** ゼロ（オープンソース）対 20ドル/月（Claude Pro）または200ドル/月（大規模チームクラウド）。',
            '**速度：** 階層2はコーディングで30〜50 tok/sを達成。階層3はユーザー間で200+ tok/sを達成。',
            '**複雑さ：** 階層1（1/10）、階層2（4/10）、階層3（8/10）。',
          ],
        },
        'tiers': {
          title: '3つの階層',
          content: 'ユースケースに基づいて選択してください：',
          items: [
            '**階層1：** 個人開発、カジュアルなチャット、APIサーバー不要。Ollama + チャットUI。',
            '**階層2：** 単独開発者、IDE統合、カスタムスクリプト。vLLM + FastAPI。',
            '**階層3：** チームデプロイ、5人以上の開発者、常時稼働サービス。vLLM + nginx + モニタリング。',
          ],
        },
        'tier1': {
          title: '階層1：CLIクイックスタート（5分）',
          numberedItems: [
            '`brew install ollama`（macOS）またはWindowsインストーラーをダウンロード。',
            '`ollama run llama3.2`（8Bモデルをダウンロードして実行）。',
            'ブラウザを開く：`http://localhost:11434`（Ollama Web UI）。',
            'チャットを開始。完了。',
          ],
          content: 'コーディング向け：VS Code拡張機能「Continue」（`continue.dev`）をインストールし、Ollama APIに向けてリアルタイム補完を取得します。',
        },
        'tier2': {
          title: '階層2：FastAPIによるAPIサーバー（30分）',
          numberedItems: [
            'Python 3.10+をインストール：`python --version`。',
            'vLLMをインストール：`pip install vllm torch`。',
            'vLLMサーバーを起動：`python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`。',
            'エンドポイントをテスト：`curl http://localhost:8000/v1/chat/completions -d \'{"model": "Llama-3.1-8B-Instruct", "messages": [{"role": "user", "content": "Write Python code for Fibonacci"}]}\' -H "Content-Type: application/json"`。',
            'IDEに統合：Copilot拡張機能を`http://localhost:8000`に向ける。',
            'バッチリクエスト：複数のプロンプトを並列送信し、vLLMが一度にすべて処理。',
          ],
          content: 'FastAPIを使う理由：OpenAI互換エンドポイント。コード内で実際のOpenAI APIのドロップイン代替として使用可能。',
        },
        'tier3': {
          title: '階層3：マルチユーザー本番環境（2時間）',
          numberedItems: [
            '別々のGPUに2つのvLLMインスタンスをデプロイ（GPU 0、GPU 1）。',
            '両インスタンス間でリクエストを負荷分散するようnginxを設定。',
            'メトリクス収集のためPrometheusを設定（リクエストレイテンシ、tok/s、エラー）。',
            'ユーザーごとのレート制限を追加（トークンバケットアルゴリズム）。',
            '10GbpsネットワークのクラウドVMまたはオンプレサーバーにデプロイ。',
            'Grafanaダッシュボードで監視（オプション）。',
          ],
          content: 'デュアルGPUリグで50人以上の同時開発者（各5 tok/s）に対応。コスト：電気代のみ（24/7稼働で月約100ドル）。',
        },
        'ide': {
          title: 'IDE統合（VS Code、Cursor）',
          content: [
            'リアルタイムコード補完のセットアップ：',
            '代替案（ネイティブIDEサポート）：Cursor EditorはローカルLLMサポートを内蔵（拡張機能不要）。',
          ],
          numberedItems: [
            '「Continue」拡張機能をインストール（`continue.dev`）。',
            '拡張機能設定を開き、カスタムAPIを設定：`http://localhost:8000/v1`（vLLMエンドポイント）。',
            'モデル名をvLLMサーバーに合わせて設定（`meta-llama/Llama-3.3-8B-Instruct`）。',
            'Ctrl+Shift+Space（またはcmd+shift+space）を押して補完をトリガー。',
            '補完がリアルタイムでストリーミング（10〜20 tok/s）。',
          ],
        },
        'monitoring': {
          title: 'デバッグ＆モニタリング',
          items: [
            '**vLLMログ：** stdoutでエラーを確認（モデルロード、OOM、CUDAエラー）。',
            '**Prometheusメトリクス：** vLLMは`/metrics`エンドポイントをエクスポート（リクエスト数、レイテンシヒストグラム、生成トークン数）。',
            '**トークンカウント：** `tiktoken`ライブラリを使って送信前にトークンをカウント（OOMサプライズを防ぐ）。',
            '**レイテンシプロファイリング：** vLLM呼び出しの前後にタイムスタンプログを追加してボトルネックを特定。',
          ],
        },
        'regional': {
          title: '地域別コンテキスト＆コンプライアンス',
          items: [
            '**日本 / METI：** 経済産業省（METI）のAIガバナンスガイドライン2024は、機密性の高い企業データに対してオンプレミス推論を推奨しています。vLLM + 階層3のセットアップはMETIの監査証跡要件を満たします。日本企業では個人情報保護法（APPI）への対応としてローカル推論が主流になりつつあります。',
            '**東アジア / アジア太平洋：** 韓国の個人情報保護法（PIPA）、台湾のPDPA、シンガポールのPDPAなど、アジア太平洋地域では各国のデータ保護法がローカル処理を推奨しています。階層2/3はこれらすべての要件を満たします。',
            '**グローバル：** GDPR（欧州）、PIPL（中国）、HIPAA（米国）はすべて、制御されたインフラ外へのデータ移転を制限しています。ローカルLLMスタックはこれらすべての規制に対してデフォルトで準拠しています。',
          ],
        },
        'mistakes': {
          title: 'よくある設定ミス',
          items: [
            '別のプロセス（Discord、ゲーム）と同じGPUでvLLMを実行する。GPU out-of-memoryエラーが発生します。',
            'タイムアウトなしでリクエストを送信する。vLLMが停止するとクライアントが永遠に待機します。リクエストには常に`timeout=60`を設定してください。',
            'vLLMが複数GPUに自動スケールすると思い込む。明示的な`--tensor-parallel-size`フラグが必要です。',
            'マルチGPU時にCUDA_VISIBLE_DEVICESを忘れる。vLLMはデフォルトですべてのGPUを使用します。',
            '2026年にLlama 2モデルを使用する。MetaはLlama 2の商用利用を2026年1月に廃止しました。Apache 2.0ライセンス（制限なし）のLlama 3.1 8B Instructを使用してください。',
          ],
        },
        'faqSection': {
          title: 'FAQ',
          faqs: [
            { q: 'どの階層を使うべきですか？', a: '個人利用（カジュアル）なら階層1。IDE統合が必要な単独開発者なら階層2。チームや24/7サービスなら階層3。' },
            { q: 'OllamaのかわりにvLLMを使えますか？', a: '可能ですが、セットアップが増えます。vLLMはバッチ処理で高速で、Python APIによる柔軟性も優れています。' },
            { q: '複数GPUでモデルを提供するには？', a: 'vLLM：`--tensor-parallel-size 2`。モデルを2つのGPUに分散し、スループットを2倍にします。' },
            { q: 'vLLM推論の上でfine-tuneできますか？', a: 'いいえ。HuggingFace Transformersで別途fine-tuneし、fine-tunedモデルをvLLMにロードしてください。' },
            { q: 'vLLMがOOMになった場合は？', a: '小さい量子化（Q8よりQ4）を使用し、バッチサイズを下げるか、モデルあたりのVRAM割り当てを減らします。`nvidia-smi`で確認してください。' },
            { q: '階層3は本番環境に対応していますか？', a: 'はい、モニタリングがあれば対応しています。Prometheus、Grafana、アラート（Alertmanager）を追加してください。標準的なインフラパターンです。' },
          ],
        },
        'relatedReading': {
          title: '関連記事',
          items: [
            '[ローカルLLM向け最高のAIコーディングアシスタント](/ja/local-llms/best-ai-coding-assistant-local-llm) -- IDE選択：Cursor、Continue.dev、Cody、TabnineはローカルLLMをサポートしています。',
            '[ローカルLLMとOpenAI互換API](/ja/local-llms/local-llm-openai-compatible-api)',
            '[Ollamaのインストールとセットアップガイド](/ja/local-llms/how-to-install-ollama)',
            '[VS Code＆CursorでローカルLLMを使う](/ja/local-llms/local-llms-with-vscode-cursor)',
            '[LoRAによるローカルLLMのファインチューニング](/ja/local-llms/fine-tuning-local-llms-lora)',
          ],
        },
        'sources': {
          title: '参考文献',
          items: [
            '[vLLM OpenAI-Compatible Server Documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html) -- 公式vLLM APIサーバー設定ガイド',
            '[Continue.dev Configuration Documentation](https://docs.continue.dev/reference/Model%20Providers/openai) -- カスタムOpenAIエンドポイント向けIDE拡張機能設定',
            '[Meta Llama 3.1 Model Card](https://llama.meta.com/llama3/) -- Llama 3.1の公式ライセンスと仕様',
          ],
        },
      },
    },
    zh: {
      theme: '工具与界面',
      title: '开发者最佳本地LLM技术栈（2026年4月）',
      seoTitle: '本地LLM开发栈：CLI→API→生产环境搭建指南2026',
      intro: '**开发者应使用vLLM + FastAPI + VS Code Copilot扩展来实现生产级本地LLM推理。** 截至2026年4月，该技术栈可实现实时代码补全、批处理以及无厂商锁定的OpenAI API兼容性。替代方案（更简单）：使用Ollama + llama.cpp CLI处理一次性脚本。',
      metaDescription: '3层搭建本地LLM开发环境：(1) Ollama CLI 5分钟、(2) vLLM + FastAPI 30分钟、(3) 多GPU生产环境（nginx + Prometheus）。VS Code和Cursor IDE集成。2026年4月。',
      twitterDescription: '3层LLM开发栈：Ollama CLI（5分钟）→ vLLM API（30分钟）→ 生产多GPU（2小时）。VS Code + Cursor。2026年4月。',
      publishDate: '2026-04-05',
      readTime: '阅读约10分钟',
      educationalLevel: 'Advanced',
      primaryTerm: 'Developer Stack',
      toc: [
        { label: '核心要点', anchor: '#tldr' },
        { label: '三个层级', anchor: '#tiers' },
        { label: '层级一：CLI快速启动（5分钟）', anchor: '#tier1' },
        { label: '层级二：FastAPI接口服务（30分钟）', anchor: '#tier2' },
        { label: '层级三：多用户生产环境（2小时）', anchor: '#tier3' },
        { label: 'IDE集成（VS Code、Cursor）', anchor: '#ide' },
        { label: '调试与监控', anchor: '#monitoring' },
        { label: '区域合规要求', anchor: '#regional' },
        { label: '常见配置错误', anchor: '#mistakes' },
        { label: '常见问题', anchor: '#faq' },
        { label: '延伸阅读', anchor: '#related' },
        { label: '参考资料', anchor: '#sources' },
      ],
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        'headline': '开发者最佳本地LLM技术栈（2026年4月）',
        'description': '生产级技术栈：vLLM、FastAPI、IDE集成实现实时代码补全。30-50令牌/秒，符合PIPL合规，无厂商锁定。',
        'url': 'https://www.promptquorum.com/zh/local-llms/local-llm-developer-stack',
        'datePublished': '2026-04-05',
        'dateModified': '2026-04-19',
        'author': { '@type': 'Organization', 'name': 'PromptQuorum' },
        'publisher': { '@type': 'Organization', 'name': 'PromptQuorum', 'url': 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Advanced',
        'about': [
          { '@type': 'SoftwareApplication', 'name': 'vLLM' },
          { '@type': 'SoftwareApplication', 'name': 'FastAPI' },
          { '@type': 'SoftwareApplication', 'name': 'Ollama' },
          { '@type': 'SoftwareApplication', 'name': 'Continue.dev' },
        ],
        'speakable': { '@type': 'SpeakableSpecification', 'cssSelector': ['.article-intro', '.key-takeaways'] },
      },
      howToSchema: {
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        'name': '如何搭建本地LLM开发者技术栈',
        'totalTime': 'PT120M',
        'step': [
          { '@type': 'HowToStep', 'name': '安装Ollama（层级一）', 'text': '在macOS上运行`brew install ollama`或下载Windows安装程序。然后运行`ollama run llama3.2`启动本地模型。' },
          { '@type': 'HowToStep', 'name': '安装vLLM（层级二）', 'text': '安装Python 3.10+并运行`pip install vllm torch`。使用`python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`启动服务器。' },
          { '@type': 'HowToStep', 'name': '配置IDE集成', 'text': '在VS Code中安装Continue扩展。将API端点设置为`http://localhost:8000/v1`，模型名称设置为`meta-llama/Llama-3.3-8B-Instruct`。' },
          { '@type': 'HowToStep', 'name': '搭建层级三生产技术栈', 'text': '部署2个vLLM实例，配置nginx负载均衡，设置Prometheus指标收集，并为每个用户添加速率限制。' },
          { '@type': 'HowToStep', 'name': '监控与调试', 'text': '检查vLLM的stdout日志中的OOM和CUDA错误。使用Prometheus /metrics端点跟踪请求延迟和令牌吞吐量。' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [
          { '@type': 'Question', 'name': '应该使用哪个层级？', 'acceptedAnswer': { '@type': 'Answer', 'text': '个人使用（临时用途）选层级一。单人开发加IDE集成选层级二。团队和24/7服务选层级三。' } },
          { '@type': 'Question', 'name': '可以用vLLM代替Ollama吗？', 'acceptedAnswer': { '@type': 'Answer', 'text': '可以，但配置更复杂。vLLM批处理更快，Python API更灵活。' } },
          { '@type': 'Question', 'name': '如何在多个GPU上提供模型服务？', 'acceptedAnswer': { '@type': 'Answer', 'text': 'vLLM：`--tensor-parallel-size 2`。将模型分布到2个GPU上，吞吐量翻倍。' } },
          { '@type': 'Question', 'name': 'vLLM出现OOM怎么办？', 'acceptedAnswer': { '@type': 'Answer', 'text': '使用更小的量化（Q4而非Q8），降低批量大小，或减少每个模型的VRAM分配。检查`nvidia-smi`。' } },
          { '@type': 'Question', 'name': '层级三适合生产环境吗？', 'acceptedAnswer': { '@type': 'Answer', 'text': '是的，配合监控可以。添加Prometheus、Grafana和告警（Alertmanager）。标准基础设施模式。' } },
        ],
      },
      gammaEmbedUrl: '/presentations/local-llm-developer-stack-static.html',
      gammaDescription: '下面的幻灯片演示涵盖三层本地LLM开发者堆栈（Ollama → vLLM API → 多用户生产），VS Code和Cursor的IDE集成，Prometheus调试和监控，以及区域合规性背景。将PDF下载为本地LLM开发者堆栈参考卡。',
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**层级一（简单）：** `ollama run llama3.2` + OpenWebUI。无需编写代码。',
            '**层级二（标准）：** vLLM + FastAPI封装。Python 3.10+，pip安装2个包，30分钟完成配置。',
            '**层级三（生产）：** vLLM + nginx负载均衡 + 监控（Prometheus）。多GPU、多用户、高容错。',
            '**IDE集成：** VS Code Copilot或Cursor连接vLLM OpenAI API端点。',
            '**批处理：** 一次发送10个提示词，并行接收10个响应（非顺序处理）。',
            '**成本：** 零费用（开源）对比每月20美元（Claude Pro）或每月200美元（大型团队云服务）。',
            '**速度：** 层级二编码场景达到30-50 tok/s。层级三跨用户达到200+ tok/s。',
            '**复杂度：** 层级一（1/10），层级二（4/10），层级三（8/10）。',
          ],
        },
        'tiers': {
          title: '三个层级',
          content: '根据使用场景选择：',
          items: [
            '**层级一：** 个人开发、日常聊天、无需API服务器。Ollama + 聊天界面。',
            '**层级二：** 单人开发、IDE集成、自定义脚本。vLLM + FastAPI。',
            '**层级三：** 团队部署、5人以上开发者、全天候服务。vLLM + nginx + 监控。',
          ],
        },
        'tier1': {
          title: '层级一：CLI快速启动（5分钟）',
          numberedItems: [
            '`brew install ollama`（macOS）或下载Windows安装程序。',
            '`ollama run llama3.2`（下载并运行8B模型）。',
            '打开浏览器：`http://localhost:11434`（Ollama网页界面）。',
            '开始聊天。完成。',
          ],
          content: '用于编程：安装VS Code扩展「Continue」（`continue.dev`），指向Ollama API，实时获取代码补全。',
        },
        'tier2': {
          title: '层级二：FastAPI接口服务（30分钟）',
          numberedItems: [
            '安装Python 3.10+：`python --version`。',
            '安装vLLM：`pip install vllm torch`。',
            '启动vLLM服务器：`python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3.3-8B-Instruct --port 8000`。',
            '测试端点：`curl http://localhost:8000/v1/chat/completions -d \'{"model": "Llama-3.1-8B-Instruct", "messages": [{"role": "user", "content": "Write Python code for Fibonacci"}]}\' -H "Content-Type: application/json"`。',
            '集成到IDE：将Copilot扩展指向`http://localhost:8000`。',
            '批量请求：并行发送多个提示词，vLLM同时处理所有请求。',
          ],
          content: '为什么用FastAPI：兼容OpenAI的端点。在您的代码中可直接替换真实的OpenAI API。',
        },
        'tier3': {
          title: '层级三：多用户生产环境（2小时）',
          numberedItems: [
            '在独立GPU上部署2个vLLM实例（GPU 0、GPU 1）。',
            '配置nginx在两个实例之间进行负载均衡。',
            '设置Prometheus进行指标收集（请求延迟、令牌/秒、错误率）。',
            '为每个用户添加速率限制（令牌桶算法）。',
            '在云VM或配备10Gbps网络的本地服务器上部署。',
            '通过Grafana仪表板进行监控（可选）。',
          ],
          content: '双GPU服务器可支持50+名并发开发者（每人5 tok/s）。成本：仅电费（24/7运行约每月100美元）。',
        },
        'ide': {
          title: 'IDE集成（VS Code、Cursor）',
          content: [
            '实时代码补全配置：',
            '替代方案（原生IDE支持）：Cursor编辑器内置本地LLM支持（无需扩展）。',
          ],
          numberedItems: [
            '安装「Continue」扩展（`continue.dev`）。',
            '打开扩展设置，配置自定义API：`http://localhost:8000/v1`（vLLM端点）。',
            '设置模型名称以匹配vLLM服务器（`meta-llama/Llama-3.3-8B-Instruct`）。',
            '按Ctrl+Shift+Space（或cmd+shift+space）触发补全。',
            '补全实时流式传输（10-20 tok/s）。',
          ],
        },
        'monitoring': {
          title: '调试与监控',
          items: [
            '**vLLM日志：** 检查stdout中的错误（模型加载、OOM、CUDA错误）。',
            '**Prometheus指标：** vLLM导出`/metrics`端点（请求数、延迟直方图、生成令牌数）。',
            '**令牌计数：** 使用`tiktoken`库在发送前计算令牌数（避免OOM意外）。',
            '**延迟分析：** 在vLLM调用前后添加时间戳日志以识别瓶颈。',
          ],
        },
        'regional': {
          title: '区域合规要求',
          items: [
            '**中国（数据安全法）：** 中国2021年《数据安全法》和《个人信息保护法》要求数据本地化存储。本地LLM推理确保所有数据留在境内，完全符合监管要求。Qwen2.5系列模型特别适合中国企业部署，推荐金融、医疗、法律行业优先选用。',
            '**亚太地区（数据跨境）：** 韩国《个人信息保护法》（PIPA）、新加坡《个人数据保护法》（PDPA）、澳大利亚《隐私法》均对跨境数据传输有严格限制。层级2/3本地推理栈满足所有亚太地区数据驻留要求，无需跨境数据传输合规审批。',
            '**企业部署：** 银行、医院、律所等监管敏感行业可通过层级三实现完全合规的AI推理基础设施。配合Prometheus监控和nginx访问控制，可满足等保2.0三级及以上要求。企业可在阿里云或腾讯云GPU实例上部署，数据完全留在中国境内。',
          ],
        },
        'mistakes': {
          title: '常见配置错误',
          items: [
            '在与其他进程（Discord、游戏）相同的GPU上运行vLLM。导致GPU内存不足错误。',
            '发送请求时不设置超时。如果vLLM挂起，客户端将永远等待。请始终在请求中设置`timeout=60`。',
            '假设vLLM能自动跨多个GPU扩展。需要明确设置`--tensor-parallel-size`标志。',
            '多GPU时忘记设置CUDA_VISIBLE_DEVICES。vLLM默认使用所有GPU。',
            '在2026年使用Llama 2模型。Meta于2026年1月废弃了Llama 2的商业使用。请使用Llama 3.1 8B Instruct（Apache 2.0许可证，无限制）。',
          ],
        },
        'faqSection': {
          title: '常见问题',
          faqs: [
            { q: '应该使用哪个层级？', a: '个人使用（临时用途）选层级一。单人开发加IDE集成选层级二。团队和24/7服务选层级三。' },
            { q: '可以用vLLM代替Ollama吗？', a: '可以，但配置更复杂。vLLM批处理更快，Python API更灵活。' },
            { q: '如何在多个GPU上提供模型服务？', a: 'vLLM：`--tensor-parallel-size 2`。将模型分布到2个GPU上，吞吐量翻倍。' },
            { q: '能在vLLM推理基础上进行微调吗？', a: '不能。请使用HuggingFace Transformers单独进行微调，然后将微调后的模型加载到vLLM中。' },
            { q: 'vLLM出现OOM怎么办？', a: '使用更小的量化（Q4而非Q8），降低批量大小，或减少每个模型的VRAM分配。检查`nvidia-smi`。' },
            { q: '层级三适合生产环境吗？', a: '是的，配合监控可以。添加Prometheus、Grafana和告警（Alertmanager）。标准基础设施模式。' },
          ],
        },
        'relatedReading': {
          title: '延伸阅读',
          items: [
            '[本地LLM最佳AI编码助手](/zh/local-llms/best-ai-coding-assistant-local-llm) -- 选择您的IDE：Cursor、Continue.dev、Cody、Tabnine支持本地LLM。',
            '[本地LLM与OpenAI兼容API](/zh/local-llms/local-llm-openai-compatible-api)',
            '[Ollama安装与配置指南](/zh/local-llms/how-to-install-ollama)',
            '[在VS Code和Cursor中使用本地LLM](/zh/local-llms/local-llms-with-vscode-cursor)',
            '[使用LoRA对本地LLM进行微调](/zh/local-llms/fine-tuning-local-llms-lora)',
          ],
        },
        'sources': {
          title: '参考资料',
          items: [
            '[vLLM OpenAI-Compatible Server Documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html) -- vLLM API服务器官方配置指南',
            '[Continue.dev Configuration Documentation](https://docs.continue.dev/reference/Model%20Providers/openai) -- 自定义OpenAI端点的IDE扩展配置文档',
            '[Meta Llama 3.1 Model Card](https://llama.meta.com/llama3/) -- Llama 3.1官方许可证与规格说明',
          ],
        },
      },
    },
  };
