// Auto-generated from src/lib/local-llms/content.ts
// Slug: multimodal-local-llms
// Generated: 2026-05-03T11:33:08.370Z

import type { Language } from "@/lib/blog/blogContent";

import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
    en: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: 'Multimodal Local LLMs: Vision, Audio, and Text Processing',
      seoTitle: 'Multimodal Local LLMs',
      intro: 'Multimodal models process images, text, and audio. As of April 2026, Llama 3.2 Vision, Gemma 3 Vision, and Qwen2-VL are practical multimodal models for local deployment. They enable document OCR, image analysis, and visual question-answering without cloud APIs.',
      metaDescription: 'Multimodal local LLMs 2026: vision, image processing, OCR, audio models. LLaVA, Qwen-VL guides with use cases.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**Multimodal models process images, text, and audio. As of April 2026, Llama 3.2 Vision, Gemma 3 Vision, and Qwen2-VL are practical multimodal models for local deployment.**',
      audience: 'Beginners running their first local LLM on consumer hardware',
      readTime: '10 min read',
      educationalLevel: 'Intermediate to Advanced',
      primaryTerm: 'multimodal models',
      toc: [
        { label: 'Key Takeaways', anchor: '#key-takeaways' },
        { label: 'Multimodal Models Available', anchor: '#models' },
        { label: 'Vision Capabilities', anchor: '#vision' },
        { label: 'Setup and Usage', anchor: '#setup' },
        { label: 'Real-World Use Cases', anchor: '#use-cases' },
        { label: 'Performance and Limitations', anchor: '#performance' },
        { label: 'Common Mistakes', anchor: '#common-mistakes' },
        { label: 'Related Reading', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**Multimodal = text + images (+ audio).** Process images natively without OCR preprocessing.',
            '**Best models (2026):** Llama 3.2 Vision 11B, Qwen2-VL 7B, Gemma 3 Vision 9B.',
            '**Use cases:** Document OCR, image analysis, visual Q&A, table extraction.',
            '**Speed:** 2-5 seconds per image (11B model). Slower than text-only, but practical.',
            'As of April 2026, multimodal is mature for specific use cases, not yet general-purpose.',
          ],
        },
        models: {
          title: 'Multimodal Models Available (April 2026)',
          rows: [
            { 'Model': 'Llama 3.2 Vision 11B', 'Image Support': 'Yes', 'VRAM': '8 GB', 'Speed': '3-5 sec/image', 'Best For': 'General vision' },
            { 'Model': 'Qwen2-VL 7B', 'Image Support': 'Yes', 'VRAM': '5 GB', 'Speed': '2-3 sec/image', 'Best For': 'Fast vision' },
            { 'Model': 'Gemma 3 Vision 9B', 'Image Support': 'Yes', 'VRAM': '6 GB', 'Speed': '3 sec/image', 'Best For': 'Balanced' },
            { 'Model': 'Llama 3.2 Vision 90B', 'Image Support': 'Yes', 'VRAM': '55 GB', 'Speed': '10+ sec/image', 'Best For': 'High quality' },
          ],
          columns: ['Model', 'Image Support', 'VRAM', 'Speed per Image', 'Best For'],
        },
        vision: {
          title: 'Vision Capabilities',
          content: [
            'Multimodal models can:',
          ],
          items: [
            '**Image description:** Explain what is in an image.',
            '**OCR (Optical Character Recognition):** Extract text from images (business card, document scan).',
            '**Visual Q&A:** Answer questions about images ("What is the brand of the car?").',
            '**Table extraction:** Parse tables from images into structured data.',
            '**Chart analysis:** Interpret data visualizations.',
            '**Object detection:** Identify and locate objects in images.',
          ],
        },
        setup: {
          title: 'Setup and Usage',
          content: 'Using Llama 3.2 Vision with Ollama:',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: 'Real-World Use Cases',
          items: [
            '**Document processing:** Extract text from scanned PDFs without external OCR service.',
            '**Content moderation:** Flag inappropriate images without sending to cloud.',
            '**Accessibility:** Describe images for visually impaired users.',
            '**Product analysis:** Analyze product images in e-commerce (category, condition, defects).',
            '**Research:** Analyze scientific charts and diagrams.',
          ],
        },
        performance: {
          title: 'Performance and Limitations',
          content: [
            '**Accuracy:** Good for document OCR and description, but not perfect for detailed analysis or small objects.',
            '**Speed:** 2-5 seconds per image. Cloud models (GPT-4 Vision) are 10-50× faster.',
            '**Image size:** Supports up to ~1000×1000 pixels. Larger images are downsampled.',
            '**Limitations:** Cannot match GPT-4 Vision accuracy on complex scenes. Trade-off: privacy vs. quality.',
          ],
        },
        commonMistakes: {
          title: 'Common Mistakes',
          items: [
            '**Expecting accuracy of GPT-4 Vision.** Local models are 20-30% less accurate. Use for specific domains, not general vision.',
            '**Not preparing images.** Crop images to focus area. Remove noise. Better input = better output.',
            '**Using 7B models for complex vision.** Small models struggle with subtle details. Use 11B+ for reliable vision.',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Related Reading',
          items: [
            '[Best Local LLMs for Coding](/local-llms/best-local-llms-for-coding) -- Vision can help code understanding.',
            '[Local RAG 2026](/local-llms/local-rag-2026) -- Combine vision with RAG for document processing.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Sources',
          items: [
            'Llama 3.2 Vision Model Card -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
    },
    es: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: 'LLMs locales multimodales: visión, audio y procesamiento de texto',
      seoTitle: 'LLMs locales multimodales',
      intro: 'Los modelos multimodales procesan imágenes, texto y audio. A partir de abril de 2026, Llama 3.2 Vision, Gemma 3 Vision y Qwen2-VL son modelos multimodales prácticos para implementación local. Permiten OCR de documentos, análisis de imágenes y preguntas y respuestas visuales sin APIs de nube.',
      metaDescription: 'LLMs locales multimodales 2026: visión, procesamiento de imágenes, OCR, modelos de audio. Guías de LLaVA y Qwen-VL con casos de uso.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**Los modelos multimodales procesan imágenes, texto y audio. A partir de abril de 2026, Llama 3.2 Vision, Gemma 3 Vision y Qwen2-VL son modelos multimodales prácticos para implementación local.**',
      audience: 'Principiantes ejecutando su primer LLM local en hardware de consumo',
      readTime: '10 min de lectura',
      educationalLevel: 'Intermediate to Advanced',
      primaryTerm: 'modelos multimodales',
      toc: [
        { label: 'Puntos clave', anchor: '#key-takeaways' },
        { label: 'Modelos multimodales disponibles', anchor: '#models' },
        { label: 'Capacidades de visión', anchor: '#vision' },
        { label: 'Configuración y uso', anchor: '#setup' },
        { label: 'Casos de uso reales', anchor: '#use-cases' },
        { label: 'Rendimiento y limitaciones', anchor: '#performance' },
        { label: 'Errores comunes', anchor: '#common-mistakes' },
        { label: 'Lecturas relacionadas', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            '**Multimodal = texto + imágenes (+ audio).** Procesa imágenes de forma nativa sin preprocesamiento OCR.',
            '**Mejores modelos (2026):** Llama 3.2 Vision 11B, Qwen2-VL 7B, Gemma 3 Vision 9B.',
            '**Casos de uso:** OCR de documentos, análisis de imágenes, preguntas y respuestas visuales, extracción de tablas.',
            '**Velocidad:** 2-5 segundos por imagen (modelo 11B). Más lento que solo texto, pero práctico.',
            'A partir de abril de 2026, lo multimodal es maduro para casos de uso específicos, pero no de propósito general todavía.',
          ],
        },
        models: {
          title: 'Modelos multimodales disponibles (abril de 2026)',
          rows: [
            { 'Modelo': 'Llama 3.2 Vision 11B', 'Soporte de imagen': 'Sí', 'VRAM': '8 GB', 'Velocidad': '3-5 seg/imagen', 'Mejor para': 'Visión general' },
            { 'Modelo': 'Qwen2-VL 7B', 'Soporte de imagen': 'Sí', 'VRAM': '5 GB', 'Velocidad': '2-3 seg/imagen', 'Mejor para': 'Visión rápida' },
            { 'Modelo': 'Gemma 3 Vision 9B', 'Soporte de imagen': 'Sí', 'VRAM': '6 GB', 'Velocidad': '3 seg/imagen', 'Mejor para': 'Equilibrado' },
            { 'Modelo': 'Llama 3.2 Vision 90B', 'Soporte de imagen': 'Sí', 'VRAM': '55 GB', 'Velocidad': '10+ seg/imagen', 'Mejor para': 'Alta calidad' },
          ],
          columns: ['Modelo', 'Soporte de imagen', 'VRAM', 'Velocidad por imagen', 'Mejor para'],
        },
        vision: {
          title: 'Capacidades de visión',
          content: [
            'Los modelos multimodales pueden:',
          ],
          items: [
            '**Descripción de imágenes:** Explica qué hay en una imagen.',
            '**OCR (Reconocimiento óptico de caracteres):** Extrae texto de imágenes (tarjeta de visita, escaneo de documento).',
            '**Preguntas y respuestas visuales:** Responde preguntas sobre imágenes ("¿Cuál es la marca del auto?").',
            '**Extracción de tablas:** Analiza tablas de imágenes en datos estructurados.',
            '**Análisis de gráficos:** Interpreta visualizaciones de datos.',
            '**Detección de objetos:** Identifica y localiza objetos en imágenes.',
          ],
        },
        setup: {
          title: 'Configuración y uso',
          content: 'Usando Llama 3.2 Vision con Ollama:',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: 'Casos de uso reales',
          items: [
            '**Procesamiento de documentos:** Extrae texto de PDFs escaneados sin servicio OCR externo.',
            '**Moderación de contenido:** Marca imágenes inapropiadas sin enviarlas a la nube.',
            '**Accesibilidad:** Describe imágenes para usuarios con discapacidad visual.',
            '**Análisis de productos:** Analiza imágenes de productos en e-commerce (categoría, estado, defectos).',
            '**Investigación:** Analiza gráficos y diagramas científicos.',
          ],
        },
        performance: {
          title: 'Rendimiento y limitaciones',
          content: [
            '**Precisión:** Buena para OCR de documentos y descripción, pero no perfecta para análisis detallado u objetos pequeños.',
            '**Velocidad:** 2-5 segundos por imagen. Los modelos de nube (GPT-4 Vision) son 10-50× más rápidos.',
            '**Tamaño de imagen:** Soporta hasta ~1000×1000 píxeles. Las imágenes más grandes se reducen por muestreo.',
            '**Limitaciones:** No puede igualar la precisión de GPT-4 Vision en escenas complejas. Compromiso: privacidad frente a calidad.',
          ],
        },
        commonMistakes: {
          title: 'Errores comunes',
          items: [
            '**Esperar la precisión de GPT-4 Vision.** Los modelos locales son 20-30% menos precisos. Úsalos para dominios específicos, no para visión general.',
            '**No preparar las imágenes.** Recorta las imágenes al área de enfoque. Elimina el ruido. Mejor entrada = mejor salida.',
            '**Usar modelos 7B para visión compleja.** Los modelos pequeños tienen dificultades con detalles sutiles. Usa 11B+ para visión confiable.',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Lecturas relacionadas',
          items: [
            '[Mejores LLMs locales para programación](/es/local-llms/best-local-llms-for-coding) -- La visión puede ayudar a entender el código.',
            '[RAG local 2026](/es/local-llms/local-rag-2026) -- Combina visión con RAG para el procesamiento de documentos.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Fuentes',
          items: [
            'Llama 3.2 Vision Model Card -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'LLMs locales multimodales: visión, audio y procesamiento de texto',
        description: 'LLMs locales multimodales 2026: visión, OCR, procesamiento de imágenes. LLaVA, Qwen-VL.',
        url: 'https://www.promptquorum.com/es/local-llms/multimodal-local-llms',
        inLanguage: 'es',
        datePublished: '2026-04-04',
        dateModified: '2026-04-04',
        author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Intermediate to Advanced',
      },
    },
    ar: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: 'نماذج LLM المحلية متعددة الوسائط: معالجة الرؤية والصوت والنص',
      seoTitle: 'نماذج LLM المحلية متعددة الوسائط 2026: رؤية وOCR',
      intro: 'تعالج النماذج متعددة الوسائط الصور والنص والصوت. اعتبارًا من أبريل 2026، Llama 3.2 Vision وGemma 3 Vision وQwen2-VL نماذج متعددة الوسائط عملية للنشر المحلي. تتيح OCR للمستندات وتحليل الصور والأسئلة والأجوبة البصرية دون واجهات API سحابية.',
      metaDescription: 'نماذج LLM المحلية متعددة الوسائط: رؤية الحاسوب، معالجة الصور، OCR، ونماذج الصوت. أدلة LLaVA وQwen-VL مع حالات استخدام فعلية وأداء مقارن 2026.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**تعالج النماذج متعددة الوسائط الصور والنص والصوت. اعتبارًا من أبريل 2026، Llama 3.2 Vision وGemma 3 Vision وQwen2-VL نماذج متعددة الوسائط عملية للنشر المحلي.**',
      audience: 'مبتدئون يشغّلون أول نموذج LLM محلي على عتاد استهلاكي',
      readTime: '10 دقائق قراءة',
      educationalLevel: 'Intermediate to Advanced',
      primaryTerm: 'نماذج متعددة الوسائط',
      toc: [
        { label: 'النقاط الرئيسية', anchor: '#key-takeaways' },
        { label: 'النماذج متعددة الوسائط المتاحة', anchor: '#models' },
        { label: 'قدرات الرؤية', anchor: '#vision' },
        { label: 'الإعداد والاستخدام', anchor: '#setup' },
        { label: 'حالات استخدام حقيقية', anchor: '#use-cases' },
        { label: 'الأداء والقيود', anchor: '#performance' },
        { label: 'أخطاء شائعة', anchor: '#common-mistakes' },
        { label: 'قراءات ذات صلة', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            '**متعدد الوسائط = نص + صور (+ صوت).** يعالج الصور أصليًا دون معالجة OCR مسبقة.',
            '**أفضل النماذج (2026):** Llama 3.2 Vision 11B، Qwen2-VL 7B، Gemma 3 Vision 9B.',
            '**حالات الاستخدام:** OCR للمستندات، تحليل الصور، الأسئلة والأجوبة البصرية، استخراج الجداول.',
            '**السرعة:** 2-5 ثوانٍ لكل صورة (نموذج 11B). أبطأ من النص وحده، لكنه عملي.',
            'اعتبارًا من أبريل 2026، تعدد الوسائط ناضج لحالات استخدام محددة، لكنه ليس للأغراض العامة بعد.',
          ],
        },
        models: {
          title: 'النماذج متعددة الوسائط المتاحة (أبريل 2026)',
          rows: [
            { 'Modelo': 'Llama 3.2 Vision 11B', 'Soporte de imagen': 'نعم', 'VRAM': '8 GB', 'Velocidad': '3-5 ث/صورة', 'Mejor para': 'رؤية عامة' },
            { 'Modelo': 'Qwen2-VL 7B', 'Soporte de imagen': 'نعم', 'VRAM': '5 GB', 'Velocidad': '2-3 ث/صورة', 'Mejor para': 'رؤية سريعة' },
            { 'Modelo': 'Gemma 3 Vision 9B', 'Soporte de imagen': 'نعم', 'VRAM': '6 GB', 'Velocidad': '3 ث/صورة', 'Mejor para': 'متوازن' },
            { 'Modelo': 'Llama 3.2 Vision 90B', 'Soporte de imagen': 'نعم', 'VRAM': '55 GB', 'Velocidad': '10+ ث/صورة', 'Mejor para': 'جودة عالية' },
          ],
          columns: ['Modelo', 'Soporte de imagen', 'VRAM', 'Velocidad por imagen', 'Mejor para'],
        },
        vision: {
          title: 'قدرات الرؤية',
          content: [
            'يمكن للنماذج متعددة الوسائط:',
          ],
          items: [
            '**وصف الصور:** يشرح ما في الصورة.',
            '**OCR (التعرّف الضوئي على الحروف):** يستخرج النص من الصور (بطاقة عمل، مسح مستند).',
            '**أسئلة وأجوبة بصرية:** يجيب عن أسئلة حول الصور ("ما ماركة السيارة؟").',
            '**استخراج الجداول:** يحلّل جداول الصور إلى بيانات منظّمة.',
            '**تحليل الرسوم البيانية:** يفسّر تصورات البيانات.',
            '**كشف الكائنات:** يحدّد ويوضّع الكائنات في الصور.',
          ],
        },
        setup: {
          title: 'الإعداد والاستخدام',
          content: 'باستخدام Llama 3.2 Vision مع Ollama:',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: 'حالات استخدام حقيقية',
          items: [
            '**معالجة المستندات:** يستخرج النص من ملفات PDF الممسوحة دون خدمة OCR خارجية.',
            '**الإشراف على المحتوى:** يضع علامة على الصور غير اللائقة دون إرسالها للسحابة.',
            '**إمكانية الوصول:** يصف الصور للمستخدمين ذوي الإعاقة البصرية.',
            '**تحليل المنتجات:** يحلّل صور المنتجات في التجارة الإلكترونية (الفئة، الحالة، العيوب).',
            '**البحث:** يحلّل الرسوم البيانية والمخططات العلمية.',
          ],
        },
        performance: {
          title: 'الأداء والقيود',
          content: [
            '**الدقة:** جيدة لـ OCR المستندات والوصف، لكنها ليست مثالية للتحليل التفصيلي أو الكائنات الصغيرة.',
            '**السرعة:** 2-5 ثوانٍ لكل صورة. النماذج السحابية (GPT-4 Vision) أسرع بمقدار 10-50×.',
            '**حجم الصورة:** يدعم حتى ~1000×1000 بكسل. الصور الأكبر يُخفَّض معدل أخذ عيناتها.',
            '**القيود:** لا يمكنه مضاهاة دقة GPT-4 Vision في المشاهد المعقدة. المقايضة: الخصوصية مقابل الجودة.',
          ],
        },
        commonMistakes: {
          title: 'أخطاء شائعة',
          items: [
            '**توقّع دقة GPT-4 Vision.** النماذج المحلية أقل دقة بنسبة 20-30%. استخدمها لمجالات محددة، لا للرؤية العامة.',
            '**عدم تجهيز الصور.** اقتصّ الصور إلى منطقة التركيز. أزل الضوضاء. إدخال أفضل = إخراج أفضل.',
            '**استخدام نماذج 7B للرؤية المعقدة.** النماذج الصغيرة تكافح مع التفاصيل الدقيقة. استخدم 11B+ للرؤية الموثوقة.',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'قراءات ذات صلة',
          items: [
            '[أفضل نماذج LLM المحلية للبرمجة](/ar/local-llms/best-local-llms-for-coding) -- يمكن للرؤية المساعدة في فهم الشيفرة.',
            '[RAG محلي 2026](/ar/local-llms/local-rag-2026) -- ادمج الرؤية مع RAG لمعالجة المستندات.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'المصادر',
          items: [
            'بطاقة نموذج Llama 3.2 Vision -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'نماذج LLM المحلية متعددة الوسائط: معالجة الرؤية والصوت والنص',
        description: 'نماذج LLM المحلية متعددة الوسائط 2026: الرؤية، OCR، معالجة الصور. LLaVA، Qwen-VL.',
        url: 'https://www.promptquorum.com/ar/local-llms/multimodal-local-llms',
        inLanguage: 'ar',
        datePublished: '2026-04-04',
        dateModified: '2026-04-04',
        author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Intermediate to Advanced',
      },
    },
    de: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: 'Multimodale lokale LLMs: Vision, Audio und Textverarbeitung',
      seoTitle: 'Multimodale lokale LLMs',
      intro: 'Multimodale Modelle verarbeiten Bilder, Text und Audio. Ab April 2026 sind Llama 3.2 Vision, Gemma 3 Vision und Qwen2-VL praktische multimodale Modelle für lokale Bereitstellung. Sie ermöglichen Dokumenten-OCR, Bildanalyse und visuelle Frage-Antwort-Verarbeitung ohne Cloud-APIs.',
      metaDescription: 'Multimodale lokale LLMs 2026: Vision, Bildverarbeitung, OCR, Audio-Modelle. LLaVA, Qwen-VL-Anleitungen mit Anwendungsfällen.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**Multimodale Modelle verarbeiten Bilder, Text und Audio. Ab April 2026 sind Llama 3.2 Vision, Gemma 3 Vision und Qwen2-VL praktische multimodale Modelle für lokale Bereitstellung.**',
      audience: 'Anfänger, die ihr erstes lokales LLM auf Consumer-Hardware ausführen',
      readTime: '10 Min. Lesezeit',
      educationalLevel: 'Intermediate to Advanced',
      primaryTerm: 'multimodale Modelle',
      toc: [
        { label: 'Zusammenfassung', anchor: '#key-takeaways' },
        { label: 'Verfügbare multimodale Modelle', anchor: '#models' },
        { label: 'Vision-Fähigkeiten', anchor: '#vision' },
        { label: 'Setup und Verwendung', anchor: '#setup' },
        { label: 'Praktische Anwendungsfälle', anchor: '#use-cases' },
        { label: 'Performance und Einschränkungen', anchor: '#performance' },
        { label: 'Häufige Fehler', anchor: '#common-mistakes' },
        { label: 'Weiterführende Literatur', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**Multimodal = Text + Bilder (+ Audio).** Verarbeiten Sie Bilder nativ ohne OCR-Vorverarbeitung.',
            '**Beste Modelle (2026):** Llama 3.2 Vision 11B, Qwen2-VL 7B, Gemma 3 Vision 9B.',
            '**Anwendungsfälle:** Dokumenten-OCR, Bildanalyse, visuelle Q&A, Tabellenextraktion.',
            '**Geschwindigkeit:** 2-5 Sekunden pro Bild (11B-Modell). Langsamer als reiner Text, aber praktisch.',
            'Ab April 2026 ist Multimodal für spezifische Anwendungsfälle reif, noch nicht für allgemeine Zwecke.',
          ],
        },
        models: {
          title: 'Verfügbare multimodale Modelle (April 2026)',
          rows: [
            { 'Modell': 'Llama 3.2 Vision 11B', 'Bildunterstützung': 'Ja', 'VRAM': '8 GB', 'Geschwindigkeit': '3-5 Sek./Bild', 'Am besten für': 'Allgemeine Vision' },
            { 'Modell': 'Qwen2-VL 7B', 'Bildunterstützung': 'Ja', 'VRAM': '5 GB', 'Geschwindigkeit': '2-3 Sek./Bild', 'Am besten für': 'Schnelle Vision' },
            { 'Modell': 'Gemma 3 Vision 9B', 'Bildunterstützung': 'Ja', 'VRAM': '6 GB', 'Geschwindigkeit': '3 Sek./Bild', 'Am besten für': 'Ausgeglichen' },
            { 'Modell': 'Llama 3.2 Vision 90B', 'Bildunterstützung': 'Ja', 'VRAM': '55 GB', 'Geschwindigkeit': '10+ Sek./Bild', 'Am besten für': 'Hohe Qualität' },
          ],
          columns: ['Modell', 'Bildunterstützung', 'VRAM', 'Geschwindigkeit pro Bild', 'Am besten für'],
        },
        vision: {
          title: 'Vision-Fähigkeiten',
          content: [
            'Multimodale Modelle können:',
          ],
          items: [
            '**Bildbeschreibung:** Erklären Sie, was in einem Bild zu sehen ist.',
            '**OCR (Optische Zeichenerkennung):** Text aus Bildern extrahieren (Visitenkarte, Dokumentenscan).',
            '**Visuelle Q&A:** Fragen zu Bildern beantworten („Was ist die Marke des Autos?").',
            '**Tabellenextraktion:** Tabellen aus Bildern in strukturierte Daten umwandeln.',
            '**Diagrammanalyse:** Datenvisualisierungen interpretieren.',
            '**Objekterkennung:** Objekte in Bildern identifizieren und lokalisieren.',
          ],
        },
        setup: {
          title: 'Setup und Verwendung',
          content: 'Verwendung von Llama 3.2 Vision mit Ollama:',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: 'Praktische Anwendungsfälle',
          items: [
            '**Dokumentenverarbeitung:** Text aus gescannten PDFs extrahieren ohne externen OCR-Service.',
            '**Inhaltsmoderation:** Unangemessene Bilder kennzeichnen, ohne an die Cloud zu senden.',
            '**Barrierefreiheit:** Bilder für sehbehinderte Benutzer beschreiben.',
            '**Produktanalyse:** Produktbilder im E-Commerce analysieren (Kategorie, Zustand, Mängel).',
            '**Forschung:** Wissenschaftliche Diagramme und Schaubilder analysieren.',
          ],
        },
        performance: {
          title: 'Performance und Einschränkungen',
          content: [
            '**Genauigkeit:** Gut für Dokumenten-OCR und Beschreibung, aber nicht perfekt für detaillierte Analysen oder kleine Objekte.',
            '**Geschwindigkeit:** 2-5 Sekunden pro Bild. Cloud-Modelle (GPT-4 Vision) sind 10-50× schneller.',
            '**Bildgröße:** Unterstützt bis zu etwa 1.000×1.000 Pixel. Größere Bilder werden herunterskaliert.',
            '**Einschränkungen:** Können GPT-4 Vision-Genauigkeit bei komplexen Szenen nicht erreichen. Kompromiss: Datenschutz vs. Qualität.',
          ],
        },
        commonMistakes: {
          title: 'Häufige Fehler',
          items: [
            '**Erwarten Sie die Genauigkeit von GPT-4 Vision.** Lokale Modelle sind 20-30% weniger genau. Verwenden Sie für spezifische Domänen, nicht für allgemeine Vision.',
            '**Bilder nicht vorbereiten.** Schneiden Sie Bilder auf den Fokusbereich zu. Entfernen Sie Rauschen. Bessere Eingabe = bessere Ausgabe.',
            '**7B-Modelle für komplexe Vision verwenden.** Kleine Modelle kämpfen mit subtilen Details. Verwenden Sie 11B+ für zuverlässige Vision.',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Weiterführende Literatur',
          items: [
            '[Best Local LLMs for Coding](/de/local-llms/best-local-llms-for-coding) -- Vision kann bei Code-Verständnis helfen.',
            '[Local RAG 2026](/de/local-llms/local-rag-2026) -- Kombinieren Sie Vision mit RAG für Dokumentenverarbeitung.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Quellen',
          items: [
            'Llama 3.2 Vision Model Card -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
    },
    fr: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: 'Modèles multimodaux locaux : vision, audio et traitement de texte',
      seoTitle: 'Modèles multimodaux locaux',
      intro: 'Les modèles multimodaux traitent images, texte et audio. Depuis avril 2026, Llama 3.2 Vision, Gemma 3 Vision et Qwen2-VL sont des modèles multimodaux pratiques pour déploiement local. Ils activent OCR de documents, analyse d\'images et question-réponse visuelle sans API cloud.',
      metaDescription: 'Modèles multimodaux locaux 2026 : vision, traitement d\'images, OCR, modèles audio. Guides LLaVA, Qwen-VL avec cas d\'usage.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**Les modèles multimodaux traitent images, texte et audio. Depuis avril 2026, Llama 3.2 Vision, Gemma 3 Vision et Qwen2-VL sont des modèles multimodaux pratiques pour déploiement local.**',
      audience: 'Débutants exécutant leur premier LLM local sur matériel grand public',
      readTime: '10 min de lecture',
      educationalLevel: 'Intermediate to Advanced',
      primaryTerm: 'modèles multimodaux',
      toc: [
        { label: 'Points clés', anchor: '#key-takeaways' },
        { label: 'Modèles multimodaux disponibles', anchor: '#models' },
        { label: 'Capacités de vision', anchor: '#vision' },
        { label: 'Installation et utilisation', anchor: '#setup' },
        { label: 'Cas d\'usage réels', anchor: '#use-cases' },
        { label: 'Performance et limitations', anchor: '#performance' },
        { label: 'Erreurs courantes', anchor: '#common-mistakes' },
        { label: 'Lectures complémentaires', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**Multimodal = texte + images (+ audio).** Traitez images nativement sans prétraitement OCR.',
            '**Meilleurs modèles (2026) :** Llama 3.2 Vision 11B, Qwen2-VL 7B, Gemma 3 Vision 9B.',
            '**Cas d\'usage :** OCR de documents, analyse d\'images, question-réponse visuelle, extraction de tableaux.',
            '**Vitesse :** 2-5 secondes par image (modèle 11B). Plus lent que texte seul, mais pratique.',
            'Depuis avril 2026, multimodal est mature pour cas d\'usage spécifiques, pas encore général.',
          ],
        },
        models: {
          title: 'Modèles multimodaux disponibles (avril 2026)',
          rows: [
            { 'Modèle': 'Llama 3.2 Vision 11B', 'Support d\'image': 'Oui', 'VRAM': '8 GB', 'Vitesse': '3-5 sec/image', 'Idéal pour': 'Vision générale' },
            { 'Modèle': 'Qwen2-VL 7B', 'Support d\'image': 'Oui', 'VRAM': '5 GB', 'Vitesse': '2-3 sec/image', 'Idéal pour': 'Vision rapide' },
            { 'Modèle': 'Gemma 3 Vision 9B', 'Support d\'image': 'Oui', 'VRAM': '6 GB', 'Vitesse': '3 sec/image', 'Idéal pour': 'Équilibré' },
            { 'Modèle': 'Llama 3.2 Vision 90B', 'Support d\'image': 'Oui', 'VRAM': '55 GB', 'Vitesse': '10+ sec/image', 'Idéal pour': 'Haute qualité' },
          ],
          columns: ['Modèle', 'Support d\'image', 'VRAM', 'Vitesse par image', 'Idéal pour'],
        },
        vision: {
          title: 'Capacités de vision',
          content: [
            'Les modèles multimodaux peuvent :',
          ],
          items: [
            '**Description d\'images :** Expliquez ce qui figure dans une image.',
            '**OCR (reconnaissance optique de caractères) :** Extrayez texte d\'images (carte de visite, scan de document).',
            '**Question-réponse visuelle :** Répondez à des questions sur images (« Quelle est la marque de la voiture ? »).',
            '**Extraction de tableaux :** Analysez tableaux d\'images en données structurées.',
            '**Analyse de diagrammes :** Interprétez visualisations de données.',
            '**Détection d\'objets :** Identifiez et localisez objets dans images.',
          ],
        },
        setup: {
          title: 'Installation et utilisation',
          content: 'Utilisation de Llama 3.2 Vision avec Ollama :',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: 'Cas d\'usage réels',
          items: [
            '**Traitement de documents :** Extrayez texte de PDFs numérisés sans service OCR externe.',
            '**Modération de contenu :** Signalez images inappropriées sans envoyer vers le cloud.',
            '**Accessibilité :** Décrivez images pour utilisateurs malvoyants.',
            '**Analyse de produits :** Analysez images produits en e-commerce (catégorie, état, défauts).',
            '**Recherche :** Analysez diagrammes et graphiques scientifiques.',
          ],
        },
        performance: {
          title: 'Performance et limitations',
          content: [
            '**Précision :** Bonne pour OCR de documents et description, mais pas parfaite pour analyse détaillée ou petits objets.',
            '**Vitesse :** 2-5 secondes par image. Modèles cloud (GPT-4 Vision) sont 10-50× plus rapides.',
            '**Taille d\'image :** Supporte jusqu\'à ~1000×1000 pixels. Images plus larges sont réduites.',
            '**Limitations :** Ne peut égaler précision GPT-4 Vision sur scènes complexes. Compromis : confidentialité vs. qualité.',
          ],
        },
        commonMistakes: {
          title: 'Erreurs courantes',
          items: [
            '**Attendre précision de GPT-4 Vision.** Modèles locaux sont 20-30% moins précis. Utilisez pour domaines spécifiques, pas vision générale.',
            '**Ne pas préparer images.** Recadrez images vers zone focale. Supprimez bruit. Meilleure entrée = meilleure sortie.',
            '**Utiliser modèles 7B pour vision complexe.** Petits modèles peinent sur détails subtils. Utilisez 11B+ pour vision fiable.',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Lectures complémentaires',
          items: [
            '[Meilleurs LLMs locaux pour coding](/fr/local-llms/best-local-llms-for-coding) -- Vision peut aider compréhension code.',
            '[RAG local 2026](/fr/local-llms/local-rag-2026) -- Combinez vision avec RAG pour traitement documents.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Sources',
          items: [
            'Llama 3.2 Vision Model Card -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
    },
    ja: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: 'マルチモーダルローカルLLM: ビジョン、オーディオ、テキスト処理',
      seoTitle: 'マルチモーダルローカルLLM',
      intro: 'マルチモーダルモデルは画像、テキスト、オーディオを処理します。2026年4月現在、Llama 3.2 Vision、Gemma 3 Vision、Qwen2-VLはローカル展開に実用的なマルチモーダルモデルです。クラウドAPIなしでドキュメントOCR、画像分析、視覚的質問応答が可能です。',
      metaDescription: 'マルチモーダルローカルLLM 2026: ビジョン、画像処理、OCR、オーディオモデル。LLaVA、Qwen-VLガイドと使用例。',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**マルチモーダルモデルは画像、テキスト、オーディオを処理します。2026年4月現在、Llama 3.2 Vision、Gemma 3 Vision、Qwen2-VLはローカル展開に実用的なマルチモーダルモデルです。**',
      audience: 'コンシューマーハードウェアで初めてのローカルLLMを実行する初心者',
      readTime: '10分の読了',
      educationalLevel: 'Intermediate to Advanced',
      primaryTerm: 'マルチモーダルモデル',
      toc: [
        { label: '重要なポイント', anchor: '#key-takeaways' },
        { label: '利用可能なマルチモーダルモデル', anchor: '#models' },
        { label: 'ビジョン機能', anchor: '#vision' },
        { label: 'セットアップと使用', anchor: '#setup' },
        { label: '実世界の使用例', anchor: '#use-cases' },
        { label: 'パフォーマンスと制限', anchor: '#performance' },
        { label: 'よくある間違い', anchor: '#common-mistakes' },
        { label: '関連記事', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**マルチモーダル = テキスト + 画像 (+ オーディオ)。** OCR前処理なしで画像をネイティブに処理します。',
            '**最適なモデル (2026年):** Llama 3.2 Vision 11B、Qwen2-VL 7B、Gemma 3 Vision 9B。',
            '**使用例:** ドキュメントOCR、画像分析、視覚的Q&A、表抽出。',
            '**速度:** 画像あたり2-5秒（11Bモデル）。テキストのみより遅いが実用的。',
            '2026年4月現在、マルチモーダルは特定の使用例に成熟していますが、まだ汎用的ではありません。',
          ],
        },
        models: {
          title: '利用可能なマルチモーダルモデル (2026年4月)',
          rows: [
            { 'モデル': 'Llama 3.2 Vision 11B', '画像サポート': 'はい', 'VRAM': '8 GB', '速度': '3-5秒/画像', '最適用途': '汎用ビジョン' },
            { 'モデル': 'Qwen2-VL 7B', '画像サポート': 'はい', 'VRAM': '5 GB', '速度': '2-3秒/画像', '最適用途': '高速ビジョン' },
            { 'モデル': 'Gemma 3 Vision 9B', '画像サポート': 'はい', 'VRAM': '6 GB', '速度': '3秒/画像', '最適用途': 'バランス型' },
            { 'モデル': 'Llama 3.2 Vision 90B', '画像サポート': 'はい', 'VRAM': '55 GB', '速度': '10+秒/画像', '最適用途': '高品質' },
          ],
          columns: ['モデル', '画像サポート', 'VRAM', '画像あたりの速度', '最適用途'],
        },
        vision: {
          title: 'ビジョン機能',
          content: [
            'マルチモーダルモデルは以下が可能です:',
          ],
          items: [
            '**画像説明:** 画像に何が含まれているかを説明します。',
            '**OCR (光学文字認識):** 画像からテキストを抽出 (名刺、スキャンドキュメント)。',
            '**視覚的Q&A:** 画像についての質問に回答 (「車のブランドは何ですか？」)。',
            '**表抽出:** 画像から表を構造化データに変換。',
            '**グラフ分析:** データビジュアライゼーションを解釈。',
            '**物体検出:** 画像内の物体を識別して配置。',
          ],
        },
        setup: {
          title: 'セットアップと使用',
          content: 'Ollama でLlama 3.2 Visionを使用:',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: '実世界の使用例',
          items: [
            '**ドキュメント処理:** 外部OCRサービスなしでスキャンされたPDFからテキストを抽出。',
            '**コンテンツモデレーション:** クラウドに送信せず不適切な画像にフラグを立てます。',
            '**アクセシビリティ:** 視覚障害者ユーザーのために画像を説明。',
            '**製品分析:** eコマースで製品画像を分析 (カテゴリー、状態、欠陥)。',
            '**研究:** 科学図表やダイアグラムを分析。',
          ],
        },
        performance: {
          title: 'パフォーマンスと制限',
          content: [
            '**精度:** ドキュメントOCRと説明には適していますが、詳細な分析や小さな物体には完全ではありません。',
            '**速度:** 画像あたり2-5秒。クラウドモデル (GPT-4 Vision) は10-50倍高速です。',
            '**画像サイズ:** 最大 ~1000×1000ピクセルをサポート。より大きな画像はダウンサンプリングされます。',
            '**制限:** 複雑なシーンではGPT-4 Vision精度と同等にはできません。トレードオフ: プライバシー対品質。',
          ],
        },
        commonMistakes: {
          title: 'よくある間違い',
          items: [
            '**GPT-4 Visionの精度を期待する。** ローカルモデルは20-30%精度が低い。汎用ビジョンではなく、特定の領域に使用します。',
            '**画像を準備しない。** 画像をフォーカス領域にトリミングします。ノイズを除去します。入力が良い = 出力が良い。',
            '**複雑なビジョンに7Bモデルを使用する。** 小さいモデルは微細な詳細で苦しみます。信頼できるビジョンには11B+を使用します。',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: '関連記事',
          items: [
            '[コーディング用最適なローカルLLM](/ja/local-llms/best-local-llms-for-coding) -- ビジョンはコード理解に役立ちます。',
            '[ローカルRAG 2026](/ja/local-llms/local-rag-2026) -- ビジョンをRAGと組み合わせてドキュメント処理。',
          ],
        },
        sources: {
          id: 'sources',
          title: 'ソース',
          items: [
            'Llama 3.2 Vision Model Card -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
    },
    zh: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: '多模态本地LLM：视觉、音频和文本处理',
      seoTitle: '多模态本地LLM',
      intro: '多模态模型处理图像、文本和音频。截至2026年4月，Llama 3.2 Vision、Gemma 3 Vision和Qwen2-VL是实用的本地部署多模态模型。它们支持文档OCR、图像分析和视觉问答，无需云API。',
      metaDescription: '多模态本地LLM 2026: 视觉、图像处理、OCR、音频模型。LLaVA、Qwen-VL指南和用例。',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**多模态模型处理图像、文本和音频。截至2026年4月，Llama 3.2 Vision、Gemma 3 Vision和Qwen2-VL是实用的本地部署多模态模型。**',
      audience: '在消费级硬件上运行首个本地LLM的初学者',
      readTime: '10分钟阅读',
      educationalLevel: 'Intermediate to Advanced',
      primaryTerm: '多模态模型',
      toc: [
        { label: '关键要点', anchor: '#key-takeaways' },
        { label: '可用的多模态模型', anchor: '#models' },
        { label: '视觉能力', anchor: '#vision' },
        { label: '设置和使用', anchor: '#setup' },
        { label: '真实世界用例', anchor: '#use-cases' },
        { label: '性能和限制', anchor: '#performance' },
        { label: '常见错误', anchor: '#common-mistakes' },
        { label: '相关阅读', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**多模态 = 文本 + 图像 (+ 音频)。** 无需OCR预处理即可本机处理图像。',
            '**最佳模型 (2026年)：** Llama 3.2 Vision 11B、Qwen2-VL 7B、Gemma 3 Vision 9B。',
            '**用例：** 文档OCR、图像分析、视觉问答、表格提取。',
            '**速度：** 每张图像2-5秒（11B模型）。比纯文本慢，但实用。',
            '截至2026年4月，多模态对特定用例已成熟，但尚未通用。',
          ],
        },
        models: {
          title: '可用的多模态模型 (2026年4月)',
          rows: [
            { '模型': 'Llama 3.2 Vision 11B', '图像支持': '是', 'VRAM': '8 GB', '速度': '3-5秒/图像', '最适用': '通用视觉' },
            { '模型': 'Qwen2-VL 7B', '图像支持': '是', 'VRAM': '5 GB', '速度': '2-3秒/图像', '最适用': '快速视觉' },
            { '模型': 'Gemma 3 Vision 9B', '图像支持': '是', 'VRAM': '6 GB', '速度': '3秒/图像', '最适用': '均衡' },
            { '模型': 'Llama 3.2 Vision 90B', '图像支持': '是', 'VRAM': '55 GB', '速度': '10+秒/图像', '最适用': '高质量' },
          ],
          columns: ['模型', '图像支持', 'VRAM', '每张图像速度', '最适用'],
        },
        vision: {
          title: '视觉能力',
          content: [
            '多模态模型可以：',
          ],
          items: [
            '**图像描述：** 解释图像中的内容。',
            '**OCR (光学字符识别)：** 从图像提取文本（名片、文档扫描）。',
            '**视觉问答：** 回答有关图像的问题（"这辆车的品牌是什么？"）。',
            '**表格提取：** 将图像中的表格解析为结构化数据。',
            '**图表分析：** 解读数据可视化。',
            '**物体检测：** 识别和定位图像中的物体。',
          ],
        },
        setup: {
          title: '设置和使用',
          content: '使用Ollama运行Llama 3.2 Vision：',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: '真实世界用例',
          items: [
            '**文档处理：** 无需外部OCR服务从扫描PDF提取文本。',
            '**内容审核：** 标记不适当的图像，无需发送到云端。',
            '**无障碍：** 为视障用户描述图像。',
            '**产品分析：** 分析电商产品图像（类别、状态、缺陷）。',
            '**研究：** 分析科学图表和图解。',
          ],
        },
        performance: {
          title: '性能和限制',
          content: [
            '**准确性：** 适合文档OCR和描述，但不完美用于详细分析或小物体。',
            '**速度：** 每张图像2-5秒。云模型（GPT-4 Vision）快10-50倍。',
            '**图像大小：** 支持~1000×1000像素。更大的图像将被缩小采样。',
            '**限制：** 复杂场景下无法匹配GPT-4 Vision准确性。权衡：隐私对质量。',
          ],
        },
        commonMistakes: {
          title: '常见错误',
          items: [
            '**期望GPT-4 Vision的准确性。** 本地模型准确性低20-30%。用于特定领域，不是通用视觉。',
            '**不准备图像。** 将图像裁剪到焦点区域。去除噪声。更好的输入 = 更好的输出。',
            '**使用7B模型处理复杂视觉。** 小模型在微妙细节上困难重重。使用11B+获得可靠视觉。',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: '相关阅读',
          items: [
            '[编码最佳本地LLM](/zh/local-llms/best-local-llms-for-coding) -- 视觉可以帮助代码理解。',
            '[本地RAG 2026](/zh/local-llms/local-rag-2026) -- 将视觉与RAG结合进行文档处理。',
          ],
        },
        sources: {
          id: 'sources',
          title: '来源',
          items: [
            'Llama 3.2 Vision Model Card -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
    },
    pt: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: 'LLMs locais multimodais: visão, áudio e processamento de texto',
      seoTitle: 'LLMs locais multimodais',
      intro: 'Os modelos multimodais processam imagens, texto e áudio. A partir de abril de 2026, Llama 3.2 Vision, Gemma 3 Vision e Qwen2-VL são modelos multimodais práticos para implantação local. Eles permitem OCR de documentos, análise de imagens e perguntas e respostas visuais sem APIs de nuvem.',
      metaDescription: 'LLMs locais multimodais 2026: visão, processamento de imagens, OCR, modelos de áudio. Guias de LLaVA e Qwen-VL com casos de uso.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**Os modelos multimodais processam imagens, texto e áudio. A partir de abril de 2026, Llama 3.2 Vision, Gemma 3 Vision e Qwen2-VL são modelos multimodais práticos para implantação local.**',
      audience: 'Iniciantes rodando seu primeiro LLM local em hardware de consumo',
      readTime: '10 min de leitura',
      educationalLevel: 'Intermediate to Advanced',
      primaryTerm: 'modelos multimodais',
      toc: [
        { label: 'Pontos principais', anchor: '#key-takeaways' },
        { label: 'Modelos multimodais disponíveis', anchor: '#models' },
        { label: 'Capacidades de visão', anchor: '#vision' },
        { label: 'Configuração e uso', anchor: '#setup' },
        { label: 'Casos de uso reais', anchor: '#use-cases' },
        { label: 'Desempenho e limitações', anchor: '#performance' },
        { label: 'Erros comuns', anchor: '#common-mistakes' },
        { label: 'Leituras relacionadas', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            '**Multimodal = texto + imagens (+ áudio).** Processa imagens de forma nativa, sem pré-processamento de OCR.',
            '**Melhores modelos (2026):** Llama 3.2 Vision 11B, Qwen2-VL 7B, Gemma 3 Vision 9B.',
            '**Casos de uso:** OCR de documentos, análise de imagens, perguntas e respostas visuais, extração de tabelas.',
            '**Velocidade:** 2-5 segundos por imagem (modelo 11B). Mais lento que apenas texto, mas prático.',
            'A partir de abril de 2026, o multimodal está maduro para casos de uso específicos, mas ainda não para uso geral.',
          ],
        },
        models: {
          title: 'Modelos multimodais disponíveis (abril de 2026)',
          rows: [
            { 'Modelo': 'Llama 3.2 Vision 11B', 'Suporte a imagem': 'Sim', 'VRAM': '8 GB', 'Velocidade': '3-5 seg/imagem', 'Melhor para': 'Visão geral' },
            { 'Modelo': 'Qwen2-VL 7B', 'Suporte a imagem': 'Sim', 'VRAM': '5 GB', 'Velocidade': '2-3 seg/imagem', 'Melhor para': 'Visão rápida' },
            { 'Modelo': 'Gemma 3 Vision 9B', 'Suporte a imagem': 'Sim', 'VRAM': '6 GB', 'Velocidade': '3 seg/imagem', 'Melhor para': 'Equilibrado' },
            { 'Modelo': 'Llama 3.2 Vision 90B', 'Suporte a imagem': 'Sim', 'VRAM': '55 GB', 'Velocidade': '10+ seg/imagem', 'Melhor para': 'Alta qualidade' },
          ],
          columns: ['Modelo', 'Suporte a imagem', 'VRAM', 'Velocidade por imagem', 'Melhor para'],
        },
        vision: {
          title: 'Capacidades de visão',
          content: [
            'Os modelos multimodais podem:',
          ],
          items: [
            '**Descrição de imagens:** Explica o que há em uma imagem.',
            '**OCR (Reconhecimento óptico de caracteres):** Extrai texto de imagens (cartão de visita, digitalização de documento).',
            '**Perguntas e respostas visuais:** Responde a perguntas sobre imagens ("Qual é a marca do carro?").',
            '**Extração de tabelas:** Converte tabelas de imagens em dados estruturados.',
            '**Análise de gráficos:** Interpreta visualizações de dados.',
            '**Detecção de objetos:** Identifica e localiza objetos em imagens.',
          ],
        },
        setup: {
          title: 'Configuração e uso',
          content: 'Usando o Llama 3.2 Vision com o Ollama:',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: 'Casos de uso reais',
          items: [
            '**Processamento de documentos:** Extrai texto de PDFs digitalizados sem serviço de OCR externo.',
            '**Moderação de conteúdo:** Sinaliza imagens inadequadas sem enviá-las para a nuvem.',
            '**Acessibilidade:** Descreve imagens para usuários com deficiência visual.',
            '**Análise de produtos:** Analisa imagens de produtos em e-commerce (categoria, estado, defeitos).',
            '**Pesquisa:** Analisa gráficos e diagramas científicos.',
          ],
        },
        performance: {
          title: 'Desempenho e limitações',
          content: [
            '**Precisão:** Boa para OCR de documentos e descrição, mas não perfeita para análise detalhada ou objetos pequenos.',
            '**Velocidade:** 2-5 segundos por imagem. Os modelos de nuvem (GPT-4 Vision) são 10-50× mais rápidos.',
            '**Tamanho da imagem:** Suporta até ~1000×1000 pixels. Imagens maiores são reduzidas por amostragem.',
            '**Limitações:** Não consegue igualar a precisão do GPT-4 Vision em cenas complexas. Compromisso: privacidade vs. qualidade.',
          ],
        },
        commonMistakes: {
          title: 'Erros comuns',
          items: [
            '**Esperar a precisão do GPT-4 Vision.** Os modelos locais são 20-30% menos precisos. Use-os para domínios específicos, não para visão geral.',
            '**Não preparar as imagens.** Recorte as imagens para a área de foco. Remova o ruído. Melhor entrada = melhor saída.',
            '**Usar modelos 7B para visão complexa.** Os modelos pequenos têm dificuldade com detalhes sutis. Use 11B+ para visão confiável.',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Leituras relacionadas',
          items: [
            '[Melhores LLMs locais para programação](/pt/local-llms/best-local-llms-for-coding) -- A visão pode ajudar a entender o código.',
            '[RAG local 2026](/pt/local-llms/local-rag-2026) -- Combine visão com RAG para o processamento de documentos.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Fontes',
          items: [
            'Llama 3.2 Vision Model Card -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'LLMs locais multimodais: visão, áudio e processamento de texto',
        description: 'LLMs locais multimodais 2026: visão, OCR, processamento de imagens. LLaVA, Qwen-VL.',
        url: 'https://www.promptquorum.com/pt/local-llms/multimodal-local-llms',
        inLanguage: 'pt-BR',
        datePublished: '2026-04-04',
        dateModified: '2026-04-04',
        author: { '@type': 'Person', name: 'Hans Kuepper', sameAs: 'https://www.linkedin.com/in/hanskuepper/' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        'proficiencyLevel': 'Intermediate to Advanced',
      },
    },
  ko: {
      freshness_tier: 'semi_annual',
      theme: 'Advanced Techniques',
      title: '멀티모달 로컬 LLM: 비전, 오디오, 텍스트 처리',
      seoTitle: '멀티모달 로컬 LLM',
      intro: '멀티모달 모델은 이미지, 텍스트, 오디오를 처리합니다. 2026년 4월 기준으로 Llama 3.2 Vision, Gemma 3 Vision, Qwen2-VL은 로컬 배포에 실용적인 멀티모달 모델입니다. 이 모델들을 사용하면 클라우드 API 없이도 문서 OCR, 이미지 분석, 시각적 질의응답이 가능합니다.',
      metaDescription: '멀티모달 로컬 LLM 2026: 비전, 이미지 처리, OCR, 오디오 모델. LLaVA, Qwen-VL 가이드 및 활용 사례.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '멀티모달 모델은 이미지, 텍스트, 오디오를 처리합니다. 2026년 4월 기준으로 Llama 3.2 Vision, Gemma 3 Vision, Qwen2-VL은 로컬 배포에 실용적인 멀티모달 모델입니다.',
      audience: '소비자용 하드웨어에서 처음 로컬 LLM을 실행하는 초보자',
      readTime: '10분 분량',
      educationalLevel: '중급~고급',
      primaryTerm: '멀티모달 모델',
      toc: [
        { label: '핵심 요점', anchor: '#key-takeaways' },
        { label: '사용 가능한 멀티모달 모델', anchor: '#models' },
        { label: '비전 기능', anchor: '#vision' },
        { label: '설정 및 사용법', anchor: '#setup' },
        { label: '실제 활용 사례', anchor: '#use-cases' },
        { label: '성능 및 한계', anchor: '#performance' },
        { label: '자주 발생하는 실수', anchor: '#common-mistakes' },
        { label: '관련 자료', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            '**멀티모달 = 텍스트 + 이미지 (+ 오디오).** OCR 전처리 없이 이미지를 직접 처리합니다.',
            '**최고의 모델 (2026):** Llama 3.2 Vision 11B, Qwen2-VL 7B, Gemma 3 Vision 9B.',
            '**활용 사례:** 문서 OCR, 이미지 분석, 시각적 Q&A, 표 추출.',
            '**속도:** 이미지당 2~5초 (11B 모델). 텍스트 전용보다 느리지만 실용적입니다.',
            '2026년 4월 기준으로 멀티모달은 특정 사용 사례에서 성숙 단계에 있으며, 아직 범용적이지는 않습니다.',
          ],
        },
        models: {
          title: '사용 가능한 멀티모달 모델 (2026년 4월)',
          rows: [
            { 'Model': 'Llama 3.2 Vision 11B', 'Image Support': '지원', 'VRAM': '8 GB', 'Speed': '이미지당 3~5초', 'Best For': '일반 비전' },
            { 'Model': 'Qwen2-VL 7B', 'Image Support': '지원', 'VRAM': '5 GB', 'Speed': '이미지당 2~3초', 'Best For': '고속 비전' },
            { 'Model': 'Gemma 3 Vision 9B', 'Image Support': '지원', 'VRAM': '6 GB', 'Speed': '이미지당 3초', 'Best For': '균형형' },
            { 'Model': 'Llama 3.2 Vision 90B', 'Image Support': '지원', 'VRAM': '55 GB', 'Speed': '이미지당 10초 이상', 'Best For': '고품질' },
          ],
          columns: ['Model', 'Image Support', 'VRAM', 'Speed per Image', 'Best For'],
        },
        vision: {
          title: '비전 기능',
          content: [
            '멀티모달 모델은 다음을 수행할 수 있습니다:',
          ],
          items: [
            '**이미지 설명:** 이미지에 무엇이 있는지 설명합니다.',
            '**OCR (광학 문자 인식):** 이미지에서 텍스트를 추출합니다 (명함, 문서 스캔 등).',
            '**시각적 Q&A:** 이미지에 관한 질문에 답합니다 ("이 차의 브랜드는 무엇입니까?").',
            '**표 추출:** 이미지에서 표를 파싱하여 구조화된 데이터로 변환합니다.',
            '**차트 분석:** 데이터 시각화 자료를 해석합니다.',
            '**객체 탐지:** 이미지에서 객체를 식별하고 위치를 파악합니다.',
          ],
        },
        setup: {
          title: '설정 및 사용법',
          content: 'Ollama와 함께 Llama 3.2 Vision을 사용하는 방법:',
          codeBlock: '# Pull the model\nollama pull llama3.2-vision:11b\n\n# Use it\nfrom ollama import Client\nclient = Client()\n\nwith open("image.jpg", "rb") as f:\n    image_data = f.read()\n\nresponse = client.generate(\n  model="llama3.2-vision:11b",\n  prompt="Describe this image",\n  images=[image_data]  # Pass image data\n)\n\nprint(response["response"])',
          codeLanguage: 'python',
        },
        useCases: {
          title: '실제 활용 사례',
          items: [
            '**문서 처리:** 외부 OCR 서비스 없이 스캔된 PDF에서 텍스트를 추출합니다.',
            '**콘텐츠 검수:** 클라우드에 전송하지 않고 부적절한 이미지를 필터링합니다.',
            '**접근성:** 시각 장애인을 위해 이미지를 설명합니다.',
            '**제품 분석:** 전자 상거래에서 제품 이미지를 분석합니다 (카테고리, 상태, 결함).',
            '**연구:** 과학적 차트 및 다이어그램을 분석합니다.',
          ],
        },
        performance: {
          title: '성능 및 한계',
          content: [
            '**정확도:** 문서 OCR 및 설명에는 적합하지만, 세부 분석이나 소형 객체에서는 완벽하지 않습니다.',
            '**속도:** 이미지당 2~5초. 클라우드 모델(GPT-4 Vision)은 10~50배 더 빠릅니다.',
            '**이미지 크기:** 최대 약 1000×1000픽셀을 지원합니다. 더 큰 이미지는 다운샘플링됩니다.',
            '**한계:** 복잡한 장면에서 GPT-4 Vision의 정확도를 따라가지 못합니다. 개인 정보 보호와 품질 간의 트레이드오프가 있습니다.',
          ],
        },
        commonMistakes: {
          title: '자주 발생하는 실수',
          items: [
            '**GPT-4 Vision 수준의 정확도를 기대하는 것.** 로컬 모델은 20~30% 정확도가 낮습니다. 범용 비전이 아닌 특정 도메인에 사용하십시오.',
            '**이미지를 준비하지 않는 것.** 초점 영역에 맞게 이미지를 자르십시오. 노이즈를 제거하십시오. 좋은 입력일수록 좋은 출력이 나옵니다.',
            '**복잡한 비전 작업에 7B 모델을 사용하는 것.** 소형 모델은 세부적인 디테일 처리에 어려움을 겪습니다. 안정적인 비전 작업을 위해서는 11B 이상의 모델을 사용하십시오.',
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: '관련 자료',
          items: [
            '[코딩에 최적화된 로컬 LLM](/local-llms/best-local-llms-for-coding) -- 비전은 코드 이해에 도움이 될 수 있습니다.',
            '[로컬 RAG 2026](/local-llms/local-rag-2026) -- 문서 처리를 위해 비전과 RAG를 결합하십시오.',
          ],
        },
        sources: {
          id: 'sources',
          title: '출처',
          items: [
            'Llama 3.2 Vision Model Card -- huggingface.co/meta-llama/Llama-3.2-11B-Vision',
            'Qwen2-VL -- github.com/QwenLM/Qwen2-VL',
          ],
        },
      },
    },
  };
