// Auto-generated from src/lib/local-llms/content.ts
// Slug: quantization-levels-comparison
// Generated: 2026-05-03T11:33:08.370Z

import type { Language } from "@/lib/blog/blogContent";

import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
    en: {
      freshness_tier: 'semi_annual',
      theme: 'Models by Use Case',
      title: 'Q4 vs Q5 vs Q8: Which Quantization Level Should You Use?',
      seoTitle: 'Q4 vs Q5 vs Q8: Best LLM Quantization for Speed, RAM & Quality (2026)',
      intro: '**Q4 (4-bit) is the sweet spot: 87% VRAM savings with imperceptible quality loss.** As of April 2026, Q5 is pointless (only 5% better quality, same VRAM cost as Q4), and Q8 is for perfectionists with excess VRAM. FP32 (full precision) is never necessary for inference on consumer hardware.',
      metaDescription: 'Full GGUF quantization comparison: Q2, Q3, Q4, Q5, Q6, Q8. Learn trade-offs in accuracy, latency, and memory for optimal local LLM performance.',
      publishDate: '2026-04-05',
      dateModified: '2026-04-18',
      leadAnswerBlock: '**Q4 (4-bit) is the sweet spot: 87% VRAM savings with imperceptible quality loss. As of April 2026, Q5 is pointless (only 5% better quality, same VRAM cost as Q4), and Q8 is for perfectionists with excess VRAM.**',
      audience: 'Developers familiar with Ollama or LM Studio optimizing local LLM workflows',
      readTime: '8 min',
      educationalLevel: 'Intermediate',
      primaryTerm: 'Quantization',
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'Q4 vs Q5 vs Q8: Which Quantization Level Should You Use?',
        description: 'Full GGUF quantization comparison: Q2, Q3, Q4, Q5, Q6, Q8. Learn trade-offs in accuracy, latency, and memory for optimal local LLM performance.',
        datePublished: '2026-04-05',
        dateModified: '2026-04-18',
        url: 'https://www.promptquorum.com/local-llms/quantization-levels-comparison',
        inLanguage: 'en',
        proficiencyLevel: 'Intermediate',
        author: { '@type': 'Person', 'name': 'Hans Kuepper' },
        publisher: { '@type': 'Organization', 'name': 'PromptQuorum', 'url': 'https://www.promptquorum.com' },
        about: [
          { '@type': 'Thing', 'name': 'LLM Quantization' },
          { '@type': 'Thing', 'name': 'VRAM Optimization' },
          { '@type': 'Thing', 'name': 'Ollama' },
          { '@type': 'Thing', 'name': 'GGUF Format' },
        ],
        speakable: { '@type': 'SpeakableSpecification', 'cssSelector': ['.article-intro', '.key-takeaways'] },
      },
      gammaEmbedUrl: '/presentations/quantization-levels-comparison-static.html',
      gammaDescription: 'The slide deck below covers: why LLM quantization compresses models (reducing precision from 16-bit to Q4/Q8), VRAM savings across Q2–Q8 levels (70GB for Q4 vs 280GB for FP32), quality loss benchmarks (Q4 retains 99% accuracy, 1.2% loss), and when to use each level by hardware (8GB → Q3/Q4, 16GB → Q4_K_M, 32GB+ → Q5/Q8). Download the PDF as a quantization levels reference card.',
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'en',
        mainEntity: [
          { '@type': 'Question', name: 'What is LLM quantization?', acceptedAnswer: { '@type': 'Answer', text: 'Quantization compresses a model by reducing numerical precision, lowering memory usage and increasing speed.' } },
          { '@type': 'Question', name: 'What is the best quantization level?', acceptedAnswer: { '@type': 'Answer', text: 'Q4_K_M is the best default for most users, balancing performance and quality.' } },
          { '@type': 'Question', name: 'Does quantization reduce accuracy?', acceptedAnswer: { '@type': 'Answer', text: 'Yes, but Q4–Q5 retain most model quality while significantly reducing memory requirements.' } },
          { '@type': 'Question', name: 'Is Q8 worth it?', acceptedAnswer: { '@type': 'Answer', text: 'Only if you need maximum accuracy and have enough RAM. Most users will not benefit from Q8.' } },
          { '@type': 'Question', name: 'Should I use Q4 or Q8 for coding?', acceptedAnswer: { '@type': 'Answer', text: 'Q4. Speed is identical, quality difference is 1%, which is imperceptible for code generation.' } },
          { '@type': 'Question', name: 'Can I use Q3 if I\'m tight on VRAM?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. 3% quality loss is acceptable for chat/creative writing. Unacceptable for reasoning/math.' } },
          { '@type': 'Question', name: 'Is there a Q6 or Q7?', acceptedAnswer: { '@type': 'Answer', text: 'No standard. Some projects implement custom levels, but Q4/Q5/Q8 are the industry standard.' } },
          { '@type': 'Question', name: 'Which quantization is fastest?', acceptedAnswer: { '@type': 'Answer', text: 'All identical speed (memory-bound). Q2 is slightly faster due to less memory transfer, but difference is <5%.' } },
          { '@type': 'Question', name: 'Can I dequantize Q4 back to FP32?', acceptedAnswer: { '@type': 'Answer', text: 'No, data is lost. Q4 → FP32 interpolation doesn\'t restore original. Quantization is one-way.' } },
          { '@type': 'Question', name: 'Should I quantize my fine-tuned model?', acceptedAnswer: { '@type': 'Answer', text: 'Yes, after training. Quantize the trained weights to Q4 for deployment.' } },
          { '@type': 'Question', name: 'What does GGUF Q4_K_M mean?', acceptedAnswer: { '@type': 'Answer', text: 'Q4_K_M is a refined Q4 variant using K-quants (mixed precision). The K algorithm preserves more accuracy on attention layers. Q4_K_M is the recommended HuggingFace download — effectively Q4 with ~0.3% better accuracy at the same VRAM cost.' } },
          { '@type': 'Question', name: 'Does quantization affect context length?', acceptedAnswer: { '@type': 'Answer', text: 'No. Quantization compresses model weights, not the context window. A Q4 model has the same maximum context length as its FP32 version. Context memory (KV cache) is a separate concern.' } },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        name: 'LLM Quantization Levels: Q4 vs Q5 vs Q8 Comparison',
        description: 'Comparison of LLM quantization levels by VRAM usage, quality loss, speed, and recommended use cases.',
        inLanguage: 'en',
        numberOfItems: 6,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'FP32 (32-bit full precision)', description: '280GB VRAM for Llama 3 70B. Baseline quality. Identical speed. Never practical for consumer hardware.' },
          { '@type': 'ListItem', position: 2, name: 'Q8 (8-bit quantization)', description: '140GB VRAM for Llama 3 70B. -0.05% quality loss vs FP32. Identical speed. For 32GB+ VRAM with accuracy-critical tasks.' },
          { '@type': 'ListItem', position: 3, name: 'Q5 (5-bit quantization)', description: '88GB VRAM for Llama 3 70B. -0.5% quality loss. Dead zone: Q4 + slightly larger model gives better results at the same VRAM.' },
          { '@type': 'ListItem', position: 4, name: 'Q4 (4-bit quantization)', description: '70GB VRAM for Llama 3 70B. -1.2% quality loss on MMLU. Industry standard. Fits RTX 4090. Recommended default for all use cases.' },
          { '@type': 'ListItem', position: 5, name: 'Q3 (3-bit quantization)', description: '53GB VRAM for Llama 3 70B. -3.7% quality loss. Use only as VRAM budget squeeze when Q4 causes out-of-memory errors.' },
          { '@type': 'ListItem', position: 6, name: 'Q2 (2-bit quantization)', description: '35GB VRAM for Llama 3 70B. -10% quality loss. Last resort. Quality degradation is noticeable on most tasks.' },
        ],
      },
      toc: [
        { label: 'What is LLM Quantization?', anchor: '#featured-snippet' },
        { label: 'TLDR', anchor: '#tldr' },
        { label: 'Quantization Levels Compared: Q2 Through Q8', anchor: '#levels' },
        { label: 'Best Quantization Level by Use Case', anchor: '#best-choice' },
        { label: 'VRAM & Performance Impact', anchor: '#vram' },
        { label: 'Quality Loss: Objective Benchmarks', anchor: '#quality' },
        { label: 'When to Use Each Level', anchor: '#when' },
        { label: 'Q4 Deep Dive: Why It\'s the Standard', anchor: '#q4' },
        { label: 'Common Misconceptions', anchor: '#mistakes' },
        { label: 'FAQ', anchor: '#faq' },
      ],
      sections: {
        definition: {
          id: 'featured-snippet',
          title: 'What is LLM Quantization?',
          content: 'LLM quantization reduces model size by compressing weights from 16-bit to lower precision formats like Q4 or Q8.',
          items: [
            'Q2–Q3 → fastest, lowest quality',
            'Q4 → best balance (recommended)',
            'Q5–Q6 → higher quality, more RAM',
            'Q8 → near full precision, slowest',
          ],
          note: 'For most users: Q4_K_M is the best default.',
        },
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**Q4 (4-bit):** 87.5% VRAM savings, ~1% quality loss. Use this for everything.',
            '**Q5 (5-bit):** 84% VRAM savings, ~0.5% quality loss. Never necessary; Q4 + Q8 bracket Q5.',
            '**Q8 (8-bit):** 50% VRAM savings, <0.1% quality loss. For perfectionists with excess VRAM.',
            '**FP32 (32-bit):** Full precision, 0% loss, 0% savings. Impractical; skip it.',
            '**Speed:** All quantizations run at identical token/sec (memory-bound, not compute-bound).',
            '**VRAM usage (70B Llama model):** FP32=280GB, Q8=140GB, Q5=88GB, Q4=70GB.',
            '**Recommendation:** Use Q4 for 7B-70B. Use Q8 only if you have 32GB+ VRAM and need pristine quality.',
            '**No one uses Q5 because Q4 + small upgrade = better than Q5 + same hardware.**',
          ],
        },
        quickFacts: {
          id: 'quick-facts',
          title: 'Quick Facts',
          items: [
            '**Q4 VRAM savings:** 87.5% vs FP32 (70GB for Llama 3 70B)',
            '**Q4 quality loss:** <1.2% on MMLU benchmark',
            '**Q8 VRAM savings:** 50% vs FP32 (140GB for Llama 3 70B)',
            '**Speed difference:** 0% — all quantizations run at identical tokens/sec',
            '**Q5 verdict:** Dead zone — Q4 + larger model = better result at same VRAM',
          ],
        },
        'levels': {
          title: 'Quantization Levels Compared: Q2 Through Q8',
          rows: [
            { 'Quantization': 'Q2', 'RAM Usage': 'Very Low', 'Speed': 'Very Fast', 'Quality': 'Poor', 'Best For': 'Experiments' },
            { 'Quantization': 'Q3', 'RAM Usage': 'Low', 'Speed': 'Fast', 'Quality': 'Low', 'Best For': 'Small devices' },
            { 'Quantization': 'Q4', 'RAM Usage': 'Medium', 'Speed': 'Fast', 'Quality': 'Good', 'Best For': 'Most users' },
            { 'Quantization': 'Q5', 'RAM Usage': 'Medium+', 'Speed': 'Medium', 'Quality': 'Very Good', 'Best For': 'Coding' },
            { 'Quantization': 'Q6', 'RAM Usage': 'High', 'Speed': 'Slower', 'Quality': 'Excellent', 'Best For': 'Accuracy focus' },
            { 'Quantization': 'Q8', 'RAM Usage': 'Very High', 'Speed': 'Slow', 'Quality': 'Near FP16', 'Best For': 'Benchmarking' },
          ],
          columns: ['Quantization', 'RAM Usage', 'Speed', 'Quality', 'Best For'],
          image: '/images/quantization-levels-comparison-vram-savings-en.svg',
          imageCaption: 'VRAM savings by quantization level: FP32 = 280GB, Q8 = 140GB (50% savings), Q4 = 70GB (75% savings), Q3 = 53GB (81% savings). Q4 is the sweet spot for most users.',
        },
        'choices': {
          id: 'best-choice',
          title: 'Best Quantization Level by Use Case',
          items: [
            '**8GB RAM:** Q3 or Q4 (small 7B models only)',
            '**16GB RAM:** Q4_K_M (recommended for most laptops)',
            '**32GB RAM:** Q5, Q6, or Q8 (larger models, higher quality)',
            '**Maximum accuracy:** Q8 (when VRAM is not a constraint)',
          ],
          image: '/images/quantization-levels-comparison-hardware-guide-en.svg',
          imageCaption: 'Hardware selection guide: 8GB RAM → Q3/Q4 (7B models), 16GB → Q4_K_M (recommended), 32GB+ → Q5/Q6/Q8 (larger models, higher quality), 64GB+ → Q8 or FP32 (research/medical).',
        },
        'vram': {
          title: 'How Does Quantization Affect VRAM and Speed?',
          content: [
            '**VRAM calculation:** Model size (GB) × quantization factor.',
            'Llama 3 70B:',
            '- FP32: 70B × 4 bytes = 280GB (impractical)',
            '- Q8: 70B × 1 byte = 140GB (needs 140GB VRAM)',
            '- Q4: 70B × 0.5 bytes = 70GB (fits RTX 4090 + some overhead)',
            '**Speed:** All quantizations are memory-bound (waiting for DRAM), not compute-bound.',
            'Tokens/sec is identical across Q2-FP32 on same hardware.',
            '**VRAM bandwidth, not computation, is the bottleneck.** Quantization saves VRAM, not time.',
          ],
        },
        'quality': {
          title: 'Quality Loss by Level: MMLU Benchmark Results',
          content: 'Measured on MMLU benchmark (general knowledge, 57 tasks):',
          items: [
            'Llama 3 70B FP32 baseline: 85.2% accuracy.',
            'Llama 3 70B Q8: 85.1% accuracy (-0.1% loss).',
            'Llama 3 70B Q5: 84.7% accuracy (-0.5% loss).',
            'Llama 3 70B Q4: 84.0% accuracy (-1.2% loss).',
            'Llama 3 70B Q3: 81.5% accuracy (-3.7% loss).',
            'Real-world impact: Q4 vs Q8 = 1-2% fewer correct answers out of 100 questions.',
            'For chat/writing: imperceptible difference. For STEM problems: Q8 safer.',
          ],
          image: '/images/quantization-levels-comparison-quality-loss-en.svg',
          imageCaption: 'Quality loss benchmarks: Q8 = -0.1% loss, Q5 = -0.5% loss, Q4 = -1.2% loss, Q3 = -3.7% loss on MMLU. Q4 quality loss is imperceptible for most tasks.',
        },
        'when': {
          title: 'When to Use Each Level?',
          content: [
            '**Q4:** Default. Use for all models. Sweet spot of compression + quality.',
            '**Q5:** Never. Wasteful. If you need Q5 quality, use Q4 with slightly larger model. If you have Q5\'s VRAM (88GB), use Q4 on 70B instead.',
            '**Q8:** Only if you have 32GB+ VRAM AND model is <70B AND you need perfect accuracy (research, medical use).',
            '**Q3:** Budget squeeze. 3% quality loss acceptable? Use Q3. Otherwise, upgrade GPU or use smaller model.',
            '**Q2:** Desperation. Quality loss too high for most. Use only if OOM on Q3.',
          ],
        },
        'q4': {
          title: 'Why Is Q4 the Industry Standard?',
          content: [
            '**Q4 is optimal because:**',
            '1. 87.5% VRAM savings (best ratio).',
            '2. <1.2% quality loss (imperceptible to users).',
            '3. No speed penalty (memory-bound, not compute-bound).',
            '4. Fits consumer hardware (70B on RTX 4090 24GB).',
            '5. Industry standard (HuggingFace, Ollama default to Q4).',
            'Every model released post-2024 includes a Q4 variant for production use.',
            'If a model only has FP32/Q8/Q5, the project is not production-ready.',
          ],
        },
        'mistakes': {
          title: 'Common Misconceptions',
          items: [
            'Q4 sounds "low quality" because 4-bit seems small. False. 1% quality loss is imperceptible.',
            'Quantization makes inference slower. False. Speed is identical (memory-bound, not compute-bound).',
            'I should use Q8 to be safe. False. Q4 is proven, safe, and standard. Q8 is wasteful.',
            'I need FP32 for accuracy. False. Never true. Q8 is sufficient even for research.',
          ],
        },
        'faqSection': {
          title: 'FAQ',
          faqs: [
            { q: 'What is LLM quantization?', a: 'Quantization compresses a model by reducing numerical precision, lowering memory usage and increasing speed.' },
            { q: 'What is the best quantization level?', a: 'Q4_K_M is the best default for most users, balancing performance and quality.' },
            { q: 'Does quantization reduce accuracy?', a: 'Yes, but Q4–Q5 retain most model quality while significantly reducing memory requirements.' },
            { q: 'Is Q8 worth it?', a: 'Only if you need maximum accuracy and have enough RAM. Most users will not benefit from Q8.' },
            { q: 'Should I use Q4 or Q8 for coding?', a: 'Q4. Speed is identical, quality difference is 1%, which is imperceptible for code generation.' },
            { q: 'Can I use Q3 if I\'m tight on VRAM?', a: 'Yes. 3% quality loss is acceptable for chat/creative writing. Unacceptable for reasoning/math.' },
            { q: 'Is there a Q6 or Q7?', a: 'No standard. Some projects implement custom levels, but Q4/Q5/Q8 are the industry standard.' },
            { q: 'Which quantization is fastest?', a: 'All identical speed (memory-bound). Q2 is slightly faster due to less memory transfer, but difference is <5%.' },
            { q: 'Can I dequantize Q4 back to FP32?', a: 'No, data is lost. Q4 → FP32 interpolation doesn\'t restore original. Quantization is one-way.' },
            { q: 'Should I quantize my fine-tuned model?', a: 'Yes, after training. Quantize the trained weights to Q4 for deployment.' },
            { q: 'What does GGUF Q4_K_M mean?', a: 'Q4_K_M is a refined Q4 variant using K-quants (mixed precision). The K algorithm preserves more accuracy on attention layers. Q4_K_M is the recommended download on HuggingFace for most models — effectively Q4 with ~0.3% better accuracy at the same VRAM cost.' },
            { q: 'Does quantization affect context length?', a: 'No. Quantization compresses model weights, not the context window. A Q4 model has the same maximum context length (e.g., 128k tokens) as its FP32 counterpart. Context memory (KV cache) is a separate concern from quantization.' },
          ],
        },
        'relatedReading': {
          title: 'Related Reading',
          items: [
            '[LLM Quantization Explained](/local-llms/llm-quantization-explained)',
            '[How Much VRAM Do You Need?](/local-llms/how-much-vram-local-llm)',
            '[Best Budget GPUs for Local LLMs](/local-llms/best-budget-gpus-local-llm)',
            '[Fastest Local LLMs for Low-End PCs](/local-llms/fastest-local-llms-low-end-pcs)',
            '[Local LLM Hardware Guide 2026](/local-llms/local-llm-hardware-guide-2026) — GPU selection, VRAM tiers, and CPU inference benchmarks',
            '[Best Local LLMs for Coding 2026](/local-llms/best-local-llms-for-coding) — Coding-specific model benchmarks and FIM support comparison',
          ],
        },
        'sources': {
          title: 'Sources',
          items: [
            '[MMLU Benchmark — OpenAI Evals](https://github.com/openai/evals) — Measuring accuracy across Q4/Q8/FP32 quantization levels on 57 reasoning tasks',
            '[Llama 3 Model Card — Meta AI](https://huggingface.co/meta-llama/Meta-Llama-3-70B) — Official accuracy specifications across quantization levels',
            '[Towards Quantization-Aware Deep Neural Networks (arXiv 2024)](https://arxiv.org/abs/2401.01781) — Research on quantization error bounds and K-quant methodology',
            'Quantization reduces model size but doesn\'t eliminate output variability. Parameter tuning can compensate for precision loss: [temperature and top-p](https://www.promptquorum.com/prompt-engineering/temperature-and-top-p-control-ai-creativity) explains sampling strategies.',
          ],
        },
      },
    },
    de: {
      theme: 'Modelle nach Anwendungsfall',
      title: 'Q4 vs Q5 vs Q8: Welche Quantisierungsstufe sollten Sie wählen?',
      seoTitle: 'Q4 vs Q5 vs Q8: Beste LLM-Quantisierung für Speed, RAM & Qualität (2026)',
      intro: '**Q4 (4-Bit) ist der optimale Kompromiss: 87,5 % VRAM-Ersparnis mit unmerklichem Qualitätsverlust.** Ab April 2026 ist Q5 überflüssig (nur 5 % bessere Qualität, gleiche VRAM-Kosten wie Q4), und Q8 ist für Perfektionisten mit überschüssigem VRAM. FP32 (vollständige Genauigkeit) ist für die Inferenz auf Verbraucherhardware nie notwendig.',
      metaDescription: 'Vollständiger GGUF-Quantisierungsvergleich: Q2, Q3, Q4, Q5, Q6, Q8. Lernen Sie die Kompromisse bei Genauigkeit, Latenz und Speicher für optimale lokale LLM-Leistung.',
      publishDate: '2026-04-05',
      dateModified: '2026-04-18',
      leadAnswerBlock: '**Q4 (4-Bit) ist der optimale Kompromiss: 87,5 % VRAM-Ersparnis mit unmerklichem Qualitätsverlust. Ab April 2026 ist Q5 überflüssig (nur 5 % bessere Qualität, gleiche VRAM-Kosten wie Q4), und Q8 ist für Perfektionisten mit überschüssigem VRAM.**',
      audience: 'Entwickler, die mit Ollama oder LM Studio lokale LLM-Workflows optimieren',
      readTime: '8 Min. Lesezeit',
      educationalLevel: 'Intermediate',
      primaryTerm: 'Quantisierung',
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'Q4 vs Q5 vs Q8: Welche Quantisierungsstufe sollten Sie wählen?',
        description: 'Vollständiger GGUF-Quantisierungsvergleich: Q2, Q3, Q4, Q5, Q6, Q8. Lernen Sie die Kompromisse bei Genauigkeit, Latenz und Speicher für optimale lokale LLM-Leistung.',
        datePublished: '2026-04-05',
        dateModified: '2026-04-18',
        url: 'https://www.promptquorum.com/local-llms/quantization-levels-comparison?lang=de',
        inLanguage: 'de',
        proficiencyLevel: 'Intermediate',
        author: { '@type': 'Person', 'name': 'Hans Kuepper' },
        publisher: { '@type': 'Organization', 'name': 'PromptQuorum', 'url': 'https://www.promptquorum.com' },
        about: [
          { '@type': 'Thing', 'name': 'LLM-Quantisierung' },
          { '@type': 'Thing', 'name': 'VRAM-Optimierung' },
          { '@type': 'Thing', 'name': 'Ollama' },
          { '@type': 'Thing', 'name': 'GGUF-Format' },
        ],
        speakable: { '@type': 'SpeakableSpecification', 'cssSelector': ['.article-intro', '.key-takeaways'] },
      },
      gammaEmbedUrl: '/presentations/quantization-levels-comparison-static.html',
      gammaDescription: 'Das Foliendeck unten behandelt: warum LLM-Quantisierung Modelle komprimiert (Reduktion der Genauigkeit von 16-Bit auf Q4/Q8), VRAM-Einsparungen über Q2–Q8-Level (70 GB für Q4 vs. 280 GB für FP32), Qualitätsverlust-Benchmarks (Q4 behält 99 % Genauigkeit bei, 1,2 % Verlust), und wann jede Stufe je nach Hardware (8 GB → Q3/Q4, 16 GB → Q4_K_M, 32 GB+ → Q5/Q8) verwendet werden sollte. Laden Sie das PDF als Quantisierungsstufen-Referenzkarte herunter.',
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'de',
        mainEntity: [
          { '@type': 'Question', name: 'Was ist LLM-Quantisierung?', acceptedAnswer: { '@type': 'Answer', text: 'Quantisierung komprimiert ein Modell, indem die numerische Genauigkeit reduziert wird, was den Speicherverbrauch senkt und die Geschwindigkeit erhöht.' } },
          { '@type': 'Question', name: 'Was ist die beste Quantisierungsstufe?', acceptedAnswer: { '@type': 'Answer', text: 'Q4_K_M ist die beste Standardoption für die meisten Nutzer und balanciert Leistung und Qualität.' } },
          { '@type': 'Question', name: 'Verringert Quantisierung die Genauigkeit?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, aber Q4–Q5 behalten die meiste Modellqualität bei, während der Speicherverbrauch erheblich sinkt.' } },
          { '@type': 'Question', name: 'Lohnt sich Q8?', acceptedAnswer: { '@type': 'Answer', text: 'Nur wenn Sie maximale Genauigkeit benötigen und genug RAM haben. Die meisten Nutzer profitieren nicht von Q8.' } },
          { '@type': 'Question', name: 'Sollte ich Q4 oder Q8 für Code-Generierung verwenden?', acceptedAnswer: { '@type': 'Answer', text: 'Q4. Die Geschwindigkeit ist identisch, der Qualitätsunterschied beträgt 1 %, was für Code-Generierung unmerklich ist.' } },
          { '@type': 'Question', name: 'Kann ich Q3 verwenden, wenn ich wenig VRAM habe?', acceptedAnswer: { '@type': 'Answer', text: 'Ja. Ein Qualitätsverlust von 3 % ist für Chat/kreatives Schreiben akzeptabel. Nicht akzeptabel für Denkaufgaben/Mathematik.' } },
          { '@type': 'Question', name: 'Gibt es Q6 oder Q7?', acceptedAnswer: { '@type': 'Answer', text: 'Keinen Standard. Einige Projekte implementieren benutzerdefinierte Level, aber Q4/Q5/Q8 sind der Industriestandard.' } },
          { '@type': 'Question', name: 'Welche Quantisierung ist am schnellsten?', acceptedAnswer: { '@type': 'Answer', text: 'Alle sind gleich schnell (speichergebunden). Q2 ist leicht schneller wegen weniger Speichertransfer, aber der Unterschied ist <5 %.' } },
          { '@type': 'Question', name: 'Kann ich Q4 zu FP32 dequantisieren?', acceptedAnswer: { '@type': 'Answer', text: 'Nein, Daten gehen verloren. Q4 → FP32 Interpolation stellt das Original nicht wieder her. Quantisierung ist Einbahnstraße.' } },
          { '@type': 'Question', name: 'Sollte ich mein fein abgestimmtes Modell quantisieren?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, nach dem Training. Quantisieren Sie die trainierten Gewichte zu Q4 für die Bereitstellung.' } },
          { '@type': 'Question', name: 'Was bedeutet GGUF Q4_K_M?', acceptedAnswer: { '@type': 'Answer', text: 'Q4_K_M ist eine verfeinerte Q4-Variante, die K-Quants (gemischte Genauigkeit) verwendet. Der K-Algorithmus bewahrt mehr Genauigkeit bei Aufmerksamkeitsschichten. Q4_K_M ist der empfohlene HuggingFace-Download – faktisch Q4 mit etwa 0,3 % besserer Genauigkeit bei gleichen VRAM-Kosten.' } },
          { '@type': 'Question', name: 'Beeinflusst Quantisierung die Kontextlänge?', acceptedAnswer: { '@type': 'Answer', text: 'Nein. Quantisierung komprimiert Modellgewichte, nicht das Kontextfenster. Ein Q4-Modell hat die gleiche maximale Kontextlänge wie seine FP32-Version. Der Kontextspeicher (KV-Cache) ist ein separates Anliegen.' } },
          { '@type': 'Question', name: 'Muss ich bei der Verwendung von Quantisierung die DSGVO beachten?', acceptedAnswer: { '@type': 'Answer', text: 'Ja. Lokale Inferenz erfüllt die Anforderungen von DSGVO Artikel 28 (Datenverarbeitung vor Ort). Nutzen Sie lokale Quantisierung für DSGVO-Compliance, BSI-Grundschutz-Kataloge und Datenresidenz in der EU. Q4-Modelle laufen vollständig offline – kein Datentransfer zu Drittanbietern.' } },
          { '@type': 'Question', name: 'Ist Quantisierung für den deutschen Mittelstand geeignet?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, besonders für den deutschen Mittelstand. Quantisierte Modelle laufen auf vorhandener Hardware (Laptops, lokalen Servern), erfüllen BSI-Grundschutz-Standards und reduzieren Lizenzkosten. KMUs profitieren vom Umstieg von Cloud-APIs zu lokal gehosteten Q4-Modellen – kosteneffizienz ohne Sicherheitskompromisse.' } },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        name: 'LLM-Quantisierungsstufen: Q4 vs Q5 vs Q8 Vergleich',
        description: 'Vergleich der LLM-Quantisierungsstufen nach VRAM-Verbrauch, Qualitätsverlust, Geschwindigkeit und empfohlene Anwendungsfälle.',
        inLanguage: 'de',
        numberOfItems: 6,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'FP32 (32-Bit volle Genauigkeit)', description: '280 GB VRAM für Llama 3 70B. Baseline-Qualität. Identische Geschwindigkeit. Nie praktisch für Verbraucherhardware.' },
          { '@type': 'ListItem', position: 2, name: 'Q8 (8-Bit Quantisierung)', description: '140 GB VRAM für Llama 3 70B. -0,05 % Qualitätsverlust vs. FP32. Identische Geschwindigkeit. Für 32 GB+ VRAM mit genauigkeitskritischen Aufgaben.' },
          { '@type': 'ListItem', position: 3, name: 'Q5 (5-Bit Quantisierung)', description: '88 GB VRAM für Llama 3 70B. -0,5 % Qualitätsverlust. Tote Zone: Q4 + etwas größeres Modell ergibt bessere Ergebnisse bei gleichem VRAM.' },
          { '@type': 'ListItem', position: 4, name: 'Q4 (4-Bit Quantisierung)', description: '70 GB VRAM für Llama 3 70B. -1,2 % Qualitätsverlust auf MMLU. Industriestandard. Passt auf RTX 4090. Empfohlener Standard für alle Anwendungsfälle.' },
          { '@type': 'ListItem', position: 5, name: 'Q3 (3-Bit Quantisierung)', description: '53 GB VRAM für Llama 3 70B. -3,7 % Qualitätsverlust. Verwenden Sie nur als VRAM-Budgetlösung, wenn Q4 zu Out-of-Memory führt.' },
          { '@type': 'ListItem', position: 6, name: 'Q2 (2-Bit Quantisierung)', description: '35 GB VRAM für Llama 3 70B. -10 % Qualitätsverlust. Notlösung. Qualitätsdegradation ist bei den meisten Aufgaben bemerkbar.' },
        ],
      },
      toc: [
        { label: 'Was ist LLM-Quantisierung?', anchor: '#featured-snippet' },
        { label: 'Zusammenfassung', anchor: '#tldr' },
        { label: 'Quantisierungsstufen im Vergleich: Q2 bis Q8', anchor: '#levels' },
        { label: 'Beste Quantisierungsstufe nach Anwendungsfall', anchor: '#best-choice' },
        { label: 'Wie beeinflusst Quantisierung VRAM und Geschwindigkeit?', anchor: '#vram' },
        { label: 'Qualitätsverlust nach Stufe: MMLU-Benchmark-Ergebnisse', anchor: '#quality' },
        { label: 'Wann sollte jede Stufe verwendet werden?', anchor: '#when' },
        { label: 'Warum ist Q4 der Industriestandard?', anchor: '#q4' },
        { label: 'Häufige Missverständnisse', anchor: '#mistakes' },
        { label: 'FAQ', anchor: '#faq' },
      ],
      sections: {
        definition: {
          id: 'featured-snippet',
          title: 'Was ist LLM-Quantisierung?',
          content: 'LLM-Quantisierung reduziert die Modellgröße durch Komprimierung von Gewichten von 16-Bit auf niedrigere Präzisionsformate wie Q4 oder Q8.',
          items: [
            'Q2–Q3 → schnellste, niedrigste Qualität',
            'Q4 → bestes Gleichgewicht (empfohlen)',
            'Q5–Q6 → höhere Qualität, mehr RAM',
            'Q8 → fast volle Präzision, am langsamsten',
          ],
          note: 'Für die meisten Nutzer: Q4_K_M ist die beste Standardoption.',
        },
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            '**Q4 (4-Bit):** 87,5 % VRAM-Ersparnis, ~1 % Qualitätsverlust. Verwenden Sie dies für alles.',
            '**Q5 (5-Bit):** 84 % VRAM-Ersparnis, ~0,5 % Qualitätsverlust. Nie notwendig; Q4 + Q8 grenzen Q5 ein.',
            '**Q8 (8-Bit):** 50 % VRAM-Ersparnis, <0,1 % Qualitätsverlust. Für Perfektionisten mit überschüssigem VRAM.',
            '**FP32 (32-Bit):** Volle Präzision, 0 % Verlust, 0 % Ersparnis. Unpraktisch; überspringen Sie es.',
            '**Geschwindigkeit:** Alle Quantisierungen laufen mit identischen Token/Sekunde (speichergebunden, nicht rechengebunden).',
            '**VRAM-Verbrauch (70B Llama-Modell):** FP32=280 GB, Q8=140 GB, Q5=88 GB, Q4=70 GB.',
            '**Empfehlung:** Verwenden Sie Q4 für 7B–70B. Verwenden Sie Q8 nur wenn Sie 32 GB+ VRAM haben und makellose Qualität benötigen.',
            '**Niemand verwendet Q5, weil Q4 + kleine Steigerung = besser als Q5 + gleiche Hardware.**',
          ],
        },
        quickFacts: {
          id: 'quick-facts',
          title: 'Schnelle Fakten',
          items: [
            '**Q4 VRAM-Ersparnis:** 87,5 % vs. FP32 (70 GB für Llama 3 70B)',
            '**Q4 Qualitätsverlust:** <1,2 % auf MMLU-Benchmark',
            '**Q8 VRAM-Ersparnis:** 50 % vs. FP32 (140 GB für Llama 3 70B)',
            '**Geschwindigkeitsunterschied:** 0 % — alle Quantisierungen laufen mit identischen Tokens/Sekunde',
            '**Q5-Urteil:** Tote Zone — Q4 + größeres Modell = besseres Ergebnis bei gleichem VRAM',
          ],
        },
        'levels': {
          title: 'Quantisierungsstufen im Vergleich: Q2 bis Q8',
          rows: [
            { 'Quantisierung': 'Q2', 'RAM-Verbrauch': 'Sehr niedrig', 'Geschwindigkeit': 'Sehr schnell', 'Qualität': 'Schlecht', 'Beste für': 'Experimente' },
            { 'Quantisierung': 'Q3', 'RAM-Verbrauch': 'Niedrig', 'Geschwindigkeit': 'Schnell', 'Qualität': 'Niedrig', 'Beste für': 'Kleine Geräte' },
            { 'Quantisierung': 'Q4', 'RAM-Verbrauch': 'Mittel', 'Geschwindigkeit': 'Schnell', 'Qualität': 'Gut', 'Beste für': 'Die meisten Nutzer' },
            { 'Quantisierung': 'Q5', 'RAM-Verbrauch': 'Mittel+', 'Geschwindigkeit': 'Mittel', 'Qualität': 'Sehr gut', 'Beste für': 'Code' },
            { 'Quantisierung': 'Q6', 'RAM-Verbrauch': 'Hoch', 'Geschwindigkeit': 'Langsamer', 'Qualität': 'Ausgezeichnet', 'Beste für': 'Genauigkeit Fokus' },
            { 'Quantisierung': 'Q8', 'RAM-Verbrauch': 'Sehr hoch', 'Geschwindigkeit': 'Langsam', 'Qualität': 'Nah an FP16', 'Beste für': 'Benchmarking' },
          ],
          columns: ['Quantisierung', 'RAM-Verbrauch', 'Geschwindigkeit', 'Qualität', 'Beste für'],
          image: '/images/quantization-levels-comparison-vram-savings-de.svg',
          imageCaption: 'VRAM-Ersparnis nach Quantisierungsstufe: FP32 = 280 GB, Q8 = 140 GB (50 % Ersparnis), Q4 = 70 GB (75 % Ersparnis), Q3 = 53 GB (81 % Ersparnis). Q4 ist der optimale Kompromiss für die meisten Nutzer.',
        },
        'choices': {
          id: 'best-choice',
          title: 'Beste Quantisierungsstufe nach Anwendungsfall',
          items: [
            '**8 GB RAM:** Q3 oder Q4 (nur kleine 7B-Modelle)',
            '**16 GB RAM:** Q4_K_M (empfohlen für die meisten Laptops)',
            '**32 GB RAM:** Q5, Q6 oder Q8 (größere Modelle, höhere Qualität)',
            '**Maximale Genauigkeit:** Q8 (wenn VRAM keine Einschränkung ist)',
          ],
          image: '/images/quantization-levels-comparison-hardware-guide-de.svg',
          imageCaption: 'Hardwareauswahl-Guide: 8 GB RAM → Q3/Q4 (7B-Modelle), 16 GB → Q4_K_M (empfohlen), 32 GB+ → Q5/Q6/Q8 (größere Modelle, höhere Qualität), 64 GB+ → Q8 oder FP32 (Forschung/Medizin).',
        },
        'vram': {
          title: 'Wie beeinflusst Quantisierung VRAM und Geschwindigkeit?',
          content: [
            '**VRAM-Berechnung:** Modellgröße (GB) × Quantisierungsfaktor.',
            'Llama 3 70B:',
            '- FP32: 70B × 4 Bytes = 280 GB (unpraktisch)',
            '- Q8: 70B × 1 Byte = 140 GB (benötigt 140 GB VRAM)',
            '- Q4: 70B × 0,5 Bytes = 70 GB (passt auf RTX 4090 + etwas Overhead)',
            '**Geschwindigkeit:** Alle Quantisierungen sind speichergebunden (warten auf DRAM), nicht rechengebunden.',
            'TokensSekunde sind auf gleicher Hardware identisch über Q2-FP32 hinweg.',
            '**VRAM-Bandbreite, nicht Berechnung, ist der Engpass.** Quantisierung spart VRAM, nicht Zeit.',
          ],
        },
        'quality': {
          title: 'Qualitätsverlust nach Stufe: MMLU-Benchmark-Ergebnisse',
          content: 'Gemessen auf MMLU-Benchmark (allgemeine Kenntnisse, 57 Aufgaben):',
          items: [
            'Llama 3 70B FP32 Baseline: 85,2 % Genauigkeit.',
            'Llama 3 70B Q8: 85,1 % Genauigkeit (-0,1 % Verlust).',
            'Llama 3 70B Q5: 84,7 % Genauigkeit (-0,5 % Verlust).',
            'Llama 3 70B Q4: 84,0 % Genauigkeit (-1,2 % Verlust).',
            'Llama 3 70B Q3: 81,5 % Genauigkeit (-3,7 % Verlust).',
            'Auswirkung in der Praxis: Q4 vs. Q8 = 1–2 % weniger korrekte Antworten pro 100 Fragen.',
            'Für Chat/Schreiben: unmerklicher Unterschied. Für MINT-Probleme: Q8 ist sicherer.',
          ],
          image: '/images/quantization-levels-comparison-quality-loss-de.svg',
          imageCaption: 'Qualitätsverlust-Benchmarks: Q8 = -0,1 % Verlust, Q5 = -0,5 % Verlust, Q4 = -1,2 % Verlust, Q3 = -3,7 % Verlust auf MMLU. Q4 Qualitätsverlust ist für die meisten Aufgaben unmerklich.',
        },
        'when': {
          title: 'Wann sollte jede Stufe verwendet werden?',
          content: [
            '**Q4:** Standard. Verwenden Sie für alle Modelle. Optimaler Kompromiss zwischen Komprimierung und Qualität.',
            '**Q5:** Nie. Verschwendung. Wenn Sie Q5-Qualität benötigen, verwenden Sie Q4 mit etwas größerem Modell. Wenn Sie Q5s VRAM (88 GB) haben, verwenden Sie Q4 auf 70B stattdessen.',
            '**Q8:** Nur wenn Sie 32 GB+ VRAM UND ein Modell <70B haben UND perfekte Genauigkeit benötigen (Forschung, Medizin).',
            '**Q3:** Budgetlösung. 3 % Qualitätsverlust akzeptabel? Verwenden Sie Q3. Andernfalls GPU upgraden oder kleineres Modell verwenden.',
            '**Q2:** Notlösung. Qualitätsverlust zu hoch für die meisten. Verwenden Sie nur wenn Q3 zu Out-of-Memory führt.',
          ],
        },
        'q4': {
          title: 'Warum ist Q4 der Industriestandard?',
          content: [
            '**Q4 ist optimal, weil:**',
            '1. 87,5 % VRAM-Ersparnis (bestes Verhältnis).',
            '2. <1,2 % Qualitätsverlust (unmerklich für Nutzer).',
            '3. Keine Geschwindigkeit-Strafe (speichergebunden, nicht rechengebunden).',
            '4. Passt auf Verbraucherhardware (70B auf RTX 4090 24GB).',
            '5. Industriestandard (HuggingFace, Ollama Standard auf Q4).',
            'Jedes nach 2024 veröffentlichte Modell enthält eine Q4-Variante für Produktion.',
            'Wenn ein Modell nur FP32/Q8/Q5 hat, ist das Projekt nicht produktionsreif.',
          ],
        },
        'mistakes': {
          title: 'Häufige Missverständnisse',
          items: [
            'Q4 klingt nach "niedriger Qualität", weil 4-Bit klein wirkt. Falsch. 1 % Qualitätsverlust ist unmerklich.',
            'Quantisierung macht Inferenz langsamer. Falsch. Geschwindigkeit ist identisch (speichergebunden, nicht rechengebunden).',
            'Ich sollte Q8 verwenden um sicher zu sein. Falsch. Q4 ist bewährt, sicher und Standard. Q8 ist verschwenderisch.',
            'Ich benötige FP32 für Genauigkeit. Falsch. Nie wahr. Q8 reicht selbst für Forschung.',
          ],
        },
        'faqSection': {
          title: 'FAQ',
          faqs: [
            { q: 'Was ist LLM-Quantisierung?', a: 'Quantisierung komprimiert ein Modell durch Reduktion der numerischen Genauigkeit, reduziert Speicherverbrauch und erhöht Geschwindigkeit.' },
            { q: 'Was ist die beste Quantisierungsstufe?', a: 'Q4_K_M ist die beste Standardoption für die meisten Nutzer und balanciert Leistung und Qualität.' },
            { q: 'Verringert Quantisierung die Genauigkeit?', a: 'Ja, aber Q4–Q5 behalten die meiste Modellqualität, während der Speicherverbrauch erheblich sinkt.' },
            { q: 'Lohnt sich Q8?', a: 'Nur wenn Sie maximale Genauigkeit benötigen und genug RAM haben. Die meisten Nutzer profitieren nicht von Q8.' },
            { q: 'Sollte ich Q4 oder Q8 für Code-Generierung verwenden?', a: 'Q4. Die Geschwindigkeit ist identisch, der Qualitätsunterschied beträgt 1 %, was für Code-Generierung unmerklich ist.' },
            { q: 'Kann ich Q3 verwenden, wenn ich wenig VRAM habe?', a: 'Ja. Ein Qualitätsverlust von 3 % ist für Chat/kreatives Schreiben akzeptabel. Nicht akzeptabel für Denkaufgaben/Mathematik.' },
            { q: 'Gibt es Q6 oder Q7?', a: 'Keinen Standard. Einige Projekte implementieren benutzerdefinierte Level, aber Q4/Q5/Q8 sind der Industriestandard.' },
            { q: 'Welche Quantisierung ist am schnellsten?', a: 'Alle sind gleich schnell (speichergebunden). Q2 ist leicht schneller wegen weniger Speichertransfer, aber der Unterschied ist <5 %.' },
            { q: 'Kann ich Q4 zu FP32 dequantisieren?', a: 'Nein, Daten gehen verloren. Q4 → FP32 Interpolation stellt das Original nicht wieder her. Quantisierung ist Einbahnstraße.' },
            { q: 'Sollte ich mein fein abgestimmtes Modell quantisieren?', a: 'Ja, nach dem Training. Quantisieren Sie die trainierten Gewichte zu Q4 für die Bereitstellung.' },
            { q: 'Was bedeutet GGUF Q4_K_M?', a: 'Q4_K_M ist eine verfeinerte Q4-Variante, die K-Quants (gemischte Genauigkeit) verwendet. Der K-Algorithmus bewahrt mehr Genauigkeit bei Aufmerksamkeitsschichten. Q4_K_M ist der empfohlene HuggingFace-Download – faktisch Q4 mit etwa 0,3 % besserer Genauigkeit bei gleichen VRAM-Kosten.' },
            { q: 'Beeinflusst Quantisierung die Kontextlänge?', a: 'Nein. Quantisierung komprimiert Modellgewichte, nicht das Kontextfenster. Ein Q4-Modell hat die gleiche maximale Kontextlänge wie seine FP32-Version. Der Kontextspeicher (KV-Cache) ist ein separates Anliegen.' },
            { q: 'Muss ich bei der Verwendung von Quantisierung die DSGVO beachten?', a: 'Ja. Lokale Inferenz erfüllt die Anforderungen von DSGVO Artikel 28 (Datenverarbeitung vor Ort). Nutzen Sie lokale Quantisierung für DSGVO-Compliance, BSI-Grundschutz-Kataloge und Datenresidenz in der EU. Q4-Modelle laufen vollständig offline – kein Datentransfer zu Drittanbietern.' },
            { q: 'Ist Quantisierung für den deutschen Mittelstand geeignet?', a: 'Ja, besonders für den deutschen Mittelstand. Quantisierte Modelle laufen auf vorhandener Hardware (Laptops, lokalen Servern), erfüllen BSI-Grundschutz-Standards und reduzieren Lizenzkosten. KMUs profitieren vom Umstieg von Cloud-APIs zu lokal gehosteten Q4-Modellen – kosteneffizienz ohne Sicherheitskompromisse.' },
          ],
        },
        'relatedReading': {
          title: 'Weiterführende Lektüre',
          items: [
            '[LLM-Quantisierung erklärt](/local-llms/llm-quantization-explained?lang=de)',
            '[Wie viel VRAM benötigen Sie?](/local-llms/how-much-vram-local-llm?lang=de)',
            '[Beste Budget-GPUs für lokale LLMs](/local-llms/best-budget-gpus-local-llm?lang=de)',
            '[Schnellste lokale LLMs für Low-End-PCs](/local-llms/fastest-local-llms-low-end-pcs?lang=de)',
            '[Lokaler LLM-Hardware-Guide 2026](/local-llms/local-llm-hardware-guide-2026?lang=de) — GPU-Auswahl, VRAM-Stufen und CPU-Inferenz-Benchmarks',
            '[Beste lokale LLMs für Code 2026](/local-llms/best-local-llms-for-coding?lang=de) — Code-spezifische Modell-Benchmarks und FIM-Support-Vergleich',
          ],
        },
        'sources': {
          title: 'Quellen',
          items: [
            '[MMLU-Benchmark — OpenAI Evals](https://github.com/openai/evals) — Messung der Genauigkeit über Q4/Q8/FP32-Quantisierungsstufen auf 57 Denkaufgaben',
            '[Llama 3 Model Card — Meta AI](https://huggingface.co/meta-llama/Meta-Llama-3-70B) — Offizielle Genauigkeitsspezifikationen über Quantisierungsstufen',
            '[Towards Quantization-Aware Deep Neural Networks (arXiv 2024)](https://arxiv.org/abs/2401.01781) — Forschung zu Quantisierungsfehlerschranken und K-Quant-Methodologie',
          ],
        },
      },
    },
  };
