// Auto-generated from src/lib/local-llms/content.ts
// Slug: run-70b-models-24gb-vram
// Generated: 2026-05-03T11:33:08.370Z

import type { Language } from "@/lib/blog/blogContent";

import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
    en: {
      freshness_tier: 'semi_annual',
      theme: 'Hardware & Performance',
      title: 'How to Run 70B Models on 24GB VRAM: Advanced Techniques',
      seoTitle: 'Run 70B Models on 24 GB VRAM: Complete Setup Guide 2026',
      intro: 'Running a 70B model (normally requires 40+ GB) on 24 GB VRAM is possible with aggressive quantization (Q2-Q3) and layer offloading, but the result is slow (~3-5 tokens/sec). As of April 2026, this is impractical for real-time chat but viable for batch processing or experimentation.',
      metaDescription: 'Run 70B models on 24GB VRAM 2026: quantization (Q4_K_M), offloading, layer splitting. Techniques with trade-offs and performance data.',
      publishDate: '2026-04-04',
      dateModified: '2026-04-19',
      leadAnswerBlock: '**Running a 70B model (normally requires 40+ GB) on 24 GB VRAM is possible with aggressive quantization (Q2-Q3) and layer offloading, but the result is slow (~3-5 tokens/sec).**',
      audience: 'Engineers deploying local LLMs in production or enterprise environments',
      readTime: '10 min read',
      educationalLevel: 'Advanced',
      primaryTerm: '70B model optimization',
      toc: [
        { label: 'Key Takeaways', anchor: '#key-takeaways' },
        { label: 'Theoretical Limits', anchor: '#limits' },
        { label: 'Quantization Strategy', anchor: '#quantization' },
        { label: 'Offloading Strategy', anchor: '#offloading' },
        { label: 'Practical Setup', anchor: '#setup' },
        { label: 'Realistic Performance', anchor: '#performance' },
        { label: 'Better Alternatives', anchor: '#alternatives' },
        { label: 'Common Mistakes', anchor: '#common-mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Related Reading', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            'Llama 3.3 70B at Q4 = 35 GB (too large for 24GB). At Q3 = 26 GB (still too large). At Q2 = 17 GB (fits!).',
            'Trade-off: Q2 has noticeable quality loss. ~70% of FP16 quality.',
            'Speed: 3-5 tokens/sec with 20 GB offloaded to system RAM (ultra-slow).',
            'Better option: Use 13B model at Q5, or buy a second GPU for layer splitting.',
            'As of April 2026, this is a constraint workaround, not a recommended approach.',
          ],
        },
        limits: {
          id: 'limits',
          title: 'The Theoretical VRAM Math',
          content: [
            '**Llama 3.3 70B at various quantizations:**',
          ],
          rows: [
            { 'Quantization': 'FP16 (baseline)', 'Size': '140 GB', 'Fits 24GB?': 'No' },
            { 'Quantization': 'Q8 (8-bit)', 'Size': '70 GB', 'Fits 24GB?': 'No' },
            { 'Quantization': 'Q5 (5-bit)', 'Size': '43.75 GB', 'Fits 24GB?': 'No' },
            { 'Quantization': 'Q4 (4-bit)', 'Size': '35 GB', 'Fits 24GB?': 'No (with offloading: maybe)' },
            { 'Quantization': 'Q3 (3-bit)', 'Size': '26 GB', 'Fits 24GB?': 'No (barely)' },
            { 'Quantization': 'Q2 (2-bit)', 'Size': '17.5 GB', 'Fits 24GB?': 'Yes' },
          ],
          columns: ['Quantization', 'Model Size', 'Fits 24GB?'],
        },
        quantization: {
          id: 'quantization',
          title: 'Aggressive Quantization: The Primary Tool',
          content: [
            '**To fit 70B in 24GB, you must use Q2 or Q3 quantization.**',
            '- **Q3**: 26 GB (still 2 GB over). Can offload 2 GB to RAM. Slightly better quality than Q2.',
            '- **Q2**: 17.5 GB (fits!). 70% quality vs FP16. Noticeable degradation but usable.',
            'Download the quantized model: `ollama pull llama3.1:70b-q2` (if available) or use conversion tools like llama.cpp.',
          ],
        },
        offloading: {
          id: 'offloading',
          title: 'Offloading to System RAM',
          content: [
            '**If using Q4 (35 GB) on 24GB GPU, you can offload the remaining 11 GB to system RAM.** Speed penalty is severe (10× slower).',
            'Only practical for batch processing where you can wait hours for results.',
          ],
        },
        setup: {
          id: 'setup',
          title: 'Practical Setup: Running 70B on 24GB',
          content: 'Step-by-step:',
          numberedItems: [
            'Use Q2 quantization: `ollama pull llama3.1:70b-q2` (if available, else convert with llama.cpp)',
            'Verify VRAM: `nvidia-smi` should show ~18 GB used',
            'Run the model: `ollama run llama3.1:70b-q2`',
            'Expect 3-5 tokens/sec (very slow)',
            'Use only for batch/offline processing, not interactive chat',
          ],
        },
        performance: {
          id: 'performance',
          title: 'Realistic Performance Expectations',
          content: [
            '**Running 70B on 24GB VRAM is slow:**',
          ],
          rows: [
            { 'Quantization': 'Q2 (24GB VRAM)', 'Speed': '5-8 tok/sec', 'Latency': '2-4 sec per token', 'Use Case': 'Batch processing only' },
            { 'Quantization': 'Q3 + offload (24GB)', 'Speed': '3-5 tok/sec', 'Latency': '3-5 sec per token', 'Use Case': 'Extremely limited' },
            { 'Quantization': 'Q4 + offload (24GB)', 'Speed': '1-3 tok/sec', 'Latency': '5-10 sec per token', 'Use Case': 'Overnight batch only' },
          ],
          columns: ['Quantization', 'Speed', 'Latency', 'Use Case'],
        },
        alternatives: {
          id: 'alternatives',
          title: 'Better Alternatives to Constrained 70B',
          content: 'Instead of struggling with 70B on limited VRAM, consider:',
          items: [
            'Use a 13B model (Llama 3.3 13B at Q5 = 8 GB, very fast)',
            'Buy a second RTX 4090 for layer splitting (2× 24GB = 48GB, 100+ tok/sec)',
            'Use a cloud API (GPT-5.5 for important tasks, local for experimentation)',
            'Wait for more efficient models (smaller, same quality)',
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: 'Common Mistakes With Constrained 70B',
          items: [
            '**Expecting Q2 to be usable for chat.** It is not. Quality degradation is too severe for real-time interaction.',
            '**Not measuring actual speed before committing.** Test with a small prompt (10 tokens) and verify speed before running large batch jobs.',
            '**Assuming offloading is "free".** System RAM is 100× slower than GPU VRAM. Offloading makes inference impractical.',
            '**Not considering alternatives.** A 13B model is dramatically faster and often sufficient in quality.',
          ],
        },
        faqSection: {
          id: 'faq',
          title: 'Frequently Asked Questions',
          faqs: [
            {
              q: 'Can I actually run a 70B model on a single RTX 4090?',
              a: 'Yes, but with significant caveats. At Q2 quantization (17.5 GB), the model fits in 24 GB VRAM but runs at 5–8 tokens/sec and has ~70% of FP16 quality. At Q4 (35 GB), you need to offload 11 GB to system RAM, dropping speed to 1–3 tokens/sec. Neither is suitable for real-time chat — only offline batch processing.',
            },
            {
              q: 'What quantization is needed to fit 70B in 24 GB VRAM?',
              a: 'Q2 quantization fits in 24 GB (17.5 GB model size). Q3 (26 GB) requires 2 GB of RAM offloading. Q4 (35 GB) requires 11 GB offloading and makes inference very slow. Q5 and above (44–70 GB) cannot fit even with offloading on a 24 GB GPU. Q2 is the only option that runs fully in VRAM.',
            },
            {
              q: 'How slow is a 70B model on 24 GB VRAM?',
              a: 'At Q2 (fully in VRAM): 5–8 tokens/sec. At Q3 with 2 GB RAM offload: 3–5 tokens/sec. At Q4 with 11 GB RAM offload: 1–3 tokens/sec. Compare to a 13B model at Q5 on the same GPU: 80–100 tokens/sec. The 70B constrained setup is 10–20× slower than a properly sized smaller model.',
            },
            {
              q: 'Is it better to use a 13B model than a constrained 70B?',
              a: 'For most tasks, yes. A 13B model at Q5 quantization runs at 80–100 tokens/sec on an RTX 4090 and delivers strong quality. A 70B model at Q2 runs at 5–8 tokens/sec with degraded quality. The 13B wins on speed and often on practical quality due to Q2 degradation. Only use 70B-on-24GB if you need specific 70B capabilities and can tolerate batch-only usage.',
            },
            {
              q: 'What is the best use case for 70B on 24 GB VRAM?',
              a: 'Overnight batch processing — tasks where you submit 100+ prompts and retrieve results hours later. Examples: document analysis, code review batches, dataset annotation. Real-time chat is impractical at 1–8 tokens/sec. For interactive use, a second RTX 4090 ($1,800) with layer splitting achieves ~100 tokens/sec — a far better investment.',
            },
            {
              q: 'How do I download Q2 quantized 70B models?',
              a: 'Via Ollama: `ollama pull llama3.1:70b-instruct-q2_K` (availability varies). Via llama.cpp: download GGUF Q2_K files from Hugging Face (search "llama-3.1-70b GGUF"). TheBloke and bartowski publish quantized versions. Verify the model with `nvidia-smi` after loading — VRAM usage should be ~18–20 GB for Q2.',
            },
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Related Reading',
          items: [
            '[Local LLM Hardware Guide 2026](/local-llms/local-llm-hardware-guide-2026) -- Buy better hardware instead.',
            '[Multi-GPU Local LLMs](/local-llms/multi-gpu-local-llms) -- Use layer splitting instead.',
            '[Best Local LLMs for Coding](/local-llms/best-local-llms-for-coding) -- Smaller models often sufficient.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Sources',
          items: [
            'llama.cpp Quantization -- github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/quants.py',
            'Model Card: Llama 3.3 70B -- huggingface.co/meta-llama/Llama-3.1-70B',
          ],
        },
      },
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'Run 70B Models on 24 GB VRAM: Complete Setup Guide 2026',
        description: 'Run 70B models on 24GB VRAM 2026: quantization (Q4_K_M), offloading, layer splitting. Techniques with trade-offs and performance data.',
        datePublished: '2026-04-04',
        dateModified: '2026-04-19',
        author: { '@type': 'Organization', name: 'PromptQuorum' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        proficiencyLevel: 'Advanced',
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        mainEntity: [
          {
            '@type': 'Question',
            name: 'Can I actually run a 70B model on a single RTX 4090?',
            acceptedAnswer: { '@type': 'Answer', text: 'Yes, but with significant caveats. At Q2 quantization (17.5 GB), the model fits in 24 GB VRAM but runs at 5–8 tokens/sec and has ~70% of FP16 quality. At Q4 (35 GB), you need to offload 11 GB to system RAM, dropping speed to 1–3 tokens/sec. Neither is suitable for real-time chat.' },
          },
          {
            '@type': 'Question',
            name: 'What quantization is needed to fit 70B in 24 GB VRAM?',
            acceptedAnswer: { '@type': 'Answer', text: 'Q2 quantization fits in 24 GB (17.5 GB model size). Q3 (26 GB) requires 2 GB of RAM offloading. Q4 (35 GB) requires 11 GB offloading and makes inference very slow. Q5 and above cannot fit even with offloading. Q2 is the only option that runs fully in VRAM.' },
          },
          {
            '@type': 'Question',
            name: 'How slow is a 70B model on 24 GB VRAM?',
            acceptedAnswer: { '@type': 'Answer', text: 'At Q2 (fully in VRAM): 5–8 tokens/sec. At Q3 with 2 GB RAM offload: 3–5 tokens/sec. At Q4 with 11 GB RAM offload: 1–3 tokens/sec. A 13B model at Q5 on the same GPU runs at 80–100 tokens/sec — 10–20× faster.' },
          },
          {
            '@type': 'Question',
            name: 'Is it better to use a 13B model than a constrained 70B?',
            acceptedAnswer: { '@type': 'Answer', text: 'For most tasks, yes. A 13B model at Q5 runs at 80–100 tokens/sec on an RTX 4090. A 70B model at Q2 runs at 5–8 tokens/sec with degraded quality. The 13B wins on speed and often on practical quality. Only use 70B-on-24GB if you need specific 70B capabilities and can tolerate batch-only usage.' },
          },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        name: 'Techniques to Run 70B Models on 24 GB VRAM',
        numberOfItems: 3,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Q2 Quantization (17.5 GB)', description: 'Fits fully in 24 GB VRAM. Quality: ~70% of FP16. Speed: 5–8 tokens/sec.' },
          { '@type': 'ListItem', position: 2, name: 'Q4 + CPU Offloading (11 GB offloaded)', description: 'Better quality but very slow: 1–3 tokens/sec. Suitable only for overnight batch.' },
          { '@type': 'ListItem', position: 3, name: 'Layer Splitting (2× RTX 4090)', description: 'Best option: 48 GB total, runs Q5 at ~100 tokens/sec. Recommended over single-GPU constraint.' },
        ],
      },
    },
    de: {
      freshness_tier: 'semi_annual',
      theme: 'Hardware & Performance',
      title: '70B-Modelle auf 24GB VRAM ausführen: Fortgeschrittene Techniken',
      seoTitle: '70B-Modelle mit 24 GB VRAM ausführen 2026',
      intro: 'Ein 70B-Modell (normalerweise 40+ GB erforderlich) auf 24 GB VRAM auszuführen ist mit aggressiver Quantisierung (Q2-Q3) und Layer-Offloading möglich, aber das Ergebnis ist langsam (~3-5 Token/Sek.). Ab April 2026 ist dies unpraktisch für Echtzeit-Chat, aber praktikabel für Batch-Verarbeitung oder Experimente.',
      metaDescription: '70B-Modelle auf 24GB VRAM 2026: Quantisierung (Q4_K_M), Offloading, Layer-Splitting. Techniken mit Trade-offs und Leistungsdaten.',
      publishDate: '2026-04-04',
      dateModified: '2026-04-19',
      leadAnswerBlock: '**Ein 70B-Modell (normalerweise 40+ GB erforderlich) auf 24 GB VRAM auszuführen ist mit aggressiver Quantisierung (Q2-Q3) und Layer-Offloading möglich, aber das Ergebnis ist langsam (~3-5 Token/Sek.).**',
      audience: 'Ingenieure, die lokale LLMs in Produktions- oder Unternehmensumgebungen einsetzen',
      readTime: '10 Min. Lesezeit',
      educationalLevel: 'Advanced',
      primaryTerm: '70B-Modell-Optimierung',
      toc: [
        { label: 'Wichtigste Erkenntnisse', anchor: '#key-takeaways' },
        { label: 'Theoretische Grenzen', anchor: '#limits' },
        { label: 'Quantisierungsstrategie', anchor: '#quantization' },
        { label: 'Offloading-Strategie', anchor: '#offloading' },
        { label: 'Praktisches Setup', anchor: '#setup' },
        { label: 'Realistische Leistung', anchor: '#performance' },
        { label: 'Bessere Alternativen', anchor: '#alternatives' },
        { label: 'Häufige Fehler', anchor: '#common-mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Weiterführendes Material', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            'Llama 3.3 70B bei Q4 = 35 GB (zu groß für 24GB). Bei Q3 = 26 GB (immer noch zu groß). Bei Q2 = 17 GB (passt!).',
            'Trade-off: Q2 hat spürbaren Qualitätsverlust. ~70% der FP16-Qualität.',
            'Geschwindigkeit: 3-5 Token/Sek. mit 20 GB auf System-RAM ausgelagert (ultra-langsam).',
            'Bessere Option: 13B-Modell bei Q5 verwenden oder eine zweite GPU für Layer-Splitting kaufen.',
            'Ab April 2026 ist dies eine Constraint-Behebung, keine empfohlene Methode.',
          ],
        },
        limits: {
          id: 'limits',
          title: 'Die theoretische VRAM-Mathematik',
          content: [
            '**Llama 3.3 70B bei verschiedenen Quantisierungen:**',
          ],
          rows: [
            { 'Quantisierung': 'FP16 (Baseline)', 'Größe': '140 GB', 'Passt in 24GB?': 'Nein' },
            { 'Quantisierung': 'Q8 (8-Bit)', 'Größe': '70 GB', 'Passt in 24GB?': 'Nein' },
            { 'Quantisierung': 'Q5 (5-Bit)', 'Größe': '43,75 GB', 'Passt in 24GB?': 'Nein' },
            { 'Quantisierung': 'Q4 (4-Bit)', 'Größe': '35 GB', 'Passt in 24GB?': 'Nein (mit Offloading: vielleicht)' },
            { 'Quantisierung': 'Q3 (3-Bit)', 'Größe': '26 GB', 'Passt in 24GB?': 'Nein (knapp)' },
            { 'Quantisierung': 'Q2 (2-Bit)', 'Größe': '17,5 GB', 'Passt in 24GB?': 'Ja' },
          ],
          columns: ['Quantisierung', 'Modellgröße', 'Passt in 24GB?'],
        },
        quantization: {
          id: 'quantization',
          title: 'Aggressive Quantisierung: Das Hauptwerkzeug',
          content: [
            '**Um 70B in 24GB zu passen, müssen Sie Q2 oder Q3 Quantisierung verwenden.**',
            '- **Q3**: 26 GB (immer noch 2 GB über). Kann 2 GB zu RAM auslagern. Etwas bessere Qualität als Q2.',
            '- **Q2**: 17,5 GB (passt!). 70% Qualität gegenüber FP16. Bemerkenswerter Qualitätsverlust, aber nutzbar.',
            'Das quantisierte Modell herunterladen: `ollama pull llama3.1:70b-q2` (falls verfügbar) oder Konvertierungstools wie llama.cpp verwenden.',
          ],
        },
        offloading: {
          id: 'offloading',
          title: 'Offloading zu System-RAM',
          content: [
            '**Wenn Sie Q4 (35 GB) auf einer 24GB GPU verwenden, können Sie die verbleibenden 11 GB zu System-RAM auslagern.** Die Geschwindigkeitseinbuße ist schwerwiegend (10× langsamer).',
            'Nur praktisch für Batch-Verarbeitung, bei der Sie Stunden auf Ergebnisse warten können.',
          ],
        },
        setup: {
          id: 'setup',
          title: 'Praktisches Setup: 70B auf 24GB ausführen',
          content: 'Schritt-für-Schritt:',
          numberedItems: [
            'Q2-Quantisierung verwenden: `ollama pull llama3.1:70b-q2` (falls verfügbar, sonst mit llama.cpp konvertieren)',
            'VRAM überprüfen: `nvidia-smi` sollte ~18 GB Auslastung anzeigen',
            'Modell ausführen: `ollama run llama3.1:70b-q2`',
            'Erwarten Sie 3-5 Token/Sek. (sehr langsam)',
            'Nur für Batch-/Offline-Verarbeitung verwenden, nicht für interaktiven Chat',
          ],
        },
        performance: {
          id: 'performance',
          title: 'Realistische Leistungserwartungen',
          content: [
            '**70B auf 24GB VRAM auszuführen ist langsam:**',
          ],
          rows: [
            { 'Quantisierung': 'Q2 (24GB VRAM)', 'Geschwindigkeit': '5-8 Token/Sek.', 'Latenz': '2-4 Sek. pro Token', 'Anwendungsfall': 'Nur Batch-Verarbeitung' },
            { 'Quantisierung': 'Q3 + Offload (24GB)', 'Geschwindigkeit': '3-5 Token/Sek.', 'Latenz': '3-5 Sek. pro Token', 'Anwendungsfall': 'Extrem begrenzt' },
            { 'Quantisierung': 'Q4 + Offload (24GB)', 'Geschwindigkeit': '1-3 Token/Sek.', 'Latenz': '5-10 Sek. pro Token', 'Anwendungsfall': 'Nur Overnight-Batch' },
          ],
          columns: ['Quantisierung', 'Geschwindigkeit', 'Latenz', 'Anwendungsfall'],
        },
        alternatives: {
          id: 'alternatives',
          title: 'Bessere Alternativen zu beschränktem 70B',
          content: 'Statt sich mit 70B bei limitiertem VRAM abzumühen, erwägen Sie:',
          items: [
            'Ein 13B-Modell verwenden (Llama 3.3 13B bei Q5 = 8 GB, sehr schnell)',
            'Eine zweite RTX 4090 für Layer-Splitting kaufen (2× 24GB = 48GB, 100+ Token/Sek.)',
            'Eine Cloud-API verwenden (GPT-5.5 für wichtige Aufgaben, lokal für Experimente)',
            'Auf effizientere Modelle warten (kleiner, gleiche Qualität)',
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: 'Häufige Fehler bei beschränktem 70B',
          items: [
            '**Erwartet, dass Q2 für Chat brauchbar ist.** Das ist es nicht. Der Qualitätsverlust ist zu schwerwiegend für die Echtzeit-Interaktion.',
            '**Nicht vorher die tatsächliche Geschwindigkeit messen.** Vor größeren Batch-Jobs mit einem kleinen Prompt (10 Token) testen und die Geschwindigkeit überprüfen.',
            '**Annahme, dass Offloading "kostenlos" ist.** System-RAM ist 100× langsamer als GPU VRAM. Das Offloading macht die Inferenz unpraktisch.',
            '**Keine Alternativen erwägen.** Ein 13B-Modell ist dramatisch schneller und oft in der Qualität ausreichend.',
          ],
        },
        faqSection: {
          id: 'faq',
          title: 'Häufig gestellte Fragen',
          faqs: [
            {
              q: 'Kann ich eine 70B-Modell wirklich auf einer einzelnen RTX 4090 ausführen?',
              a: 'Ja, aber mit erheblichen Einschränkungen. Bei Q2-Quantisierung (17,5 GB) passt das Modell in 24 GB VRAM, läuft aber mit 5-8 Token/Sek. und hat ~70% der FP16-Qualität. Bei Q4 (35 GB) müssen Sie 11 GB zu System-RAM auslagern, wodurch die Geschwindigkeit auf 1-3 Token/Sek. sinkt. Keine ist für Echtzeit-Chat geeignet — nur für Offline-Batch-Verarbeitung.',
            },
            {
              q: 'Welche Quantisierung ist erforderlich, um 70B in 24 GB VRAM zu passen?',
              a: 'Q2-Quantisierung passt in 24 GB (17,5 GB Modellgröße). Q3 (26 GB) erfordert 2 GB RAM-Offloading. Q4 (35 GB) erfordert 11 GB Offloading und macht die Inferenz sehr langsam. Q5 und höher (44-70 GB) können nicht passen, auch nicht mit Offloading auf einer 24 GB GPU. Q2 ist die einzige Option, die vollständig in VRAM läuft.',
            },
            {
              q: 'Wie langsam ist eine 70B-Modell auf 24 GB VRAM?',
              a: 'Bei Q2 (vollständig in VRAM): 5-8 Token/Sek. Bei Q3 mit 2 GB RAM-Offload: 3-5 Token/Sek. Bei Q4 mit 11 GB RAM-Offload: 1-3 Token/Sek. Vergleichen Sie mit einem 13B-Modell bei Q5 auf der gleichen GPU: 80-100 Token/Sek. Das beschränkte 70B-Setup ist 10-20× langsamer als ein richtig dimensioniertes kleineres Modell.',
            },
            {
              q: 'Ist es besser, ein 13B-Modell statt eines beschränkten 70B zu verwenden?',
              a: 'Für die meisten Aufgaben ja. Ein 13B-Modell bei Q5-Quantisierung läuft auf einer RTX 4090 mit 80-100 Token/Sek. und liefert starke Qualität. Ein 70B-Modell bei Q2 läuft mit 5-8 Token/Sek. mit verminderter Qualität. Das 13B-Modell gewinnt bei Geschwindigkeit und oft bei praktischer Qualität aufgrund von Q2-Verschlechterung. Verwenden Sie 70B-auf-24GB nur, wenn Sie spezifische 70B-Fähigkeiten benötigen und Batch-only-Verwendung tolerieren können.',
            },
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Weiterführendes Material',
          items: [
            '[Local LLM Hardware Guide 2026](/de/local-llms/local-llm-hardware-guide-2026) -- Kaufen Sie bessere Hardware.',
            '[Multi-GPU Local LLMs](/de/local-llms/multi-gpu-local-llms) -- Verwenden Sie statt dessen Layer-Splitting.',
            '[Best Local LLMs for Coding](/de/local-llms/best-local-llms-for-coding) -- Kleinere Modelle sind oft ausreichend.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Quellen',
          items: [
            'llama.cpp Quantisierung -- github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/quants.py',
            'Model Card: Llama 3.3 70B -- huggingface.co/meta-llama/Llama-3.1-70B',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        url: 'https://www.promptquorum.com/de/local-llms/run-70b-models-24gb-vram',
        inLanguage: 'de',
        headline: '70B-Modelle auf 24GB VRAM ausführen: Kompletter Setup-Guide 2026',
        description: '70B-Modelle auf 24GB VRAM 2026: Quantisierung (Q4_K_M), Offloading, Layer-Splitting. Techniken mit Trade-offs und Leistungsdaten.',
        datePublished: '2026-04-04',
        dateModified: '2026-04-19',
        author: { '@type': 'Person', name: 'Hans Kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        proficiencyLevel: 'Advanced',
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'de',
        mainEntity: [
          {
            '@type': 'Question',
            name: 'Kann ich eine 70B-Modell wirklich auf einer einzelnen RTX 4090 ausführen?',
            acceptedAnswer: { '@type': 'Answer', text: 'Ja, aber mit erheblichen Einschränkungen. Bei Q2-Quantisierung (17,5 GB) passt das Modell in 24 GB VRAM, läuft aber mit 5-8 Token/Sek. und hat ~70% der FP16-Qualität. Bei Q4 (35 GB) müssen Sie 11 GB zu System-RAM auslagern, wodurch die Geschwindigkeit auf 1-3 Token/Sek. sinkt.' },
          },
          {
            '@type': 'Question',
            name: 'Welche Quantisierung ist erforderlich, um 70B in 24 GB VRAM zu passen?',
            acceptedAnswer: { '@type': 'Answer', text: 'Q2-Quantisierung passt in 24 GB (17,5 GB Modellgröße). Q3 (26 GB) erfordert 2 GB RAM-Offloading. Q4 (35 GB) erfordert 11 GB Offloading und macht die Inferenz sehr langsam. Q5 und höher können nicht passen, auch nicht mit Offloading. Q2 ist die einzige Option, die vollständig in VRAM läuft.' },
          },
          {
            '@type': 'Question',
            name: 'Wie langsam ist eine 70B-Modell auf 24 GB VRAM?',
            acceptedAnswer: { '@type': 'Answer', text: 'Bei Q2 (vollständig in VRAM): 5-8 Token/Sek. Bei Q3 mit 2 GB RAM-Offload: 3-5 Token/Sek. Bei Q4 mit 11 GB RAM-Offload: 1-3 Token/Sek. Ein 13B-Modell bei Q5 auf der gleichen GPU läuft mit 80-100 Token/Sek. — 10-20× schneller.' },
          },
          {
            '@type': 'Question',
            name: 'Ist es besser, ein 13B-Modell statt eines beschränkten 70B zu verwenden?',
            acceptedAnswer: { '@type': 'Answer', text: 'Für die meisten Aufgaben ja. Ein 13B-Modell bei Q5 läuft auf einer RTX 4090 mit 80-100 Token/Sek. Ein 70B-Modell bei Q2 läuft mit 5-8 Token/Sek. mit verminderter Qualität. Das 13B gewinnt bei Geschwindigkeit und oft bei praktischer Qualität. Verwenden Sie 70B-auf-24GB nur, wenn Sie spezifische 70B-Fähigkeiten benötigen und Batch-only-Verwendung tolerieren können.' },
          },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        inLanguage: 'de',
        name: 'Techniken zum Ausführen von 70B-Modellen auf 24 GB VRAM',
        numberOfItems: 3,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Q2-Quantisierung (17,5 GB)', description: 'Passt vollständig in 24 GB VRAM. Qualität: ~70% von FP16. Geschwindigkeit: 5-8 Token/Sek.' },
          { '@type': 'ListItem', position: 2, name: 'Q4 + CPU-Offloading (11 GB ausgelagert)', description: 'Bessere Qualität, aber sehr langsam: 1-3 Token/Sek. Nur für Overnight-Batch geeignet.' },
          { '@type': 'ListItem', position: 3, name: 'Layer-Splitting (2× RTX 4090)', description: 'Beste Option: 48 GB gesamt, läuft Q5 mit ~100 Token/Sek. Empfohlen statt Single-GPU-Constraint.' },
        ],
      },
    },
    fr: {
      freshness_tier: 'semi_annual',
      theme: 'Hardware & Performance',
      title: 'Exécuter des modèles 70B sur 24 Go de VRAM : Techniques avancées',
      seoTitle: 'Exécuter des modèles 70B sur 24 Go de VRAM : Guide complet 2026',
      intro: 'Exécuter un modèle 70B (nécessite normalement 40+ Go) sur 24 Go de VRAM est possible avec une quantification agressive (Q2-Q3) et un déchargement de couches, mais le résultat est lent (~3-5 tokens/sec). Depuis avril 2026, c\'est peu pratique pour le chat en temps réel, mais viable pour le traitement par lot ou les expériences.',
      metaDescription: 'Modèles 70B sur 24 Go de VRAM 2026 : quantification (Q4_K_M), déchargement, division de couches. Techniques avec compromis et données de performance.',
      publishDate: '2026-04-04',
      dateModified: '2026-04-19',
      leadAnswerBlock: '**Exécuter un modèle 70B (nécessite normalement 40+ Go) sur 24 Go de VRAM est possible avec une quantification agressive (Q2-Q3) et un déchargement de couches, mais le résultat est lent (~3-5 tokens/sec).**',
      audience: 'Ingénieurs déployer des LLMs locaux dans des environnements de production ou d\'entreprise',
      readTime: '10 min de lecture',
      educationalLevel: 'Advanced',
      primaryTerm: 'Optimisation modèle 70B',
      toc: [
        { label: 'Points clés', anchor: '#key-takeaways' },
        { label: 'Limites théoriques', anchor: '#limits' },
        { label: 'Stratégie de quantification', anchor: '#quantization' },
        { label: 'Stratégie de déchargement', anchor: '#offloading' },
        { label: 'Configuration pratique', anchor: '#setup' },
        { label: 'Performance réaliste', anchor: '#performance' },
        { label: 'Meilleures alternatives', anchor: '#alternatives' },
        { label: 'Erreurs courantes', anchor: '#common-mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Lectures connexes', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            'Llama 3.3 70B en Q4 = 35 Go (trop grand pour 24 Go). En Q3 = 26 Go (toujours trop). En Q2 = 17 Go (convient!).',
            'Compromis : Q2 a une dégradation notable de qualité. ~70% de la qualité FP16.',
            'Vitesse : 3-5 tokens/sec avec 20 Go déchargé sur RAM système (ultra-lent).',
            'Meilleure option : utiliser un modèle 13B en Q5, ou acheter un GPU secondaire pour la division de couches.',
            'Depuis avril 2026, c\'est une solution de contournement, pas une approche recommandée.',
          ],
        },
        limits: {
          id: 'limits',
          title: 'Les mathématiques théoriques du VRAM',
          content: [
            '**Llama 3.3 70B à différentes quantifications :**',
          ],
          rows: [
            { 'Quantification': 'FP16 (baseline)', 'Taille': '140 Go', 'Convient en 24 Go?': 'Non' },
            { 'Quantification': 'Q8 (8-bit)', 'Taille': '70 Go', 'Convient en 24 Go?': 'Non' },
            { 'Quantification': 'Q5 (5-bit)', 'Taille': '43.75 Go', 'Convient en 24 Go?': 'Non' },
            { 'Quantification': 'Q4 (4-bit)', 'Taille': '35 Go', 'Convient en 24 Go?': 'Non (avec déchargement : peut-être)' },
            { 'Quantification': 'Q3 (3-bit)', 'Taille': '26 Go', 'Convient en 24 Go?': 'Non (juste)' },
            { 'Quantification': 'Q2 (2-bit)', 'Taille': '17.5 Go', 'Convient en 24 Go?': 'Oui' },
          ],
          columns: ['Quantification', 'Taille du modèle', 'Convient en 24 Go?'],
        },
        quantization: {
          id: 'quantization',
          title: 'Quantification agressive : l\'outil principal',
          content: [
            '**Pour adapter 70B à 24 Go, vous devez utiliser la quantification Q2 ou Q3.**',
            '- **Q3** : 26 Go (encore 2 Go de plus). Peut décharger 2 Go vers la RAM. Qualité légèrement meilleure que Q2.',
            '- **Q2** : 17.5 Go (convient!). 70% de qualité par rapport à FP16. Dégradation notable mais utilisable.',
            'Téléchargez le modèle quantifié : `ollama pull llama3.1:70b-q2` (si disponible) ou utilisez des outils de conversion comme llama.cpp.',
          ],
        },
        offloading: {
          id: 'offloading',
          title: 'Déchargement vers la RAM système',
          content: [
            '**Si vous utilisez Q4 (35 Go) sur un GPU 24 Go, vous pouvez décharger les 11 Go restants vers la RAM système.** La pénalité de vitesse est sévère (10× plus lent).',
            'Pratique uniquement pour le traitement par lot où vous pouvez attendre des heures.',
          ],
        },
        setup: {
          id: 'setup',
          title: 'Configuration pratique : exécuter 70B sur 24 Go',
          content: 'Étape par étape :',
          numberedItems: [
            'Utilisez la quantification Q2 : `ollama pull llama3.1:70b-q2` (si disponible, sinon convertir avec llama.cpp)',
            'Vérifiez le VRAM : `nvidia-smi` devrait afficher ~18 Go utilisés',
            'Exécutez le modèle : `ollama run llama3.1:70b-q2`',
            'Attendez-vous à 3-5 tokens/sec (très lent)',
            'Utilisez uniquement pour le traitement par lot hors ligne, pas pour le chat interactif',
          ],
        },
        performance: {
          id: 'performance',
          title: 'Attentes réalistes de performance',
          content: [
            '**Exécuter 70B sur 24 Go de VRAM est lent :**',
          ],
          rows: [
            { 'Quantification': 'Q2 (24 Go VRAM)', 'Vitesse': '5-8 tok/sec', 'Latence': '2-4 sec par token', 'Cas d\'usage': 'Traitement par lot uniquement' },
            { 'Quantification': 'Q3 + déchargement (24 Go)', 'Vitesse': '3-5 tok/sec', 'Latence': '3-5 sec par token', 'Cas d\'usage': 'Extrêmement limité' },
            { 'Quantification': 'Q4 + déchargement (24 Go)', 'Vitesse': '1-3 tok/sec', 'Latence': '5-10 sec par token', 'Cas d\'usage': 'Uniquement batch nocturne' },
          ],
          columns: ['Quantification', 'Vitesse', 'Latence', 'Cas d\'usage'],
        },
        alternatives: {
          id: 'alternatives',
          title: 'Meilleures alternatives à un 70B contraint',
          content: 'Au lieu de vous débattre avec un 70B avec VRAM limité, considérez :',
          items: [
            'Utiliser un modèle 13B (Llama 3.3 13B en Q5 = 8 Go, très rapide)',
            'Acheter un GPU RTX 4090 secondaire pour la division de couches (2× 24 Go = 48 Go, 100+ tokens/sec)',
            'Utiliser une API cloud (GPT-5.5 pour les tâches importantes, local pour les expériences)',
            'Attendre des modèles plus efficaces (plus petit, même qualité)',
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: 'Erreurs courantes avec un 70B contraint',
          items: [
            '**S\'attendre à ce que Q2 soit utilisable pour le chat.** Ce n\'est pas le cas. La dégradation de qualité est trop grave pour l\'interaction en temps réel.',
            '**Ne pas mesurer la vitesse réelle à l\'avance.** Testez avec un petit prompt (10 tokens) et vérifiez la vitesse avant d\'exécuter de grands travaux par lot.',
            '**Supposer que le déchargement est "gratuit".** La RAM système est 100× plus lente que le VRAM du GPU. Le déchargement rend l\'inférence peu pratique.',
            '**Ne pas considérer les alternatives.** Un modèle 13B est dramatiquement plus rapide et souvent suffisant en qualité.',
          ],
        },
        faqSection: {
          id: 'faq',
          title: 'Questions fréquemment posées',
          faqs: [
            {
              q: 'Puis-je vraiment exécuter un modèle 70B sur une seule RTX 4090?',
              a: 'Oui, mais avec des réserves importantes. En quantification Q2 (17.5 Go), le modèle convient en 24 Go de VRAM mais fonctionne à 5-8 tokens/sec et a ~70% de la qualité FP16. En Q4 (35 Go), vous devez décharger 11 Go vers la RAM système, réduisant la vitesse à 1-3 tokens/sec. Aucun n\'est adapté au chat en temps réel — seulement pour le traitement par lot hors ligne.',
            },
            {
              q: 'Quelle quantification est nécessaire pour adapter 70B à 24 Go de VRAM?',
              a: 'La quantification Q2 convient en 24 Go (taille du modèle 17.5 Go). Q3 (26 Go) nécessite 2 Go de déchargement RAM. Q4 (35 Go) nécessite 11 Go de déchargement et rend l\'inférence très lente. Q5 et supérieur (44-70 Go) ne peuvent pas convenir même avec déchargement sur un GPU 24 Go. Q2 est la seule option qui fonctionne entièrement en VRAM.',
            },
            {
              q: 'Quelle est la lenteur d\'un modèle 70B sur 24 Go de VRAM?',
              a: 'En Q2 (entièrement en VRAM) : 5-8 tokens/sec. En Q3 avec 2 Go de déchargement RAM : 3-5 tokens/sec. En Q4 avec 11 Go de déchargement RAM : 1-3 tokens/sec. Comparez avec un modèle 13B en Q5 sur le même GPU : 80-100 tokens/sec. La configuration 70B contrainte est 10-20× plus lente qu\'un modèle plus petit correctement dimensionné.',
            },
            {
              q: 'Est-il préférable d\'utiliser un modèle 13B plutôt qu\'un 70B contraint?',
              a: 'Pour la plupart des tâches, oui. Un modèle 13B en quantification Q5 fonctionne à 80-100 tokens/sec sur une RTX 4090 et offre une qualité forte. Un modèle 70B en Q2 fonctionne à 5-8 tokens/sec avec une qualité réduite. Le 13B gagne en vitesse et souvent en qualité pratique due à la dégradation Q2. Utilisez 70B-sur-24 Go uniquement si vous avez besoin de capacités spécifiques au 70B et pouvez tolérer une utilisation par lot uniquement.',
            },
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Lectures connexes',
          items: [
            '[Local LLM Hardware Guide 2026](/fr/local-llms/local-llm-hardware-guide-2026) -- Achetez du meilleur matériel.',
            '[Multi-GPU Local LLMs](/fr/local-llms/multi-gpu-local-llms) -- Utilisez plutôt la division de couches.',
            '[Best Local LLMs for Coding](/fr/local-llms/best-local-llms-for-coding) -- Les modèles plus petits suffisent souvent.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Sources',
          items: [
            'Quantification llama.cpp -- github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/quants.py',
            'Carte modèle : Llama 3.3 70B -- huggingface.co/meta-llama/Llama-3.1-70B',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        url: 'https://www.promptquorum.com/fr/local-llms/run-70b-models-24gb-vram',
        inLanguage: 'fr',
        headline: 'Exécuter des modèles 70B sur 24 Go de VRAM : Guide complet 2026',
        description: 'Modèles 70B sur 24 Go de VRAM 2026 : quantification (Q4_K_M), déchargement, division de couches. Techniques avec compromis et données de performance.',
        datePublished: '2026-04-04',
        dateModified: '2026-04-19',
        author: { '@type': 'Person', name: 'Hans Kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        proficiencyLevel: 'Advanced',
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'fr',
        mainEntity: [
          {
            '@type': 'Question',
            name: 'Puis-je vraiment exécuter un modèle 70B sur une seule RTX 4090?',
            acceptedAnswer: { '@type': 'Answer', text: 'Oui, mais avec des réserves importantes. En quantification Q2 (17.5 Go), le modèle convient en 24 Go de VRAM mais fonctionne à 5-8 tokens/sec et a ~70% de la qualité FP16. En Q4 (35 Go), vous devez décharger 11 Go vers la RAM système, réduisant la vitesse à 1-3 tokens/sec.' },
          },
          {
            '@type': 'Question',
            name: 'Quelle quantification est nécessaire pour adapter 70B à 24 Go de VRAM?',
            acceptedAnswer: { '@type': 'Answer', text: 'La quantification Q2 convient en 24 Go (taille du modèle 17.5 Go). Q3 (26 Go) nécessite 2 Go de déchargement RAM. Q4 (35 Go) nécessite 11 Go de déchargement et rend l\'inférence très lente. Q5 et supérieur ne peuvent pas convenir même avec déchargement. Q2 est la seule option qui fonctionne entièrement en VRAM.' },
          },
          {
            '@type': 'Question',
            name: 'Quelle est la lenteur d\'un modèle 70B sur 24 Go de VRAM?',
            acceptedAnswer: { '@type': 'Answer', text: 'En Q2 (entièrement en VRAM) : 5-8 tokens/sec. En Q3 avec 2 Go de déchargement RAM : 3-5 tokens/sec. En Q4 avec 11 Go de déchargement RAM : 1-3 tokens/sec. Un modèle 13B en Q5 sur le même GPU fonctionne à 80-100 tokens/sec — 10-20× plus rapide.' },
          },
          {
            '@type': 'Question',
            name: 'Est-il préférable d\'utiliser un modèle 13B plutôt qu\'un 70B contraint?',
            acceptedAnswer: { '@type': 'Answer', text: 'Pour la plupart des tâches, oui. Un modèle 13B en Q5 fonctionne à 80-100 tokens/sec sur une RTX 4090. Un modèle 70B en Q2 fonctionne à 5-8 tokens/sec avec une qualité réduite. Le 13B gagne en vitesse et souvent en qualité pratique. Utilisez 70B-sur-24 Go uniquement si vous avez besoin de capacités spécifiques et pouvez tolérer une utilisation par lot uniquement.' },
          },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        inLanguage: 'fr',
        name: 'Techniques pour exécuter des modèles 70B sur 24 Go de VRAM',
        numberOfItems: 3,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Quantification Q2 (17.5 Go)', description: 'Convient entièrement en 24 Go de VRAM. Qualité : ~70% de FP16. Vitesse : 5-8 tokens/sec.' },
          { '@type': 'ListItem', position: 2, name: 'Q4 + Déchargement CPU (11 Go déchargé)', description: 'Meilleure qualité mais très lent : 1-3 tokens/sec. Adapté uniquement pour le lot nocturne.' },
          { '@type': 'ListItem', position: 3, name: 'Division de couches (2× RTX 4090)', description: 'Meilleure option : 48 Go total, exécute Q5 à ~100 tokens/sec. Recommandé plutôt qu\'une contrainte single-GPU.' },
        ],
      },
    },
    ja: {
      freshness_tier: 'semi_annual',
      theme: 'Hardware & Performance',
      title: '24GB VRAMで70Bモデルを実行: 高度なテクニック',
      seoTitle: '24GB VRAMで70Bモデルを実行: 完全セットアップガイド 2026',
      intro: '70Bモデル（通常40GB以上必要）を24GB VRAMで実行することは、積極的な量子化（Q2-Q3）とレイヤーオフロードで可能ですが、結果は遅い（〜3-5 tokens/秒）。2026年4月現在、リアルタイムチャットには非実用的ですが、バッチ処理または実験用途には実行可能です。',
      metaDescription: '24GB VRAMで70Bモデル 2026: 量子化（Q4_K_M）、オフロード、レイヤー分割。トレードオフとパフォーマンスデータを含むテクニック。',
      publishDate: '2026-04-04',
      dateModified: '2026-04-19',
      leadAnswerBlock: '**70Bモデル（通常40GB以上必要）を24GB VRAMで実行することは、積極的な量子化（Q2-Q3）とレイヤーオフロードで可能ですが、結果は遅い（〜3-5 tokens/秒）。**',
      audience: '本番環境またはエンタープライズ環境にローカルLLMsをデプロイするエンジニア',
      readTime: '10分で読める',
      educationalLevel: 'Advanced',
      primaryTerm: '70Bモデル最適化',
      toc: [
        { label: '重要ポイント', anchor: '#key-takeaways' },
        { label: '理論的な限界', anchor: '#limits' },
        { label: '量子化戦略', anchor: '#quantization' },
        { label: 'オフロード戦略', anchor: '#offloading' },
        { label: '実践的なセットアップ', anchor: '#setup' },
        { label: '現実的なパフォーマンス', anchor: '#performance' },
        { label: 'より良い代替案', anchor: '#alternatives' },
        { label: 'よくある間違い', anchor: '#common-mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: '関連資料', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            'Llama 3.3 70B Q4時 = 35GB（24GBには大きすぎる）。Q3 = 26GB（依然として大きい）。Q2 = 17GB（適切！）。',
            'トレードオフ: Q2は著しい品質低下。〜70% のFP16品質。',
            '速度: システムRAMに20GBをオフロードして3-5 tokens/秒（超遅い）。',
            'より良い選択肢: Q5で13Bモデルを使用、またはレイヤー分割用に2番目のGPUを購入。',
            '2026年4月現在、これは制約回避策であり、推奨されるアプローチではありません。',
          ],
        },
        limits: {
          id: 'limits',
          title: '理論的なVRAM計算',
          content: [
            '**様々な量子化レベルでのLlama 3.3 70B:**',
          ],
          rows: [
            { '量子化': 'FP16（ベースライン）', 'サイズ': '140GB', '24GBに適合？': 'いいえ' },
            { '量子化': 'Q8（8ビット）', 'サイズ': '70GB', '24GBに適合？': 'いいえ' },
            { '量子化': 'Q5（5ビット）', 'サイズ': '43.75GB', '24GBに適合？': 'いいえ' },
            { '量子化': 'Q4（4ビット）', 'サイズ': '35GB', '24GBに適合？': 'いいえ（オフロード時：おそらく）' },
            { '量子化': 'Q3（3ビット）', 'サイズ': '26GB', '24GBに適合？': 'いいえ（辛うじて）' },
            { '量子化': 'Q2（2ビット）', 'サイズ': '17.5GB', '24GBに適合？': 'はい' },
          ],
          columns: ['量子化', 'モデルサイズ', '24GBに適合？'],
        },
        quantization: {
          id: 'quantization',
          title: '積極的な量子化：主要ツール',
          content: [
            '**70Bを24GBに適合させるにはQ2またはQ3量子化を使用する必要があります。**',
            '- **Q3**: 26GB（まだ2GB超過）。2GBをRAMにオフロード可能。Q2より若干品質が良い。',
            '- **Q2**: 17.5GB（適切！）。FP16比較で70%品質。著しい低下だが使用可能。',
            '量子化済みモデルをダウンロード: `ollama pull llama3.1:70b-q2`（利用可能な場合）またはllama.cppなどの変換ツールを使用。',
          ],
        },
        offloading: {
          id: 'offloading',
          title: 'システムRAMへのオフロード',
          content: [
            '**24GB GPUでQ4（35GB）を使用する場合、残りの11GBをシステムRAMにオフロード可能。** 速度ペナルティは重大（10倍遅い）。',
            '数時間待機可能なバッチ処理でのみ実用的。',
          ],
        },
        setup: {
          id: 'setup',
          title: '実践的なセットアップ: 24GBで70Bを実行',
          content: 'ステップバイステップ:',
          numberedItems: [
            'Q2量子化を使用: `ollama pull llama3.1:70b-q2`（利用可能な場合、それ以外はllama.cppで変換）',
            'VRAMを確認: `nvidia-smi`は〜18GB使用を表示すべき',
            'モデルを実行: `ollama run llama3.1:70b-q2`',
            '3-5 tokens/秒を予想（非常に遅い）',
            'バッチ/オフライン処理のみに使用、インタラクティブチャットには使用しない',
          ],
        },
        performance: {
          id: 'performance',
          title: '現実的なパフォーマンス期待値',
          content: [
            '**24GB VRAMで70Bを実行するのは遅い:**',
          ],
          rows: [
            { '量子化': 'Q2（24GB VRAM）', '速度': '5-8 tok/秒', 'レイテンシ': 'トークンあたり2-4秒', 'ユースケース': 'バッチ処理のみ' },
            { '量子化': 'Q3 + オフロード（24GB）', '速度': '3-5 tok/秒', 'レイテンシ': 'トークンあたり3-5秒', 'ユースケース': '極度に制限' },
            { '量子化': 'Q4 + オフロード（24GB）', '速度': '1-3 tok/秒', 'レイテンシ': 'トークンあたり5-10秒', 'ユースケース': '深夜バッチのみ' },
          ],
          columns: ['量子化', '速度', 'レイテンシ', 'ユースケース'],
        },
        alternatives: {
          id: 'alternatives',
          title: '制約付き70Bの代替案',
          content: 'VRAM制限で70Bと格闘する代わりに、以下を検討してください:',
          items: [
            '13Bモデルを使用（Llama 3.3 13B Q5 = 8GB、非常に高速）',
            'レイヤー分割用に2番目のRTX 4090を購入（2× 24GB = 48GB、100+ tokens/秒）',
            'クラウドAPIを使用（重要なタスク用GPT-5.5、実験用ローカル）',
            'より効率的なモデル待機（より小さい、同じ品質）',
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: '制約付き70Bでのよくある間違い',
          items: [
            '**Q2がチャット用に使用可能だと予想。** そうではありません。品質低下はリアルタイムインタラクションには深刻すぎる。',
            '**事前に実際の速度を測定しない。** 大きなバッチジョブを実行する前に、小さいプロンプト（10トークン）でテストし、速度を確認。',
            '**オフロードが「無料」だと想定。** システムRAMはGPU VRAMより100倍遅い。オフロードは推論を非実用的にする。',
            '**代替案を検討しない。** 13Bモデルは劇的に高速で、品質でしばしば十分。',
          ],
        },
        faqSection: {
          id: 'faq',
          title: 'よくある質問',
          faqs: [
            {
              q: '本当に単一のRTX 4090で70Bモデルを実行できますか？',
              a: 'はい、ただし重大な注意事項があります。Q2量子化（17.5GB）では、モデルは24GB VRAMに適合しますが、5-8 tokens/秒で実行され、〜70% のFP16品質があります。Q4（35GB）では、11GBをシステムRAMにオフロードする必要があり、速度は1-3 tokens/秒に低下します。どちらもリアルタイムチャットには適さず、オフラインバッチ処理のみ。',
            },
            {
              q: '70Bを24GB VRAMに適合させるために必要な量子化は？',
              a: 'Q2量子化は24GBに適合（17.5GBモデルサイズ）。Q3（26GB）は2GBのRAMオフロードが必要。Q4（35GB）は11GBのオフロードが必要で推論は非常に遅い。Q5以上（44-70GB）は24GB GPUでのオフロードでさえ適合不可。Q2がVRAMで完全に実行される唯一の選択肢。',
            },
            {
              q: '24GB VRAMで70Bモデルはどの程度遅いですか？',
              a: 'Q2（VRAM内完全）: 5-8 tokens/秒。Q3（2GB RAMオフロード）: 3-5 tokens/秒。Q4（11GB RAMオフロード）: 1-3 tokens/秒。同じGPU上のQ5での13Bモデルと比較: 80-100 tokens/秒。制約付き70Bセットアップは適切にサイズされた小さいモデルより10-20倍遅い。',
            },
            {
              q: '制約付き70Bより13Bモデルを使用する方が良いですか？',
              a: 'ほとんどのタスクではい。Q5量子化での13Bモデルはアップル4090で80-100 tokens/秒で実行され、強力な品質を提供します。Q2での70Bモデルは5-8 tokens/秒で品質が低下します。13BはQ2劣化による速度と実用品質の両方で勝利。特定の70B機能が必要で、バッチのみ使用を許容できる場合のみ70B-on-24GB使用。',
            },
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: '関連資料',
          items: [
            '[Local LLM Hardware Guide 2026](/ja/local-llms/local-llm-hardware-guide-2026) -- より良いハードウェアを購入。',
            '[Multi-GPU Local LLMs](/ja/local-llms/multi-gpu-local-llms) -- 代わりにレイヤー分割を使用。',
            '[Best Local LLMs for Coding](/ja/local-llms/best-local-llms-for-coding) -- より小さいモデルはしばしば十分。',
          ],
        },
        sources: {
          id: 'sources',
          title: 'ソース',
          items: [
            'llama.cpp量子化 -- github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/quants.py',
            'モデルカード: Llama 3.3 70B -- huggingface.co/meta-llama/Llama-3.1-70B',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        url: 'https://www.promptquorum.com/ja/local-llms/run-70b-models-24gb-vram',
        inLanguage: 'ja',
        headline: '24GB VRAMで70Bモデルを実行: 完全セットアップガイド 2026',
        description: '24GB VRAMで70Bモデル 2026: 量子化（Q4_K_M）、オフロード、レイヤー分割。トレードオフとパフォーマンスデータを含むテクニック。',
        datePublished: '2026-04-04',
        dateModified: '2026-04-19',
        author: { '@type': 'Organization', name: 'PromptQuorum' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        proficiencyLevel: 'Advanced',
        about: [
          { '@type': 'Thing', name: 'Llama 3.3' },
          { '@type': 'Thing', name: '70Bモデル' },
          { '@type': 'Thing', name: 'VRAM最適化' },
        ],
        speakable: {
          '@type': 'SpeakableSpecification',
          cssSelector: ['.article-intro', '.key-takeaways'],
        },
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'ja',
        mainEntity: [
          {
            '@type': 'Question',
            name: '本当に単一のRTX 4090で70Bモデルを実行できますか？',
            acceptedAnswer: { '@type': 'Answer', text: 'はい、ただし重大な注意事項があります。Q2量子化（17.5GB）では、モデルは24GB VRAMに適合しますが、5-8 tokens/秒で実行され、〜70% のFP16品質があります。Q4（35GB）では、11GBをシステムRAMにオフロードする必要があります。' },
          },
          {
            '@type': 'Question',
            name: '70Bを24GB VRAMに適合させるために必要な量子化は？',
            acceptedAnswer: { '@type': 'Answer', text: 'Q2量子化は24GBに適合（17.5GBモデルサイズ）。Q3（26GB）は2GBのRAMオフロードが必要。Q4（35GB）は11GBのオフロードが必要で推論は非常に遅い。Q5以上は24GB GPUでは適合不可。Q2がVRAMで完全に実行される唯一の選択肢。' },
          },
          {
            '@type': 'Question',
            name: '24GB VRAMで70Bモデルはどの程度遅いですか？',
            acceptedAnswer: { '@type': 'Answer', text: 'Q2（VRAM内完全）: 5-8 tokens/秒。Q3（2GB RAMオフロード）: 3-5 tokens/秒。Q4（11GB RAMオフロード）: 1-3 tokens/秒。同じGPU上のQ5での13Bモデル: 80-100 tokens/秒。制約付き70BセットアップはQ2劣化により10-20倍遅い。' },
          },
          {
            '@type': 'Question',
            name: '制約付き70Bより13Bモデルを使用する方が良いですか？',
            acceptedAnswer: { '@type': 'Answer', text: 'ほとんどのタスクではい。Q5での13Bはアップル4090で80-100 tokens/秒で実行され強力な品質。Q2での70Bは5-8 tokens/秒で品質低下。13Bが速度と実用品質で勝利。特定の70B機能が必要で、バッチのみ使用を許容できる場合のみ70B-on-24GB使用。' },
          },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        inLanguage: 'ja',
        name: '24GB VRAMで70Bモデルを実行するテクニック',
        numberOfItems: 3,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Q2量子化（17.5GB）', description: '24GB VRAMに完全に適合。品質：〜70% のFP16。速度：5-8 tokens/秒。' },
          { '@type': 'ListItem', position: 2, name: 'Q4 + CPUオフロード（11GB オフロード）', description: 'より良い品質だが非常に遅い：1-3 tokens/秒。深夜バッチのみに適した。' },
          { '@type': 'ListItem', position: 3, name: 'レイヤー分割（2× RTX 4090）', description: '最良の選択肢：48GB合計、Q5を〜100 tokens/秒で実行。シングルGPU制約より推奨。' },
        ],
      },
    },
    zh: {
      freshness_tier: 'semi_annual',
      theme: 'Hardware & Performance',
      title: '在24GB VRAM上运行70B模型：高级技术',
      seoTitle: '在24GB VRAM上运行70B模型：完整设置指南2026',
      intro: '在24GB VRAM上运行70B模型（通常需要40GB以上）是可能的，使用积极量化（Q2-Q3）和层卸载，但结果较慢（约3-5 tokens/秒）。截至2026年4月，这对实时聊天不实用，但适用于批处理或实验。',
      metaDescription: '24GB VRAM上的70B模型2026：量化（Q4_K_M）、卸载、层分割。含权衡和性能数据的技术。',
      publishDate: '2026-04-04',
      dateModified: '2026-04-19',
      leadAnswerBlock: '**在24GB VRAM上运行70B模型（通常需要40GB以上）是可能的，使用积极量化（Q2-Q3）和层卸载，但结果较慢（约3-5 tokens/秒）。**',
      audience: '在生产或企业环境中部署本地LLMs的工程师',
      readTime: '阅读约10分钟',
      educationalLevel: 'Advanced',
      primaryTerm: '70B模型优化',
      toc: [
        { label: '关键点', anchor: '#key-takeaways' },
        { label: '理论限制', anchor: '#limits' },
        { label: '量化策略', anchor: '#quantization' },
        { label: '卸载策略', anchor: '#offloading' },
        { label: '实际设置', anchor: '#setup' },
        { label: '现实性能', anchor: '#performance' },
        { label: '更好的替代方案', anchor: '#alternatives' },
        { label: '常见错误', anchor: '#common-mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: '相关阅读', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            'Llama 3.3 70B Q4 = 35GB（对24GB来说太大）。Q3 = 26GB（仍然太大）。Q2 = 17GB（合适！）。',
            '权衡：Q2有明显质量下降。约70%的FP16质量。',
            '速度：卸载20GB到系统RAM时3-5 tokens/秒（超级慢）。',
            '更好选项：使用Q5的13B模型，或购买第二个GPU用于层分割。',
            '截至2026年4月，这是约束解决方法，不是推荐方法。',
          ],
        },
        limits: {
          id: 'limits',
          title: '理论VRAM数学',
          content: [
            '**不同量化级别的Llama 3.3 70B:**',
          ],
          rows: [
            { '量化': 'FP16（基准）', '大小': '140GB', '适合24GB？': '否' },
            { '量化': 'Q8（8位）', '大小': '70GB', '适合24GB？': '否' },
            { '量化': 'Q5（5位）', '大小': '43.75GB', '适合24GB？': '否' },
            { '量化': 'Q4（4位）', '大小': '35GB', '适合24GB？': '否（卸载时：可能）' },
            { '量化': 'Q3（3位）', '大小': '26GB', '适合24GB？': '否（勉强）' },
            { '量化': 'Q2（2位）', '大小': '17.5GB', '适合24GB？': '是' },
          ],
          columns: ['量化', '模型大小', '适合24GB？'],
        },
        quantization: {
          id: 'quantization',
          title: '积极量化：主要工具',
          content: [
            '**要使70B适合24GB，必须使用Q2或Q3量化。**',
            '- **Q3**：26GB（仍然超2GB）。可卸载2GB到RAM。质量略好于Q2。',
            '- **Q2**：17.5GB（合适！）。相对FP16质量70%。明显下降但可用。',
            '下载量化模型：`ollama pull llama3.1:70b-q2`（如果可用）或使用llama.cpp等转换工具。',
          ],
        },
        offloading: {
          id: 'offloading',
          title: '卸载到系统RAM',
          content: [
            '**在24GB GPU上使用Q4（35GB）时，可卸载剩余11GB到系统RAM。** 速度惩罚严重（10倍慢）。',
            '仅适用于可等待数小时的批处理。',
          ],
        },
        setup: {
          id: 'setup',
          title: '实际设置：在24GB上运行70B',
          content: '逐步：',
          numberedItems: [
            '使用Q2量化：`ollama pull llama3.1:70b-q2`（如果可用，否则用llama.cpp转换）',
            '检查VRAM：`nvidia-smi`应显示约18GB使用',
            '运行模型：`ollama run llama3.1:70b-q2`',
            '预期3-5 tokens/秒（非常慢）',
            '仅用于批处理/离线处理，不用于交互聊天',
          ],
        },
        performance: {
          id: 'performance',
          title: '现实性能期望',
          content: [
            '**在24GB VRAM上运行70B很慢:**',
          ],
          rows: [
            { '量化': 'Q2（24GB VRAM）', '速度': '5-8 tok/秒', '延迟': '每token 2-4秒', '用例': '仅批处理' },
            { '量化': 'Q3 + 卸载（24GB）', '速度': '3-5 tok/秒', '延迟': '每token 3-5秒', '用例': '极度受限' },
            { '量化': 'Q4 + 卸载（24GB）', '速度': '1-3 tok/秒', '延迟': '每token 5-10秒', '用例': '仅深夜批处理' },
          ],
          columns: ['量化', '速度', '延迟', '用例'],
        },
        alternatives: {
          id: 'alternatives',
          title: '受限70B的更好替代方案',
          content: '与其与受限VRAM的70B搏斗，考虑：',
          items: [
            '使用13B模型（Llama 3.3 13B Q5 = 8GB，非常快）',
            '购买第二个RTX 4090用于层分割（2× 24GB = 48GB，100+ tokens/秒）',
            '使用云API（重要任务用GPT-5.5，实验用本地）',
            '等待更高效模型（更小，相同质量）',
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: '受限70B的常见错误',
          items: [
            '**预期Q2适用于聊天。** 不是。质量下降对实时交互过于严重。',
            '**事先不测量实际速度。** 在运行大型批处理前用小提示（10 token）测试并验证速度。',
            '**假设卸载"免费"。** 系统RAM比GPU VRAM慢100倍。卸载使推理不实用。',
            '**不考虑替代方案。** 13B模型快得多，质量通常充分。',
          ],
        },
        faqSection: {
          id: 'faq',
          title: '常见问题',
          faqs: [
            {
              q: '我真的能在单个RTX 4090上运行70B模型吗？',
              a: '是的，但有重大注意事项。在Q2量化（17.5GB）处，模型适合24GB VRAM但以5-8 tokens/秒运行且质量约70% FP16。在Q4（35GB）处，需卸载11GB到系统RAM，速度降至1-3 tokens/秒。两者都不适合实时聊天——仅离线批处理。',
            },
            {
              q: '什么量化需要使70B适合24GB VRAM？',
              a: 'Q2量化适合24GB（17.5GB模型大小）。Q3（26GB）需2GB RAM卸载。Q4（35GB）需11GB卸载且推理非常慢。Q5及以上（44-70GB）即使卸载也不能适合24GB GPU。Q2是唯一在VRAM中完全运行的选项。',
            },
            {
              q: '24GB VRAM上的70B模型有多慢？',
              a: 'Q2（完全在VRAM）：5-8 tokens/秒。Q3（2GB RAM卸载）：3-5 tokens/秒。Q4（11GB RAM卸载）：1-3 tokens/秒。相比同GPU上Q5的13B模型：80-100 tokens/秒。受限70B设置比适当大小的小模型慢10-20倍。',
            },
            {
              q: '使用13B模型而非受限70B更好吗？',
              a: '对大多数任务是。Q5量化的13B模型在RTX 4090上以80-100 tokens/秒运行且提供强质量。Q2的70B模型以5-8 tokens/秒运行质量降低。13B在速度和通常实用质量上赢得胜利。仅在需要特定70B能力且可容忍仅批处理使用时使用70B-on-24GB。',
            },
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: '相关阅读',
          items: [
            '[Local LLM Hardware Guide 2026](/zh/local-llms/local-llm-hardware-guide-2026) -- 购买更好硬件。',
            '[Multi-GPU Local LLMs](/zh/local-llms/multi-gpu-local-llms) -- 改用层分割。',
            '[Best Local LLMs for Coding](/zh/local-llms/best-local-llms-for-coding) -- 较小模型通常足够。',
          ],
        },
        sources: {
          id: 'sources',
          title: '来源',
          items: [
            'llama.cpp量化 -- github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/quants.py',
            '模型卡：Llama 3.3 70B -- huggingface.co/meta-llama/Llama-3.1-70B',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        url: 'https://www.promptquorum.com/zh/local-llms/run-70b-models-24gb-vram',
        inLanguage: 'zh',
        headline: '在24GB VRAM上运行70B模型：完整设置指南2026',
        description: '24GB VRAM上的70B模型2026：量化（Q4_K_M）、卸载、层分割。含权衡和性能数据的技术。',
        datePublished: '2026-04-04',
        dateModified: '2026-04-19',
        author: { '@type': 'Organization', name: 'PromptQuorum' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        proficiencyLevel: 'Advanced',
        about: [
          { '@type': 'Thing', name: 'Llama 3.3' },
          { '@type': 'Thing', name: '70B模型' },
          { '@type': 'Thing', name: 'VRAM优化' },
        ],
        speakable: {
          '@type': 'SpeakableSpecification',
          cssSelector: ['.article-intro', '.key-takeaways'],
        },
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'zh',
        mainEntity: [
          {
            '@type': 'Question',
            name: '我真的能在单个RTX 4090上运行70B模型吗？',
            acceptedAnswer: { '@type': 'Answer', text: '是的，但有重大注意事项。在Q2量化（17.5GB）处，模型适合24GB VRAM但以5-8 tokens/秒运行且质量约70% FP16。在Q4（35GB）处，需卸载11GB到系统RAM，速度降至1-3 tokens/秒。两者都不适合实时聊天。' },
          },
          {
            '@type': 'Question',
            name: '什么量化需要使70B适合24GB VRAM？',
            acceptedAnswer: { '@type': 'Answer', text: 'Q2量化适合24GB（17.5GB模型大小）。Q3（26GB）需2GB RAM卸载。Q4（35GB）需11GB卸载且推理非常慢。Q5及以上不能适合24GB GPU。Q2是唯一在VRAM中完全运行的选项。' },
          },
          {
            '@type': 'Question',
            name: '24GB VRAM上的70B模型有多慢？',
            acceptedAnswer: { '@type': 'Answer', text: 'Q2（完全在VRAM）：5-8 tokens/秒。Q3（2GB RAM卸载）：3-5 tokens/秒。Q4（11GB RAM卸载）：1-3 tokens/秒。同GPU上Q5的13B模型：80-100 tokens/秒。受限70B设置比小模型慢10-20倍。' },
          },
          {
            '@type': 'Question',
            name: '使用13B模型而非受限70B更好吗？',
            acceptedAnswer: { '@type': 'Answer', text: '对大多数任务是。Q5的13B在RTX 4090上以80-100 tokens/秒运行。Q2的70B以5-8 tokens/秒运行质量降低。13B在速度和实用质量上赢得。仅在需特定70B能力且容忍仅批处理时使用70B-on-24GB。' },
          },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        inLanguage: 'zh',
        name: '在24GB VRAM上运行70B模型的技术',
        numberOfItems: 3,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Q2量化（17.5GB）', description: '完全适合24GB VRAM。质量：约70% FP16。速度：5-8 tokens/秒。' },
          { '@type': 'ListItem', position: 2, name: 'Q4 + CPU卸载（卸载11GB）', description: '更好质量但非常慢：1-3 tokens/秒。仅适用深夜批处理。' },
          { '@type': 'ListItem', position: 3, name: '层分割（2× RTX 4090）', description: '最佳选项：48GB总计，Q5运行约100 tokens/秒。推荐用于单GPU约束。' },
        ],
      },
    },
    es: {
      freshness_tier: 'semi_annual',
      theme: 'Hardware & Performance',
      title: 'Cómo ejecutar modelos 70B en 24 GB de VRAM: técnicas avanzadas',
      seoTitle: 'Ejecutar modelos 70B en 24 GB de VRAM: guía completa 2026',
      intro: 'Ejecutar un modelo 70B (que normalmente requiere más de 40 GB) en 24 GB de VRAM es posible con cuantización agresiva (Q2-Q3) y offloading de capas, pero el resultado es lento (~3-5 tokens/seg). A partir de abril de 2026, esto es impráctico para chat en tiempo real, pero viable para procesamiento por lotes o experimentación.',
      metaDescription: 'Ejecutar modelos 70B en 24 GB de VRAM 2026: cuantización (Q4_K_M), offloading, división de capas. Técnicas con compromisos y datos de rendimiento.',
      publishDate: '2026-04-04',
      dateModified: '2026-04-19',
      leadAnswerBlock: '**Ejecutar un modelo 70B (que normalmente requiere más de 40 GB) en 24 GB de VRAM es posible con cuantización agresiva (Q2-Q3) y offloading de capas, pero el resultado es lento (~3-5 tokens/seg).**',
      audience: 'Ingenieros que despliegan LLMs locales en entornos de producción o empresariales',
      readTime: '10 min de lectura',
      educationalLevel: 'Advanced',
      primaryTerm: 'optimización de modelos 70B',
      toc: [
        { label: 'Puntos clave', anchor: '#key-takeaways' },
        { label: 'Límites teóricos', anchor: '#limits' },
        { label: 'Estrategia de cuantización', anchor: '#quantization' },
        { label: 'Estrategia de offloading', anchor: '#offloading' },
        { label: 'Configuración práctica', anchor: '#setup' },
        { label: 'Rendimiento realista', anchor: '#performance' },
        { label: 'Mejores alternativas', anchor: '#alternatives' },
        { label: 'Errores comunes', anchor: '#common-mistakes' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Lecturas relacionadas', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            'Llama 3.3 70B en Q4 = 35 GB (demasiado grande para 24 GB). En Q3 = 26 GB (todavía demasiado grande). En Q2 = 17 GB (¡cabe!).',
            'Compensación: Q2 tiene una pérdida de calidad notable. ~70% de la calidad FP16.',
            'Velocidad: 3-5 tokens/seg con 20 GB descargados a la RAM del sistema (ultra lento).',
            'Mejor opción: usar un modelo 13B en Q5, o comprar una segunda GPU para división de capas.',
            'A partir de abril de 2026, esto es una solución a una restricción, no un enfoque recomendado.',
          ],
        },
        limits: {
          id: 'limits',
          title: 'Las matemáticas teóricas del VRAM',
          content: [
            '**Llama 3.3 70B con varias cuantizaciones:**',
          ],
          rows: [
            { 'Cuantización': 'FP16 (base)', 'Tamaño': '140 GB', '¿Cabe en 24 GB?': 'No' },
            { 'Cuantización': 'Q8 (8 bits)', 'Tamaño': '70 GB', '¿Cabe en 24 GB?': 'No' },
            { 'Cuantización': 'Q5 (5 bits)', 'Tamaño': '43,75 GB', '¿Cabe en 24 GB?': 'No' },
            { 'Cuantización': 'Q4 (4 bits)', 'Tamaño': '35 GB', '¿Cabe en 24 GB?': 'No (con offloading: quizás)' },
            { 'Cuantización': 'Q3 (3 bits)', 'Tamaño': '26 GB', '¿Cabe en 24 GB?': 'No (por poco)' },
            { 'Cuantización': 'Q2 (2 bits)', 'Tamaño': '17,5 GB', '¿Cabe en 24 GB?': 'Sí' },
          ],
          columns: ['Cuantización', 'Tamaño del modelo', '¿Cabe en 24 GB?'],
        },
        quantization: {
          id: 'quantization',
          title: 'Cuantización agresiva: la herramienta principal',
          content: [
            '**Para que 70B quepa en 24 GB, debes usar cuantización Q2 o Q3.**',
            '- **Q3**: 26 GB (todavía 2 GB de más). Se pueden descargar 2 GB a la RAM. Calidad ligeramente mejor que Q2.',
            '- **Q2**: 17,5 GB (¡cabe!). 70% de calidad frente a FP16. Degradación notable pero utilizable.',
            'Descarga el modelo cuantizado: `ollama pull llama3.1:70b-q2` (si está disponible) o usa herramientas de conversión como llama.cpp.',
          ],
        },
        offloading: {
          id: 'offloading',
          title: 'Offloading a la RAM del sistema',
          content: [
            '**Si usas Q4 (35 GB) en una GPU de 24 GB, puedes descargar los 11 GB restantes a la RAM del sistema.** La penalización de velocidad es severa (10× más lento).',
            'Solo es práctico para el procesamiento por lotes donde puedes esperar horas para obtener resultados.',
          ],
        },
        setup: {
          id: 'setup',
          title: 'Configuración práctica: ejecutar 70B en 24 GB',
          content: 'Paso a paso:',
          numberedItems: [
            'Usa cuantización Q2: `ollama pull llama3.1:70b-q2` (si está disponible; de lo contrario, convierte con llama.cpp)',
            'Verifica el VRAM: `nvidia-smi` debería mostrar ~18 GB en uso',
            'Ejecuta el modelo: `ollama run llama3.1:70b-q2`',
            'Espera 3-5 tokens/seg (muy lento)',
            'Úsalo solo para procesamiento por lotes/sin conexión, no para chat interactivo',
          ],
        },
        performance: {
          id: 'performance',
          title: 'Expectativas de rendimiento realistas',
          content: [
            '**Ejecutar 70B en 24 GB de VRAM es lento:**',
          ],
          rows: [
            { 'Cuantización': 'Q2 (24 GB VRAM)', 'Velocidad': '5-8 tok/seg', 'Latencia': '2-4 seg por token', 'Caso de uso': 'Solo procesamiento por lotes' },
            { 'Cuantización': 'Q3 + offload (24 GB)', 'Velocidad': '3-5 tok/seg', 'Latencia': '3-5 seg por token', 'Caso de uso': 'Extremadamente limitado' },
            { 'Cuantización': 'Q4 + offload (24 GB)', 'Velocidad': '1-3 tok/seg', 'Latencia': '5-10 seg por token', 'Caso de uso': 'Solo lotes nocturnos' },
          ],
          columns: ['Cuantización', 'Velocidad', 'Latencia', 'Caso de uso'],
        },
        alternatives: {
          id: 'alternatives',
          title: 'Mejores alternativas al 70B restringido',
          content: 'En lugar de luchar con un 70B con VRAM limitada, considera:',
          items: [
            'Usar un modelo 13B (Llama 3.3 13B en Q5 = 8 GB, muy rápido)',
            'Comprar una segunda RTX 4090 para división de capas (2× 24 GB = 48 GB, más de 100 tokens/seg)',
            'Usar una API en la nube (GPT-5.5 para tareas importantes, local para experimentación)',
            'Esperar modelos más eficientes (más pequeños, misma calidad)',
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: 'Errores comunes con el 70B restringido',
          items: [
            '**Esperar que Q2 sea utilizable para chat.** No lo es. La degradación de calidad es demasiado severa para la interacción en tiempo real.',
            '**No medir la velocidad real antes de comprometerse.** Prueba con un prompt pequeño (10 tokens) y verifica la velocidad antes de ejecutar trabajos por lotes grandes.',
            '**Asumir que el offloading es "gratuito".** La RAM del sistema es 100× más lenta que la VRAM de la GPU. El offloading hace que la inferencia sea impráctica.',
            '**No considerar alternativas.** Un modelo 13B es dramáticamente más rápido y a menudo suficiente en calidad.',
          ],
        },
        faqSection: {
          id: 'faq',
          title: 'Preguntas frecuentes',
          faqs: [
            {
              q: '¿Realmente puedo ejecutar un modelo 70B en una sola RTX 4090?',
              a: 'Sí, pero con advertencias importantes. Con cuantización Q2 (17,5 GB), el modelo cabe en 24 GB de VRAM pero funciona a 5-8 tokens/seg y tiene ~70% de la calidad FP16. Con Q4 (35 GB), necesitas descargar 11 GB a la RAM del sistema, lo que reduce la velocidad a 1-3 tokens/seg. Ninguna opción es adecuada para el chat en tiempo real — solo para el procesamiento por lotes sin conexión.',
            },
            {
              q: '¿Qué cuantización se necesita para que 70B quepa en 24 GB de VRAM?',
              a: 'La cuantización Q2 cabe en 24 GB (17,5 GB de tamaño de modelo). Q3 (26 GB) requiere 2 GB de offloading de RAM. Q4 (35 GB) requiere 11 GB de offloading y hace que la inferencia sea muy lenta. Q5 y superiores (44-70 GB) no pueden caber incluso con offloading en una GPU de 24 GB. Q2 es la única opción que funciona completamente en VRAM.',
            },
            {
              q: '¿Qué tan lento es un modelo 70B en 24 GB de VRAM?',
              a: 'Con Q2 (completamente en VRAM): 5-8 tokens/seg. Con Q3 y 2 GB de offload de RAM: 3-5 tokens/seg. Con Q4 y 11 GB de offload de RAM: 1-3 tokens/seg. Compara con un modelo 13B en Q5 en la misma GPU: 80-100 tokens/seg. La configuración 70B restringida es 10-20× más lenta que un modelo más pequeño del tamaño adecuado.',
            },
            {
              q: '¿Es mejor usar un modelo 13B que un 70B restringido?',
              a: 'Para la mayoría de las tareas, sí. Un modelo 13B con cuantización Q5 funciona a 80-100 tokens/seg en una RTX 4090 y ofrece gran calidad. Un modelo 70B en Q2 funciona a 5-8 tokens/seg con calidad degradada. El 13B gana en velocidad y a menudo en calidad práctica debido a la degradación de Q2. Solo usa 70B-en-24GB si necesitas capacidades específicas del 70B y puedes tolerar un uso exclusivamente por lotes.',
            },
            {
              q: '¿Cuál es el mejor caso de uso para 70B en 24 GB de VRAM?',
              a: 'Procesamiento por lotes nocturno — tareas en las que envías 100+ prompts y recuperas resultados horas después. Ejemplos: análisis de documentos, revisiones de código por lotes, anotación de conjuntos de datos. El chat en tiempo real es impráctíco a 1-8 tokens/seg. Para uso interactivo, una segunda RTX 4090 ($1.800) con división de capas alcanza ~100 tokens/seg — una inversión mucho mejor.',
            },
            {
              q: '¿Cómo descargo modelos 70B cuantizados en Q2?',
              a: 'A través de Ollama: `ollama pull llama3.1:70b-instruct-q2_K` (la disponibilidad varía). A través de llama.cpp: descarga archivos GGUF Q2_K desde Hugging Face (busca "llama-3.1-70b GGUF"). TheBloke y bartowski publican versiones cuantizadas. Verifica el modelo con `nvidia-smi` después de cargarlo — el uso de VRAM debería ser ~18-20 GB para Q2.',
            },
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Lecturas relacionadas',
          items: [
            '[Guía de hardware para LLM locales 2026](/es/local-llms/local-llm-hardware-guide-2026) -- Compra mejor hardware.',
            '[LLMs locales con múltiples GPU](/es/local-llms/multi-gpu-local-llms) -- Usa la división de capas en su lugar.',
            '[Los mejores LLMs locales para programación](/es/local-llms/best-local-llms-for-coding) -- Los modelos más pequeños suelen ser suficientes.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Fuentes',
          items: [
            'Cuantización llama.cpp -- github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/quants.py',
            'Ficha del modelo: Llama 3.3 70B -- huggingface.co/meta-llama/Llama-3.1-70B',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        url: 'https://www.promptquorum.com/es/es/local-llms/run-70b-models-24gb-vram',
        inLanguage: 'es',
        headline: 'Ejecutar modelos 70B en 24 GB de VRAM: guía completa 2026',
        description: 'Ejecutar modelos 70B en 24 GB de VRAM 2026: cuantización (Q4_K_M), offloading, división de capas. Técnicas con compromisos y datos de rendimiento.',
        datePublished: '2026-04-04',
        dateModified: '2026-04-19',
        author: { '@type': 'Person', name: 'Hans Kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        proficiencyLevel: 'Advanced',
        speakable: {
          '@type': 'SpeakableSpecification',
          cssSelector: ['.article-intro', '.key-takeaways'],
        },
        about: [
          { '@type': 'Thing', name: 'Llama 3.3' },
          { '@type': 'Thing', name: 'modelos 70B' },
          { '@type': 'Thing', name: 'optimización de VRAM' },
        ],
        mentions: [
          { '@type': 'SoftwareApplication', name: 'Ollama' },
          { '@type': 'SoftwareApplication', name: 'llama.cpp' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        inLanguage: 'es',
        mainEntity: [
          {
            '@type': 'Question',
            name: '¿Realmente puedo ejecutar un modelo 70B en una sola RTX 4090?',
            acceptedAnswer: { '@type': 'Answer', text: 'Sí, pero con advertencias importantes. Con cuantización Q2 (17,5 GB), el modelo cabe en 24 GB de VRAM pero funciona a 5-8 tokens/seg y tiene ~70% de la calidad FP16. Con Q4 (35 GB), necesitas descargar 11 GB a la RAM del sistema, reduciendo la velocidad a 1-3 tokens/seg. Ninguna opción es adecuada para el chat en tiempo real.' },
          },
          {
            '@type': 'Question',
            name: '¿Qué cuantización se necesita para que 70B quepa en 24 GB de VRAM?',
            acceptedAnswer: { '@type': 'Answer', text: 'La cuantización Q2 cabe en 24 GB (17,5 GB de tamaño de modelo). Q3 (26 GB) requiere 2 GB de offloading de RAM. Q4 (35 GB) requiere 11 GB de offloading y hace que la inferencia sea muy lenta. Q5 y superiores no pueden caber incluso con offloading. Q2 es la única opción que funciona completamente en VRAM.' },
          },
          {
            '@type': 'Question',
            name: '¿Qué tan lento es un modelo 70B en 24 GB de VRAM?',
            acceptedAnswer: { '@type': 'Answer', text: 'Con Q2 (completamente en VRAM): 5-8 tokens/seg. Con Q3 y 2 GB de offload de RAM: 3-5 tokens/seg. Con Q4 y 11 GB de offload de RAM: 1-3 tokens/seg. Un modelo 13B en Q5 en la misma GPU funciona a 80-100 tokens/seg — 10-20× más rápido.' },
          },
          {
            '@type': 'Question',
            name: '¿Es mejor usar un modelo 13B que un 70B restringido?',
            acceptedAnswer: { '@type': 'Answer', text: 'Para la mayoría de las tareas, sí. Un modelo 13B en Q5 funciona a 80-100 tokens/seg en una RTX 4090. Un modelo 70B en Q2 funciona a 5-8 tokens/seg con calidad degradada. El 13B gana en velocidad y a menudo en calidad práctica. Solo usa 70B-en-24GB si necesitas capacidades específicas del 70B y puedes tolerar un uso exclusivamente por lotes.' },
          },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        inLanguage: 'es',
        name: 'Técnicas para ejecutar modelos 70B en 24 GB de VRAM',
        numberOfItems: 3,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Cuantización Q2 (17,5 GB)', description: 'Cabe completamente en 24 GB de VRAM. Calidad: ~70% de FP16. Velocidad: 5-8 tokens/seg.' },
          { '@type': 'ListItem', position: 2, name: 'Q4 + offloading de CPU (11 GB descargados)', description: 'Mejor calidad pero muy lento: 1-3 tokens/seg. Adecuado solo para lotes nocturnos.' },
          { '@type': 'ListItem', position: 3, name: 'División de capas (2× RTX 4090)', description: 'Mejor opción: 48 GB en total, ejecuta Q5 a ~100 tokens/seg. Recomendado sobre la restricción de una sola GPU.' },
        ],
      },
    },
    pt: {
      freshness_tier: 'semi_annual',
      theme: 'Hardware & Performance',
      title: 'Como executar modelos 70B em 24 GB de VRAM: técnicas avançadas',
      seoTitle: 'Executar modelos 70B em 24 GB de VRAM: guia completo 2026',
      intro: 'Executar um modelo 70B (que normalmente requer mais de 40 GB) em 24 GB de VRAM é possível com quantização agressiva (Q2-Q3) e offloading de camadas, mas o resultado é lento (~3-5 tokens/seg). A partir de abril de 2026, isso é impraticável para chat em tempo real, mas viável para processamento em lotes ou experimentação.',
      metaDescription: 'Executar modelos 70B em 24 GB de VRAM 2026: quantização (Q4_K_M), offloading, divisão de camadas. Técnicas com compensações e dados de desempenho.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**Executar um modelo 70B (que normalmente requer mais de 40 GB) em 24 GB de VRAM é possível com quantização agressiva (Q2-Q3) e offloading de camadas, mas o resultado é lento (~3-5 tokens/seg).**',
      audience: 'Engenheiros implantando LLMs locais em ambientes de produção ou empresariais',
      readTime: '10 min de leitura',
      educationalLevel: 'Advanced',
      primaryTerm: 'otimização de modelos 70B',
      toc: [
        { label: 'Principais conclusões', anchor: '#key-takeaways' },
        { label: 'Limites teóricos', anchor: '#limits' },
        { label: 'Estratégia de quantização', anchor: '#quantization' },
        { label: 'Estratégia de offloading', anchor: '#offloading' },
        { label: 'Configuração prática', anchor: '#setup' },
        { label: 'Desempenho realista', anchor: '#performance' },
        { label: 'Melhores alternativas', anchor: '#alternatives' },
        { label: 'Erros comuns', anchor: '#common-mistakes' },
        { label: 'Perguntas frequentes', anchor: '#faq' },
        { label: 'Leitura relacionada', anchor: '#related-reading' },
      ],
      sections: {
        tldr: {
          id: 'key-takeaways',
          isTldr: true,
          items: [
            'Llama 3.3 70B em Q4 = 35 GB (grande demais para 24 GB). Em Q3 = 26 GB (ainda grande demais). Em Q2 = 17 GB (cabe!).',
            'Compensação: Q2 tem perda de qualidade perceptível. ~70% da qualidade FP16.',
            'Velocidade: 3-5 tokens/seg com 20 GB descarregados para a RAM do sistema (ultra lento).',
            'Melhor opção: usar modelo 13B em Q5, ou comprar uma segunda GPU para divisão de camadas.',
            'A partir de abril de 2026, isso é uma solução alternativa para uma restrição, não uma abordagem recomendada.',
          ],
        },
        limits: {
          id: 'limits',
          title: 'A matemática teórica de VRAM',
          content: [
            '**Llama 3.3 70B com várias quantizações:**',
          ],
          rows: [
            { 'Quantização': 'FP16 (base)', 'Tamanho': '140 GB', 'Cabe em 24 GB?': 'Não' },
            { 'Quantização': 'Q8 (8 bits)', 'Tamanho': '70 GB', 'Cabe em 24 GB?': 'Não' },
            { 'Quantização': 'Q5 (5 bits)', 'Tamanho': '43,75 GB', 'Cabe em 24 GB?': 'Não' },
            { 'Quantização': 'Q4 (4 bits)', 'Tamanho': '35 GB', 'Cabe em 24 GB?': 'Não (com offloading: talvez)' },
            { 'Quantização': 'Q3 (3 bits)', 'Tamanho': '26 GB', 'Cabe em 24 GB?': 'Não (por pouco)' },
            { 'Quantização': 'Q2 (2 bits)', 'Tamanho': '17,5 GB', 'Cabe em 24 GB?': 'Sim' },
          ],
          columns: ['Quantização', 'Tamanho do modelo', 'Cabe em 24 GB?'],
        },
        quantization: {
          id: 'quantization',
          title: 'Quantização agressiva: a ferramenta principal',
          content: [
            '**Para que 70B caiba em 24 GB, você deve usar quantização Q2 ou Q3.**',
            '- **Q3**: 26 GB (ainda 2 GB a mais). Pode descarregar 2 GB para a RAM. Qualidade ligeiramente melhor que Q2.',
            '- **Q2**: 17,5 GB (cabe!). 70% de qualidade vs FP16. Degradação perceptível, mas utilizável.',
            'Baixe o modelo quantizado: `ollama pull llama3.1:70b-q2` (se disponível) ou use ferramentas de conversão como llama.cpp.',
          ],
        },
        offloading: {
          id: 'offloading',
          title: 'Offloading para a RAM do sistema',
          content: [
            '**Se usar Q4 (35 GB) em uma GPU de 24 GB, você pode descarregar os 11 GB restantes para a RAM do sistema.** A penalidade de velocidade é severa (10× mais lento).',
            'Só é prático para processamento em lotes onde você pode esperar horas pelos resultados.',
          ],
        },
        setup: {
          id: 'setup',
          title: 'Configuração prática: executar 70B em 24 GB',
          content: 'Passo a passo:',
          numberedItems: [
            'Use quantização Q2: `ollama pull llama3.1:70b-q2` (se disponível; caso contrário, converta com llama.cpp)',
            'Verifique a VRAM: `nvidia-smi` deve mostrar ~18 GB em uso',
            'Execute o modelo: `ollama run llama3.1:70b-q2`',
            'Espere 3-5 tokens/seg (muito lento)',
            'Use apenas para processamento em lotes/offline, não para chat interativo',
          ],
        },
        performance: {
          id: 'performance',
          title: 'Expectativas de desempenho realistas',
          content: [
            '**Executar 70B em 24 GB de VRAM é lento:**',
          ],
          rows: [
            { 'Quantização': 'Q2 (24 GB VRAM)', 'Velocidade': '5-8 tok/seg', 'Latência': '2-4 seg por token', 'Caso de uso': 'Apenas processamento em lotes' },
            { 'Quantização': 'Q3 + offload (24 GB)', 'Velocidade': '3-5 tok/seg', 'Latência': '3-5 seg por token', 'Caso de uso': 'Extremamente limitado' },
            { 'Quantização': 'Q4 + offload (24 GB)', 'Velocidade': '1-3 tok/seg', 'Latência': '5-10 seg por token', 'Caso de uso': 'Apenas lotes noturnos' },
          ],
          columns: ['Quantização', 'Velocidade', 'Latência', 'Caso de uso'],
        },
        alternatives: {
          id: 'alternatives',
          title: 'Melhores alternativas ao 70B restrito',
          content: 'Em vez de lutar com 70B com VRAM limitada, considere:',
          items: [
            'Usar um modelo 13B (Llama 3.3 13B em Q5 = 8 GB, muito rápido)',
            'Comprar uma segunda RTX 4090 para divisão de camadas (2× 24 GB = 48 GB, mais de 100 tokens/seg)',
            'Usar uma API na nuvem (GPT-5.5 para tarefas importantes, local para experimentação)',
            'Aguardar modelos mais eficientes (menores, mesma qualidade)',
          ],
        },
        commonMistakes: {
          id: 'common-mistakes',
          title: 'Erros comuns com o 70B restrito',
          items: [
            '**Esperar que Q2 seja utilizável para chat.** Não é. A degradação de qualidade é severa demais para interação em tempo real.',
            '**Não medir a velocidade real antes de se comprometer.** Teste com um prompt pequeno (10 tokens) e verifique a velocidade antes de executar grandes trabalhos em lotes.',
            '**Assumir que o offloading é "gratuito".** A RAM do sistema é 100× mais lenta que a VRAM da GPU. O offloading torna a inferência impraticável.',
            '**Não considerar alternativas.** Um modelo 13B é dramaticamente mais rápido e muitas vezes suficiente em qualidade.',
          ],
        },
        faqSection: {
          id: 'faq',
          title: 'Perguntas frequentes',
          faqs: [
            {
              q: 'Posso realmente executar um modelo 70B em uma única RTX 4090?',
              a: 'Sim, mas com ressalvas importantes. Com quantização Q2 (17,5 GB), o modelo cabe em 24 GB de VRAM, mas executa a 5-8 tokens/seg e tem ~70% da qualidade FP16. Com Q4 (35 GB), você precisa descarregar 11 GB para a RAM do sistema, reduzindo a velocidade para 1-3 tokens/seg. Nenhuma opção é adequada para chat em tempo real — apenas para processamento em lotes offline.',
            },
            {
              q: 'Qual quantização é necessária para que 70B caiba em 24 GB de VRAM?',
              a: 'A quantização Q2 cabe em 24 GB (17,5 GB de tamanho do modelo). Q3 (26 GB) requer 2 GB de offloading de RAM. Q4 (35 GB) requer 11 GB de offloading e torna a inferência muito lenta. Q5 e superiores não cabem mesmo com offloading em uma GPU de 24 GB. Q2 é a única opção que executa completamente em VRAM.',
            },
            {
              q: 'Quão lento é um modelo 70B em 24 GB de VRAM?',
              a: 'Com Q2 (completamente em VRAM): 5-8 tokens/seg. Com Q3 e 2 GB de offload de RAM: 3-5 tokens/seg. Com Q4 e 11 GB de offload de RAM: 1-3 tokens/seg. Compare com um modelo 13B em Q5 na mesma GPU: 80-100 tokens/seg — 10-20× mais rápido.',
            },
            {
              q: 'É melhor usar um modelo 13B do que um 70B restrito?',
              a: 'Para a maioria das tarefas, sim. Um modelo 13B em quantização Q5 executa a 80-100 tokens/seg em uma RTX 4090. Um modelo 70B em Q2 executa a 5-8 tokens/seg com qualidade degradada. O 13B vence em velocidade e frequentemente em qualidade prática. Use 70B em 24 GB apenas se precisar de capacidades específicas do 70B e puder tolerar uso exclusivamente em lotes.',
            },
            {
              q: 'Qual é o melhor caso de uso para 70B em 24 GB de VRAM?',
              a: 'Processamento em lotes noturno — tarefas onde você envia 100+ prompts e recupera resultados horas depois. Exemplos: análise de documentos, revisões de código em lotes, anotação de conjuntos de dados. Chat em tempo real é impraticável a 1-8 tokens/seg.',
            },
            {
              q: 'Como baixo modelos 70B quantizados em Q2?',
              a: 'Via Ollama: `ollama pull llama3.1:70b-instruct-q2_K` (disponibilidade varia). Via llama.cpp: baixe arquivos GGUF Q2_K do Hugging Face (pesquise "llama-3.1-70b GGUF"). Verifique o modelo com `nvidia-smi` após carregá-lo — o uso de VRAM deve ser ~18-20 GB para Q2.',
            },
          ],
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Leitura relacionada',
          items: [
            '[Guia de hardware para LLM locais 2026](/pt/local-llms/local-llm-hardware-guide-2026) -- Compre hardware melhor.',
            '[LLMs locais com múltiplas GPUs](/pt/local-llms/multi-gpu-local-llms) -- Use divisão de camadas.',
            '[Melhores LLMs locais para programação](/pt/local-llms/best-local-llms-for-coding) -- Modelos menores frequentemente suficientes.',
          ],
        },
        sources: {
          id: 'sources',
          title: 'Fontes',
          items: [
            'Quantização llama.cpp -- github.com/ggerganov/llama.cpp/blob/master/gguf-py/gguf/quants.py',
            'Ficha do modelo: Llama 3.3 70B -- huggingface.co/meta-llama/Llama-3.1-70B',
          ],
        },
      },
      schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        url: 'https://www.promptquorum.com/pt/local-llms/run-70b-models-24gb-vram',
        inLanguage: 'pt-BR',
        headline: 'Executar modelos 70B em 24 GB de VRAM: guia completo 2026',
        description: 'Executar modelos 70B em 24 GB de VRAM 2026: quantização (Q4_K_M), offloading, divisão de camadas. Técnicas com compensações e dados de desempenho.',
        datePublished: '2026-04-04',
        author: { '@type': 'Person', name: 'Hans Kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        proficiencyLevel: 'Advanced',
        speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        inLanguage: 'pt-BR',
        name: 'Técnicas para executar modelos 70B em 24 GB de VRAM',
        numberOfItems: 3,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Quantização Q2 (17,5 GB)', description: 'Cabe completamente em 24 GB de VRAM. Qualidade: ~70% do FP16. Velocidade: 5-8 tokens/seg.' },
          { '@type': 'ListItem', position: 2, name: 'Q4 + offloading de CPU (11 GB descarregados)', description: 'Melhor qualidade, mas muito lento: 1-3 tokens/seg. Adequado apenas para lotes noturnos.' },
          { '@type': 'ListItem', position: 3, name: 'Divisão de camadas (2× RTX 4090)', description: 'Melhor opção: 48 GB no total, executa Q5 a ~100 tokens/seg. Recomendado sobre a restrição de uma única GPU.' },
        ],
      },
    },
  };
