// Auto-generated from src/lib/local-llms/content.ts
// Slug: small-local-llm-models
// Generated: 2026-05-03T11:33:08.370Z

import type { Language } from "@/lib/blog/blogContent";

import type { LLMArticle } from "@/lib/local-llms/types";

export const article: Partial<Record<Language, LLMArticle>> = {
    en: {
      freshness_tier: 'semi_annual',
      theme: 'Best Models',
      title: 'Small Local LLM Models: Best Sub-4B Models for Low RAM Machines in 2026',
      seoTitle: 'Small Local LLM Models 2026: Top 5 Sub-4B Ranked',
      intro: 'Small local LLMs (1B-4B parameters) run on machines with 4-8 GB RAM and produce 30-70 tokens/sec on CPU -- fast enough for real-time chat. The best small models in 2026 are Microsoft Phi-4 Mini 3.8B (best reasoning), Google Gemma 2 2B (fastest), Qwen2.5 3B (best coding), and Meta Llama 3.2 3B (best general use).',
      metaDescription: 'Best sub-4B local LLM models for 4-8 GB RAM: Phi-4 Mini (68% MMLU), Gemma 2 (fastest), Qwen2.5 (coding), Llama 3.2 (general). April 2026 rankings.',
      publishDate: '2026-04-04',
      leadAnswerBlock: '**Small local LLMs (1B-4B parameters) run on machines with 4-8 GB RAM and produce 30-70 tokens/sec on CPU -- fast enough for real-time chat.**',
      audience: 'Beginners running their first local LLM on consumer hardware',
      readTime: '8 min read',
      educationalLevel: 'Beginner',
      primaryTerm: 'small local LLM',
      toc: [
        { label: 'Key Takeaways', anchor: '#key-takeaways' },
        { label: 'What Is a "Small" Local LLM?', anchor: '#what-is-small-llm' },
        { label: 'Which Model Should You Use?', anchor: '#model-selection-guide' },
        { label: '#1 Phi-4 Mini 3.8B -- Best Reasoning', anchor: '#phi-4-mini' },
        { label: '#2 Gemma 2 2B -- Fastest on CPU', anchor: '#gemma-2-2b' },
        { label: '#3 Qwen2.5 3B -- Best for Coding', anchor: '#qwen2-5-3b' },
        { label: '#4 Llama 3.2 3B -- Best General Use', anchor: '#llama-3-2-3b' },
        { label: '#5 Llama 3.2 1B -- Absolute Minimum', anchor: '#llama-3-2-1b' },
        { label: 'Full Comparison Table', anchor: '#comparison-table' },
        { label: 'Quantization Guide', anchor: '#quantization-guide' },
        { label: 'Regional Context', anchor: '#regional-context' },
        { label: 'Common Mistakes', anchor: '#common-mistakes' },
        { label: 'Related Reading', anchor: '#related-reading' },
        { label: 'FAQ', anchor: '#faq' },
        { label: 'Sources', anchor: '#sources' },
      ],
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'Small Local LLM Models: Best Sub-4B Models for Low RAM Machines in 2026',
        description: 'Small local LLMs (1B-4B parameters) run on machines with 4-8 GB RAM and produce 30-70 tokens/sec on CPU -- fast enough for real-time chat.',
        datePublished: '2026-04-04',
        dateModified: '2026-04-05',
        'url': 'https://www.promptquorum.com/local-llms/small-local-llm-models',
        'inLanguage': 'en',
        author: { '@type': 'Person', 'name': 'Hans Kuepper', 'sameAs': 'https://www.promptquorum.com/author/hans-kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        proficiencyLevel: 'Beginner',
        about: [
          { '@type': 'Thing', name: 'Small local LLM' },
          { '@type': 'Thing', name: 'Phi-4 Mini' },
          { '@type': 'Thing', name: 'Gemma 2 2B' },
          { '@type': 'Thing', name: 'Llama 3.2 3B' },
          { '@type': 'Thing', name: 'Low RAM inference' },
        ],
      },
      itemListSchema: {
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        name: 'Best Small Local LLM Models Under 4B Parameters 2026',
        numberOfItems: 5,
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Phi-4 Mini 3.8B', description: 'MMLU 68%, HumanEval 70%. 2.5 GB RAM. 30-50 tok/sec CPU. 128K context. Best reasoning. ollama run phi4-mini' },
          { '@type': 'ListItem', position: 2, name: 'Gemma 2 2B', description: 'MMLU 52%. 1.7 GB RAM. 40-60 tok/sec CPU -- fastest small model. 8K context. ollama run gemma2:2b' },
          { '@type': 'ListItem', position: 3, name: 'Qwen2.5 3B', description: 'MMLU 62%, HumanEval 65%. 2 GB RAM. 29 languages natively. Function calling supported. ollama run qwen2.5:3b' },
          { '@type': 'ListItem', position: 4, name: 'Llama 3.2 3B', description: 'MMLU 58%, HumanEval 60%. 2.5 GB RAM. 128K context. Most community support. ollama run llama3.2:3b' },
          { '@type': 'ListItem', position: 5, name: 'Llama 3.2 1B', description: 'MMLU 32%. 1.3 GB RAM. 60-90 tok/sec CPU. Absolute minimum RAM requirement. ollama run llama3.2:1b' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'inLanguage': 'en',
        mainEntity: [
          { '@type': 'Question', name: 'Using Q8_0 quantization instead of Q4_K_M', acceptedAnswer: { '@type': 'Answer', text: 'Q8_0 requires nearly double the RAM of Q4_K_M for minimal quality improvement at small scale. A Llama 3.2 3B model at Q8_0 needs ~3.8 GB RAM vs ~2.5 GB for Q4_K_M. On a 4 GB machine, Q8_0 may trigger swap usage and make inference 3-5× slower. Always use Q4_K_M as the default for sub-4B models.' } },
          { '@type': 'Question', name: 'Running a base model instead of the instruct variant', acceptedAnswer: { '@type': 'Answer', text: 'Base models (e.g., llama3.2:3b-text) are pre-fine-tuning checkpoints trained to predict the next token in text. They do not follow instructions. When you ask a base model "What is 2+2?", it may complete the sentence as a quiz rather than answer "4". Always use the instruct variant: llama3.2:3b (Ollama defaults to instruct for named models).' } },
          { '@type': 'Question', name: 'Expecting 7B model quality from a 3B model', acceptedAnswer: { '@type': 'Answer', text: 'A 3B model at 68% MMLU (Phi-4 Mini) performs similarly to a 2023-era GPT-3.5 Mini on general tasks. Complex reasoning chains, long-form writing, and nuanced code generation will produce noticeably lower quality than a 7B model. If output quality is insufficient, upgrade to a 7B model -- the RAM difference is ~2 GB (2.5 GB → 4.5 GB).' } },
          { '@type': 'Question', name: 'What is the smallest local LLM that produces useful output?', acceptedAnswer: { '@type': 'Answer', text: 'As of April 2026, the practical minimum for useful output is a 3B model at Q4_K_M quantization. Models below 2B parameters struggle with multi-step instructions and complex reasoning. For tasks like summarization and simple Q&A, Gemma 2 2B is usable. For anything more complex, start with a 3B model.' } },
          { '@type': 'Question', name: 'Can a 3B model run on a phone?', acceptedAnswer: { '@type': 'Answer', text: 'Yes -- Llama 3.2 1B and 3B are designed for on-device mobile deployment. Meta provides optimized builds for iOS (via MLC LLM) and Android. Inference on a modern phone produces 15-30 tok/sec for 1B models. LM Studio and Ollama do not currently run on iOS or Android -- mobile requires separate frameworks.' } },
          { '@type': 'Question', name: 'Are small models good for summarization?', acceptedAnswer: { '@type': 'Answer', text: 'Yes -- summarization is one of the strongest use cases for small models. Gemma 2 2B and Llama 3.2 3B reliably produce accurate summaries of texts up to ~4,000 words. For longer documents, use a model with a large context window like Phi-4 Mini or Llama 3.2 3B (both 128K tokens).' } },
          { '@type': 'Question', name: 'How much faster is a 2B model than a 7B model on the same hardware?', acceptedAnswer: { '@type': 'Answer', text: 'Approximately 2-3× faster on CPU. Gemma 2 2B generates 40-60 tok/sec vs 10-20 tok/sec for Mistral 7B on the same laptop CPU. On a GPU, the speed advantage narrows. The speed difference is most noticeable on CPU-only machines.' } },
          { '@type': 'Question', name: 'Do small models support function calling?', acceptedAnswer: { '@type': 'Answer', text: 'Some do. Qwen2.5 3B supports function calling and JSON mode. Llama 3.2 3B has basic tool use support. Gemma 2 2B does not support function calling. Check the model documentation before building a pipeline that depends on structured output.' } },
          { '@type': 'Question', name: 'Which small model is best for languages other than English?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen2.5 3B supports 29 languages natively including Chinese, Japanese, Korean, and Arabic. Gemma 2 2B and Phi-4 Mini are primarily English-optimized. For non-English tasks at the small model scale, Qwen2.5 3B is the clear choice.' } },
          { '@type': 'Question', name: 'What is the difference between Phi-4 Mini and Llama 3.2 3B for everyday tasks?', acceptedAnswer: { '@type': 'Answer', text: 'Phi-4 Mini outperforms Llama 3.2 3B on reasoning and coding (68% vs 58% MMLU, 70% vs 60% HumanEval) at nearly identical RAM. Llama 3.2 3B has broader community support and more fine-tunes available. Choose Phi-4 Mini for structured reasoning; Llama 3.2 3B for general chat and compatibility.' } },
        ],
      },
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**Best reasoning at small scale**: Phi-4 Mini 3.8B -- 68% MMLU, 70% HumanEval, runs on 4 GB RAM.',
            '**Fastest on CPU**: Gemma 2 2B -- 40-60 tok/sec on any modern laptop, 1.7 GB RAM.',
            '**Best small coding model**: Qwen2.5 3B -- 65% HumanEval at ~2 GB RAM.',
            '**Best general-purpose 3B**: Llama 3.2 3B -- most community support, 128K context, 2.5 GB RAM.',
            'As of April 2026, no sub-2B model produces output quality suitable for professional tasks. Use 3B+ for real work.',
          ],
        },
        whatIsSmall: {
          title: 'What Is a "Small" Local LLM and When Should You Use One?',
          content: [
            '**A small local LLM is typically defined as a model with fewer than 4 billion parameters.** At Q4_K_M quantization, these models require 1.5-3 GB of RAM -- well within the constraints of entry-level laptops with 4-8 GB total memory.',
            'As of April 2026, small models are appropriate for: quick summarization, simple Q&A, code snippet explanation, translation of short texts, and classification tasks. They are not suitable for multi-step reasoning, complex code generation, or writing long-form coherent documents.',
            'The quality gap between a 3B and 7B model is significant -- roughly equivalent to the gap between GPT-3.5 Mini and GPT-3.5 Turbo. For users with 8 GB RAM, a 7B model at Q4_K_M is almost always the better choice if the machine has headroom. See [Best Beginner Local LLM Models](/local-llms/best-beginner-local-llm-models) for 7B recommendations.',
          ],
        },
        modelSelectionGuide: {
          title: 'Which Model Should You Use? Quick Decision Guide?',
          image: '/images/small-llm-decision-tree-mockup.svg',
          imageCaption: 'Decision tree: choose by priority (reasoning, speed, or coding). Default to Llama 3.2 3B if unsure.',
        },
        phi4mini: {
          title: 'Phi-4 Mini 3.8B -- Best Reasoning Performance in the Sub-4B Class',
          content: [
            '**Microsoft Phi-4 Mini achieves 68% on MMLU and 70% on HumanEval -- scores that exceed many 7B models released before 2025.** This is possible because Phi-4 Mini was trained on a curated synthetic dataset focused on reasoning and problem-solving, rather than broad web text.',
            'As of April 2026, Phi-4 Mini is the recommended choice for users who primarily need reasoning (math, logic, step-by-step explanations) or coding assistance on hardware with 4-6 GB RAM.',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '68%' },
            { 'Spec': 'HumanEval', 'Value': '70%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2.5 GB' },
            { 'Spec': 'Context', 'Value': '128K tokens' },
            { 'Spec': 'CPU speed', 'Value': '30-50 tok/sec' },
            { 'Spec': 'Ollama command', 'Value': 'ollama run phi4-mini' },
          ],
          columns: ['Spec', 'Value'],
        },
        gemma2: {
          title: 'Gemma 2 2B -- Fastest Small Local LLM on CPU',
          content: [
            '**Google Gemma 2 2B generates 40-60 tokens/sec on a modern laptop CPU -- the fastest of any model at this quality tier.** Its 1.7 GB RAM footprint leaves ample memory for the OS and other applications on a 4 GB machine.',
            'Quality is lower than Phi-4 Mini or Llama 3.2 3B on reasoning tasks. The 8K context window (vs. 128K on Phi-4 Mini and Llama 3.2) is a practical limitation for longer documents. Gemma 2 2B is the right choice when response speed matters more than output depth.',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '52%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~1.7 GB' },
            { 'Spec': 'Context', 'Value': '8K tokens' },
            { 'Spec': 'CPU speed', 'Value': '40-60 tok/sec' },
            { 'Spec': 'Ollama command', 'Value': 'ollama run gemma2:2b' },
          ],
          columns: ['Spec', 'Value'],
        },
        qwen25_3b: {
          title: 'Qwen2.5 3B -- Best Small Model for Coding Tasks',
          content: [
            '**Qwen2.5 3B scores 65% on HumanEval -- 5 percentage points above Llama 3.2 3B -- making it the best choice for coding tasks at the 3B scale.** It includes JSON mode and function calling support, and natively handles 29 languages.',
            'For non-coding tasks in English, Llama 3.2 3B and Phi-4 Mini produce more natural prose. Choose Qwen2.5 3B specifically when coding or multilingual output is the primary use case.',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '62%' },
            { 'Spec': 'HumanEval', 'Value': '65%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2 GB' },
            { 'Spec': 'Context', 'Value': '128K tokens' },
            { 'Spec': 'CPU speed', 'Value': '25-40 tok/sec' },
            { 'Spec': 'Ollama command', 'Value': 'ollama run qwen2.5:3b' },
          ],
          columns: ['Spec', 'Value'],
        },
        llama32_3b: {
          title: 'Llama 3.2 3B -- Best General-Purpose Small Model',
          content: [
            '**Meta Llama 3.2 3B is the most widely documented and community-supported 3B model.** It scores 58% on MMLU and 60% on HumanEval -- slightly below Phi-4 Mini on both -- but has the widest tool support, the most fine-tunes available, and the largest collection of community guides.',
            'The 128K context window is the same as larger Llama 3.x models, making it suitable for summarizing medium-length documents. For a first small model, Llama 3.2 3B remains the safest choice due to predictable behavior and extensive documentation.',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '58%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2.5 GB' },
            { 'Spec': 'Context', 'Value': '128K tokens' },
            { 'Spec': 'CPU speed', 'Value': '25-45 tok/sec' },
            { 'Spec': 'Ollama command', 'Value': 'ollama run llama3.2:3b' },
          ],
          columns: ['Spec', 'Value'],
        },
        llama32_1b: {
          title: 'Llama 3.2 1B -- Absolute Minimum for Any Useful Output',
          content: 'Llama 3.2 1B requires only 1.3 GB of RAM and generates 60-90 tok/sec on CPU -- the fastest locally-runnable model. Output quality is marginal: it handles very simple classification and keyword extraction but struggles with coherent multi-sentence responses. As of April 2026, use Llama 3.2 1B only when RAM is genuinely the binding constraint (under 3 GB available) or for testing tool integrations.',
        },
        comparisonTable: {
          title: 'Full Comparison: Best Small Local LLMs Under 4B Parameters',
          image: '/images/small-llm-performance-tier-mockup.svg',
          imageCaption: 'Performance tiers: MMLU and HumanEval scores show Phi-4 Mini leads on reasoning and coding, Gemma 2 is fastest on CPU, Qwen2.5 excels at coding.',
          rows: [
            { 'Model': 'Phi-4 Mini 3.8B', 'MMLU': '68%', 'HumanEval': '70%', 'RAM': '2.5 GB', 'Context': '128K', 'Best For': 'Reasoning, coding' },
            { 'Model': 'Qwen2.5 3B', 'MMLU': '62%', 'HumanEval': '65%', 'RAM': '2 GB', 'Context': '128K', 'Best For': 'Coding, multilingual' },
            { 'Model': 'Llama 3.2 3B', 'MMLU': '58%', 'HumanEval': '60%', 'RAM': '2.5 GB', 'Context': '128K', 'Best For': 'General use, first model' },
            { 'Model': 'Gemma 2 2B', 'MMLU': '52%', 'HumanEval': '38%', 'RAM': '1.7 GB', 'Context': '8K', 'Best For': 'Speed, very low RAM' },
            { 'Model': 'Llama 3.2 1B', 'MMLU': '32%', 'HumanEval': '28%', 'RAM': '1.3 GB', 'Context': '128K', 'Best For': 'Absolute minimum RAM' },
          ],
          columns: ['Model', 'MMLU', 'HumanEval', 'RAM', 'Context', 'Best For'],
        },
        regionalContext: {
          title: 'Small Local LLMs by Region',
          content: [
            '**EU / GDPR:** For EU professionals running AI on constrained hardware -- field work, air-gapped environments, older enterprise laptops -- small local models provide GDPR-compliant inference with zero data egress. A Phi-4 Mini 3.8B running on a standard-issue corporate laptop (8 GB RAM) keeps all processed text on-device under GDPR Article 5 (data minimization). For German BSI compliance documentation: Phi-4 Mini (Microsoft, MIT licence) and Llama 3.2 3B (Meta, Llama Community licence) both provide versioned model identifiers via their Ollama tags, satisfying AI tool documentation requirements. Mistral does not currently offer a sub-4B model. For EU organizations preferring an EU-origin model at this size class, options are limited until Mistral releases a sub-4B variant.',
            '**Japan (METI):** For Japanese-language tasks at the small model tier, Qwen2.5 3B is the only model in this comparison with native Japanese tokenization. Llama 3.2 3B handles Japanese but with lower token efficiency. For Japanese summarization or translation on constrained hardware: `ollama run qwen2.5:3b`. The speed advantage of small models is particularly relevant for Japanese enterprise use: 25-40 tok/sec on CPU provides adequate real-time response for chat interfaces on standard-issue office hardware.',
            '**China:** Qwen2.5 3B (Alibaba, Apache 2.0) is the natural choice for Chinese-language small model deployment. Native Chinese tokenization processes Mandarin text 30-40% more efficiently than Llama at equivalent parameter count. For IoT and edge deployments under China\'s Data Security Law (数据安全法): `ollama run qwen2.5:3b` runs on any Linux device with 4 GB RAM and processes all text on-device with no external API calls.',
          ],
        },
        commonMistakes: {
          title: 'What Are the Common Mistakes When Running Small Local LLMs?',
          items: [
            '**Using Q8_0 quantization instead of Q4_K_M:** Q8_0 requires nearly double the RAM of Q4_K_M for minimal quality improvement at small scale. A Llama 3.2 3B model at Q8_0 needs ~3.8 GB RAM vs ~2.5 GB for Q4_K_M. On a 4 GB machine, Q8_0 may trigger swap usage and make inference 3-5× slower. Always use Q4_K_M as the default for sub-4B models.',
            '**Running a base model instead of the instruct variant:** Base models (e.g., `llama3.2:3b-text`) are pre-fine-tuning checkpoints trained to predict the next token in text. They do not follow instructions. When you ask a base model "What is 2+2?", it may complete the sentence as a quiz rather than answer "4". Always use the instruct variant: `llama3.2:3b` (Ollama defaults to instruct for named models).',
            '**Expecting 7B model quality from a 3B model:** A 3B model at 68% MMLU (Phi-4 Mini) performs similarly to a 2023-era GPT-3.5 Mini on general tasks. Complex reasoning chains, long-form writing, and nuanced code generation will produce noticeably lower quality than a 7B model. If output quality is insufficient, upgrade to a 7B model -- the RAM difference is ~2 GB (2.5 GB → 4.5 GB).',
          ],
        },
        quantizationGuide: {
          title: 'Understanding Quantization: RAM vs Quality Trade-off',
          image: '/images/small-llm-quantization-tradeoff-mockup.svg',
          imageCaption: 'Quantization trade-off: Q4_K_M (2.5 GB, -0.5% quality) is the recommended default. Q8_0 uses 3.8 GB with no quality gain. Q3_K_M (1.8 GB, -1.8% loss) for extreme RAM constraints.',
        },
        relatedReading: {
          id: 'related-reading',
          title: 'Related Reading',
          items: [
            '[Best Beginner Local LLM Models](/local-llms/best-beginner-local-llm-models) -- 7B model recommendations when 8 GB RAM is available and quality needs to step up from 3B',
            '[Run Your First Local LLM](/local-llms/run-first-local-llm) -- step-by-step guide to pulling and running any model from this page with Ollama in under 10 minutes',
            '[Local LLM on a Laptop](/local-llms/local-llm-on-laptop) -- thermal and battery management for sustained inference on constrained hardware',
            '[LLM Quantization Explained](/local-llms/llm-quantization-explained) -- why Q4_K_M is the default and when to consider Q3_K_M for extreme RAM constraints',
            '[Best Local LLMs for Coding](/local-llms/best-local-llms-for-coding) -- coding-specific models at 7B+ scale when Qwen2.5 3B is not enough for complex tasks',
            '[Troubleshooting Local LLM Setup](/local-llms/troubleshooting-local-llm-setup) -- fix OOM errors, slow inference, and model loading failures common on low-RAM machines',
          ],
        },
        faqSection: {
          id: 'faq',
          title: 'Common Questions About Small Local LLM Models',
          faqs: [
            {
              q: 'What is the smallest local LLM that produces useful output?',
              a: 'As of April 2026, the practical minimum for useful output is a 3B model at Q4_K_M quantization. Models below 2B parameters (Llama 3.2 1B, Gemma 2 2B) produce coherent single sentences but struggle with multi-step instructions, longer responses, and complex reasoning. For tasks like summarization and simple Q&A, Gemma 2 2B is usable. For anything more complex, start with a 3B model.',
            },
            {
              q: 'Can a 3B model run on a phone?',
              a: 'Yes -- Llama 3.2 1B and 3B are specifically designed for on-device mobile deployment. Meta provides optimized builds for iOS (via MLC LLM) and Android. Inference on a modern phone (Snapdragon 8 Gen 3 or Apple A17 Pro) produces 15-30 tok/sec for 1B models. LM Studio and Ollama do not currently run on iOS or Android -- mobile requires separate frameworks.',
            },
            {
              q: 'Are small models good for summarization?',
              a: 'Yes -- summarization is one of the strongest use cases for small models. Gemma 2 2B and Llama 3.2 3B reliably produce accurate summaries of texts up to ~4,000 words (their practical context limit for quality output). For longer documents, use a model with a large context window like Phi-4 Mini or Llama 3.2 3B (both 128K tokens).',
            },
            {
              q: 'How much faster is a 2B model than a 7B model on the same hardware?',
              a: 'Approximately 2-3× faster on CPU. Gemma 2 2B generates 40-60 tok/sec vs 10-20 tok/sec for Mistral 7B on the same laptop CPU. On a GPU, the speed advantage narrows because GPU throughput is less constrained by model size. The speed difference is most noticeable on CPU-only machines.',
            },
            {
              q: 'Do small models support function calling?',
              a: 'Some do. Qwen2.5 3B supports function calling and JSON mode. Llama 3.2 3B has basic tool use support. Gemma 2 2B does not support function calling. Check the model\'s documentation before building a pipeline that depends on structured output.',
            },
            {
              q: 'Which small model is best for languages other than English?',
              a: 'Qwen2.5 3B supports 29 languages natively including Chinese, Japanese, Korean, and Arabic. Gemma 2 2B and Phi-4 Mini are primarily English-optimized. For non-English tasks at the small model scale, Qwen2.5 3B is the clear choice. See [Qwen vs Llama vs Mistral multilingual comparison](/local-llms/qwen-vs-llama-vs-mistral) for a full language comparison.',
            },
            {
              q: 'What is the difference between Phi-4 Mini and Llama 3.2 3B for everyday tasks?',
              a: 'Phi-4 Mini outperforms Llama 3.2 3B on reasoning, math, and coding (68% vs 58% MMLU, 70% vs 60% HumanEval) at nearly identical RAM (2.5 GB each). For everyday tasks -- Q&A, summarization, simple explanations -- the quality gap is noticeable but not dramatic. Llama 3.2 3B has broader community support and more fine-tunes available. Choose Phi-4 Mini for structured reasoning; Llama 3.2 3B for general chat and broader compatibility.',
            },
            {
              q: 'Can I run two small models simultaneously?',
              a: 'Yes, if total RAM permits. Two 3B models at Q4_K_M use ~5 GB combined -- feasible on an 8 GB machine with a lean OS. Ollama loads one model at a time per process by default. Run two Ollama instances on different ports (OLLAMA_HOST=:11434 and OLLAMA_HOST=:11435) to serve two models in parallel. This is useful for A/B testing outputs.',
            },
            {
              q: 'Do small models work for RAG (retrieval-augmented generation)?',
              a: 'Yes for simple RAG. Llama 3.2 3B and Phi-4 Mini can answer questions over retrieved document chunks reliably. For RAG over large knowledge bases requiring multi-hop reasoning, 7B+ models perform more consistently. GPT4All\'s LocalDocs feature uses a 3B model for document Q&A and works well for personal document collections.',
            },
            {
              q: 'Is Phi-4 Mini better than Llama 3.2 3B for coding?',
              a: 'Yes. Phi-4 Mini scores 70% on HumanEval vs 60% for Llama 3.2 3B -- a meaningful 10-point gap at this scale. For coding assistance on 4-6 GB RAM machines, Phi-4 Mini is the recommended choice. For multilingual coding (non-Python), Qwen2.5 3B at 65% HumanEval is competitive with Phi-4 Mini while also supporting function calling.',
            },
          ],
        },
        sources: {
          id: 'sources',
          title: 'Sources',
          items: [
            'Hugging Face Open LLM Leaderboard -- open-llm-leaderboard.hf.space (MMLU and HumanEval scores)',
            'Microsoft Phi-4 Technical Report -- microsoft.com/en-us/research/publication/phi-4-technical-report/',
            'Meta Llama 3.2 Model Card -- huggingface.co/meta-llama/Llama-3.2-3B-Instruct',
            'Google Gemma 2 Technical Report -- storage.googleapis.com/deepmind-media/gemma/gemma-2-report.pdf',
          ],
        },
      },
    },
    de: {
      theme: 'Best Models',
      title: 'Beste kleine lokale LLMs 2026 : Sub-4B-Modelle für RAM-arme Maschinen',
      seoTitle: 'Beste kleine lokale LLMs 2026: Sub-4B Modelle Vergleich',
      metaDescription: 'Best Sub-4B Modelle für 4-8 GB RAM in 2026: Phi-4 Mini (68% MMLU), Gemma 2 (schnellste), Qwen2.5 (Codierung), Llama 3.2. Vollständiger Vergleich.',
      intro: 'Kleine lokale LLMs (1B-4B Parameter) laufen auf Maschinen mit 4-8 GB RAM und erzeugen 30-70 Token/Sek auf CPU -- schnell genug für Echtzeit-Chat. Die besten kleinen Modelle in 2026 sind Microsoft Phi-4 Mini 3.8B (bestes Reasoning), Google Gemma 2 2B (schnellste), Qwen2.5 3B (beste Codierung) und Meta Llama 3.2 3B (beste allgemeine Nutzung).',
      publishDate: '2026-04-04',
      readTime: '8 min',
      educationalLevel: 'Beginner',
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'Beste kleine lokale LLMs 2026 : Sub-4B-Modelle für RAM-arme Maschinen',
        description: 'Beste kleine lokale LLMs 2026 : Phi-4 Mini (Reasoning), Gemma 2 (Geschwindigkeit), Qwen2.5 (Codierung), Llama 3.2 (allgemeine Verwendung). Vollständiger Vergleich für RAM-arme Hardware.',
        datePublished: '2026-04-04',
        dateModified: '2026-04-04',
        'url': 'https://www.promptquorum.com/local-llms/small-local-llm-models?lang=de',
        'inLanguage': 'de',
        author: { '@type': 'Person', 'name': 'Hans Kuepper', 'sameAs': 'https://www.promptquorum.com/author/hans-kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        about: [
          { '@type': 'Thing', name: 'Phi-4 Mini 3.8B' },
          { '@type': 'Thing', name: 'Gemma 2 2B' },
          { '@type': 'Thing', name: 'Qwen2.5 3B' },
          { '@type': 'Thing', name: 'Llama 3.2 3B' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'inLanguage': 'de',
        mainEntity: [
          { '@type': 'Question', name: 'Was ist das kleinste lokale LLM, das nützliche Ausgaben produziert?', acceptedAnswer: { '@type': 'Answer', text: 'Seit April 2026 ist das praktische Minimum ein 3B-Modell bei Q4_K_M-Quantisierung. Modelle unter 2B Parametern produzieren kohärente einzelne Sätze, kämpfen aber mit mehrstufigen Anweisungen und komplexem Reasoning. Für die meisten Fälle beginnen Sie mit einem 3B-Modell.' } },
          { '@type': 'Question', name: 'Kann ich ein 3B-Modell auf einem Telefon ausführen?', acceptedAnswer: { '@type': 'Answer', text: 'Ja -- Llama 3.2 1B und 3B sind speziell für die mobile Bereitstellung auf dem Gerät konzipiert. Inferenzen auf einem modernen Telefon erzeugen 15-30 tok/sec für 1B-Modelle. Mobile Frameworks wie MLC LLM unterstützen iOS, aber Ollama und LM Studio funktionieren derzeit nicht auf iOS/Android.' } },
          { '@type': 'Question', name: 'Sind kleine Modelle gut für Zusammenfassung?', acceptedAnswer: { '@type': 'Answer', text: 'Ja -- Zusammenfassung ist einer der besten Anwendungsfälle für kleine Modelle. Gemma 2 2B und Llama 3.2 3B produzieren zuverlässig genaue Zusammenfassungen von Texten bis zu ~4.000 Wörtern.' } },
          { '@type': 'Question', name: 'Wie viel schneller ist ein 2B-Modell als ein 7B-Modell auf derselben Hardware?', acceptedAnswer: { '@type': 'Answer', text: 'Etwa 2-3× schneller auf CPU. Gemma 2 2B generiert 40-60 tok/sec vs 10-20 tok/sec für Mistral 7B auf dem gleichen Laptop-CPU. Der Geschwindigkeitsvorteil ist auf reinen CPU-Maschinen am deutlichsten.' } },
          { '@type': 'Question', name: 'Unterstützen kleine Modelle Funktionsaufrufe?', acceptedAnswer: { '@type': 'Answer', text: 'Einige tun dies. Qwen2.5 3B unterstützt Funktionsaufrufe und JSON-Modus. Llama 3.2 3B hat grundlegende Werkzeugunterstützung. Gemma 2 2B unterstützt Funktionsaufrufe nicht.' } },
          { '@type': 'Question', name: 'Welches kleine Modell ist für Sprachen außer Englisch am besten?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen2.5 3B unterstützt nativ 29 Sprachen, einschließlich Chinesisch, Japanisch, Koreanisch und Arabisch. Gemma 2 2B und Phi-4 Mini sind hauptsächlich auf Englisch optimiert. Für nicht-englische Aufgaben auf kleiner Modellskala ist Qwen2.5 3B die klare Wahl.' } },
          { '@type': 'Question', name: 'Was ist der Qualitätsunterschied zwischen einem 3B- und 7B-Modell?', acceptedAnswer: { '@type': 'Answer', text: 'Ein 3B-Modell mit 68% MMLU (Phi-4 Mini) schneidet ähnlich wie ein GPT-3.5 Mini aus dem Jahr 2023 bei allgemeinen Aufgaben ab. Längere Texte und komplexer Code werden eine deutlich niedrigere Qualität haben.' } },
          { '@type': 'Question', name: 'Wie kann ich ein kleines LLM auf Deutsch ausführen?', acceptedAnswer: { '@type': 'Answer', text: 'Laden Sie das Modell mit Ollama herunter: `ollama pull qwen2.5:3b` oder `ollama pull llama3.2:3b`. Starten Sie ein Gespräch auf Deutsch mit `ollama run qwen2.5:3b`. Es sind keine speziellen Konfigurationsparameter erforderlich -- die Modelle produzieren automatisch qualitativ hochwertigen deutschen Text gemäß DSGVO-Standards für lokale Verarbeitung.' } },
        ],
      },
      sections: {
        tldr: { id: 'key-takeaways',
 isTldr: true, items: ['**Bestes Reasoning im kleinen Format**: Phi-4 Mini 3.8B -- 68% MMLU, 70% HumanEval, läuft auf 4 GB RAM.', '**Schnellste auf CPU**: Gemma 2 2B -- 40-60 tok/sek auf jedem modernen Laptop, 1,7 GB RAM.', '**Bestes kleines Codierungsmodell**: Qwen2.5 3B -- 65% HumanEval bei ~2 GB RAM.', '**Beste Universal-3B**: Llama 3.2 3B -- beste Community-Unterstützung, 128K Kontext, 2,5 GB RAM.', 'Seit April 2026 produziert kein Sub-2B-Modell Ausgabequalität, die für professionelle Aufgaben geeignet ist. Verwenden Sie 3B+ für echte Arbeit.'] },
        whatIsSmall: { title: 'Was ist ein „kleines" lokales LLM und wann sollten Sie eines verwenden?', content: ['Ein kleines lokales LLM ist typischerweise definiert als ein Modell mit weniger als 4 Milliarden Parametern. Bei Q4_K_M-Quantisierung benötigen diese Modelle 1,5-3 GB RAM -- gut innerhalb der Einschränkungen von Einstiegs-Laptops mit 4-8 GB Gesamtspeicher.', 'Seit April 2026 sind kleine Modelle geeignet für: schnelle Zusammenfassung, einfache F&A, Erklärung von Code-Snippets, Übersetzung kurzer Texte und Klassifizierungsaufgaben. Sie sind nicht geeignet für mehrstufiges Reasoning, komplexe Code-Generierung oder das Verfassen langer kohärenter Dokumente.', 'Die Qualitätslücke zwischen einem 3B- und 7B-Modell ist erheblich -- ungefähr der Lücke zwischen GPT-3.5 Mini und GPT-3.5 Turbo entsprechend. Für Benutzer mit 8 GB RAM ist ein 7B-Modell bei Q4_K_M fast immer die bessere Wahl. Siehe [Beste Anfänger-Lokale-LLM-Modelle](/local-llms/best-beginner-local-llm-models) für 7B-Empfehlungen.'] },
        phi4mini: { title: 'Phi-4 Mini 3.8B -- Beste Reasoning-Leistung in der Sub-4B-Klasse', content: ['Microsoft Phi-4 Mini erreicht 68% bei MMLU und 70% bei HumanEval -- Werte, die viele vor 2025 veröffentlichte 7B-Modelle übertreffen. Dies ist möglich, weil Phi-4 Mini auf einem kuratierten synthetischen Datensatz trainiert wurde, der auf Reasoning und Problemlösung fokussiert ist.', 'Seit April 2026 ist Phi-4 Mini die empfohlene Wahl für Benutzer, die hauptsächlich Reasoning oder Code-Unterstützung auf Hardware mit 4-6 GB RAM benötigen.'], rows: [{ 'Spec': 'MMLU', 'Value': '68%' }, { 'Spec': 'HumanEval', 'Value': '70%' }, { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2,5 GB' }, { 'Spec': 'Kontext', 'Value': '128K Token' }, { 'Spec': 'CPU-Geschwindigkeit', 'Value': '30-50 tok/sek' }, { 'Spec': 'Ollama-Befehl', 'Value': 'ollama run phi4-mini' }], columns: ['Spec', 'Value'] },
        gemma2: { title: 'Gemma 2 2B -- Schnellstes kleines lokales LLM auf CPU', content: ['Google Gemma 2 2B generiert 40-60 Token/Sek auf einer modernen Laptop-CPU -- das schnellste Modell in dieser Qualitätsklasse. Sein 1,7-GB-RAM-Footprint lässt viel Speicher für Betriebssystem und andere Anwendungen auf einer 4-GB-Maschine.', 'Die Qualität ist niedriger als Phi-4 Mini bei Reasoning. Das 8K-Kontextfenster ist eine praktische Einschränkung für längere Dokumente. Gemma 2 2B ist die richtige Wahl, wenn Antwortgeschwindigkeit wichtiger ist als Ausgabetiefe.'], rows: [{ 'Spec': 'MMLU', 'Value': '52%' }, { 'Spec': 'RAM (Q4_K_M)', 'Value': '~1,7 GB' }, { 'Spec': 'Kontext', 'Value': '8K Token' }, { 'Spec': 'CPU-Geschwindigkeit', 'Value': '40-60 tok/sek' }, { 'Spec': 'Ollama-Befehl', 'Value': 'ollama run gemma2:2b' }], columns: ['Spec', 'Value'] },
        qwen25_3b: { title: 'Qwen2.5 3B -- Bestes kleines Modell für Codierungsaufgaben', content: ['Qwen2.5 3B erreicht 65% bei HumanEval -- 5 Prozentpunkte über Llama 3.2 3B -- und ist beste Wahl für Codierungsaufgaben im 3B-Format. Es umfasst JSON-Modus und Funktionsaufruf-Unterstützung und verarbeitet nativ 29 Sprachen.', 'Für nicht-Codierungs-Aufgaben im Englischen erzeugen Llama 3.2 3B und Phi-4 Mini natürlichere Prosa. Wählen Sie Qwen2.5 3B speziell für Codierung oder mehrsprachige Aufgaben.'], rows: [{ 'Spec': 'MMLU', 'Value': '62%' }, { 'Spec': 'HumanEval', 'Value': '65%' }, { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2 GB' }, { 'Spec': 'Kontext', 'Value': '128K Token' }, { 'Spec': 'CPU-Geschwindigkeit', 'Value': '25-40 tok/sek' }, { 'Spec': 'Ollama-Befehl', 'Value': 'ollama run qwen2.5:3b' }], columns: ['Spec', 'Value'] },
        llama32_3b: { title: 'Llama 3.2 3B -- Bestes Universal-Kleinmodell', content: ['Meta Llama 3.2 3B ist das am weitesten dokumentierte und von der Community unterstützte 3B-Modell. Es erreicht 58% bei MMLU und 60% bei HumanEval, aber hat breiteste Werkzeugunterstützung, die meisten Fine-Tunes und größte Sammlung von Community-Guides.', 'Das 128K-Kontextfenster eignet sich für Zusammenfassung von Dokumenten mittlerer Länge. Für ein erstes kleines Modell bleibt Llama 3.2 3B die sicherste Wahl aufgrund vorhersehbaren Verhaltens und umfangreicher Dokumentation.'], rows: [{ 'Spec': 'MMLU', 'Value': '58%' }, { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2,5 GB' }, { 'Spec': 'Kontext', 'Value': '128K Token' }, { 'Spec': 'CPU-Geschwindigkeit', 'Value': '25-45 tok/sek' }, { 'Spec': 'Ollama-Befehl', 'Value': 'ollama run llama3.2:3b' }], columns: ['Spec', 'Value'] },
        llama32_1b: { title: 'Llama 3.2 1B -- Absolute Mindestanforderung für nützliche Ausgabe', content: 'Llama 3.2 1B benötigt nur 1,3 GB RAM und generiert 60-90 tok/sek auf CPU. Die Ausgabequalität ist marginal: es bewältigt sehr einfache Klassifizierung, kämpft aber mit kohärenten mehrsätzigen Antworten. Seit April 2026 verwenden Sie Llama 3.2 1B nur, wenn RAM die bindende Einschränkung ist oder zum Testen von Tool-Integrationen.' },
        comparisonTable: { title: 'Vollständiger Vergleich: Beste kleine lokale LLMs unter 4B Parametern', rows: [{ 'Modell': 'Phi-4 Mini 3.8B', 'MMLU': '68%', 'HumanEval': '70%', 'RAM': '2,5 GB', 'Kontext': '128K', 'Beste für': 'Reasoning, Codierung' }, { 'Modell': 'Qwen2.5 3B', 'MMLU': '62%', 'HumanEval': '65%', 'RAM': '2 GB', 'Kontext': '128K', 'Beste für': 'Codierung, mehrsprachig' }, { 'Modell': 'Llama 3.2 3B', 'MMLU': '58%', 'HumanEval': '60%', 'RAM': '2,5 GB', 'Kontext': '128K', 'Beste für': 'Allgemein, erstes Modell' }, { 'Modell': 'Gemma 2 2B', 'MMLU': '52%', 'HumanEval': '38%', 'RAM': '1,7 GB', 'Kontext': '8K', 'Beste für': 'Geschwindigkeit, niedriges RAM' }, { 'Modell': 'Llama 3.2 1B', 'MMLU': '32%', 'HumanEval': '28%', 'RAM': '1,3 GB', 'Kontext': '128K', 'Beste für': 'Minimales RAM' }], columns: ['Modell', 'MMLU', 'HumanEval', 'RAM', 'Kontext', 'Beste für'] },
        regionalContext: { title: 'Kleine lokale LLMs nach Region', content: ['**EU / DSGVO:** Für EU-Profis auf begrenzter Hardware -- Feldarbeit, air-gapped Umgebungen, ältere Enterprise-Laptops -- bieten kleine lokale Modelle DSGVO-konforme Inferenz ohne Datengress. Ein Phi-4 Mini 3.8B auf Standard-Corporate-Laptop (8 GB RAM) behält alle Texte auf Gerät unter DSGVO-Artikel 5. Für BSI-Compliance: Phi-4 Mini (Microsoft, MIT-Lizenz) und Llama 3.2 3B (Meta, Llama Community-Lizenz) bieten versionierte Modell-Identifikatoren via Ollama-Tags. Mistral bietet derzeit kein Sub-4B-Modell. Für EU-Organisationen mit EU-Präferenz sind Optionen begrenzt, bis Mistral Sub-4B freigibt.', '**Japan (METI):** Für japanischsprachige Aufgaben ist Qwen2.5 3B das einzige Modell mit nativer japanischer Tokenisierung. Llama 3.2 3B verarbeitet Japanisch mit niedrigerer Token-Effizienz. Für japanische Zusammenfassung oder Übersetzung: `ollama run qwen2.5:3b`. Der Geschwindigkeitsvorteil ist relevant für japanischen Enterprise-Einsatz: 25-40 tok/sek auf CPU bietet angemessene Echtzeit-Antwort auf Standard-Office-Hardware.', '**China:** Qwen2.5 3B (Alibaba, Apache 2.0) ist natürliche Wahl für chinesischsprachige Bereitstellung. Native chinesische Tokenisierung verarbeitet Mandarin-Text 30-40% effizienter als Llama. Für IoT und Edge unter Chinas Datensicherheitsgesetz: `ollama run qwen2.5:3b` läuft auf jedem Linux-Gerät mit 4 GB RAM ohne externe API-Aufrufe.'] },
        commonMistakes: { title: 'Häufige Fehler beim Ausführen kleiner lokaler LLMs', items: ['**Verwendung von Q8_0 statt Q4_K_M:** Q8_0 benötigt fast doppelt so viel RAM mit minimaler Qualitätsverbesserung. Ein Llama 3.2 3B mit Q8_0 benötigt ~3,8 GB RAM vs ~2,5 GB für Q4_K_M. Auf 4 GB Maschinen kann Q8_0 Swap-Nutzung und 3-5× langsamere Inferenz auslösen. Verwenden Sie immer Q4_K_M für Sub-4B-Modelle.', '**Ausführung eines Basis-Modells statt Instruct-Variante:** Basis-Modelle (z. B. `llama3.2:3b-text`) folgen keine Anweisungen. Wenn Sie ein Basis-Modell „Was ist 2+2?" fragen, kann es den Satz als Quiz vervollständigen statt „4" zu antworten. Verwenden Sie immer: `llama3.2:3b` (Ollama greift standardmäßig zu Instruct).', '**Erwartung von 7B-Qualität aus 3B-Modell:** Ein 3B-Modell mit 68% MMLU (Phi-4 Mini) funktioniert ähnlich wie GPT-3.5 Mini aus 2023. Komplexe Reasoning, lange Texte und differenzierter Code haben niedrigere Qualität. Für bessere Qualität: aktualisieren Sie auf 7B (RAM-Unterschied: ~2 GB mehr).'] },
        relatedReading: { title: 'Weiterführende Lektüre', items: ['[Beste Anfänger-Lokale-LLM-Modelle](/local-llms/best-beginner-local-llm-models) -- 7B-Empfehlungen wenn 8 GB RAM verfügbar', '[Ihr erstes lokales LLM ausführen](/local-llms/run-first-local-llm) -- Schritt-für-Schritt-Anleitung mit Ollama unter 10 Minuten', '[Lokales LLM auf Laptop](/local-llms/local-llm-on-laptop) -- Wärmeverwaltung und Batterielebensdauer auf begrenzter Hardware', '[LLM-Quantisierung erklärt](/local-llms/llm-quantization-explained) -- warum Q4_K_M Standard ist und Q3_K_M für extreme RAM-Einschränkungen', '[Beste lokale LLMs zum Codieren](/local-llms/best-local-llms-for-coding) -- Codierungs-Modelle bei 7B+ wenn Qwen2.5 3B nicht ausreicht', '[Lokales LLM-Setup beheben](/local-llms/troubleshooting-local-llm-setup) -- OOM-Fehler, langsame Inferenz und Ladefehler auf RAM-armen Maschinen'] },
        faqSection: { title: 'Häufig gestellte Fragen', faqs: [{ q: 'Was ist das kleinste lokale LLM mit nützlicher Ausgabe?', a: 'Seit April 2026 ist 3B bei Q4_K_M praktisches Minimum. Modelle unter 2B (Llama 3.2 1B, Gemma 2 2B) erzeugen kohärente einzelne Sätze, kämpfen aber mit mehrstufigen Anweisungen und Reasoning. Für Zusammenfassung und F&A ist Gemma 2 2B brauchbar. Für komplexere Aufgaben: beginnen Sie mit 3B.' }, { q: 'Kann ein 3B-Modell auf einem Telefon laufen?', a: 'Ja -- Llama 3.2 1B und 3B sind für mobile Bereitstellung konzipiert. Meta bietet optimierte Builds für iOS und Android. Inferenz auf modernem Telefon erzeugt 15-30 tok/sek für 1B. LM Studio und Ollama laufen nicht auf iOS/Android -- mobil erfordert separate Frameworks.' }, { q: 'Sind kleine Modelle für Zusammenfassung geeignet?', a: 'Ja -- Zusammenfassung ist stärkster Anwendungsfall für kleine Modelle. Gemma 2 2B und Llama 3.2 3B produzieren zuverlässig genaue Zusammenfassungen von Texten bis zu ~4.000 Wörtern. Für längere Dokumente verwenden Sie Modell mit großem Kontext wie Phi-4 Mini oder Llama 3.2 3B (beide 128K).' }, { q: 'Wie viel schneller ist 2B als 7B auf gleicher Hardware?', a: 'Ungefähr 2-3× schneller auf CPU. Gemma 2 2B generiert 40-60 tok/sek vs 10-20 tok/sek für Mistral 7B. Auf GPU verengt sich Vorteil, da GPU-Durchsatz weniger durch Modellgröße begrenzt ist. Unterschied ist auf reinen CPU-Maschinen deutlichst.' }, { q: 'Unterstützen kleine Modelle Funktionsaufrufe?', a: 'Einige tun dies. Qwen2.5 3B unterstützt Funktionsaufrufe und JSON. Llama 3.2 3B hat grundlegende Werkzeugunterstützung. Gemma 2 2B unterstützt keine Funktionsaufrufe. Überprüfen Sie Modelldokumentation vor Pipeline-Aufbau.' }, { q: 'Welches kleine Modell ist beste für nicht-englische Sprachen?', a: 'Qwen2.5 3B unterstützt nativ 29 Sprachen (Chinesisch, Japanisch, Koreanisch, Arabisch). Gemma 2 2B und Phi-4 Mini sind hauptsächlich auf Englisch optimiert. Für nicht-englische Aufgaben bei kleinen Modellen ist Qwen2.5 3B klare Wahl.' }, { q: 'Unterschied zwischen Phi-4 Mini und Llama 3.2 3B?', a: 'Phi-4 Mini übertrifft bei Reasoning, Mathematik, Codierung (68% vs 58% MMLU, 70% vs 60% HumanEval) bei fast identischem RAM (2,5 GB). Für Alltags-Aufgaben ist Lücke spürbar aber nicht dramatisch. Llama 3.2 3B hat breitere Support. Wählen Sie Phi-4 Mini für Reasoning; Llama für Chat.' }, { q: 'Kann ich zwei kleine Modelle gleichzeitig laufen lassen?', a: 'Ja, wenn RAM zulässt. Zwei 3B-Modelle bei Q4_K_M verwenden ~5 GB kombiniert -- auf 8 GB Maschine mit schlankem OS möglich. Ollama lädt standardmäßig ein Modell pro Prozess. Laufen Sie zwei Ollama-Instanzen auf verschiedenen Ports (OLLAMA_HOST=:11434 und :11435) parallel.' }, { q: 'Funktionieren kleine Modelle für RAG?', a: 'Ja für einfaches RAG. Llama 3.2 3B und Phi-4 Mini beantworten Fragen über abgerufene Dokumentchunks zuverlässig. Für RAG über große Wissensdatenbanken mit Multi-Hop-Reasoning sind 7B+-Modelle konsistenter. GPT4All LocalDocs nutzt 3B für Dokument-Q&A.' }, { q: 'Ist Phi-4 Mini besser als Llama 3.2 3B für Codierung?', a: 'Ja. Phi-4 Mini erreicht 70% auf HumanEval vs 60% für Llama 3.2 3B -- aussagekräftige 10-Punkte-Lücke. Für Code-Hilfe auf 4-6 GB RAM ist Phi-4 Mini empfohlen. Für mehrsprachige Codierung (nicht-Python) ist Qwen2.5 3B mit 65% HumanEval wettbewerbsfähig und unterstützt Funktionsaufrufe.' }] },
        sources: { title: 'Quellen', items: ['Hugging Face Open LLM Leaderboard -- open-llm-leaderboard.hf.space (MMLU und HumanEval Werte)', 'Microsoft Phi-4 Technical Report -- microsoft.com/en-us/research/publication/phi-4-technical-report/', 'Meta Llama 3.2 Model Card -- huggingface.co/meta-llama/Llama-3.2-3B-Instruct', 'Google Gemma 2 Technical Report -- storage.googleapis.com/deepmind-media/gemma/gemma-2-report.pdf'] },
      },
    },
    fr: {
      theme: 'Best Models',
      title: 'Meilleurs petits LLMs locaux 2026 : modèles sub-4B pour machines à faible RAM',
      seoTitle: 'Meilleurs petits LLMs locaux 2026 : classement complet',
      metaDescription: 'Top 5 modèles sub-4B pour 4-8 GB RAM en 2026 : Phi-4 Mini (68% MMLU), Gemma 2 (plus rapide), Qwen2.5 (codage), Llama 3.2. Comparaison complète RGPD.',
      intro: 'Les petits LLMs locaux (1B-4B paramètres) fonctionnent sur des machines avec 4-8 GB RAM et produisent 30-70 tokens/sec sur CPU -- assez rapide pour le chat en temps réel. Les meilleurs petits modèles en 2026 sont Microsoft Phi-4 Mini 3.8B (meilleur reasoning), Google Gemma 2 2B (plus rapide), Qwen2.5 3B (meilleur codage), et Meta Llama 3.2 3B (meilleur usage général).',
      publishDate: '2026-04-04',
      readTime: '8 min',
      educationalLevel: 'Beginner',
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: 'Meilleurs petits LLMs locaux 2026 : modèles sub-4B pour machines à faible RAM',
        description: 'Meilleurs petits LLMs locaux 2026 : Phi-4 Mini (reasoning), Gemma 2 (vitesse), Qwen2.5 (codage), Llama 3.2 (utilisation générale). Comparaison complète pour RAM faible.',
        datePublished: '2026-04-04',
        dateModified: '2026-04-04',
        'url': 'https://www.promptquorum.com/local-llms/small-local-llm-models?lang=fr',
        'inLanguage': 'fr',
        author: { '@type': 'Person', 'name': 'Hans Kuepper', 'sameAs': 'https://www.promptquorum.com/author/hans-kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        about: [
          { '@type': 'Thing', name: 'Phi-4 Mini 3.8B' },
          { '@type': 'Thing', name: 'Gemma 2 2B' },
          { '@type': 'Thing', name: 'Qwen2.5 3B' },
          { '@type': 'Thing', name: 'Llama 3.2 3B' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'inLanguage': 'fr',
        mainEntity: [
          { '@type': 'Question', name: 'Quel est le plus petit LLM local qui produit une sortie utile ?', acceptedAnswer: { '@type': 'Answer', text: 'Depuis avril 2026, le minimum pratique pour une sortie utile est un modèle 3B à quantification Q4_K_M. Les modèles sous 2B paramètres produisent des phrases cohérentes mais peinent avec les instructions multi-étapes et le reasoning complexe. Pour la plupart des cas, commencez avec un modèle 3B.' } },
          { '@type': 'Question', name: 'Puis-je exécuter un modèle 3B sur un téléphone ?', acceptedAnswer: { '@type': 'Answer', text: 'Oui -- Llama 3.2 1B et 3B sont spécifiquement conçus pour le déploiement mobile sur appareil. Les inférences sur un téléphone moderne produisent 15-30 tok/sec pour les modèles 1B. Les frameworks mobiles comme MLC LLM supportent iOS, mais Ollama et LM Studio ne fonctionnent pas actuellement sur iOS/Android.' } },
          { '@type': 'Question', name: 'Les petits modèles sont-ils bons pour la synthèse ?', acceptedAnswer: { '@type': 'Answer', text: 'Oui -- la synthèse est l\'un des meilleurs cas d\'usage pour les petits modèles. Gemma 2 2B et Llama 3.2 3B produisent régulièrement des résumés précis de textes jusqu\'à ~4 000 mots.' } },
          { '@type': 'Question', name: 'Combien de fois plus rapide est un modèle 2B qu\'un modèle 7B sur le même matériel ?', acceptedAnswer: { '@type': 'Answer', text: 'Environ 2-3× plus rapide sur CPU. Gemma 2 2B génère 40-60 tok/sec vs 10-20 tok/sec pour Mistral 7B sur le même CPU portable. L\'avantage de vitesse est plus notable sur les machines CPU uniquement.' } },
          { '@type': 'Question', name: 'Les petits modèles supportent-ils l\'appel de fonction ?', acceptedAnswer: { '@type': 'Answer', text: 'Certains oui. Qwen2.5 3B supporte l\'appel de fonction et le mode JSON. Llama 3.2 3B a un support basique d\'utilisation d\'outils. Gemma 2 2B ne supporte pas l\'appel de fonction.' } },
          { '@type': 'Question', name: 'Quel petit modèle est meilleur pour les langues autres que l\'anglais ?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen2.5 3B supporte 29 langues nativement incluant le chinois, le japonais, le coréen et l\'arabe. Gemma 2 2B et Phi-4 Mini sont principalement optimisés pour l\'anglais. Pour les tâches non-anglais à l\'échelle du petit modèle, Qwen2.5 3B est le choix clair.' } },
          { '@type': 'Question', name: 'Quelle est la différence de qualité entre un modèle 3B et 7B ?', acceptedAnswer: { '@type': 'Answer', text: 'Un modèle 3B à 68% MMLU (Phi-4 Mini) performe de façon similaire à un GPT-3.5 Mini d\'ère 2023 sur les tâches générales. L\'écriture longue et le code complexe auront une qualité notablement inférieure.' } },
          { '@type': 'Question', name: 'Comment puis-je exécuter un petit LLM en français ?', acceptedAnswer: { '@type': 'Answer', text: 'Téléchargez le modèle avec Ollama : `ollama pull qwen2.5:3b` ou `ollama pull llama3.2:3b`. Démarrez une conversation en français avec `ollama run qwen2.5:3b`. Aucun paramètre de configuration spécial n\'est nécessaire -- les modèles produisent automatiquement du texte français de bonne qualité.' } },
          { '@type': 'Question', name: 'Quels sont les erreurs courantes avec les petits modèles locaux ?', acceptedAnswer: { '@type': 'Answer', text: 'Les erreurs courantes incluent : utiliser Q8_0 au lieu de Q4_K_M (consomme deux fois plus de RAM), exécuter la variante de base au lieu de la variante d\'instruction, et attendre une qualité de modèle 7B d\'un modèle 3B.' } },
        ],
      },
      sections: {},
    },
    ja: {
      theme: 'Best Models',
      title: '最高の小規模ローカルLLM 2026：低RAM向けSub-4Bモデル',
      seoTitle: '2026年最高の小型ローカルLLM：ベンチマーク完全ガイド',
      metaDescription: '4～8GB RAM向け最高5つの小型ローカルLLMモデル2026年完全比較：Phi-4 Mini（68% MMLU）、Gemma 2（最速）、Qwen2.5（コーディング）、Llama 3.2。',
      intro: '小規模ローカルLLM（1B～4Bパラメータ）は4～8GB RAMのマシンで動作し、CPU上で30～70トークン/秒を生成します。リアルタイムチャットに十分な速度です。2026年の最高の小規模モデルはMicrosoft Phi-4 Mini 3.8B（最高の推論）、Google Gemma 2 2B（最速）、Qwen2.5 3B（最高のコーディング）、Meta Llama 3.2 3B（最高の汎用）です。',
      publishDate: '2026-04-04',
      readTime: '8分',
      educationalLevel: 'Beginner',
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: '最高の小規模ローカルLLM 2026：低RAM向けSub-4Bモデル',
        description: '最高の小規模ローカルLLM 2026：Phi-4 Mini（推論）、Gemma 2（速度）、Qwen2.5（コーディング）、Llama 3.2（一般用途）。RAM制限されたマシン向けの完全な比較。',
        datePublished: '2026-04-04',
        dateModified: '2026-04-04',
        'url': 'https://www.promptquorum.com/local-llms/small-local-llm-models?lang=ja',
        'inLanguage': 'ja',
        author: { '@type': 'Person', 'name': 'Hans Kuepper', 'sameAs': 'https://www.promptquorum.com/author/hans-kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        about: [
          { '@type': 'Thing', name: 'Phi-4 Mini 3.8B' },
          { '@type': 'Thing', name: 'Gemma 2 2B' },
          { '@type': 'Thing', name: 'Qwen2.5 3B' },
          { '@type': 'Thing', name: 'Llama 3.2 3B' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'inLanguage': 'ja',
        mainEntity: [
          { '@type': 'Question', name: '有用な出力を生成する最小のローカルLLMは何ですか？', acceptedAnswer: { '@type': 'Answer', text: '2026年4月以降、有用な出力の実用的な最小値はQ4_K_M量子化での3Bモデルです。2Bパラメータ未満のモデルは一貫した文を生成しますが、複数ステップの指示と複雑な推論に苦労しています。ほとんどの場合、3Bモデルから始めてください。' } },
          { '@type': 'Question', name: '3Bモデルを携帯電話で実行できますか？', acceptedAnswer: { '@type': 'Answer', text: 'はい -- Llama 3.2 1Bと3Bはモバイルデバイスでの展開用に設計されています。最新の携帯電話での推論は1Bモデルで15～30トークン/秒を生成します。MLC LLMなどのモバイルフレームワークはiOSをサポートしていますが、OllamaとLM StudioはiOS/Androidで現在動作しません。' } },
          { '@type': 'Question', name: '小規模モデルは要約に適していますか？', acceptedAnswer: { '@type': 'Answer', text: 'はい -- 要約は小規模モデルの最適なユースケースの1つです。Gemma 2 2BとLlama 3.2 3Bは約4,000語までのテキストの正確な要約を一貫して生成します。' } },
          { '@type': 'Question', name: '2Bモデルは同じハードウェアで7Bモデルより何倍速いですか？', acceptedAnswer: { '@type': 'Answer', text: 'CPUで約2～3倍速いです。Gemma 2 2Bは同じノートパソコンのCPUでMistral 7Bの40～60トークン/秒対10～20トークン/秒を生成します。速度の利点はCPUのみのマシンで最も顕著です。' } },
          { '@type': 'Question', name: '小規模モデルは関数呼び出しをサポートしていますか？', acceptedAnswer: { '@type': 'Answer', text: 'いくつかサポートしています。Qwen2.5 3Bは関数呼び出しとJSONモードをサポートしています。Llama 3.2 3Bは基本的なツール使用をサポートしています。Gemma 2 2Bは関数呼び出しをサポートしていません。' } },
          { '@type': 'Question', name: '英語以外の言語に最適な小規模モデルはどれですか？', acceptedAnswer: { '@type': 'Answer', text: 'Qwen2.5 3Bは中国語、日本語、韓国語、アラビア語を含む29言語をネイティブにサポートしています。Gemma 2 2BとPhi-4 Miniは主に英語用に最適化されています。小規模モデルスケールの非英語タスクの場合、Qwen2.5 3Bが明確な選択肢です。' } },
          { '@type': 'Question', name: '3Bモデルと7Bモデルの品質の違いは何ですか？', acceptedAnswer: { '@type': 'Answer', text: '68% MMLU（Phi-4 Mini）の3Bモデルは、一般的なタスクで2023年のGPT-3.5 Miniと同様のパフォーマンスです。長い文と複雑なコードはかなり低い品質になります。' } },
          { '@type': 'Question', name: '日本語で小規模LLMを実行するにはどうすればよいですか？', acceptedAnswer: { '@type': 'Answer', text: 'Ollamaでモデルをダウンロードします：`ollama pull qwen2.5:3b`または`ollama pull llama3.2:3b`。`ollama run qwen2.5:3b`で日本語で会話を始めます。特別な設定パラメータは不要です -- モデルは自動的に高品質の日本語テキストを生成します。' } },
        ],
      },
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**小規模スケールでの最高の推論**: Phi-4 Mini 3.8B -- 68% MMLU、70% HumanEval、4 GB RAMで動作。',
            '**CPUで最速**: Gemma 2 2B -- 最新のノートパソコンのCPUで40～60トークン/秒、1.7 GB RAM。',
            '**最高の小規模コーディングモデル**: Qwen2.5 3B -- ~2 GB RAMで65% HumanEval。',
            '**最高の汎用3Bモデル**: Llama 3.2 3B -- 最も多くのコミュニティサポート、128Kコンテキスト、2.5 GB RAM。',
            '2026年4月現在、2B以下のモデルはプロフェッショナルなタスクに適した出力品質を生成しません。実務では3B以上を使用してください。',
          ],
        },
        whatIsSmall: {
          title: '「小規模」ローカルLLMとは何か、そしていつ使うべきか？',
          content: [
            '**小規模ローカルLLMは、通常、40億未満のパラメータを持つモデルとして定義されます。** Q4_K_M量子化では、これらのモデルは1.5～3 GBのRAMを必要とします。これは、4～8 GBの総メモリを持つエントリーレベルノートパソコンの制約内です。',
            '2026年4月現在、小規模モデルは以下に適しています：クイック要約、シンプルなQ&A、コードスニペット説明、短いテキストの翻訳、分類タスク。複数ステップの推論、複雑なコード生成、長い一貫した文書の作成には適していません。',
            '3Bモデルと7Bモデル間の品質ギャップは重大です。GPT-3.5 MiniとGPT-3.5 Turbo間のギャップとほぼ同等です。8 GB RAMを持つユーザーの場合、マシンに余裕があれば、Q4_K_Mの7Bモデルがほぼ常に良い選択です。7B推奨については、[最高の初心者向けローカルLLMモデル](/local-llms/best-beginner-local-llm-models)を参照してください。',
          ],
        },
        phi4mini: {
          title: 'Phi-4 Mini 3.8B -- Sub-4Bクラスで最高の推論パフォーマンス',
          content: [
            '**Microsoft Phi-4 MiniはMMLA68%、HumanEval70%を達成します。** これらのスコアは2025年より前にリリースされた多くの7Bモデルを上回っています。これが可能な理由は、Phi-4 Miniが広いウェブテキストではなく、推論と問題解決に焦点を当てた管理されたシンセティックデータセットで訓練されたためです。',
            '2026年4月現在、Phi-4 Miniは、主に推論（数学、論理、段階的説明）またはコード支援が必要で、4～6 GB RAMのハードウェアを持つユーザーに推奨される選択肢です。',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '68%' },
            { 'Spec': 'HumanEval', 'Value': '70%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2.5 GB' },
            { 'Spec': 'コンテキスト', 'Value': '128Kトークン' },
            { 'Spec': 'CPU速度', 'Value': '30～50トークン/秒' },
            { 'Spec': 'Ollamaコマンド', 'Value': 'ollama run phi4-mini' },
          ],
          columns: ['Spec', 'Value'],
        },
        gemma2: {
          title: 'Gemma 2 2B -- CPUで最速の小規模ローカルLLM',
          content: [
            '**Google Gemma 2 2Bは、モダンノートパソコンのCPUで40～60トークン/秒を生成します。** この品質帯域内のモデルの中で最速です。1.7 GB RAMのフットプリントにより、4 GBマシン上のOSと他のアプリケーション用に十分なメモリが残ります。',
            '推論タスクではPhi-4 MiniまたはLlama 3.2 3Bより品質が低いです。8Kコンテキストウィンドウ（Phi-4 MiniとLlama 3.2の128Kに対して）は、より長い文書の実用的な制限です。応答速度が出力の深さより重要な場合、Gemma 2 2Bが正しい選択です。',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '52%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~1.7 GB' },
            { 'Spec': 'コンテキスト', 'Value': '8Kトークン' },
            { 'Spec': 'CPU速度', 'Value': '40～60トークン/秒' },
            { 'Spec': 'Ollamaコマンド', 'Value': 'ollama run gemma2:2b' },
          ],
          columns: ['Spec', 'Value'],
        },
        qwen25_3b: {
          title: 'Qwen2.5 3B -- コーディングタスク向けの最高の小規模モデル',
          content: [
            '**Qwen2.5 3BはHumanEvalで65%のスコアを獲得し、Llama 3.2 3Bより5ポイント高く、3Bスケールでのコーディングタスクに最適です。**JSONモードと関数呼び出しサポートを含み、29言語をネイティブに処理します。',
            '英語での非コーディングタスクについては、Llama 3.2 3BとPhi-4 Miniはより自然なプロスを生成します。コーディングまたは多言語出力が主なユースケースの場合、特にQwen2.5 3Bを選択してください。',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '62%' },
            { 'Spec': 'HumanEval', 'Value': '65%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2 GB' },
            { 'Spec': 'コンテキスト', 'Value': '128Kトークン' },
            { 'Spec': 'CPU速度', 'Value': '25～40トークン/秒' },
            { 'Spec': 'Ollamaコマンド', 'Value': 'ollama run qwen2.5:3b' },
          ],
          columns: ['Spec', 'Value'],
        },
        llama32_3b: {
          title: 'Llama 3.2 3B -- 最高の汎用小規模モデル',
          content: [
            '**Meta Llama 3** .2 3Bは、最も広くドキュメント化され、コミュニティがサポートする3Bモデルです。MMLU58%、HumanEval60%のスコアは、両方でPhi-4 Miniを若干下回りますが、最も広いツールサポート、最も利用可能なファインチューン、最大のコミュニティガイドコレクションを備えています。',
            '128Kコンテキストウィンドウは、より大きなLlama 3.xモデルと同じで、中程度の長さの文書の要約に適しています。最初の小規模モデルとして、Llama 3.2 3Bは予測可能な動作と広範なドキュメンテーションのため、最も安全な選択のままです。',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '58%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2.5 GB' },
            { 'Spec': 'コンテキスト', 'Value': '128Kトークン' },
            { 'Spec': 'CPU速度', 'Value': '25～45トークン/秒' },
            { 'Spec': 'Ollamaコマンド', 'Value': 'ollama run llama3.2:3b' },
          ],
          columns: ['Spec', 'Value'],
        },
        llama32_1b: {
          title: 'Llama 3.2 1B -- 有用な出力のための絶対最小値',
          content: 'Llama 3.2 1Bはわずか1.3 GBのRAMを必要とし、CPUで60～90トークン/秒を生成します。最も高速なローカル実行可能モデルです。出力品質は限界的です：非常にシンプルな分類とキーワード抽出を処理しますが、一貫した複数文の応答に苦労します。2026年4月現在、RAMが本当に制約（3 GB未満）である場合、またはツール統合をテストする場合のみ、Llama 3.2 1Bを使用してください。',
        },
        comparisonTable: {
          title: '完全比較：4B未満の最高の小規模ローカルLLM',
          rows: [
            { 'モデル': 'Phi-4 Mini 3.8B', 'MMLU': '68%', 'HumanEval': '70%', 'RAM': '2.5 GB', 'コンテキスト': '128K', '最適用途': '推論、コーディング' },
            { 'モデル': 'Qwen2.5 3B', 'MMLU': '62%', 'HumanEval': '65%', 'RAM': '2 GB', 'コンテキスト': '128K', '最適用途': 'コーディング、多言語' },
            { 'モデル': 'Llama 3.2 3B', 'MMLU': '58%', 'HumanEval': '60%', 'RAM': '2.5 GB', 'コンテキスト': '128K', '最適用途': '汎用、最初のモデル' },
            { 'モデル': 'Gemma 2 2B', 'MMLU': '52%', 'HumanEval': '38%', 'RAM': '1.7 GB', 'コンテキスト': '8K', '最適用途': '速度、非常に低いRAM' },
            { 'モデル': 'Llama 3.2 1B', 'MMLU': '32%', 'HumanEval': '28%', 'RAM': '1.3 GB', 'コンテキスト': '128K', '最適用途': '絶対最小RAM' },
          ],
          columns: ['モデル', 'MMLU', 'HumanEval', 'RAM', 'コンテキスト', '最適用途'],
        },
        regionalContext: {
          title: '地域別の小規模ローカルLLM',
          content: [
            '**日本（METI）：** 小規模モデルティアでの日本語タスクについては、この比較の唯一のモデルであるネイティブな日本語トークン化はQwen2.5 3Bです。Llama 3.2 3Bは日本語を処理しますが、トークン効率は低くなります。RAM制約の下での日本語要約または翻訳の場合：`ollama run qwen2.5:3b`。小規模モデルの速度の利点は日本企業の使用に特に関連しています。CPUで25～40トークン/秒は、標準的な職場ハードウェア上のチャットインターフェースに適切なリアルタイム応答を提供します。日本の独立系企業向けMETIガイダンスに準拠した小規模モデルの実装については、Ollama経由のローカル展開がすべてのテキスト処理をオンデバイスに保つため推奨されます。',
            '**中国：** Qwen2.5 3B（Alibaba、Apache 2.0）は、中国語の小規模モデル展開の自然な選択です。ネイティブな中国語トークン化により、同等のパラメータ数のLlamaより30～40%効率的に中国語テキストを処理します。IoTおよび中国のデータセキュリティ法（数据安全法）下でのエッジ展開の場合：`ollama run qwen2.5:3b`は4 GB RAMを備えた任意のLinuxデバイスで動作し、外部APIコールなしですべてのテキストをオンデバイスで処理します。',
            '**その他の地域：** 英語ユースケースの場合、Phi-4 Mini 3.8BはCPUベースのシステムで最高の推論品質を提供します。コストの最適化と速度が重要な場合、Gemma 2 2Bはスケールできる推論基盤を最小限のメモリで提供します。',
          ],
        },
        commonMistakes: {
          title: '小規模ローカルLLMを実行する場合の一般的な誤り',
          items: [
            '**Q4_K_Mの代わりにQ8_0量子化を使用する：** Q8_0は、小規模での品質改善がわずかなため、Q4_K_Mのほぼ2倍のRAMを必要とします。Llama 3.2 3BモデルのQ8_0は~3.8 GB RAMが必要で、Q4_K_Mでは~2.5 GBです。4 GBマシンではQ8_0はスワップ使用をトリガーし、推論を3～5倍遅くする可能性があります。Sub-4BモデルではデフォルトとしてQ4_K_Mを常に使用してください。',
            '**命令バリアント代わりにベースモデルを実行する：** ベースモデル（例：`llama3.2:3b-text`）は、テキスト内の次のトークンを予測するようにトレーニングされた事前ファインチューニングチェックポイントです。指示に従いません。ベースモデルに「2+2は何ですか？」と聞くと、「4」と答える代わりにクイズとして文を完成させるかもしれません。常に命令バリアントを使用してください：`llama3.2:3b`（Ollamaは名前付きモデルのデフォルトで命令を使用）。',
            '**3Bモデルから7Bモデルの品質を期待する：** 68% MMLU（Phi-4 Mini）の3Bモデルは、一般的なタスクで2023年のGPT-3.5 Miniと同様にパフォーマンスします。複雑な推論チェーン、長文の作成、微妙なコード生成は、7Bモデルより顕著に低い品質を生成します。出力品質が不十分な場合は、7Bモデルにアップグレードしてください。RAMの差は~2 GB（2.5 GB → 4.5 GB）です。',
          ],
        },
        relatedReading: {
          title: '関連資料',
          items: [
            '[最高の初心者向けローカルLLMモデル](/local-llms/best-beginner-local-llm-models) -- 8 GB RAMが利用可能で、品質が3Bからステップアップする必要がある場合の7B推奨',
            '[最初のローカルLLMを実行する](/local-llms/run-first-local-llm) -- Ollamaを使用して10分未満でこのページの任意のモデルをプルして実行するステップバイステップガイド',
            '[ノートパソコン上のローカルLLM](/local-llms/local-llm-on-laptop) -- RAM制約の下での持続的な推論のための熱管理とバッテリー管理',
            '[LLM量子化の説明](/local-llms/llm-quantization-explained) -- Q4_K_Mがデフォルトである理由と、極端なRAM制約のためにQ3_K_Mを考慮する場合',
            '[最高のローカルコーディング用LLM](/local-llms/best-local-llms-for-coding) -- Qwen2.5 3Bが複雑なタスクに十分でない場合の7B+スケールのコード固有モデル',
            '[ローカルLLMセットアップのトラブルシューティング](/local-llms/troubleshooting-local-llm-setup) -- RAM制約マシンで一般的なOOMエラー、遅い推論、モデルロードの失敗を修正',
          ],
        },
        faqSection: {
          id: 'faq',
          title: '小規模ローカルLLMモデルについてのよくある質問',
          faqs: [
            {
              q: '有用な出力を生成する最小のローカルLLMは何ですか？',
              a: '2026年4月現在、有用な出力の実用的な最小値はQ4_K_M量子化での3Bモデルです。2B以下のパラメータを持つモデル（Llama 3.2 1B、Gemma 2 2B）は一貫した単一文を生成しますが、複数ステップの指示と複雑な推論に苦労しています。要約やシンプルなQ&Aなどのタスクの場合、Gemma 2 2Bは使用可能です。より複雑な場合は、3Bモデルから始めてください。',
            },
            {
              q: '3Bモデルを電話で実行できますか？',
              a: 'はい -- Llama 3.2 1Bと3Bは、オンデバイスのモバイル展開用に設計されています。Metaは、iOS（MLC LLM経由）およびAndroid向けの最適化されたビルドを提供します。モダンフォン（Snapdragon 8 Gen 3またはApple A17 Pro）での推論は、1Bモデルで15～30トークン/秒を生成します。LM StudioとOllamaは現在iOSまたはAndroidで動作しません。モバイルには別のフレームワークが必要です。',
            },
            {
              q: '小規模モデルは要約に適していますか？',
              a: 'はい -- 要約は小規模モデルの最強のユースケースの1つです。Gemma 2 2BとLlama 3.2 3Bは、~4,000語までのテキスト（品質出力の実用的なコンテキスト制限）の正確な要約を確実に生成します。より長い文書の場合は、Phi-4 MiniまたはLlama 3.2 3B（両方で128Kトークン）のような大きなコンテキストウィンドウを持つモデルを使用してください。',
            },
            {
              q: '2Bモデルは同じハードウェアで7Bモデルより何倍速いですか？',
              a: 'CPU上で約2～3倍速いです。Gemma 2 2Bは同じノートパソコンのCPUでMistral 7Bより40～60トークン/秒対10～20トークン/秒を生成します。GPUではスピード利点は狭くなります。スピード差はCPUのみのマシンで最も顕著です。',
            },
            {
              q: '小規模モデルは関数呼び出しをサポートしていますか？',
              a: 'いくつかサポートしています。Qwen2.5 3Bは関数呼び出しとJSONモードをサポートしています。Llama 3.2 3Bは基本的なツール使用をサポートしています。Gemma 2 2Bは関数呼び出しをサポートしていません。構造化された出力に依存するパイプラインを構築する前に、モデルのドキュメントを確認してください。',
            },
            {
              q: '英語以外の言語に最適な小規模モデルはどれですか？',
              a: 'Qwen2.5 3Bは、中国語、日本語、韓国語、アラビア語を含む29言語をネイティブにサポートしています。Gemma 2 2BとPhi-4 Miniは主に英語最適化されています。小規模モデルスケールでの非英語タスクの場合、Qwen2.5 3Bが明確な選択肢です。[Qwen vs Llama vs Mistral 多言語比較](/local-llms/qwen-vs-llama-vs-mistral)で完全な言語比較を参照してください。',
            },
            {
              q: '日常的なタスクでのPhi-4 MiniとLlama 3.2 3Bの違いは何ですか？',
              a: 'Phi-4 Miniはほぼ同じRAM（各2.5 GB）で推論、数学、コーディングでLlama 3.2 3Bを上回ります（68%対58% MMLU、70%対60% HumanEval）。日常的なタスク -- Q&A、要約、シンプルな説明 -- では、品質ギャップは顕著ですが劇的ではありません。Llama 3.2 3Bはより広いコミュニティサポートとより多くのファインチューンが利用可能です。構造化された推論にはPhi-4 Miniを選択し、汎用チャットと互換性にはLlama 3.2 3Bを選択してください。',
            },
            {
              q: '2つの小規模モデルを同時に実行できますか？',
              a: 'はい、合計RAMが許可する場合。Q4_K_Mで2つの3Bモデルは~5 GB組み合わされて使用します。リーンなOSを備えた8 GBマシンでは実行可能です。Ollamaはデフォルトでプロセスごとに一度に1つのモデルをロードします。異なるポート（OLLAMA_HOST=:11434とOLLAMA_HOST=:11435）で2つのOllamaインスタンスを実行して、2つのモデルを並行して提供してください。これは出力をA/Bテストするのに役立ちます。',
            },
            {
              q: '小規模モデルはRAG（検索拡張生成）に機能しますか？',
              a: 'シンプルなRAGの場合ははい。Llama 3.2 3BとPhi-4 Miniは、取得した文書チャンク上の質問に確実に答えることができます。複数ホップの推論が必要な大規模な知識ベース上のRAGの場合、7B+モデルはより一貫してパフォーマンスします。GPT4AllのLocalDocsフィーチャーはドキュメントQ&Aに3Bモデルを使用し、個人ドキュメント集合に対してうまく動作します。',
            },
            {
              q: 'Phi-4 MiniはコーディングでLlama 3.2 3Bより優れていますか？',
              a: 'はい。Phi-4 Miniはこのスケールで意味のある10ポイントギャップでLlama 3.2 3Bの60%対70% HumanEvalスコアを達成します。4～6 GB RAMマシンでのコーディング支援の場合、Phi-4 Miniが推奨される選択肢です。多言語コーディング（非Python）の場合、65% HumanEvalのQwen2.5 3Bはphi-4 Miniと競争力があり、関数呼び出しもサポートしています。',
            },
          ],
        },
        sources: {
          title: 'ソース',
          items: [
            'Hugging Face Open LLM Leaderboard -- open-llm-leaderboard.hf.space（MMLUとHumanEvalスコア）',
            'Microsoft Phi-4技術レポート -- microsoft.com/en-us/research/publication/phi-4-technical-report/',
            'Meta Llama 3.2モデルカード -- huggingface.co/meta-llama/Llama-3.2-3B-Instruct',
            'Google Gemma 2技術レポート -- storage.googleapis.com/deepmind-media/gemma/gemma-2-report.pdf',
          ],
        },
      },
    },
    zh: {
      theme: 'Best Models',
      title: '2026年最佳小型本地LLM：低RAM机器的Sub-4B模型',
      seoTitle: '2026年最佳小型本地LLM：5大模型性能完整对比',
      metaDescription: '2026年4-8GB RAM最佳5大小型本地LLM完整对比：Phi-4 Mini（68% MMLU）、Gemma 2（最快速度）、Qwen2.5（编码最优）、Llama 3.2（通用推荐）。',
      intro: '小型本地LLM（1B-4B参数）在4-8GB RAM的机器上运行，在CPU上生成30-70个令牌/秒----足够用于实时聊天。2026年最好的小型模型是Microsoft Phi-4 Mini 3.8B（最佳推理）、Google Gemma 2 2B（最快）、Qwen2.5 3B（最佳编码）和Meta Llama 3.2 3B（最佳通用用途）。',
      publishDate: '2026-04-04',
      readTime: '8分钟',
      educationalLevel: 'Beginner',
schema: {
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: '2026年最佳小型本地LLM：低RAM机器的Sub-4B模型',
        description: '2026年最佳小型本地LLM：Phi-4 Mini（推理）、Gemma 2（速度）、Qwen2.5（编码）、Llama 3.2（通用）。RAM受限机器的完整比较。',
        datePublished: '2026-04-04',
        dateModified: '2026-04-04',
        'url': 'https://www.promptquorum.com/local-llms/small-local-llm-models?lang=zh',
        'inLanguage': 'zh',
        author: { '@type': 'Person', 'name': 'Hans Kuepper', 'sameAs': 'https://www.promptquorum.com/author/hans-kuepper' },
        publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
        about: [
          { '@type': 'Thing', name: 'Phi-4 Mini 3.8B' },
          { '@type': 'Thing', name: 'Gemma 2 2B' },
          { '@type': 'Thing', name: 'Qwen2.5 3B' },
          { '@type': 'Thing', name: 'Llama 3.2 3B' },
        ],
      },
      faqSchema: {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'inLanguage': 'zh',
        mainEntity: [
          { '@type': 'Question', name: '生成有用输出的最小本地LLM是什么？', acceptedAnswer: { '@type': 'Answer', text: '截至2026年4月，有用输出的实际最小值是Q4_K_M量化下的3B模型。2B参数以下的模型可以生成连贯的单句，但在多步骤指令和复杂推理方面表现不佳。对于大多数情况，从3B模型开始。' } },
          { '@type': 'Question', name: '我可以在手机上运行3B模型吗？', acceptedAnswer: { '@type': 'Answer', text: '可以----Llama 3.2 1B和3B专为移动设备部署而设计。在现代手机上的推理为1B模型生成15-30个令牌/秒。MLC LLM等移动框架支持iOS，但Ollama和LM Studio目前不能在iOS/Android上运行。' } },
          { '@type': 'Question', name: '小型模型适合摘要总结吗？', acceptedAnswer: { '@type': 'Answer', text: '可以----摘要总结是小型模型最好的用例之一。Gemma 2 2B和Llama 3.2 3B可靠地生成长达约4,000个单词的文本摘要。' } },
          { '@type': 'Question', name: '2B模型比同一硬件上的7B模型快多少倍？', acceptedAnswer: { '@type': 'Answer', text: '在CPU上快约2-3倍。Gemma 2 2B在同一笔记本电脑CPU上生成40-60个令牌/秒，相比Mistral 7B的10-20个令牌/秒。速度优势在仅CPU的机器上最为明显。' } },
          { '@type': 'Question', name: '小型模型支持函数调用吗？', acceptedAnswer: { '@type': 'Answer', text: '有些支持。Qwen2.5 3B支持函数调用和JSON模式。Llama 3.2 3B具有基本的工具使用支持。Gemma 2 2B不支持函数调用。' } },
          { '@type': 'Question', name: '哪个小型模型对英语以外的语言最佳？', acceptedAnswer: { '@type': 'Answer', text: 'Qwen2.5 3B原生支持29种语言，包括中文、日语、韩语和阿拉伯语。Gemma 2 2B和Phi-4 Mini主要针对英语优化。对于小模型规模的非英语任务，Qwen2.5 3B是明确的选择。' } },
          { '@type': 'Question', name: '3B模型和7B模型的质量差异是什么？', acceptedAnswer: { '@type': 'Answer', text: '一个68% MMLU（Phi-4 Mini）的3B模型在通用任务上的性能与2023年的GPT-3.5 Mini相似。较长的文本和复杂代码会有显著较低的质量。' } },
          { '@type': 'Question', name: '我如何用中文运行小型LLM？', acceptedAnswer: { '@type': 'Answer', text: '使用Ollama下载模型：`ollama pull qwen2.5:3b`或`ollama pull llama3.2:3b`。使用`ollama run qwen2.5:3b`开始中文对话。无需特殊配置参数----模型自动生成高质量中文文本。' } },
        ],
      },
      sections: {
        tldr: {
          id: 'key-takeaways',

          isTldr: true,
          items: [
            '**小规模规模的最佳推理**: Phi-4 Mini 3.8B -- 68% MMLU，70% HumanEval，运行于4 GB RAM。',
            '**CPU上最快**: Gemma 2 2B -- 任何现代笔记本电脑CPU上40-60令牌/秒，1.7 GB RAM。',
            '**最好的小规模编码模型**: Qwen2.5 3B -- 〜2 GB RAM下65% HumanEval。',
            '**最好的通用3B模型**: Llama 3.2 3B -- 最多社区支持，128K上下文，2.5 GB RAM。',
            '截至2026年4月，2B以下的模型无法生成适合专业任务的输出质量。对于实际工作，使用3B或更大的模型。',
          ],
        },
        whatIsSmall: {
          title: '什么是"小型"本地LLM，何时应该使用它？',
          content: [
            '**小型本地LLM通常定义为参数少于40亿的模型。** 在Q4_K_M量化下，这些模型需要1.5-3 GB的RAM，完全在具有4-8 GB总内存的入门级笔记本电脑的约束范围内。',
            '截至2026年4月，小型模型适合：快速摘要、简单问答、代码片段解释、短文本翻译和分类任务。不适合多步推理、复杂代码生成或长篇一致的文档编写。',
            '3B模型和7B模型之间的质量差距很大，大致相当于GPT-3.5 Mini和GPT-3.5 Turbo之间的差距。对于拥有8 GB RAM的用户，如果机器有余量，Q4_K_M的7B模型几乎总是更好的选择。有关7B建议，请参阅[最佳初学者本地LLM模型](/local-llms/best-beginner-local-llm-models)。',
          ],
        },
        phi4mini: {
          title: 'Phi-4 Mini 3.8B -- Sub-4B类中最佳推理性能',
          content: [
            '**Microsoft Phi-4 Mini在MMLU上达到68%，在HumanEval上达到70%，这些得分超过了许多2025年之前发布的7B模型。** 之所以可能，是因为Phi-4 Mini在专注于推理和问题解决的精选合成数据集上进行了训练，而不是广泛的网络文本。',
            '截至2026年4月，Phi-4 Mini是需要推理（数学、逻辑、分步解释）或在4-6 GB RAM硬件上进行编码协助的用户的推荐选择。',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '68%' },
            { 'Spec': 'HumanEval', 'Value': '70%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2.5 GB' },
            { 'Spec': '上下文', 'Value': '128K令牌' },
            { 'Spec': 'CPU速度', 'Value': '30-50令牌/秒' },
            { 'Spec': 'Ollama命令', 'Value': 'ollama run phi4-mini' },
          ],
          columns: ['Spec', 'Value'],
        },
        gemma2: {
          title: 'Gemma 2 2B -- CPU上最快的小型本地LLM',
          content: [
            '**Google Gemma 2 2B在现代笔记本电脑CPU上生成40-60令牌/秒，是该质量层级内最快的模型。** 其1.7 GB RAM占用空间在4 GB机器上为OS和其他应用程序留下充足的内存。',
            '在推理任务上的质量低于Phi-4 Mini或Llama 3.2 3B。8K上下文窗口（相对于Phi-4 Mini和Llama 3.2的128K）对于较长的文档是实际限制。当响应速度比输出深度更重要时，Gemma 2 2B是正确的选择。',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '52%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~1.7 GB' },
            { 'Spec': '上下文', 'Value': '8K令牌' },
            { 'Spec': 'CPU速度', 'Value': '40-60令牌/秒' },
            { 'Spec': 'Ollama命令', 'Value': 'ollama run gemma2:2b' },
          ],
          columns: ['Spec', 'Value'],
        },
        qwen25_3b: {
          title: 'Qwen2.5 3B -- 编码任务的最佳小型模型',
          content: [
            '**Qwen2.5 3B在HumanEval上得分65%，比Llama 3.2 3B高5个百分点，使其成为3B规模编码任务的最佳选择。**它支持JSON模式和函数调用，并原生处理29种语言。',
            '对于英文的非编码任务，Llama 3.2 3B和Phi-4 Mini会产生更自然的散文。特别是在编码或多语言输出是主要用例时，选择Qwen2.5 3B。',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '62%' },
            { 'Spec': 'HumanEval', 'Value': '65%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2 GB' },
            { 'Spec': '上下文', 'Value': '128K令牌' },
            { 'Spec': 'CPU速度', 'Value': '25-40令牌/秒' },
            { 'Spec': 'Ollama命令', 'Value': 'ollama run qwen2.5:3b' },
          ],
          columns: ['Spec', 'Value'],
        },
        llama32_3b: {
          title: 'Llama 3.2 3B -- 最好的通用小型模型',
          content: [
            '**Meta Llama 3** .2 3B是最广泛记录的、社区支持最多的3B模型。它在MMLU上得分58%，在HumanEval上得分60%，在两者上都略低于Phi-4 Mini，但拥有最广泛的工具支持、最多可用的微调和最大的社区指南集合。',
            '128K上下文窗口与更大的Llama 3.x模型相同，适合总结中等长度的文档。作为第一个小型模型，Llama 3.2 3B因其可预测的行为和广泛的文档记录而仍然是最安全的选择。',
          ],
          rows: [
            { 'Spec': 'MMLU', 'Value': '58%' },
            { 'Spec': 'RAM (Q4_K_M)', 'Value': '~2.5 GB' },
            { 'Spec': '上下文', 'Value': '128K令牌' },
            { 'Spec': 'CPU速度', 'Value': '25-45令牌/秒' },
            { 'Spec': 'Ollama命令', 'Value': 'ollama run llama3.2:3b' },
          ],
          columns: ['Spec', 'Value'],
        },
        llama32_1b: {
          title: 'Llama 3.2 1B -- 任何有用输出的绝对最小值',
          content: 'Llama 3.2 1B仅需1.3 GB RAM，在CPU上生成60-90令牌/秒，是最快的本地运行模型。输出质量是边界的：它处理非常简单的分类和关键词提取，但在连贯的多句响应上苦恼。截至2026年4月，仅在RAM是真正约束（可用3 GB以下）或测试工具集成时使用Llama 3.2 1B。',
        },
        comparisonTable: {
          title: '完整比较：4B以下最好的小型本地LLM',
          rows: [
            { '模型': 'Phi-4 Mini 3.8B', 'MMLU': '68%', 'HumanEval': '70%', 'RAM': '2.5 GB', '上下文': '128K', '最适合': '推理、编码' },
            { '模型': 'Qwen2.5 3B', 'MMLU': '62%', 'HumanEval': '65%', 'RAM': '2 GB', '上下文': '128K', '最适合': '编码、多语言' },
            { '模型': 'Llama 3.2 3B', 'MMLU': '58%', 'HumanEval': '60%', 'RAM': '2.5 GB', '上下文': '128K', '最适合': '通用、首个模型' },
            { '模型': 'Gemma 2 2B', 'MMLU': '52%', 'HumanEval': '38%', 'RAM': '1.7 GB', '上下文': '8K', '最适合': '速度、非常低RAM' },
            { '模型': 'Llama 3.2 1B', 'MMLU': '32%', 'HumanEval': '28%', 'RAM': '1.3 GB', '上下文': '128K', '最适合': '绝对最小RAM' },
          ],
          columns: ['模型', 'MMLU', 'HumanEval', 'RAM', '上下文', '最适合'],
        },
        regionalContext: {
          title: '按地区的小型本地LLM',
          content: [
            '**中国（数据安全法）：** Qwen2.5 3B（阿里巴巴，Apache 2.0）是中文小型模型部署的自然选择。原生中文标记化以相当的参数数与Llama相比，处理普通话文本的效率提高30-40%。对于IoT和中国《数据安全法》（数据安全法）下的边缘部署：`ollama run qwen2.5:3b`在配备4 GB RAM的任何Linux设备上运行，并在设备上处理所有文本，不进行外部API调用。本地Ollama部署保持所有文本处理在设备上，符合《数据安全法》对数据驻留和非跨境传输的要求。',
            '**日本：** 对于小型模型层的日文任务，此比较中唯一的原生日文标记化是Qwen2.5 3B。Llama 3.2 3B处理日文但标记效率较低。对于RAM约束下的日文摘要或翻译：`ollama run qwen2.5:3b`。小型模型的速度优势对日本企业使用特别相关：CPU上25-40令牌/秒为标准办公硬件上的聊天界面提供适当的实时响应。',
            '**其他地区：** 对于英文用例，Phi-4 Mini 3.8B在基于CPU的系统上提供最佳推理质量。当成本优化和速度很重要时，Gemma 2 2B以最小的内存提供可扩展的推理基础。',
          ],
        },
        commonMistakes: {
          title: '运行小型本地LLM时的常见错误',
          items: [
            '**使用Q8_0量化而不是Q4_K_M：** Q8_0需要Q4_K_M的几乎两倍RAM，质量改进最少。Llama 3.2 3B模型在Q8_0下需要~3.8 GB RAM对比Q4_K_M下的~2.5 GB。在4 GB机器上，Q8_0可能触发交换使用并使推理速度降低3-5倍。对于Sub-4B模型，始终使用Q4_K_M作为默认值。',
            '**运行基础模型而不是指令变体：** 基础模型（例如`llama3.2:3b-text`）是预先微调的检查点，经训练用于预测文本中的下一个令牌。它们不遵循指令。当您问基础模型"2+2是什么？"时，它可能将句子作为测验完成而不是回答"4"。始终使用指令变体：`llama3.2:3b`（Ollama对命名模型默认为指令）。',
            '**期望从3B模型获得7B模型质量：** 68% MMLU（Phi-4 Mini）的3B模型在一般任务上的表现与2023年代的GPT-3.5 Mini相似。复杂推理链、长篇写作和细微代码生成将产生明显低于7B模型的质量。如果输出质量不足，升级到7B模型----RAM差异约为2 GB（2.5 GB → 4.5 GB）。',
          ],
        },
        relatedReading: {
          title: '相关阅读',
          items: [
            '[最佳初学者本地LLM模型](/local-llms/best-beginner-local-llm-models) -- 当8 GB RAM可用且质量需要从3B升级时的7B推荐',
            '[运行您的第一个本地LLM](/local-llms/run-first-local-llm) -- 使用Ollama在10分钟内拉取和运行此页面上任何模型的分步指南',
            '[笔记本电脑上的本地LLM](/local-llms/local-llm-on-laptop) -- 在RAM约束下进行持续推理的热管理和电池管理',
            '[LLM量化解释](/local-llms/llm-quantization-explained) -- 为什么Q4_K_M是默认值以及何时为极端RAM约束考虑Q3_K_M',
            '[最佳本地编码LLM](/local-llms/best-local-llms-for-coding) -- 当Qwen2.5 3B不足以完成复杂任务时的7B+规模编码特定模型',
            '[本地LLM设置故障排除](/local-llms/troubleshooting-local-llm-setup) -- 修复RAM约束机器上常见的OOM错误、缓慢推理和模型加载失败',
          ],
        },
        faqSection: {
          id: 'faq',
          title: '关于小型本地LLM模型的常见问题',
          faqs: [
            {
              q: '生成有用输出的最小本地LLM是什么？',
              a: '截至2026年4月，有用输出的实际最小值是Q4_K_M量化下的3B模型。2B以下参数的模型生成连贯的单句但在多步骤指令和复杂推理上苦恼。对于摘要和简单问答等任务，Gemma 2 2B是可用的。对于更复杂的任务，从3B模型开始。',
            },
            {
              q: '我可以在电话上运行3B模型吗？',
              a: '可以----Llama 3.2 1B和3B专为设备上移动部署而设计。Meta为iOS（通过MLC LLM）和Android提供优化的构建。在现代手机上的推理为1B模型生成15-30令牌/秒。LM Studio和Ollama目前不在iOS或Android上运行----移动需要单独的框架。',
            },
            {
              q: '小型模型适合摘要吗？',
              a: '是的----摘要是小型模型最强的用例之一。Gemma 2 2B和Llama 3.2 3B可靠地生成高达〜4,000字的文本的准确摘要。对于较长的文档，使用具有大上下文窗口的模型，如Phi-4 Mini或Llama 3.2 3B（均128K令牌）。',
            },
            {
              q: '2B模型在相同硬件上比7B模型快多少倍？',
              a: '在CPU上大约快2-3倍。Gemma 2 2B在同一笔记本电脑CPU上生成40-60令牌/秒对Mistral 7B的10-20令牌/秒。在GPU上，速度优势缩小。速度差在仅CPU的机器上最明显。',
            },
            {
              q: '小型模型支持函数调用吗？',
              a: '有些支持。Qwen2.5 3B支持函数调用和JSON模式。Llama 3.2 3B有基本的工具使用支持。Gemma 2 2B不支持函数调用。在构建依赖于结构化输出的管道之前检查模型文档。',
            },
            {
              q: '英文以外的语言最好的小型模型是什么？',
              a: 'Qwen2.5 3B原生支持29种语言，包括中文、日文、韩文和阿拉伯文。Gemma 2 2B和Phi-4 Mini主要是英文优化的。对于小型模型规模的非英文任务，Qwen2.5 3B是明确的选择。有关完整的语言比较，请参阅[Qwen vs Llama vs Mistral 多语言比较](/local-llms/qwen-vs-llama-vs-mistral)。',
            },
            {
              q: '日常任务中Phi-4 Mini和Llama 3.2 3B之间的区别是什么？',
              a: 'Phi-4 Mini以几乎相同的RAM（每个2.5 GB）在推理、数学和编码上超过Llama 3.2 3B（68%对58% MMLU，70%对60% HumanEval）。对于日常任务----问答、摘要、简单解释----质量差距明显但不引人注目。Llama 3.2 3B拥有更广泛的社区支持和更多可用的微调。为结构化推理选择Phi-4 Mini；为通用聊天和兼容性选择Llama 3.2 3B。',
            },
            {
              q: '我可以同时运行两个小型模型吗？',
              a: '可以，如果总RAM允许的话。两个3B模型在Q4_K_M下组合使用〜5 GB----在具有精益OS的8 GB机器上可行。Ollama默认按进程一次加载一个模型。在不同的端口（OLLAMA_HOST=:11434和OLLAMA_HOST=:11435）上运行两个Ollama实例以并行提供两个模型。这对于A/B测试输出很有用。',
            },
            {
              q: '小型模型适合RAG（检索增强生成）吗？',
              a: '对于简单RAG是的。Llama 3.2 3B和Phi-4 Mini可以可靠地回答检索到的文档块上的问题。对于需要多跳推理的大型知识库上的RAG，7B+模型执行更加一致。GPT4All的LocalDocs功能为文档问答使用3B模型，对个人文档集合效果很好。',
            },
            {
              q: 'Phi-4 Mini在编码上比Llama 3.2 3B更好吗？',
              a: '是的。Phi-4 Mini在此规模达到60%对70% HumanEval得分，与Llama 3.2 3B相比有意义的10点差距。对于4-6 GB RAM机器上的编码协助，Phi-4 Mini是推荐选择。对于多语言编码（非Python），65% HumanEval的Qwen2.5 3B与Phi-4 Mini竞争，同时也支持函数调用。',
            },
          ],
        },
        sources: {
          title: '来源',
          items: [
            'Hugging Face Open LLM排行榜 -- open-llm-leaderboard.hf.space（MMLU和HumanEval得分）',
            'Microsoft Phi-4技术报告 -- microsoft.com/en-us/research/publication/phi-4-technical-report/',
            'Meta Llama 3.2模型卡 -- huggingface.co/meta-llama/Llama-3.2-3B-Instruct',
            'Google Gemma 2技术报告 -- storage.googleapis.com/deepmind-media/gemma/gemma-2-report.pdf',
          ],
        },
      },
    },
  };
