import type { Language } from '@/lib/blog/blogContent'
import type { LLMArticle } from '@/lib/local-llms/types'

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    freshness_tier: 'semi_annual',
    publishDate: '2026-05-26',
    dateModified: '2026-05-26',
    next_refresh_due: '2026-11-26',
    theme: 'Overview & Reference',
    title: 'Run Local AI Behind a Firewall: Offline Deployment Guide 2026',
    seoTitle: 'Local AI Behind Firewall 2026: Offline Setup Guide',
    intro:
      'Running a local AI behind a corporate firewall or in an air-gapped environment requires downloading every dependency before you lose internet access. One missed file — a tokeniser config, a prompt template, a quantised model shard — breaks the setup silently. This guide gives you a complete pre-flight checklist, a step-by-step offline workflow for Ollama and llama.cpp, and hardware recommendations for organisations in China or any environment governed by data-residency law.',
    metaDescription:
      'Deploy local LLMs offline behind a firewall: complete checklist, Ollama and llama.cpp air-gap workflow, NAS storage sizing, and China DSL compliance notes.',
    twitterDescription:
      'Offline local LLM deployment: download everything before you lose internet. Checklist, Ollama air-gap workflow, NAS sizing, China DSL compliance.',
    gammaEmbedUrl: '/presentations/local-ai-behind-firewall-offline-2026-static.html',
    readTime: '12 min read',
    educationalLevel: 'Intermediate',
    primaryTerm: 'local AI behind firewall',
    targetKeywords: [
      'local ai behind firewall 2026',
      'offline local llm deployment',
      'air-gapped llm setup',
      'local llm china data security law',
      'ollama offline install',
    ],
    leadAnswerBlock:
      '**Download Ollama, your chosen model at Q4_K_M, and any tokeniser files on an internet-connected machine first. Transfer everything to the offline environment via USB, SSD, or internal network share. No internet is needed after the initial download.**',
    quickAnswerTop: {
      en: {
        question: 'How do I run a local LLM completely offline?',
        answer:
          'Download Ollama (or llama.cpp binary), your model GGUF file, and any config files on an internet-connected machine. Transfer to the offline host. Run `ollama serve` with `OLLAMA_MODELS` pointing to your local model directory — no internet access needed after transfer.',
        bullets: [
          'Download: Ollama binary + model GGUF + tokeniser configs on connected machine',
          'Transfer: USB/SSD or internal network share (no cloud)',
          'Run: `OLLAMA_MODELS=/path/to/models ollama serve`',
          'Verify: `ollama run qwen2.5:14b` works fully offline',
          'China DSL/CAC: local inference means data never leaves your hardware',
        ],
        updatedDate: '2026-05',
      },
      de: {
        question: 'Wie betreibe ich einen lokalen LLM vollständig offline?',
        answer:
          'Ollama-Binary, Modell-GGUF und Konfigurationsdateien auf einem verbundenen Rechner herunterladen, dann per USB/SSD auf den Offline-Host übertragen. `ollama serve` mit `OLLAMA_MODELS` starten — danach kein Internetzugang nötig.',
        bullets: ['Download: Ollama + GGUF-Modell + Tokenizer-Configs auf verbundenem Rechner', 'Transfer: USB/SSD oder internes Netzwerk', 'Ausführen: `OLLAMA_MODELS=/pfad/zu/modellen ollama serve`', 'DSGVO: lokale Inferenz, keine Datenweitergabe an Dritte'],
        updatedDate: '2026-05',
      },
      fr: {
        question: 'Comment exécuter un LLM local complètement hors ligne ?',
        answer: 'Téléchargez le binaire Ollama, le fichier GGUF du modèle et les configs sur une machine connectée, puis transférez via USB/SSD. Exécutez `ollama serve` avec `OLLAMA_MODELS` pointant vers votre dossier local.',
        bullets: ['Téléchargement : Ollama + GGUF + configs tokeniseur', 'Transfert : USB/SSD ou partage réseau interne', 'RGPD : inférence locale, aucun transfert vers des tiers'],
        updatedDate: '2026-05',
      },
      ja: {
        question: 'ローカルLLMを完全オフラインで実行するには？',
        answer: 'インターネット接続マシンでOllamaバイナリ・モデルGGUF・設定ファイルをダウンロードし、USB/SSDでオフラインホストに転送。`OLLAMA_MODELS`を指定して`ollama serve`を起動——以降はインターネット不要です。',
        bullets: ['ダウンロード：Ollama + GGUF + トークナイザー設定', '転送：USB/SSDまたは内部ネットワーク共有', 'METIガイドライン：ローカル推論でデータを外部に出さない'],
        updatedDate: '2026-05',
      },
      zh: {
        question: '如何完全离线运行本地LLM？',
        answer: '在联网机器上下载Ollama二进制文件、模型GGUF文件和配置文件，通过USB/SSD传输到离线主机。设置`OLLAMA_MODELS`环境变量后运行`ollama serve`——之后无需网络连接。',
        bullets: ['下载：Ollama + GGUF模型 + 分词器配置', '传输：USB/SSD或内部网络共享', '《数据安全法》/CAC：本地推理，数据不出设备', '验证：`ollama run qwen2.5:14b`完全离线运行'],
        updatedDate: '2026-05',
      },
    },
    toc: [
      { label: 'TL;DR', anchor: 'tldr' },
      { label: 'Pre-flight Checklist', anchor: 'preflight' },
      { label: 'Download Everything', anchor: 'download' },
      { label: 'Ollama Air-Gap Setup', anchor: 'ollama-airgap' },
      { label: 'llama.cpp Air-Gap Setup', anchor: 'llamacpp-airgap' },
      { label: 'NAS Storage Sizing', anchor: 'nas-storage' },
      { label: 'China Data Security Law', anchor: 'china-compliance' },
      { label: 'Offline RAG', anchor: 'offline-rag' },
      { label: 'FAQ', anchor: 'faq' },
    ],
    snippetBlocks: [
      { type: 'one-sentence', content: 'Download Ollama, the model GGUF, and tokeniser configs on a connected machine, then transfer via USB or internal network — no internet needed after that.' },
      { type: 'plain-terms', content: 'An air-gapped local LLM deployment means no data leaves your hardware after setup. The key challenge is downloading every file you need before going offline. Missing one config file — a tokeniser, a chat template, or a model shard — will cause silent failures. This guide gives you the complete checklist.' },
    ],
    sections: {
      tldr: {
        id: 'tldr',
        title: 'TL;DR',
        isTldr: true,
        items: [
          'Download everything on a connected machine: Ollama binary, GGUF model, tokeniser configs, and any RAG dependencies',
          'Transfer via USB SSD, internal network share, or air-gapped laptop — never rely on cloud sync',
          'Set `OLLAMA_MODELS` env variable to point to your offline model directory',
          'Qwen2.5 14B at Q4_K_M (9.5 GB) is the recommended offline default — wide enough capability, fits on 16 GB unified memory',
          'NAS sizing: plan 20 GB per 7B model, 50 GB per 14B model, and 100 GB per 32B model at Q4_K_M',
          'China Data Security Law: local inference satisfies data residency requirements regardless of model provenance',
        ],
      },
      preflight: {
        id: 'preflight',
        title: 'Pre-flight Checklist — Download Before You Go Offline',
        content: 'Check off every item on a connected machine before moving to the air-gapped environment.',
        numberedItems: [
          '**Ollama binary** — download from ollama.com for your OS (Linux x86_64, macOS arm64, Windows). Version ≥0.3.0 recommended.',
          '**Model GGUF file** — pull via `ollama pull qwen2.5:14b-instruct-q4_K_M` on the connected machine. Models cache to `~/.ollama/models/`.',
          '**Tokeniser + chat template** — Ollama bundles these with the model manifest; no separate download needed if you use Ollama.',
          '**llama.cpp binary** (if using llama.cpp) — download a pre-built release from github.com/ggerganov/llama.cpp/releases.',
          '**Embedding model** (for offline RAG) — `ollama pull nomic-embed-text` or `mxbai-embed-large`.',
          '**Vector DB binary** (for offline RAG) — Chroma standalone, Qdrant binary, or SQLite+sqlite-vss (no Python install required).',
          '**Python wheels** (if using Python tooling) — download `.whl` files via `pip download` with `--no-deps` and transfer them.',
          '**Verification hash** — run `sha256sum` on each GGUF file before transfer to detect corruption.',
        ],
      },
      download: {
        id: 'download',
        title: 'Download Commands for the Connected Machine',
        content: 'Run all of these on the internet-connected machine before transfer. Replace model tags as needed.',
        items: [
          '`ollama pull qwen2.5:14b-instruct-q4_K_M` — 9.5 GB, recommended default',
          '`ollama pull qwen2.5:7b-instruct-q4_K_M` — 5.5 GB, for lower-VRAM machines',
          '`ollama pull nomic-embed-text` — 274 MB, for offline RAG embeddings',
          '`ollama pull deepseek-r1:7b` — 5.5 GB, if math/reasoning is the primary use case',
          'Model files location: `~/.ollama/models/` on Linux/macOS, `%USERPROFILE%\\.ollama\\models` on Windows',
          'For llama.cpp: download GGUF directly from HuggingFace and verify SHA256 before transfer',
        ],
      },
      ollamaAirgap: {
        id: 'ollama-airgap',
        title: 'Ollama Air-Gap Workflow',
        content: 'After transferring files to the offline machine:',
        numberedItems: [
          'Copy the entire `~/.ollama/` directory from the connected machine to the same path on the offline host.',
          'Install the Ollama binary: `chmod +x ollama && sudo mv ollama /usr/local/bin/`',
          'Set the model directory: `export OLLAMA_MODELS=/path/to/offline/ollama/models`',
          'Start the server: `ollama serve` — verify it starts without network calls in the logs.',
          'Test offline: `ollama run qwen2.5:14b` — should respond immediately without hitting any external URL.',
          'Bind to all interfaces for LAN access: `OLLAMA_HOST=0.0.0.0:11434 ollama serve`',
        ],
      },
      llamacppAirgap: {
        id: 'llamacpp-airgap',
        title: 'llama.cpp Air-Gap Workflow',
        content: 'llama.cpp is fully self-contained after the binary + GGUF are present — no runtime dependencies needed.',
        items: [
          'Transfer the pre-built binary and your GGUF file to the offline machine.',
          'Run: `./llama-server -m ./qwen2.5-14b-instruct-q4_K_M.gguf --port 8080`',
          'The `--no-mmap` flag disables memory-mapped I/O if running from a network share.',
          'Use `--n-gpu-layers 35` to offload layers to GPU on NVIDIA; `--n-gpu-layers -1` offloads all on Apple Silicon.',
          'OpenAI-compatible API available at `http://localhost:8080/v1` — drop-in for any OpenAI SDK.',
        ],
      },
      nasStorage: {
        id: 'nas-storage',
        title: 'NAS Storage Sizing for Offline Model Libraries',
        content:
          'A model library for a small team typically holds 3–6 models at different sizes. Plan storage before purchase.',
        tableData: {
          columns: ['Model', 'Q4_K_M Size', 'Q8_0 Size', 'VRAM Required'],
          rows: [
            { 'Model': 'Qwen2.5 7B', 'Q4_K_M Size': '5.5 GB', 'Q8_0 Size': '8.5 GB', 'VRAM Required': '8 GB' },
            { 'Model': 'Qwen2.5 14B', 'Q4_K_M Size': '9.5 GB', 'Q8_0 Size': '15 GB', 'VRAM Required': '12 GB' },
            { 'Model': 'Qwen2.5 32B', 'Q4_K_M Size': '20.5 GB', 'Q8_0 Size': '34 GB', 'VRAM Required': '24 GB' },
            { 'Model': 'Qwen2.5 72B', 'Q4_K_M Size': '46 GB', 'Q8_0 Size': '75 GB', 'VRAM Required': '48 GB' },
            { 'Model': 'nomic-embed-text', 'Q4_K_M Size': '0.27 GB', 'Q8_0 Size': '0.5 GB', 'VRAM Required': '1 GB' },
          ],
        },
        items: [
          'Recommended NAS for model storage: Synology DS923+ with 4× 4 TB drives in RAID 5 (~12 TB usable)',
          'Minimum for a 2–3 model library: 2 TB SSD (portable drive works for single-machine deployments)',
          'NFS mount the NAS to the inference server; set `OLLAMA_MODELS` to the NFS path',
        ],
      },
      chinaCompliance: {
        id: 'china-compliance',
        title: 'China Data Security Law and CAC Compliance',
        content:
          'China\'s Data Security Law (DSL, 2021) and Cybersecurity Law (CSL) require that important data processed in China be stored domestically. The Cyberspace Administration of China (CAC) additionally requires that AI systems providing public-facing services complete a security assessment before launch.',
        items: [
          '**Data residency:** Local inference means data never leaves your hardware. This satisfies DSL Article 31 (important data stored in China) regardless of model origin.',
          '**Model provenance:** Qwen2.5 (Alibaba) simplifies internal compliance documentation for enterprises — the model vendor is a PRC company. DeepSeek (DeepSeek AI, Hangzhou) is also PRC-origin.',
          '**Public-facing AI services:** If your deployment is user-facing (not purely internal), CAC\'s Algorithm Security Assessment rules require filing. Internal/offline deployments used by employees only are generally out of scope.',
          '**Network isolation verification:** Use `iptables` or a firewall rule to confirm no outbound connections from the inference server — document this for compliance records.',
          '**Audit logs:** Log prompt-response pairs locally (not to cloud) if required by internal data-governance policy. Ollama does not log by default; add middleware if needed.',
        ],
      },
      offlineRag: {
        id: 'offline-rag',
        title: 'Offline RAG Setup',
        content: 'Retrieval-Augmented Generation (RAG) fully offline requires: a local LLM + a local embedding model + a local vector store.',
        numberedItems: [
          '**Embedding model:** Pull `ollama pull nomic-embed-text` on the connected machine. Transfer with the rest of the Ollama models directory.',
          '**Vector store:** Chroma can run as a standalone binary (no Python needed); alternatively use Qdrant binary release or SQLite with the `sqlite-vss` extension.',
          '**Document ingestion:** Use LangChain or LlamaIndex offline (install wheels before going offline). Point the document loader to local files — no web crawling.',
          '**Query flow:** Document → embed via local nomic-embed-text → retrieve top-k chunks from local vector DB → pass to local Qwen2.5 → response. Zero external calls.',
          '**Testing:** Confirm with `tcpdump -i any -n port 443` that zero HTTPS traffic is generated during a full RAG query cycle.',
        ],
      },
      faqSection: {
        id: 'faq',
        title: 'FAQ',
        faqs: [
          { q: 'Does Ollama make any network calls when running offline?', a: 'By default, Ollama does not make network calls when serving a locally cached model. It contacts ollama.com only to pull or update models. Running `OLLAMA_MODELS` pointed at a local cache with `ollama serve` makes no outbound calls.' },
          { q: 'Can I run Qwen2.5 72B on a NAS-mounted path?', a: 'Yes, but expect slower load times (10–30 seconds) due to NFS latency during model loading. Once loaded, inference performance depends only on GPU/CPU VRAM — not storage speed.' },
          { q: 'What is the smallest model that handles Chinese text well offline?', a: 'Qwen2.5 7B at Q4_K_M (5.5 GB VRAM). It handles Chinese with native tokenisation and produces coherent responses at 50–80 tok/s on an RTX 3060.' },
          { q: 'Do I need a CAC security assessment for an internal offline deployment?', a: 'Generally no. CAC\'s Algorithm Security Assessment rules target public-facing AI services. Internal deployments accessible only to employees are out of scope. Consult a compliance professional for your specific situation.' },
          { q: 'Can llama.cpp run without any system dependencies?', a: 'On Linux, the pre-built binary requires GLIBC 2.28+ (standard on Ubuntu 20.04+). On macOS arm64, the binary is self-contained. On Windows, the CUDA build requires CUDA runtime DLLs.' },
          { q: 'How do I update models in an air-gapped environment?', a: 'Download the updated GGUF on a connected machine, verify the SHA256 hash, transfer via USB/SSD, and replace the old GGUF in your model directory. Restart the Ollama server to pick up the new file.' },
        ],
      },
      relatedReading: {
        id: 'related-reading',
        title: 'Related Reading',
        items: [
          '[Local RAG for Private Business Data](/power-local-llm/local-rag-for-private-business-data) — Full RAG pipeline setup with open-source tools',
          '[Best NAS Storage for Local AI Models 2026](/power-local-llm/best-nas-storage-local-ai-models-2026) — NAS hardware comparison for model libraries',
          '[Qwen Local Deployment Guide 2026](/local-llms/qwen-local-deployment-guide-2026) — Hardware tiers for all Qwen2.5 variants',
        ],
      },
    },
    schema: {
      '@context': 'https://schema.org',
      '@type': 'TechArticle',
      headline: 'Run Local AI Behind a Firewall: Offline Deployment Guide 2026',
      description: 'Deploy local LLMs offline behind a firewall: pre-flight checklist, Ollama and llama.cpp air-gap workflow, NAS storage sizing, and China Data Security Law compliance notes.',
      url: 'https://www.promptquorum.com/power-local-llm/local-ai-behind-firewall-offline-2026?lang=en',
      inLanguage: 'en',
      author: { '@type': 'Person', name: 'Hans Kuepper' },
      publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' },
      datePublished: '2026-05-26',
      dateModified: '2026-05-26',
      about: [{ '@type': 'Thing', name: 'Air-gapped LLM' }, { '@type': 'Thing', name: 'Offline AI deployment' }, { '@type': 'Thing', name: 'China Data Security Law' }],
      speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] },
    },
    faqSchema: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      inLanguage: 'en',
      mainEntity: [
        { '@type': 'Question', name: 'Does Ollama make any network calls when running offline?', acceptedAnswer: { '@type': 'Answer', text: 'Ollama contacts ollama.com only to pull or update models. Running with a local cache and OLLAMA_MODELS set makes no outbound calls.' } },
        { '@type': 'Question', name: 'What is the smallest model that handles Chinese text well offline?', acceptedAnswer: { '@type': 'Answer', text: 'Qwen2.5 7B at Q4_K_M (5.5 GB VRAM). Native Chinese tokenisation, 50–80 tok/s on an RTX 3060.' } },
        { '@type': 'Question', name: 'Do I need a CAC assessment for internal offline deployment?', acceptedAnswer: { '@type': 'Answer', text: 'Generally no. CAC Algorithm Security Assessment rules target public-facing AI services. Internal-only deployments are generally out of scope.' } },
      ],
    },
  },

  de: {
    freshness_tier: 'semi_annual',
    publishDate: '2026-05-26',
    dateModified: '2026-05-26',
    next_refresh_due: '2026-11-26',
    theme: 'Overview & Reference',
    title: 'Lokale KI hinter der Firewall: Offline-Deployment-Guide 2026',
    seoTitle: 'Lokale KI offline hinter Firewall 2026: Deployment-Guide',
    intro: 'Lokale KI hinter einer Unternehmens-Firewall oder in einer Air-Gap-Umgebung zu betreiben erfordert, dass alle Abhängigkeiten vor dem Verlust des Internetzugangs heruntergeladen werden. Dieser Leitfaden bietet eine vollständige Vorab-Checkliste, einen Schritt-für-Schritt-Offline-Workflow für Ollama und llama.cpp sowie Hardware-Empfehlungen für Organisationen in Deutschland und im Bereich DSGVO-konformer Datenverarbeitung.',
    metaDescription: 'Lokale LLMs offline hinter Firewall betreiben: vollständige Checkliste, Ollama Air-Gap-Workflow, NAS-Speicherbedarf und DSGVO-Hinweise für Deutschland.',
    twitterDescription: 'Offline-LLM-Deployment: alles herunterladen, bevor Sie das Internet verlieren. Checkliste, Ollama Air-Gap, NAS-Dimensionierung, DSGVO.',
    readTime: '12 Min. Lesezeit',
    educationalLevel: 'Intermediate',
    primaryTerm: 'lokale KI hinter Firewall',
    targetKeywords: ['lokale ki hinter firewall 2026', 'offline llm deployment', 'ollama offline installieren', 'air-gap llm dsgvo'],
    leadAnswerBlock: '**Ollama, das gewählte Modell in Q4_K_M und alle Tokenizer-Dateien zunächst auf einem verbundenen Rechner herunterladen, dann per USB-SSD oder internes Netzwerk auf die Offline-Umgebung übertragen. Nach dem initialen Download ist kein Internet mehr nötig.**',
    quickAnswerTop: {
      en: { question: 'How do I run a local LLM completely offline?', answer: 'Download everything on a connected machine, transfer via USB/SSD, then run `ollama serve` with OLLAMA_MODELS pointing to your local cache.', bullets: ['Download: Ollama + GGUF + tokeniser configs', 'Transfer: USB/SSD or internal LAN', 'GDPR: no data leaves your hardware'], updatedDate: '2026-05' },
      de: { question: 'Wie betreibe ich einen lokalen LLM vollständig offline?', answer: 'Alles auf einem verbundenen Rechner herunterladen, per USB/SSD übertragen, dann `ollama serve` mit `OLLAMA_MODELS` auf das lokale Cache-Verzeichnis starten.', bullets: ['Download: Ollama + GGUF + Tokenizer-Configs', 'Transfer: USB/SSD oder internes LAN', 'DSGVO: keine Datenweitergabe an Dritte', 'Verifizierung: SHA256-Hash vor dem Transfer prüfen'], updatedDate: '2026-05' },
      fr: { question: 'Comment exécuter un LLM local hors ligne ?', answer: 'Téléchargez tout sur une machine connectée, transférez via USB/SSD, lancez `ollama serve` avec OLLAMA_MODELS pointant vers votre cache local.', bullets: ['Téléchargement : Ollama + GGUF + configs', 'Transfert : USB/SSD', 'RGPD : aucune donnée transmise à des tiers'], updatedDate: '2026-05' },
      ja: { question: 'ローカルLLMを完全オフラインで実行するには？', answer: '接続マシンですべてダウンロードし、USB/SSDで転送後、OLLAMA_MODELSをローカルキャッシュに指定して`ollama serve`を起動。', bullets: ['ダウンロード：Ollama + GGUF + 設定', '転送：USB/SSD', 'METI：データが外部に出ない'], updatedDate: '2026-05' },
      zh: { question: '如何完全离线运行本地LLM？', answer: '在联网机器下载所有文件，通过USB/SSD传输，设置OLLAMA_MODELS后运行`ollama serve`。', bullets: ['下载：Ollama + GGUF + 配置', '传输：USB/SSD', '数据安全法：数据不出设备'], updatedDate: '2026-05' },
    },
    toc: [
      { label: 'Zusammenfassung', anchor: 'tldr' },
      { label: 'Vorab-Checkliste', anchor: 'preflight' },
      { label: 'Download-Befehle', anchor: 'download' },
      { label: 'Ollama Air-Gap-Setup', anchor: 'ollama-airgap' },
      { label: 'llama.cpp Air-Gap-Setup', anchor: 'llamacpp-airgap' },
      { label: 'NAS-Speicherdimensionierung', anchor: 'nas-storage' },
      { label: 'DSGVO & BSI-Grundschutz', anchor: 'china-compliance' },
      { label: 'Offline-RAG', anchor: 'offline-rag' },
      { label: 'FAQ', anchor: 'faq' },
    ],
    snippetBlocks: [
      { type: 'one-sentence', content: 'Ollama, das Modell-GGUF und Tokenizer-Configs auf einem verbundenen Rechner herunterladen, dann per USB oder internes Netzwerk übertragen — danach kein Internet mehr nötig.' },
      { type: 'plain-terms', content: 'Ein Air-Gap-LLM-Deployment bedeutet, dass nach der Einrichtung keine Daten die Hardware verlassen. Die Herausforderung ist das Herunterladen aller benötigten Dateien vor dem Offline-Gehen. Fehlt eine einzige Konfigurationsdatei, schlägt das Setup ohne Fehlermeldung fehl.' },
    ],
    sections: {
      tldr: { id: 'tldr', title: 'Zusammenfassung', isTldr: true, items: ['Alles auf einem verbundenen Rechner herunterladen: Ollama-Binary, GGUF-Modell, Tokenizer-Configs', 'Per USB-SSD oder internes Netzwerk übertragen — nie Cloud-Sync verwenden', '`OLLAMA_MODELS`-Umgebungsvariable auf das Offline-Modell-Verzeichnis setzen', 'Qwen2.5 14B bei Q4_K_M (9,5 GB) ist der empfohlene Offline-Standard', 'NAS-Dimensionierung: 20 GB pro 7B-Modell, 50 GB pro 14B, 100 GB pro 32B', 'DSGVO: Lokale Inferenz — keine Datenweitergabe an Dritte, kein Auftragsverarbeitungsvertrag nötig'] },
      preflight: { id: 'preflight', title: 'Vorab-Checkliste — vor dem Offline-Gehen herunterladen', content: 'Alle Punkte auf einem verbundenen Rechner abhaken, bevor die Umgebung isoliert wird.', numberedItems: ['**Ollama-Binary** — ollama.com für Ihr Betriebssystem herunterladen. Version ≥0.3.0 empfohlen.', '**Modell-GGUF** — `ollama pull qwen2.5:14b-instruct-q4_K_M` auf dem verbundenen Rechner ausführen.', '**Tokenizer + Chat-Template** — Ollama bündelt diese mit dem Modell-Manifest; kein separater Download nötig.', '**Embedding-Modell** (für Offline-RAG) — `ollama pull nomic-embed-text`.', '**Verifikations-Hash** — `sha256sum` auf jede GGUF-Datei vor dem Transfer anwenden.'] },
      download: { id: 'download', title: 'Download-Befehle für den verbundenen Rechner', content: 'Alle Befehle auf dem verbundenen Rechner ausführen, bevor der Transfer stattfindet.', items: ['`ollama pull qwen2.5:14b-instruct-q4_K_M` — 9,5 GB, empfohlener Standard', '`ollama pull qwen2.5:7b-instruct-q4_K_M` — 5,5 GB, für VRAM-ärmere Maschinen', '`ollama pull nomic-embed-text` — 274 MB, für Offline-RAG-Embeddings'] },
      ollamaAirgap: { id: 'ollama-airgap', title: 'Ollama Air-Gap-Workflow', content: 'Nach dem Dateitransfer auf die Offline-Maschine:', numberedItems: ['Gesamtes `~/.ollama/`-Verzeichnis auf denselben Pfad des Offline-Hosts kopieren.', 'Ollama-Binary installieren: `chmod +x ollama && sudo mv ollama /usr/local/bin/`', 'Modell-Verzeichnis setzen: `export OLLAMA_MODELS=/pfad/zu/modellen`', 'Server starten: `ollama serve` — Logs prüfen, ob keine Netzwerkaufrufe stattfinden.', 'Offline testen: `ollama run qwen2.5:14b` — sollte sofort ohne externe URL-Anfragen antworten.'] },
      llamacppAirgap: { id: 'llamacpp-airgap', title: 'llama.cpp Air-Gap-Workflow', content: 'llama.cpp ist nach Binary + GGUF vollständig eigenständig — keine Runtime-Abhängigkeiten.', items: ['Binary und GGUF-Datei auf die Offline-Maschine übertragen.', 'Ausführen: `./llama-server -m ./qwen2.5-14b-instruct-q4_K_M.gguf --port 8080`', 'OpenAI-kompatible API unter `http://localhost:8080/v1` — Drop-in für jedes OpenAI-SDK.'] },
      nasStorage: { id: 'nas-storage', title: 'NAS-Speicherdimensionierung für Offline-Modell-Bibliotheken', content: 'Eine Modell-Bibliothek für ein kleines Team hält typischerweise 3–6 Modelle in verschiedenen Größen.', tableData: { columns: ['Modell', 'Q4_K_M-Größe', 'Q8_0-Größe', 'VRAM-Bedarf'], rows: [{ 'Modell': 'Qwen2.5 7B', 'Q4_K_M-Größe': '5,5 GB', 'Q8_0-Größe': '8,5 GB', 'VRAM-Bedarf': '8 GB' }, { 'Modell': 'Qwen2.5 14B', 'Q4_K_M-Größe': '9,5 GB', 'Q8_0-Größe': '15 GB', 'VRAM-Bedarf': '12 GB' }, { 'Modell': 'Qwen2.5 32B', 'Q4_K_M-Größe': '20,5 GB', 'Q8_0-Größe': '34 GB', 'VRAM-Bedarf': '24 GB' }] }, items: ['Empfohlenes NAS für Modell-Speicherung: Synology DS923+ mit 4× 4-TB-Laufwerken im RAID 5 (~12 TB nutzbar)', 'Minimum für eine 2–3-Modell-Bibliothek: 2-TB-SSD', 'BSI-Grundschutz: NAS-Laufwerk in der Dateiserver-Grundkonfiguration (SYS.1.3) dokumentieren'] },
      chinaCompliance: { id: 'china-compliance', title: 'DSGVO & BSI-Grundschutz für Offline-Deployments', content: 'Für DSGVO-konforme Deployments in Deutschland gelten bei lokaler Inferenz vereinfachte Anforderungen.', items: ['**Keine Auftragsverarbeitung:** Lokale Inferenz ohne Cloud-Anbindung erfordert keinen Auftragsverarbeitungsvertrag nach DSGVO Art. 28.', '**BSI-Grundschutz:** Air-Gapped-Server-Deployment entspricht dem Baustein SYS.1.1 (Allgemeiner Server). Netzwerkisolierung in der Systemdokumentation erfassen.', '**Protokollierung:** Ollama protokolliert standardmäßig keine Prompts. Falls Revisionsprotokoll erforderlich, Middleware zwischenschalten und lokal speichern.', '**Firewall-Regel:** `iptables -A OUTPUT -j DROP` für den Inferenz-Server dokumentieren, um Netzwerkisolierung nachzuweisen.'] },
      offlineRag: { id: 'offline-rag', title: 'Offline-RAG-Setup', content: 'RAG vollständig offline erfordert: lokales LLM + lokales Embedding-Modell + lokale Vektordatenbank.', numberedItems: ['**Embedding-Modell:** `ollama pull nomic-embed-text` auf dem verbundenen Rechner. Mit dem Ollama-Verzeichnis übertragen.', '**Vektordatenbank:** Chroma als eigenständiges Binary (kein Python nötig); alternativ Qdrant-Binary-Release.', '**Dokumenten-Ingestion:** LangChain oder LlamaIndex offline nutzen (Wheels vor dem Offline-Gehen herunterladen).', '**Query-Flow:** Dokument → Embedding via lokales nomic-embed-text → Top-k-Chunks aus lokaler DB → Qwen2.5 → Antwort. Kein externer Aufruf.'] },
      faqSection: { id: 'faq', title: 'FAQ', faqs: [
        { q: 'Macht Ollama Netzwerkaufrufe im Offline-Betrieb?', a: 'Nein. Ollama kontaktiert ollama.com nur beim Herunterladen oder Aktualisieren von Modellen. `ollama serve` mit lokalem Cache macht keine ausgehenden Verbindungen.' },
        { q: 'Ist das Offline-Deployment DSGVO-konform?', a: 'Ja. Lokale Inferenz ohne Cloud-Anbindung erfordert keinen Auftragsverarbeitungsvertrag nach DSGVO Art. 28, da keine Daten an Dritte übermittelt werden.' },
        { q: 'Welches ist das kleinste Modell für gutes Deutsch offline?', a: 'Qwen2.5 7B bei Q4_K_M (5,5 GB VRAM). Deutschsprachige Ausgaben sind kohärent; für anspruchsvollere Aufgaben Qwen2.5 14B verwenden.' },
      ] },
      relatedReading: { id: 'related-reading', title: 'Verwandte Artikel', items: ['[Lokales RAG für private Geschäftsdaten](/power-local-llm/local-rag-for-private-business-data?lang=de)', '[Bestes NAS für lokale KI-Modelle 2026](/power-local-llm/best-nas-storage-local-ai-models-2026?lang=de)', '[Qwen Lokal-Deployment-Guide 2026](/local-llms/qwen-local-deployment-guide-2026?lang=de)'] },
    },
    schema: { '@context': 'https://schema.org', '@type': 'TechArticle', headline: 'Lokale KI hinter der Firewall: Offline-Deployment-Guide 2026', description: 'Lokale LLMs offline hinter Firewall: vollständige Checkliste, Ollama Air-Gap-Workflow, NAS-Speicherbedarf, DSGVO-Hinweise.', url: 'https://www.promptquorum.com/power-local-llm/local-ai-behind-firewall-offline-2026?lang=de', inLanguage: 'de', author: { '@type': 'Person', name: 'Hans Kuepper' }, publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' }, datePublished: '2026-05-26', dateModified: '2026-05-26', about: [{ '@type': 'Thing', name: 'Offline LLM' }, { '@type': 'Thing', name: 'DSGVO' }], speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] } },
    faqSchema: { '@context': 'https://schema.org', '@type': 'FAQPage', inLanguage: 'de', mainEntity: [{ '@type': 'Question', name: 'Macht Ollama Netzwerkaufrufe im Offline-Betrieb?', acceptedAnswer: { '@type': 'Answer', text: 'Nein. `ollama serve` mit lokalem Cache macht keine ausgehenden Verbindungen.' } }, { '@type': 'Question', name: 'Ist das Offline-Deployment DSGVO-konform?', acceptedAnswer: { '@type': 'Answer', text: 'Ja. Lokale Inferenz erfordert keinen Auftragsverarbeitungsvertrag nach DSGVO Art. 28.' } }] },
  },

  fr: {
    freshness_tier: 'semi_annual', publishDate: '2026-05-26', dateModified: '2026-05-26', next_refresh_due: '2026-11-26',
    theme: 'Overview & Reference',
    title: 'IA locale derrière un pare-feu : Guide de déploiement hors ligne 2026',
    seoTitle: 'IA locale hors ligne derrière pare-feu 2026 : Guide',
    intro: 'Exécuter une IA locale derrière un pare-feu d\'entreprise nécessite de télécharger toutes les dépendances avant de perdre l\'accès à Internet. Ce guide fournit une liste de contrôle complète, un workflow hors ligne pour Ollama et llama.cpp, et des recommandations matérielles pour les organisations soumises aux lois sur la résidence des données.',
    metaDescription: 'Déployer des LLM locaux hors ligne derrière un pare-feu : liste de contrôle, workflow Ollama air-gap, dimensionnement NAS et conformité RGPD.',
    twitterDescription: 'Déploiement LLM hors ligne : téléchargez tout avant de perdre internet. Liste de contrôle, air-gap Ollama, NAS, RGPD.',
    readTime: '12 min de lecture', educationalLevel: 'Intermediate', primaryTerm: 'IA locale hors ligne pare-feu',
    targetKeywords: ['ia locale hors ligne 2026', 'llm offline derrière pare-feu', 'ollama air-gap installation'],
    leadAnswerBlock: '**Téléchargez Ollama, le modèle en Q4_K_M et les fichiers de configuration sur une machine connectée. Transférez via USB ou réseau interne. Aucune connexion Internet n\'est nécessaire après le transfert initial.**',
    quickAnswerTop: {
      en: { question: 'How do I run a local LLM completely offline?', answer: 'Download everything on a connected machine, transfer via USB/SSD, run `ollama serve` with OLLAMA_MODELS.', bullets: ['Download: Ollama + GGUF + configs', 'Transfer: USB/SSD', 'GDPR: no data leaves hardware'], updatedDate: '2026-05' },
      de: { question: 'Wie betreibe ich einen lokalen LLM offline?', answer: 'Alles herunterladen, übertragen, `ollama serve` starten.', bullets: ['Download', 'Transfer', 'DSGVO-konform'], updatedDate: '2026-05' },
      fr: { question: 'Comment exécuter un LLM local hors ligne ?', answer: 'Téléchargez tout sur une machine connectée, transférez via USB/SSD, exécutez `ollama serve` avec OLLAMA_MODELS pointant vers votre cache local.', bullets: ['Téléchargement : Ollama + GGUF + configs tokeniseur', 'Transfert : USB/SSD ou réseau interne', 'RGPD : aucune donnée transmise à des tiers', 'Vérification : hash SHA256 avant transfert'], updatedDate: '2026-05' },
      ja: { question: 'オフラインでLLMを実行するには？', answer: '接続マシンでダウンロードし、USB/SSD転送後、OLLAMA_MODELSを設定して起動。', bullets: ['ダウンロード', '転送', 'データ不出'], updatedDate: '2026-05' },
      zh: { question: '如何离线运行LLM？', answer: '在联网机器下载，USB/SSD传输，设置OLLAMA_MODELS后运行。', bullets: ['下载', '传输', '数据安全法合规'], updatedDate: '2026-05' },
    },
    toc: [{ label: 'Résumé', anchor: 'tldr' }, { label: 'Liste de contrôle', anchor: 'preflight' }, { label: 'Commandes de téléchargement', anchor: 'download' }, { label: 'Ollama air-gap', anchor: 'ollama-airgap' }, { label: 'Dimensionnement NAS', anchor: 'nas-storage' }, { label: 'RGPD & conformité', anchor: 'china-compliance' }, { label: 'RAG hors ligne', anchor: 'offline-rag' }, { label: 'FAQ', anchor: 'faq' }],
    snippetBlocks: [
      { type: 'one-sentence', content: 'Téléchargez Ollama, le GGUF du modèle et les configs tokeniseur sur une machine connectée, transférez via USB ou réseau interne — aucune connexion nécessaire ensuite.' },
      { type: 'plain-terms', content: 'Un déploiement LLM air-gap signifie qu\'aucune donnée ne quitte votre matériel après la configuration. Le défi principal est de télécharger tous les fichiers nécessaires avant de se déconnecter.' },
    ],
    sections: {
      tldr: { id: 'tldr', title: 'Résumé', isTldr: true, items: ['Tout télécharger sur une machine connectée : binaire Ollama, GGUF, configs tokeniseur', 'Transférer via USB-SSD ou réseau interne — ne jamais utiliser la synchronisation cloud', 'Définir la variable `OLLAMA_MODELS` pour pointer vers le répertoire de modèles hors ligne', 'Qwen2.5 14B en Q4_K_M (9,5 Go) est le standard hors ligne recommandé', 'Conformité RGPD : inférence locale — aucune donnée transmise à des tiers'] },
      preflight: { id: 'preflight', title: 'Liste de contrôle pré-déploiement', content: 'Cocher chaque élément sur une machine connectée avant l\'isolation.', numberedItems: ['**Binaire Ollama** — télécharger depuis ollama.com pour votre OS. Version ≥0.3.0 recommandée.', '**Fichier GGUF du modèle** — `ollama pull qwen2.5:14b-instruct-q4_K_M` sur la machine connectée.', '**Modèle d\'embedding** (pour RAG hors ligne) — `ollama pull nomic-embed-text`.', '**Hash de vérification** — `sha256sum` sur chaque fichier GGUF avant transfert.'] },
      download: { id: 'download', title: 'Commandes de téléchargement', content: 'Exécuter sur la machine connectée.', items: ['`ollama pull qwen2.5:14b-instruct-q4_K_M` — 9,5 Go, standard recommandé', '`ollama pull nomic-embed-text` — 274 Mo, pour le RAG hors ligne'] },
      ollamaAirgap: { id: 'ollama-airgap', title: 'Workflow Ollama air-gap', content: 'Après transfert des fichiers sur la machine hors ligne :', numberedItems: ['Copier l\'ensemble du répertoire `~/.ollama/` vers le même chemin sur l\'hôte hors ligne.', 'Définir le répertoire : `export OLLAMA_MODELS=/chemin/vers/modèles`', 'Démarrer le serveur : `ollama serve` — vérifier l\'absence d\'appels réseau dans les logs.', 'Tester hors ligne : `ollama run qwen2.5:14b`'] },
      llamacppAirgap: { id: 'llamacpp-airgap', title: 'Workflow llama.cpp air-gap', content: 'llama.cpp est autonome avec le binaire + GGUF.', items: ['Transférer le binaire et le fichier GGUF.', 'Exécuter : `./llama-server -m ./qwen2.5-14b-instruct-q4_K_M.gguf --port 8080`', 'API compatible OpenAI disponible sur `http://localhost:8080/v1`.'] },
      nasStorage: { id: 'nas-storage', title: 'Dimensionnement NAS', content: 'Planifier 20 Go par modèle 7B, 50 Go par 14B, 100 Go par 32B en Q4_K_M.', tableData: { columns: ['Modèle', 'Taille Q4_K_M', 'VRAM requise'], rows: [{ 'Modèle': 'Qwen2.5 7B', 'Taille Q4_K_M': '5,5 Go', 'VRAM requise': '8 Go' }, { 'Modèle': 'Qwen2.5 14B', 'Taille Q4_K_M': '9,5 Go', 'VRAM requise': '12 Go' }, { 'Modèle': 'Qwen2.5 32B', 'Taille Q4_K_M': '20,5 Go', 'VRAM requise': '24 Go' }] } },
      chinaCompliance: { id: 'china-compliance', title: 'RGPD & conformité hors ligne', content: 'Pour les déploiements conformes au RGPD en France, l\'inférence locale simplifie les obligations.', items: ['**Pas de sous-traitance :** L\'inférence locale sans cloud ne nécessite pas de DPA selon l\'Art. 28 RGPD.', '**CNIL :** Les traitements locaux uniquement internes ne nécessitent pas de notification spécifique à la CNIL.', '**Journalisation :** Ollama ne journalise pas les prompts par défaut. Si un journal d\'audit est requis, ajouter un middleware local.'] },
      offlineRag: { id: 'offline-rag', title: 'RAG hors ligne', content: 'RAG entièrement hors ligne nécessite : LLM local + modèle d\'embedding local + base vectorielle locale.', numberedItems: ['**Modèle d\'embedding :** `ollama pull nomic-embed-text` sur la machine connectée.', '**Base vectorielle :** Chroma en binaire autonome ou Qdrant binary release.', '**Flux de requêtes :** Document → embedding nomic-embed → top-k chunks → Qwen2.5 → réponse. Zéro appel externe.'] },
      faqSection: { id: 'faq', title: 'FAQ', faqs: [
        { q: 'Ollama effectue-t-il des appels réseau en mode hors ligne ?', a: 'Non. Ollama contacte ollama.com uniquement pour télécharger ou mettre à jour des modèles. `ollama serve` avec un cache local n\'effectue aucune connexion sortante.' },
        { q: 'Ce déploiement est-il conforme au RGPD ?', a: 'Oui. L\'inférence locale sans cloud ne nécessite pas de DPA selon l\'Art. 28 RGPD, car aucune donnée n\'est transmise à des tiers.' },
      ] },
      relatedReading: { id: 'related-reading', title: 'Lectures connexes', items: ['[RAG local pour données professionnelles privées](/power-local-llm/local-rag-for-private-business-data?lang=fr)', '[Meilleur NAS pour modèles IA locaux 2026](/power-local-llm/best-nas-storage-local-ai-models-2026?lang=fr)'] },
    },
    schema: { '@context': 'https://schema.org', '@type': 'TechArticle', headline: 'IA locale derrière un pare-feu : Guide de déploiement hors ligne 2026', description: 'Déployer des LLM locaux hors ligne : liste de contrôle, Ollama air-gap, NAS, RGPD.', url: 'https://www.promptquorum.com/power-local-llm/local-ai-behind-firewall-offline-2026?lang=fr', inLanguage: 'fr', author: { '@type': 'Person', name: 'Hans Kuepper' }, publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' }, datePublished: '2026-05-26', dateModified: '2026-05-26', about: [{ '@type': 'Thing', name: 'LLM hors ligne' }], speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] } },
    faqSchema: { '@context': 'https://schema.org', '@type': 'FAQPage', inLanguage: 'fr', mainEntity: [{ '@type': 'Question', name: 'Ollama effectue-t-il des appels réseau hors ligne ?', acceptedAnswer: { '@type': 'Answer', text: 'Non. `ollama serve` avec un cache local n\'effectue aucune connexion sortante.' } }] },
  },

  ja: {
    freshness_tier: 'semi_annual', publishDate: '2026-05-26', dateModified: '2026-05-26', next_refresh_due: '2026-11-26',
    theme: 'Overview & Reference',
    title: 'ファイアウォール背後でのローカルAI：オフライン展開ガイド 2026',
    seoTitle: 'ファイアウォール背後のローカルAI 2026 | Ollama air-gapセットアップ完全ガイド',
    intro: '企業ファイアウォールの背後やエアギャップ環境でローカルAIを運用するには、インターネット接続を失う前にすべての依存関係をダウンロードする必要があります。このガイドでは、完全な事前チェックリスト、OllamaとLlama.cppのオフラインワークフロー、そして日本のMETIガイドラインやデータ居住要件に対応する組織向けのハードウェア推奨事項を提供します。',
    metaDescription: 'ファイアウォール背後でのローカルLLMオフライン展開：事前チェックリスト、Ollama air-gapワークフロー、NASストレージサイジング、METIガイドライン対応。',
    twitterDescription: 'オフラインLLM展開：インターネットを失う前にすべてダウンロード。チェックリスト、Ollama air-gap、NASサイジング。',
    readTime: '12分で読める', educationalLevel: 'Intermediate', primaryTerm: 'ファイアウォール背後のローカルAI',
    targetKeywords: ['ローカルai オフライン 2026', 'ollama エアギャップ インストール', 'ローカルllm meti'],
    leadAnswerBlock: '**まず接続マシンでOllama・Q4_K_Mモデル・トークナイザー設定をダウンロード。USB/SSDでオフラインホストに転送。最初のダウンロード後はインターネット不要。**',
    quickAnswerTop: {
      en: { question: 'How to run LLM offline?', answer: 'Download on connected machine, transfer via USB, run `ollama serve` with OLLAMA_MODELS.', bullets: ['Download: Ollama + GGUF + configs', 'Transfer: USB/SSD', 'METI: data stays on-device'], updatedDate: '2026-05' },
      de: { question: 'LLM offline betreiben?', answer: 'Download, Transfer, Start.', bullets: ['Download', 'Transfer', 'DSGVO-konform'], updatedDate: '2026-05' },
      fr: { question: 'Exécuter LLM hors ligne ?', answer: 'Télécharger, transférer, lancer.', bullets: ['Téléchargement', 'Transfert', 'RGPD'], updatedDate: '2026-05' },
      ja: { question: 'ローカルLLMを完全オフラインで実行するには？', answer: 'インターネット接続マシンでOllamaバイナリ・モデルGGUF・設定ファイルをダウンロードし、USB/SSDでオフラインホストに転送。`OLLAMA_MODELS`を指定して`ollama serve`を起動。以降はインターネット不要。', bullets: ['ダウンロード：Ollama + GGUF + トークナイザー設定（接続マシン上で）', '転送：USB/SSDまたは内部ネットワーク共有', '起動：`OLLAMA_MODELS=/path/to/models ollama serve`', 'METIガイドライン：ローカル推論でデータが外部に出ない', 'SHA256ハッシュで転送前の検証を推奨'], updatedDate: '2026-05' },
      zh: { question: '如何离线运行LLM？', answer: '联网机器下载，USB/SSD传输，OLLAMA_MODELS设置后启动。', bullets: ['下载', '传输', '数据安全法合规'], updatedDate: '2026-05' },
    },
    toc: [{ label: 'まとめ', anchor: 'tldr' }, { label: '事前チェックリスト', anchor: 'preflight' }, { label: 'ダウンロードコマンド', anchor: 'download' }, { label: 'Ollama air-gapセットアップ', anchor: 'ollama-airgap' }, { label: 'NASストレージサイジング', anchor: 'nas-storage' }, { label: 'METIガイドライン対応', anchor: 'china-compliance' }, { label: 'オフラインRAG', anchor: 'offline-rag' }, { label: 'よくある質問', anchor: 'faq' }],
    snippetBlocks: [
      { type: 'one-sentence', content: 'OllamaバイナリとモデルGGUFと設定ファイルを接続マシンでダウンロードし、USB/SSDで転送——以降インターネット不要。' },
      { type: 'plain-terms', content: 'エアギャップLLM展開とは、セットアップ後はデータがハードウェアから出ないことを意味します。主な課題はオフラインになる前に必要なファイルをすべてダウンロードすることです。' },
    ],
    sections: {
      tldr: { id: 'tldr', title: 'まとめ', isTldr: true, items: ['接続マシンですべてダウンロード：Ollamaバイナリ・GGUFモデル・トークナイザー設定', 'USB-SSDまたは内部ネットワーク経由で転送——クラウド同期は使わない', '`OLLAMA_MODELS`環境変数をオフラインモデルディレクトリに設定', 'Qwen2.5 14B（Q4_K_M、9.5 GB）が推奨オフラインデフォルト', 'METIガイドライン：ローカル推論でデータが外部に出ない'] },
      preflight: { id: 'preflight', title: '事前チェックリスト', content: '孤立環境に移る前に接続マシンですべて確認。', numberedItems: ['**Ollamaバイナリ** — ollama.comからOS用をダウンロード。バージョン≥0.3.0推奨。', '**モデルGGUF** — `ollama pull qwen2.5:14b-instruct-q4_K_M`を接続マシンで実行。', '**埋め込みモデル**（オフラインRAG用）— `ollama pull nomic-embed-text`。', '**検証ハッシュ** — 転送前に各GGUFファイルで`sha256sum`を実行。'] },
      download: { id: 'download', title: 'ダウンロードコマンド', content: '接続マシンで実行。', items: ['`ollama pull qwen2.5:14b-instruct-q4_K_M` — 9.5 GB、推奨デフォルト', '`ollama pull nomic-embed-text` — 274 MB、オフラインRAG用'] },
      ollamaAirgap: { id: 'ollama-airgap', title: 'Ollama air-gapワークフロー', content: 'オフラインマシンへのファイル転送後：', numberedItems: ['`~/.ollama/`ディレクトリ全体をオフラインホストの同じパスにコピー。', 'バイナリインストール：`chmod +x ollama && sudo mv ollama /usr/local/bin/`', 'モデルディレクトリ設定：`export OLLAMA_MODELS=/path/to/models`', 'サーバー起動：`ollama serve` — ログでネットワーク呼び出しなしを確認。', 'オフラインテスト：`ollama run qwen2.5:14b`'] },
      llamacppAirgap: { id: 'llamacpp-airgap', title: 'llama.cpp air-gapワークフロー', content: 'バイナリ + GGUF後、llama.cppは完全に自己完結。', items: ['バイナリとGGUFをオフラインマシンに転送。', '実行：`./llama-server -m ./qwen2.5-14b-instruct-q4_K_M.gguf --port 8080`', 'OpenAI互換API：`http://localhost:8080/v1`'] },
      nasStorage: { id: 'nas-storage', title: 'NASストレージサイジング', content: '小チーム向けモデルライブラリは通常3〜6モデルを保有。', tableData: { columns: ['モデル', 'Q4_K_M サイズ', 'VRAM必要量'], rows: [{ 'モデル': 'Qwen2.5 7B', 'Q4_K_M サイズ': '5.5 GB', 'VRAM必要量': '8 GB' }, { 'モデル': 'Qwen2.5 14B', 'Q4_K_M サイズ': '9.5 GB', 'VRAM必要量': '12 GB' }, { 'モデル': 'Qwen2.5 32B', 'Q4_K_M サイズ': '20.5 GB', 'VRAM必要量': '24 GB' }] } },
      chinaCompliance: { id: 'china-compliance', title: 'METIガイドライン・データ管理対応', content: '日本のMETI AIガイドラインとデータガバナンスフレームワークへの対応。', items: ['**データ管理：** ローカル推論によりデータがハードウェアから出ない。METIの「AI利活用ガイドライン」のデータ管理要件を満たしやすい。', '**モデル記録：** METIガイドラインではモデル名とバージョンの記録が求められる。Ollamaはモデル情報を`~/.ollama/models/`に保存——記録に活用可能。', '**監査ログ：** Ollamaはデフォルトでプロンプトを記録しない。監査ログが必要な場合はミドルウェアをローカルに追加。'] },
      offlineRag: { id: 'offline-rag', title: 'オフラインRAGセットアップ', content: '完全オフラインのRAGには：ローカルLLM + ローカル埋め込みモデル + ローカルベクターDB。', numberedItems: ['**埋め込みモデル：** `ollama pull nomic-embed-text`を接続マシンで。Ollamaディレクトリと一緒に転送。', '**ベクターDB：** Chromaスタンドアロンバイナリ（Python不要）またはQdrantバイナリリリース。', '**クエリフロー：** 文書 → nomic-embed-textで埋め込み → ローカルDBからtop-kチャンク → Qwen2.5 → 応答。外部呼び出しゼロ。'] },
      faqSection: { id: 'faq', title: 'よくある質問', faqs: [
        { q: 'オフライン実行時にOllamaはネットワーク呼び出しをしますか？', a: 'しません。Ollamaはモデルのダウンロード・更新時のみollama.comに接続します。ローカルキャッシュで`ollama serve`を実行した場合、外部接続は発生しません。' },
        { q: 'METIガイドライン対応のため最適なモデルは？', a: 'Qwen2.5 14B（Q4_K_M、9.5 GB VRAM）。日本語・中国語・英語に対応し、METI推奨の高品質なAI出力を実現します。モデル名とバージョン（qwen2.5:14b-instruct-q4_K_M）を記録に残してください。' },
      ] },
      relatedReading: { id: 'related-reading', title: '関連記事', items: ['[プライベートビジネスデータ用ローカルRAG](/power-local-llm/local-rag-for-private-business-data?lang=ja)', '[ローカルAIモデル向けNAS 2026](/power-local-llm/best-nas-storage-local-ai-models-2026?lang=ja)'] },
    },
    schema: { '@context': 'https://schema.org', '@type': 'TechArticle', headline: 'ファイアウォール背後のローカルAI：オフライン展開ガイド 2026', description: 'ファイアウォール背後でのオフラインLLM展開：事前チェックリスト・Ollama air-gap・NASサイジング・METIガイドライン対応。', url: 'https://www.promptquorum.com/power-local-llm/local-ai-behind-firewall-offline-2026?lang=ja', inLanguage: 'ja', author: { '@type': 'Organization', name: 'PromptQuorum' }, publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' }, datePublished: '2026-05-26', dateModified: '2026-05-26', about: [{ '@type': 'Thing', name: 'オフラインLLM' }], speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] } },
    faqSchema: { '@context': 'https://schema.org', '@type': 'FAQPage', inLanguage: 'ja', mainEntity: [{ '@type': 'Question', name: 'オフラインでOllamaはネットワーク呼び出しをしますか？', acceptedAnswer: { '@type': 'Answer', text: 'しません。ローカルキャッシュで`ollama serve`を実行した場合、外部接続は発生しません。' } }] },
  },

  zh: {
    freshness_tier: 'semi_annual', publishDate: '2026-05-26', dateModified: '2026-05-26', next_refresh_due: '2026-11-26',
    theme: 'Overview & Reference',
    title: '防火墙后的本地AI：离线部署指南 2026',
    seoTitle: '防火墙后本地AI offline setup 2026：Ollama air-gap部署与合规指南',
    intro: '在企业防火墙或隔离网络环境中运行本地AI，需要在断网前下载所有依赖文件。一个遗漏的文件——分词器配置、提示模板或量化模型分片——就会导致无声失败。本指南提供完整的部署前检查清单、Ollama和llama.cpp的离线工作流程，以及针对中国《数据安全法》和CAC法规的合规说明。',
    metaDescription: '防火墙后本地LLM完整离线部署：预检清单、Ollama air-gap工作流程、NAS存储规划，以及中国《数据安全法》与CAC网络安全合规说明。',
    twitterDescription: '离线本地LLM部署：断网前下载所有文件。检查清单、Ollama air-gap、NAS规划、数据安全法合规。',
    readTime: '12分钟阅读', educationalLevel: 'Intermediate', primaryTerm: '防火墙后本地AI',
    targetKeywords: ['防火墙后本地ai 2026', '离线llm部署', 'ollama离线安装', '本地ai数据安全法'],
    leadAnswerBlock: '**首先在联网机器上下载Ollama、Q4_K_M模型文件和配置文件，通过USB/SSD传输到隔离环境。设置OLLAMA_MODELS环境变量后运行`ollama serve`。初次下载后无需网络连接。**',
    quickAnswerTop: {
      en: { question: 'How to run LLM offline?', answer: 'Download on connected machine, transfer via USB, run `ollama serve` with OLLAMA_MODELS.', bullets: ['Download: Ollama + GGUF + configs', 'Transfer: USB/SSD', 'China DSL: data stays on-device'], updatedDate: '2026-05' },
      de: { question: 'LLM offline?', answer: 'Download, Transfer, Start.', bullets: ['Download', 'Transfer', 'DSGVO'], updatedDate: '2026-05' },
      fr: { question: 'LLM hors ligne ?', answer: 'Télécharger, transférer, lancer.', bullets: ['Téléchargement', 'Transfert', 'RGPD'], updatedDate: '2026-05' },
      ja: { question: 'オフラインLLM？', answer: 'ダウンロード、転送、起動。', bullets: ['ダウンロード', '転送', 'METI対応'], updatedDate: '2026-05' },
      zh: { question: '如何完全离线运行本地LLM？', answer: '在联网机器上下载Ollama二进制文件、模型GGUF文件和配置文件，通过USB/SSD传输到离线主机，设置`OLLAMA_MODELS`环境变量后运行`ollama serve`。初次下载后完全无需网络。', bullets: ['下载：Ollama二进制 + GGUF模型 + 分词器配置（在联网机器上）', '传输：USB/SSD或内部网络共享', '启动：`OLLAMA_MODELS=/path/to/models ollama serve`', '《数据安全法》/CAC：本地推理，数据始终在设备内', '建议传输前用SHA256验证GGUF文件完整性'], updatedDate: '2026-05' },
    },
    toc: [{ label: '摘要', anchor: 'tldr' }, { label: '部署前检查清单', anchor: 'preflight' }, { label: '下载命令', anchor: 'download' }, { label: 'Ollama离线设置', anchor: 'ollama-airgap' }, { label: 'NAS存储规划', anchor: 'nas-storage' }, { label: '《数据安全法》合规', anchor: 'china-compliance' }, { label: '离线RAG', anchor: 'offline-rag' }, { label: '常见问题', anchor: 'faq' }],
    snippetBlocks: [
      { type: 'one-sentence', content: '在联网机器上下载Ollama、模型GGUF和分词器配置，通过USB或内部网络传输——之后无需网络连接。' },
      { type: 'plain-terms', content: '隔离网络的本地LLM部署意味着设置完成后数据不会离开您的硬件。关键挑战是在断网之前下载所有必需文件。遗漏任何一个配置文件都可能导致无声失败。' },
    ],
    sections: {
      tldr: { id: 'tldr', title: '摘要', isTldr: true, items: ['在联网机器上下载所有内容：Ollama二进制、GGUF模型、分词器配置', '通过USB-SSD或内部网络传输——绝不使用云同步', '设置`OLLAMA_MODELS`环境变量指向离线模型目录', 'Qwen2.5 14B（Q4_K_M，9.5 GB）是推荐的离线默认选择', 'NAS规划：每个7B模型20 GB，14B模型50 GB，32B模型100 GB（Q4_K_M格式）', '《数据安全法》/CAC：本地推理满足数据驻留要求，数据始终在您的硬件内'] },
      preflight: { id: 'preflight', title: '部署前检查清单——断网前下载', content: '在隔离环境之前，在联网机器上逐一确认以下所有项目。', numberedItems: ['**Ollama二进制文件** — 从ollama.com下载您操作系统对应版本，推荐≥0.3.0。', '**模型GGUF文件** — 在联网机器上运行`ollama pull qwen2.5:14b-instruct-q4_K_M`。', '**分词器和聊天模板** — Ollama随模型清单一起打包；无需单独下载。', '**嵌入模型**（离线RAG用）— `ollama pull nomic-embed-text`（274 MB）。', '**验证哈希** — 传输前对每个GGUF文件运行`sha256sum`，检测损坏。'] },
      download: { id: 'download', title: '联网机器上的下载命令', content: '传输前在联网机器上运行所有命令。', items: ['`ollama pull qwen2.5:14b-instruct-q4_K_M` — 9.5 GB，推荐默认', '`ollama pull qwen2.5:7b-instruct-q4_K_M` — 5.5 GB，低显存机器用', '`ollama pull nomic-embed-text` — 274 MB，离线RAG嵌入', '`ollama pull deepseek-r1:7b` — 5.5 GB，数学/推理为主时使用', '模型文件位置：Linux/macOS的`~/.ollama/models/`，Windows的`%USERPROFILE%\\.ollama\\models`'] },
      ollamaAirgap: { id: 'ollama-airgap', title: 'Ollama离线工作流程', content: '将文件传输到离线机器后：', numberedItems: ['将完整的`~/.ollama/`目录从联网机器复制到离线主机的相同路径。', '安装Ollama二进制：`chmod +x ollama && sudo mv ollama /usr/local/bin/`', '设置模型目录：`export OLLAMA_MODELS=/path/to/offline/ollama/models`', '启动服务器：`ollama serve` — 检查日志确认无网络调用。', '离线测试：`ollama run qwen2.5:14b` — 应立即响应，无外部URL请求。', '局域网访问绑定：`OLLAMA_HOST=0.0.0.0:11434 ollama serve`'] },
      llamacppAirgap: { id: 'llamacpp-airgap', title: 'llama.cpp离线工作流程', content: 'llama.cpp在二进制文件+GGUF就位后完全自包含——无需运行时依赖。', items: ['将预构建二进制和GGUF文件传输到离线机器。', '运行：`./llama-server -m ./qwen2.5-14b-instruct-q4_K_M.gguf --port 8080`', 'OpenAI兼容API在`http://localhost:8080/v1`——任何OpenAI SDK的直接替代。'] },
      nasStorage: { id: 'nas-storage', title: 'NAS存储规划', content: '小团队的模型库通常存储3-6个不同规模的模型。', tableData: { columns: ['模型', 'Q4_K_M大小', 'Q8_0大小', '所需显存'], rows: [{ '模型': 'Qwen2.5 7B', 'Q4_K_M大小': '5.5 GB', 'Q8_0大小': '8.5 GB', '所需显存': '8 GB' }, { '模型': 'Qwen2.5 14B', 'Q4_K_M大小': '9.5 GB', 'Q8_0大小': '15 GB', '所需显存': '12 GB' }, { '模型': 'Qwen2.5 32B', 'Q4_K_M大小': '20.5 GB', 'Q8_0大小': '34 GB', '所需显存': '24 GB' }, { '模型': 'nomic-embed-text', 'Q4_K_M大小': '0.27 GB', 'Q8_0大小': '0.5 GB', '所需显存': '1 GB' }] }, items: ['推荐NAS：群晖DS923+配4块4 TB硬盘（RAID 5，约12 TB可用）', '2-3模型库最低配置：2 TB SSD（便携硬盘适合单机部署）', '通过NFS挂载NAS到推理服务器，设置`OLLAMA_MODELS`为NFS路径'] },
      chinaCompliance: { id: 'china-compliance', title: '中国《数据安全法》和CAC合规', content: '中国《数据安全法》（DSL，2021年）和《网络安全法》（CSL）要求在中国境内处理的重要数据在境内存储。国家互联网信息办公室（CAC）还要求提供面向公众服务的AI系统在上线前完成安全评估。', items: ['**数据驻留：** 本地推理意味着数据不会离开您的硬件，满足《数据安全法》第31条（重要数据在境内存储），与模型来源无关。', '**模型溯源：** 选用Qwen2.5（阿里巴巴）或DeepSeek（杭州深度求索）简化企业合规文档，两者均为中国企业出品。', '**面向公众的AI服务：** 若您的部署面向用户（非纯内部），需按CAC《算法安全评估规定》提交备案。仅供内部员工使用的离线部署通常不在范围内。', '**网络隔离验证：** 使用`iptables`或防火墙规则确认推理服务器无对外连接——记录在案以供合规审查。', '**审计日志：** Ollama默认不记录提示词。如内部数据治理政策要求，需在本地添加中间件（非云端）。'] },
      offlineRag: { id: 'offline-rag', title: '离线RAG设置', content: '完全离线的检索增强生成（RAG）需要：本地LLM + 本地嵌入模型 + 本地向量数据库。', numberedItems: ['**嵌入模型：** 在联网机器上`ollama pull nomic-embed-text`，随Ollama模型目录一起传输。', '**向量数据库：** Chroma可作为独立二进制运行（无需Python）；或使用Qdrant二进制版。', '**文档摄入：** 离线使用LangChain或LlamaIndex（断网前下载wheel包）。文档加载器指向本地文件——无需网络爬虫。', '**查询流程：** 文档 → 本地nomic-embed-text嵌入 → 从本地向量DB检索top-k片段 → 传递给本地Qwen2.5 → 响应。零外部调用。', '**验证：** 用`tcpdump -i any -n port 443`确认完整RAG查询周期无HTTPS流量产生。'] },
      faqSection: { id: 'faq', title: '常见问题', faqs: [
        { q: 'Ollama在离线运行时是否会产生网络调用？', a: '不会。Ollama仅在拉取或更新模型时连接ollama.com。使用本地缓存运行`ollama serve`不会产生任何对外连接。' },
        { q: '本地AI部署是否符合中国《数据安全法》？', a: '本地推理意味着数据始终留在您的硬件上，无论模型来自哪家公司，均满足《数据安全法》的数据驻留要求。' },
        { q: '内部离线部署是否需要CAC算法安全评估？', a: '通常不需要。CAC的算法安全评估规定主要针对面向公众的AI服务。仅供内部员工使用的部署通常不在范围内。请咨询合规专业人士了解您的具体情况。' },
        { q: '最适合离线处理中文文本的最小模型是什么？', a: 'Qwen2.5 7B（Q4_K_M，5.5 GB显存）。原生中文分词，在RTX 3060上以50-80词元/秒运行，输出连贯。' },
        { q: '如何在隔离环境中更新模型？', a: '在联网机器上下载更新的GGUF，验证SHA256哈希，通过USB/SSD传输，替换模型目录中的旧文件，重启Ollama服务器。' },
      ] },
      relatedReading: { id: 'related-reading', title: '相关阅读', items: ['[本地RAG用于私人业务数据](/power-local-llm/local-rag-for-private-business-data?lang=zh)', '[本地AI模型最佳NAS存储 2026](/power-local-llm/best-nas-storage-local-ai-models-2026?lang=zh)', '[Qwen本地部署指南 2026](/local-llms/qwen-local-deployment-guide-2026?lang=zh)', '[微信本地LLM集成2026](/power-local-llm/wechat-local-llm-integration-2026?lang=zh) — 将离线Ollama后端接入微信机器人：技术路线与合规注意事项。'] },
    },
    schema: { '@context': 'https://schema.org', '@type': 'TechArticle', headline: '防火墙后的本地AI：离线部署指南 2026', description: '防火墙后本地LLM离线部署：完整检查清单、Ollama air-gap、NAS存储规划、《数据安全法》/CAC合规说明。', url: 'https://www.promptquorum.com/power-local-llm/local-ai-behind-firewall-offline-2026?lang=zh', inLanguage: 'zh', author: { '@type': 'Organization', name: 'PromptQuorum' }, publisher: { '@type': 'Organization', name: 'PromptQuorum', url: 'https://www.promptquorum.com' }, datePublished: '2026-05-26', dateModified: '2026-05-26', about: [{ '@type': 'Thing', name: '离线LLM' }, { '@type': 'Thing', name: '数据安全法' }], speakable: { '@type': 'SpeakableSpecification', cssSelector: ['.article-intro', '.key-takeaways'] } },
    faqSchema: { '@context': 'https://schema.org', '@type': 'FAQPage', inLanguage: 'zh', mainEntity: [{ '@type': 'Question', name: 'Ollama在离线运行时是否产生网络调用？', acceptedAnswer: { '@type': 'Answer', text: '不会。使用本地缓存运行`ollama serve`不会产生任何对外连接。' } }, { '@type': 'Question', name: '是否需要CAC安全评估？', acceptedAnswer: { '@type': 'Answer', text: '内部离线部署通常不需要。CAC规定主要针对面向公众的AI服务。' } }, { '@type': 'Question', name: '本地部署是否符合《数据安全法》？', acceptedAnswer: { '@type': 'Answer', text: '是的。本地推理数据始终在设备内，满足数据驻留要求。' } }] },
  },
}
