import type { Language } from '@/lib/blog/blogContent'
import type { LLMArticle } from '@/lib/local-llms/types'

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    theme: 'Local AI Agents & Tool Use',
    freshness_tier: 'semi_annual',
    next_refresh_due: '2027-03-05',
    publishDate: '2026-09-05',
    dateModified: '2026-09-05',
    educationalLevel: 'Intermediate',
    audience: 'Developers and power users evaluating OpenClaw as a personal AI agent gateway, and readers who remember its January 2026 renaming saga and want to know its current governance and security track record',
    primaryTerm: 'OpenClaw',
    title: 'OpenClaw Review 2026: Renamed Twice, Now Run by a Nonprofit',
    seoTitle: 'OpenClaw Review 2026: History and Security Record',
    intro: 'OpenClaw is an open-source AI agent gateway: a persistent background service that connects a language model to messaging apps you already use — WhatsApp, Telegram, Discord, Slack, Signal, iMessage, and more — and lets it run shell commands, control a browser, read and write files, and manage a calendar or inbox, all triggered by a text message. It started in November 2025 as a personal project called Clawdbot, was renamed twice within three days in January 2026 after a trademark dispute with Anthropic, and by February 2026 had been handed to a nonprofit foundation after its creator joined OpenAI. It has also accumulated 647 published security advisories in that time.',
    metaDescription: 'OpenClaw is an open-source AI agent gateway for WhatsApp, Discord, and more. What it does, its Clawdbot-to-Moltbot-to-OpenClaw rename, and its 647-advisory security record.',
    readTime: '12 min read',
    targetKeywords: [
      'OpenClaw review',
      'OpenClaw AI agent',
      'what is OpenClaw',
      'OpenClaw security',
      'Clawdbot Moltbot OpenClaw',
      'OpenClaw vs alternatives',
    ],
    leadAnswerBlock: 'OpenClaw is an open-source, MIT-licensed AI agent gateway that runs a language model against your own messaging apps and machine — not a chatbot you visit, but a background service that reaches you on WhatsApp, Discord, Slack, and 25+ other channels and can run shell commands, control a browser, and touch your files when you ask it to. It began as a solo project in November 2025, changed its name twice in three days after a trademark dispute with Anthropic, and is now stewarded by a nonprofit foundation after its creator, Peter Steinberger, joined OpenAI in February 2026.',
    quickAnswerTop: {
      en: {
        question: 'What is OpenClaw and is it safe to use?',
        answer: 'OpenClaw ([github.com/openclaw/openclaw](https://github.com/openclaw/openclaw)) is an open-source, MIT-licensed AI agent gateway that connects a language model to messaging apps and lets it run shell commands, control a browser, and manage files on your machine. It is real and actively maintained — 388,916 stars, a release roughly every few days, current version v2026.9.1 — but it carries a documented security history: 647 published GitHub security advisories between January and June 2026, including 14 critical and 219 high-severity findings, plus a disclosed unauthenticated remote-code-execution chain triggered by a single WhatsApp message (patched in version 2026.6.6). Whether it is "safe" depends entirely on how carefully you configure it — the capabilities that make it useful (shell access, file access, browser control) are the same capabilities behind every advisory on that list.',
        bullets: [
          'MIT license, 388,916 stars, 81,708 forks, actively maintained (last push within hours of this review)',
          'Originally named Clawdbot (Nov 2025), renamed to Moltbot then OpenClaw within 3 days in January 2026 after an Anthropic trademark dispute over "Clawd"',
          'Creator Peter Steinberger (founder of PSPDFKit) joined OpenAI in February 2026; the project is now stewarded by the nonprofit OpenClaw Foundation, chaired by Dave Morin',
          '647 published security advisories (Jan–Jun 2026): 14 critical, 219 high, 350 medium, 64 low — per GitHub\'s own security-advisories API',
          'A disclosed unauthenticated RCE chain (3 CVEs, CVSS up to 8.8) triggered via a single WhatsApp message, affecting versions through 2026.6.1, patched in 2026.6.6',
        ],
        updatedDate: '2026-09',
      },
    },
    toc: [
      { label: 'TL;DR', anchor: 'tldr' },
      { label: 'What Is OpenClaw?', anchor: 'what-is-openclaw' },
      { label: 'From Clawdbot to Moltbot to OpenClaw', anchor: 'openclaw-history' },
      { label: 'How OpenClaw Works', anchor: 'how-openclaw-works' },
      { label: 'Security Track Record', anchor: 'openclaw-security' },
      { label: 'Is OpenClaw Still Maintained?', anchor: 'is-openclaw-still-maintained' },
      { label: 'Who Should Use OpenClaw', anchor: 'who-should-use-openclaw' },
      { label: 'OpenClaw vs. Alternatives', anchor: 'openclaw-vs-alternatives' },
      { label: 'Common Mistakes', anchor: 'common-mistakes' },
      { label: 'FAQ', anchor: 'faq' },
    ],
    sections: {
      tldr: {
        id: 'tldr',
        title: 'TL;DR — OpenClaw in 2026',
        isTldr: true,
        snippetBlocks: [
          { type: 'one-sentence', text: 'OpenClaw is an open-source, MIT-licensed AI agent gateway that connects a language model to messaging apps like WhatsApp and Discord and lets it run shell commands, control a browser, and manage files on your machine, with an unusually public and extensive security-advisory history (647 published in its first six months).' },
          { type: 'plain-terms', text: 'Instead of opening a chat window, you text an AI agent the same way you\'d text a person — on WhatsApp, Telegram, Slack, whatever you already use — and it can actually go do things on your computer, not just reply with text. That power is also the risk: every advisory in its 647-item security history traces back to exactly that capability.' },
        ],
        items: [
          'Open-source AI agent gateway: connects an LLM to WhatsApp, Telegram, Discord, Slack, Signal, iMessage, and 25+ other channels',
          'Can run shell commands, control a browser, read/write files, and manage calendar or email — triggered by a text message',
          'Started November 2025 as "Clawdbot"; renamed to "Moltbot" then "OpenClaw" within 3 days in January 2026 after Anthropic\'s trademark dispute over "Clawd"',
          'Creator Peter Steinberger joined OpenAI in February 2026; project handed to the nonprofit OpenClaw Foundation, chaired by Dave Morin, sponsored by OpenAI',
          '647 published GitHub security advisories (Jan–Jun 2026): 14 critical, 219 high, 350 medium, 64 low',
          'A disclosed unauthenticated RCE chain (3 CVEs, CVSS up to 8.8) via a single WhatsApp message, patched in version 2026.6.6',
          'MIT licensed, 388,916 stars, current release v2026.9.1',
        ],
        callouts: [
          { type: 'note', text: 'This review covers OpenClaw as of v2026.9.1 (September 2026). Given its release pace (multiple versions per week) and its unusually active security-advisory history, verify current status directly on the repository before deploying it, especially with real messaging accounts and file-system access.' },
        ],
      },
      overview: {
        id: 'what-is-openclaw',
        title: 'What Is OpenClaw?',
        content: 'OpenClaw ([github.com/openclaw/openclaw](https://github.com/openclaw/openclaw)) is an open-source AI agent gateway — a persistent background service, not a chat window you visit — that runs on your own machine and reaches you through messaging apps you already use. Its own description states it plainly: "The AI that really does things. Any OS. Any Platform." At its center is the Gateway, a daemon that manages connections to messaging channels, routes incoming messages to agent sessions, and handles scheduling.',
        items: [
          'Talks to you through WhatsApp, Telegram, Discord, Slack, Signal, iMessage, and other channels (documentation cites 29 supported channels)',
          'Can run shell commands, control a browser, read and write files, manage a calendar, and send emails — all from a text message',
          'Works with OpenAI, Google Gemini, Mistral, local models via Ollama, and effectively any provider with an API',
          'State (transcripts, memory index) lives on your own machine rather than a vendor cloud, per the project\'s stated design goal',
          'Processes messages within a session one at a time via a Command Queue, to keep tool use and session history consistent',
          'Homepage: [openclaw.ai](https://openclaw.ai)',
        ],
        note: 'The lobster branding ("the lobster way") throughout OpenClaw\'s marketing and documentation is a direct carryover from its January 2026 rename to Moltbot — lobsters molt to grow — which stuck even after the project renamed itself again to OpenClaw three days later.',
      },
      history: {
        id: 'openclaw-history',
        title: 'From Clawdbot to Moltbot to OpenClaw',
        content: [
          'OpenClaw did not start as OpenClaw. Austrian software engineer Peter Steinberger, founder of the PDF-tooling company PSPDFKit, built a personal AI assistant for himself named "Clawd" — a playful nod to Anthropic\'s Claude — and open-sourced a more capable version on GitHub in November 2025 under the name Clawdbot.',
          'On January 27, 2026, Anthropic\'s legal team sent a trademark notice: "Clawd" was judged phonetically too close to "Claude." Steinberger leaned into the project\'s lobster mascot — lobsters molt to grow — and renamed it Moltbot that same day, with the agent persona becoming "Molty." Three days later, on January 29, 2026, he renamed it again to OpenClaw, saying "Moltbot" never quite rolled off the tongue. The second rename, executed with deliberate secrecy and coordinated timing to avoid a repeat incident, referenced both the project\'s open-source nature and its lobster heritage.',
          'The transition was not clean. When Steinberger attempted to rename the GitHub organization and the project\'s X/Twitter handle simultaneously, crypto scammers seized the briefly-abandoned handles within roughly 10 seconds and promoted a fake "$CLAWD" token on Solana that reached a reported market capitalization above $16 million before Steinberger publicly denounced it as a scam. Typosquat domains and a cloned GitHub repository also appeared in the following days.',
          'In February 2026, Steinberger announced he was joining OpenAI and that a nonprofit foundation would take over stewardship of the project. The OpenClaw Foundation formally launched with 501(c)(3) nonprofit status, a first full-time team of ten across engineering and operations, and is chaired by entrepreneur and investor Dave Morin. OpenAI committed to sponsoring the foundation while OpenClaw remains open source under the MIT license.',
        ],
        callouts: [
          { type: 'note', text: 'The scam-token and domain-squatting incidents around the January 2026 rename were directed at abandoned social/GitHub handles during the transition window, not a vulnerability in the OpenClaw software itself. They are included here because they shaped the project\'s public reputation and are frequently conflated with its separate, software-level security advisories covered below.' },
        ],
      },
      howItWorks: {
        id: 'how-openclaw-works',
        title: 'How OpenClaw Works',
        content: 'OpenClaw\'s architecture centers on the Gateway: a persistent daemon that manages every messaging-channel connection, routes incoming messages to the right agent session, and handles scheduled or background tasks. Within a single session, messages are processed one at a time through a Command Queue rather than in parallel — the project\'s own documentation explains this is deliberate, to prevent tool conflicts and keep session history consistent. Conversation transcripts are indexed into a local SQLite database with vector search, and the agent runs a memory-search query against that index before answering, rather than relying only on the current conversation\'s context window.',
        items: [
          'Gateway: persistent background daemon managing channel connections, message routing, and scheduling',
          'Command Queue: serializes message processing per session to prevent tool conflicts',
          'Local memory: transcripts indexed into SQLite with vector search, queried before each response',
          'Model-agnostic: OpenAI, Google Gemini, Mistral, local models via Ollama, or any API-compatible provider',
          'Team mode: a shared gateway with sessions multiple people can open and steer, live presence, and commits credited to individual team members',
        ],
        numberedItems: [
          'macOS or Linux: run `curl -fsSL https://openclaw.ai/install.sh | bash` in a terminal.',
          'Windows: run `iwr -useb https://openclaw.ai/install.ps1 | iex` in PowerShell.',
          'Already manage Node.js yourself? Install the published package instead: `npm install -g openclaw@latest --allow-scripts=openclaw` (npm 12, or npm 11.16+).',
          'The installer launches an onboarding wizard automatically — choose Quick start to reuse detected AI access and open the dashboard, or Custom setup for the full guided flow.',
          'Quick start keeps the Gateway running in the foreground. For background operation, stop it with Ctrl+C, then run `openclaw gateway install`.',
          'Run `openclaw dashboard` to open the Control UI in your browser and confirm the Gateway is reachable; send it a test message to confirm the model connection works.',
        ],
        note: 'These are the install commands published in OpenClaw\'s own documentation as of this review. Verify against [docs.openclaw.ai](https://docs.openclaw.ai) before running them — install scripts and onboarding flows can change between OpenClaw\'s frequent releases.',
      },
      security: {
        id: 'openclaw-security',
        title: 'Security Track Record',
        content: [
          'OpenClaw\'s security history is unusually well-documented, and unusually large, for a project of any age. Per GitHub\'s own security-advisories API, the project published 647 advisories between January 31 and June 30, 2026: 14 rated critical, 219 high, 350 medium, and 64 low. No new advisories had been published between July and this review\'s September 2026 snapshot, though that gap reflects this review\'s data pull, not a guarantee the pace has permanently slowed — check the repository\'s live advisory feed for the current count.',
          'The most serious disclosed issue was reported by security researcher Chinmohan Nayak: three high-severity vulnerabilities (GHSA-hjr6-g723-hmfm, GHSA-9969-8g9h-rxwm, both CVSS 8.8; GHSA-575v-8hfq-m3mc, CVSS 8.4) that together formed an unauthenticated remote-code-execution chain triggerable by a single WhatsApp message. It affected versions through 2026.6.1 and was patched in 2026.6.6.',
          'Separately, in the days after the January 2026 rename, security firm Malwarebytes and other researchers reported over 1,000 publicly exposed OpenClaw instances leaking API keys, private chat histories, and system credentials — a configuration and deployment problem (unsecured public exposure) rather than a code vulnerability in OpenClaw itself.',
        ],
        itemHeadings: true,
        rows: [
          { 'Signal': 'Published advisories (Jan–Jun 2026)', 'What it shows': '647 total: 14 critical, 219 high, 350 medium, 64 low' },
          { 'Signal': 'Most severe disclosed issue', 'What it shows': 'Unauthenticated RCE chain via WhatsApp message, CVSS up to 8.8, patched in 2026.6.6' },
          { 'Signal': 'Exposed-instance incident', 'What it shows': '1,000+ public instances found leaking API keys and chat histories (deployment misconfiguration, not a code flaw)' },
          { 'Signal': 'Disclosure process', 'What it shows': 'Advisories published through GitHub\'s standard security-advisory workflow, with CVE/GHSA identifiers and CVSS scores' },
        ],
        columns: ['Signal', 'What it shows'],
        callouts: [
          { type: 'note', text: 'We did not run our own security audit of OpenClaw for this review. Every figure above comes from GitHub\'s public security-advisories API or named, dated reporting (Forbes, Malwarebytes, and the named researcher\'s own disclosure), not from testing PromptQuorum performed. A large advisory count is not automatically damning — it can reflect either a genuinely large attack surface (OpenClaw touches shell, browser, files, and email) or an unusually rigorous disclosure process, and the two are not mutually exclusive here. Verify the current advisory count and your installed version against the repository before deploying it with real accounts or file-system access.' },
        ],
      },
      maintenance: {
        id: 'is-openclaw-still-maintained',
        title: 'Is OpenClaw Still Maintained?',
        content: [
          'Yes, actively. The repository was pushed to within hours of this review\'s research, and OpenClaw ships new versions roughly every few days — the five most recent tags at review time were v2026.9.1, v2026.8.2, v2026.8.1, and two beta releases, spanning less than two weeks.',
          'Governance changed hands in February 2026: creator Peter Steinberger joined OpenAI, and stewardship passed to the nonprofit OpenClaw Foundation (501(c)(3) status, chaired by Dave Morin, a first full-time team of ten across engineering and operations, sponsored by OpenAI). The project remains MIT licensed under that arrangement. As of this review, the foundation had not published detailed public governance documents, so exactly how technical and roadmap decisions are made day-to-day is not fully transparent from the outside.',
        ],
        itemHeadings: true,
        rows: [
          { 'Signal': 'Repository activity', 'What it shows': 'Pushed within hours of this review; releases roughly every few days' },
          { 'Signal': 'Current release', 'What it shows': 'v2026.9.1' },
          { 'Signal': 'Star count', 'What it shows': '388,916 stars, 81,708 forks' },
          { 'Signal': 'Governance', 'What it shows': 'Nonprofit OpenClaw Foundation (501(c)(3)), chaired by Dave Morin, sponsored by OpenAI, since February 2026' },
        ],
        columns: ['Signal', 'What it shows'],
      },
      whoShouldUse: {
        id: 'who-should-use-openclaw',
        title: 'Who Should Use OpenClaw?',
        content: 'The right fit depends heavily on your tolerance for a young, fast-moving, and unusually security-scrutinized project having real access to your accounts, files, and shell.',
        subsections: [
          { title: 'Consider OpenClaw if', list: [
            'You want a single AI agent reachable from the messaging apps you already use, rather than a separate chat app or web dashboard',
            'You are comfortable running a permissive, on-device agent (shell, browser, files) and are willing to keep it updated against a fast release cadence',
            'You want a model-agnostic gateway that can point at OpenAI, Gemini, Mistral, or a local model via Ollama rather than being locked to one provider',
            'You are deploying for yourself or a small trusted team, not exposing it publicly without review — the 1,000+-instance exposure incident above happened to public deployments, not the default local setup',
          ] },
          { title: 'Think carefully, or wait, if', list: [
            'You need a stable, slow-moving tool for a regulated or high-stakes environment — the 647-advisory, multiple-release-per-week pace cuts against predictability',
            'You are not prepared to review OpenClaw\'s permission model in detail before granting it shell, file, or messaging-account access',
            'You want a narrower, single-purpose agent — a terminal coding agent (Aider, Open Interpreter) or a workflow-automation tool (n8n) with an AI node is a smaller attack surface for a narrower job',
          ] },
        ],
      },
      comparisonTable: {
        id: 'openclaw-vs-alternatives',
        title: 'OpenClaw vs. Alternatives',
        content: 'OpenClaw\'s combination of messaging-channel reach and full machine control does not have an exact peer in this directory. The closest comparisons split across two different axes: other broad personal-agent gateways, and narrower single-purpose agents that trade OpenClaw\'s reach for a smaller attack surface.',
        columns: ['Tool', 'Interface', 'License', 'Best For'],
        rows: [
          { 'Tool': '[OpenClaw](https://github.com/openclaw/openclaw)', 'Interface': 'Messaging apps + Gateway', 'License': 'MIT', 'Best For': 'Cross-channel personal agent, full machine access' },
          { 'Tool': '[goose](https://goose-docs.ai)', 'Interface': 'Desktop, CLI', 'License': 'Apache-2.0', 'Best For': 'Coding/automation agent, Linux Foundation-governed' },
          { 'Tool': '[n8n](https://n8n.io)', 'Interface': 'Web, self-hosted', 'License': 'Fair-code', 'Best For': 'Workflow automation with AI/LLM nodes' },
          { 'Tool': '[Open Interpreter](/power-local-llm/open-interpreter-review)', 'Interface': 'Terminal, ACP-compatible', 'License': 'Apache 2.0', 'Best For': 'Scoped terminal coding agent for open models' },
          { 'Tool': '[Onyx](https://onyx.app)', 'Interface': 'Web, self-hosted', 'License': 'MIT', 'Best For': 'Enterprise search + RAG, any model provider' },
          { 'Tool': '[AutoGPT (classic)](/power-local-llm/autogpt-local-review)', 'Interface': 'CLI, autonomous loop', 'License': 'MIT', 'Best For': 'Unscoped autonomous-agent experiments' },
        ],
        subsections: [
          { title: 'Best Choice by Use Case', list: [
            'Best for reaching an agent from apps you already use: OpenClaw — no other tool here spans 25+ messaging channels',
            'Best for a Linux Foundation-governed coding/automation agent: goose',
            'Best for automating business workflows with an AI step: n8n',
            'Best for a narrower, lower-permission coding agent: Open Interpreter',
            'Best for self-hosted enterprise search across any model provider: Onyx',
          ] },
        ],
      },
      commonMistakes: {
        id: 'common-mistakes',
        title: 'Common Mistakes',
        items: [
          'Confusing the January 2026 scam-token and typosquat-domain incidents (which targeted abandoned social/GitHub handles during the rename) with a vulnerability in OpenClaw\'s own code — they are separate issues covered in different sections above',
          'Exposing a Gateway instance to the public internet without authentication, which is exactly the misconfiguration behind the 1,000+-instance exposure incident, rather than keeping it on a private network or behind proper access controls',
          'Running an outdated version against a project that ships new releases every few days and has published 647 security advisories — check your installed version against the current release before assuming you are patched',
          'Granting full shell, file, and messaging-account access without first reading OpenClaw\'s permission and channel-disablement settings, given the documented history of permission-related advisories (including per-account tool disablement being ignored, as in GHSA-2q7j-2vhx-56g8)',
        ],
      },
      faq: {
        id: 'faq',
        title: 'Frequently Asked Questions',
        faqs: [
          { q: 'What is OpenClaw?', a: 'OpenClaw is an open-source, MIT-licensed AI agent gateway that connects a language model to messaging apps like WhatsApp, Telegram, Discord, and Slack, and lets it run shell commands, control a browser, read and write files, and manage a calendar or email, all triggered by a text message.' },
          { q: 'Is OpenClaw the same as Clawdbot or Moltbot?', a: 'Yes. OpenClaw is the same project, renamed twice within three days in January 2026: first from Clawdbot to Moltbot after an Anthropic trademark dispute over the name "Clawd," then from Moltbot to OpenClaw three days later.' },
          { q: 'Who created OpenClaw and who runs it now?', a: 'Austrian software engineer Peter Steinberger, founder of PSPDFKit, created the project as Clawdbot in November 2025. In February 2026 he joined OpenAI, and stewardship passed to the nonprofit OpenClaw Foundation, chaired by Dave Morin and sponsored by OpenAI, while the project remains MIT licensed.' },
          { q: 'Is OpenClaw safe to use?', a: 'It depends on configuration and how current your installed version is. OpenClaw has published 647 security advisories (14 critical, 219 high, 350 medium, 64 low) between January and June 2026, including a now-patched unauthenticated remote-code-execution chain triggerable via a single WhatsApp message. Its shell, file, and browser access are powerful by design — review its permission model before granting broad access, and keep it updated given its frequent release cadence.' },
          { q: 'What is the OpenClaw Gateway?', a: 'The Gateway is OpenClaw\'s core component: a persistent background daemon that manages connections to messaging channels, routes incoming messages to agent sessions, and handles scheduled tasks. Within one session, it processes messages one at a time through a Command Queue to keep tool use and session history consistent.' },
          { q: 'What models does OpenClaw work with?', a: 'OpenClaw is model-agnostic. It works with OpenAI, Google Gemini, Mistral, local models via Ollama, and effectively any provider with a compatible API.' },
          { q: 'How do I install OpenClaw?', a: 'On macOS or Linux, run curl -fsSL https://openclaw.ai/install.sh | bash. On Windows, run iwr -useb https://openclaw.ai/install.ps1 | iex in PowerShell. If you already manage Node.js, you can instead run npm install -g openclaw@latest --allow-scripts=openclaw. The installer launches an onboarding wizard automatically.' },
          { q: 'Is OpenClaw free?', a: 'Yes. It is MIT licensed, which permits free use, modification, and redistribution, including inside a commercial product.' },
          { q: 'What happened with the $CLAWD token?', a: 'During the January 2026 rename, crypto scammers briefly seized the project\'s abandoned GitHub organization and X/Twitter handles and promoted a fake "$CLAWD" token on Solana, which reportedly reached over $16 million in market capitalization before Steinberger publicly denounced it as a scam. It was not created or endorsed by the OpenClaw project.' },
          { q: 'How does OpenClaw compare to n8n or goose?', a: 'n8n is a workflow-automation platform with AI nodes, better suited to structured business processes than open-ended personal-assistant tasks. goose is a Linux Foundation-governed coding and automation agent with a narrower scope than OpenClaw\'s cross-channel reach. OpenClaw\'s distinguishing feature is that it reaches you through messaging apps you already use and can act broadly on your machine from there — a wider capability surface than either alternative, with a correspondingly larger documented security history.' },
        ],
      },
      sources: {
        id: 'sources',
        title: 'Sources',
        links: [
          { url: 'https://github.com/openclaw/openclaw', title: 'openclaw/openclaw on GitHub', description: 'The canonical source repository, including release tags, star/fork counts, and the security-advisories feed referenced in this review.' },
          { url: 'https://openclaw.ai', title: 'OpenClaw homepage', description: 'The project\'s official site and entry point to its documentation.' },
          { url: 'https://github.com/openclaw/openclaw/security/advisories', title: 'OpenClaw security advisories on GitHub', description: 'The public advisory feed this review\'s 647-advisory figure and severity breakdown are drawn from, via the GitHub API.' },
          { url: 'https://www.forbes.com/sites/ronschmelzer/2026/01/30/moltbot-molts-again-and-becomes-openclaw-pushback-and-concerns-grow/', title: 'Forbes: "Moltbot Molts Again and Becomes OpenClaw"', description: 'Reporting on the January 2026 rename, the trademark dispute, and the scam-token/typosquatting incidents referenced in this review.' },
          { url: 'https://en.wikipedia.org/wiki/OpenClaw', title: 'OpenClaw on Wikipedia', description: 'Background on the project\'s origin, naming history, and creator.' },
        ],
      },
      relatedReading: {
        id: 'related-reading',
        title: 'Related Reading',
        items: [
          '[Open Interpreter Review 2026: Same Name, Rust Core, New License](/power-local-llm/open-interpreter-review) — a narrower-scope, terminal-based coding agent as an alternative to OpenClaw\'s full-machine reach.',
          '[AutoGPT Review 2026: Classic Agent vs. Hosted Platform](/power-local-llm/autogpt-local-review) — an earlier, unscoped autonomous-agent design from the same broad "give an LLM agency" category.',
          '[Local LLM Software Directory 2026](/power-local-llm/local-llm-software-directory) — the full catalog of local AI tools this article belongs to.',
        ],
      },
    },
  },
}
