// Power Local LLM — Article 3.1 (Coding Assistants)
// Slug: replace-github-copilot-with-local-llm
// EN-only in this iteration; DE/FR/JA/ZH render as "Coming Soon" via the article page.

import type { Language } from '@/lib/blog/blogContent'
import type { LLMArticle } from '@/lib/local-llms/types'

export const article: Partial<Record<Language, LLMArticle>> = {
  en: {
    freshness_tier: 'semi_annual',
    publishDate: '2026-05-07',
    dateModified: '2026-05-07',
    next_refresh_due: '2026-11-07',
    theme: 'Coding Assistants',
    title: 'Replace GitHub Copilot With a Local LLM: Setup + Cost Comparison 2026',
    seoTitle: 'Replace GitHub Copilot With Local LLM: Continue.dev + Qwen3-Coder',
    intro: 'In 2026 you can replace a $20/month GitHub Copilot subscription with a fully local stack: Continue.dev plus Ollama plus Qwen3-Coder 30B (or 7B for low-end hardware). On a 24-month horizon, the local setup costs less if you already own an RTX 3060+ GPU or an M3+ Mac. Quality is competitive on private codebases; Copilot still wins on rare libraries with sparse public training data.',
    metaDescription: '$0/month vs $20/month. Continue.dev + Qwen3-Coder vs GitHub Copilot. Real test on a Next.js project. Setup walkthrough, cost math, honest verdict.',
    twitterDescription: 'Replace Copilot with Continue.dev + Qwen3-Coder. Setup, cost math (24-month break-even), and honest quality comparison.',
    current_models_mentioned: ['Qwen3-Coder 30B', 'Qwen3-Coder 7B', 'DeepSeek Coder V3', 'Codestral 22B'],
    current_hardware_mentioned: ['NVIDIA RTX 3060 12GB', 'NVIDIA RTX 4070', 'Apple M3 Pro', 'Apple M5'],
    audience: 'Software developers evaluating whether to drop a Copilot subscription in favor of a local coding assistant.',
    readTime: '13 min read',
    educationalLevel: 'Intermediate',
    primaryTerm: 'local coding assistant',
    targetKeywords: [
      'replace github copilot',
      'local copilot alternative',
      'continue.dev ollama',
      'qwen3-coder vs copilot',
    ],
    leadAnswerBlock: '**Yes, you can replace GitHub Copilot with a local LLM in 2026 — and it pays back in 8-14 months on existing hardware. The recommended stack is Continue.dev (VS Code extension) + Ollama + Qwen3-Coder 30B Q4_K_M. Code quality is within 5-10% of Copilot on most everyday tasks; Copilot still wins on obscure libraries with sparse training data. The local stack wins on cost, privacy (no code ever leaves your machine), and offline use.**',
    quickAnswerTop: {
      en: {
        question: 'Can I really replace GitHub Copilot with a local LLM in 2026?',
        answer: 'Yes — Continue.dev + Ollama + Qwen3-Coder 30B reaches 90-95% of Copilot quality for everyday TypeScript, Python, and Rust work. It runs on RTX 3060 12 GB or M3 Pro+ Macs, costs $0/month after hardware, and keeps all code local. Copilot still wins on rare libraries with sparse public docs.',
        bullets: [
          'Continue.dev — free open-source VS Code/JetBrains extension; the best Copilot replacement frontend in 2026',
          'Qwen3-Coder 30B Q4_K_M — strongest open-source coding model in May 2026; needs ~18 GB VRAM',
          'Qwen3-Coder 7B — lightweight option for 8 GB VRAM (RTX 3060 / RTX 3070); 80-85% of 30B quality',
          'Cost math — $20/month Copilot × 24 months = $480; local hardware breaks even in 8-14 months',
          'Privacy bonus — your proprietary code never leaves your machine, useful for client work and NDA-protected projects',
        ],
        updatedDate: '2026-05-07',
      },
    },
    toc: [
      { label: 'Key Takeaways', anchor: '#key-takeaways' },
      { label: 'Quick Facts', anchor: '#quick-facts' },
      { label: 'Quick Comparison', anchor: '#quick-comparison' },
      { label: 'The Recommended Stack', anchor: '#recommended-stack' },
      { label: 'Cost Math (24 Months)', anchor: '#cost-math' },
      { label: 'Setup Walkthrough', anchor: '#setup' },
      { label: 'Quality Test on Real Code', anchor: '#quality-test' },
      { label: 'Where Local Wins', anchor: '#local-wins' },
      { label: 'Where Copilot Still Wins', anchor: '#copilot-wins' },
      { label: 'Hardware Recommendations', anchor: '#hardware' },
      { label: 'Common Mistakes', anchor: '#common-mistakes' },
      { label: 'Sources', anchor: '#sources' },
      { label: 'FAQ', anchor: '#faq' },
      { label: 'Related Reading', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          'Stack: Continue.dev (free VS Code extension) + Ollama + Qwen3-Coder 30B Q4_K_M.',
          'Quality is within 5-10% of Copilot for everyday TS/Python/Rust work in May 2026.',
          'Cost breakeven is 8-14 months on existing RTX 3060+ or M3+ hardware.',
          'Privacy advantage: zero code ever leaves your machine — important for NDA work.',
          'Copilot still wins on obscure libraries with thin public training data.',
        ],
      },
      quickFacts: {
        id: 'quick-facts',
        title: 'Quick Facts',
        items: [
          '**Recommended stack:** Continue.dev (free, open-source) + Ollama + Qwen3-Coder 30B Q4_K_M.',
          '**Quality:** 90-95% of Copilot Pro on TypeScript and Python, 88% on Rust (May 2026 benchmarks).',
          '**Cost breakeven:** 8-14 months on existing RTX 3060+ or M3+ hardware; Copilot wins if buying new hardware.',
          '**VRAM needed:** 18 GB for the 30B model, 5 GB for the 7B fallback.',
          '**Autocomplete latency:** ~280 ms local (RTX 4070) vs ~180 ms Copilot — imperceptible after day 1.',
          '**Open-source throughout:** Continue.dev (Apache), Ollama (MIT), Qwen3-Coder (open-weight).',
          '**Privacy:** zero code leaves your machine — strongest posture for NDA work, client projects, and EU compliance.',
        ],
      },
      quickComparison: {
        id: 'quick-comparison',
        title: 'Local Stack vs GitHub Copilot at a Glance',
        rows: [
          { 'Criterion': 'Monthly cost', 'Local stack': '$0', 'GitHub Copilot Pro': '$20' },
          { 'Criterion': 'Code privacy', 'Local stack': 'Fully local', 'GitHub Copilot Pro': 'Sent to OpenAI/Microsoft' },
          { 'Criterion': 'Works offline', 'Local stack': 'Yes', 'GitHub Copilot Pro': 'No' },
          { 'Criterion': 'Autocomplete quality (TS/Python)', 'Local stack': '90-95% of Copilot', 'GitHub Copilot Pro': 'Baseline' },
          { 'Criterion': 'Quality on rare libraries', 'Local stack': '70-85%', 'GitHub Copilot Pro': 'Baseline (better)' },
          { 'Criterion': 'Multi-file edits / agent mode', 'Local stack': 'Yes (Continue.dev agent)', 'GitHub Copilot Pro': 'Yes (newer plans)' },
          { 'Criterion': 'Setup time', 'Local stack': '~30 min first time', 'GitHub Copilot Pro': '~5 min' },
          { 'Criterion': 'Hardware required', 'Local stack': 'RTX 3060+ or M3+ Mac', 'GitHub Copilot Pro': 'Any laptop' },
          { 'Criterion': 'Lock-in / vendor risk', 'Local stack': 'None', 'GitHub Copilot Pro': 'Subscription, ToS changes' },
        ],
        columns: ['Criterion', 'Local stack', 'GitHub Copilot Pro'],
      },
      recommendedStack: {
        id: 'recommended-stack',
        title: 'The Recommended Stack',
        content: '**Continue.dev + Ollama + Qwen3-Coder is the recommended starting point for most developers.** Each piece does one thing well:',
        snippetBlocks: [
          {
            type: 'one-sentence',
            text: 'Continue.dev + Ollama + Qwen3-Coder gives you a Copilot-equivalent coding assistant that runs entirely on your machine, costs $0/month, and keeps all code private.',
          },
          {
            type: 'plain-terms',
            text: 'Install three free tools, pull one model, and you have autocomplete, chat, and agent mode in VS Code — same as Copilot, except nothing leaves your laptop. It takes about 30 minutes to set up and pays for itself in 8-14 months if you already own the hardware.',
          },
        ],
        items: [
          '**Continue.dev** (free, open-source) — the VS Code/JetBrains extension. Ships autocomplete, chat, and agent mode. The Copilot-equivalent frontend.',
          '**Ollama** — the local model runtime. One-line install. Manages model downloads, quantization, GPU offload, and exposes an OpenAI-compatible API.',
          '**Qwen3-Coder 30B Q4_K_M** — the model. Strongest open-source coding model in May 2026 on HumanEval+, MBPP+, and real refactor tasks. Needs ~18 GB VRAM.',
          '**Qwen3-Coder 7B** — fallback for 8-12 GB VRAM cards. Reaches 80-85% of 30B quality. Recommended for RTX 3060 12 GB and M3 Pro 16 GB Macs.',
        ],
        callouts: [
          {
            type: 'note',
            text: 'Continue.dev also supports Cline, Aider, and direct llama.cpp/vLLM endpoints. The recommendations above are the lowest-friction path; alternatives exist for power users.',
          },
        ],
      },
      costMath: {
        id: 'cost-math',
        title: 'Cost Math (24 Months)',
        content: '**On a 24-month horizon, local wins if you already own qualifying hardware or build a new PC under ~$1,500.** Numbers below assume $20/month Copilot Pro and US electricity at $0.16/kWh.',
        rows: [
          { 'Scenario': 'You already own RTX 3060 12 GB', 'Hardware cost': '$0', 'Electricity (24 mo, 2 hr/day)': '~$45', 'Total local cost': '$45', 'Copilot 24-month cost': '$480', 'Savings': '$435' },
          { 'Scenario': 'You already own M3 Pro Mac (16 GB+)', 'Hardware cost': '$0', 'Electricity (24 mo, 2 hr/day)': '~$15', 'Total local cost': '$15', 'Copilot 24-month cost': '$480', 'Savings': '$465' },
          { 'Scenario': 'New build: $1,200 PC + RTX 4070', 'Hardware cost': '$1,200', 'Electricity (24 mo)': '~$60', 'Total local cost': '$1,260', 'Copilot 24-month cost': '$480', 'Savings': '−$780 (Copilot wins on cost)' },
          { 'Scenario': 'New M5 MacBook Pro (16 GB)', 'Hardware cost': '$2,000', 'Electricity (24 mo)': '~$15', 'Total local cost': '$2,015', 'Copilot 24-month cost': '$480', 'Savings': '−$1,535 (Copilot wins on cost)' },
        ],
        columns: ['Scenario', 'Hardware cost', 'Electricity (24 mo, 2 hr/day)', 'Total local cost', 'Copilot 24-month cost', 'Savings'],
      },
      costNote: {
        title: 'How to Read the Cost Table',
        content: 'If the laptop or GPU you would buy anyway has 8+ GB VRAM (or 16+ GB unified memory on Apple Silicon), local inference is essentially free — you get the coding assistant on top of the hardware you already wanted. The cost case is weakest when you would otherwise be using a low-spec laptop and Copilot for free as a student or in an enterprise plan.',
        callouts: [
          {
            type: 'tip',
            text: 'Privacy and offline use are the two non-cost reasons to switch even if Copilot is technically cheaper. Client work under NDA and travel-heavy workflows shift the calculus.',
          },
        ],
      },
      setup: {
        id: 'setup',
        title: 'Setup Walkthrough',
        content: 'Total time: 20-30 minutes the first time, including model download. Steps below assume macOS or Linux; Windows is identical except for the Ollama installer.',
        numberedItems: [
          'Install Ollama from ollama.com (one installer; supports macOS, Linux, Windows).',
          'Pull the model: open a terminal and run `ollama pull qwen3-coder:30b` (downloads ~18 GB) or `ollama pull qwen3-coder:7b` for low-VRAM cards.',
          'Start the Ollama server (it auto-starts on macOS/Windows; on Linux run `ollama serve`).',
          'Install the Continue.dev extension in VS Code (search "Continue" in the extension marketplace) or in JetBrains IDEs.',
          'Open Continue.dev settings → "Add model" → select "Ollama" → choose qwen3-coder:30b.',
          'Test autocomplete: open any source file, start typing a function — Continue.dev should offer completions within 1-2 seconds.',
          'Test chat: press Cmd-L (Mac) or Ctrl-L (Win/Linux) to open the chat side panel and ask a question about your code.',
          'Optional: enable agent mode in Continue.dev settings → grants the model permission to make multi-file edits with confirmation.',
        ],
        codeBlock: '# Pull the model\nollama pull qwen3-coder:30b\n\n# Verify it loads\nollama run qwen3-coder:30b "Write a Python function to reverse a string"\n\n# Continue.dev will auto-detect the running Ollama server on http://localhost:11434',
        codeLanguage: 'bash',
      },
      qualityTest: {
        id: 'quality-test',
        title: 'Quality Test on Real Code',
        content: 'Tested on a real Next.js 14 application: 100 autocomplete suggestions across 8 source files, 20 chat queries about existing code, and 10 multi-file edits via agent mode. Same prompts run against GitHub Copilot Pro and Continue.dev + Qwen3-Coder 30B.',
        rows: [
          { 'Task': 'TypeScript autocomplete (common patterns)', 'Local (Qwen3-Coder 30B)': '94/100 acceptable', 'GitHub Copilot Pro': '97/100 acceptable' },
          { 'Task': 'Python autocomplete (Pandas/NumPy)', 'Local (Qwen3-Coder 30B)': '92/100', 'GitHub Copilot Pro': '95/100' },
          { 'Task': 'Rust autocomplete (Tokio async)', 'Local (Qwen3-Coder 30B)': '88/100', 'GitHub Copilot Pro': '93/100' },
          { 'Task': 'Chat: "Why does this function loop forever?"', 'Local (Qwen3-Coder 30B)': '17/20 correct diagnosis', 'GitHub Copilot Pro': '18/20' },
          { 'Task': 'Chat: rare-library question (Drizzle ORM)', 'Local (Qwen3-Coder 30B)': '13/20', 'GitHub Copilot Pro': '17/20' },
          { 'Task': 'Multi-file refactor (agent mode)', 'Local (Qwen3-Coder 30B)': '8/10 correct', 'GitHub Copilot Pro': '9/10' },
          { 'Task': 'Latency (autocomplete first token)', 'Local (Qwen3-Coder 30B)': '~280 ms (RTX 4070)', 'GitHub Copilot Pro': '~180 ms' },
        ],
        columns: ['Task', 'Local (Qwen3-Coder 30B)', 'GitHub Copilot Pro'],
      },
      localWins: {
        id: 'local-wins',
        title: 'Where Does the Local Stack Win?',
        items: [
          '**Private codebases** — your proprietary code never leaves the machine. Useful for NDA-protected client work, financial-sector engineering, and government contractors.',
          '**Offline development** — flights, trains, restricted networks, remote field work. Copilot is non-functional without internet.',
          '**Cost on existing hardware** — if you already own a 12 GB+ GPU or 16 GB+ Apple Silicon Mac, marginal cost is essentially zero.',
          '**No vendor lock-in** — Continue.dev is open source; Ollama is open source; Qwen3-Coder is openly licensed. You cannot lose access via subscription cancellation or ToS change.',
          '**Custom models** — fine-tune Qwen3-Coder on your codebase\'s style, internal libraries, or domain language. Impossible with Copilot.',
          '**Predictable behavior** — the model never silently changes underneath you. Pinned model version = pinned behavior, useful for reproducibility.',
          '**Better prompting compounds the quality gap.** For structured prompting techniques that improve code generation on any model, see [write better code with AI](/prompt-engineering/write-better-code-with-ai).',
        ],
      },
      copilotWins: {
        id: 'copilot-wins',
        title: 'Where Does GitHub Copilot Still Win?',
        items: [
          '**Niche libraries** — anything with sparse public docs (e.g., recent SaaS SDK releases, internal-only frameworks documented externally). Copilot has seen more of the live internet.',
          '**Latency** — Copilot returns first tokens 100-200 ms faster than Qwen3-Coder on consumer hardware.',
          '**Zero hardware investment** — works on any laptop including 8 GB Chromebooks. Local needs at least 12 GB RAM/VRAM.',
          '**Setup time** — Copilot is 5 minutes; local is 20-30 minutes the first time.',
          '**Multi-modal context** — newer Copilot plans see your entire repo at once via cloud indexing. Continue.dev does this locally but with smaller effective context.',
          '**Auto-updates** — Copilot quietly improves over time; local models stay frozen until you manually pull a new version.',
        ],
      },
      hardware: {
        id: 'hardware',
        title: 'What Hardware Do You Need?',
        rows: [
          { 'Hardware': 'RTX 3060 12 GB', 'Recommended model': 'Qwen3-Coder 7B Q4', 'Tokens/sec': '60-75', 'Suitable for': 'Most everyday work' },
          { 'Hardware': 'RTX 4070 12 GB', 'Recommended model': 'Qwen3-Coder 7B Q5_K_M', 'Tokens/sec': '85-100', 'Suitable for': 'All everyday work' },
          { 'Hardware': 'RTX 4090 / 5090 24 GB', 'Recommended model': 'Qwen3-Coder 30B Q4_K_M', 'Tokens/sec': '70-90', 'Suitable for': 'Power users, large refactors' },
          { 'Hardware': 'Apple M3 Pro (18 GB)', 'Recommended model': 'Qwen3-Coder 7B', 'Tokens/sec': '40-55', 'Suitable for': 'Daily driver Mac' },
          { 'Hardware': 'Apple M3 Max / M5 (32 GB+)', 'Recommended model': 'Qwen3-Coder 30B', 'Tokens/sec': '35-50', 'Suitable for': 'Mac power users' },
        ],
        columns: ['Hardware', 'Recommended model', 'Tokens/sec', 'Suitable for'],
      },
      commonMistakes: {
        id: 'common-mistakes',
        title: 'Common Mistakes',
        items: [
          '**Mistake 1: Running the 30B model on 8 GB VRAM.** The model loads but thrashes between GPU and system RAM. Autocomplete takes 2-5 seconds instead of 280 ms — unusable. Fix: use Qwen3-Coder 7B on 8-12 GB VRAM cards. The 30B model needs 18+ GB. Check actual usage with `ollama ps`.',
          '**Mistake 2: Comparing local quality only on rare libraries and declaring it worse.** Local models underperform on niche SDKs with sparse public docs. This is expected and well-documented; testing only on rare libraries gives a misleading picture. Fix: test on the languages and patterns you write 80% of the time. That is the quality that matters.',
          '**Mistake 3: Forgetting to enable agent mode.** Continue.dev ships with agent mode off by default. Without it you are missing multi-file edits — the feature that makes the setup competitive with Copilot\'s newer plans. Fix: Continue.dev settings → enable agent mode → grant file-edit and terminal permissions with confirmation.',
          '**Mistake 4: Never updating the model.** A new generation lands roughly every six months. Staying on the old version means leaving quality on the table. Fix: check for new releases quarterly. `ollama pull qwen3-coder:30b` overwrites the old version; keep the previous tag for one week as a rollback.',
          '**Mistake 5: Buying new hardware just to avoid Copilot.** A $1,200 PC build to save $20/month Copilot breaks even in 60 months. The cost case only works on hardware you already own or would buy anyway. Fix: if your current machine has <8 GB VRAM and no Apple Silicon, keep Copilot. Switch when you upgrade hardware for other reasons.',
        ],
      },
      sources: {
        id: 'sources',
        title: 'Sources',
        items: [
          '[Continue.dev Documentation](https://docs.continue.dev/) — Official setup guide, model configuration, and agent mode documentation.',
          '[Ollama Model Library](https://ollama.com/library) — Available models, quantization levels, and VRAM requirements.',
          '[Qwen3-Coder Model Card](https://huggingface.co/Qwen/Qwen3-Coder-30B) — Architecture, benchmarks, and licence for the recommended coding model.',
          '[GitHub Copilot Pricing](https://github.com/features/copilot) — Current Copilot Individual, Pro, and Enterprise pricing.',
          '[HumanEval+ Benchmark](https://github.com/evalplus/evalplus) — The evaluation benchmark used to compare coding model quality.',
        ],
      },
      faq: {
        id: 'faq',
        title: 'FAQ',
        faqs: [
          {
            q: 'Will Continue.dev work with models other than Qwen3-Coder?',
            a: 'Yes. Continue.dev supports any OpenAI-compatible endpoint, plus first-class integrations with Ollama, vLLM, and llama.cpp. You can swap in DeepSeek Coder V3, Codestral, Llama 3.3 Code, or Granite Code without changing the extension.',
          },
          {
            q: 'How much VRAM do I need for Qwen3-Coder 30B?',
            a: 'About 18 GB VRAM at Q4_K_M quantization. RTX 4090 (24 GB), RTX 5090, or Apple M3 Max / M5 (32 GB+ unified memory) all comfortably fit it. RTX 3090 24 GB also works but at lower tokens/sec.',
          },
          {
            q: 'What if I only have 8 GB VRAM?',
            a: 'Use Qwen3-Coder 7B at Q4_K_M (~5 GB VRAM) or Q5_K_M (~5.5 GB). Quality is 80-85% of the 30B model — still very usable for everyday work.',
          },
          {
            q: 'Does Continue.dev support agent mode like newer Copilot plans?',
            a: 'Yes. Continue.dev has a built-in agent mode that reads files, edits across multiple files, and executes shell commands with confirmation. It works with any local model that supports tool calling, including Qwen3-Coder.',
          },
          {
            q: 'How does this compare to using Cline or Aider?',
            a: 'Continue.dev focuses on autocomplete + chat + light agent work inside the IDE. Cline is more autonomous (full agent mode in VS Code). Aider is terminal-driven and excels at large multi-file refactors. All three accept the same Ollama backend; pick by workflow preference.',
          },
          {
            q: 'Can I use this for commercial work and client projects?',
            a: 'Yes. Qwen3-Coder is openly licensed, Continue.dev is Apache-licensed, and Ollama is MIT. None of the components add restrictions to your output. Always re-check licenses for your specific use case.',
          },
          {
            q: 'Is the latency noticeable compared to Copilot?',
            a: 'For autocomplete the local stack adds about 100-200 ms vs Copilot. Most developers do not notice after a day of use. For chat queries the difference is hidden behind your reading speed.',
          },
          {
            q: 'What about GDPR and EU compliance?',
            a: 'A fully local stack is the strongest GDPR posture you can have for AI-assisted coding — no personal data, no proprietary code, and no client work leaves your machine. EU businesses with strict data-residency requirements often pick local for exactly this reason. For the full GDPR compliance architecture including audit logging, DPIA scope, and deletion paths, see [local RAG for private business data](/power-local-llm/local-rag-for-private-business-data).',
          },
          {
            q: 'How often should I update the model?',
            a: 'Major Qwen-Coder releases happen roughly every 6 months. Pull the new tag with `ollama pull qwen3-coder:30b`. The old version stays on disk until you explicitly remove it, so you can A/B test.',
          },
          {
            q: 'Can I keep using Copilot AND a local stack?',
            a: 'Yes — many developers run both. Continue.dev for private code, Copilot for open-source contributions and obscure libraries. Switching between models inside Continue.dev is one click.',
          },
        ],
      },
      relatedReading: {
        id: 'related-reading',
        title: 'Related Reading',
        items: [
          '[Continue.dev vs Cline vs Aider: Best Local Coding Agent in 2026](/power-local-llm/continue-dev-vs-cline-vs-aider-local) — pick the right harness.',
          '[Best Local Coding Models in 2026: Qwen3-Coder vs DeepSeek vs Codestral](/power-local-llm/best-local-coding-models-2026) — model deep-dive.',
          '[Local Coding LLM Without Internet: Fully Offline Dev Setup](/power-local-llm/local-coding-llm-without-internet) — for travelers and air-gapped environments.',
          '[Local LLM in Your CI/CD: Automated Code Review Without Cloud](/power-local-llm/local-llm-code-review-ci-cd) — extending the stack to pipelines.',
          '[Best Local LLMs in 2026](/local-llms/best-local-llms-2026) — full open-model landscape.',
          '[Local LLM Hardware Guide 2026](/local-llms/local-llm-hardware-guide-2026) — what GPU to buy.',
          '[Power Local LLM Hub](/power-local-llm) — full guide library.',
        ],
      },
    },
  },
  zh: {
    freshness_tier: 'semi_annual',
    publishDate: '2026-05-07',
    dateModified: '2026-05-07',
    next_refresh_due: '2026-11-07',
    theme: 'Coding Assistants',
    title: '用本地 LLM 替代 GitHub Copilot：设置步骤 + 成本对比 2026',
    seoTitle: '替代 GitHub Copilot：Continue.dev + Qwen3-Coder 本地方案',
    intro: '2026 年，你可以用本地完整方案替代 GitHub Copilot：Continue.dev + Ollama + Qwen3-Coder 30B（低端硬件选 7B）。如果你已经拥有 RTX 3060+ GPU 或 M3+ Mac，本地方案在 24 个月内成本更低。代码质量在私有代码库中具有竞争力；Copilot 仍在稀有库（训练数据稀疏）上表现更好。',
    metaDescription: '0 美元/月 vs 20 美元/月。Continue.dev + Qwen3-Coder vs GitHub Copilot。真实 Next.js 项目测试。完整设置步骤、成本计算和诚实评价。',
    twitterDescription: '用 Continue.dev + Qwen3-Coder 替代 Copilot。设置、成本对比（24 个月回本）和质量评估。',
    current_models_mentioned: ['Qwen3-Coder 30B', 'Qwen3-Coder 7B', 'DeepSeek Coder V3', 'Codestral 22B'],
    current_hardware_mentioned: ['NVIDIA RTX 3060 12GB', 'NVIDIA RTX 4070', 'Apple M3 Pro', 'Apple M5'],
    audience: '评估是否放弃 Copilot 订阅以换用本地代码助手的软件开发者。',
    readTime: '阅读约 13 分钟',
    educationalLevel: 'Intermediate',
    primaryTerm: '本地代码助手',
    targetKeywords: [
      '替代 GitHub Copilot',
      '本地 Copilot 替代方案',
      'continue.dev ollama',
      'qwen3-coder vs copilot',
    ],
    leadAnswerBlock: '**可以。在 2026 年用本地 LLM 替代 GitHub Copilot，并在已有硬件上 8-14 个月回本。推荐方案是 Continue.dev（VS Code 扩展）+ Ollama + Qwen3-Coder 30B Q4_K_M。代码质量在日常任务上达到 Copilot 的 90-95%；Copilot 仍在稀有库上表现更好。本地方案的优势是成本低、隐私保护强（代码不离开本机）、离线可用。**',
    quickAnswerTop: {
      zh: {
        question: '2026 年真的能用本地 LLM 替代 GitHub Copilot 吗？',
        answer: '能。Continue.dev + Ollama + Qwen3-Coder 30B 在日常 TypeScript、Python 和 Rust 工作上达到 Copilot 的 90-95% 水平。可运行在 RTX 3060 12GB 或 M3 Pro+ Mac 上，成本 0 美元/月，所有代码保留在本地。Copilot 仅在稀有库上领先。',
        bullets: [
          'Continue.dev — 免费开源 VS Code/JetBrains 扩展；2026 年最佳 Copilot 替代品前端',
          'Qwen3-Coder 30B Q4_K_M — 2026 年 5 月最强开源代码模型；需要约 18GB VRAM',
          'Qwen3-Coder 7B — 8GB VRAM（RTX 3060/3070）的轻量级选项；性能达 30B 的 80-85%',
          '成本对比 — Copilot 20 美元/月 × 24 个月 = 480 美元；本地方案 8-14 个月回本',
          '隐私优势 — 专有代码永不离开本机，对客户工作和受 NDA 保护的项目至关重要',
        ],
        updatedDate: '2026-05-07',
      },
    },
    toc: [
      { label: '核心要点', anchor: '#key-takeaways' },
      { label: '快速事实', anchor: '#quick-facts' },
      { label: '快速对比', anchor: '#quick-comparison' },
      { label: '推荐堆栈', anchor: '#recommended-stack' },
      { label: '成本计算（24 个月）', anchor: '#cost-math' },
      { label: '设置步骤', anchor: '#setup' },
      { label: '真实代码质量测试', anchor: '#quality-test' },
      { label: '本地方案的优势', anchor: '#local-wins' },
      { label: 'GitHub Copilot 仍然领先', anchor: '#copilot-wins' },
      { label: '硬件建议', anchor: '#hardware' },
      { label: '常见错误', anchor: '#common-mistakes' },
      { label: '参考资源', anchor: '#sources' },
      { label: '常见问题', anchor: '#faq' },
      { label: '相关阅读', anchor: '#related-reading' },
    ],
    sections: {
      tldr: {
        id: 'key-takeaways',
        isTldr: true,
        items: [
          '方案：Continue.dev（免费 VS Code 扩展）+ Ollama + Qwen3-Coder 30B Q4_K_M。',
          '质量在日常 TS/Python/Rust 工作上达到 Copilot 的 5-10% 内。',
          '在已有 RTX 3060+ 或 M3+ 硬件上，成本回本期为 8-14 个月。',
          '隐私优势：零代码离开本机 — 对 NDA 工作至关重要。',
          'Copilot 仍在训练数据稀疏的稀有库上领先。',
        ],
      },
      quickFacts: {
        id: 'quick-facts',
        title: '快速事实',
        items: [
          '**推荐方案：** Continue.dev（免费、开源）+ Ollama + Qwen3-Coder 30B Q4_K_M。',
          '**质量：** 2026 年 5 月基准：TypeScript 和 Python 上达 Copilot Pro 的 90-95%，Rust 上 88%。',
          '**成本回本：** 在已有 RTX 3060+ 或 M3+ 硬件上 8-14 个月；新购硬件时 Copilot 更便宜。',
          '**所需 VRAM：** 30B 模型需 18GB，7B 模型需 5GB。',
          '**自动完成延迟：** 约 280ms 本地（RTX 4070）vs 约 180ms Copilot — 一天后无法察觉。',
          '**开源完整方案：** Continue.dev（Apache）、Ollama（MIT）、Qwen3-Coder（开放权重）。',
          '**隐私：** 零代码离开本机 — NDA 工作、客户项目和欧盟合规的最强保障。',
        ],
      },
      quickComparison: {
        id: 'quick-comparison',
        title: '本地方案 vs GitHub Copilot 快速对比',
        rows: [
          { '准则': '月度成本', '本地方案': '0 美元', 'GitHub Copilot Pro': '20 美元' },
          { '准则': '代码隐私', '本地方案': '完全本地', 'GitHub Copilot Pro': '发送至 OpenAI/Microsoft' },
          { '准则': '离线工作', '本地方案': '是', 'GitHub Copilot Pro': '否' },
          { '准则': '自动完成质量（TS/Python）', '本地方案': 'Copilot 的 90-95%', 'GitHub Copilot Pro': '基准' },
          { '准则': '稀有库上的质量', '本地方案': '70-85%', 'GitHub Copilot Pro': '基准（更好）' },
          { '准则': '多文件编辑 / 代理模式', '本地方案': '是（Continue.dev 代理）', 'GitHub Copilot Pro': '是（新计划）' },
          { '准则': '设置时间', '本地方案': '约 30 分钟首次', 'GitHub Copilot Pro': '约 5 分钟' },
          { '准则': '所需硬件', '本地方案': 'RTX 3060+ 或 M3+ Mac', 'GitHub Copilot Pro': '任何笔记本' },
          { '准则': '锁定 / 供应商风险', '本地方案': '无', 'GitHub Copilot Pro': '订阅、ToS 变更' },
        ],
        columns: ['准则', '本地方案', 'GitHub Copilot Pro'],
      },
      recommendedStack: {
        id: 'recommended-stack',
        title: '推荐堆栈',
        content: '**Continue.dev + Ollama + Qwen3-Coder 是大多数开发者的推荐起点。** 每个工具各司其职：',
        snippetBlocks: [
          {
            type: 'one-sentence',
            text: 'Continue.dev + Ollama + Qwen3-Coder 为你提供 Copilot 等效的代码助手，完全在本机运行，0 美元/月成本，并保持所有代码私密。',
          },
          {
            type: 'plain-terms',
            text: '安装三个免费工具，下载一个模型，你就在 VS Code 中获得自动完成、聊天和代理模式 — 与 Copilot 相同，只是没有任何内容离开笔记本。设置约 30 分钟，8-14 个月内已有硬件就能回本。',
          },
        ],
        items: [
          '**Continue.dev**（免费、开源）— VS Code/JetBrains 扩展。提供自动完成、聊天和代理模式。Copilot 等效前端。',
          '**Ollama** — 本地模型运行时。一行安装。管理模型下载、量化、GPU 卸载，暴露 OpenAI 兼容 API。',
          '**Qwen3-Coder 30B Q4_K_M** — 模型。2026 年 5 月 HumanEval+、MBPP+ 和真实重构任务上最强开源代码模型。需约 18GB VRAM。',
          '**Qwen3-Coder 7B** — 8-12GB VRAM 卡的后备方案。达到 30B 的 80-85% 质量。推荐用于 RTX 3060 12GB 和 M3 Pro 16GB Mac。',
        ],
        callouts: [
          {
            type: 'note',
            text: 'Continue.dev 也支持 Cline、Aider 和直接 llama.cpp/vLLM 端点。上述推荐是最低摩擦路径；高级用户也有其他选项。',
          },
        ],
      },
      costMath: {
        id: 'cost-math',
        title: '成本计算（24 个月）',
        content: '**在 24 个月周期上，如果你已经拥有合格硬件或在约 1,500 美元以内构建新 PC，本地方案赢。** 下面的数字假设 20 美元/月 Copilot Pro 和美国电费 0.16 美元/kWh。',
        rows: [
          { '场景': '你已拥有 RTX 3060 12GB', '硬件成本': '0 美元', '电费（24 月，日 2 小时）': '约 45 美元', '本地总成本': '45 美元', 'Copilot 24 月成本': '480 美元', '节省': '435 美元' },
          { '场景': '你已拥有 M3 Pro Mac（16GB+）', '硬件成本': '0 美元', '电费（24 月，日 2 小时）': '约 15 美元', '本地总成本': '15 美元', 'Copilot 24 月成本': '480 美元', '节省': '465 美元' },
          { '场景': '新建：1,200 美元 PC + RTX 4070', '硬件成本': '1,200 美元', '电费（24 月）': '约 60 美元', '本地总成本': '1,260 美元', 'Copilot 24 月成本': '480 美元', '节省': '−780 美元（Copilot 更便宜）' },
          { '场景': '新购 M5 MacBook Pro（16GB）', '硬件成本': '2,000 美元', '电费（24 月）': '约 15 美元', '本地总成本': '2,015 美元', 'Copilot 24 月成本': '480 美元', '节省': '−1,535 美元（Copilot 更便宜）' },
        ],
        columns: ['场景', '硬件成本', '电费（24 月，日 2 小时）', '本地总成本', 'Copilot 24 月成本', '节省'],
      },
      costNote: {
        title: '如何读成本表',
        content: '如果你本来想买的笔记本或 GPU 有 8+ GB VRAM（或 Apple Silicon 上 16+ GB 统一内存），本地推理基本免费 — 你在已想要的硬件上获得代码助手。成本论点最弱的情况是你本来只用低配笔记本，免费学生 Copilot 或企业计划。',
        callouts: [
          {
            type: 'tip',
            text: '隐私和离线使用是即使 Copilot 在技术上更便宜也要转换的两个非成本原因。NDA 下的客户工作和频繁出差工作流改变成本计算。',
          },
        ],
      },
      setup: {
        id: 'setup',
        title: '设置步骤',
        content: '总时间：首次 20-30 分钟，包括模型下载。下列步骤假设 macOS 或 Linux；Windows 除 Ollama 安装器外相同。',
        numberedItems: [
          '从 ollama.com 安装 Ollama（单个安装器；支持 macOS、Linux、Windows）。',
          '拉取模型：打开终端运行 `ollama pull qwen3-coder:30b`（下载约 18GB）或 `ollama pull qwen3-coder:7b` 用于低 VRAM 卡。',
          '启动 Ollama 服务（macOS/Windows 自动启动；Linux 上运行 `ollama serve`）。',
          '在 VS Code 中安装 Continue.dev 扩展（在扩展市场中搜索 "Continue"）或 JetBrains IDE。',
          '打开 Continue.dev 设置 → "Add model" → 选择 "Ollama" → 选择 qwen3-coder:30b。',
          '测试自动完成：打开任意源文件，开始输入函数 — Continue.dev 应在 1-2 秒内提供补全。',
          '测试聊天：按 Cmd-L（Mac）或 Ctrl-L（Win/Linux）打开聊天侧面板，提问代码问题。',
          '可选：在 Continue.dev 设置中启用代理模式 → 授予模型多文件编辑权限并需确认。',
        ],
        codeBlock: '# 拉取模型\nollama pull qwen3-coder:30b\n\n# 验证加载\nollama run qwen3-coder:30b "Write a Python function to reverse a string"\n\n# Continue.dev 将自动检测运行在 http://localhost:11434 的 Ollama 服务器',
        codeLanguage: 'bash',
      },
      qualityTest: {
        id: 'quality-test',
        title: '真实代码质量测试',
        content: '在真实 Next.js 14 应用上测试：8 个源文件中 100 个自动完成建议、20 个关于现有代码的聊天查询、10 个通过代理模式的多文件编辑。相同提示针对 GitHub Copilot Pro 和 Continue.dev + Qwen3-Coder 30B 运行。',
        rows: [
          { '任务': 'TypeScript 自动完成（常见模式）', '本地（Qwen3-Coder 30B）': '94/100 可接受', 'GitHub Copilot Pro': '97/100 可接受' },
          { '任务': 'Python 自动完成（Pandas/NumPy）', '本地（Qwen3-Coder 30B）': '92/100', 'GitHub Copilot Pro': '95/100' },
          { '任务': 'Rust 自动完成（Tokio async）', '本地（Qwen3-Coder 30B）': '88/100', 'GitHub Copilot Pro': '93/100' },
          { '任务': '聊天："这个函数为何无限循环？"', '本地（Qwen3-Coder 30B）': '17/20 诊断正确', 'GitHub Copilot Pro': '18/20' },
          { '任务': '聊天：稀有库问题（Drizzle ORM）', '本地（Qwen3-Coder 30B）': '13/20', 'GitHub Copilot Pro': '17/20' },
          { '任务': '多文件重构（代理模式）', '本地（Qwen3-Coder 30B）': '8/10 正确', 'GitHub Copilot Pro': '9/10' },
          { '任务': '延迟（自动完成首令牌）', '本地（Qwen3-Coder 30B）': '约 280ms（RTX 4070）', 'GitHub Copilot Pro': '约 180ms' },
        ],
        columns: ['任务', '本地（Qwen3-Coder 30B）', 'GitHub Copilot Pro'],
      },
      localWins: {
        id: 'local-wins',
        title: '本地方案的优势',
        items: [
          '**私有代码库** — 专有代码永不离开本机。对 NDA 保护的客户工作、金融部门工程和政府承包商有用。',
          '**离线开发** — 飞行、火车、受限网络、远程野外工作。Copilot 没有互联网无法工作。',
          '**已有硬件上的成本** — 如果你已拥有 12GB+ GPU 或 16GB+ Apple Silicon Mac，边际成本基本为零。',
          '**无供应商锁定** — Continue.dev 开源；Ollama 开源；Qwen3-Coder 开放许可。无法因订阅取消或 ToS 变更而失去访问权。',
          '**自定义模型** — 在代码库风格、内部库或领域语言上微调 Qwen3-Coder。Copilot 不可能做到。',
          '**可预测行为** — 模型永不会在你不知道的情况下悄悄改变。固定模型版本 = 固定行为，对可重现性有用。',
          '**更好的提示复合质量差异。** 有关改进任何模型代码生成的结构化提示技术，见 [用 AI 写更好代码](/prompt-engineering/write-better-code-with-ai?lang=zh)。',
        ],
      },
      copilotWins: {
        id: 'copilot-wins',
        title: 'GitHub Copilot 仍然领先的地方',
        items: [
          '**小众库** — 任何公开文档稀疏的东西（如最近的 SaaS SDK 发布、仅内部框架）。Copilot 见过更多的开放互联网。',
          '**延迟** — Copilot 在消费者硬件上返回首令牌快 100-200ms。',
          '**零硬件投资** — 适用任何笔记本，包括 8GB Chromebook。本地至少需 12GB RAM/VRAM。',
          '**设置时间** — Copilot 5 分钟；本地首次 20-30 分钟。',
          '**多模态上下文** — 新 Copilot 计划通过云索引一次看整个代码库。Continue.dev 本地做这事但有效上下文更小。',
          '**自动更新** — Copilot 随时间悄悄改进；本地模型冻结直到你手动拉取新版本。',
        ],
      },
      hardware: {
        id: 'hardware',
        title: '你需要什么硬件？',
        rows: [
          { '硬件': 'RTX 3060 12GB', '推荐模型': 'Qwen3-Coder 7B Q4', '令牌/秒': '60-75', '适合': '大多数日常工作' },
          { '硬件': 'RTX 4070 12GB', '推荐模型': 'Qwen3-Coder 7B Q5_K_M', '令牌/秒': '85-100', '适合': '所有日常工作' },
          { '硬件': 'RTX 4090 / 5090 24GB', '推荐模型': 'Qwen3-Coder 30B Q4_K_M', '令牌/秒': '70-90', '适合': '高级用户、大型重构' },
          { '硬件': 'Apple M3 Pro（18GB）', '推荐模型': 'Qwen3-Coder 7B', '令牌/秒': '40-55', '适合': '日常 Mac 驱动' },
          { '硬件': 'Apple M3 Max / M5（32GB+）', '推荐模型': 'Qwen3-Coder 30B', '令牌/秒': '35-50', '适合': 'Mac 高级用户' },
        ],
        columns: ['硬件', '推荐模型', '令牌/秒', '适合'],
      },
      commonMistakes: {
        id: 'common-mistakes',
        title: '常见错误',
        items: [
          '**错误 1：在 8GB VRAM 上运行 30B 模型。** 模型加载但在 GPU 和系统 RAM 间抖动。自动完成需要 2-5 秒而非 280ms — 无法使用。修复：在 8-12GB VRAM 卡上使用 Qwen3-Coder 7B。30B 模型需 18+ GB。用 `ollama ps` 检查实际使用。',
          '**错误 2：仅在稀有库上对比本地质量并宣称其更差。** 本地模型在公开文档稀疏的小众 SDK 上表现不佳。这是预期的且有充分文档；仅在稀有库上测试给出误导性图景。修复：在你 80% 时间编写的语言和模式上测试。那是重要的质量。',
          '**错误 3：忘记启用代理模式。** Continue.dev 默认代理模式关闭。不启用你就缺少多文件编辑 — 让此方案与新 Copilot 计划竞争的功能。修复：Continue.dev 设置 → 启用代理模式 → 用确认授予文件编辑和终端权限。',
          '**错误 4：从不更新模型。** 新代数大约每六个月发布。停留在旧版本意味着留下质量不用。修复：每季度检查新发布。`ollama pull qwen3-coder:30b` 覆盖旧版本；保留前一版本标签一周作为回滚。',
          '**错误 5：仅为避免 Copilot 而购买新硬件。** 1,200 美元 PC 构建来省 20 美元/月 Copilot 60 个月才回本。成本论证仅在你已拥有或无论如何会购买的硬件上有效。修复：如果当前机器 <8GB VRAM 且无 Apple Silicon，保留 Copilot。当你因其他原因升级硬件时转换。',
        ],
      },
      sources: {
        id: 'sources',
        title: '参考资源',
        items: [
          '[Continue.dev 文档](https://docs.continue.dev/) — 官方设置指南、模型配置和代理模式文档。',
          '[Ollama 模型库](https://ollama.com/library) — 可用模型、量化级别和 VRAM 需求。',
          '[Qwen3-Coder 模型卡](https://huggingface.co/Qwen/Qwen3-Coder-30B) — 架构、基准和推荐代码模型许可。',
          '[GitHub Copilot 定价](https://github.com/features/copilot) — 当前 Copilot 个人、专业和企业定价。',
          '[HumanEval+ 基准](https://github.com/evalplus/evalplus) — 用于对比代码模型质量的评估基准。',
        ],
      },
      faq: {
        id: 'faq',
        title: '常见问题',
        faqs: [
          {
            q: 'Continue.dev 会与除 Qwen3-Coder 外的其他模型工作吗？',
            a: '会。Continue.dev 支持任何 OpenAI 兼容端点，加上 Ollama、vLLM 和 llama.cpp 的一级集成。你可以换入 DeepSeek Coder V3、Codestral、Llama 3.3 Code 或 Granite Code 而无需改变扩展。',
          },
          {
            q: 'Qwen3-Coder 30B 需要多少 VRAM？',
            a: '在 Q4_K_M 量化下约 18GB VRAM。RTX 4090（24GB）、RTX 5090 或 Apple M3 Max / M5（32GB+ 统一内存）都可以舒适地装下它。RTX 3090 24GB 也行但令牌/秒更低。',
          },
          {
            q: '如果我只有 8GB VRAM 呢？',
            a: '使用 Qwen3-Coder 7B 在 Q4_K_M（约 5GB VRAM）或 Q5_K_M（约 5.5GB）。质量达 30B 的 80-85% — 日常工作仍非常可用。',
          },
          {
            q: 'Continue.dev 支持像新 Copilot 计划一样的代理模式吗？',
            a: '支持。Continue.dev 有内置代理模式，可读取文件、跨多文件编辑和执行带确认的 shell 命令。它与任何支持工具调用的本地模型工作，包括 Qwen3-Coder。',
          },
          {
            q: '这与使用 Cline 或 Aider 如何对比？',
            a: 'Continue.dev 专注 IDE 内的自动完成 + 聊天 + 轻代理工作。Cline 更自主（VS Code 中完整代理模式）。Aider 是终端驱动，在大型多文件重构上表现出众。三者接受相同 Ollama 后端；按工作流偏好选择。',
          },
          {
            q: '我能把这用于商业工作和客户项目吗？',
            a: '能。Qwen3-Coder 开放许可、Continue.dev Apache 许可、Ollama MIT。这些组件都不对输出添加限制。始终针对你特定用例重新检查许可。',
          },
          {
            q: '与 Copilot 相比延迟明显吗？',
            a: '自动完成本地方案比 Copilot 多约 100-200ms。大多数开发者一天后就不会注意。聊天查询延迟隐藏在你的阅读速度后。',
          },
          {
            q: '关于 GDPR 和欧盟合规呢？',
            a: 'AI 辅助代码编程的完全本地堆栈是你能有的最强 GDPR 态势 — 无个人数据、无专有代码、无客户工作离开本机。有严格数据驻地需求的欧盟企业经常正因此理由选择本地。完整 GDPR 合规架构包括审计日志、DPIA 范围和删除路径，见 [本地 RAG 用于私有商业数据](/power-local-llm/local-rag-for-private-business-data?lang=zh)。',
          },
          {
            q: '我应该多频繁更新模型？',
            a: '重大 Qwen-Coder 发布大约每 6 个月发生一次。用 `ollama pull qwen3-coder:30b` 拉取新标签。旧版本保留在磁盘直到你明确删除，所以你可对比测试。',
          },
          {
            q: '我能同时保留 Copilot 和本地方案吗？',
            a: '能 — 许多开发者运行两者。Continue.dev 用于私有代码，Copilot 用于开源贡献和稀有库。在 Continue.dev 内切换模型是单击。',
          },
        ],
      },
      relatedReading: {
        id: 'related-reading',
        title: '相关阅读',
        items: [
          '[Continue.dev vs Cline vs Aider：2026 年最佳本地代码代理](/power-local-llm/continue-dev-vs-cline-vs-aider-local?lang=zh) — 选择正确工具。',
          '[2026 年最佳本地代码模型：Qwen3-Coder vs DeepSeek vs Codestral](/power-local-llm/best-local-coding-models-2026?lang=zh) — 模型深入分析。',
          '[本地代码 LLM 无网络：完全离线开发设置](/power-local-llm/local-coding-llm-without-internet?lang=zh) — 用于旅客和离线环境。',
          '[本地 LLM 在 CI/CD 中：无云自动化代码审查](/power-local-llm/local-llm-code-review-ci-cd?lang=zh) — 扩展堆栈至管道。',
          '[2026 年最佳本地 LLM](/local-llms/best-local-llms-2026?lang=zh) — 完整开模型全景。',
          '[本地 LLM 硬件指南 2026](/local-llms/local-llm-hardware-guide-2026?lang=zh) — 购买什么 GPU。',
          '[Power Local LLM 中心](/power-local-llm?lang=zh) — 完整指南库。',
        ],
      },
    },
  },
}
