import type { AboutCopy } from './types'

export const zh: AboutCopy = {
  kicker: '关于 PromptQuorum',
  h1: '开放权重与开源 AI 的发现引擎。',
  heroLead:
    'PromptQuorum 帮你在自己的硬件上私密地运行 AI，而不是向云服务商租用：一个收录 {{appCount}} 款本地 AI 应用的目录、一个涵盖九种语言、共 {{articleCount}} 篇文章的知识库，以及一款可以让多个模型并排比较的免费应用。',
  heroSub:
    '开放权重与开源模型很容易下载，但该用哪个应用、你的硬件能否运行、又该如何配置，仍然是难题。PromptQuorum 填补的正是这一空白。',
  heroOpenWeightNote:
    '"开放权重"（open-weight）是指训练好的模型文件本身——而不只是周边代码——可以自由下载并在任何地方运行，这与 GPT、Gemini 等只能在厂商自己服务器上运行的闭源模型不同。',
  heroOpenWeightLinkLabel: '开放权重 vs 开源，一文说清',
  ctaDirectory: '浏览目录',
  ctaHardware: '我的硬件能运行什么？',
  ctaEcosystem: '各部分如何协同运作',
  ctaMcp: '通过 MCP 连接',
  wavesH2: '从模型到应用：开放 AI 的三次浪潮',
  wavesLead: '开放权重与开源 AI 的发展经历了三次浪潮，每一次都解决了一个问题，也带出了下一个问题。',
  waves: [
    {
      n: '第一波',
      title: '模型',
      solved: '让 AI 可以下载。',
      text: '开放权重与开源模型（Llama、Qwen、Mistral、Gemma、DeepSeek 等数百种）已经从研究成果变成任何人都能下载的文件，Hugging Face 就是它们的聚集地。',
      catch: '模型文件本身无法回答问题。',
      product: 'Hugging Face',
    },
    {
      n: '第二波',
      title: '运行环境',
      solved: '让模型可以运行。',
      text: 'Ollama、LM Studio 和 llama.cpp 把下载好的文件变成了在你自己电脑上运行的模型：输入提示词，即可获得答案。',
      catch: '使用方式仍然局限：对大多数人来说，这只是一个聊天窗口，很多人也就止步于此。',
      product: 'Ollama & LM Studio',
    },
    {
      n: '第三波',
      title: '应用',
      solved: '让本地 AI 真正有用。',
      text: '构建在其之上的应用：与你的文档对话、在编辑器里编程、运行智能体、语音转录与合成、生成图像和视频、实现家居自动化。它们可以直接调用模型，也可以通过 Ollama、LM Studio 等接口调用。',
      catch: '这类应用有成百上千个，散落在 GitHub 的 README、Discord 讨论帖和更新日志里，大多是英文写就，而且很快就会过时。',
      product: '应用',
    },
  ],
  theCatchLabel: '问题在于：',
  waveHighlightBadge: '这正是 PromptQuorum 发挥作用的地方',
  wavesClosing:
    '模型是引擎，运行环境负责启动引擎，应用才是人们真正驾驶的部分。PromptQuorum 就是第三次浪潮的地图、说明书和试驾体验。',
  believeH2: '为什么选择本地：我们的信念',
  believeQuoteTitle: '互联网应该是开放的，AI 也应该开放。',
  believeQuotePre:
    '互联网之所以变得有用，是因为任何人都可以在上面发布内容，任何人都可以阅读，而且没有哪一家公司能决定你可以做什么。AI 正处在同样的分岔路口：它既可以是从少数几家供应商那里租用的东西，也可以是你自己拥有并运行的东西。',
  believeQuoteBold: '我们相信，本地 AI 是更好的选择',
  believeQuotePost:
    '——这对于大多数长期重要的用途而言都成立：花费多少、由谁掌控、谁能看到你的数据，以及明年它是否依然存在。',
  beliefs: [
    ['本地模型是开放的。', '你可以下载权重文件，并在自己的硬件上运行。没有人需要批准你的提示词，也没有人夹在你和模型之间。'],
    ['成本始终由你掌控。', '一旦模型在你自己的电脑上运行，就不再有计量收费、按 token 计费的账单，也不会有你没同意过的涨价。硬件就是成本，花多少钱由你决定。'],
    ['它不会被夺走。', '云端模型可能一夜之间被修改、限制、涨价或下线。而你已经下载的模型，只要文件还在，就会一直以同样的方式运行下去。'],
    ['你的数据始终留在你手中。', '当应用和模型都在本地运行时，你的提示词和文档永远不会离开你的电脑。'],
    ['独立自主才是关键。', '本地 AI 不只是更便宜的替代方案，更是一种不必依赖他人条款、服务器或决定的方式。'],
  ],
  believeClosing:
    '摆脱受制于人，是这个网站上所有内容的共同主题：这也是为什么目录保持中立、每个条目都链接到官方来源、以及我们用九种语言发布内容的原因。',
  believeItalic:
    '我们并不认为云端 AI 不好。我们相信，你应该拥有真正的选择权，而选择本地 AI 应该和选择云端 AI 一样简单。',
  ecosystemH2: '一个生态系统，四个协同运作的部分',
  ecosystemLead:
    'PromptQuorum 不只是一款应用，也不只是一个目录，而是围绕同一个目标构建的四个部分，让你无需离开这个网站，就能从“我该运行什么？”一路走到实际可用的配置。',
  connectsLabel: '与其他部分的联动：',
  findLabel: '查找',
  learnLabel: '学习',
  useLabel: '使用',
  askLabel: '询问',
  partFindTitle: '本地 AI 目录',
  partFindOneLiner: '可检索、结构化的本地 AI 软件地图。',
  partFindBody:
    '和用自由文本堆出来的"最佳 AI 应用"榜单不同，这里的 {{appCount}} 款本地 AI 应用——分布在 {{groupCount}} 个分组、{{categoryCount}} 个类别中——全部使用同一套结构化字段描述：功能、支持平台、许可证、价格和硬件需求，并附有官方网站链接。正是这种统一结构让条目之间可以互相比较，也支撑了硬件匹配功能：设置一次硬件配置，每款应用都会显示在你的电脑上能流畅运行、勉强运行，还是无法运行。',
  partFindConnects: '各条目会链接到对应的 PromptQuorum 评测和使用指南（如果已有的话）。',
  partLearnTitle: '知识库',
  partLearnOneLiner: '每一条推荐背后的操作指南库。',
  partLearnBody:
    '{{articleCount}} 篇文章：涵盖硬件（VRAM、Apple Silicon、GPU、纯 CPU 方案）、软件、模型、量化、RAG、智能体、语音、提示词工程，以及完整本地 AI 技术栈的指南、评测与对比。面向想要一套真正能用的方案的人，而不是理论说教。',
  partLearnConnects: '评测和对比文章会链接回它们所涉及的目录条目。',
  partUseTitle: 'PromptQuorum 应用',
  partUseOneLiner: '并排比较多个模型的回答。',
  partUseBody:
    '一款免费的多模型应用，目前处于测试阶段。将同一条提示词发送给多个模型（包括本地模型），查看它们的回答在哪些地方一致、哪些地方相互矛盾。意见一致是一个有用的信号，但并非证明。你使用自己的密钥和模型。你发送的内容不会经过任何 PromptQuorum 服务器，应用本身也不会向我们回传任何数据。这也是 PromptQuorum 最初的起点。',
  partUseConnects: '它连接 Ollama 和 LM Studio（两者均已收录在目录中），让本地模型与云端模型并列呈现。',
  partAskTitle: 'MCP 服务器',
  partAskOneLiner: '让你自己的 AI 助手直接查询 PromptQuorum。',
  partAskBody:
    '面向 Model Context Protocol 的公开只读服务器。Claude、Cursor 以及任何支持 MCP 的助手都可以借此搜索目录、获取应用详情、阅读指南并解释许可证。无需账号，也无需 API 密钥。这样一来，当你的 AI 回答有关本地 AI 的问题时，就能引用 PromptQuorum 的内容，而不是凭空猜测。',
  partAskConnects: '它读取的目录和指南与本网站完全相同，因此你的助手所依据的信息来源与你自己看到的一致。',
  ctaOpenDirectory: '打开目录',
  ctaReadGuides: '阅读指南',
  ctaAboutApp: '关于这款应用',
  ctaSeeHowToConnect: '查看连接方法',
  practiceH3: '实际使用流程',
  practiceIntro: '假设你有 16 GB RAM，想要离线与自己的 PDF 文档对话。',
  practiceSteps: [
    '在目录中设置你的硬件配置，选择“与文档对话”这一使用场景，每款应用都会显示它能否在你的电脑上流畅运行。',
    '打开你中意的应用的评测，以及它所需运行环境（例如 Ollama 或 LM Studio）的使用指南。',
    '用本地模型运行它。如果你想看看不同模型如何回答同一个问题，可以使用 PromptQuorum 应用。',
    '或者跳过这些浏览步骤，直接连接 MCP 服务器，把同样的问题交给你自己的 AI 助手。',
  ],
  forYouH2: '从目标出发，而不是从产品名称出发',
  forYouLead:
    '你不需要事先知道“llama.cpp”或“Open WebUI”这些名字的存在，也能找到它们。从你想做的事情开始：',
  goals: [
    '我想在笔记本电脑上使用私密的 ChatGPT 替代品。',
    '我有 16 GB RAM，实际上能运行什么？',
    '我想离线与自己的 PDF 文档对话。',
    '我需要一个用于 VS Code 的本地编程助手。',
    '我想为智能家居配备一个离线语音助手。',
  ],
  ctaBrowse: '按使用场景浏览',
  ctaSetHardware: '设置我的硬件配置',
  forYouIfH3: '如果你符合以下情况，PromptQuorum 就是为你准备的……',
  forYouList: [
    '你安装了 Ollama 或 LM Studio，聊了一段时间后，开始好奇还能用它做什么。',
    '你想要私密、可离线使用、不需要再订阅一个服务的 AI。',
    '你正在挑选本地 AI 软件，希望在同一个地方看到所有选项的统一信息。',
    '你开发或维护一款本地 AI 工具，希望它有一个准确的条目。',
    '你使用英语以外的语言阅读，对只有英文版的安装指南感到厌倦。',
    '你希望自己的 AI 助手能依据一个持续维护的信息来源，回答有关本地 AI 的问题。',
  ],
  notForYouH3: '如果你符合以下情况，它可能就不适合你……',
  notForYouText: '你只需要一个托管的聊天机器人，不在乎它在哪里运行。云端 AI 是很好的工具，我们只是专注于另一条路径。',
  neutralH2: '中立是设计原则',
  neutralLead: '参考资料只有在值得信赖时才有用。以下规则适用于每一个页面：',
  neutral: [
    ['编辑独立，而非付费。', '目录中的收录与排序靠实力赢得，任何公司都无法花钱买到更靠前的位置。'],
    ['每个条目格式统一。', '一个人独立维护的项目，与获得风投支持的项目，页面结构完全相同。'],
    ['始终链接官方来源。', '每个条目都链接到该工具自己的官方网站。'],
    ['评测状态公开透明。', '每个条目都有一个 PromptQuorum 评测板块。如果尚未评测，页面会明确标注“尚未评测”，而不是掩盖这一空白。'],
    ['创始人提供的信息会被标注。', '当工具的开发者补充说明时，页面会清楚标明这是由开发者提供的内容。'],
    ['欢迎指正。', '目录中的数据可能会过时。任何人，尤其是开发者本人，都可以通过 hello@promptquorum.com 报告错误。'],
    ['收录标准公开透明。', '我们收录的都是拥有正规官网、且在过去六个月内有更新的真实应用，重点关注本地 LLM 使用场景。'],
  ],
  languagesH2: '从一开始就支持九种语言',
  languagesLead: '本地 AI 是一场全球性的浪潮，但与之相关的大多数信息都只有英文版本。PromptQuorum 用九种语言发布内容：',
  languagesClosing: '这意味着无论是在圣保罗、首尔还是利雅得，人们都能用自己的语言，找到同样结构清晰的答案。',
  languagesPhilosophy: '这不是事后补上的翻译。大多数关于本地 AI 的知识都是先用英文写成，其他语言即便有，也往往是后来才补上的——这恰恰把最能从在自己硬件上运行模型中受益的人排除在外。我们认为，AI 应该是属于全世界的技术，而不是一项让全世界去适应的英语技术，因此每一篇文章从一开始就以读者自己的语言发布。',
  mcpH2: '在你的 AI 中使用 PromptQuorum',
  mcpLead: '只需将 PromptQuorum 连接到你的助手一次，它就能替你查找信息。',
  mcpFirstClaim:
    'PromptQuorum 是首个发布公开、无需身份验证 MCP 端点的 AI 应用目录。只需连接一次，任何兼容 MCP 的助手——Claude、ChatGPT、Cursor 等——都能直接在你的对话中查询 PromptQuorum 的应用数据库、许可证信息和文章内容，无需在多个标签页之间来回复制粘贴。',
  mcpBenefit:
    '这些数据不只是被读取，而是成为你的助手可以进行推理的输入。它会把 PromptQuorum 返回的内容，与自身知识、对话中的其他文件以及正在进行的网络搜索结合起来，在同一个回答里给出结果。具体来说，你可以：',
  mcpExample:
    '举个例子：问"哪些本地 AI 应用能在 16 GB 内存下运行，并且可以跟 PDF 对话？"，你的助手会直接查询 PromptQuorum 的目录和知识库，然后给出具体的应用名称，附带许可证和硬件适配情况——而不是凭可能已经过时的训练数据去猜测。',
  mcpBullets: [
    '无需离开对话，直接比较 PromptQuorum 评测过的应用，并继续追问细节',
    '对照你的使用场景核实工具的许可证，数据直接引用自 PromptQuorum',
    '将 PromptQuorum 的硬件要求，与你自己的配置或上传的文档进行比对',
    '把 PromptQuorum 的目录数据，融入助手正在进行的更广泛的网络调研中',
  ],
  mcpEndpointLabel: 'MCP 端点：',
  mcpEndpointNote: '（公开、只读、无需身份验证）',
  mcpManifestLabel: '发现清单：',
  mcpToolsLabel: '可用工具：',
  ctaMcpGuide: '完整的 MCP 配置指南',
  founderH2: '由谁打造',
  founderImgAlt: 'Hans Küpper，PromptQuorum 创始人',
  founderTitle: 'PromptQuorum 创始人',
  founderBioP1:
    'PromptQuorum 最初是一款多模型应用。Hans 之所以开发它，是因为单一 AI 给出的答案很难验证。向多个模型提出同一个问题，至少可以看出它们在哪里达成一致、在哪里出现分歧。',
  founderBioP2:
    '在开发这款应用的过程中，一个更大的空白浮现出来：想要可靠、私密 AI 的人，却没有一份值得信赖的本地 AI 世界地图。于是这款应用逐渐发展成了一个生态系统，目录、知识库和 MCP 服务器都指向同一个目标。',
  founderBioP3: '隐私与用户掌控权，是不容妥协的设计原则。',
  founderBioSmall: '独立运营，总部位于德国。拥有 30 多年咨询与综合管理经验，足迹遍及 20 多个国家。',
  roadmapH2: '未来的方向',
  roadmapLead:
    'AI 的运行方式正在改变：从纯云端，转向云端、本地、混合与边缘并存的格局。PromptQuorum 正是为这一转变而打造。路线图包括：',
  roadmap: [
    ['创始人认证：', '工具开发者可以确认并补充自己的条目内容。'],
    ['全站硬件感知：', '你的硬件配置将在每一个提到该工具的页面上显示兼容性，而不仅仅是在目录页面中。'],
    ['精选视频：', '为每款应用附上最佳的实操演示视频。'],
    ['云端 ↔ 本地配对：', '为每个云服务标注对应的本地替代方案，反之亦然。'],
  ],
  roadmapClosing:
    '目标是：无论是人还是 AI，当他们问出“我该如何使用开放权重与开源 AI？”这个问题时，PromptQuorum 都会是他们可以信赖的答案来源。',
  involvedH2: '参与其中',
  foundersLabel: '创始人与开发者：',
  foundersText: '让你的工具获得收录、更正你的条目信息，或添加创始人说明：',
  pressLabel: '媒体与合作：',
  followLabel: '关注我们：',
  breadcrumbHome: '首页',
  breadcrumbAbout: '关于我们',
}
